### ISSUE TITLE
0.1 errors when opening VSCode

### ISSUE THREAD

**Issue by DavSanchez** [haskell/haskell-language-server#101]
Hi guys!

Congratulations for this project. Hope it becomes the tool of our dreams to work with Haskell!

I'm trying `haskell-language-server` and I have encountered this issue, where it returns an error about not finding the module and there is a "Processing 1/2" indicator at the status bar that won't finish, as in the image below.

<img width="682" alt="Screenshot 2020-05-09 at 03 05 39" src="https://user-images.githubusercontent.com/11422515/81461311-cab7e400-91a2-11ea-9c7e-f4e59e733138.png">

Obviously it's not working. Hover, formatting... nothing. It's just stuck there.

The instructions done to install this were:

```bash
git clone https://.../haskell/haskell-language-server.git --recurse-submodules
cd haskell-language-server
git checkout 0.1
stack ./install.hs hls-8.8.3
```

The settings for VSCode are only:

```json
{
  "languageServerHaskell.formattingProvider": "ormolu",
  "languageServerHaskell.hieVariant": "haskell-language-server"
}
```

And the project itself is one generated with `stack new <template>`, unmodified apart from setting a git repo.

What could this be? Am I doing something wrong? Thanks in advance!

**Comment by Avi-D-coder** [comment]
This is unfortunately expected behavior for the time being. #88 is not yet ready for use.

For the time being please install and run [implicit-hie](https://github.com/Avi-D-coder/implicit-hie).
It will generate an `hie.yaml` config file and everything will work.

PS: I will be discussing getting hie/hls/ghcide installed and working with cabal and stack on the weekly haskell video chat at 5 PM UTC tomorrow(Saturday).

**Comment by fendor** [comment]
@DavSanchez Can you please post the full log? Imo, this is *not* expected behaviour.
Also, as a quicker work-around to this problem, you may write a `hie.yaml` file. A rought introduction: https://github.com/haskell/haskell-ide-engine#project-configuration

For a simple stack project, a `hie.yaml` with the contents:
```yaml
cradle:
  stack:
```
should suffice.

**Comment by DavSanchez** [comment]
Ah, I had a `hie.yaml` created from the available ones from this repo, and I just realised I had left an uncommented path and component there that was not present in my project structure (was referring to `haskell-language-server` component, from the original file). Now the process unstuck and it works, sorry!

Just in case it gives you any more information you can use, the log is the following:

> [client] run command = "haskell-language-server-wrapper --lsp"
[client] debug command = "haskell-language-server-wrapper --lsp"
ghcide version: 0.1.0.0 (GHC: 8.8.3) (PATH: /.../.local/bin/haskell-language-server-wrapper) (GIT hash: 019b02831595b6a3be6776bfc56060ab918876e7)
ghcide version: 0.1.0.0 (GHC: 8.8.3) (PATH: /.../.local/bin/haskell-language-server-8.8.3) (GIT hash: 019b02831595b6a3be6776bfc56060ab918876e7)
Starting (haskell-language-server)LSP server...
  with arguments: Arguments {argLSP = True, argsCwd = Nothing, argFiles = [], argsVersion = False, argsShakeProfiling = Nothing, argsTesting = False, argsExamplePlugin = False, argsDebugOn = False, argsLogFile = Nothing, argsThreads = 1}
  with plugins: [PluginId "brittany",PluginId "floskell",PluginId "ghcide",PluginId "ormolu",PluginId "pragmas"]
If you are seeing this in a terminal, you probably should have run ghcide WITHOUT the --lsp option!
 Started LSP server in 0.00s
2020-05-09 18:10:52.393533 [ThreadId 9] - Opened text document: file:///.../htgeobot/src/Lib.hs
Consulting the cradle for "/.../htgeobot/src/Lib.hs"
> Error parsing targets: Unknown local package: haskell-language-server
> Note that to specify options to be passed to GHCi, use the --ghci-options flag
2020-05-09 18:10:52.786702 [ThreadId 44] - Plugin.makeCodeLens (ideLogger)
> /.../htgeobot/.stack-work/install/x86_64-osx/e65fb45fb2f681541018788623ee2651c5c0fbe15135afc7c7153784047a1a27/8.8.3/pkgdb:/.../.stack/snapshots/x86_64-osx/e65fb45fb2f681541018788623ee2651c5c0fbe15135afc7c7153784047a1a27/8.8.3/pkgdb:/.../.stack/programs/x86_64-osx/ghc-8.8.3/lib/ghc-8.8.3/package.conf.d
haskell-language-server-8.8.3: CradleError (ExitFailure 1) ["Failed to parse result of calling stack","Error parsing targets: Unknown local package: haskell-language-server","Note that to specify options to be passed to GHCi, use the --ghci-options flag"]

The ... stands for my $HOME directory.

Thanks!
