### ISSUE TITLE
Retrie plugin

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#103]
http://hackage.haskell.org/package/retrie 

Retrie is a modern alternative to HaRe, and possibly better maintained as it is used by Facebook.

It can be used to implement refactorings like:

- Inline functions with `--unfold`
- Extract functions, with `--fold`
- Inline and extract type synonyms, with `--type-forward` and `--type-backward`

It could be also used to implement renames and moves, but those would require custom scripts.

**Comment by alanz** [comment]
Yes, I have been wanting to get to this.  And also wondering if it should not be used to make the changes from hlint.

**Comment by xich** [comment]
I'm not working on it myself, but happy to support anyone who does. I would love to see this happen!

@alanz Funny you mention hlint. That was the initial motivation for retrie, but I never got back around to doing the integration. I probably will at some point, if someone doesn't beat me to it.

**Comment by alanz** [comment]
ping @ndmitchell

**Comment by ndmitchell** [comment]
HLint uses the refactor data types - https://hackage.haskell.org/package/refact-0.3.0.2/docs/Refact-Types.html - so all that is required is someone to have those supported in retrie. Note that recently @zliu41 has been working to improve these, and there are some known bugs in apply-refact that we currently use to execute these replacements.

**Comment by xich** [comment]
The `Replace` constructor from `Refact.Types` would be quite easy to generate from retrie's writer type:

https://github.com/facebookincubator/retrie/blob/f54706a1c8e4f16ae39e540059cf4e2b33498d18/Retrie/Replace.hs#L86-L90

That is essentially how I do replacements in CPP files already:

https://github.com/facebookincubator/retrie/blob/99256ce6f97c40bb4f3211302a3381eed099ad5e/Retrie/Run.hs#L113

(`printCPP` splices them into the actual file)

**Comment by pepeiborra** [comment]
I have started working on Retrie integration in the branch https://github.com/pepeiborra/ide/tree/retrie

The branch relies on some upstream changes and therefore cannot be merged yet: https://github.com/facebookincubator/retrie/pull/9

**Comment by TomMD** [comment]
Looks like retrie has included @pepeiborra 's changes.  From the linked PR:

> Just released this as part of retrie-0.1.1.1

So... LGTM?

**Comment by pepeiborra** [comment]
I want to wait until https://github.com/facebookincubator/retrie/issues/10 lands before resuming this work

**Comment by xich** [comment]
Ah, sorry! Didn’t realize I was blocking you. I’m afk the next couple days, but once I’m back, let’s try to work out the details.
