### ISSUE TITLE
Add installation instructions

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#104]
The README does not include any information on how to install haskell-language-server and hook it into an LSP client. Am I missing something?

**Comment by Sir4ur0n** [comment]
Hi,

Seems to be a duplicate of https://github.com/haskell/haskell-language-server/issues/85

**Comment by alanz** [comment]
@pepeiborra the TLDR is it installs the same way as haskell-ide-engine.  I use

```bash
./cabal-hls-install hls-8.8.3
```

Then both emacs lsp-mode and vscode-hie-server now have a simple selector between hie, hls and ghcide.

**Comment by pepeiborra** [comment]
Thanks everyone. Should I close this in favor of #85?

**Comment by jneira** [comment]
I am porting the hie readme here. @pepeiborra yeah, if you dont mind i'll close it in favor of #85
