### ISSUE TITLE
Consider using a merge bot to make easier pr handling

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#1150]
* With last changes to pr policy we have to watch more closely pr's, to keep them in sync with master, as now it is required to pass checks against HEAD (and that is a good thing)
* There are several merge bots in github but we should choose one that update pr's branches auto:
  * dhall-haskell is using mergify (free for open source projects): https://mergify.io/
    * ~~not sure if it updates pr's branches auto~~It does it (including rebases)
  * bulldozer: it update branches for sure: https://github.com/palantir/bulldozer

//cc @alanz @pepeiborra (as you have admin rights to make it possible)

**Comment by pepeiborra** [comment]
I think you have admin rights now too @jneira

**Comment by jneira** [comment]
@pepeiborra yeah, a new brand world of options to break things badly 😝 
reviweing the project settings i've seen an option similar to the provided one by mergify and friends:

![imagen](https://user-images.githubusercontent.com/54035/103487113-353d2480-4e03-11eb-83b5-eea4f1b71c12.png)

It seems less poweful but integrated directly with github with no further configuration

**Comment by pepeiborra** [comment]
It's sure worth trying, although it doesn't seem that it's smart enough to keep PRs in sync with master
