### ISSUE TITLE
False compile error: conflicting family instance declarations

### ISSUE THREAD

**Issue by luntain** [haskell/haskell-language-server#1161]
I'm getting this error only when invoking haskell-language-server on both the files from the library and the executable that depends it. The instance is specified in my local library. Both the family and the type the instance is specified for are from a hackage package (not locally defined).

```
File:     /home/.../Http/Auth.hs
Hidden:   no
Range:    68:14-68:28
Source:   typecheck
Severity: DsError
Message: 
  Conflicting family instance declarations:
  AuthServerData (AuthProtect "UVA-Auth") = Credentials
  -- Defined at /home/.../Http/Auth.hs:68:15
  AuthServerData (AuthProtect "UVA-Auth") = Credentials
  -- Defined in module Http.Auth
Files that failed:
 * /home/.../Http/Auth.hs
```

I checked that this issue does not occur for orphan class instances (through defining Ord on (IO a)).

**Comment by pepeiborra** [comment]
Thanks for the report, but there are already two other issues for conflicting instances. Can you check if any of those duplicate your issue and close it?

**Comment by luntain** [comment]
These two seem to cover the issue.

https://github.com/haskell/haskell-language-server/issues/210
https://github.com/haskell/haskell-language-server/issues/773
