### ISSUE TITLE
Sticky diagnostics

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#1171]
I have seen a redundant import warning refusing to go away after clearing the import, and I believe this could well be an unintended consequence of haskell/ghcide#959

I haven't been able to reproduce it consistently, much less to create a failing test. Just recording it here as a known issue for now.

**Comment by wz1000** [comment]
I have also been seeing similar problems with typechecking errors sticking around after they should have been fixed since I rebased my hiedb branch a couple of days ago, but didn't report as I wasn't sure if it was my fault.
