### ISSUE TITLE
Rethink VFS handling

### ISSUE THREAD

**Issue by wz1000** [haskell/haskell-language-server#1172]
I think the way `VFSHandle` currently works leaves us vulnerable to race conditions and subtle inconsistencies, since the `VFS` maintained by `haskell-lsp` is updated asynchronously and independently of the shake graph. I think a better way to manage this with `lsp-1.0.0` would be to take VFS snapshots on file modification events using [`getVirtualFiles`](https://hackage.haskell.org/package/lsp-1.0.0.1/docs/Language-LSP-Server.html#v:getVirtualFiles), then use this to answer VFS queries for the current shake session.

**Comment by jneira** [comment]
@wz1000 thanks, do you suspect there are open issues related with?

**Comment by michaelpj** [comment]
I think you did this!
