### ISSUE TITLE
Upload to Hackage

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#1175]
Goal: `cabal install haskell-language-server` should just work

Minimum tasks required:

- [x] Change `all-plugins` and `all-formatters` to `default: False`, 
- [x] Change individual plugins flags to `default: True`
- [x] Change packaged plugin flags to `Manual: False`
- [x] (optional) Upload plugin to Hackage: explicit imports
- [x] (optional) Upload plugin to Hackage: retrie
- [x] (optional) Upload plugin to Hackage: eval 
- [x] (optional) Upload plugin to Hackage: hlint
- [ ] (optional) Upload plugin to Hackage: tactics
- [x] (optional) Upload plugin to Hackage: splice
- [x] (optional) Upload plugin to Hackage: class
- [x] (optional) Upload plugin to Hackage: haddock
- [x] Backport changes to release branch (tag: ghcide-0.7.0.0)
- [x] `cabal upload ...`

**Comment by pepeiborra** [comment]
Please upload your plugin to Hackage if you want to be available @tittoassini @isovector @Ailrun @jneira @konn @berberman

**Comment by konn** [comment]
When I implemented the Splice plugin, I factored out `Ide.TreeTransform`, which was part of the Tactics plugin, as a new package `hls-exactprint-utils`, since I need that functionality and their variants. Should I upload it as well?

**Comment by pepeiborra** [comment]
Yes, please do upload that too

**Comment by konn** [comment]
Thad package includes codes by @isovector and @TOTBWF plus some variants and generalisation of the underlying monad I implement and it also lacks a license (which is inherited from Tactics plugin). I think I have to discuss on these with @isovector and @TOTBWF.

**Comment by isovector** [comment]
I generally prefer BSD-style licenses, but am happy inheriting Apache 2.0 if it makes life easier.

**Comment by Ailrun** [comment]
Class plugin is now uploaded.

**Comment by konn** [comment]
> I generally prefer BSD-style licenses, but am happy inheriting Apache 2.0 if it makes life easier.

OK, then I will set it to Apache 2.0 and upload it to Hackage if @TOTBWF agrees.
Can I add @isovector (isovector on Hackage) and @TOTBWF (ReedMullanix on Hackage) as co-maintainers of `hls-exactprint-utils` after that? I think doing so makes situation smooth as Tactics plugin also depends on that package.

**Comment by isovector** [comment]
@konn just add me as the co-maintainer; @TOTBWF wasn't involved with that module.

**Comment by konn** [comment]
OK, so I will list I and you as a author/maintainer of hls-exactprint-utils, making pull-request for this, and upload to Hackage after it got merged!

**Comment by isovector** [comment]
Sounds good, thanks for taking the lead here!

**Comment by jneira** [comment]
As commented in irc and the[ other issue about uploading the package](https://github.com/haskell/haskell-language-server/issues/400#issuecomment-724606557), we should update the README to include the hackage method of installation, and warning about a caveat: the `haskell-language-server` executable will only works with the ghc used for installing it. `haskell-language-server-wrapper` is able to choose the correct hls+ghc version if the executable follow the convention of add the ghc version as suffix.
So users will have to set the correct hls version on path before opening the project or copy the executable following the convention required by the wrapper.

**Comment by berberman** [comment]
> Class plugin is now uploaded.

@Ailrun I found a little mistake in class plugin: https://github.com/haskell/haskell-language-server/blob/28d24d5d732d32b465381578f0fc2fa425df7b9d/plugins/hls-class-plugin/hls-class-plugin.cabal#L4

**Comment by Ailrun** [comment]
@berberman Oops... I will fix that.

**Comment by konn** [comment]
I've just uploaded `hls-exactprint-utils` and `hls-splice-plugin` also added @isovector to maintainers of `hls-exactprint-utils`.

**Comment by berberman** [comment]
`hls-haddock-comments-plugin` is uploaded.

**Comment by alanz** [comment]
I think we should update the Copyright, Author and Maintainer fields of the haskell-language-server.cabal file.

It is a collective entity.

IIRC, some projects have a file called CONTRIBUTORS, and copyright refers to that? As an idea.

And this can be dealt with as a separate issue, need not hold up releasing the candidate.

**Comment by pepeiborra** [comment]
Makes sense. Best to get it right before uploading. I'm not in a huge rush to upload anyway.

**Comment by jneira** [comment]
i've just upload hls-hlint-plugin: https://hackage.haskell.org/package/hls-hlint-plugin
i am thinking in adding @alanz and @ndmitchell as hackage maintaniners if they agree, someone else?

**Comment by jneira** [comment]
> 
> 
> I think we should update the Copyright, Author and Maintainer fields of the haskell-language-server.cabal file.
> 
> It is a collective entity.
> 
> IIRC, some projects have a file called CONTRIBUTORS, and copyright refers to that? As an idea.
> 
> And this can be dealt with as a separate issue, need not hold up releasing the candidate.

I've used this values in hls-hlint.plugin:

```cabal
author:        https://github.com/haskell/haskell-language-server/contributors
maintainer:    https://github.com/haskell/haskell-language-server/contributors
```

but i've kept `copyright: Alan Zimmerman`,not sure if you can put an url in that field, i guess you will need an invidual or an org, like `Haskell.org, Inc.` (i would use that one cause we are in it github organization)

**Comment by alanz** [comment]
Perhaps we should add an explicit contributors file, and manage it with something like https://allcontributors.org/

**Comment by alanz** [comment]
And technically the copyright is all contributors, not just me.

**Comment by jneira** [comment]
It would be nice to tag each package release like: https://github.com/haskell/haskell-language-server/releases/tag/hls-hlint-plugin-0.1.0.0
It lets users get the exact version quickly using git and see the history, etc.
To make easier the release process we could make ci doing the hackage releases automatically and a way to trigger them could be create those tags, following the convention ${packageName}-{version}.

**Comment by tittoassini** [comment]
So, is the plan to completely remove the plugins from the hls repository?

**Comment by jneira** [comment]
@tittoassini afaik not necessarily but this make it possible, 
Howeverthere are some issues with the test suite: https://github.com/haskell/haskell-language-server/issues/576

**Comment by tittoassini** [comment]
Should I set these fields in the eval plugin cabal? Has this been agreed?

author:        https://github.com/haskell/haskell-language-server/contributors
maintainer:    https://github.com/haskell/haskell-language-server/contributors

**Comment by jneira** [comment]
I used them in the hlint plugin and nobody disagreed

**Comment by tittoassini** [comment]
https://hackage.haskell.org/package/hls-eval-plugin-0.1.0.0

**Comment by tittoassini** [comment]
fixed link to README:

https://hackage.haskell.org/package/hls-eval-plugin

**Comment by jneira** [comment]
@pepeiborra is there some blocker to upload the package? should we upload tactic plugin?

**Comment by pepeiborra** [comment]
No blockers, the tactics package is certainly not a blocker. I thought you and Alan wanted to add a contributors file, that's all

**Comment by jneira** [comment]
@pepeiborra mmm right, i thought we could upload it anyways, with the actual copyrigths (like actual hls-plugin-api or hls-hlint-plugin). thoughts @alanz?

**Comment by ndmitchell** [comment]
FWIW, I tend not to bother with contributors files in projects I'm involved with as its a constant source of maintenance. And when a new contributor shows up, you realise way too late (after they're contributed a substantial portion) that no one forgot to include them. I'd just say "The Haskell IDE Team" or even just Alan, and people who want to know the contributors can look it up on GitHub interface.

**Comment by alanz** [comment]
I am happy with "The Haskell IDE Team" . It seems crazy for it to be me, there are so many people contributing.

**Comment by jneira** [comment]
Ok i will change hls-plugin-api and hls-plugin-api metadata

**Comment by jneira** [comment]
@pepeiborra I've changed the package metadata for hls itself, hls-plugin-api and hls-hlint-plugin with #1234 so afaics it could be uploaded when merged

**Comment by jneira** [comment]
@isovector it would be nice to have hls-tactics-plugin in hackage too, would you have some time to do it (if you agree of course)?

**Comment by isovector** [comment]
Sure thing. What do you need from me?

**Comment by jneira** [comment]
@isovector upload the hls-tactics-plugin (the version tagged [with 0.8.0.0](https://github.com/haskell/haskell-language-server/tree/0.8.0/plugins/tactics)) to hackage, ~~not sure if you had to do it before~~(i just check you are a [experimented hackage uploader](https://hackage.haskell.org/user/isovector) :slightly_smiling_face:)

**Comment by pepeiborra** [comment]
@jneira you just need to back port all the new changes (I've lost track) to the branch: https://github.com/haskell/haskell-language-server/tree/0.8.0-hackage and then upload to Hackage

**Comment by konn** [comment]
It's rather off-topic, but can I add some maintainers of the HLS repo to Hackage maintainer of splice plugin and (now deprecated) hls-exactprint-utils package? I'm willing to maintain Splice Plugin at least for a while, but I think it is safer and allows us flexible release procedure.

**Comment by jneira** [comment]
> @jneira you just need to back port all the new changes (I've lost track) 

Do you refer to https://github.com/haskell/haskell-language-server/pull/1234, for example? My idea was not make a new release of hls-plugin-api and hls-hlint.plugin but update the package metadata with hackage revisions. 

...but the change of hls itself should be backported, right, will do asap

**Comment by jneira** [comment]
@pepeiborra I've updated the 0.8.0-hackage branch: https://github.com/haskell/haskell-language-server/commit/812da1173d585a6927ad32e6c37f3b0dc628648d, and hls-plugin-api/hls-hlint-plugin have revisions to match the metadata of that commit

**Comment by konn** [comment]
OK, I've just copied Maintainer list of `hls-plugin-api` to `hls-splice-plugin` and `hls-exactprint-utils` (now deprecated, but the uploaded version of Splice Plugin depends on it).
I think I added @alanz @pepeiborra @wz1000 @bubba and @jneira, if I operated correctly. Thanks!

**Comment by augustss** [comment]
It's rather confusing when the instructions tell you how to install from hackage, but then it doesn't exist on hackage.  Perhaps add a comment about that in the instructions?

(And now I quietly go back to using ghcide.)

**Comment by pepeiborra** [comment]
Uploaded: https://hackage.haskell.org/package/haskell-language-server-0.8.0.0

**Comment by isovector** [comment]
Uploaded tactics. https://hackage.haskell.org/package/hls-tactics-plugin

**Comment by Ailrun** [comment]
@isovector BTW, is there something to do with that version number? It looks quite high.

**Comment by isovector** [comment]
@Ailrun it's what was already in the cabal file. Not sure where it came from :)

**Comment by isovector** [comment]
Well, we're stuck with it now. I'll maintain PVP from here going forwards. /shrug

**Comment by Ailrun** [comment]
It looks like it is the first version introduced by you? (This PR includes the first commit that introduces the cabal file, https://github.com/haskell/haskell-language-server/pull/516) Though maybe it comes from the other repo (I heard that there was a root repo for the tactic plugin)

**Comment by jneira** [comment]
maybe it was the version of hls when the plugin was bootstrapped?
