### ISSUE TITLE
New ghc-check-0.4 version breaks ghcide submodule

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#118]
Hi, if we build the project with a hackage index newer that the `ghc-check-0.4` release (2020-05-17T18:00:07Z), ghcide fails to build due to not having upper bound over the lib

**Comment by jneira** [comment]
The fix would be merge https://github.com/digital-asset/ghcide/pull/568/files into upstream ghcide
The temporary workaround, restrict ghc-check in the cabal.project

**Comment by jneira** [comment]
https://github.com/mpickering/ghcide/pull/39

**Comment by fendor** [comment]
Can we just ad an upper-bound on ghc-check? It is good practice anyways, especially since this lib has regurarly breaking changes at the moment

**Comment by pepeiborra** [comment]
> Can we just ad an upper-bound on ghc-check? It is good practice anyways, especially since this lib has regurarly breaking changes at the moment

This has already been done upstream in ghcide.

**Comment by jneira** [comment]
And cherrypicked to mpickering/hls(see link above) and [alanz/hls-az](https://github.com/alanz/ghcide/pull/4) 😅

**Comment by jneira** [comment]
Fixed by 15194
