### ISSUE TITLE
Cannot find haskell-language-server-Windows-8.8.3.exe

### ISSUE THREAD

**Issue by bradrn** [haskell/haskell-language-server#1184]
I am trying to use HLS with [a personal project](https://github.com/bradrn/cabasa) using GHC 8.8.3. The relevant HLS executable should, of course, be `haskell-language-server-Windows-8.8.3.exe`. However, this executable is missing from the latest two releases (0.8.0 and 0.7.1). Was this just a mistake in preparing the GitHub release; if so, can the relevant executable be uploaded? Alternately, if there really is a reason why I cannot use HLS with GHC 8.8.3 on Windows, it would be nice for that to be documented.

**Comment by Ailrun** [comment]
See https://github.com/haskell/haskell-language-server/issues/276

**Comment by bradrn** [comment]
Whoops, didn’t see that, thank you!
