### ISSUE TITLE
Merge hls-exactprint-utils into ghcide

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#1200]
This package contains a single module, `Ide.TreeTransform`, originally extracted from the `tactics` plugin, that provides a rather nice API for working with ghc-exactprint.

Ghcide code actions perform a lot of stringy AST rewriting that are both an eye sore and an endless source of bugs.

I want to make it possible to use `Ide.TreeTransform` in ghcide code actions, so my plan is: 

1. Rename `Ide.TreeTransform` to `Development.IDE.GHC.ExactPrint` to make it easier to discover
2. Move it to the ghcide package to make it usable. This is needed because `hls-exactprint-utils` depends on `ghcide`, so `ghcide` cannot depend on `hls-exactprint-utils`.
3. Expose `Development.IDE.GHC.ExactPrint` from the `ghcide` package for all the other plugins to use.

@isovector @konn any objections?

**Comment by isovector** [comment]
No objections

**Comment by konn** [comment]
No objections neither!
