### ISSUE TITLE
Properly import data constructors

### ISSUE THREAD

**Issue by GuillaumeDesforges** [haskell/haskell-language-server#1210]
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
$ haskell-language-server-wrapper --probe-tools
haskell-language-server version: 0.6.0.0 (GHC: 8.10.2) (PATH: /nix/store/li7n1p632m5wkkzw7yvw4ahj2mn55c2d-haskell-language-server-0.6.0.0/bin/haskell-language-server-wrapper)
Tool versions found on the $PATH
cabal:          Not found
stack:          2.5.1
ghc:            Not found
```
Which lsp-client do you use: VS Code

Describe your project (alternative: link to the project):

Contents of `hie.yaml`:
```yaml
cradle:
  stack:
```

### Steps to reproduce
* Have some imports from a module, for example
    ```
    import Katip (permitItem)
    ```
* Use a data constructor (e.g. `ColorIfTerminal`) in the code.
* Trigger code action (e.g. "Add ColorIfTerminal to to the import list of Katip")

### Expected behaviour

Imports become
```
import Katip (permitItem, ColorStrategy(ColorIfTerminal))
```

### Actual behaviour

```
import Katip (permitItem, ColorIfTerminal)
```
which creates an error

**Comment by Ailrun** [comment]
Maybe related with this merged PR?
https://github.com/haskell/haskell-language-server/pull/766
I'm not sure, though.

**Comment by jneira** [comment]
@mrBliss please, could you take a quick look to confirm the bug could be related with that pr?

**Comment by mrBliss** [comment]
> @mrBliss please, could you take a quick look to confirm the bug could be related with that pr?

Yes, I'll look into it.

**Comment by mrBliss** [comment]
@GuillaumeDesforges You are using haskell-language-server-0.6.0.0, which is relatively old, we're at 0.8.0.0 now. My PR, #766, was not even merged in 0.6.0.0.

I have tried to reproduce this with a recent version, which includes my #766, and I get the following suggestion: `Add ColorStrategy(ColorIfTerminal) to the import list of Katip`, which is correct.

I actually think #766 didn't change this but an earlier PR, e.g., https://github.com/haskell/ghcide/pull/916/.

**Comment by jneira** [comment]
@mrBliss many thanks for checking it, i should have checked the hls version before even ping you, sorry
I will wait the confirmation of @GuillaumeDesforges before closing it

**Comment by GuillaumeDesforges** [comment]
Indeed, I was using HLS from nixpkgs (e9158eca70a from 09/12, not so long ago).

I'm glad things are going so fast!

Sorry for the inconvenience,

Best

**Comment by jneira** [comment]
@GuillaumeDesforges no problem at all, thanks for your bug reports

**Comment by Ailrun** [comment]
Sorry for linking your PR, @mrBliss. I should have checked the HLS version of this issue.
Thank you for all your investigation!

**Comment by mrBliss** [comment]
> Sorry for linking your PR, @mrBliss. I should have checked the HLS version of this issue.
> Thank you for all your investigation!

No problem at all. My PR indeed looked related :slightly_smiling_face:
