### ISSUE TITLE
HLS version 0.8.0 frequently stuck when saving files

### ISSUE THREAD

**Issue by poscat0x04** [haskell/haskell-language-server#1214]
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 0.8.0.0 (GHC: 8.10.3) (PATH: /nix/store/px0cwk7xl79yq4b1pvkwaxfkwaswhis1-haskell-language-server-0.8.0.0/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		Not found
ghc:		8.10.3
```
Which lsp-client do you use:
vscode
Describe your project (alternative: link to the project):
cabal project
Contents of `hie.yaml`:
implicit hie

### Steps to reproduce
I'm not sure how to reproduce this issue reliably, but it seems that this issue comes up a lot more frequently when I'm editing a file that has errors (type errors/parse errors, etc.) in it.

### Expected behaviour
HLS should not stuck

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

<details>
<summary>
Debug output:
</summary>

```
<paste your logs here>
```
</details>

Paste the logs from the lsp-client, e.g. for [VS Code](https://github.com/haskell/vscode-haskell#troubleshooting)

<details>
<summary>
LSP logs:
</summary>

```
<paste your logs here>
```
</details>

**Comment by poscat0x04** [comment]
update: I can reliably reproduce this issue just by commenting out code

**Comment by jneira** [comment]
@poscat0x04 that definitely can help to debug the issue, please, could you give the instructions to reproduce it (linking to the source code if possible)?

**Comment by poscat0x04** [comment]
Oh right, sorry. To reproduce:
1. Open any Haskell file
2. type `{-`
3. type enter
3. type `-}`
4. save file
5. delete the lines containing comments you just entered
6. repeat 2-5 for a few times, HLS will then stuck

**Comment by konn** [comment]
I have encountered this bug for these days, too.
I suspect Eval plugin's comment parser, but no evidence.
If so, it can be addressed by using `getParsedModuelWithComments` instead of the custom comment parser to detect doctests.

**Comment by berberman** [comment]
I could repro following above steps.

**Comment by Ailrun** [comment]
That probably comes from Eval plugin. @poscat0x04 and @berberman, could you check whether your log message contains something like "Parser error" or so?

**Comment by konn** [comment]
If there is no other people to do with, I will try to rewrite doctest parser in Eval Plugin with `getParsedModuleWithComments` to see how this can affect this issue.
