### ISSUE TITLE
Multi Cradle : No prefixes matched for ./app/devel.hs

### ISSUE THREAD

**Issue by milosavljevic94** [haskell/haskell-language-server#1215]
My environment for develop Haskell/Yesod app : Ubuntu 20.04, VS Code, Haskell plugin and Stack.
Without plugin don't have error, but when plugin is installed error is:

```
Multi Cradle: No prefixes matched
pwd: /home/nemanja/Diplomski projekat/Manifestation
filepath: /home/nemanja/Diplomski projekat/Manifestation/app/devel.hs
prefixes:
("./src",Stack {component = Just "Manifestation:lib", stackYaml = Nothing})
("./app/main.hs",Stack {component = Just "Manifestation:exe:Manifestation", stackYaml = Nothing})
("./app/DevelMain.hs",Stack {component = Just "Manifestation:exe:Manifestation", stackYaml = Nothing})
("./app/Paths_Manifestation.hs",Stack {component = Just "Manifestation:exe:Manifestation", stackYaml = Nothing})
("./test",Stack {component = Just "Manifestation:test:Manifestation-test", stackYaml = Nothing})

```
And always get notifications in VS Code : 

No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for app/devel.hs.
 Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie).
You should ignore this message, unless you see a 'Multi Cradle: No prefixes matched' error.

If someone can solve, thanks!

**Comment by jneira** [comment]
Hi, thanks for the bug report. The cradle is esentially a configuration that maps filepaths with "components" (libs, executables, test suites, etc). The module you want to load with hls has to match one of the prefixes, and `app/devel.hs`does not match any. I guess that file is not listed in the build config files (.cabal or package.yaml). The implicit configuration uses those config files to generate those prefixes. 
So you should have be able to open `./app/main.hs` for example, as it is listed in that configuration

You can use an explicit configuration, creating a `hie.yaml` file in the project root listing the prefixes and try to add devel.hs to load it in the ide: see https://github.com/haskell/haskell-language-server#configuring-your-project-build for mor info

**Comment by milosavljevic94** [comment]
Thank you @jneira ! 
I created something like: 
```
cradle:
  stack:
  - path : "./app/devel.hs"
    component: "Manifestation:lib"
```
in hie.yaml and error is missing. 

Now I get a new one, maybe you know how to solve because they may be related : 
```
Could not load module ‘Application’
It is a member of the hidden package ‘Manifestation-0.0.0’.
You can run ‘:set -package Manifestation’ to expose it.
(Note: this unloads all the modules in the current scope.) 
```

**Comment by jneira** [comment]
@milosavljevic94 that hie.yaml would be incomplete, it should list all posible paths with modules in your project
to create a initial complete file you can run `stack install implicit-hie && gen-hie > hie.yaml`, and you can add there 
```
- path : "./app/devel.hs"
    component: "Manifestation:lib"
```

Could you share the code you are trying to load in the ide?

**Comment by milosavljevic94** [comment]
@jneira, I use this command to make hie file.
I got the initial file and added the problematic path like : 

- path: "./app/devel.hs"
      component: "Manifestation:exe:Manifestation"

 and now there are no more errors.

Thanks a lot, now I can continue working without errors in VS code.

**Comment by jneira** [comment]
great! thanks for reporting the issue
