### ISSUE TITLE
Ask for a collective email adress for "Haskell IDE Team"

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#1236]
* As mentioned [here](https://github.com/haskell/haskell-language-server/pull/1234#pullrequestreview-571708104)
* To set as maintainer in the package metadata and to have a single point to contact and feedback
* We can ask to haskell.org or the new haskell foundation

**Comment by ndmitchell** [comment]
Maybe rather than replacing it with an email, which needs checking etc, why not just include the issues link on github as our email?

**Comment by jneira** [comment]
I did that for hls-hlint-plugin (and cabal check or hackage upload didn't complain) but later i checked the field in the cabal reference and [it states](https://cabal.readthedocs.io/en/latest/cabal-package.html#pkg-field-maintainer) it should be an `address`.
`address` does not have any restriction (but the name itself :shrug:). 

> freeform, URL, address: An arbitrary, uninterpreted string.

Can we consider an url an `adress`? or could we ignore it as cabal does not validate it (for now)? Most packages have an email though. I guess that if there are conflicts and hackage trustees want to contact the maintainer, they will use that email (not always the comunication can be public)

But to be fair maintaining an address can be cumbersome, not sure if @alanz is receiving lot of spam in his email informed in hackage packages.

**Comment by alanz** [comment]
I get very little mail, we can keep it, at least we know a human is getting it.

**Comment by jneira** [comment]
Ok, so closing for now
