### ISSUE TITLE
How to use hie-compat in GHC 8.6?

### ISSUE THREAD

**Issue by m4dc4p** [haskell/haskell-language-server#1252]
My project builds with GHC 8.6. I'd love to use HIE files to speed up HLS on our project. How do I use the hie-compat library in my build?

Thank you for the awesome work!

**Comment by ndmitchell** [comment]
Honestly, while it's probably possible, it's likely to be a lot of fiddly work. Upgrading to a newer GHC is likely to be easier, and as a bonus you get to a newer GHC too. I would strongly recommend that path.

I thought that HLS generated .hie files automatically for you, so there was nothing to do? Or are you referring to building them in advance in the build system and then having HLS use them for you?

**Comment by wz1000** [comment]
ghcide already uses hie-compat to generate .hie files for GHC 8.6. There is no additional configuration needed.

**Comment by m4dc4p** [comment]
Thanks for the responses. I'm using HLS via VS Code. I searched for `*.hie` files in our build outputs but didn't see any. I'd much rather upgrade to 8.8 but I'm not in control of that. I heard on a podcast about hie-compat and hoped I could take advantage of speedups from them.

**Comment by wz1000** [comment]
Did you look in `~/.cache/ghcide`?

**Comment by m4dc4p** [comment]
There they are! Thanks.
