### ISSUE TITLE
Superfluous warning: "Proceeding with implicit cradle. You should ignore this message, [..]"

### ISSUE THREAD

**Issue by martijnbastiaan** [haskell/haskell-language-server#1259]
### Your environment
HLS versions: it was all fetched by VS Code, so I'm not entirely sure. 

Client: VS Code

Project: https://github.com/clash-lang/clash-starters/tree/b1a53b7d1e62a07026557dc392a710e8028dc515/simple

### Steps to reproduce
Open the starter project I linked just now in VS Code.

### Expected behaviour
It should start with no warnings.

### Actual behaviour
It warns:

```
No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for src/Example/Project.hs.
 Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie).
You should ignore this message, unless you see a 'Multi Cradle: No prefixes matched' error.
```

Unless there's something wrong (e.g., `Multi Cradle: No prefixes matched`) I don't think this message should be displayed. The message itself even thinks so :-)

**Comment by jneira** [comment]
Hi, thanks for your bug report, there is plans to remove it already (demoting it to a log debug entry): https://github.com/haskell/haskell-language-server/issues/620
So i am gonna close this one if you dont mind, you can track the resolution in the mentioned issue.

**Comment by martijnbastiaan** [comment]
Thanks!
