### ISSUE TITLE
HLS can't see modules from external packages?

### ISSUE THREAD

**Issue by Anrock** [haskell/haskell-language-server#126]
Not sure what's going on. So I've migrated from hie + stack to hls + stack and then replaced stack with cabal-3.0. It was kinda fine until it broke. 

I've tried to find a commit when it broke, but it reproductable with every commit since day one (relative to day I cloned the repo).

So the error is that HLS marks imports of many modules with `"Could not find module ‘Foo.Bar’ It is not a module in the current program, or in any known package."`.

It marks as error imports from: 
* External packages. Seen polysemy, optparse-applicative
* Other modules from the same lib component.

Doesn't mark as error imports from: 
* Packages shipped with GHC. Seen `base`, `text`, `array`.
* Other modules from the same executable component.

Looks like HLS doesn't see any modules except from packages shipped with GHC and modules of current executable component?

I've managed to reproduce it with empty cabal project by adding library component with some modules and optparse-applicative build-dependency.

Here is sample run with of minimal project where Main.hs imports `Options.Applicative` from optparse-applicative, Foo and Bar from library exposed-modules and Baz from other executable module. Also, Bar imports Foo.
```
ghcide version: 0.1.0.0 (GHC: 8.6.5) (PATH: /home/anrock/.cabal/bin/haskell-language-server-8.6.5)
(haskell-language-server)Ghcide setup tester in /tmp/test.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Step 1/6: Finding files to test in /tmp/test
Found 5 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6: Initializing the IDE

Step 4/6: Type checking the files
Consulting the cradle for "/tmp/test/Main.hs"
Right (ComponentOptions {componentOptions = [], componentRoot = "/tmp/test", componentDependencies = []})
"Making new HscEnv[main]"
(([],Just HscEnvEq 7),fromList [])
Consulting the cradle for "/tmp/test/lib/Bar.hs"
Right (ComponentOptions {componentOptions = [], componentRoot = "/tmp/test", componentDependencies = []})
"Making new HscEnv[main,main]"
File:     /tmp/test/Main.hs
Hidden:   no
Range:    4:7-4:26
Source:   not found
Severity: DsError
Message:
  Could not find module ‘Options.Applicative’
  It is not a module in the current program, or in any known package.
File:     /tmp/test/Main.hs
Hidden:   no
Range:    5:7-5:10
Source:   not found
Severity: DsError
Message:
  Could not find module ‘Foo’
  It is not a module in the current program, or in any known package.
File:     /tmp/test/Main.hs
Hidden:   no
Range:    6:7-6:10
Source:   not found
Severity: DsError
Message:
  Could not find module ‘Bar’
  Perhaps you meant
  Bag (needs flag -package-key ghc-8.6.5)
  Var (needs flag -package-key ghc-8.6.5)
(([],Just HscEnvEq 8),fromList [])
(([],Just HscEnvEq 9),fromList [])
Consulting the cradle for "/tmp/test/Baz.hs"
Right (ComponentOptions {componentOptions = [], componentRoot = "/tmp/test", componentDependencies = []})
File:     /tmp/test/lib/Bar.hs
Hidden:   no
Range:    3:7-3:10
Source:   not found
Severity: DsError
Message:
  Could not find module ‘Foo’
  It is not a module in the current program, or in any known package.
"Making new HscEnv[main,main,main]"
(([],Just HscEnvEq 10),fromList [])
(([],Just HscEnvEq 11),fromList [])
(([],Just HscEnvEq 12),fromList [])
Consulting the cradle for "/tmp/test/Setup.hs"
Right (ComponentOptions {componentOptions = [], componentRoot = "/tmp/test", componentDependencies = []})
"Making new HscEnv[main,main,main,main]"
(([],Just HscEnvEq 13),fromList [])
(([],Just HscEnvEq 14),fromList [])
(([],Just HscEnvEq 15),fromList [])
(([],Just HscEnvEq 16),fromList [])
Consulting the cradle for "/tmp/test/lib/Foo.hs"
Right (ComponentOptions {componentOptions = [], componentRoot = "/tmp/test", componentDependencies = []})
"Making new HscEnv[main,main,main,main,main]"
(([],Just HscEnvEq 17),fromList [])
(([],Just HscEnvEq 18),fromList [])
(([],Just HscEnvEq 19),fromList [])
(([],Just HscEnvEq 20),fromList [])
(([],Just HscEnvEq 21),fromList [])
[INFO] finish: TypecheckTest (took 0.73s)
```

GHC 8.6.5, HLS from 40673269045b214b993c61c112981c7497aae1be compiled via `./cabal-hls-install hls-8.6.5`.

NB. I don't have much experience with cabal, I've installed it with autogenerated ebuild , and recently I did `cabal user-config init -f` so with high probability it may be a invalid user environment. Anyway I would be grateful for fix / advicce.

**Comment by fendor** [comment]
> `Right (ComponentOptions {componentOptions = [], componentRoot = "/tmp/test", componentDependencies = []})`

Component options are empty, that is why external libraries can not be loaded.
Have you tried an explicit `hie.yaml`? That is currently the only reliable way of creating a session.

**Comment by Anrock** [comment]
> Have you tried an explicit hie.yaml?

No, because it was working before without it. Do I understand correctly that "everything was working" was kind of sheer luck and writing hie.yaml is the expected way to use hls?

**Comment by fendor** [comment]
For simple cabal projects, I think it should work. But the implicit-cradle discovery mechanism just isnt very reliable at the moment.

**Comment by Anrock** [comment]
Okay, off to write hie.yaml then.
