### ISSUE TITLE
Consider restoring the old Eval plugin

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#1276]
The extended Eval plugin was merged in https://github.com/haskell/haskell-language-server/pull/438 replacing the original Eval plugin. It is capable and powerful, but also complicated and dangerous - its custom parser has a tendency to error out and bring down the entire process, and the additional features can be hard to understand.

Many users are not aware of the extra features for running doc tests and properties, changing settings and imports, etc. and would be better served by the simpler original Eval plugin, but unfortunately it's now gone.

Proposal: bring back the original Eval plugin under a new name, e.g. `hls-eval-simple`, and ship with both linked and config to select which one gets used, just like we do with formatters.

**Comment by konn** [comment]
👍 for it. Although its custom parser is rewritten carefully in #1232 (not merged though), maintaining its own parser and try not to introduce infinite loops to freeze entire HLS at the same time can be a complicated process.
Aside from extended features like block comment support, QuickCheck support and `$setup` section and so on, there can be many common parts that can be shared both simple- and extended-eval plugin. So I think it makes sense to me to separate extended feature as a separate package and make it depend on `hls-eval-simple`.

Hopefully, changes in #1232 will stabilise comment parsing of Extended Eval Plugin, I think it is safe to set the default Eval plugin to Extended mode provided that the PR gets merged.

**Comment by jneira** [comment]
Ok, #1232 sounds promising, i guess we should make a minor release once it is merged

**Comment by Ailrun** [comment]
@jneira I think since we already merged #704, releasing a minor version goes somewhat against the reason why we wait the merge of the PR.

**Comment by jneira** [comment]
yeah, we should release a version with the eval fix but without hiedb, maybe it does not worth

**Comment by konn** [comment]
I want to confirm: not within a few days, but February release willbe made once hiedb change works properly, right?

**Comment by Ailrun** [comment]
@konn Yeah, I believe that's the original intention.

**Comment by michaelpj** [comment]
Closing since nothing has happened and it seems unlikely we're going to do this
