### ISSUE TITLE
Cannot invoke stylish-haskell (better error handling fo config file error)

### ISSUE THREAD

**Issue by QuarticCat** [haskell/haskell-language-server#1277]
### Env

- OS: Arch Linux
- VSCode: 1.52.1
- Haskell Extension: 1.2.0
- GHC: 8.8.4 (installed by ghcup)

Formatters are installed by stack. But it seems that HLS has its own formatters. The version it outputs can not match mine.

### Log

Stylish-haskell:

```
Message: RequestMessage {_jsonrpc = "2.0", _id = IdInt 60, _method = TextDocumentFormatting, _params = DocumentFormattingParams {_textDocument = TextDocumentIdentifier {_uri = Uri {getUri = "file:///home/quartic/Workspace/Code/Temp/Haskell/ttttt2.hs"}}, _options = FormattingOptions {_tabSize = 2, _insertSpaces = True}, _workDoneToken = Nothing}}
Exception: 0:0:Language.Haskell.Stylish.Config.loadConfig: fromJSON: key "via" not found

CallStack (from HasCallStack):
  error, called at lib/Language/Haskell/Stylish/Config.hs:123:32 in stylish-haskell-0.12.2.0-1484562cd628adb85456026d1e1a4cd35a905ae014f7fdd185580d56b98143cf:Language.Haskell.Stylish.Config
[Error - 5:08:52 AM] Request textDocument/formatting failed.
  Message: 0:0:Language.Haskell.Stylish.Config.loadConfig: fromJSON: key "via" not found

CallStack (from HasCallStack):
  error, called at lib/Language/Haskell/Stylish/Config.hs:123:32 in stylish-haskell-0.12.2.0-1484562cd628adb85456026d1e1a4cd35a905ae014f7fdd185580d56b98143cf:Language.Haskell.Stylish.Config
  Code: -32603 
```

Brittany:

```
/opt/ghc/8.8.4/lib/ghc-8.8.4/settings: openFile: does not exist (No such file or directory)
2021-01-30 05:06:15.803330178 [ThreadId 925] - Unexpected exception on request, please report!
Message: RequestMessage {_jsonrpc = "2.0", _id = IdInt 52, _method = TextDocumentFormatting, _params = DocumentFormattingParams {_textDocument = TextDocumentIdentifier {_uri = Uri {getUri = "file:///home/quartic/Workspace/Code/Temp/Haskell/ttttt2.hs"}}, _options = FormattingOptions {_tabSize = 2, _insertSpaces = True}, _workDoneToken = Nothing}}
Exception: ExitFailure 1
[Error - 5:06:15 AM] Request textDocument/formatting failed.
  Message: ExitFailure 1
  Code: -32603 
```

**Comment by jneira** [comment]
Hi, thanks for the bug report, i've translated it to the haskell-language-server repo, as it is responsible for handle formatters.
As you has verified the formatters are embedded in hls itself, with the versions set here.
The issue with stilysh-haskell is new for me but the brittany one could be https://github.com/haskell/haskell-language-server/issues/549. In that case the new hls version just released should fix it.

**Comment by QuarticCat** [comment]
@jneira

**Comment by QuarticCat** [comment]
@jneira After update to 0.9.0, brittany works. But stylish-haskell still has that problem.

Also, sorry for my misoperation just now.

**Comment by Ailrun** [comment]
Would you mind if I ask for a reproduction?

**Comment by QuarticCat** [comment]
@Alirun 

- Install GHC 8.8.4 by ghcup and set it
- Create a Haskell file with any content, say:
  ```haskell
  main :: IO ()
  main = print "123"
  ```
- Open it with VSCode, then let VSCode automatically download HLS
- Press alt+shift+F, or right click and choose Format Document
- Now these messages can be seen from OUTPUT

**Comment by jneira** [comment]
Maybe open a file instead a folder with a haskell project could be related.

**Comment by Ailrun** [comment]
I cannot reproduce with, at least, the built-from-lastest-commit version in both VSCode and Emacs (under Manjaro). Do you have any other file than that Haskell file, like `$HOME/.config/.stylish-haskell.yml` or similar (https://github.com/jaspervdj/stylish-haskell#configuration)?

**Comment by QuarticCat** [comment]
@Ailrun 
Yes... I found one. It seems that the problem is caused by the outdated config file that was previously configured for my old version stylish-haskell. The formatter works after I delete `.stylish-haskell.yml`. Sorry for bothering you.

**Comment by Ailrun** [comment]
OK, maybe it's better to have a better error handling for the configuration file error.

**Comment by Anton-Latukha** [comment]
Maybe it is solved now?

**Comment by michaelpj** [comment]
I suspect this is better now, the plugin has changed a bunch
