### ISSUE TITLE
tar should be installed before the installation of HLS, this should be an additional instruction of HLS installation 

### ISSUE THREAD

**Issue by leo-mao** [haskell/haskell-language-server#1280]
### Your environment
Win8.1 Pro version 6.3 9600 64bit

### Steps to reproduce
follow the official instruction to install HLS
```
cd ..
git clone https://github.com/haskell/haskell-language-server --recurse-submodules
cd haskell-language-server
stack install.hs hls-8.10.3
```

### Expected behaviour

Installation should be done flawlessly.
### Actual behaviour

```
2021-01-31 12:43:58.193440: [debug] Process finished in 108ms: C:\Program Files\Git\cmd\git.EXE -c core.autocrlf=false archive -o C:\Users\Admin\AppData\Local\Temp\with-repo-archive22888\foo.tar HEAD
2021-01-31 12:43:58.499660: [error] Executable named tar not found on path: [".",.......]
```
### How to fix it
since `tar` is only available under *nix, cygwin have to be installed aforehand.
1. install `cygwin`
2. run the `stack install.hs hls` in cygwin terminal, or add `C:\cygwin64\bin` to system `PATH` and run the command in cmd
> btw. if you encounter `"commitAndReleaseBuffer: invalid argument (invalid character)"` issue in later installation, you should change your [terminal encoding to utf8](https://kylejung0828.github.io/dev/changing-code-page-in-windows-terminal/)

**Comment by fendor** [comment]
I thought `stack` would be enough, no cygwin required? Doesn't it install msys2 into a private location?

**Comment by fendor** [comment]
Seems related: https://github.com/commercialhaskell/stack/issues/5249

**Comment by leo-mao** [comment]
> Seems related: [commercialhaskell/stack#5249](https://github.com/commercialhaskell/stack/issues/5249)

>Seems that whilst windows 10 comes with tar windows 7 does not

okay, in win 10 will this issue not occur, i.e. sole stack could be enough, whilst in win7&8.1 is not the case.

**Comment by fendor** [comment]
Does it work to execute `stack exec -- pacman -S tar`?

From: https://docs.haskellstack.org/en/stable/developing_on_windows/

**Comment by leo-mao** [comment]
> 
> 
> Does it work to execute `stack exec -- pacman -S tar`?
> 
> From: https://docs.haskellstack.org/en/stable/developing_on_windows/

It does surprise me that stack even support pacman, and `stack exec -- pacman -S tar` works, and this could be another workaround for this issue.

**Comment by ndmitchell** [comment]
Tar isn't only available on Cygwin - in fact, if you want to get a copy of Tar, there is BSD Tar which provides native Windows binaries which I use. I think we might want to be careful about using tar, but installing Cygwin is a very big hammer to try that.

What is actually using tar? Is it Stack itself? Or are we spawning tar directly?

**Comment by leo-mao** [comment]
> 
> 
> Tar isn't only available on Cygwin - in fact, if you want to get a copy of Tar, there is BSD Tar which provides native Windows binaries which I use. I think we might want to be careful about using tar, but installing Cygwin is a very big hammer to try that.


Thanks for your advice, I choose Cygwin is because that I have less experience with cmd and Cygwin is recommanded by stackoverflow, which might also offer other essential but potentially missing binaries.    

> What is actually using tar? Is it Stack itself? Or are we spawning tar directly?
As I provided in issue description, `tar` is needed by `git archive`.

**Comment by ndmitchell** [comment]
I personally use https://sourceforge.net/projects/unxutils/. MingW is also a good option. Cygwin is usually a worse option than MingW.

Who is running `git archive`? Us or `stack`? If it's us, we should stop, and just download the right archive from GitHub directly. If it's stack, we should raise the issue with them, as they should ensure the right tools are installed.

**Comment by fendor** [comment]
I *think* it is `stack` that is calling it. At least I dont recall (or can't find) using anything tar related. (As a nix user, I am rather confident, we don't have a direct dependency on tar)

**Comment by Ailrun** [comment]
BTW, why "haskell-ide-engine"? Now the repo is "haskell-language-server".

**Comment by leo-mao** [comment]
> 
> 
> BTW, why "haskell-ide-engine"? Now the repo is "haskell-language-server".

sorry, that's a typo, I just copy from [old tutorial](https://medium.com/@dogwith1eye/setting-up-haskell-in-vs-code-with-stack-and-the-ide-engine-81d49eda3ecf) when I writing issue. Also the hls version which I tried to install was 8.10.3, now it should be the command I typed in cmd

**Comment by leo-mao** [comment]
> 
> 
> I _think_ it is `stack` that is calling it. At least I dont recall (or can't find) using anything tar related. (As a nix user, I am rather confident, we don't have a direct dependency on tar in the installation process)

It could happen when the `stack` installing the ghc, because I remember the error occurred really quickly after I typed in the command, however I cannot reproduce it now, by removing `tar` from `stack pacman` and removing `cygwin` from `PATH`, is it because ghc has been installed?

**Comment by jneira** [comment]
> is it because ghc has been installed?

probably, you can try to rename or move ghc from it actual location, where stack is looking for, to reproduce again

**Comment by leo-mao** [comment]
Really wired, even if I remove everything under `%LOCALAPPDATA%\Programs\stack` doesn't reproduce this issue, I'm confused now

**Comment by jneira** [comment]
So we should note in the documentation that tar is needed to use the install script

**Comment by leo-mao** [comment]
> So we should note in the documentation that tar is needed to use the install script

Since I cannot reproduce this problem, I don't think it's a obligatory pre-requisite to install tar, maybe as additional information?
