### ISSUE TITLE
How to use Record completion snippets?

### ISSUE THREAD

**Issue by googleson78** [haskell/haskell-language-server#1303]
Context: Using nvim with LanguageClient-neovim

How can I use the functionality to automatically get unassigned record fields generated?

What LSP "command" do I need to issue to the language server?

**Comment by samhh** [comment]
I have the same question using the native (master, due in 0.5) LSP client. I'd expect it to be a code action but it's not there.

To be clear, this is atop a diagnostic of: `Fields of ‘MyType’ not initialised: field1, field2, etc`

**Comment by jneira** [comment]
I think @expipiplus1 has being used hls with vim with relative success, maybe they know something about this

**Comment by expipiplus1** [comment]
Snippets seem to just work for me with coc.nvim: https://asciinema.org/a/414482 (Had to set up the keybinding for it as it's not a feature I regularly use)

As for performing an action on that uninitialized field warning/error, I wasn't able get that working in nvim or vscode.

**Comment by michaelpj** [comment]
Sounds like it's unclear if this is still an issue, so closing.
