### ISSUE TITLE
Benchmark suite can fail unexpectedly

### ISSUE THREAD

**Issue by konn** [haskell/haskell-language-server#1306]
We have a really nice benchmark suite to ensure efficiency. However, in some (unpredictable) cases, it fails due to an unexpected `resource busy` exception, e.g. see [Benchmark #630](https://github.com/haskell/haskell-language-server/runs/1798215794?check_suite_focus=true#step:9:221).
Since the current benchmark suite is the most time-consuming part of a CI, which can take up to two hours, and it can unexpectedly fail at the very end of a run, it might be favourable to avoid such `resource busy` exceptions.

**Comment by pepeiborra** [comment]
I have a fix and other improvements coming
