### ISSUE TITLE
Add ghc-8.10.4 support

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#1317]
I was not aware of this one!

**Comment by Ailrun** [comment]
Me too, wow, we have quite a number of GHC 8.10!

**Comment by ahmadrasyidsalim** [comment]
What about 9.0.1? https://www.haskell.org/ghc/download_ghc_9_0_1.html

**Comment by konn** [comment]
Already tracked here, pinned at the top of issues: #297

**Comment by stupdfox** [comment]
@konn uh, my bad, thanks.

**Comment by ahmadrasyidsalim** [comment]
@konn, uh huh, my bad, thanks.

**Comment by pepeiborra** [comment]
Circle CI is already struggling, so if you are planning to add more jobs to the matrix, please consider dropping others at the same time

**Comment by jneira** [comment]
Yeah, i was thinking in establish a policy by which we only are gonna support at most three minor versions (if there is no really good reason to do it)
So we would rule out 8.10.1 from all ci jobs, including releases.

**Comment by jneira** [comment]
@Ailrun we should do a release (a github simple one) with support for this, would you like to try it? no problem otherwise 😄

**Comment by Ailrun** [comment]
Will only a github release be enough?

**Comment by jneira** [comment]
I think so, at least for now, i dont want lose the possibility of doing quick github releases without hackage one

**Comment by Ailrun** [comment]
OK, I will try the release

**Comment by jneira** [comment]
Many thanks, feel free to ask for help whenever you find any barrier

**Comment by simonmichael** [comment]
+1 for release. Protecting users from stupid install hassles is (vscode-haskell's, I thought ?) number one feature, and the reason I have been confidently recommending it to people.  (Saw someone getting tripped up by it in the Haskell matrix room today).
