### ISSUE TITLE
ghcide plugins don't honour generic plugin configuration

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#1321]
* The config was added with #691
* As far i am able to test, ghcide plugins seems to ignore their sections 
* With this config in `.vscode/settings.json`

```json
{
    "haskell": {
        "plugin" : {
            "importLens" : {
                "codeLensOn" : false
            },
            "ghcide-type-lenses" : {
                "codeLensOn" : false
            }
        }
    }
}
```

i see import lenses are removed but no type sigs ones:

![imagen](https://user-images.githubusercontent.com/54035/107155440-aaf35d80-6978-11eb-9122-3e3e12f9e04f.png)

* I took plugin descriptors from https://github.com/haskell/haskell-language-server/blob/master/ghcide/src/Development/IDE/Plugin/HLS/GhcIde.hs#L20-L26, not sure if they are the correct way to use in the configuration

**Comment by berberman** [comment]
I think this issue was fixed by #1284:
https://github.com/haskell/haskell-language-server/blob/4bcd0c684d7a1be9043f318c976a090c55bc0814/hls-plugin-api/src/Ide/Types.hs#L73

**Comment by jneira** [comment]
So hls-1.0.0 should include it, could we test the configuration pasted above to confirm it (will do in some hours myself)?

**Comment by berberman** [comment]
![image](https://user-images.githubusercontent.com/26041945/109947752-a1111000-7d14-11eb-9a6d-203a9d614e31.png)

Works for me

**Comment by jneira** [comment]
Many thanks for confirming it, love miss issues already resolved :sweat_smile:
