### ISSUE TITLE
No valid buildplan for hls 0.9.0 with the tactis-plugin

### ISSUE THREAD

**Issue by maralorn** [haskell/haskell-language-server#1329]
hls 0.9.0 has a bound `haskell-lsp (==0.23.*)`, there is only one hackage release for `hls-tactis-plugin` which has a bound of `haskell-lsp (==0.22.*)`. So if I don‘t misinterpret anything there is no way to build hls 0.9.0 with the tactics plugin.

I assume this can be fixed with a revision for hls-tactics-plugin on hackage. cc: @isovector

**Comment by jneira** [comment]
the flag adding the plugin is set to auto iirc, is not cabal removing tactics auto from the build plan?

**Comment by maralorn** [comment]
That’s a question of paranthesizing. I was not very clear on this . There is no valid buildplan for "hls 0.9.0 with the tactis-plugin". I assume cabal can still build "hls 0.9.0" but I try to build it with all plugins.

Overriding the bound works by the way, so making that more flexible seems like an easy win.

**Comment by isovector** [comment]
What do you need on my end? I am hoping to not need to do administrative things every time LSP changes.

**Comment by maralorn** [comment]
I totally understand that sentiment. It’s certainly not a given that you have to. Maybe this can be improved together with automating the release process.

What - I think - we need right now is a new revision on hackage for the hls-tactics-plugin, where you change the bound of `haskell-lsp` from `(==0.22.*)` to `>= 0.22 && < 0.23`.

**Comment by jneira** [comment]
@isovector have you consider share the responsability (and the work! 🙂) of the plugin in hackage? we are thinking in automate hackage releases and to have a common maintainer for all plugins would be handy for that scenario.

**Comment by isovector** [comment]
@maralorn The package information on hackage is already `haskell-lsp    ^>=0.22` -- shouldn't that be enough?
@jneira happy to. I just want to be a code monkey!

**Comment by isovector** [comment]
Oh, sorry, I misread what was being asked of me. New bounds are `haskell-lsp    >=0.22 && < 0.24`

**Comment by jneira** [comment]
> @jneira happy to. I just want to be a code monkey!

nice, imo adding any of the hls maintainers could agilize the release process, what about adding @pepeiborra or @Ailrun? afaics the plugin already has commits from them (if they agree of course)

**Comment by maralorn** [comment]
@isovector Sorry, brain fail … It’s mistakes like this why I like Haskell and testsuites …

**Comment by maralorn** [comment]
Thank you! Seems fixed on hackage.
