### ISSUE TITLE
Requires zlib on Debian/Ubuntu

### ISSUE THREAD

**Issue by Sir4ur0n** [haskell/haskell-language-server#133]
This library needs zlib to be installed, but it's not mentioned in the Debian prerequisites.

On a freshly installed Ubuntu 20.04 (WSL) I had to install the `zlib1g-dev` package (not `zlib1g`) before the Haskell `zlib` package would compile.

**Comment by jneira** [comment]
Thanks for noting it, would you be interested in open a pr to correct install instructions?

**Comment by Sir4ur0n** [comment]
Yes sorry, should have mentioned, I'm already working on it (running tests for older Ubuntu version 18.04), PR should land shortly after
