### ISSUE TITLE
ghcide 0.7.4.0 breaks hls-explicit-imports-plugin 0.1.0.0

### ISSUE THREAD

**Issue by hamishmack** [haskell/haskell-language-server#1332]
Ironically explicitly importing from `import Development.IDE.GHC.Compat` might have avoided the problem.

```
src/Ide/Plugin/ExplicitImports.hs:219:10: error:
    Ambiguous occurrence ‘isQualifiedImport’
    It could refer to
       either ‘Development.IDE.GHC.Compat.isQualifiedImport’,
              imported from ‘Development.IDE.GHC.Compat’ at src/Ide/Plugin/ExplicitImports.hs:29:1-33
           or ‘Ide.Plugin.ExplicitImports.isQualifiedImport’,
              defined at src/Ide/Plugin/ExplicitImports.hs:255:1
    |
219 |   | not (isQualifiedImport imp),
    |          ^^^^^^^^^^^^^^^^^
```

**Comment by jneira** [comment]
Ouch, the plugin need a revision with a upper bound over ghcide then, 
//cc @pepeiborra

**Comment by pepeiborra** [comment]
Yeah, I discovered the same thing overnight. Revision done and will upload a new version soon. I have also added @jneira as a maintainer to all my plugins in case I'm not around next time. Thanks.
