### ISSUE TITLE
Code action "Apply all hints" shows everywhere

### ISSUE THREAD

**Issue by berberman** [haskell/haskell-language-server#1341]
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:
```
haskell-language-server version: 0.9.0.0 (GHC: 8.10.3) (PATH: /home/berberman/.cabal/store/ghc-8.10.3/haskell-language-server-0.9.0.0-18058efd60909de3b42ad413a831db1d65bdb70ecd78bdd620d47f958f9480c0/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:          3.2.0.0
stack:          Not found
ghc:            8.10.3
```
Which lsp-client do you use:
vscode

Not sure if it's intended, but imo this code action should populate accompanying each single fix, just like the code action for removing all redundant imports. (cc @jneira)

![A](https://user-images.githubusercontent.com/26041945/107472952-d2317100-6baa-11eb-8ebf-613af271da1a.png)

on whitespace:

![B](https://user-images.githubusercontent.com/26041945/107472994-e5dcd780-6baa-11eb-93a8-4e4ecbae5d1d.png)

**Comment by jneira** [comment]
Hi, not sure if i am understanding it but the screenshots are the behaviour you want to have, no?
The `Apply all hints` is showed for every hlint diagnostic when there is more than one hlint diagnostic in a file, on purpose.
Sorry if i am missing something obvious but how you trigger code actions directly without quick fix?

**Comment by berberman** [comment]
Sorry, my bad, I wasn't being clear. There were two hlint diagnostics in the file. At right places (where the code we want to fix), two code actions populated as expected. But I could always get "Apply all hints" at any point in the file. I recorded a video to show that:


https://user-images.githubusercontent.com/26041945/107477553-e24d4e80-6bb2-11eb-9921-63938fac0646.mp4

**Comment by jneira** [comment]
Oh, i see now, thanks for the clarification, it adds unnecessary noise, yeah
