### ISSUE TITLE
Add a config option to control tactics' auto's gas

### ISSUE THREAD

**Issue by isovector** [haskell/haskell-language-server#1355]
It would allow us to solve things like https://github.com/haskell/haskell-language-server/issues/562

**Comment by isovector** [comment]
Additionally, maybe automatically increase the gas if a hole fill doesn't produce any results.

**Comment by jneira** [comment]
Only want to note that now plugins has its own namespace in our config: #691

**Comment by isovector** [comment]
Thanks for the info, @jneira . Do these options show up in editors' configuration settings?

**Comment by jneira** [comment]
I am afraid they still not are, there is an issue about https://github.com/haskell/vscode-haskell/issues/336
You can do it manually though: https://github.com/haskell/haskell-language-server/issues/1342#issuecomment-776518880
