### ISSUE TITLE
Build Error for 8.10.4 (maybe only under Windows)

### ISSUE THREAD

**Issue by CarstenKoenig** [haskell/haskell-language-server#1372]
### Your environment

please note: that is *after* I fixed the issue with the workaround I added bellow

```
haskell-language-server version: 0.9.0.0 (GHC: 8.10.4) (PATH: C:\Users\cakoeni1\AppData\Roaming\local\bin\haskell-language-server.exe) (GIT hash: 4d431e9a7c51ab1b817476c1fec45c6cbaa676e8)
Tool versions found on the $PATH
cabal:          Not found
stack:          2.5.1
ghc:            Not found
```

only stack should matter here though - it's a windows OS

### Steps to reproduce

    git clone https://github.com/haskell/haskell-language-server --recurse-submodules
    cd haskell-language-server
    stack ./install.hs hls-8.10.4

### Expected behaviour
haskell-language-server.exe and haskell-language-server-wrapper.exe is build and installed

### Actual behaviour
error

    with-utf8 > app\utf8-troubleshoot\Main.hs:23:31: error:
    with-utf8 >     Module `GHC.IO.Encoding.Iconv' does not export `localeEncodingName'
    with-utf8 >    |
    with-utf8 > 23 | import GHC.IO.Encoding.Iconv (localeEncodingName)

see https://github.com/serokell/haskell-with-utf8/issues/9

### work around

add this to `extra-deps` in `stack-8.10.4.yaml`:

      - github: f-f/haskell-with-utf8
        commit: 8ae743ac6503a4c494ea3bd52f1fe7d72f9f125d

**Comment by Ailrun** [comment]
It looks like indeed it happens only in Windows, as [GHC.IO.Encoding.Iconv](https://hackage.haskell.org/package/base-4.14.1.0/docs/src/GHC.IO.Encoding.Iconv.html) does not export them only when `!defined(mingw32_HOST_OS)`.

**Comment by jneira** [comment]
Ugh, we dont have builds in ci for stack+windows, thanks for report the issue, we will try to fix asap

**Comment by jneira** [comment]
> only stack should matter here though - it's a windows OS

i use mostly cabal in windows (and our ci is building and testing using cabal in ci) :wink:

**Comment by CarstenKoenig** [comment]
> 
> 
> > only stack should matter here though - it's a windows OS
> 
> i use mostly cabal in windows (and our ci is building and testing using cabal in ci) 😉

sorry the comment was probably very poorly worded - I did not want to express that only stack matters on windows - I wanted to express that the only information that IMO mattered in that *console log* was the stack-version.

The template for the issue here asked me to include the output and the following comments around it was me trying to say that this was using the tooling with my "temp-fix" applied and that it AFAIK should not really matter for the issue at hand.

**Comment by Ailrun** [comment]
Yeah I also believe that the usage of the tool `stack` should not matter. It's more like how that dependency is broken in Windows OS.

**Comment by jneira** [comment]
But it works in cabal and windows, without using any source-repository-package... to investigate

**Comment by jneira** [comment]
@CarstenKoenig it turns out that using last with-utf8 fixes the issue, as 1.0.2.2 has a patch for it
cabal, which uses version ranges, has picked the patched version automatically but stack using fixed versions needed manual changes in stack.yaml to get it

**Comment by CarstenKoenig** [comment]
Thank you for the info and you all for your work - HLS and the VS.code extension is quite amazing

I guess it's ok to close the issue in this case.

Do you want me to do it?

**Comment by jneira** [comment]
Thank you for trying it and take some time to report the issue.
The merging of the pr will close it automatically.
