### ISSUE TITLE
hls-plugin-api 0.7.1.0 breaks haskell-language-server 0.9.0.0

### ISSUE THREAD

**Issue by hamishmack** [haskell/haskell-language-server#1395]
I think we need to add a `hls-plugin-api ==0.7.0.*` constraint like the one for `ghcide` (see #1332 and #1381)

**Comment by hamishmack** [comment]
I also think we might need `hls-retrie-plugin ==0.1.1.0`

**Comment by pepeiborra** [comment]
I have added restrictions for hls-plugin-api and all the plugins

**Comment by pepeiborra** [comment]
Leaving this ticket open until the restrictions are merged in HEAD

**Comment by jneira** [comment]
Closed by #1392
