### ISSUE TITLE
[QoL] Strip CWD from diagnostics message

### ISSUE THREAD

**Issue by Anrock** [haskell/haskell-language-server#140]
It would be nice if HLS stripped CWD prefix from diagnostics message.
So when I'm editing a `Foo.hs` and there are some errors diagnostic text would be
`lib/Foo.hs:148:12: error: blah-blah` instead of `/home/anrock/projects/example/lib/Foo.hs:148:12: error: blah-blah`.

Questionable: Strip filepath from message completely. Given that all location info already provided in LSP response there is no need to have it in message - LSP client should take of displaying location info if needed. 

Also it looks kinda easy to do but given HLS highly modular structure I have no idea where to even look for the diagnostics emitting code. Any tips?

**Comment by Anrock** [comment]
Looks like it's already done in ghcide 0.2 with https://github.com/digital-asset/ghcide/pull/546/

**Comment by peterwicksstringfield** [comment]
I think this can be closed? https://github.com/haskell/ghcide/pull/546 was merged a while ago, and the corresponding issue in ghcide was closed.
