### ISSUE TITLE
Pre-commit hook fails with parse error

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#1416]
```
stylish-haskell..........................................................Failed
- hook id: stylish-haskell
- exit code: 1

ghcide/src/Development/IDE/Main.hs: RealSrcSpan SrcSpanOneLine "ghcide/src/Development/IDE/Main.hs" 198 109 110: parse error on input `@'
```

I believe stylish-haskell does support type applications, so maybe this is a configuration issue?

**Comment by Ailrun** [comment]
I cannot reproduce it with CLI, so it's probably to do with nix-pre-commit-hook.

**Comment by Ailrun** [comment]
It looks like pre-commit cannot detect the stylish-haskell setting file...

**Comment by Ailrun** [comment]
IDK why, but pre-commit only uses the top-level stylish-haskell setting and does not use any subdirectory settings...
