### ISSUE TITLE
Bullet points in hover

### ISSUE THREAD

**Issue by bubba** [haskell/haskell-language-server#142]
There's these funky bullet points in the hover request that render quite weirdly in VS code

<img width="504" alt="image" src="https://user-images.githubusercontent.com/2488460/83412542-29732500-a412-11ea-96c1-68625b69d15b.png">

I presume these aren't meant to be there? Or at least formatted differently

**Comment by jneira** [comment]
I've noticed them too, i think they come from the upstream ghcide/hls

**Comment by googleson78** [comment]
unrendered, for reference:
![2020-06-01-164159_481x188_scrot](https://user-images.githubusercontent.com/8667384/83414900-ea030380-a426-11ea-84a4-4e18e1e33859.png)

**Comment by alanz** [comment]
I put them there.  The default rendering of "* * *" in emacs-lsp is broken, it makes the hover window take up the entire width of the frame

**Comment by alanz** [comment]
See https://github.com/alanz/ghcide/commit/02740c8375ad2894c8ed71200d3a02d51cd3133d

**Comment by bubba** [comment]
Ah, I see now that these used to be horizontal rules. But I'm not even sure if VS code rendered them properly either in the first place: I just tested out `* * *` again and I'm getting this

<img width="652" alt="image" src="https://user-images.githubusercontent.com/2488460/83455269-880dc280-a455-11ea-95ca-f4053c5822f5.png">

Perhaps the ultimate horizontal rule is just a `\n`. But hopefully the clients will get around to fixing this at some point, at which we can maybe switch back. https://github.com/microsoft/vscode/issues/98982

**Comment by alanz** [comment]
well, if the bullet does not work, a newline is an option.

**Comment by alanz** [comment]
FYI, the emacs issue is at https://github.com/emacs-lsp/lsp-ui/issues/442

**Comment by bubba** [comment]
https://github.com/haskell/haskell-language-server/pull/150

**Comment by bubba** [comment]
The HRs have been fixed in vscode now
