### ISSUE TITLE
Import suggestions for out of scope type class methods in instance declarations

### ISSUE THREAD

**Issue by Jashweii** [haskell/haskell-language-server#1423]
Example:
```Haskell
data X = X
instance Semigroup X where
  (<>) _ _ = X
  -- stimes is not imported
  stimes _ _ = X
```
HLS should suggest importing stimes (it does if instead used in an expression), and should probably import when using the "add placeholders for <type class complete set>". (Note it could be a qualified import.)

(GHC 8.10.4, cabal 3.2.0.0, stack 2.5.1 (unused), hls 0.9.0.0 (built from latest source), vscode)

**Comment by July541** [comment]
Close and continue in a smaller scope. #3017
