### ISSUE TITLE
Document the Haskell Language Server versioning policy

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#1434]
It's clearly not the PVP, so it ought to be documented somewhere for the sake of future contributors and maintainers.

The documentation should include answers for the following questions:

1. Motivation for deviating from the PVP, and tradeoffs
2. Specification: lower bounds, upper bounds, and version bumps, for all the categories of packages. 
  There are 3 categories imho: 
    1. core packages 
    2. plugin packages
    3. the HLS package
3. Examples of releases that involve interactions with Hackage: 
    1. Major release 
    2. Bug fix release for core packages
    3. Bug fix release for plugin packages
    4. Bug fix release for HLS

**Comment by jneira** [comment]
We are following pvp almost strictly in practice, not sure if it still is needed to document it somewhere

**Comment by pepeiborra** [comment]
That's great news, will close then
