### ISSUE TITLE
Is binary of 1.0 release for GHC 8.10.4 missed?

### ISSUE THREAD

**Issue by fishtreesugar** [haskell/haskell-language-server#1437]

**Comment by vaclavsvejcar** [comment]
I'm having the same issue, still getting error about `0.9.0` not being available instead of downloading `1.0.0`.
<img width="453" alt="Snímek obrazovky 2021-02-24 v 12 18 58" src="https://user-images.githubusercontent.com/5843430/108993164-7b439580-769a-11eb-9acd-d13299e32430.png">

**Comment by jneira** [comment]
> Maybe because the 1.0.0 is here on GitHub still as pre-release?

That is exactly the reason, we will mark it as definitive asap

**Comment by waldganger** [comment]
Hi, I have the same problem on Windows 10. I am new to Haskell, the language server will be of a great help to me !
![vscode](https://user-images.githubusercontent.com/39879951/109111591-7c77cf80-7739-11eb-80b7-e3e22972180a.jpg)

**Comment by Ailrun** [comment]
Now 1.0.0 is truely released, and it should be available.

**Comment by jneira** [comment]
So i think we can close this one, we'll see if any windows user needs 8.8.4 and cant upgrade to 8.10.4
