### ISSUE TITLE
A compilation issue when providing wrong kinded type parameter

### ISSUE THREAD

**Issue by theobat** [haskell/haskell-language-server#144]
Hi there,

I faced this weird bug while working on my project massalia:

```
Compilation Issue
lookup_final_id

$fGSQLRecordqueryFormatfilterType:*:
Call stack:
    CallStack (from HasCallStack):
      callStackDoc, called at compiler/utils/Outputable.hs:1159:37 in ghc:Outputable
      pprPanic, called at compiler/main/TidyPgm.hs:201:12 in ghc:TidyPgm
Please report this bug to the compiler authors.

```
The real compiler error from stack is this:
```
➜  massalia git:(master) ✗ stack build
massalia> configure (lib)
Configuring massalia-0.1.0.0...
massalia> build (lib)
Preprocessing library for massalia-0.1.0.0..
Building library for massalia-0.1.0.0..
[24 of 25] Compiling Massalia.SQLClass

/Volumes/volume_code/code/perso/massalia/src/Massalia/SQLClass.hs:556:47: error:
    • Expecting one more argument to ‘a’
      Expected a type, but ‘a’ has kind ‘* -> *’
    • In the type ‘a’
      In the first argument of ‘(<>)’, namely ‘gfullTopSelection @a name’
      In the expression:
        gfullTopSelection @a name <> gfullTopSelection @b name
    |
556 |   gfullTopSelection name = gfullTopSelection @a name <> gfullTopSelection @b name
    |                                               ^


--  While building package massalia-0.1.0.0 using:
      /Users/theophile/.stack/setup-exe-cache/x86_64-osx/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3 --builddir=.stack-work/dist/x86_64-osx/Cabal-3.0.1.0 build lib:massalia --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

This is a file (https://github.com/theobat/massalia/blob/master/src/Massalia/SQLClass.hs) which contains a lot of Generic code and type-classes. It seems the problem specifically regards the kind mismatch (I do not face any problem if the kind of the type parameter match the expected). 

PS: I reported the bug because it said so in the message, but it's not blocking me or anything, I'll try to provide a minimal reproducible case but I don't know when I'll find the time to do so...

**Comment by wz1000** [comment]
I suspect this might have to do with hls passing `-fdefer-type-errors` to ghc. I am unable to build your project, could you check passing this flag to ghc or ghci? If you get the same error, this is probably a ghc bug.

**Comment by theobat** [comment]
So I tried to reproduce this in a dedicated file and failed (for now)... I can't make HLS fail like it did maybe it's related to a subtle combination of language pragma, but it's more complicated than I thought:

```
-- This does not fail
{-# LANGUAGE KindSignatures #-}
{-# LANGUAGE MultiParamTypeClasses #-}

module Lib where

class TestHLSError (a :: * -> *) b where
    qsd :: a b -> b

instance TestHLSError String String where
    qsd = undefined
```

**Comment by theobat** [comment]
So a tried to reproduce using the example given at https://github.com/digital-asset/ghcide/issues/406, using the same example with ghc 8.8.3 & stack yields no error, but a very close example give indeed the same error:

```haskell

module Lib where

class TestHLSError a where
    qsd :: a String

instance TestHLSError IO where
    qsd = undefined @(IO String)
```

And indeed @wz1000 it does panic GHC using `stack build --ghc-options -fdefer-type-errors`(and does not panic without the defer error). Now,I'm not sure it's exactly the same as my initial error, but I'm pretty confident it was similar enough to be the same cause.
