### ISSUE TITLE
Add FUNDING file to link to OpenCollective 

### ISSUE THREAD

**Issue by MaxGabriel** [haskell/haskell-language-server#1440]
Github allows you to add a FUNDING file to link to the OpenCollective project for HLS:

https://docs.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository#about-funding-files
https://opencollective.com/haskell-language-server

I think adding this would be easy, lend legitimacy to the OpenCollective project, and encourage more people to sponsor

**Comment by Ailrun** [comment]
Actually, I didn't know that we already have an OpenCollective account. @alanz, @ndmitchell, @mpickering, is the account used actively?

**Comment by isovector** [comment]
This is the one I was told to support at.
