### ISSUE TITLE
Include hls ./install script when loading haskell-language-server with itself

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#145]
* From #121
* The install script lives under the subdirectory `install` and it does not belong to the main project (it is not a component or a subppackage of hls)
  * This was on purpose, to isolate it and use its own dependencies, resolver, etc
* So if you load haskell-language-server on itself it is not able to load the install script, even if you add it in the `hie.yaml`
* The workaround is open directly the `install` subdir in other editor  window
* @Sir4ur0n [suggested](https://github.com/haskell/haskell-language-server/issues/121#issuecomment-634997748 ) that it would be better to make possible open all the haskell code in the same editor "session"
  * though a change in `hie-bios` to make it able to load different stack (and cabal) projects with the same config

**Comment by Sir4ur0n** [comment]
Thank you for creating this dedicated issue for the `./install` folder!

> though a change in hie-bios to make it able to load different stack (and cabal) projects with the same config

I'm sorry, I'm not sure I understand what you mean. Is it already supported by `hie-bios`? Or is it a prerequisite?
If so, is there already such an issue in `hie-bios` repo?

**Comment by jneira** [comment]
> I'm sorry, I'm not sure I understand what you mean. Is it already supported by `hie-bios`? Or is it a prerequisite?
> If so, is there already such an issue in `hie-bios` repo?

It is not supported by hie-bios and it would be a prerequisite for use hls main project and install withint an unique `hie.yaml`. I am afraid there is no issue about.

**Comment by Sir4ur0n** [comment]
Thank you!

In https://github.com/haskell/haskell-language-server/pull/147 I have marked the `./install/` directory with a `none` cradle, so that whoever opens the full `hls` project in any editor will not get any error. This is the best I could think of until hie-bios supports multi-stack project.

**Comment by Sir4ur0n** [comment]
I just opened https://github.com/mpickering/hie-bios/issues/191 to track this feature.

**Comment by jneira** [comment]
As @mipckering [suggested](https://github.com/mpickering/hie-bios/issues/191#issuecomment-639151690) we could use a `./install/hie.yaml` to load them and add a specific `./install/hie.yaml.cbl` and `./install/hie.yaml.stack` in the repo if it works

**Comment by Sir4ur0n** [comment]
Yes that was my intention too, I'll try Matt's solution tonight and if it works, I will adapt my PR accordingly
