### ISSUE TITLE
Parser error on the `-- $` chain of characters

### ISSUE THREAD

**Issue by Sir4ur0n** [haskell/haskell-language-server#148]
While trying to fix the `hie.yaml` for #121 I noticed 2 tests have a parsing error.

The guilty seems to be the `-- $` chain of characters **in an implementation of function**

Minimal example:
```haskell
foo :: ()
foo =
  let bar = ()
  -- some comment
  -- $ some other comment
   in bar
```

The line `  -- $ some other comment` has an error:

```
/home/sir4ur0n/code/haskell-language-server/src/Ide/Plugin/Ormolu.hs:42:3: error:
    parse error on input ‘-- $ some other comment’parser
```

![image](https://user-images.githubusercontent.com/1204125/83815976-a4ae3280-a6c1-11ea-87aa-71736a8c92e3.png)

**Comment by googleson78** [comment]
[Related (?) issue in ghicde](https://github.com/digital-asset/ghcide/issues/573)

**Comment by Sir4ur0n** [comment]
Indeed, this is the same root cause. E.g. running `stack haddock` on such code results in an error:
```
Running Haddock on library for foobar-0.1.0.0..

src/Lib.hs:9:3: error: parse error on input ‘-- $’
  |
9 |   -- $
  |   ^^^^
Haddock coverage:
```

I am not familiar with how HLS is managed: should we keep this issue open? Or close it as it is "only" an underlying issue?

**Comment by fendor** [comment]
Keep it open, so that others see that the issue is known and even being worked on.

**Comment by Sir4ur0n** [comment]
As explained in https://github.com/digital-asset/ghcide/issues/573#event-3423705019 the root cause is Haddock failing + Ghcide considering (in the past) Haddock parsing errors as errors (now downgraded to warnings + "Haddock" is now visible in the error message.

I guess this issue can be closed as soon as HLS refers to a version of GHCIDE with [this commit](https://github.com/digital-asset/ghcide/commit/154e57fdda7f32745dd7904878084af59eafc751)

**Comment by Sir4ur0n** [comment]
I just tested with HLS 0.3 and the issue seems to be fixed, I propose we close this. Thank you everyone!
