### ISSUE TITLE
How to run HLS on HLS?

### ISSUE THREAD

**Issue by mpardalos** [haskell/haskell-language-server#1503]
Is there a recommended way to develop HLS? I am trying to work on HLS with the latest HLS from ghcup and I am having trouble getting it to work. Starting from a clean clone on master (9bd09280790ad5813cf605de7a6178fa3d51a89e) and doing
```sh
cp stack-8.10.4.yaml stack.yaml
haskell-language-server-wrapper
```
Ends with 
```
Completed (0 files worked, 473 files failed)
```
And gives these errors for a very large number of files:
```
2021-03-05 19:54:54.518123337 [ThreadId 7342] INFO hls:	File:     /home/mpardalos/Documents/haskell-language-server/ghcide/src/Development/IDE/Plugin.hs
Hidden:   no
Range:    1:1-2:1
Source:   compiler
Severity: DsError
Message:  target ‘mainlike’ is not a module name or a source file
```

Is there more steps than this to setting up HLS for HLS? Should I be adding an hie.yaml? If so, shouldn't there be a guide for new contributors detailing these steps? I would be willing to write up such a guide. 

### Your environment
Output of `haskell-language-server-wrapper --probe-tools`:
```
haskell-language-server version: 1.0.0.0 (GHC: 8.10.4) (PATH: /home/mpardalos/.ghcup/bin/haskell-language-server-wrapper-1.0.0) (GIT hash: 4cd1cf934638881e52b3eba9f70157a4b799c0e9)
Tool versions found on the $PATH
cabal:		3.4.0.0
stack:		2.3.3
ghc:		8.10.4
```
Which lsp-client do you use: emacs with emacs-lsp

**Comment by Ailrun** [comment]
It works well when I run it with default `stack.yaml` (I'm also using Emacs with `lsp-mode`) without `hie.yaml`, although we need `hie.yaml` at least for plugins devs. It would be great if you can send us a PR for the guide.

**Comment by mpardalos** [comment]
It seems to work with 8.6.5 for me as well. It is weird that the other versions are broken. It would be useful if someone else could try to reproduce this.

**Comment by jneira** [comment]
Now we are using 8.10.4 in the default `stack.yaml`, does it continue causing problems @mpardalos?

**Comment by jneira** [comment]
@mpardalos i am gonna close this one, feel free to reopen if you continue expereincing the bug with actual master
