### ISSUE TITLE
Possible to pass options to HLint?

### ISSUE THREAD

**Issue by tfausak** [haskell/haskell-language-server#1509]
I have my HLint config in a non-standard location. Is it possible to pass `--hint my-hlint-config.yaml` through to HLint? Without it I get only the default hints.

**Comment by jneira** [comment]
Hi, i've transferred the issue to haskell-language-server, as it is the responsive for hlint integration (concretely the hls-hlint-plugin).

Actually there is no way to pass that option to hlint plugin but i think it could be a nice addition, the code that loads the hlint config is here:

https://github.com/haskell/haskell-language-server/blob/1b245caddbcffd39db6419bd56c80fc54a4fa678/plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs#L261-L266

And it would need to add a config option in a still missing specific section for hlint, like tactics has done here:

* getting the config

https://github.com/haskell/haskell-language-server/blob/1b245caddbcffd39db6419bd56c80fc54a4fa678/plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/LanguageServer.hs#L86-L91

* with type 
https://github.com/haskell/haskell-language-server/blob/db7234895e765a51a832992513f210eee4c4bbdd/plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Types.hs#L86-L90

**Comment by rmehri01** [comment]
Hi, I'd like to help out with this if possible!

**Comment by jneira** [comment]
@rmehri01 nice! tha main steps are sketched in the above comment. The configuration structure has changed so it does the way to deal with it, i will update this with the relevant code sites

**Comment by rmehri01** [comment]
I think I got the basic idea of what to do since I got it compiling but when I was testing to see if it works I ran into [this FIXME](
https://github.com/ndmitchell/hlint/blob/792514dc9a92e7bacac1fd336372731dbd0c038f/src/Language/Haskell/HLint.hs#L75-L87) for `argsSettings`, which `getHlintSettingsRule` calls. Does this mean `--hint` will not work with it?

**Comment by jneira** [comment]
@rmehri01 many thanks for continue working on this, sorry but i had no time to update links to actual code

> Edit: looks like this issue might be related but for everything instead of just --hint.

Not sure about that one, i can see `(parseFlags, _, _) <- argsSettings [ "-XQuasiQuotes" ]` works in that issue (so it works at least for lang exts args)

> I ran into this FIXME for argsSettings, which getHlintSettingsRule calls. Does this mean --hint will not work with it?

It is possible (maybe @ndmitchell could help us confirming it). However, i would continue working on this, we could improve hlint support threrafter.

**Comment by ndmitchell** [comment]
I suspect that FIXME isn't relevant. However, the issues in https://github.com/ndmitchell/hlint/issues/1232 might well be relevant. It looks like the HLint configuration stuff as currently exposed has some weird issues.

**Comment by rmehri01** [comment]
Ah I see, `getHlintSettingsRule` only seems to be called with `getHlintSettingsRule (HlintEnabled [])`, so I changed to using `autoSettings` instead and now passing the custom config works! 

The only thing is that `autoSettings` doesn't seem to support other settings like `argsSettings` does, so do we still want to be able to add other settings too?

**Comment by jneira** [comment]
> Ah I see, `getHlintSettingsRule` only seems to be called with `getHlintSettingsRule (HlintEnabled [])`, so I changed to using `autoSettings` instead and now passing the custom config works!

mmm, not sure without taking a look to actual code but my idea was change `getHlintSettingsRule (HlintEnabled [])` for
`getHlintSettingsRule (HlintEnabled listOfArgsFromLspConfig)`, so we could continue using `argsSettings`, which would use the list of args supplied in the config

**Comment by rmehri01** [comment]
> mmm, not sure without taking a look to actual code but my idea was change `getHlintSettingsRule (HlintEnabled [])`
> for `getHlintSettingsRule (HlintEnabled listOfArgsFromLspConfig)`, so we could continue using `argsSettings`, which would use the list of args supplied in the config

Yeah this would definitely be easier and it was what I was trying at first, but I keep running into this error when using `argsSettings` with `--hint`, which is why I thought the FIXME was initially relevant:
```
*Ide.Plugin.Hlint Language.Haskell.HLint> argsSettings ["-h my-hlint-config.yaml"]
*** Exception: user error (Failed to find requested hint files:
   my-hlint-config.yaml
)
```
I tried using different file paths to make sure too. I might be doing something wrong though, I'm not sure.

> However, i would continue working on this, we could improve hlint support threrafter.

So to clarify, you think it is better to do it this way for now, even though `--hint` might not work and then it can be improved in the future?

**Comment by jneira** [comment]
> Yeah this would definitely be easier and it was what I was trying at first, but I keep running into this error when using argsSettings with --hint, which is why I thought the FIXME was initially relevant

Mmm i think it worths to take a deeper look to at least to know why it does not work and ensure it comes from an hlint bug.

> So to clarify, you think it is better to do it this way for now, even though --hint might not work and then it can be improved in the future?

sure, go ahead, we can continue discussing possible alternatives in the pull request. Only want to note we usually ask for some new test case demonstrating the new feature (but you can open it as draft anyways)
