### ISSUE TITLE
ghcide missing upper bound on haddock-library (breaks HLS 0.9.0.0)

### ISSUE THREAD

**Issue by hamishmack** [haskell/haskell-language-server#1525]
Please add `haddock-library <1.10` to [ghcide-0.7.3.0](https://hackage.haskell.org/package/ghcide-0.7.3.0).  Without this upper bound, building HLS 0.9.0.0 picks `haddock-library` 1.10 and `ghcide` fails to build as a result.

**Comment by jneira** [comment]
I added it to 0.7.5.0  before 1.0.0.0 was released but no for the rest, will do

**Comment by jneira** [comment]
Thanks for report the issue, added for [0.7.3.0](https://hackage.haskell.org/package/ghcide-0.7.3.0/revisions/) and [0.7.4.0](https://hackage.haskell.org/package/ghcide-0.7.4.0/revisions/)
