### ISSUE TITLE
output error brittany at code has list comprehension

### ISSUE THREAD

**Issue by insight1111** [haskell/haskell-language-server#1528]
version: 1.28.0-insider (user setup)
commit: 431ef9da3cf88a7e164f9d33bf62695e07c6c2a9
date: 2018-10-03T12:44:29.343Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

hie verison: Version 0.2.2.0, Git revision 881f2b3b737c34f72fffa3bec94f08f256f0d6fe (2000 commits) x86_64 ghc-8.4.2

code example:

``` haskell
a::[Int]
a=[x|x<-[1..3]]
```

get output

```
[Error - 7:19:30 AM] Request textDocument/formatting failed.
  Message: brittanyCmd: RealSrcSpan SrcSpanMultiLine "stdin" 2 6 3 1: unterminated quasiquotation at end of input

  Code: -32603 
```

but when i use brittany that separately install, no error occurs.(version brittany version 0.9.0.0)
is it a brittany bug? or hie? or vscode-hie-server?

**Comment by jneira** [comment]
@insight1111 @patrickaldis is this still being reproduced with last hls?

**Comment by jneira** [comment]
I cant reproduce with last hls version, fomatting with brittany gives me:

```haskell
a :: [Int]
a = [ x | x <- [1 .. 3] ]
```

so i am gonna close it, feel free to reopen if you continue experiencing it
