### ISSUE TITLE
Hoogle plugin

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#153]
* hie used hoogle to show docs on libraries other than boot ones or local ones
* now we need to build with docs enabled for dependencies to get them:
  * we would have to mention that in the readme
  * the built is almost twice slower and you got sometimes haddock errors
* In hie the code lived here: https://github.com/haskell/haskell-ide-engine/blob/master/src/Haskell/Ide/Engine/Support/Hoogle.hs
  * And was used for completions: https://github.com/haskell/haskell-ide-engine/blob/master/src/Haskell/Ide/Engine/Completions.hs
  * And for show docs: https://github.com/haskell/haskell-ide-engine/blob/master/src/Haskell/Ide/Engine/Plugin/Haddock.hs

But now it is ghcide the source for docs and completions, would be feasible add hoogle as backport for both externally? could we examine the result for both and replace them if they are empty?

**Comment by fendor** [comment]
The plugin itself is not that important, but the support functions are required by #155 and #156

**Comment by expipiplus1** [comment]
One nice reason to use Hoogle for fetching docs is that nix has very good support for generating a Hoogle database of all dependencies.

**Comment by jneira** [comment]
Not sure if the plugin makes sense anymore

> But now it is ghcide the source for docs and completions, would be feasible add hoogle as backport for both externally? could we examine the result for both and replace them if they are empty?

So i am gonna close this
