### ISSUE TITLE
Stale error displayed in VScode

### ISSUE THREAD

**Issue by FrancisToth** [haskell/haskell-language-server#1530]
Hi guys, Haskell noob here. I start playing with VSCode (1.40.2) and Haskell IDE Engine (0.14.0.0) with Haskell Language Server (0.0.31) , and got a really weird behaviour. Given the following code:
```haskell
module Chap9
    ( 
    )
where

loop3 :: (String, String) -> [String]
loop3 (_, (_ : _)) = loop3 $ ([], [])

foo :: String -> String
foo s = s
```
If I add another function named like `foo`
```haskell
foo :: String -> String
foo s = s
```
wait for the error to be displayed, and then fix the name of the duplicated function like this:
```haskell
foo2 :: String -> String
foo2 s = s
```
the code compiles (when loaded from the terminal) but the editor still shows the stale error telling there are multiple declarations of `foo`.   I do not get the error if the `loop3` function is declared like this:
```haskell
loop3 :: (String, String) -> [String]
loop3 (_, _ : _) = loop3 $ ([], [])
```
So it looks like the problem comes from pattern matching but I cannot explain why. If this is not the right place to talk about this, I sincerely apologize. In any case, thank you in advance.

**Comment by jneira** [comment]
In fact hls does not have the quick fix for duplicate functions so the error cant be evene reproduced :worried:

**Comment by jneira** [comment]
Opened feature request, i hope the bug will be not present when it will be added :wink: https://github.com/haskell/haskell-language-server/issues/1532
