### ISSUE TITLE
Honour or remove "maxNumberOfProblems" configuration option

### ISSUE THREAD

**Issue by bubba** [haskell/haskell-language-server#1534]
As I was looking through the VS Code extensions API documentation, I found that the maxNumberOfProblems configuration option is lifted straight from the [example extension that they provide](https://code.visualstudio.com/api/language-extensions/language-server-extension-guide#explaining-the-language-client). It looks like it may have been accidentally leftover when setting up the boilerplate

I'm not sure how useful such a configuration option is in practice, and does haskell-language-server/ghcide still support this?

**Comment by ndmitchell** [comment]
I'd rather delete it - I doubt anyone sets it custom, and less configuration is always less testing.
