### ISSUE TITLE
Files for golden test missing in hackage release of hls-tactics-plugin

### ISSUE THREAD

**Issue by maralorn** [haskell/haskell-language-server#1536]
When packaging hls-tactics-plugin in nixpkgs, I tried to run the tests to make sure it works fine.
The golden tests all fail because of missing golden files.

### Steps to reproduce

Get hls-tactics-plugin from hackage and run the golden tests.

### Expected behaviour

They pass.

### Actual behaviour

They don‘t.

### Include debug information

Release: 1.0.0.0

**Comment by jneira** [comment]
pull request adding test data files: #1605
