### ISSUE TITLE
Add LSP kinds to "import" code actions

### ISSUE THREAD

**Issue by isovector** [haskell/haskell-language-server#1556]
The current "import" code actions are pretty overwhelming, especially for commonly used names. We get the cartesian product of `matches` x `styles`.

I'd like to suggest we export `import Foo.Blah` under the kind `quickfix.import.module` and `import Foo.Blah (what)` under `quickfix.import.definition`. Users can then opt-in to their preferred style, and users/clients who don't care will still see today's behavior.

**Comment by uhbif19** [comment]
How this could be filtered in editor?
