### ISSUE TITLE
Change "About" description.

### ISSUE THREAD

**Issue by friedbrice** [haskell/haskell-language-server#1557]
This is hopefully an easy one.

Can we please change the repository description, which shows up under the heading "About" in Github's UI

It currently reads: "Integration point for ghcide and haskell-ide-engine. One IDE to rule them all."

This description is confusing to people who are unfamiliar with the project history and could lead them to mistakenly believe that Ghcide and HIE are runtime dependencies of HLS.

<img width="885" alt="Screen Shot 2021-03-11 at 12 29 20 PM" src="https://user-images.githubusercontent.com/3302003/110851190-9222e400-8265-11eb-8aa9-1d4aa88e967a.png">

**Comment by Ailrun** [comment]
(FYI, GHCIDE is actually a dependency, though HIE is not)

**Comment by Anrock** [comment]
"Successor of ghcide & haskell-ide-engine. One IDE to rule them all"

And I still it's kinda silly to mention IDE in HLS descriptions because it's language server, not IDE 🤔

**Comment by jneira** [comment]
I like @Anrock suggestion, will change the about description in some hours if nobody disagree or have another proposal
//cc @Ailrun @friedbrice

**Comment by jneira** [comment]
Description changed!
