### ISSUE TITLE
Add code action for hiding imports

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-language-server#156]
Initially taken from: https://github.com/haskell/haskell-ide-engine/issues/1191

> It would be nice if there was a code action for hiding imports which are unused and being shadowed by local declarations.
>
> This is complicated because it requires some detailed information on the provenance of these names in order to hide them (for example if they are record fields).
> An example:
>
> Given the following warning:
> 
> ```
> triangle/Main.hs:83:26: warning: [-Wname-shadowing]
>     This binding for ‘window’ shadows the existing bindings
>       imported from ‘Graphics.Vulkan’ at triangle/Main.hs:(29,1)-(45,59)
>       (and originally defined in ‘Graphics.Vulkan.Extensions.VK_NN_vi_surface’)
>       imported from ‘Graphics.Vulkan’ at triangle/Main.hs:(29,1)-(45,59)
>       (and originally defined in ‘Graphics.Vulkan.Extensions.VK_KHR_xlib_surface’)
>       imported from ‘Graphics.Vulkan’ at triangle/Main.hs:(29,1)-(45,59)
>       (and originally defined in ‘Graphics.Vulkan.Extensions.VK_KHR_xcb_surface’)
>       imported from ‘Graphics.Vulkan’ at triangle/Main.hs:(29,1)-(45,59)
>       (and originally defined in ‘Graphics.Vulkan.Extensions.VK_KHR_android_surface’)
> ```

As a first step, we can try to implement a mechanism to hide a symbol that is name shadowing and can improve this with some time!

There are two different implementation paths ahead:
* Porting the [Hsimport Plugin](https://github.com/haskell/haskell-ide-engine/blob/master/src/Haskell/Ide/Engine/Plugin/HsImport.hs) and adding suitable code-actions (might be hard since the hsimport plugin is a complicated piece of software)
* Modifying the import suggestion logic of ghcide: https://github.com/digital-asset/ghcide/blob/master/src/Development/IDE/Plugin/CodeAction.hs#L140

**Comment by pepeiborra** [comment]
I think this was closed by mistake, #1193 seems unrelated

**Comment by alanz** [comment]
HLS at 0fd73f8494d488cf20159c7cc068f3e73d497565 gives really good code actions for resolving ambiguous functions

<img width="504" alt="Screenshot 2021-02-05 at 11 01 22" src="https://user-images.githubusercontent.com/409607/107028985-349f0180-67a6-11eb-97de-204399e8bf4a.png">

It would be great to see the same machinery modified for name shadowing cases. At the very least to hide the imported clashing name if it is not actually used in the file.
