### ISSUE TITLE
Feature idea: alternate format for numeric literals

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-language-server#1560]
The rust language server has a code action that provides alternative formats for numeric literals, in different bases.

<img width="528" alt="Screenshot 2021-03-12 at 10 01 06" src="https://user-images.githubusercontent.com/409607/110924593-22226580-831a-11eb-85b0-edb893c76386.png">

This might be something to consider for haskell

**Comment by jneira** [comment]
@drsooch great, thanks for willing to contribute. The docs i've found about numeric literals are:
* numeric literals from the haskell 2010 language report: https://www.haskell.org/onlinereport/haskell2010/haskellch2.html#x7-190002.5
* the ghc extensions about literals: http://downloads.haskell.org/~ghc/latest/docs/html/users_guide/exts/literals.html
  * extensions should be enabled to allow the different literal syntaxes
