### ISSUE TITLE
ghcide-tests hang when running inside nix build

### ISSUE THREAD

**Issue by maralorn** [haskell/haskell-language-server#1562]
### Steps to reproduce
I take the current derivation ghcide 1.0.0.0 out of nixpkgs master and enable `doCheck` on it and run the build.

### Expected behaviour
The tests pass.

### Actual behaviour
The build stalls on `Test suite ghcide-tests: RUNNING....`.

The process monitor tells me I have two zombified `ghcide` process as children of `ghcide-tests` without any cpu activity.

If this is something that only happens inside nix, it’s obviously not so much your problem. But I‘d like to know if anyone else has observed this (outside of nix) or knows how it could be prevented.

**Comment by pepeiborra** [comment]
Most likely #727

**Comment by maralorn** [comment]
Thank you! Closing as duplicate.
(I had only looked for issues concerning the tests.)
