### ISSUE TITLE
Add code action to add unused function to export list

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-language-server#157]
When you have an unused function and an explicit export list in your module it would make sense to offer a code action to add the function to the explicit export list! 

Implementation could be done similar to the code in: https://github.com/digital-asset/ghcide/blob/master/src/Development/IDE/Plugin/CodeAction.hs#L140

**Comment by sureyeaah** [comment]
Can I take this one?

**Comment by fendor** [comment]
@sureyeaah Please do! 
IIRC, @pepeiborra said that this feature should be added to ghcide. 
I think it will be easier in ghcide, as there is example code, and you dont have to understand the plugin system of HLS yet. 
In my opinion, either is fine and can be moved to either project if necessary.

**Comment by pepeiborra** [comment]
The path of least resistance would be ghcide, because that's where all the code actions currently live. Indeed, some of the more heavy weight code actions in ghcide, like the Suggest Imports one, should probably be extracted to hls too.

**Comment by sureyeaah** [comment]
So I'm handling top level variable definitions, newtype/data types/type classeswhile exporting all(e.g. X(..)), type synonyms and pattern synonyms. I'm not dealing with constructors explicitly since that would involve finding the corresponding type in the exports first. Thoughts?

**Comment by sureyeaah** [comment]
Merged in ghcide.

**Comment by bubba** [comment]
You can make a PR to hls to cherry-pick the changes on top of the ghcide submodule, or wait until we eventually get it synced back up with digital-asset/master

**Comment by sureyeaah** [comment]
This has been merged in hls master.

**Comment by fendor** [comment]
Closed by #348
