### ISSUE TITLE
Upgrade ghcide

### ISSUE THREAD

**Issue by vagifverdi** [haskell/haskell-language-server#159]
ghcide has improvements both for space leaks and performance: https://mpickering.github.io/ide/posts/2020-06-12-performance-of-ghcide-020.html

When can these improvements be folded into haskell-language-server?

**Comment by wz1000** [comment]
See https://github.com/haskell/haskell-language-server/pull/160/files

**Comment by jneira** [comment]
Maybe we could close this one, it seems the requested improvements has been included with #160
