### ISSUE TITLE
VSCode haskell language server cannot detect GHC installed by stack

### ISSUE THREAD

**Issue by zhangqian-sh** [haskell/haskell-language-server#1593]
I am using VSCode Remote Development Kit to run haskell on a Linux Server. I have installed GHC with stack, and added the GHC path to .bashrc and .profile. However, when I open a haskell file, VSCode will prompt a window says "Project requires ghc but it isn't installed." But I can run GHC from the terminal with in the VSCode.

System Info: Ubuntu 20.04 LTS, GHC 8.10.4, VSCode 1.54.3, VSCode Remote Development 0.20

Besides, it seems that the extension does not have an entry for setting GHC path, is it possible to add that? So that I can manually set the path. Thank you very much!

**Comment by Ailrun** [comment]
If you do not have a project setting, this issue is a duplicate of #692.

**Comment by zhangqian-sh** [comment]
Thank you for the post! Actually I have GHC in PATH, but after using stack to create a new project and opening the project folder with VSCode, I can use the the extension now. I hope the the feature of opening single file with stack will be implemented soon.

**Comment by zhangqian-sh** [comment]
I have found that after the first time I opened a stack project, the plugin will download another binary. Then it will be able to work with standalone files (linting, etc.) since GHC is in my PATH. This behavior is strange. But my problem is solved now. Thank you for your help!
