### ISSUE TITLE
Naming of homomorphic split Wingman command

### ISSUE THREAD

**Issue by santiweight** [haskell/haskell-language-server#1600]
The Homomorphic split command on Wingman, while making sense, is an opaque name to anyone less familiar with category theory etc. A potentially better option is for the Wingman command displayed to be based on the type of the functor in question. For example, if splitting on a variable "var" of type Either, the command might look like:

     Wingman: map var to Either

See #1582 for more discussion

**Comment by santiweight** [comment]
I'm not sure how to tag this as Wingman/improvement or assign to @isovector but we should do that :)

**Comment by isovector** [comment]
I'd like some other ideas for the naming scheme here. The major moving pieces here are the name of the variable and the type constructor in question. For each data constructor `C` of the type constructor, we want to construct a match of the form:

```haskell
    C a b -> C _ _
```

**Comment by santiweight** [comment]
Another suggestion: "Wingman: map constructor fields"
