### ISSUE TITLE
Wingman gets slow on big modules

### ISSUE THREAD

**Issue by isovector** [haskell/haskell-language-server#1602]
Even for things like "refine hole" which should be instant. My guess is that waiting for a fresh type-checking result is to blame. We could probably get away with using stale data instead.

**Comment by pepeiborra** [comment]
GHC is *very* slow at typechecking holes. Even Wingman used stale data, the default ghcide code action handler would still be slow and bottleneck the code action response

**Comment by pepeiborra** [comment]
Let me insist on playing with the settings we use - `Opt_SortBySubsumHoleFits` was only "fast enough" for occasional use, and maybe that's no longer good enough

**Comment by isovector** [comment]
@pepeiborra my understanding is that we currently use the hole fit suggestions to fill in the `replace _ with <whatever>` code actions, and I'm a little scared to break that.

**Comment by pepeiborra** [comment]
Some of those options, like `Opt_SortBySubsumHoleFits`, may not be worth the computational cost. So by all means feel free to tweak them and test the results! At the very least we could expose a config option to enable users to decide

**Comment by isovector** [comment]
I've had all hole fits turned off globally since 2018 for exactly this performance reason :)

**Comment by isovector** [comment]
Was playing around with this today, and typechecking is significantly (and _noticeably_) faster having disabled the hole fit suggestions. Seeing as they mostly suggest things like `replace _ with id _`, I think the performance gains here more than make up for the slight loss of functionality.

**Comment by anka-213** [comment]
Was the performance still too bad after disabling `Opt_SortBySubsumHoleFits`? I would much prefer disabling that and maybe refinement hole fits over disabling type hole fits entirely.

**Comment by isovector** [comment]
@anka-213 I just tried that this morning, and the behavior is still wicked slow. After case-splitting a `HsExpr GhcPs`, having hole-fit (even without subsumption holes) suggestions on takes upwards of 1 minute. And this gets invalidated on every keystroke. Comparatively, disabling all hole-fits means the code actions come up in <1 second.

**Comment by anka-213** [comment]
Ah, that's too bad! Thanks for testing it!

**Comment by anka-213** [comment]
I think the feature is most useful for things imported from elsewhere that I didn't realize would fit the hole. For example like this: https://twitter.com/idontgetoutmuch/status/1390258191511007233

So I'm not sure how much that would help.

**Comment by pepeiborra** [comment]
How hard would be to improve the performance of hole fit suggestions in GHC?

**Comment by anka-213** [comment]
I wonder if we could do something similar to what hoogle does to create an index for external libraries?

**Comment by isovector** [comment]
@pepeiborra It's tracked here: https://gitlab.haskell.org/ghc/ghc/-/issues/16875
