### ISSUE TITLE
CI jobs of plugins' test suites got stuck randomly

### ISSUE THREAD

**Issue by berberman** [haskell/haskell-language-server#1627]
#1606 and #1612 moved plugins' test suites and created standalone CI jobs for them. However, according to the runs for recent PRs, it seemd that they got stuck randomly:

https://github.com/haskell/haskell-language-server/runs/2197372198
https://github.com/haskell/haskell-language-server/runs/2206602816
https://github.com/haskell/haskell-language-server/runs/2206604842

**Comment by pepeiborra** [comment]
You need to make sure to build with `--threaded` and have 2 or more capabilities, or we could just fix #727
