### ISSUE TITLE
Shadows can lead to confusing showings of definitions on hover.

### ISSUE THREAD

**Issue by alissa-tung** [haskell/haskell-language-server#1632]
### Your environment
```sh
haskell-language-server version: 1.0.0.0 (GHC: 8.10.4) (PATH: /home/alissa/.ghcup/bin/haskell-language-server-wrapper-1.0.0) (GIT hash: 4cd1cf934638881e52b3eba9f70157a4b799c0e9)
Tool versions found on the $PATH
cabal:          3.4.0.0
stack:          2.5.1
ghc:            8.10.4
```
VS Code

### Steps to reproduce
```haskell
data ADT id
  = Cons id
  | Cons2 id id
```

It can be solved by simply add the line:
```haskell
import Prelude hiding (id)
```
But why should we need to see the definitions of functions at a fresh variable place?

### Expected behavior
```
id
Defined at /home/alissa/Scratch/issue/Issue.hs:5:10
```

### Actual behaviour
```
id
Defined at /home/alissa/Scratch/issue/Issue.hs:5:10

id :: a -> a     -- Defined in ‘GHC.Base’
Identity function.

id x = x
```

**Comment by berberman** [comment]
Sorry, I'm not able to reproduce that. Where did you put the cursor to get the hover message in "Actual behaviour"?

**Comment by alissa-tung** [comment]
RHS of the `data ADT`.

![Screenshot_20210329_122007](https://user-images.githubusercontent.com/80032304/112786578-258f4e00-9089-11eb-89e5-ec5ad99de66b.png)

**Comment by berberman** [comment]
In my case:
![image](https://user-images.githubusercontent.com/26041945/112787070-47d59b80-908a-11eb-9907-8695d7e37496.png)

**Comment by Ailrun** [comment]
@berberman I think your cursor is on different line, yours is on line 5, where @alissa-tung's one is on line 3.

**Comment by berberman** [comment]
We use hie asts to display the information of the element on hover, where the rename and typecheck have already done -- normally, there shouldn't be ambiguity involved.

@alissa-tung I doubt if your project was loaded successfully. Did other IDE features work?

**Comment by Ailrun** [comment]
I also cannot reproduce it (with any of the cursor positions).

**Comment by alissa-tung** [comment]
I guess that's caused by another Haskell plugin… Sorry for bothering.
