### ISSUE TITLE
New Code action: add UndecidableInstances

### ISSUE THREAD

**Issue by eviefp** [haskell/haskell-language-server#1679]
It would be awesome if HLS would be able to suggest, as a quick action, adding `UndecidableInstances` like it does with many other extensions.

For example, this error message

```
src/File.hs:(75,3)-(78,51): error:
    • Illegal nested constraint ‘Cast
                                   (BasicOrderType b) (BasicOrderType b')’
      (Use UndecidableInstances to permit 
this)
    • In the instance declaration for
        ‘Cast (OrderByItemG b a) (OrderByItemGb' a')’
   |
75 |   ( Cast (BasicOrderType b) (BasicOrderType b')
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
```

**Comment by Ailrun** [comment]
I think this already works; Did you check code actions from pragmas plugin?

**Comment by vladciobanu** [comment]
I am getting some code actions to add some language pragmas, but not this one. Would a repro case help?

**Comment by Ailrun** [comment]
Yeah, that would be help. I tried to repro, but mine gives `UndecidableInstances` action as expected.

**Comment by michaelpj** [comment]
Given this didn't get confirmation, I'll close for now. Please reopen if you can confirm!
