### ISSUE TITLE
April 2021 Monthly Release

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#1681]
* It is release time! @berberman kindly has accepted driving the release this time, many thanks!
* There are quite pr activity recently and ci transient failures has delayed their handling so we have to wait to reach some stability on that side (i hope it will be soon)

**Comment by Ailrun** [comment]
Out of curiosity, where did you have such a conversation with @berberman?

**Comment by jneira** [comment]
@Ailrun sorry if i was not being transparent, we discussed that in irc/fp discord channels. The idea is the more people know about the process the better. 
Maybe we should opened the issue as a first step? will do next time

**Comment by Ailrun** [comment]
@jneira Nothing to sorry about, I was just curious about other communication channels, especially active ones.

**Comment by wolverian** [comment]
Was this meant to be released as a pre-release?

**Comment by berberman** [comment]
> Was this meant to be released as a pre-release? 

It's the routine of performing release -- once the binaries are ready, we will unmark the pre-release status

**Comment by berberman** [comment]
@jneira  Ah, CI job failed: https://github.com/haskell/haskell-language-server/runs/2321922916. What should we do next?

**Comment by jneira** [comment]
Ugh, it did not fail in the two last releases (but it did before that)
As the [document suggests](https://github.com/haskell/haskell-language-server/blob/master/docs/releases.md#failing-workflow) the safer (but maybe too careful) is recreate the tag (deleting it from the repo and creat it again from the same commit) and the prerelease from zero (deleting the actual one)
Iirc when i tried to simple rerun the build, it throwed errors cause part of the binaries already existed in the release.

**Comment by berberman** [comment]
It seems that I don't have permission to delete an existing release

**Comment by jneira** [comment]
Mmm, ok, i've set your user as "maintainer", could you see now a red button close to "Edit release" here: https://github.com/haskell/haskell-language-server/releases/tag/1.1.0?

**Comment by berberman** [comment]
yes, now I can

**Comment by jneira** [comment]
https://github.com/haskell/haskell-language-server/actions/runs/741150263
:crossed_fingers:

**Comment by berberman** [comment]
Damn it, the build failed again

**Comment by jneira** [comment]
maybe it is a persistent bug, there is not any issue with a similar problem?
unfortunately we don't test the build job between releases to check `cabal install` works correctly (and maybe we should do it)
if you trigger the build in your repo, does it fail? will try myself too

**Comment by jneira** [comment]
the GitHub actions VM images has been updated recently, maybe it is related

**Comment by berberman** [comment]
The runner `ubuntu-latest` was updated from `18.04` to `20.04` since last release. I will delete the pre-release now and try using `18.04` in my fork

**Comment by berberman** [comment]
@jneira Downgrading to `18.04` fixed this: https://github.com/berberman/haskell-language-server/runs/2325193103. So I think we have two choices now:

1. open a PR to update `build.yml`, re-tag `1.1.0` on squashed commit of the PR, and finally publish the release
2. leave `build.yml` as it is, publish the release, and upload binaries from my fork

2 seems to take less effort, but the commit updating `build.yml` may affect git rev listed in `--probe-tools`

**Comment by jneira** [comment]
I would vote for 1 cause the build will be fixed in master, ready for another release if necessary while we fix it for `20.04`.

**Comment by berberman** [comment]
Due to the land of #1717, we need prepare a new release of ghcide and re-prepare HLS 1.2 based on #1717. Now we have a chance to downgrade the ubuntu runner

**Comment by berberman** [comment]
It seems that @pepeiborra has already uploaded `ghcide-1.2.0.1`, but I want to include approved #1709 and #1715 in HLS 1.2 -- both of them made changes in ghcide, so I plan to prepare a `ghcide-1.2.0.2` release

**Comment by berberman** [comment]
@jneira The build succeeded! So the last step is to upload 8.8.3 and 8.8.4 binaries for Windows?

**Comment by jneira** [comment]
> The build succeeded! So the last step is to upload 8.8.3 and 8.8.4 binaries for Windows?

Nice! Yeah, i'll try to do it this evening GMT (it will take some time in my laptop, with a cold cabal store cache :worried:)
Many thanks, you have dealed with this problematic release amazingly

**Comment by berberman** [comment]
@jneira I have built 8.8.4 one on my local machine, though it took some efforts... Is it enough? Should we upload 8.8.3 or even 8.8.2 as well?

**Comment by jneira** [comment]
nice, lately we are uploading only 8.8.4. You can check the last 1.0.0 release, if all artifacts match with the prerelease, it is good to go!

**Comment by berberman** [comment]
uploaded and unmarked pre-release now
