### ISSUE TITLE
Infix backticked holes get their backticks deleted once filled

### ISSUE THREAD

**Issue by masaeedu** [haskell/haskell-language-server#1690]
### Steps to reproduce

Write this:

```
data A = A

foo :: A -> A -> A
foo A A = A

test :: A -> A -> A
test a1 a2 = a1 `_` a2
```

Open up the context menu on the hole and select "replace with `foo`".

### Expected behaviour

The implementation should now look like:

```
test :: A -> A -> A
test a1 a2 = a1 `foo` a2
```

### Actual behaviour

The implementation now looks like:

```
test :: A -> A -> A
test a1 a2 = a1 foo a2
```

**Comment by isovector** [comment]
My guess is that this is a bug in the exactprint machinery, that it's dropping the backtick annotations.

**Comment by isovector** [comment]
But this isn't Wingman; I don't provide any `replace with _` code actions.

**Comment by Ailrun** [comment]
Oh, sorry. I somehow thought this is related with Wingman.

**Comment by isovector** [comment]
No worries, I did too!

**Comment by isovector** [comment]
I think this (and all analogous pieces of code) are the offender

https://github.com/haskell/haskell-language-server/blob/607ae3b95a3a2bad23c338ccbaafd2cb84f25116/ghcide/src/Development/IDE/GHC/ExactPrint.hs#L229-L230

IIUC, `exactprint ` attaches annotations to source spans, which get overwritten when we replace a node. I think if we read the annotations off the node that used to be there, and attach them to the newly replaced node, this should fix a bunch of issues --- including that big ugly `needsParensSpace` thing (or at least, the _space_ part of it.)

**Comment by isovector** [comment]
(all of this assumes that `replace with _` uses ExactPrint)

**Comment by isovector** [comment]
Which it doesn't seem to, but I think that will fix some problems in WIngman anyway.

**Comment by jneira** [comment]
Maybe the cause is the code is using the ParseModule version without annotations?

https://github.com/haskell/haskell-language-server/blob/607ae3b95a3a2bad23c338ccbaafd2cb84f25116/ghcide/src/Development/IDE/Core/Rules.hs#L197-L207

**Comment by berberman** [comment]
This code action is provided by ghcide, which depends on diagnostic messages, not parsed ast.
https://github.com/haskell/haskell-language-server/blob/607ae3b95a3a2bad23c338ccbaafd2cb84f25116/ghcide/src/Development/IDE/Plugin/CodeAction.hs#L677-L689

**Comment by jneira** [comment]
So updating the regexp should fix it, it seems it could be a good first issue
