### ISSUE TITLE
VS Code Extension not detected ghc --print-libdir.

### ISSUE THREAD

**Issue by Nagkei10** [haskell/haskell-language-server#1693]
I'm using Ubuntu-20.04 with WSL2 and installed it using the Stack installer script.
When I try to start Haskell from WSL bash, it outputs `Couldn't execute ghc --print-libdir` error and Language Server doesn't start.
The `implicit-hie` package and `hie-bios` package have been installed.

**Comment by jneira** [comment]
probably we should add it as konwn issue in troubleshooting section

**Comment by mgajda** [comment]
Same problem here, even though the project is clearly `stack.yaml`, the HLS tries to run `cabal` inside.

**Comment by golddydev** [comment]
> > or create a stack project with stack init
> 
> I tried.
> 
> > put the ghc used by stack on 
> >   P
> >   A
> >   T
> >   H
> >   w
> >   i
> >   t
> >   h
> >   e
> >   x
> >   p
> >   o
> >   r
> >   t
> >   P
> >   A
> >   T
> >   H
> >   =
> > (stack path --compiler-bin --silent):$PATH
> 
> I tried it and it worked.

To where did you add that line, I tried, but still get same error

**Comment by fendor** [comment]
@golddydev Hi! The extension was significantly overhauled since this issue was created and closed.

Please open a new issue describing your issue, make sure to include logs and then we can see what the problem is :)
