### ISSUE TITLE
segfault on multi-module project

### ISSUE THREAD

**Issue by goertzenator** [haskell/haskell-language-server#1698]
I have a Haskell project that has only ever worked under hls-0.6.0 and I would like to get it working under 1.0.0.  Everything after 0.6.0 has given me the vscode "failed 5 times in 3 minutes, not restarting" error.  Digging deeper into 1.0.0 failures, I see that it is segfaulting.

My hls seems to work fine a on brand new `stack new` project, so there must be something odd about my larger multi-module project.

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
$ haskell-language-server-8.8.4 --probe-tools
haskell-language-server version: 1.0.0.0 (GHC: 8.8.4) (PATH: /nix/store/yxk4vi09xypb7jiznmdypv7l5jxja5rx-haskell-language-server-1.0.0.0/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:          Not found
stack:          2.5.1.1
ghc:            Not found

```
Which OS do you use:
NixOS
[shell.nix](https://gist.github.com/goertzenator/832ccf98da0a3ace26f001cfffd82128)

Which lsp-client do you use:
vscode

Describe your project (alternative: link to the project):
This is a closed commercial project so I cannot share the whole thing.

[stack.yaml](https://gist.github.com/goertzenator/e1bb11ec9d80fd9bdfbd3e4ebacc506b)
[censored file tree](https://gist.github.com/goertzenator/6e0f8e05e879fec6c8a336bdec6f8ed7)
[hie.yaml](https://gist.github.com/goertzenator/f5120d0b8895e4fc0a4f1e643470fde2)

### Steps to reproduce
In the project root:
```
nix-shell
haskell-language-server-8.8.4
```
### Expected behaviour
Shouldn't segfault.

### Actual behaviour
Segfaults after 15 seconds or so.

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

[hls debug output](https://gist.github.com/goertzenator/f4ae7fe15b8def788a279a2e91adbc19)

**Comment by jneira** [comment]
hi, many thanks for the detailed bug report. Two questions that may help trace the issue:
* The project has several subdirs (config, database) not included in the cradle, i suppose you dont want load them in vscode (ide features will not work with them). Not load them is fine though.
* Could you attach the haskell lsp log of a live vscode session, opening a file that should work with it?
* Are you using template haskell in your source files?

**Comment by goertzenator** [comment]
Thanks for the response.

- The cradle was made with `gen-hie >hie.yaml` and did not include `config` and `database`.  I ultimately would like to have them included, but that's a small side-problem at the moment.
- [lsp log](https://gist.github.com/goertzenator/edeb405bb1626baa538e4f6baf204989) as requested.
- Yes, we do use template haskell in `spencer`, but not in `config` and `database`.  QuasiQuotes too if that matters.

**Comment by jneira** [comment]
Wow the lsp logs looks weird, i guess it crashes after `haskell-lsp.runWith`?
I think it should output some lines between crashes though, do you enable debug in lsp config options?

**Comment by goertzenator** [comment]
Ah, it was not in debug mode.  Turning on the "trace - messages" switch in VS Code changed the command from ...
```
haskell-language-server-8.8.4 --lsp -l lsplog.txt
```
... to...
```
haskell-language-server-8.8.4 --lsp -d -l lsplog.txt
```
... and gave me [this log](https://gist.github.com/goertzenator/c4edcaacd984a88d13d5da9fe4b4419d).

Opening a file in the project with no templates still resulted in a crash.  This was the case logged in the link above.  Note that other files in the project still have templates and it looked like HLS was scanning them, so I'm not sure if I did what you wanted.

I checked again with a pristine `stack init` project (no templates) and everything worked fine.

Also of note:  For unrelated reasons I switched from nixpkgs Haskell infrastructure to haskell.nix infrastructure which includes it's own HLS (1.0.0).  I get the exact same failure.

**Comment by michaelpj** [comment]
I think we've been observing something similar, in particular the weird thing where the build seems to be immediately cancelled:
```
2021-04-16 08:30:20.969261738 [ThreadId 54] DEBUG hls:	Restarting build session (aborting the previous one took 0.00s)
2021-04-16 08:30:20.969315484 [ThreadId 38] DEBUG hls:	Finishing build session(exception: AsyncCancelled)
```

**Comment by goertzenator** [comment]
This still fails under `1.1.0`.

**Comment by goertzenator** [comment]
Is there anything I can do to move this forward?  Any branches I can test?  Any parts I can turn off to make it not fail?

For whatever reason, 0.6.0 no longer works for me so I've got no ide support at all right now. :(

**Comment by peterwicksstringfield** [comment]
Looks like the nix build makes a statically linked binary? Using dynamically linked binaries has fixed similar problems for other people in the past. Maybe that would work for you?

Try this:
```shell
ldd path/to/haskell-language-server
```

Dynamically linked:
```shell
peter@gtower:~/haskell-language-server$ ldd masterbuild/haskell-language-server-wrapper 
	linux-vdso.so.1 (0x00007fff08dfc000)
        [more junk ...]
```

vs

Statically linked:
```shell
peter@gtower:~/haskell-language-server$ ldd ~/.ghcup/bin/haskell-language-server-wrapper 
	not a dynamic executable
```

If the binary you are using is statically linked, maybe try building with stack or cabal so you get a dynamically linked one? Possibly the dynamically linked one won't crash. There's probably a way to get a dynamic build out of nix too, but I haven't learned how to use nix yet :S.

**Comment by goertzenator** [comment]
I ran `ldd` and `haskell-language-server` is definitely a dynamic executable under NixOS.

Some other news:  Last week I updated my NixOs from 20.09 to 21.05 and now HLS is doing *much* better.  I do not see crashes any more.  I'm not convinced it processes every file right (ie, I don't see import hints on every file), but it is already proving to be massively more useful than it was before.

**Comment by jneira** [comment]
ok, it seems the nix bump fixed somewhat the segfault so i am gonan close the issue optimistically, feel free to reopen if you hit the bug again, thanks!
