### ISSUE TITLE
Splitting a variable bound in a `NamedFieldPun` duplicates record match

### ISSUE THREAD

**Issue by kcsongor** [haskell/haskell-language-server#1736]
Given the following code:

```haskell
data Bar = Bar { ax :: Int, bax :: Bool }

bar :: Bar -> Int
bar Bar {ax, bax} = _
```

executing the `case split on bax` code action results in 

```haskell
data Bar = Bar { ax :: Int, bax :: Bool }

bar :: Bar -> Int
bar Bar {ax, bax} = _
bar Bar {ax, bax} = _
```

a workaround is turning the pattern in question into a normal record field binding first:

```haskell
bar :: Bar -> Int
bar Bar {ax, bax = bax} = _
```

then executing the same code action results in the expected output:

```haskell
bar :: Bar -> Int
bar Bar {ax, bax = False} = _
bar Bar {ax, bax = True} = _
```

I've tried this on both the latest master (9ae20922) and the latest release (`1.1`) and both exhibit this behaviour.

**Comment by isovector** [comment]
Nice catch. Easy thing to fix.
