### ISSUE TITLE
Completions for methods of the current class in instance declarations

### ISSUE THREAD

**Issue by fwcd** [haskell/haskell-language-server#1738]
Consider the following example:

```haskell
class Test a where
    test :: a -> ()

instance Test Int where
    test = _
```

At `_`, it would be nice to have the method `test` in the completion list, e.g. for recursive invocations, this is not the case currently, however:

![image](https://user-images.githubusercontent.com/30873659/115060390-182aee00-9ee8-11eb-8524-af4bad95e68f.png)

**Comment by Ailrun** [comment]
Confirmed.
