### ISSUE TITLE
Wrong `Conflicting definitions` error

### ISSUE THREAD

**Issue by Sir4ur0n** [haskell/haskell-language-server#175]
Hi,

We are considering migrating to HLS for our project, but we surprisingly get some typecheck errors, while Stack compilation works just fine.

The first problem we encounter is about conflicting definitions.

I tried to pull together a minimal reproducing repo: https://github.com/Sir4ur0n/hls-bug-conflicting-definitions

Everything you need (Stack, HLS) is provided by `shell.nix` (though build may be long), but the bug remains with traditional Stack + HLS installations (tested on a coworker Macbook).

* `stack build` works fine
* `haskell-language-server` gives a typecheck error:
```
File:     /home/sir4ur0n/sandbox/foobar/src/BugHLS.hs
Hidden:   no
Range:    8:0-8:14
Source:   typecheck
Severity: DsError
Message: 
  Conflicting definitions for ‘a_a28B’
  Bound at: /home/sir4ur0n/sandbox/foobar/src/BugHLS.hs:8:1-14
  /home/sir4ur0n/sandbox/foobar/src/BugHLS.hs:8:1-14
Files that failed:
 * /home/sir4ur0n/sandbox/foobar/src/BugHLS.hs
```

Even more surprising, the 2 paths are exactly the same, even the character ranges.

Note, we use [some extensions](https://github.com/Sir4ur0n/hls-bug-conflicting-definitions/blob/master/package.yaml#L11) in this breaking piece of code

This was tested with HLS 8.8.3 as we use Stack snapshot `lts-15.15` which relies on GHC 8.8.3.

I suspect this has to do with TemplateHaskell, but AFAIU HLS should support such code.

Thank you for your help!

**Comment by Sir4ur0n** [comment]
I just tested this problem again today, with a more recent version of HLS, and the bug is gone :man_shrugging: 

However we have another, similar issue, but related to type families and type instances... I'll try to reproduce the issue in my side repository first...

**Comment by Sir4ur0n** [comment]
Small progress: my remaining issue seems to be exactly the same as https://github.com/digital-asset/ghcide/issues/641

Should we keep this issue open?

**Comment by jneira** [comment]
Let's keep it open to track the resolution upstream.

**Comment by jneira** [comment]
> Let's keep it open to track the resolution upstream.

But in a new one with a specific title #210
