### ISSUE TITLE
Emacs Key Bindings for Features

### ISSUE THREAD

**Issue by mmport80** [haskell/haskell-language-server#1765]
I like using emacs without X ("nox"). Therefore key-bindings are essential (I suppose that implies "code actions" - but I am not an LSP afficionado).

Fantastic project!

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

haskell-language-server version: 1.0.0.0 (GHC: 8.10.4) (PATH: /home/john/hls/haskell-language-server-wrapper) (GIT hash: 4cd1cf934638881e52b3eba9f70157a4b799c0e9)
Tool versions found on the $PATH
cabal:          Not found
stack:          2.1.3.1
ghc:            Not found

Which OS do you use:
Nix

Which lsp-client do you use:
emacs

Describe your project (alternative: link to the project):
minimal stack (dev environment setup)

### Steps to reproduce
Try to 1) evaluate code or 2) insert type signatures via "lsp-execute-code-action".

(I can see all the lenses, just cannot interact with them)

### Expected behaviour
both features should be useable via the keyboard

### Actual behaviour
no code actions are displayed

### Include debug information
n/a

**Comment by michaelpj** [comment]
All of HLS's functionality is exposed via one of the standard LSP modes. It looks like you're using `lsp-mode`: so if you want it to add more commands or similar you should open an issue there!

**Comment by michaelpj** [comment]
I'm particular, given your comments about lenses, you may be interested in https://github.com/emacs-lsp/lsp-mode/issues/2088

**Comment by mmport80** [comment]
Thanks for this! Good spot. I think Avy will suffice for my purposes

**Comment by jneira** [comment]
So is there some action to be done in hls?

**Comment by mmport80** [comment]
no, I think it can be closed
