### ISSUE TITLE
Empty case split should graft into FunBinds matches if possible

### ISSUE THREAD

**Issue by isovector** [haskell/haskell-language-server#1767]
Given `(>>=) x f = case x of`, running `Complete code constructors` today produces

```haskell
  (>>=) x f = case x of
    Goto s -> _
    Terminal a -> _
    Transition g -> _
    Invoke s mx g -> _
```

but instead could produce

```haskell
  (>>=) (Goto s) f = _
  (>>=) (Terminal a) f = _
  -- etc...
```

**Comment by Ailrun** [comment]
As a note, it should create FunBinds only when other variables are not patterns, because if they are, FunBinds may change the evaluation order of arguments.
