### ISSUE TITLE
Error on hovering [docs]: Cannot render inline math formular

### ISSUE THREAD

**Issue by adityagupta1089** [haskell/haskell-language-server#1773]
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
Tool versions found on the $PATH
cabal:          3.4.0.0
stack:          2.5.1
ghc:            8.10.4
```
Which OS do you use: ArchLinux

Which lsp-client do you use: VSCode

### Steps to reproduce
I am not able to see math being rendered, it says "cannot render inline math formula" even though I have mathjax installed.
![image](https://user-images.githubusercontent.com/11774081/115974670-e8c95080-a57b-11eb-8c4a-6e258d910686.png)

**Comment by jneira** [comment]
Hi, thanks for the bug report, it was detected in #201, you can read there the discussionabout and track the possible resolution.
