### ISSUE TITLE
Hackage release of 1.1.0

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#1774]
Hi, afaik the last hls version is not in hackage yet. Some users (particularly nix ones) can access it yet.
Iirc some version bumps were done in the github release and i hope the hackahe one would be more straightforward thanks to that work already done
//cc @berberman @pepeiborra

**Comment by berberman** [comment]
Do we have any meta changes that need to be back ported to 1.1.0-hackage? If no, I guess we are good to uoload all of the rest packages to Hackage now.

**Comment by berberman** [comment]
Packages we need to upload, based on [1.1.0-hackage](https://github.com/haskell/haskell-language-server/tree/1.1.0-hackage):

* [x] `hls-plugin-api` - [1.1.0.0](https://hackage.haskell.org/package/hls-plugin-api-1.1.0.0)
* [x] `hls-test-utils` - [1.0.0.0](https://hackage.haskell.org/package/hls-test-utils-1.0.0.0)
* [x] `ghcide` - [1.2.0.2](https://hackage.haskell.org/package/ghcide-1.2.0.2)
* [x] `hls-brittany-plugin` - [1.0.0.1](https://hackage.haskell.org/package/hls-brittany-plugin-1.0.0.1)
* [ ] `hls-class-plugin` - 1.0.0.1
* [ ] `hls-eval-plugin` - 1.1.0.0
* [x] `hls-explicit-imports-plugin` - [1.0.0.1](https://hackage.haskell.org/package/hls-explicit-imports-plugin-1.0.0.1)
* [ ] `hls-haddock-comments-plugin` - 1.0.0.1
* [ ] `hls-hlint-plugin` - 1.0.0.2
* [x] `hls-retrie-plugin` - [1.0.0.2](https://hackage.haskell.org/package/hls-retrie-plugin-1.0.0.2)
* [ ] `hls-splice-plugin` - 1.0.0.2
* [ ] `hls-stylish-haskell-plugin` - 1.0.0.0
* [ ] `hls-tactics-plugin` - 1.1.0.0
* [ ] `haskell-language-server` - 1.1.0.0

**Comment by jneira** [comment]
Uploading `hls-hlint-plugin`

**Comment by Ailrun** [comment]
Uploaded `hls-class-plugin`, `hls-haddock-comments-plugin`, and `hls-tactic-plugin`.

**Comment by jneira** [comment]
Uploaded `hls-hlint-plugin`

**Comment by jneira** [comment]
Uploading hls-eval-plugin (i've added @berberman and @Ailrun as maintainers too)

**Comment by jneira** [comment]
Uploaded `hls-splice-plugin-1.0.0.1`, going to bed, i left you the last one 🙂

**Comment by berberman** [comment]
Uploaded `haskell-language-server-1.1.0.0`
