### ISSUE TITLE
install from source on arm64/aarch64 hardware (raspi4)

### ISSUE THREAD

**Issue by andrewufrank** [haskell/haskell-language-server#1781]
### Your environment
```
i have installed with ghcup and set to ghc-8.10.4 
```
Which OS do you use: 
[debian bullseye with MATE
[uname -a
Linux panama 5.10.0-6-arm64 #1 SMP Debian 5.10.28-1 (2021-04-09) aarch64 GNU/Linux](url)](url)

Describe your project (alternative: link to the project):
I use cabal and use a clone of this github project from 2021-04-29 with no changes. 

```
./cabal-hls-install ghc-8.10.4
```
gives:
```
Error when running Shake build system:
  at want, called at src/Development/Shake/Internal/Args.hs:83:67 in shake-0.19.4-d04f24ed7cb366bfbd919a0f604ddc1ffa631cd9ffd475cd68e1a7a9fc4add63:Development.Shake.Internal.Args
* Depends on: ghc-8.10.4
  at error, called at src/Development/Shake/Internal/Rules/File.hs:179:58 in shake-0.19.4-d04f24ed7cb366bfbd919a0f604ddc1ffa631cd9ffd475cd68e1a7a9fc4add63:Development.Shake.Internal.Rules.File
* Raised the exception:
Error, file does not exist and no rule available:
  ghc-8.10.4
```

### Steps to reproduce
```
./cabal-hls-install ghcs
```
gives
```
Found the following GHC paths: 
ghc-8.10.4: /home/frank/.ghcup/bin/ghc-8.10.4
ghc-8.8.4: /usr/bin/ghc-8.8.4
```

```
./cabal-hls-install ghc-8.8.4 
```
gives the same error.

### Expected behaviour

HLS should be build for the 8.10.4 compiler.

### Actual behaviour

```
* Raised the exception:
Error, file does not exist and no rule available:
  ghc-8.10.4
```

I assume that there is some problem caused with the arm64 architecture. or perhaps just the description of it (arm64 in stead of aarch64).

**Comment by fendor** [comment]
Hi! 
The correct command is `./cabal-hls-install hls-8.10.4`.

Looks like the messages need to be improved.

**Comment by andrewufrank** [comment]
I naively assume that the spelling I received in the message `./cabal-hls-install ghcs` would indicate the required input. Somehow I eventually got it going (with ghcup tui - which perhaps need also some more advertising - it is a very nice tool, perhaps with the drawback of the for me not intuitive name 'tui'). 
Thank you for your efforts!

**Comment by fendor** [comment]
Closed the script no longer exists. Please use [GHCup](https://www.haskell.org/ghcup/guide/#hls) for compiling from source.
