### ISSUE TITLE
Mismatch dependency version `haskell-lsp` between hls and ghcide fork

### ISSUE THREAD

**Issue by GuillaumeDesforges** [haskell/haskell-language-server#180]
There is a dependency mismatch between

https://github.com/wz1000/ghcide/blob/master/ghcide.cabal#L47-L48

and

https://github.com/haskell/haskell-language-server/blob/master/haskell-language-server.cabal#L79

this blocks https://github.com/NixOS/nixpkgs/pull/91279

**Comment by fendor** [comment]
It seems you are looking at a different branch. We are depending on https://github.com/wz1000/ghcide/tree/hls-2 which updated the haskell-lsp version appropriately.

**Comment by GuillaumeDesforges** [comment]
My bad, sorry about that
