### ISSUE TITLE
HLS not starting when more than one component

### ISSUE THREAD

**Issue by andrewufrank** [haskell/haskell-language-server#1806]
Using vscode when I start HLS I get an error message indicating that the HLS could not start. When I check the output I see:

```
ghci | cabal: Cannot open a repl for multiple components at once. The target 'all'
ghci | refers to all the packages in the project which includes the libraries
ghci | uniform-convenience, uniform-json, uniform-pandoc, uniform-watch and
ghci | uniform-webserver.

```
I understand the limiation, but need a way to start HLS in such situations. I see that I can start `cabal repl lib:<package-name>` but then the necessary libraries for import are not set (this is probably better dealt with in a separate issue?) and I do not understand whether the HLS is  properly started and working continuously.

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

``` 
haskell-language-server-wrapper --probe-tools
haskell-language-server version: 1.1.0.0 (GHC: 8.10.4) (PATH: /home/frank/.ghcup/bin/haskell-language-server-wrapper-1.1.0) (GIT hash: f1c096927186a93d8e3ccd4fe8385cc1b070350b)
Tool versions found on the $PATH
cabal:		3.4.0.0
stack:		2.5.1
ghc:		8.10.4


```
Which OS do you use: Debian Linux Mint

Which lsp-client do you use: vscode

Describe your project (alternative: link to the project):

Contents of `hie.yaml`: I was told this is not necessary anymore - none!
```yaml

```

### Steps to reproduce

Start HLS for packages with library and tests or executables

### Expected behaviour

HLS should work; the start need not be automatic - a manual start would be acceptable.

 Happy to provide more information!

**Comment by fendor** [comment]
Are you sure this output is printed by HLS and not some other vscode extension? I do not recall seeing this kind of output *ever* before and I use hls on projects with more than one component, e.g. hls itself, cabal, and others...

Otherwise, you may have found a bug. Can you execute `haskell-language-server-wrapper --debug <some-source-file>` and paste here the output?

**Comment by andrewufrank** [comment]
@fendor: vscode + cabal + HLS (and perhaps other components) is occasionally confusing. Thank you for the confirmation that HLS should work with multiple components (contrary to old indications that there are (were) problems - which produced my suspicion together with the error messag i received). I am not sure which tool produced the out and I will observe carefully when and what produced it. At the moment I cannot reconstruct the case, but I saw it several times in the past days. 

As a suggestion: It would be useful for "users" to have a place (e.g.e the readme) where information like
- hie.yaml files are not needed (except ..) and are produced automatically 
- HLS works for multiple components (other comments and error messages are outdated)
- a list of the extensions which are necessary for vscode, which ones are automatically installed (and visible to the user) - this helps to remove extensions which are not necessary any more (which may be my case her)
could be found authoritatively (because it is updated iwth changes in the code). 

thank you for your efforts! The Haskell IDE is moving forward rapidly!

**Comment by andrewufrank** [comment]
I found the message
````
Error while starting GHCi.
````
which preceeded the output I pasted above (or something equivlant). I have removed my old `.ghci` file which I assumed cause the error and the message is now referring to a default (set prompt). 
I found that I had `Simple GHC (Haskell) Integration` installed.  Disabled and now the problem seems solved.

**Comment by michaelpj** [comment]
It sounds like this is fixed!
