### ISSUE TITLE
Strange bug with "UnboxedTuples"

### ISSUE THREAD

**Issue by nrolland** [haskell/haskell-language-server#1813]
When this extension is enabled, I can't evaluate expressions

```haskell
{-# LANGUAGE UnboxedTuples #-}

module SOQuestionRLSBug where

-- >>> show 3 -- disable "UnboxedTuples" to evaluate this expression in RLS from Visual studio
```

**Comment by pepeiborra** [comment]
This happens because GHC doesn't support `UnboxedTuples` in bytecode, which is what the eval plugin uses.
Could you try to use `{-# OPTIONS -fobject-code #-}` and report back?

**Comment by July541** [comment]
Adding {-# OPTIONS -fobject-code #-} seems does not work.
Combining the Dynflag `Opt_ByteCodeIfUnboxed` with the ghcSession can prevent this bug happen. Maybe we can add an extra `Opt_ByteCodeIfUnboxed` flag if the module is not interpreted, but I am not sure is it a generalized solution.

**Comment by jneira** [comment]
* Related with #771
