### ISSUE TITLE
Faster release cycles, please!

### ISSUE THREAD

**Issue by awgn** [haskell/haskell-language-server#182]
Hello,

Many people would appreciate faster release cycles. 

The very first tag 0.1 was released on 3 May, and since then no further tags has been pushed. However, a number of PRs have been merged and the easiest way to broadcast this information is to make new releases.

Indeed, not all people are used to build the master branch if they don't see a new reassuring tag. 

Hope this is taken as a constructive suggestion. I really appreciate your work guys and the value of this project.

Best,
N.

**Comment by alanz** [comment]
We are intending to get onto the monthly rhythm again now, had some initial glitches.
