### ISSUE TITLE
Add plugin to format .cabal files

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#183]
* From https://github.com/alanz/vscode-hie-server/issues/241
* I could be implemented using  [cabal-fmt]( https://github.com/phadej/cabal-fmt) as suggested by @fendor

/cc @WillSewell

**Comment by WillSewell** [comment]
Or use `cabal format`, which I see as the "official" style.

**Comment by fendor** [comment]
`cabal-fmt` does quite a bit more than `cabal format`, but I guess you are right that it is more official (although cabal-fmt is produced by a cabal maintainer).
Also, in my opinion the bigger issue, is that with tools such as `stack`, `rules_haskell`, and similar, we might not have `cabal` installed on the system. Maybe we can extend hls to have multiple cabal formatters as well?

**Comment by maoe** [comment]
Sadly `cabal format` expands common stanzas (https://github.com/haskell/cabal/issues/5734) so I don't think it's suitable as a general auto-formatter.

**Comment by Avi-D-coder** [comment]
Off topic: Thanks for mentioning this!
> Sadly `cabal format` expands common stanzas ([haskell/cabal#5734](https://github.com/haskell/cabal/issues/5734)) so I don't think it's suitable as a general auto-formatter.

I believe this is will allow https://github.com/Avi-D-coder/implicit-hie to support common stanza!

**Comment by jneira** [comment]
I wonder if handling of cabal config should live in its own lsp server, to not bloat hls with cabal related dependencies and features

**Comment by ndmitchell** [comment]
I imagine that eventually we'll want to do things like creating new modules and automatically adding them to Cabal, or marking whether a module is exposed or not at the top of the module and adjusting that quickly. That requires a sufficient level of integration with Cabal that I suspect eventually we'll have to become a Cabal LSP (and potentially a Stack LSP). That might be a decade away though :)

**Comment by jneira** [comment]
Related with other features request related with the interacion between hls and cabal:
* #155: add dependencies in .cabal files
* #113 control the build tool (execute build/test/run on cabal)
