### ISSUE TITLE
Eval plugin test does not work with stack

### ISSUE THREAD

**Issue by Ailrun** [haskell/haskell-language-server#1838]
### Your environment
Current master branch (a9113df001a26b155d2c9e2ce8b9e85242d35d92)
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 1.1.0.1 (GHC: 8.10.4) (PATH: /home/jjc/.local/bin/haskell-language-server) (GIT hash: a9113df001a26b155d2c9e2ce8b9e85242d35d92)
Tool versions found on the $PATH
cabal:          3.4.0.0
stack:          2.7.1
ghc:            8.10.4
```
Which OS do you use: Manjaro
Which lsp-client do you use: N/A
Describe your project (alternative: link to the project): N/A
Contents of `hie.yaml`: N/A

### Steps to reproduce
Run `stack test hls-eval-plugin`

### Expected behaviour
Works as with Cabal

### Actual behaviour
Failed as there's no code lens (like the following):
```
  Produces Evaluate code lenses: FAIL (2.42s)
    test/Main.hs:34:
    expected: [Just "Evaluate..."]
     but got: []
```

**Comment by Ailrun** [comment]
It's because of `test.cabal` in its testdata directory. I will fix this in #1836.

**Comment by Ailrun** [comment]
Actually I failed because of `QuickCheck` dependency of the tests...

**Comment by michaelpj** [comment]
Old and I think not that important
