### ISSUE TITLE
Contributing via nix-env doesn't work, zlib seems to be missing from derivation

### ISSUE THREAD

**Issue by ErnestKz** [haskell/haskell-language-server#1846]
Using NixOS 20.09

### Steps to reproduce
Clone repo then follow steps of using-nix
https://github.com/haskell/haskell-language-server#using-nix
cabal build

### Actual behaviour
cabal: Failed to build zlib-0.6.2.3
https://gist.github.com/ErnestKz/f0441e3ce1d55cf22331ac849bfeafc5

**Comment by ErnestKz** [comment]
I'm a nix noobie, not quite sure how to fix this.

**Comment by Ailrun** [comment]
Thank you for the issue. Could you also provide the log for zlib (`/home/ek/.cabal/logs/ghc-8.10.4/zlib-0.6.2.3-7f53445b38bac53a1687f527c632e5666d785c000d0b1ce9dde5f157f68bede8.log` mentioned in your gist)? That would be more helpful.

**Comment by ErnestKz** [comment]
```
cat /home/ek/.cabal/logs/ghc-8.10.4/zlib-0.6.2.3-7f53445b38bac53a1687f527c632e5666d785c000d0b1ce9dde5f157f68bede8.log
Configuring library for zlib-0.6.2.3..
cabal: Missing dependency on a foreign library:
* Missing (or bad) header file: zlib.h
* Missing (or bad) C library: z
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.If the
library file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
If the header file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.
```

**Comment by Ailrun** [comment]
Oops sorry, I missed that part (it's actually in your gist). Yeah, I can reproduce the issue in my non-NixOS (Linux) machine. It's maybe an issue of our nix default expression.

If you have nix flake, could you try `nix develop` too? That one works well for me.

@berberman Could you check this issue with `nix-shell; cabal build`?

**Comment by ErnestKz** [comment]
`nix develop`  seems to work so I'll use that for now. Thanks for having a look.

**Comment by Ailrun** [comment]
Maybe related issue: https://github.com/edolstra/flake-compat/issues/13

**Comment by berberman** [comment]
Thanks for the reporting, there's a mistake in `default.nix`.
