### ISSUE TITLE
Remove support for ghc-8.8.2

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#1863]
* Hi, those ghc versions were released quite time ago and bot have 2 new minor versions available and widely used
  * 8.8.2 was released on 2020-01-16
  * 8.10.2 was released on 2020-08-08 and it has not gotten to have stackage lts

**Comment by jneira** [comment]
I would like to know some statistics about ghc downloads per version, to have some numbers on which make the decision, anyone knows where thay could be found?

**Comment by konn** [comment]
I'm strongly against removing 8.10.2 support, as there is known thread-safety issue #1465 for 8.10.3 and 8.10.4, and 8.10.5 is not yet released...

**Comment by jneira** [comment]
> 
> 
> I'm strongly against removing 8.10.2 support, as there is known thread-safety issue #1465 for 8.10.-8.10.4, and its fixes in 8.10.5 is not yet released...

Thanks for noting it, this is a good reason to keep it around
