### ISSUE TITLE
Code Action for adding a constructor to imports is a noop

### ISSUE THREAD

**Issue by ProofOfKeags** [haskell/haskell-language-server#1868]
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 1.1.0.0 (GHC: 8.10.4) (PATH: /home/proofofkeags/.local/bin/haskell-language-server-wrapper) (GIT hash: f1c096927186a93d8e3ccd4fe8385cc1b070350b)
Tool versions found on the $PATH
cabal:          3.2.0.0
stack:          2.7.1
ghc:            Not found
```
Which OS do you use: Linux

Which lsp-client do you use: VSCode

### Steps to reproduce
1. Reference a Constructor that is not imported and shares a name with its type.
2. Use Ctrl+. to execute code action to add constructor to import list

### Expected behaviour
Type and constructor should be added to import list.

### Actual behaviour
Only the type is added to the import list

### Include debug information
No relevant logs

**Comment by Ailrun** [comment]
Thank you for the report. I believe this is a duplicate of #1768, which is fixed in the master branch. Could you try the master branch version of HLS?

**Comment by ProofOfKeags** [comment]
It does appear to be a duplicate. Is master stable enough to work off of usually?

**Comment by Ailrun** [comment]
Sometimes there's some critical issues, but it's usually only during few commits and I would say it's mostly stable.

**Comment by ProofOfKeags** [comment]
Can confirm that this does work on master.
