### ISSUE TITLE
Question: my install of haskell-language-server + coc + vim only partially working

### ISSUE THREAD

**Issue by fjhheras** [haskell/haskell-language-server#187]
I have a cabal system installed with ghcup. I installed haskell-language-server using `cabal v2-run ./install.hs --project-file install/shake.project hls`

Installation was sucessful, but it is not detecting the installed packages in my cabal projects, among other problems. The hlint I installed with `cabal install hlint` detects the cabal installed packages with no problem.

To solve this, I tried to create a hie.yaml file with the following contents: `radle: {cabal: {component: "lib:haskell-language-server"}}`, but when running haskell-language-server I receive this error:

```
  Failed to parse result of calling cabal
  
  cabal: Internal error in target matching. It should always be possible to find
  a syntax that's sufficiently qualified to give an unambiguous match. However
  when matching 'lib:haskell-language-server' we found
  lib:haskell-language-server (unknown-component) which does not have an
  unambiguous syntax. The possible syntax and the targets they match are as
  follows:
  'lib:haskell-language-server' which matches lib:haskell-language-server
  (unknown-component), :pkg:lib:lib:lib:file:haskell-language-server
  (unknown-file)
```

Other things (maybe unrelated) that I was not able to configure with vim+coc were:
- Linting with hlint
- Go to definition

**Comment by fendor** [comment]
hi, thank you for your bug report!
Can you explain your project setup? You will have better results if you use a cabal or stack project.

Your `hie.yaml` is meant to explain hls how *your* project is loaded. In this case you should describe which files belong to which component. In this syntax, it means that any files belong to the component `lib:haskell-language-server`, the library of the project `haskell-language-server`.
Assuming you are using a cabal project, your component is `lib:<name of the cabal file>`.

**Comment by fjhheras** [comment]
I am a Haskell beginner, and this is a repo where I am going through the exercises in a book:

https://github.com/fjhheras/haskellbook_exercises

My intention was to create a common cabal project for all chapters, and then call each file individually using `cabal exec -- runghc chapter17/identity.hs` for example (scripts of previous chapters are not working with this new system yet). Therefore I did not configure anything in the cabal file, except for dependencies.

**Comment by fendor** [comment]
That projects looks complicated to configure correctly... We will need a full cabal project, e.g. each file must be possible to open with cabal. If you use a big cabal project, you will probably need a `cabal.project` file.
We can try too help you set up hls for it, once you managed to create a cabal project for each chapter.

**Comment by Avi-D-coder** [comment]
Once you have a `cabal.project`, https://github.com/Avi-D-coder/implicit-hie should be able to generate a correct `hie.yaml` file.

What's your motive for wanting all the chapters to be in one cabal project?
Why not just treat each chapter as a self-contained cabal package? If `cabal build` succeeds in a chapter, just run `gen-hie > hie.yaml` in each chapter.

**Comment by fjhheras** [comment]
Hi, thank you for your help. I changed the structure so now I have a cabal project for each chapter. Unfortunately for it to work I need to add 6 lines for each executable (e.g. https://github.com/fjhheras/haskellbook_exercises/blob/master/chapter17/chapter17.cabal)

With the new structure, a `haskell-language-server` installation works, but still does not recognise the cabal project dependencies (In comparison, a `haskell-ide-engine` installation now works perfectly, and even linting is working).

For `haskell-language-server` to work, as @Avi-D-coder proposed, I installed gen-hie and generated the following hie.yaml file:
```
cradle:
  cabal:
    - path: "./identity.hs"
      component: "chapter17:exe:identity"

    - path: "./listapplicative.hs"
      component: "chapter17:exe:listapplicative"

    - path: "./lookups.hs"
      component: "chapter17:exe:lookups"

    - path: "./ziplist.hs"
      component: "chapter17:exe:ziplist"
```
Once placed, nvim+coc is giving me the following errors: 
```
Program error: Failed to load interface for ‘Main’no unit id matching ‘main’ was found
```
and
```
  Multi Cradle: No prefixes matched
  pwd: /home/user/Documents/haskell/haskellbook_exercises/chapter17
  filepath: /home/user/Documents/haskell/haskellbook_exercises/chapter17/Setup.hs
  prefixes:
  ("./identity.hs",Cabal {component = Just "chapter17:exe:identity"})
  ("./listapplicative.hs",Cabal {component = Just "chapter17:exe:listapplicative"})
  ("./lookups.hs",Cabal {component = Just "chapter17:exe:lookups"})
  ("./ziplist.hs",Cabal {component = Just "chapter17:exe:ziplist"})
Files that failed:
[INFO] finish: User TypeCheck (took 0.05s)
 * /home/user/Documents/haskell/haskellbook_exercises/chapter17/Setup.hs
 * /home/user/Documents/haskell/haskellbook_exercises/chapter17/ziplist.hs
```

**Comment by oblitum** [comment]
@fjhheras have you checked coc wiki about how to install HLS? I'm using binaries provided by @bubba without issues.

**Comment by jneira** [comment]
@fjhheras `Setup.hs` is known to fail and `ziplist.hs` seems to has something different to others (that work)
What is the behaviour of vscode opening the differente modules (with lastest hls)?

**Comment by jneira** [comment]
* hlint support is not available (although it will be soon)
* afaik the errors are covered by other issues

So i would close it if you agree, feel free to reopen

**Comment by fjhheras** [comment]
OK, no worries.
