### ISSUE TITLE
IRC broken

### ISSUE THREAD

**Issue by July541** [haskell/haskell-language-server#1876]
I noticed that the IRC channel `#haskell-language-server#` is not working now, does anyone know about that?

By the way, it seems the knowledge about [`ghcide`](https://github.com/haskell/haskell-language-server/blame/master/README.md#L764) in README should be updated due to we have merged `ghcide` into `hls`.

**Comment by berberman** [comment]
Recently, many freenode channels have been taken over by freenode operators by abuses of power, so FOSS communities are moving out of there. For us, the channel `#haskell-language-server` is available on [libera.chat](https://libera.chat/), a new IRC network organized by some of the old freenode staffs.

Yeah, the READNE should be updated accordingly.

**Comment by July541** [comment]
@berberman Thanks, I'll join it later.
