### ISSUE TITLE
June 2021 Monthly Release

### ISSUE THREAD

**Issue by Ailrun** [haskell/haskell-language-server#1890]
I think we have quite a number of PRs merged, bugs fixed, and features improved, so it will be great to have this month's official release.
Do you think any PR should be merged before the release? If so, please put it in a comment.

**Comment by pepeiborra** [comment]
Let's try to land #1649 (GHC 9.0 support) this weekend. @anka-213 has put in a lot of work and it's almost ready to merge.

**Comment by Ailrun** [comment]
I'm waiting for GHC 8.10.5 PR (#1899)

**Comment by Ailrun** [comment]
With #1912 and #1919, the release is done.
