### ISSUE TITLE
[GHC 9.0] No need to parse specially for hlint?

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#1891]
_Originally posted by @pepeiborra in https://github.com/haskell/haskell-language-server/pull/1649#discussion_r645961387_

**Comment by anka-213** [comment]
Does anyone have the details about what has changed related to haddock parsing in ghc9?

**Comment by jneira** [comment]
The comment in `getParsedModule` was a little bit misleading and was removed in #2338 . 
hlint needs `getParsedModuleWithComments` as demonstrated here: https://github.com/haskell/haskell-language-server/pull/2366 so i think we can close this
