### ISSUE TITLE
Distribute native Apple M1 binaries 

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#1896]
GHC 8.10.5 is out including native binaries for the Apple M1 hardware: https://www.haskell.org/ghc/blog/20210605-ghc-8.10.5-released.html

What do we need in order to create and distribute Apple M1 binaries? 

- [x] GHC 8.10.5 available in the Haskell Github Action
- [ ] Apple M1 hardware available in the GA free tier - https://github.com/actions/virtual-environments/issues/2187
- [ ] Haskell VSCode extension able to detect the M1 hardware and download the right binaries

**Comment by jneira** [comment]
This is needed for #2008

**Comment by jneira** [comment]
Closing this as the useful checklist was moved to #2008, thanks @pepeiborra!
