### ISSUE TITLE
Support GHC 8.10.5

### ISSUE THREAD

**Issue by Ailrun** [haskell/haskell-language-server#1898]
[GHC 8.10.5 is out](https://www.haskell.org/ghc/download_ghc_8_10_5.html), and it fixed [the thread-safety issue](https://gitlab.haskell.org/ghc/ghc/-/issues/19417) mentioned in https://github.com/haskell/haskell-language-server/issues/1863#issuecomment-846755647~~, so I think now we can replace 8.10.2 with 8.10.5~~.

Unfortunately, we cannot remove 8.10.2 because of https://gitlab.haskell.org/ghc/ghc/-/issues/19968. I will open a separate issue for 8.10.6 support and 8.10.2 removal.

**Comment by Ailrun** [comment]
We cannot remove 8.10.2 until 8.10.6 is out, as MacOS has a build problem with GHC 8.10.5

**Comment by jneira** [comment]
@Ailrun is there some ghc ticket about? it would be great to trackit, to ensure 8.10.6 will have a fix for macos

**Comment by Ailrun** [comment]
Here is the link: https://gitlab.haskell.org/ghc/ghc/-/issues/19968

**Comment by Ailrun** [comment]
Closed by #1899. For the GHC 8.10.2 issue and GHC 8.10.6 support, please see #1913.

**Comment by mouse07410** [comment]
Could you clarify, please? It looks like HLS-1.2.0 does **not** support GHC-8.10.5 on MacOS yet?

<img width="564" alt="Screen Shot 2021-06-15 at 10 44 10" src="https://user-images.githubusercontent.com/5923577/122074541-4e40fd00-cdc7-11eb-8024-41b241ea7fa5.png">

**Comment by Ailrun** [comment]
@mouse07410 
From 1.2.0 release note:
> - Support for GHC 8.10.5 is added.
Note that macOS version is unfortunately not included in this release because of [a GHC issue with network package](https://gitlab.haskell.org/ghc/ghc/-/issues/19968).

**Comment by mouse07410** [comment]
Please see https://github.com/haskell/haskell-language-server/issues/1913
