### ISSUE TITLE
Rename fails

### ISSUE THREAD

**Issue by GuillaumeDesforges** [haskell/haskell-language-server#190]
When I try to rename, I get:

```
Request textDocument/rename failed.
  Message: []
  Code: -32602 
```

I use VS Code with the Haskell Language Server plugin https://marketplace.visualstudio.com/items?itemName=alanz.vscode-hie-server

**Comment by jneira** [comment]
I think it is not implemented in hls (and ghcide). It worked in hie using HaRe and we should reimplement the plugin, using HaRe (or [Retrie](https://github.com/haskell/haskell-language-server/issues/103)?)

**Comment by GuillaumeDesforges** [comment]
Oh ok
Would it be possible to return an actual error message when a feature is not implemented, so as not to make that kind of confusion?

**Comment by branjwong** [comment]
I'm also getting this same error!

**Comment by bubba** [comment]
For now we should just make sure that we're not declaring the rename capability

**Comment by samhh** [comment]
Is there an appropriate issue for tracking this as a feature request now?

**Comment by bubba** [comment]
I think #282 mentions it
