### ISSUE TITLE
Couldn't execute ghc --print-libdir

### ISSUE THREAD

**Issue by z5230445** [haskell/haskell-language-server#1907]
Dear all
Im running vscode on windows10. 

I have installed the Haskell installer for windows from the official website
(https://docs.haskellstack.org/en/stable/README/#how-to-install)

I have also installed the haskell extension pack on my vscode.

Now im getting an error as shown in the photo. Please help and thank you so very much.
![issue](https://user-images.githubusercontent.com/64478091/121452556-fa0ed500-c9e2-11eb-8737-8b434ebe83e7.png)

**Comment by Ailrun** [comment]
Do you have system GHC installed? If not, you need a stack project (with `stack.yaml`) in order to use GHC installed by stack.

**Comment by z5230445** [comment]
Hi Ailrun
Thanks for the help. I am new to Haskel. Would you please elaborate on " a stack project (with stack.yaml)" ? Thank you so much

**Comment by Ailrun** [comment]
@z5230445 I assume that your directory does not have any project configuration, i.e., it's just with `*.hs` files. Without System GHC (installed in your `%PATH%`), the current HLS does not support such a case. You need either
- Install a system GHC (using choco package manager)
- Project setting for your directory

For the project setting, you need `stack.yaml` and one of `<your project name>.cabal`/`package.yaml`. You can create those files using `stack new` command with a template ([listed here](https://github.com/commercialhaskell/stack-templates)), or you can create `package.yaml` by hand based on info in https://github.com/sol/hpack and then use `stack init`.

**Comment by z5230445** [comment]
Thank you so much.

**Comment by jneira** [comment]
> I assume that your directory does not have any project configuration, i.e., it's just with *.hs files. Without System GHC (installed in your %PATH%), the current HLS does not support such a case. 

For completeness the issue tracking support for this case is: #692

**Comment by z5230445** [comment]
problem solved thanks so much.
