### ISSUE TITLE
Change root for language server?

### ISSUE THREAD

**Issue by TheOddler** [haskell/haskell-language-server#1910]
I have a Yesod server project that uses `parseRoutesFile "routes.txt"`. However, the server code is in a sub-folder of my whole project, and thus I get an error stating that "routes.txt" is not found.

![image](https://user-images.githubusercontent.com/1831376/121386020-eebb9b00-c949-11eb-8fad-29b9eac2725a.png)

This is because it is looking for this file in the root folder open in vscode, rather than the root of the actual Haskell project. 
As you can see, the `routes.txt` is inside the subfolder `shortblito-web-server` and not in the root:

![image](https://user-images.githubusercontent.com/1831376/121385814-bb790c00-c949-11eb-99a6-2a8d3e860d04.png)

Is there a way to let this plugin know that the root of the actual haskell project is `shortblito-web-server`?

Thanks!

**Comment by pepeiborra** [comment]
You could argue that the cwd should be the cradle location and not the workspace root, but what does this mean for multi-cradle projects? There can only be one working directory.

Alternatively, `hie-bios` could somehow attempt to post process all the paths in flags, but that wouldn't help with relative paths in TH.

**Comment by Vlix** [comment]
Would `makeRelativeToProject` maybe help in this case?

**Comment by TheOddler** [comment]
> 
> 
> Would `Data.FileEmbed.makeRelativeToProject` maybe help in this case?

It looks like it does! Thanks a lot!

I'll close this for now then, I'll have to test more to be 100% it works in all cases, but initially it seems to work.

Thanks!
