### ISSUE TITLE
new code action: add binding

### ISSUE THREAD

**Issue by alok** [haskell/haskell-language-server#1917]
i often write type sigs first. a code action to autogenerate a body would be nice. something like

``` f :: a -> b
-- for the body, code actions adds something like 'f a = _' 
```

**Comment by berberman** [comment]
Duplicate of #458

**Comment by jneira** [comment]
@alok thanks for your feature request, that would be a nice addition for sure. You can follow its progress in the linked previous feature request: #458. Feel free to reopen if you think the feature described there doesnt match yours.
