### ISSUE TITLE
Convert golden tests to tasty-golden

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#192]
I think using utilities from tasty-golden is better in terms of golden file management (it allows us to update golden file automatically).

_Originally posted by @Ailrun in https://github.com/haskell/haskell-language-server/pull/191_

**Comment by Ailrun** [comment]
Actually our golden test already use tasty-golden. I mean it would be better for the test you introduced in #191.

**Comment by jneira** [comment]
It seems 67744c changed eval plugin tests to make it use golden files, ¿do more tests need be changed to use tasty-golden?

**Comment by jneira** [comment]
It seems all golden tests are using tasty-golden so we could close this. Feel free to reopen the issue it is not the case (with pointers to concrete tests if possible)
