### ISSUE TITLE
Fails to load when cabal file contains non-ASCII characters

### ISSUE THREAD

**Issue by chris-martin** [haskell/haskell-language-server#1926]
I have an example here of a project that crashes haskell-language-server because the cabal file contains an em dash. If I remove the offending character, then HLS works.

> Couldn't figure out what GHC version the project is using: /home/chris/.config/Code/User/globalStorage/haskell.haskell/haskell-language-server-wrapper-1.2.0-linux --project-ghc-version exited with exit code 1: No 'hie.yaml' found. Try to discover the project type! haskell-language-server-wrapper-1.2.0-linux: /home/chris/environment-variables/environment-variables.cabal: hGetContents: invalid argument (invalid byte sequence)

![Screenshot from 2021-06-15 03-04-40](https://user-images.githubusercontent.com/399718/122025653-c2a77c00-cd86-11eb-9d42-622f0c6a13c4.png)

- OS: NixOS 21.05
- lsp-client: VSCode
- no hie.yaml file

**Comment by jneira** [comment]
A possible workaround could be generate an explicit `hie.yaml` file using the utility `gen-hie` (you can get it with `cabal install implicit-hie`)

**Comment by chris-martin** [comment]
Thanks for the workaround, that does work.

**Comment by jneira** [comment]
Hmm, i cant reproduce with hls 1.1 in windows adding this line to my cabal file: `description: With unicode char → —`
Will try with 1.2

**Comment by ncfavier** [comment]
Can confirm having the same issue with the VSCode extension on NixOS.

**Comment by ncfavier** [comment]
Solved by installing nixpkgs' `haskell-language-server` instead of using the one managed by the extension.

**Comment by jneira** [comment]
It seems this is not reproduced with newer hls versions, feel free to reopen ion other case

**Comment by gusbicalho** [comment]
FYI, I just ran into this bug with hls 1.7.0. The log below shows the cabal file as text and hex dump.

It turned out that the problem was that the VM I was using had locales set to `POSIX`. Once I fixed things so that it got a `UTF-8` locale, HLS worked again. I imagine this means `hGetContents` uses the system locale to pick an encoding, and if the locale is not UTF-8 it breaks down on multi-byte chars (?)

```
$ ls -la
total 28
drwxr-xr-x  2 gusbicalho gusbicalho  4096 Apr 29 19:16 .
drwxrwxrwt 69 root       root       20480 Apr 29 19:15 ..
-rw-r--r--  1 gusbicalho gusbicalho   157 Apr 29 19:15 repro-utf8.cabal

$ cat repro-utf8.cabal
cabal-version: 2.0
name: repro-utf8
build-type: Simple
version: 0.1.0.0
author: lön

library
    default-language: Haskell98
    build-depends: base == 4.*

$ od -t cx1 repro-utf8.cabal
0000000   c   a   b   a   l   -   v   e   r   s   i   o   n   :       2
         63  61  62  61  6c  2d  76  65  72  73  69  6f  6e  3a  20  32
0000020   .   0  \n   n   a   m   e   :       r   e   p   r   o   -   u
         2e  30  0a  6e  61  6d  65  3a  20  72  65  70  72  6f  2d  75
0000040   t   f   8  \n   b   u   i   l   d   -   t   y   p   e   :
         74  66  38  0a  62  75  69  6c  64  2d  74  79  70  65  3a  20
0000060   S   i   m   p   l   e  \n   v   e   r   s   i   o   n   :
         53  69  6d  70  6c  65  0a  76  65  72  73  69  6f  6e  3a  20
0000100   0   .   1   .   0   .   0  \n   a   u   t   h   o   r   :
         30  2e  31  2e  30  2e  30  0a  61  75  74  68  6f  72  3a  20
0000120   l 303 266   n  \n  \n   l   i   b   r   a   r   y  \n
         6c  c3  b6  6e  0a  0a  6c  69  62  72  61  72  79  0a  20  20
0000140           d   e   f   a   u   l   t   -   l   a   n   g   u   a
         20  20  64  65  66  61  75  6c  74  2d  6c  61  6e  67  75  61
0000160   g   e   :       H   a   s   k   e   l   l   9   8  \n
         67  65  3a  20  48  61  73  6b  65  6c  6c  39  38  0a  20  20
0000200           b   u   i   l   d   -   d   e   p   e   n   d   s   :
         20  20  62  75  69  6c  64  2d  64  65  70  65  6e  64  73  3a
0000220       b   a   s   e       =   =       4   .   *  \n
         20  62  61  73  65  20  3d  3d  20  34  2e  2a  0a
0000235

$ cabal build
Resolving dependencies...
Build profile: -w ghc-9.2.2 -O1
In order, the following will be built (use -v for more details):
 - repro-utf8-0.1.0.0 (lib) (first run)
Configuring library for repro-utf8-0.1.0.0..
Preprocessing library for repro-utf8-0.1.0.0..
Building library for repro-utf8-0.1.0.0..

$ haskell-language-server-wrapper-1.7.0.0
No 'hie.yaml' found. Try to discover the project type!
haskell-language-server-wrapper-1.7.0.0: /tmp/repro-utf8/repro-utf8.cabal: hGetContents: invalid argument (invalid byte sequence)
```

**Comment by isomorpheme** [comment]
I also seem to be having the same issue, having built 1.7.0.0. from source.
