### ISSUE TITLE
Cannot build from hackage: `Exception when trying to run compile-time code: : cannot satisfy -package-id directory-tree-0.12.1` 

### ISSUE THREAD

**Issue by augustss** [haskell/haskell-language-server#1927]
I tried to build haskell-language-server from scratch. 

Which OS do you use:
Windows 10

### Steps to reproduce
 cabal install haskell-language-server

### Expected behaviour
Should build

### Actual behaviour
Error message
...
Starting     ghcide-1.4.0.1 (lib)
Building     ghcide-1.4.0.1 (lib)
Installing   ghc-lib-parser-8.10.5.20210606 (lib)
Completed    ghc-lib-parser-8.10.5.20210606 (lib)

Failed to build ghcide-1.4.0.1.
Build log (
C:\Users\lennart.augustsson\AppData\Roaming\cabal\logs\ghc-8.10.4\ghcide-1.4.0.1-0c6b65b57e435fa7837b40c9c25d7f3456cd45ba.log
):
Preprocessing library for ghcide-1.4.0.1..
Building library for ghcide-1.4.0.1..
[ 1 of 61] Compiling Control.Concurrent.Strict ( src\Control\Concurrent\Strict.hs, dist\build\Control\Concurrent\Strict.o )
[ 2 of 61] Compiling Development.IDE.Core.Debouncer ( src\Development\IDE\Core\Debouncer.hs, dist\build\Development\IDE\Core\Debouncer.o )
[ 3 of 61] Compiling Development.IDE.Core.PositionMapping ( src\Development\IDE\Core\PositionMapping.hs, dist\build\Development\IDE\Core\PositionMapping.o )
[ 4 of 61] Compiling Development.IDE.GHC.Compat ( src\Development\IDE\GHC\Compat.hs, dist\build\Development\IDE\GHC\Compat.o )
[ 5 of 61] Compiling Development.IDE.GHC.CPP ( src\Development\IDE\GHC\CPP.hs, dist\build\Development\IDE\GHC\CPP.o )
[ 6 of 61] Compiling Development.IDE.Plugin.CodeAction.PositionIndexed ( src\Development\IDE\Plugin\CodeAction\PositionIndexed.hs, dist\build\Development\IDE\Plugin\CodeAction\PositionIndexed.o )
[ 7 of 61] Compiling Development.IDE.Session.VersionCheck ( session-loader\Development\IDE\Session\VersionCheck.hs, dist\build\Development\IDE\Session\VersionCheck.o )

session-loader\Development\IDE\Session\VersionCheck.hs:17:24: error:
    • Exception when trying to run compile-time code:
        <command line>: cannot satisfy -package-id directory-tree-0.12.1-fb510ec79174eba0e2367eaa39bbdf0d1a4e8022
    (use -v for more information)
      Code: makeGhcVersionChecker
              (fromMaybe GHC.Paths.libdir <$> lookupEnv "NIX_GHC_LIBDIR")
    • In the Template Haskell splice
        $$(makeGhcVersionChecker
             (fromMaybe GHC.Paths.libdir <$> lookupEnv "NIX_GHC_LIBDIR"))
      In the expression:
        $$(makeGhcVersionChecker
             (fromMaybe GHC.Paths.libdir <$> lookupEnv "NIX_GHC_LIBDIR"))
      In an equation for ‘ghcVersionChecker’:
          ghcVersionChecker
            = $$(makeGhcVersionChecker
                   (fromMaybe GHC.Paths.libdir <$> lookupEnv "NIX_GHC_LIBDIR"))
   |
17 | ghcVersionChecker = $$(makeGhcVersionChecker (fromMaybe GHC.Paths.libdir <$> lookupEnv "NIX_GHC_LIBDIR"))
   |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal.exe: Failed to build ghcide-1.4.0.1 (which is required by
exe:haskell-language-server from haskell-language-server-1.2.0.0 and
exe:haskell-language-server-wrapper from haskell-language-server-1.2.0.0). See
the build log above for details.

**Comment by augustss** [comment]
Running 
  cabal install directory-tree --lib
by hand made it work.

**Comment by jneira** [comment]
running `cabal-plan | grep directory-tree` in the hls repo dont output nothing so it is no a compile time dependency?
maybe the th code depends on it and it is not a explicit dependency? 🤔 
i will double check

**Comment by jneira** [comment]
> Running
> cabal install directory-tree --lib
> by hand made it work.

Only to be sure, did you start the installation with a full clean cabal environment (with a fresh cabal store in `%APPDATA%\cabal\store`) or had you tried install hls previously?

**Comment by augustss** [comment]
> @augustss first of all, thanks for your bug report.
> Only to be sure, and to try to reproduce it, did you start the installation with a full clean cabal environment (with a fresh cabal store in `%APPDATA%\cabal\store`) or had you tried install hls previously?
It was an almost clean install.  I had removed the whole cabal directory, and then run 'cabal install cabal-install'.  And then I tried to install hls.

**Comment by jneira** [comment]
colsing optimistically, feel free to reopen if you hit the bug building lastest hls from hackage
