### ISSUE TITLE
How to set Path for cabal to use?

### ISSUE THREAD

**Issue by jrp2014** [haskell/haskell-language-server#1950]
When I use `llvm-hs` cabal uses `llvm-config` to locate the version of llvm that I have installed.  So llvm-config (which is somewhere in `/usr/local/opt/llvm/bin`) must be in my path.  I could do that globally, but would like to be able to set it only when I am working on a specific project.   Is there something that I can do to set up the project environment to cover the bases below?

```
To use the bundled libc++ please add the following LDFLAGS:
  LDFLAGS="-L/usr/local/opt/llvm/lib -Wl,-rpath,/usr/local/opt/llvm/lib"

llvm is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have llvm first in your PATH, run:
  echo 'export PATH="/usr/local/opt/llvm/bin:$PATH"' >> ~/.zshrc

For compilers to find llvm you may need to set:
  export LDFLAGS="-L/usr/local/opt/llvm/lib"
  export CPPFLAGS="-I/usr/local/opt/llvm/include"
```

**Comment by jneira** [comment]
Hi, thanks for your question. The usual way to set specific things for a project with cabal is the config file `cabal.project`. 
Not sure if the configuration options available in that file could cover you use case though. You can take a look to the reference: https://cabal.readthedocs.io/en/3.4/cabal-projectindex.html#cap-cabal.project%20fields

**Comment by jrp2014** [comment]
thanks
