### ISSUE TITLE
During Manual Installation, an encoding error: `commitAndReleaseBuffer`: invalid argument (invalid character)

### ISSUE THREAD

**Issue by freckletonj** [haskell/haskell-language-server#1957]
**TL;DR** : `en_US.UTF-8` vs `C.UTF-8`

I've solved this as being an error of the environment's `LANG` encoding, but it'd be nice if this were documented.

Problem:

```sh
$ stack ./install.hs hls-8.8.4
<<<...>>>
ghc-lib                          > Registering library for ghc-lib-8.10.4.20210206..
<stderr>: commitAndReleaseBuffer: invalid argument (invalid character)

<stderr>: commitAndReleaseBuffer: invalid argument (invalid character)
Progress 8/162
```

Solution: 
```sh
$ echo $LANG
en_US.UTF-8

$ LANG=C.UTF-8 stack ./install.hs hls-8.8.4
```

-----------------

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
$ haskell-language-server --probe-tools
haskell-language-server version: 1.2.0.0 (GHC: 8.8.4) (PATH: ~/.local/bin/haskell-language-server) (GIT hash: 0d9ba1548a15c427963cde7f1635316c1d5ea179)
Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		2.3.3
ghc:		8.8.3

```
Which OS do you use: **Debian**

Which lsp-client do you use: **emacs**

**Comment by jneira** [comment]
wow, thanks for reporting the issue, i would say it should work with `en_US.UTF-8`, have you tried to install `ghc-lib-8.10.4.20210206` in isolation with the original `LANG` definition?

**Comment by freckletonj** [comment]
I haven't, if I installed that separately, would the `stack ./install.hs` know how to link to it instead of recompiling it itself?

**Comment by jneira** [comment]
If you execute `stack install ghc-lib-8.10.4.20210206 --stack-yaml=stack-8.8.4.yaml` i think it will not recompile it. Nevertheless the test could be used to open an issue upstream.

**Comment by michaelpj** [comment]
`install.hs` is dead.
