### ISSUE TITLE
"Couldn't figure out what GHC version the project is using"

### ISSUE THREAD

**Issue by sgronblo** [haskell/haskell-language-server#1972]
After updating VSCode recently and trying to use this plugin, it suddenly stopped working with the following error popping up:

> Couldn't figure out what GHC version the project is using: /Users/sam/Library/Application Support/Code/User/globalStorage/haskell.haskell/haskell-language-server-wrapper-1.2.0-darwin --project-ghc-version exited with exit code 1: No 'hie.yaml' found. Try to discover the project type! Failed to get project GHC version:CradleError {cradleErrorDependencies = [], cradleErrorExitCode = ExitSuccess, cradleErrorStderr = ["Couldn't execute stack exec --silent ghc -- --numeric-version"]}

If I run the included stack command `stack exec --silent ghc -- --numeric-version` I get the following output: "8.10.4"

**Comment by jneira** [comment]
Hi, thanks for reporting the issue. does the command success if you execute it in a shell opened within vscode itself? If it fails this will probably a manifestation of #236 and maybe you have to setup your `PATH` in `etc/profile`

**Comment by sgronblo** [comment]
I pressed F1, picked the option "Terminal: Focus on Terminal View". Copy paste the command. Get the same output: "8.10.4".

**Comment by sgronblo** [comment]
Ok, very strange. I had definitely tried restarting VSCode multiple times earlier too. But doing it now, it seems to be back to working 😮

**Comment by sgronblo** [comment]
Guess this can be closed for now.

**Comment by tintin10q** [comment]
I am having this issue now. I get

```
/home/programmer/.config/Code/User/globalStorage/haskell.haskell/haskell-language-server-wrapper-1.5.1-linux --project-ghc-version exited with exit code 1: No 'hie.yaml' found. Try to discover the project type! Failed to get project GHC version:CradleError {cradleErrorDependencies = [], cradleErrorExitCode = ExitFailure 1, cradleErrorStderr = ["Error when calling stack setup --silent","",""]}
```

Everything was fine a couple hours ago. The plugin completely stopped working.

**Comment by tintin10q** [comment]
I also get this message 

```
$ ghci
<command line>: cannot satisfy -package-id boxes-0.1.5-32f4691b20257738cc1934464a3ad158c96f4ce6a816e479e117154683532df3: 
    boxes-0.1.5-32f4691b20257738cc1934464a3ad158c96f4ce6a816e479e117154683532df3 is unusable due to missing dependencies:
      split-0.2.3.4-KyPtAwfJzED2zEIheQpqQL
    (use -v for more information)
```
