### ISSUE TITLE
July 2021 monthly release (1.3.0) with limited ghc 9.0 support (needs hackage release)

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#1990]
The release also would include, among other things:
* The lately amazing work done in the wingman plugin by @isovector 
* Binaries for ghc-9.0.1 (thanks to @anka-213)
  * Those binaries dont include all plugins and did not pass the entire test suite but i think we could inlcude it with noting they are in beta state (would love to know your opinion about this)
* Artifacts for ghcup for the three os's and a SHA256SUMS with the checksums from all artifacts which could be gpg signed (not sure if we will able to sign them in this one though)
* Checklist of upstream packages we need up to date to make the hackage release:
  * [ ] ghc-api-compat:
    * https://github.com/hsyl20/ghc-api-compat/pull/11
    * https://gitlab.haskell.org/haskell/ghc-api-compat/-/issues/1#note_371055
    * https://github.com/haskell/cabal/issues/4629
    * (pending pr to remove it from hls)
  * [x] remove `allow-newer`: #2097

**Comment by konn** [comment]
I think we could send to lsp clients, when called for ghc 9, some "warning" that noting GHC 9.0.1 support is in the beta stage with partial functionalities and pointing to GHC 9 tracking issue #297.
I think it is likely that some people might not be aware of release note (e.g. automaticaljy updated/installed  by lsp client), and sporadically report it as independent issues - so some auxiliary pointer at the editor level could prevent such cases.

**Comment by jneira** [comment]
> I think we could send to lsp clients, when called for ghc 9, some "warning" that noting GHC 9.0.1 support is in the beta stage with partial functionalities and pointing to GHC 9 tracking issue #297.

Good idea, a warning popup would be great

**Comment by anka-213** [comment]
Oh, does it no longer pass the test suite? What broke?

**Comment by jneira** [comment]
> Oh, does it no longer pass the test suite? What broke?

Dont worry enabled tests are passing but afaics ghc-9.0 is not tested at all in Windows and macOS and the tests of all plugins, including the enabled ones for ghc-9.0 are not being executed.

**Comment by jneira** [comment]
In fact we are not testing macOS at all :worried:

**Comment by anka-213** [comment]
I have run all the tests manually on MacOS on my machine and they worked fine there last I checked. I don't know about windows. But yes, we could enable the tests for ghc9 on windows and macos at the cost of more CI time.

**Comment by anka-213** [comment]
(I believe both windows and macos are significantly more expensive than ubuntu for github's ci time calculations, but I don't know how that matters for this project)

**Comment by jneira** [comment]
I've activated test for windows and macOs in my repo, lets see how they are going: https://github.com/jneira/haskell-language-server/actions/runs/986014293

**Comment by jneira** [comment]
Not bad at all:
```
1 out of 559 tests failed (1414.12s)
```

The failing test:

```
TH Splice Hover:                                                                                    FAIL (2.22s)
        test\exe\Main.hs:3560:
        failed to find: `Identity` in hover message:
        
        '''haskell
        id :: forall a. a -> a
        '''
        
        *Defined in 'GHC.Base'*
        
        
        
        * * *
        
        '''haskell
        _ :: Q Exp -> Q Exp
        '''
```

**Comment by konn** [comment]
> > I think we could send to lsp clients, when called for ghc 9, some "warning" that noting GHC 9.0.1 support is in the beta stage with partial functionalities and pointing to GHC 9 tracking issue #297.
> 
> Good idea, a warning popup would be great

OK, I'm tring this in #1992!

**Comment by jneira** [comment]
Would we want to see some pending pr in the next release? In the vscode extension side we have to add the alert when downloading 9.0

**Comment by jneira** [comment]
I am afraid i have not much free time as i would like to have lately, if someone want to drive the release the work would be very welcomed :worried:

**Comment by Ailrun** [comment]
I can take it over. Probably I have at least that amount of time span...

**Comment by Ailrun** [comment]
BTW; I think it will be great if #1955 can be merged within the timeframe of this release (and I guess it's feasible?). So I will wait that if no one objects.

**Comment by July541** [comment]
@Ailrun It has the basic function now, and I'll push it today asap, release the current version is OK. But it doesn't support `File of Interest`, which means the file opened in the editor may not acquire precisive results. Implement it needs at least 3-4 days probably, I have an initial thought and now working for it, would you mind waiting?

**Comment by Ailrun** [comment]
@July541 I think a few days of delay is OK (though it may become August release than July release :) ), and releasing more fully-featured one is worth the delay.

**Comment by isovector** [comment]
I'd like to land #1873 as well

**Comment by Ailrun** [comment]
@isovector, do you want to include #2038 into this release? Otherwise I will prepare the release once #2040 is merged

C.C. @pepeiborra

**Comment by isovector** [comment]
@Ailrun I plan to merge #2038 as soon as CI gets fixed, but it's not critical for the release. Feel free to cut the release whenever is convenient for you!

**Comment by jneira** [comment]
@hasufell hi! we should synchronize our release with the ghcup update. Only want to note that, until we include the binary for windows and ghc-8.8.4, as standalone zip and inside the ghcup tar and the sha list, the release is not complete (we will not unmark the prerelease check until that happens)

**Comment by Ailrun** [comment]
@jneira, could you upload GHC 8.8.4 if you have time for that? I think SHA256SUMS should also be fixed with that though

**Comment by jneira** [comment]
the release has got me away from my laptop, will start the build asap
my last trick to make it work was set `-O0` for floskell

**Comment by jneira** [comment]
i've uploaded the bin for windows and ghc-8.8.4 and udpated the windows .tar.gz and sha256sum, makint the release definitive, so it is available 🎉 
i am afraid that the related vscode extension publish has not been done due to ci problems, but the actual version will download the new version (but with no other warning than the emitted in the hls log)
https://github.com/haskell/vscode-haskell/issues/385#issuecomment-889756007

**Comment by jneira** [comment]
last lsp has been published so it is not blocking the hackage release anymore: https://github.com/haskell/lsp/issues/348
we have to check the rest of deps

**Comment by jneira** [comment]
* We will need to backport #2059 to the branch (to be created) `1.3.0-hackage`

**Comment by Ailrun** [comment]
Thank you for the note! I added the branch and created the backport PR

**Comment by jneira** [comment]
We have a terrible list of allow-newer and a source repository package over ghc-api-compat which has to be removed to get the hackage release:

https://github.com/haskell/haskell-language-server/blob/b8b962018cacb07eb0d0ef638a52b75bf3cf8a39/cabal.project#L32-L86

**Comment by jneira** [comment]
And ideally we should make packages not buildables for ghc >= 9.0.1 (as we need lot of dependencies hackage releases)

**Comment by jneira** [comment]
Ok, i am giving a try, [removing all things from cabal.project that might block the hackage release](https://github.com/haskell/haskell-language-server/compare/1.3.0-hackage...jneira:1.3.0-hackage-try?expand=1):
* It finds a build plan and builds succesfully for ghc-8.8.4
* But for ghc-8.10.5 obviously it fails

```
Resolving dependencies...
Error:
    Problem with module re-exports:
      - The module 'GHC.Platform.ARM64'
        is not exported by any suitable package.
        It occurs in neither the 'exposed-modules' of this package,
        nor any of its 'build-depends' dependencies.
    In the stanza 'library'
    In the package 'ghc-api-compat-8.6'
```

Due to removing

```
source-repository-package
  type: git
  location: https://github.com/hsyl20/ghc-api-compat
  tag: 8fee87eac97a538dbe81ff1ab18cff10f2f9fa15
```

So we would need a ghc-api-compat

**Comment by jneira** [comment]
tbh, given the amount of upstream packages we need up to date in hackage, i dont know if a hackage release will be possible before the next github one

**Comment by jneira** [comment]
I am gonna to start the compilation of packages and correlated prs/issues :sweat:

**Comment by michaelpj** [comment]
It may not be a popular position, but if we're serious about releasing to Hackage regularly we need to try really hard to avoid pulling things in via `source-repository-package` and instead get upstream to do Hackage releases :/

**Comment by jneira** [comment]
same for allow-newer's, for them and source repo packages I would ask  to include a comment linking the relevant issue/pr which resolution will allow remove it
will update contribute guidelines with that, just in case someone reads them 😝

**Comment by pepeiborra** [comment]
> Ok, i am giving a try, [removing all things from cabal.project that might block the hackage release](https://github.com/haskell/haskell-language-server/compare/1.3.0-hackage...jneira:1.3.0-hackage-try?expand=1):
> 
> * It finds a build plan and builds succesfully for ghc-8.8.4
> 
> * But for ghc-8.10.5 obviously it fails
> 
> 
> 
> ```
> 
> Resolving dependencies...
> 
> Error:
> 
>     Problem with module re-exports:
> 
>       - The module 'GHC.Platform.ARM64'
> 
>         is not exported by any suitable package.
> 
>         It occurs in neither the 'exposed-modules' of this package,
> 
>         nor any of its 'build-depends' dependencies.
> 
>     In the stanza 'library'
> 
>     In the package 'ghc-api-compat-8.6'
> 
> ```
> 
> 
> 
> Due to removing
> 
> 
> 
> ```
> 
> source-repository-package
> 
>   type: git
> 
>   location: https://github.com/hsyl20/ghc-api-compat
> 
>   tag: 8fee87eac97a538dbe81ff1ab18cff10f2f9fa15
> 
> ```
> 
> 
> 
> So we would need a ghc-api-compat release

I vaguely remember ghc-api-compat  cannot be uploaded to Hackage anymore, at least from HEAD. Maybe we need to backport the 8.10.5 fix and ask for a minor release /cc @hsyl20

Are there any other blockers for 8.10.x?

**Comment by jneira** [comment]
yeah, I commented in the ghc-api-compat issue I linked in the description of this issue: https://gitlab.haskell.org/haskell/ghc-api-compat/-/issues/1#note_371055
I have to try removing allow-newer and the constraint and see if they need some upstream release too.
Some of them are related with benchmarks and my plan is create a special cabal-benchmark.project (in master too) to isolate all the related workarounds (including the custom shake-bench)

**Comment by jneira** [comment]
Ok, finally we got to remove all the blocking `allow-newer` with no further changes 😅 (so they were obsolete)
The unique blocker then would be the release of ghc-api-compat, which needs fixes in cabal/hackage: https://github.com/haskell/cabal/issues/4629

**Comment by jneira** [comment]
As the needed fixes in cabal/hackage for being able to upload ghc-api-compat will not be done in a short period of time and @fendor has raised good points against its use (maybe we could include here for completeness?) we are gonna take the alternative of drop ghc-api-compat itself.
That has be done for HieDb itself: https://github.com/wz1000/HieDb/pull/36 and can be translated to hls as well.

**Comment by jneira** [comment]
We are exercising the automatic hacka relese here: https://github.com/jneira/haskell-language-server/runs/3545669772

The first error has been with ghcide:

```
cabal: Could not resolve dependencies:
[__0] trying: ghcide-1.4.1.0 (user goal)
[__1] trying: retrie-1.0.0.0 (dependency of ghcide)
[__2] next goal: ghc (dependency of ghcide)
[__2] rejecting: ghc-8.6.5/installed-8.6.5 (conflict: retrie => ghc>=8.8 &&
<9.2)
[__2] trying: ghc-8.10.2
[__3] next goal: base (dependency of ghcide)
[__3] rejecting: base-4.12.0.0/installed-4.12.0.0 (conflict: ghc => base<0 &&
>=4.14 && <4.15)
[__3] skipping: base-4.15.0.0, base-4.14.3.0, base-4.14.2.0, base-4.14.1.0,
base-4.14.0.0, base-4.13.0.0, base-4.12.0.0, base-4.11.1.0, base-4.11.0.0,
base-4.10.1.0, base-4.10.0.0, base-4.9.1.0, base-4.9.0.0, base-4.8.2.0,
base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1, base-4.7.0.0,
base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0, base-4.4.1.0,
base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2, base-4.2.0.1,
base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2, base-3.0.3.1 (has the
same characteristics that caused the previous version to fail: excluded by
constraint '<0 && >=4.14 && <4.15' from 'ghc')
[__3] fail (backjumping, conflict set: base, ghc, ghcide)
Backjump limit reached (currently 4000, change with --max-backjumps or try to
run with --reorder-goals).
```

//cc @pepeiborra

**Comment by pepeiborra** [comment]
Retrie dropped support for 8.6.5 a while ago.

**Comment by jneira** [comment]
uhmm and how is working master?

**Comment by pepeiborra** [comment]
ghcide doesn't specify any lower bounds on retrie, so I suppose cabal is just using an older version of retrie which builds with ghc 8.6.

**Comment by jneira** [comment]
https://github.com/haskell/haskell-language-server/actions/runs/1216111548 :crossed_fingers:

**Comment by jneira** [comment]
> 
> 
> https://github.com/haskell/haskell-language-server/actions/runs/1216111548 crossed_fingers

it worked!!!

We have to publish them definitely:

- [ ] hls-module-name-plugin-1.0.0.1
- [ ] hls-ormolu-plugin-1.0.0.1
- [ ] hls-splice-plugin-1.0.0.4
- [ ] hls-hlint-plugin-1.0.1.1
- [ ] hls-test-utils-1.1.0.0
- [ ] hls-haddock-comments-plugin-1.0.0.3
- [ ] hls-floskell-plugin-1.0.0.1
- [ ] hls-tactics-plugin-1.3.0.0
- [ ] hls-explicit-imports-plugin-1.0.0.4
- [ ] hls-plugin-api-1.2.0.0
- [ ] hls-retrie-plugin-1.0.1.1
- [ ] hls-class-plugin-1.0.0.3
- [ ] ghcide-1.4.1.0
- [ ] hls-fourmolu-plugin-1.0.0.2
- [ ] hls-stylish-haskell-plugin-1.0.0.2
- [ ] hls-call-hierarchy-plugin-1.0.0.0
- [ ] haskell-language-server-1.3.0.0
- [ ] hls-pragmas-plugin-1.0.0.1
- [ ] hls-brittany-plugin-1.0.0.2
- [ ] hie-compat-0.2.1.0
- [ ] hls-refine-imports-plugin-1.0.0.1
- [ ] hls-eval-plugin-1.1.2.0

**Comment by jneira** [comment]
Well it did want we want but the logic to skip existing packages with the same version and no changes (or throw error if there is changes) did not work well: hls-graph has not changed but is has been built

**Comment by jneira** [comment]
So this is done, if the release has any issue it will be in a new one.

Thanks to all helped in this release, specially @Ailrun, who drove the release
