### ISSUE TITLE
SQLite3 returned ErrorIO while attempting to perform step: disk I/O

### ISSUE THREAD

**Issue by timgilbert** [haskell/haskell-language-server#1994]
I suspect this is a problem local to my machine, but I'm seeing this error in my logs and HLS is failing to start:

```
ERROR hls:	Fatal error in server thread: SQLite3 returned ErrorIO while attempting to perform step: disk I/O error
```

I suspect some kind of cache or persistent store must have been corrupted somewhere, but I'm not really sure how to go about fixing it.

I've tried this with the HEAD branch, and with the latest compiled version auto-downloaded by VSCode and the results are the same in both cases.

Things were working well yesterday for me on a relatively recent commit (last several weeks); this problem started once I pulled the latest HEAD and restarted.

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
% haskell-language-server-wrapper --probe-tools
haskell-language-server version: 1.2.0.0 (GHC: 8.8.4) (PATH: /Users/tim/.local/bin/haskell-language-server-wrapper) (GIT hash: a0def3c4236b12105970b59f791bf86df666fbcc)
Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		2.7.1
ghc:		8.8.4

```
Which OS do you use: macOS 10.14

Which lsp-client do you use: vscode

Describe your project (alternative: link to the project): this is a nix-based project using cabal, but HLS is not installed by the nix environment (I usually compile from source via stack, and then set my HLS binary to `~/.local/bin/haskell-lanuage-server-8.8.4` in the vscode preferences)

Contents of `hie.yaml`:
```yaml
cradle:
  cabal:
    - path: "src"
      component: "lib:config-etl"
    - path: "app"
      component: "config-etl:config-etl-exe"
    - path: "validator"
      component: "config-etl:validator"
    - path: "test"
      component: "config-etl:config-etl-test"
  dependencies:
    - default.nix
    - shell.nix
    - package.yaml
```

### Steps to reproduce
Run haskell-language-server-wrapper

### Expected behaviour
Successful exit

### Actual behaviour
```
% haskell-language-server-wrapper
Found "/Users/tim/er/config-etl/hie.yaml" for "/Users/tim/er/config-etl/a"
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper) Version 1.2.0.0, Git revision a0def3c4236b12105970b59f791bf86df666fbcc (2288 commits) x86_64 ghc-8.8.4
Current directory: /Users/tim/er/config-etl
Operating system: darwin
Arguments: []
Cradle directory: /Users/tim/er/config-etl
Cradle type: Cabal

Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		2.7.1
ghc:		8.8.4


Consulting the cradle to get project GHC version...
Project GHC version: 8.8.4
haskell-language-server exe candidates: ["haskell-language-server-8.8.4","haskell-language-server"]
Launching haskell-language-server exe at:/Users/tim/.local/bin/haskell-language-server-8.8.4
haskell-language-server version: 1.2.0.0 (GHC: 8.8.4) (PATH: /Users/tim/.local/bin/haskell-language-server-8.8.4) (GIT hash: a0def3c4236b12105970b59f791bf86df666fbcc)
 haskell-language-server-8.8.4: SQLite3 returned ErrorIO while attempting to perform step: disk I/O error
haskell-language-server-wrapper: callProcess: /Users/tim/.local/bin/haskell-language-server-8.8.4 (exit 1): failed
```

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

Debug output:
```
haskell-language-server version: 1.2.0.0 (GHC: 8.8.4) (PATH: /Users/tim/.local/bin/haskell-language-server) (GIT hash: a0def3c4236b12105970b59f791bf86df666fbcc)
 haskell-language-server: SQLite3 returned ErrorIO while attempting to perform step: disk I/O error
```

Paste the logs from the lsp-client, e.g. for [VS Code](https://github.com/haskell/vscode-haskell#troubleshooting)

<details>
<summary>
LSP logs:
</summary>

```
ERROR hls:	Fatal error in server thread: SQLite3 returned ErrorIO while attempting to perform step: disk I/O error
```
</details>

**Comment by pepeiborra** [comment]
HEAD brings in an update to hiedb with a new schema version, so it is likely that the error is the result of schema incompatibilities. Did the error start appearing only after installing HEAD?


 I thought that schema version changes were well supported, @wz1000 any idea of what's going on?

**Comment by timgilbert** [comment]
I did notice the error after installing HEAD, yeah, but then after I rolled back to the previous commit I still saw it - maybe the new version modified my schema in a backwards-incompatible way?

Is there a sqlite `.db` file I can blow away somewhere?

**Comment by wz1000** [comment]
I don't think this is a schema error. Looks more like a permission issue. The database files should be in `~/.cache/ghcide` or `$XDG_CACHE_DIR/ghcide`.

**Comment by timgilbert** [comment]
I did verify just now that everything in `~/.cache/ghcide` was owned by me and writable, FWIW.

...and, in fact, removing that directory seems to have fixed the problem. (I've kept the old one around in case it's useful for analysis.) I'm fine to close this ticket for now unless it's useful to you for debugging purposes. Thanks!

**Comment by pepeiborra** [comment]
A plausible explanation is that an old instance of ghcide was locking the db and preventing the upgrade to the new version

**Comment by michaelpj** [comment]
Closing as old and quiet
