### ISSUE TITLE
Eta-reduced constrained variables become GHC.Types.Any in suggested type signatures

### ISSUE THREAD

**Issue by Fybe** [haskell/haskell-language-server#2006]
### Steps to reproduce
By writing the following function definitions
```haskell
f = show

g = (+)

h = (>0)
```
and selecting the suggested type signatures, one obtains
```haskell
f :: ghc-prim-0.6.1:GHC.Types.Any -> String
f = show

g :: ghc-prim-0.6.1:GHC.Types.Any -> ghc-prim-0.6.1:GHC.Types.Any -> ghc-prim-0.6.1:GHC.Types.Any
g = (+)

h :: ghc-prim-0.6.1:GHC.Types.Any -> Bool
h = (>0)
```

Interestingly, after eta expanding it works as expected:
```haskell
f :: Show a => a -> String
f a = show a

g :: Num a => a -> a -> a
g a = (a+)

h :: (Ord a, Num a) => a -> Bool
h a = a > 0
```

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 1.2.0.0 (GHC: 8.10.4) (PATH: /home/finn/.config/Code/User/globalStorage/haskell.haskell/haskell-language-server-1.2.0-linux-8.10.4) (GIT hash: be2071e985cb417f984ab00a1aad76dee02d6d0b)
Tool versions found on the $PATH
cabal:		3.0.0.0
stack:		2.5.1
ghc:		8.8.4
```
Which OS do you use:
Fedora 34

Which lsp-client do you use:
VS Code

**Comment by berberman** [comment]
Did you tweak GHC extensions? With [`MonomorphismRestriction`](https://wiki.haskell.org/Monomorphism_restriction) which is enabled by default nowadays, your `f = show` shouldn't compile, the inferred type of `g = (+)` should be `g :: Integer -> Integer -> Integer`, and `h = (>0)` should be `h :: Integer -> Bool`. IMHO this typechecking manner has nothing to do with HLS.

**Comment by Fybe** [comment]
Hey, you are right, enabling NoMonomorphismRestriction makes it work! Sorry for the wrong issue then...
