### ISSUE TITLE
Is bringing up a REPL within the scope of HLS?

### ISSUE THREAD

**Issue by korayal** [haskell/haskell-language-server#202]
I'm using HLS via haskell-lsp on Emacs and right now we have to run `haskell-interactive-switch` command from `haskell-mode` to drop into a REPL, or load current module in it. And it seems if I'm not in a source module, some dependencies do not get picked up and it fails.

So, I was wondering if there's a plan to take over the task of bringing up a REPL, or is this out of the scope for this project.

**Comment by jneira** [comment]
It somewhat related with the [new pr](https://github.com/haskell/haskell-language-server/pull/191) adding the feature of evaluate embedded in docs expressions in a repl. [In a pr comment](https://github.com/haskell/haskell-language-server/pull/191#issuecomment-657011442) it was mentioned the possibility of evaluate module definitions directly (and he issue #94).
So it is not exactly the same cause you dont have a full repl session but i think it is related.

**Comment by alanz** [comment]
There is an intention to have one eventually, but this is tied to some upstream GHC features too. And I can never locate the issue I am thinking of, to do with API access and repl at the same time.

**Comment by jneira** [comment]
The question was answered and there is a newer issue tracking the repl feature, so closing
