### ISSUE TITLE
Change "About" description (again).

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#2028]
From irc

> isovector: what do yall think about changing the "About" on GH for hls
> right now it mentions ghcide and hie... but those are both ancient and probably nobody except the people in this room know about what they are or care about the history of hls

Agree with @isovector, suggestions?

**Comment by Anrock** [comment]
I still sometimes see people (newcomers mostly) asking about tooling and mentioning ghcide and hie. So I guess mentioning HLS as successor to both is probably still a good idea to clear up confusion.

**Comment by Ailrun** [comment]
As our error messages often mention ghcide, I think it is still great to leave the description somewhere in the repo; I'm not sure whether "About" is the best title for the section though.

**Comment by jneira** [comment]
I dont fully like the "one ide to rule them all" neither as there are other haskell ides (like ghcid) with different feature sets, design and goals, that can (and imo should) coexist with hls.

**Comment by jneira** [comment]
* [rust](https://github.com/rust-analyzer/rust-analyzer): "A Rust compiler front-end for IDEs"
* [purescript](https://github.com/nwolverson/purescript-language-server): No description, website, or topics provided. :open_mouth: 
* [idris](https://github.com/idris-community/idris2-lsp): "Language Server for Idris2" 
* [clojure](https://github.com/clojure-lsp/clojure-lsp): "Language Server (LSP) for Clojure" :+1:
* [erlang](https://github.com/erlang-ls/erlang_ls): "The Erlang Language Server" (dont like `the` for us)

**Comment by jneira** [comment]
So what about: "Language server (LSP) for haskell. Successor of ghcide & haskell-ide-engine."

**Comment by jneira** [comment]
"Succesor of ghcide" could be a little bit confusing as we are *using* ghcide as a lib. I think we could remove the succesor thing in 2 or three years :-P

**Comment by jneira** [comment]
Will change the description as https://github.com/haskell/haskell-language-server/issues/2028#issuecomment-890762353 if nobody disagree

**Comment by Ailrun** [comment]
How about "Standard"/"Official" ("Language Server ...")? Sometimes just saying "Language Server" feels little unofficial (especially as language server is usually not the most used IDE(-like) in may other languages)

**Comment by jneira** [comment]
mmm dont want to be unpolite with other haskell language servers in any way, nor discourage the creation of new ones, but i agree with you.
What about "Official haskell ide support via language server (LSP). Succesor..."?

**Comment by Ailrun** [comment]
I think that's great, thank you for suggesting the new phrase.

**Comment by jneira** [comment]
Will change the description as https://github.com/haskell/haskell-language-server/issues/2028#issuecomment-890775847 if nobody disagree

**Comment by jneira** [comment]
Changed! I hope you like the new phrasing although it still includes refs to hie and ghcide @isovector
