### ISSUE TITLE
HLint doesn't report "Unused LANGUAGE pragma"

### ISSUE THREAD

**Issue by georgefst** [haskell/haskell-language-server#2042]
File contains just:
```hs
{-# LANGUAGE BangPatterns #-}
```
HLS reports no warnings. HLint 3.2.7 on the command line says:

```
haskell/Main.hs:1:1-29: Warning: Unused LANGUAGE pragma
Found:
  {-# LANGUAGE BangPatterns #-}
Perhaps you should remove it.
```

Odd. Is HLS intentionally disabling these hints for some reason?

**Comment by jneira** [comment]
Hmm i would swear i've seen warning about unused pragmas at some point, will try to reproduce

**Comment by georgefst** [comment]
Thanks. Let me know if you can't and I'll try to narrow it down.

**Comment by jneira** [comment]
Can reproduce at first, not sure when it has started to fail, maybe since the pr which added support for ghc-9
We need a regression test here and investigate
