### ISSUE TITLE
Add documentation to plugins

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#2066]
* We have no documentation about each plugin but [wingman ](https://github.com/haskell/haskell-language-server/tree/master/plugins/hls-tactics-plugin) (kudos to @isovector for taking care of)
* This is :disappointed: and makes their use, maintenance and contributor initial work harder
* The documentation could live in the readme of each one (like wingman)
* As part of such documentation we could include the relevant server configuration (so we will make progress on #1433)
* It should include:
  * demos on how it works and a general description
  * the configuration controlling it as commented above
  * requirements to make it work (see #2064), kown issues, etc
  * tech doc about its organization, tech decisions made and their rationale, etc

**Comment by jneira** [comment]
> 
> 
> I added a document in the call hierarchy, maybe we can let this as an example.

Of course! many thanks, i think we should ask for something similar for the new plugins (and work hard to add it for the existing ones)

**Comment by jneira** [comment]
We have to do a check list here with the plugins and the current status of their docs

**Comment by July541** [comment]
A track list
- ghcide
  - [x] core (https://github.com/haskell/haskell-language-server/blob/master/ghcide/README.md)
  - [ ] hover and symbols
  - [ ] code actions imports exports
  - [ ] code actions type signatures
  - [ ] code actions bindings
  - [ ] code actions fill holes
  - [ ] completions
  - [ ] type lenses
- [ ] hls-brittany-plugin
- [x] hls-call-hierarchy-plugin
- [x] hls-class-plugin (https://github.com/haskell/haskell-language-server/blob/master/plugins/hls-eval-plugin/README.md)
- [ ] hls-eval-plugin
- [ ] hls-explicit-imports-plugin
- [ ] hls-floskell-plugin
- [ ] hls-fourmolu-plugin
- [ ] hls-haddock-comments-plugin
- [ ] hls-hlint-plugin
- [ ] hls-module-name-plugin
- [ ] hls-ormolu-plugin
- [ ] hls-pragmas-plugin
- [ ] hls-refine-imports-plugin
- [ ] hls-retrie-plugin
- [ ] hls-splice-plugin
- [ ] hls-stylish-haskell-plugin
- [x] hls-tactics-plugin (https://github.com/haskell/haskell-language-server/blob/master/plugins/hls-tactics-plugin/README.md), [Command](https://github.com/haskell/haskell-language-server/blob/master/plugins/hls-tactics-plugin/COMMANDS.md)

**Comment by jneira** [comment]
The actual features doc page could link to each plugin as suggested by @michaelpj , once their docs are completed (or gradually while the plugins are being completed)

**Comment by michaelpj** [comment]
:+1: to this.

We have some readmes already, it would be great to have more! I'd also like to incorporate them into the doc build properly... perhaps I can symlink them in so that sphinx will index them as part of the main project? :thinking:

**Comment by July541** [comment]
> 

I updated the state by my personal search, not sure if contains all. https://github.com/haskell/haskell-language-server/issues/2066#issuecomment-892594879

**Comment by fendor** [comment]
This looks completed to me, thank you everyone!
