### ISSUE TITLE
Install script downloads the wrong version of ghc

### ISSUE THREAD

**Issue by davidspies** [haskell/haskell-language-server#207]
When I try to run the install script as in the readme it insists on downloading ghc-8.6.5

```
$ stack ./install.hs hls-8.8.4
ghc-8.6.5:    8.61 MiB / 175.83 MiB (  4.90%) downloaded...^C

```

**Comment by fendor** [comment]
The install script is run with ghc 8.6.5. 
So, this is expected behaviour.

**Comment by jneira** [comment]
To match the ghc used by the script and the used one for install hls, you can change the resolver of ./install/shake.yaml to match the stack-${ghcVersion}.yaml one

**Comment by bubba** [comment]
I think we can close this then, but just to clarify for anyone else stumbling across this ghc-8.6.5 is the version of ghc being downloaded to run the installer script itself, not for haskell-language-server
