### ISSUE TITLE
Hole fit suggestions don't work.

### ISSUE THREAD

**Issue by klapaucius** [haskell/haskell-language-server#2071]
I understand that the plugin was switched off because of problems with the Wingman plugin, but I believe that it's a big mistake. Hole fits is a useful and proven tool. I'm searching for existing fitting functions all the time. Wingman is pretty interesting, but I don't write recursive definitions of `foldr` that much, if at all.

**Comment by jneira** [comment]
Sorry to read that you prefer the old behaviour. Not sure if it could be restored easily, @isovector?

**Comment by isovector** [comment]
`"haskell.plugin.tactics.globalOn": false`

For what it's worth, this isn't really a Wingman thing. The implementation of hole fits is atrociously slow, and GHC is also disabling them by default.

> Wingman is pretty interesting, but I don't write recursive definitions of foldr that much, if at all.

I think you might have the wrong of the stick about what Wingman does :)

**Comment by jneira** [comment]
@klapaucius something else to be done here? maybe a note in docs?

**Comment by klapaucius** [comment]
I would prefer the configuration option that stops adding a lot of typed holes. I believe the case split could work without adding holes, and it's a useful part of Wingman.
But note in docs is fine.

**Comment by isovector** [comment]
@klapaucius please send a PR!
