### ISSUE TITLE
Code evaluation links appear, but do not work

### ISSUE THREAD

**Issue by nathanKramer** [haskell/haskell-language-server#2073]
Mac OSX Catalina 10.15.2
VS Code Version: 1.54.3
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Haskell Extension Version: 1.2.0

As you can see in the below video:

- I disable all extensions
- I enable the haskell extension
- ✅ the code evaluation links are appearing correctly
- ✅ I'm seeing some sort of indication that the language server is evaluating the code
- ❌ The file is not being changed

https://user-images.githubusercontent.com/4732403/112234801-69e9ab00-8c91-11eb-997c-b35075e712d6.mov

Also, I noticed after recording that I chose a bad example that would throw an error if run, to be clear it also doesn't work with a trivial example like the following:

```
-- >>> 1 + 1
--
```

**Comment by jneira** [comment]
@nathanKramer sorry i missed completely this issue. Maybe the eval plugin bug causing the bug is resolved in newer hls versions, coud you try it again? thanks!

**Comment by nathanKramer** [comment]
I've moved on from this and can't reproduce, let's hope it was an anomaly and rely on someone else reporting in the future if a problem exists.
