### ISSUE TITLE
Autocompletion no longer counts qualified imports

### ISSUE THREAD

**Issue by Akhristenko** [haskell/haskell-language-server#2082]
### Steps to reproduce
I have 2 modules
```haskell
module MyModule (myid) where

myid :: a -> a
myid a = a
```
```haskell
module MyModuleB (myid') where

import qualified MyModule

myid' :: a -> a
myid' = MyModule.myid
```
I delete `myid` in second module and invoke autocompletion when cursor placed after `MyModule.`

### Expected behaviour
In autocompletion list i see only functions from MyModule

### Actual behaviour
In autocompletion list i see all function from all modules

**Comment by pepeiborra** [comment]
Thanks for reporting, this is likely a regression after #2040

**Comment by pepeiborra** [comment]
I'm not so sure this is a regression anymore. It's actually a new feature! Previously autocompletion only suggested imported identifiers, now it suggests also unimported identifiers and automatically inserts a new import if necessary. Qualifiers are no longer used only for filtering, but also to inform the format of the inserted import. However qualifiers are still used for filtering, and list of completions should put the functions from current imports first. Can you confirm whether this is the case for you?

**Comment by Akhristenko** [comment]
> However qualifiers are still used for filtering, and list of completions should put the functions from current imports first.

It's not true, at least on version 1.3.0 it show all names in alphabetical order. But if hls will showing names imported in qualifiers ordered alphabetically before all other names it will solve this issue.

**Comment by Akhristenko** [comment]
ideally i would like this behavior:
- if we invoke autocomplete on qualifier, which was not imported, we see all functions and autoimport perform after we select one of them.
- if we invoke autocomplete on qualifier, which was imported, we see only functions which was imported. But if we invoke autocomplete second time we see all functions and can autoimport one of them.

**Comment by alexnaspo** [comment]
I would be interested in attempting this. Is it currently possible to get a list of all of the possible exported functions in a plugin for a given module?

**Comment by alexnaspo** [comment]
I see a decent path forward on this one, is it worth picking up? @pepeiborra

**Comment by pepeiborra** [comment]
I would start with a set of tests demonstrating the problem, and then we can discuss what needs to be done to enforce the behaviour that I outlined above.

Implementing the behaviour that @Akhristenko suggested is not something I would recommend. "If we invoke autocomplete a second time" is not a condition that the LSP server can detect.
