### ISSUE TITLE
Automatically update data on build

### ISSUE THREAD

**Issue by Trebor-Huang** [haskell/haskell-language-server#2085]
I'm using stack version 2.7.3, vscode-haskell version 1.5.1.

When I update something in one file, e.g. change a type signature or add a function, the change is not reflected when I edit another file, until I build the project and reload. So when I'm jumping back and forth between two files, I need to reload the plugin a lot.

Is it possible to automatically update when I compile the project? Or even better, is it possible without even recompiling?

**Comment by Ailrun** [comment]
I think the issue here is the same as #1822: cross-section definition. New definitions or type signature changes in `library` section are not reflected immediately (before rebuild) to other sections, like `executable` or `test`

**Comment by jneira** [comment]
@Trebor-Huang hi, I think it is a duplicate too, so i closed this, feel free to reopen if you think your issue differs in any way the mentioned one. There you could track its eventual resolution
