### ISSUE TITLE
Hackage version behind this repo: `1.2.0.0` versus `1.3.0`?

### ISSUE THREAD

**Issue by peterbecich** [haskell/haskell-language-server#2089]
I see the latest version of `haskell-language-server` in Hackage is 1.2.0.0:
<img width="359" alt="Screen Shot 2021-08-11 at 12 24 18 PM" src="https://user-images.githubusercontent.com/6315338/129090660-7b56469b-2ce4-4875-95fb-eade1ec83cd2.png">
https://hackage.haskell.org/package/haskell-language-server-1.2.0.0

and the latest version in this repository is 1.3.0: https://github.com/haskell/haskell-language-server/releases/tag/1.3.0

The latest version provided by ghcup is also 1.3.0:
```
✔✔ hls   1.3.0          latest,recommended
```

Is there something I don't know about how the versioning of this project works?
Thanks

### Expected behaviour
The latest version on Hackage would be `1.3.0.0`

### Actual behaviour
The latest version on Hackage is `1.2.0.0`

**Comment by Ailrun** [comment]
1.3.0 is not uploaded to Hackage yet. You may want to subscribe https://github.com/haskell/haskell-language-server/issues/1990 to see the progress. (The issue will be closed once 1.3.0 is uploaded to Hackage).

I will close this issue as the uploading process is tracked in the linked issue. If there's any other problems, feel free to reopen!

**Comment by peterbecich** [comment]
Thanks very much
