### ISSUE TITLE
Disabling "explicit imports code lenses" does not seem to work

### ISSUE THREAD

**Issue by edsko** [haskell/haskell-language-server#2098]
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 1.3.0.0 (GHC: 8.10.4) (PATH: /home/edsko/.ghcup/bin/haskell-language-server-wrapper-1.3.0) (GIT hash: e7c5e90b6df5dff2760d76169eddaea3bdd6a831)
Tool versions found on the $PATH
cabal:		3.4.0.0
stack:		2.7.3
ghc:		8.8.4
```
Which OS do you use:
Ubuntu
Which lsp-client do you use:
vscode
Describe your project (alternative: link to the project):
https://github.com/well-typed/large-records (cabal file, cabal project file)
Contents of `hie.yaml`:
Don't use one

### Steps to reproduce
When "Enables explicit imports code lenses" is enabled, the import section of my example looks like

![image](https://user-images.githubusercontent.com/935288/129548631-d0c5d848-4f9e-4be0-ac93-9ed12297757c.png)

After disabling, it looks like

![image](https://user-images.githubusercontent.com/935288/129548695-e1b172b3-ea42-4d96-aa9a-ecce63b05a7b.png)

### Expected behaviour

I'd not expect to see any import lenses anymore (but maybe I'm misunderstanding the setting?).

### Actual behaviour

_Some_ import lenses are gone, but not all.

**Comment by edsko** [comment]
Actually, this is probably a vscode integration issue, rather than a HLS issue. Will reopen in the appropriate repo.

**Comment by pepeiborra** [comment]
The lenses you are seeing now are created by a different plugin: refine imports
