### ISSUE TITLE
"Conflicting family instance declarations" false positive

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#210]
From https://github.com/haskell/haskell-language-server/issues/175#issuecomment-660865914:

> Small progress: my remaining issue seems to be exactly the same as digital-asset/ghcide#641
>
> Should we keep this issue open?

**Comment by istathar** [comment]
I think I just ran into this. It wasn't a problem with 0.4.0 but when the vscode extension downloaded 0.5.0 suddenly I'm getting dozens of errors that look like:

```
Conflicting family instance declarations:
  Token Label = TechniqueToken
    -- Defined at /home/andrew/src/technique-lang/technique/lib/Technique/Formatter.hs:242:8
  Token Label = TechniqueToken
    -- Defined in module Technique.Formatter typecheck
```

which is clearly spurious. The build outside from the command-line works fine. Is there a way to work around this perchance?

AfC

**Comment by aviaviavi** [comment]
I'm also seeing this in 0.5.0, but was seeing it in the previous version too. Our app compiles just fine, but haskell-language-server is failing on files, complaining of this "conflicting family instance declaration"

**Comment by ilyakooo0** [comment]
Still happens in 0.8.0

**Comment by jneira** [comment]
Colsing in favor of #773 (ported from ghcide)

**Comment by Sorokin-Anton** [comment]
Tee this wrong messages appears in hls-1.7.0.0 too, when type family is defined in other loaded package
