### ISSUE TITLE
Outline looks very odd in emacs

### ISSUE THREAD

**Issue by michaelpj** [haskell/haskell-language-server#2103]
This may well be a `lsp-mode` bug, but I thought it was worth opening here in case anything jumps out at people.

![imenu1](https://user-images.githubusercontent.com/1699466/129723878-742b2967-6943-4c49-81b9-516e3f3e5eb4.png)

There are several weird things in this screenshot:
- The item for `imports` appears above the module item
- Items display badly, sometimes just displaying part of the instance context, not even the class name. Especially bad if the context contains newlines!
- Newtypes have something extremely messed up where the constructor is rendered before the newtype itself or something?

I wonder if we're sending weird document symbol information.

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 1.1.0.0 (GHC: 8.10.4) (PATH: /nix/store/nlzddq1c1x7h3lhwmfq3gvrh2aql2c0m-haskell-language-server-exe-haskell-language-server-1.1.0.0/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:          3.4.0.0
stack:          2.7.3
ghc:            8.10.4.

```
Which OS do you use:
NixOs
Which lsp-client do you use:
emacs, lsp-mode
Describe your project (alternative: link to the project):
cabal.project
Contents of `hie.yaml`:

### Steps to reproduce
Open a file with any stuff and open `lsp-ui-imenu`.

**Comment by michaelpj** [comment]
I tried again today and it was fine, _apart_ from the instance rendering issue. So I have no idea what was going on there :/

**Comment by Ailrun** [comment]
Actually I can reproduce this issue in the latest Emacs 28. `imports` goes above, and the order of constructors and field accessors is messed up, etc.
