### ISSUE TITLE
Go to references

### ISSUE THREAD

**Issue by Sir4ur0n** [haskell/haskell-language-server#211]
Hi,

It looks like HLS currently doesn't support "Go to References" family of features, am I correct?

Basically this allows one to find places where a particular piece of code (function/type) is used.

What do you think about adding this feature?

Cheers

**Comment by fendor** [comment]
Hi! 

Indeed, hls does not support this feature yet.
There is a WIP branch of ghcide to support it: https://github.com/wz1000/ghcide/tree/hiedb-2
It uses HIE files and a sqlite database.
I use this branch as a daily driver but it still has some bugs.

Maybe @wz1000 can tell us how we can help to get this feature :)

**Comment by jneira** [comment]
[There is a open pr to add hie-db to ghcide](https://github.com/haskell/ghcide/pull/898), it should add this feature.

**Comment by jneira** [comment]
In ghcide @meditans mentioned the `find-references` feature. As it seems to be related with this we are gonna include here.
In vscode the unique command i can find is `References: Find All Implementantions`. Not sure if @meditans was referring to though.

**Comment by meditans** [comment]
@jneira in `emacs` there's the command `lsp-find-definition` that works as intended, and the command `lsp-find-references` that should bring you to where a variable is used and instead gives back the error:
```
helm-M-x-execute-command: The connected server(s) does not support method textDocument/references.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
```
How were @fendor and @wz1000 using it?

More broadly, I'm not sure what the status of this feature is, as the linked issue https://github.com/haskell/ghcide/pull/898 has been recently closed with the migration to `hls`. Who is working on this? What needs to be done?

**Comment by jneira** [comment]
that ghcide pr has been moved to this repo as #704

**Comment by jneira** [comment]
And the pr has been merged so go to references should work now
@Sir4ur0n @meditans
