### ISSUE TITLE
hls crashes after `Can't find interface-file declaration for variable` errors

### ISSUE THREAD

**Issue by marklemay** [haskell/haskell-language-server#2113]
I am getting the "The Haskell (...) server crashed 5 times in the last 3 minutes. The server will not be restarted." possibly because "Request textDocument/codeAction failed".

I disabled almost all optional plugin functionality and generated this [log](https://github.com/haskell/vscode-haskell/files/7008942/bug-4.txt)

Unfortunately I cannot make a simple project that exercises this error.  I can share a private repo where it seems to always happen if that helps.  There may be different errors that make this hard to reproduce.

according to visual studio code:
```
Version: 1.55.1 (Universal)
Commit: 08a217c4d27a02a5bcde898fd7981bda5b49391b
Date: 2021-04-07T18:22:52.186Z (4 mos ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.4.0
```

follow up to: https://github.com/haskell/vscode-haskell/issues/429

**Comment by jneira** [comment]
The error was produced din hie: https://github.com/haskell/haskell-ide-engine/issues/1100

**Comment by jneira** [comment]
@marklemay do you use template haskell in the problematic files?

**Comment by michaelpj** [comment]
I have been meaning to open an issue like this, I often see a similar error.

**Comment by marklemay** [comment]
@jneira 
cabal repl src/Dynamic/Ast.hs seems to work though it doesn't do to the correct module.  in the repl :l src/Dynamic/Ast.hs takes me there without errors

I don't believe there is template Haskell in that file specifically, though there are a lot of exotic features used elsewhere in that project.

**Comment by michaelpj** [comment]
Closing as old and quiet
