### ISSUE TITLE
Flaky GHCIDE test: `Timestamps do not have millisecond` (ignored for now)

### ISSUE THREAD

**Issue by isovector** [haskell/haskell-language-server#2115]
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:
CI 

Which OS do you use:
Ubuntu latest

### Steps to reproduce
CI is flakey. It reproduces itself.

### Expected behaviour
Tests should reliably pass.

### Actual behaviour

https://github.com/haskell/haskell-language-server/runs/3373456727

```
ghcide
  Unit
    timestamps have millisecond resolution: FAIL (0.02s)
      test/exe/Main.hs:5677:
      Timestamps do not have millisecond resolution: 10000us
```

This happens roughly 10% of the time

**Comment by anka-213** [comment]
Maybe is just luck that makes it work as much as 90% of the time? Would increasing the tolerance to not require millisecond resolution be a solution?

We could modify `findResolution_us` to return the actual difference in timestamp (`t' - t`) in order to help diagnose the problem.

**Comment by jneira** [comment]
https://github.com/haskell/haskell-language-server/runs/3504012776?check_suite_focus=true testing #2154

```
Test suite ghcide-tests: RUNNING...
ghcide
  Unit
    timestamps have millisecond resolution: FAIL (0.03s)
      test/exe/Main.hs:5717:
      Timestamps do not have millisecond resolution: 10000us
```

:worried: reopening just in case

**Comment by isovector** [comment]
I just hit this too. Definitely still happening.

**Comment by jneira** [comment]
Sorry but i am ignoring it with https://github.com/haskell/haskell-language-server/pull/2182/commits/692a26e2b358adf212f346b26eb9299103309593 to not block ci

**Comment by isovector** [comment]
Thanks @jneira. I was just about to send a PR doing that
