### ISSUE TITLE
Question - refactoring to plug-ins

### ISSUE THREAD

**Issue by alexnaspo** [haskell/haskell-language-server#2140]
Are there any pieces of functionality that are currently implemented in ghcide (or anywhere else) that should be moved to HLS plugins?

If so, I would love to contribute to any of these initiatives.

**Comment by jneira** [comment]
Hi, many thanks for willing to contribute to the repo.
The first one of pending refactors which come to my mind is the move of hlint tests to its plugin. Now they live in the main test component of hls:

https://github.com/haskell/haskell-language-server/blob/a800b9d71e4eac70d672d30b2488949ea26dcbc3/test/functional/FunctionalCodeAction.hs#L40

But it should be in the plugin package:

https://github.com/haskell/haskell-language-server/tree/master/plugins/hls-hlint-plugin
