### ISSUE TITLE
Extension should reload when cabal file changes

### ISSUE THREAD

**Issue by a3b4c6** [haskell/haskell-language-server#2150]
Whenever I tweak my cabal file (e.g. declare a module or add a dependency), I have to manually restart the server (using `haskell.commands.restartServer`). I was expecting the extension to detect any change to my cabal file and automatically restart the server. Would it be a good idea? How would it be implemented?

**Comment by jneira** [comment]
Sorry the link was broken, i've moved the issue to the hls repo and it works now
