### ISSUE TITLE
Support for stack scripts

### ISSUE THREAD

**Issue by fyusuf-a** [haskell/haskell-language-server#2201]
It is possible to execute a stack program outside of a stack project and with only one file using the lines provided [in the documentation](https://docs.haskellstack.org/en/stable/GUIDE/#script-interpreter). Would it be possible to implement support for this in your project ?

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 1.2.0.0 (GHC: 8.8.4) (PATH: /home/fyusuf-a/.cabal/store/ghc-8.8.4/haskell-language-server-1.2.0.0-e-haskell-language-server-3fd296f99d374f7cd5ffa3f1119c810ac75c1cf90b40963ae8d113fadbfa9dc5/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:		3.3.0.0
stack:		2.7.3
ghc:		8.8.4

```
Which OS do you use:
Ubuntu
Which lsp-client do you use:
Neovim with coc.nvim

Describe your project (alternative: link to the project):

Content of Main.hs :
```haskell
#!/usr/bin/env stack
-- stack script --resolver lts-12.21 --package async

import Control.Concurrent.Async
import Data.Foldable (traverse_)

main = undefined
```

### Steps to reproduce
```sh
chmod +x Main.hs
./Main.hs
```

### Expected behaviour
No linting for errors should happen.

### Actual behaviour
The haskell-language-server should report no error.

**Comment by jneira** [comment]
hi, thanks for reporting the issue
we have an issue about here https://github.com/haskell/haskell-language-server/issues/111
you can read it there is no workaround for now and a linked issue in stack which will enable it

**Comment by jneira** [comment]
so I am gonna close it if you don't mind, you can track the progress in the mentioned issue

**Comment by fyusuf-a** [comment]
Sorry I have missed this issue.

**Comment by jneira** [comment]
dont worry, it serves as a signal people is hitting the issue and need the fix 🙂
