### ISSUE TITLE
Update freebsd installation instructions

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#2204]
* After having prebuilt binaries with #2200
* From #1769
//cc @arrowd @hasufell

**Comment by arrowd** [comment]
Repeating my comment here:

> From what I can tell, FreeBSD binaries are being produced for FreeBSD 13. They should be produced on FreeBSD 12.2 to be compatible with both 12 and 13.

> I also prefer our Ports for producing packages, but if this works out - sure, why not.
