### ISSUE TITLE
Create proper source tarballs in CI/on releases

### ISSUE THREAD

**Issue by hasufell** [haskell/haskell-language-server#2216]
Implementing https://gitlab.haskell.org/haskell/ghcup-hs/-/merge_requests/180 I need proper source tarballs.

The default ones are:

1. autogenerated and would depend on github not messing with the tarball layout (they did so at least twice) for the hash to be stable
2. depend on the tag (yeah, if you force push, the hash changes too)
3. have bad tarball names like `1.4.0.tar.gz`, causing trouble for ghcup

Something like:

```sh
git archive --prefix=haskell-language-server-${version}/ --format=tar.gz -o haskell-language-server-${version}.tar.gz HEAD
```

in CI should do the trick.

**Comment by jneira** [comment]
@hasufell the mr is merged and released, how could improve it creating source tarballs here? are you using them from gitlab in the actual version?

**Comment by hasufell** [comment]
ghcup is using the source tarballs

**Comment by jneira** [comment]
> 
> 
> ghcup is using the source tarballs

the default ones from github? so improving them would allow clean ghcup code

**Comment by hasufell** [comment]
> the default ones from github? so improving them would allow clean ghcup code

I don't understand what you mean. ghcup needs source tarballs to compile HLS from source. The automatically generated aren't good enough as I described in the first comment.

**Comment by jneira** [comment]
> ghcup is using the source tarballs

hmm so if default ones are not valid and we are not generating in github the good ones yet, Where are the tarballs it is using now from?

**Comment by hasufell** [comment]
> Where are the tarballs it is using now from?

Created on my own.

**Comment by jneira** [comment]
thanks, will add a job in the build workflow to generate and add them to sha256 sums
