### ISSUE TITLE
VSCode Wingman "Use custom Tactics Block" doesn't work 

### ISSUE THREAD

**Issue by ProofOfKeags** [haskell/haskell-language-server#2229]
Environment: VSCode
HLS 1.3.0
Linux

Simply results in a pair of errors
![Screenshot from 2021-09-22 01-08-51](https://user-images.githubusercontent.com/4033651/134298545-c915ccc9-0a2e-43e6-a357-e56dfaa32e61.png)

**Comment by jneira** [comment]
@ProofOfKeags thanks for reporting the bug, what is the custom block?
//cc @isovector

**Comment by ProofOfKeags** [comment]
That's just it. I am never given the opportunity to even put one in. So I suppose the block is "", but I think the real issue here is how do I input a custom block in vscode?

**Comment by isovector** [comment]
What version of GHC? You can type one out by hand: `[wingman| |]`. My guess is that somewhere you have an explicit `NoTemplateHaskell` or `NoTemplateHaskellSyntax`?

**Comment by ProofOfKeags** [comment]
8.10.4 and afaict theres nothing interfering with templatehaskell. I built 1.3.0 from source rather than pulling from ghcup. I can also reattempt with 1.4.0 if theres any chance that will fix it.

It is a possibility that the problem isn't in the language server but is instead in the VSCode plugin side. It's really tough to say. If you have a method of telling the difference I could try it and report back.

**Comment by isovector** [comment]
If you could post the debug log, it'd be helpful!

**Comment by isovector** [comment]
Closing due to no repro. Feel free to reopen if you get one!
