### ISSUE TITLE
Add language extension code action targets atop module definition

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#2233]
* Reported in discord https://discord.com/channels/280033776820813825/505370075402862594/890307437926686790

![imagen](https://user-images.githubusercontent.com/54035/134409539-8df269f6-913d-4b21-909d-4bb90e75e6db.png)

* The fourth issue about wrong placement of pragmas 🤦

**Comment by Ailrun** [comment]
@skykanin said it was HLS 1.1, but maybe it also happens in the latest HLS, so it's worth to check whether it works as expected here or not.

**Comment by jneira** [comment]
I've not reproduced it with 1.4.0:

```haskell
{-# LANGUAGE CPP #-}
{- |
   A comment
-}
module Lib where
```

```haskell
{-# LANGUAGE CPP #-}
{-# LANGUAGE RankNTypes #-}
{- |
   A comment
-}
module Lib where
```

i hope the content of the comment is not related

**Comment by skykanin** [comment]
> I've not reproduced it with 1.4.0:
> 
> ```haskell
> {-# LANGUAGE CPP #-}
> {- |
>    A comment
> -}
> module Lib where
> ```
> 
> ```haskell
> {-# LANGUAGE CPP #-}
> {-# LANGUAGE RankNTypes #-}
> {- |
>    A comment
> -}
> module Lib where
> ```
> 
> i hope the content of the comment is not related

```hs
{- |
   Module      : Test.QuadTree
   License     : GNU GPL, version 3 or above
   Maintainer  : skykanin <3789764+skykanin@users.noreply.github.com>
   Stability   : alpha
   Portability : portable
 Unit tests ensuring proper behaviour of the QuadTree data structure
-}
```
Here is the full comment if you want to test

**Comment by jneira** [comment]
it works too, thanks!

![imagen](https://user-images.githubusercontent.com/54035/134412628-6acdd1a3-8b97-462c-94bf-d8de15091b5e.png)
