### ISSUE TITLE
sidestream bit leak... 

### ISSUE THREAD

**Issue by C-BAND** [haskell/haskell-language-server#2236]
`Bit Flagging` inside Haskell Compiler, has been causing sidestream BiT leak, in Haskell Main Memory Object, can it be reversed?

Or, Can zombie RCO: herein Haskell's TCO, be enqued; for debug information to be absolute TruTh?

**Comment by ndmitchell** [comment]
Hi @C-BAND - I'm afraid there isn't enough information in this ticket to act, Can you please explain the issue, how to reproduce it, and in particular the OS/GHC/HLS versions you are running with.

**Comment by C-BAND** [comment]
Was this issue in not reproducible on wsl?

**Comment by C-BAND** [comment]
after, memory.log.enque = array.true, this was patchble inside haskell compiler. So would have factorial yield of main memory performance macine.
