### ISSUE TITLE
Auto import doesn't work in some cases

### ISSUE THREAD

**Issue by Akhristenko** [haskell/haskell-language-server#2238]
### Your environment
```sh
haskell-language-server version: 1.4.0.0 (GHC: 8.10.7) (GIT hash: 253547816ee216c53ee7dacc0ad3cac43e863d30)
Tool versions found on the $PATH
cabal:          3.4.0.0
stack:          2.7.3
ghc:            8.10.4
```
Which OS do you use: Ubuntu 20.04
Which lsp-client do you use: VSCode

### Steps to reproduce
- create new project with stack and latest resolver (LTS 18.10 for ghc-8.10.7)
- in this project add `mtl` to dependencies of executable
- build project and open Main.hs
- in end of the file typing `rc = runC`, invoke autocomplete and select `runCont` from `Control.Monad.Cont`. After that line with `import Control.Monad.Cont (runCont)` will be added on start of the file.
- in end of the file typing `c = con`, invoke autocomplete and select `cont` from `Control.Monad.Cont`

### Expected behaviour
hls modify import list to `import Control.Monad.Cont (runCont, cont)`

### Actual behaviour
import list remain `import Control.Monad.Cont (runCont)`

**Comment by Akhristenko** [comment]
After doing a few experiments, I noticed some patterns.
Auto import doesn't work in case, when vscode insert snippets when use autocompletion. i attach screenshot illustrated this case.
If i disable this feature auto import work correct.
![bug](https://user-images.githubusercontent.com/1381278/134548935-12b4e031-0c06-44bb-94bf-b4501d152a71.jpg)

**Comment by michaelpj** [comment]
We don't provide snippets any more, so I think this may well be fixed by accident
