### ISSUE TITLE
Deprecated `ghcide` still selected by cabal to get newer `hiedb`

### ISSUE THREAD

**Issue by hamishmack** [haskell/haskell-language-server#2244]
I think this issue could be resolved by revising `hls-explicit-imports-plugin` dependencies in hackage for versions [1.0.0.3](https://hackage.haskell.org/package/hls-explicit-imports-plugin-1.0.0.3), [1.0.0.4](https://hackage.haskell.org/package/hls-explicit-imports-plugin-1.0.0.4) and [1.0.1.0](https://hackage.haskell.org/package/hls-explicit-imports-plugin-1.0.1.0).  The new dependency could specifically exclude the incompatible version with something like:

```
ghcide (>=1.4.0.1 && <1.4.2.1) || (>1.4.2.1 && <1.5)
```

`ghcide` `1.4.2.1` has already been deprecated in https://hackage.haskell.org/package/ghcide/preferred

```
ghcide has no preferred version ranges.

Explicitly deprecated versions for ghcide include: 1.4.2.1

The version range given to this package, therefore, is <1.4.2.1 || >1.4.2.1
```

Despite this `1.4.2.1` is still selected because the latest version of `ghcide` (`1.4.2.2`) depends on `hiedb (==0.4.0.*)`, and `1.4.2.1` allows `hiedb (==0.4.1.*)`.

The package that fails (at least the first one that fails) is `hls-explicit-imports-plugin` version `1.0.1.0` with:

```
src/Ide/Plugin/ExplicitImports.hs:201:18: error:
    Not in scope: data constructor ‘OldRealSrcSpan’
    Perhaps you meant one of these:
      ‘RealSrcSpan’ (imported from Development.IDE.GHC.Compat),
      ‘SrcLoc.RealSrcSpan’ (imported from SrcLoc),
      variable ‘getRealSrcSpan’ (imported from Development.IDE.GHC.Compat)
    |
201 |             | L (OldRealSrcSpan l) i <- fromMaybe [] mbMinImports
    |                  ^^^^^^^^^^^^^^
```

[`OldRealSrcSpan`](https://hackage.haskell.org/package/ghcide-1.4.2.2/docs/Development-IDE-GHC-Compat.html#v:OldRealSrcSpan) is in `ghcide` `1.4.2.2` and was in `1.4.2.0`, but is not present in `1.4.2.1`.

To reproduce the issue:

```
% cabal update
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org is up to date at index-state 2021-09-27T03:34:40Z
```
```
% cabal unpack haskell-language-server
Unpacking to haskell-language-server-1.4.0.0/
```
```
% cd haskell-language-server-1.4.0.0
```
```
% cabal configure
Resolving dependencies...
Build profile: -w ghc-8.10.7 -O1
In order, the following would be built (use -v for more details):
...
 - hiedb-0.4.1.0 (lib) (requires download & build)
...
 - ghcide-1.4.2.1 (lib) (requires download & build)
...
```
```
% cabal configure --constraint='ghcide==1.4.2.2'
'cabal.project.local' already exists, backing it up to 'cabal.project.local~'.
Resolving dependencies...
Build profile: -w ghc-8.10.7 -O1
In order, the following would be built (use -v for more details):
...
 - hiedb-0.4.0.0 (lib) (requires build)
...
 - ghcide-1.4.2.2 (lib) (requires download & build)
...
```

**Comment by pepeiborra** [comment]
Thanks for reporting this, I'll sort it out later today

**Comment by pepeiborra** [comment]
Should be solved now, I've made ghcide `1.4.2.1` depend on a version of hiedb that doesn't exist, so cabal won't be able to select it anymore

**Comment by jneira** [comment]
> Despite this `1.4.2.1` is still selected because the latest version of `ghcide` (`1.4.2.2`) depends on `hiedb (==0.4.0.*)`, and `1.4.2.1` allows `hiedb (==0.4.1.*)`.

cabal prefers other versions than the deprecated ones but it still uses it see https://github.com/haskell/cabal/issues/3635

> I've made ghcide 1.4.2.1 depend on a version of hiedb that doesn't exist, so cabal won't be able to select it anymore

maybe `buildable: false`, which should be sematically equivalent, would make the intent more clear?
not suggesting made the change now, only for future ones

**Comment by pepeiborra** [comment]
Using `buildable:false` did not occur to me, thanks for the suggestion
