### ISSUE TITLE
Neovim LSP not showing diagnostics after file reload

### ISSUE THREAD

**Issue by sproott** [haskell/haskell-language-server#2247]
I have reported this to nvim-lspconfig at https://github.com/neovim/nvim-lspconfig/issues/1282 but they think it is an hls issue.

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 1.4.0.0 (GHC: 8.10.4) (PATH: /home/sproott/.ghcup/bin/haskell-language-server-wrapper-1.4.0) (GIT hash: 253547816ee216c53ee7dacc0ad3cac43e863d30)
Tool versions found on the $PATH
cabal:		Not found
stack:		2.7.3
ghc:		Not found
```
Which OS do you use:
ArchLinux

Which lsp-client do you use:
Neovim

Describe your project (alternative: link to the project):
Empty stack project with `Setup.hs` removed and this added in the `src/Lib.hs` file:
```haskell
arr :: String
arr = [1, 2, 3]
```

Contents of `hie.yaml`: 
```yaml
cradle:
  stack:
```
but the issue happens even without it

See https://github.com/neovim/nvim-lspconfig/issues/1282 for more info

**Comment by oblitum** [comment]
I replicate this on coc.nvim as well.

**Comment by fabfianda** [comment]
Same here

**Comment by jneira** [comment]
The lsp log is here: https://gist.github.com/sproott/927e2d9e73fdca1988bb0859af8a94b2

The error which makes hls as the main supect is:

```
[ ERROR ] 2021-09-25T19:10:27+0200 ] /usr/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ] "rpc" "haskell-language-server-wrapper" "stderr" "2021-09-25 19:10:27.503531656 [ThreadId 122] INFO hls:\tthread killed\n"
```

**Comment by michaelpj** [comment]
Tentatively closing as old and quiet.
