### ISSUE TITLE
Properly name the binaries before gzipping them

### ISSUE THREAD

**Issue by bubba** [haskell/haskell-language-server#225]
Currently all the binaries are gzipped with the proper name, but when unzipped have the name `hls` or `his-wrapper`. They should be named `haskell-language-server-8.x.y` and `haskell-language-server-wrapper` respectively

**Comment by jneira** [comment]
Mainly unrelated but, would it possible that windows binaries will use zip instead gzip? It is the default format in windows.

**Comment by bubba** [comment]
@jneira I didn't realise that, that's a good catch!

**Comment by dreamsmasher** [comment]
Still have sort of a similar problem, the Linux releases are named haskell-language-server-Linux-8.x.x but the wrapper specifically looks for haskell-language-server-8.x.x. I had to manually rename the executable in order to get it to work.

**Comment by Ailrun** [comment]
I'm wondering why does the workflow script renames executables. Specifically,
https://github.com/haskell/haskell-language-server/blob/f2384e14abb206b133811d2c1d8525536d01a320/.github/workflows/build.yml#L37-L44
It looks like this is why we get the different names instead of the proper names...

**Comment by fendor** [comment]
@Ailrun According to the blog post: https://mpickering.github.io/ide/posts/2020-07-10-ghc-libdir.html
To avoid long path problems on windows.

**Comment by Ailrun** [comment]
Thank you for the link. Windows path limit... that's annoying... Then we should rename it after the build...

**Comment by jneira** [comment]
I am afraid that they need to be renamed before the build or the build itself fails.
The final name could be the long one.

**Comment by bubba** [comment]
@jneira do you know what command can be used on git bash to zip files on Windows? Just calling `zip` fails since it doesn't exist: https://github.com/bubba/haskell-language-server/runs/915797336?check_suite_focus=true#step:8:6

I checked the GitHub Actions virtual environment and 7zip seems to be installed, but I'm not sure what the command/executable is

**Comment by Ailrun** [comment]
@bubba AFAIK, the command for 7zip is 7z.
