### ISSUE TITLE
Restart hls when updating .cabal files

### ISSUE THREAD

**Issue by funrep** [haskell/haskell-language-server#2250]
Hi! I want to be able to restart hls when I update a cabal file so it has up-to-date dependencies information. Is this possible to enable somehow? If not it would be a nice feature.

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 1.3.0.0 (GHC: 8.10.4) (PATH: /nix/store/5k53a741r42pqydb9q7z7gnzqvn6w848-haskell-language-server-wrapper/bin/haskell-language-server-wrapper)
Tool versions found on the $PATH
cabal:          3.4.0.0
stack:          2.7.3
ghc:            8.10.5
```
Which OS do you use:
MacOS 11.6
Which lsp-client do you use:
VS Code
Describe your project (alternative: link to the project):
Repository with several cabal projects in sub-folders.
Launching VS Code from root directory and loading all projects.

### Steps to reproduce
Change a cabal file.

### Expected behaviour
Restart haskell-language-server.

### Actual behaviour
haskell-language-server will not have up-to-date dependencies

**Comment by jneira** [comment]
@funrep hi, thanks for reporting the issue. It was reported in #2150 and originally in #1068. It is a regression, as it used to work (as decribed in #1068). I am gonna close this a duplicate if you dont mind, you can track the resolution in the original one.
