### ISSUE TITLE
Installation on Arch fails: cannot resolve dependency

### ISSUE THREAD

**Issue by ianyepan** [haskell/haskell-language-server#2268]
I'm using Arch Linux, and was trying to install haskell-language-server with the command `sudo pacman -S haskell-language-server`. However, the installation cannot go through because of the following dependency issues:

```
resolving dependencies...
warning: cannot resolve "haskell-ghc-lib-parser", a dependency of "haskell-fourmolu"
warning: cannot resolve "haskell-fourmolu", a dependency of "haskell-hls-fourmolu-plugin"
warning: cannot resolve "haskell-hls-fourmolu-plugin", a dependency of "haskell-language-server"
warning: cannot resolve "haskell-ghc-lib-parser", a dependency of "stylish-haskell"
warning: cannot resolve "stylish-haskell", a dependency of "haskell-hls-stylish-haskell-plugin"
warning: cannot resolve "haskell-hls-stylish-haskell-plugin", a dependency of "haskell-language-server"
:: The following package cannot be upgraded due to unresolvable dependencies:
      haskell-language-server

:: Do you want to skip the above package for this upgrade? [y/N]
```

Pressing either Y or N makes no difference, the installation quits.
How can I resolve this dependency issue? Thanks in advance!

**Comment by felixonmars** [comment]
Some packages were missing from the GHC 9.0 rebuild move. This has been fixed now.

Sorry for the trouble.

**Comment by ianyepan** [comment]
@felixonmars @jneira I just tried installing it again and it's working perfectly -- can't thank you guys enough!

Closing issue.
