### ISSUE TITLE
Incomplete patterns warnings are imprecise

### ISSUE THREAD

**Issue by viluon** [haskell/haskell-language-server#2272]
As is customary, I first searched for similar issues but did not find any. This one lies somewhere between a bug report and a feature request, opinions on whether this is an actual issue may vary. Feel free to redirect me to another project (such as GHC itself) if the culprit resides outside of HLS.

### Your environment
Output of `haskell-language-server-wrapper --probe-tools`:
```sh
haskell-language-server version: 1.4.0.0 (GHC: 8.10.4) (PATH: /home/viluon/.ghcup/bin/haskell-language-server-wrapper-1.4.0) (GIT hash: 253547816ee216c53ee7dacc0ad3cac43e863d30)
Tool versions found on the $PATH
cabal:          3.4.0.0
stack:          2.7.1
ghc:            8.10.3
```
Which OS do you use: Arch Linux
Which lsp-client do you use: VS Code
[Link](https://github.com/grin-compiler/ghc-whole-program-compiler-project/blob/master/external-stg-interpreter/lib/Stg/Interpreter.hs#L203) to the project

### Steps to reproduce
Perform an incomplete pattern match on an ADT with `-Wincomplete-patterns`.

### Expected behaviour
The syntactic construct introducing the pattern match is highlighted with the warning but the arms are not.

### Actual behaviour
The entire pattern-matching expression is highlighted.
![image](https://user-images.githubusercontent.com/7235381/136964409-1a9fa560-a196-4e35-9742-05067f50d794.png)

This is a lot of undesirable noise – the existing match arms aren't the problem here, it is the *absence* of other match arms that should be highlighted. Since it's difficult to highlight something that doesn't exist, I think the scope of the warning should be restricted to just the `case o of` of this particular example. The overly broad warning shadows other warnings local to the individual match arms, hiding actual issues (in this snippet, the `case` is in fact exhaustive, although GHC has no way of knowing that).

**Comment by michaelpj** [comment]
I think this likely comes from GHC, so making an upstream issue would be good! 

We could fiddle with the source span on our side... but I think that will land us with a bunch of awkward fragile code to maintain, so I'm not sure it's worth it.

**Comment by michaelpj** [comment]
I'm going to close this since I think it's an upstream issue.
