### ISSUE TITLE
Time to cut a new release: November 2021/1.5.0

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#2281]
* It would contain the recent great performance improvements by @pepeiborra
* Also to enable fourmolu for ghc-9.0.1 thanks to @georgefst 
* It would be great to have the rename plugin even disabled at runtime by default (#2193)
* Anyone would like to drive it this time :slightly_smiling_face: ? this one does not seem to be too cumbersome

### github release

* [X] generate the list of pull requests finished since the last release using the [haskell script](https://github.com/haskell/haskell-language-server/blob/master/GenChangelogs.hs) in the project root.
  Nix users should run command `gen-hls-changelogs` (a wrapper of the script) in nix-shell instead.
* [X] add that list to the actual [Changelog](https://github.com/haskell/haskell-language-server/blob/master/ChangeLog.md) with a description of the release.
* [X] bump up versions of changed packages. All are optional but [haskell-language-server itself](https://github.com/haskell/haskell-language-server/blob/master/haskell-language-server.cabal).
* [X] create the tag and make an initial prerelease to trigger the ci workflow (see details below)
* [ ] contact ghcup team (#haskell-ghcup irc channel or via its [repo](https://gitlab.haskell.org/haskell/ghcup-hs/-/issues)) to try to sync our release and its inclusion in ghcup
* [X] check uploaded binaries  and the release description (usually the changelog entry) and uncheck the prerelease box
* [X] make public the release in the usual social channels: irc, twitter, reddit, discord, discourse, etc (not required but useful to spread the word :slightly_smiling_face:)
  * [X] irc
  * [X] twitter
  * [X] discord
  * [X] discourse
  * [ ] reddit

### hackage release

* [X] bump up package versions following the [pvp specification](https://pvp.haskell.org/) if they are not already updated
* [X] create ${version}-hackage branch to trigger the hackage github workflow which will upload all changed packages to hackage as candidates
* [X] check manually candidates in hackage
* [X] publish them definitely

//cc @Ailrun @berberman @michaelpj @konn

**Comment by Ailrun** [comment]
I'm unfortunately insanely occupied with my POPL preparation :(

**Comment by jneira** [comment]
Well it is time to start the engine:
* I am checking hackage to see what bumps would be needed here: https://github.com/jneira/haskell-language-server/actions/runs/1447761160

@pepeiborra what version bump do you think is needed for ghcide? There is ton of changes (diff [here](https://github.com/jneira/haskell-language-server/runs/4175194641?check_suite_focus=true)) and i guess some of them would need a major version bump (so maybe it is time to set it to `1.5.0.0`)

**Comment by pepeiborra** [comment]
Yes, it's time for 1.5.0.0. 
I'll try to land #2323 this weekend. No need to wait any further

**Comment by jneira** [comment]
I am afraid that th-extras version with 9.0.1 has not been released so ghcide can't be built:

```
src/Language/Haskell/TH/Extras.hs:42:17: error: 

Error: • Expecting one more argument to ‘TyVarBndr’ 

Expected a type, but ‘TyVarBndr’ has kind ‘* -> *’ 

• In the type signature: nameOfBinder :: TyVarBndr -> Name 

| 

42 | nameOfBinder :: TyVarBndr -> Name 

| ^^^^^^^
```

I ve emailed maintainers again asking for the release, but if they don't respond soon we will have to ship without 9.0.1 support

**Comment by jneira** [comment]
After updating hackage index and invalidate the cache, the build is getting a compile error on ghc-lib-parser-8.10.7.20210828
* run workflow: https://github.com/jneira/haskell-language-server/runs/4187119335?check_suite_focus=true
* issue in ghc-lib repo: https://github.com/digital-asset/ghc-lib/issues/332

**Comment by jneira** [comment]
Ok, so ghc-lib is not supposed to be buildable with newer ghcs, in the general case:

> > I assume ghc-lib-parse >= 8.10.5.20210606 is buildable with ghc-9.0.1 as their base bounds allow it.

> it's not. generally, we only support building "forward" (or rather, this is a ghc restriction).

I started a build forcing the formatters using ghc-lib-parse-9.0 and the build has been succesful: https://github.com/jneira/haskell-language-server/runs/4210568210?check_suite_focus=true
However this is another blocker to release hls in hackage for ghc-9.0.1. :worried:

**Comment by jneira** [comment]
* I've cut the tag and publish the prerelease: https://github.com/haskell/haskell-language-server/releases/tag/1.5.0
  * It has triggered the release build: https://github.com/haskell/haskell-language-server/actions/runs/1475174019
* I've push 1.5.0 to gitlab and it triggered the release build there: https://gitlab.haskell.org/haskell/haskell-language-server/-/pipelines/44095 (//cc @hasufell)
* Will push the hackage branch once the github release is done
  * The run checking hackage with 1.5.0 is https://github.com/haskell/haskell-language-server/actions/runs/1475182207

**Comment by jneira** [comment]
* Github release done
* There had been some build errors in the gitlab pipeline
* Pushed 1.5.0-hackage to start the hackage release: https://github.com/haskell/haskell-language-server/actions/runs/1475412256

**Comment by jneira** [comment]
The package candidates has been published, only left make them definitive:

- [ ] hls-graph-1.5.1.0
- [ ] hls-plugin-api-1.2.0.2
- [ ] ghcide-1.5.0 
- [ ] hls-test-utils-1.1.0.1 
- [ ] hls-eval-plugin-1.2.0.1
- [ ] hls-stylish-haskell-plugin-1.0.0.3
- [ ] hls-module-name-plugin-1.0.0.2
- [ ] hls-pragmas-plugin-1.0.1.1
- [ ] hls-haddock-comments-plugin-1.0.0.4
- [ ] hls-retrie-plugin-1.0.1.3
- [ ] hls-splice-plugin-1.0.0.5
- [ ] hls-tactics-plugin-1.5.0.0
- [ ] hls-floskell-plugin-1.0.0.2
- [ ] hls-explicit-imports-plugin-1.0.1.1
- [ ] hls-hlint-plugin-1.0.2.0
- [ ] hls-refine-imports-plugin-1.0.0.2
- [ ] hls-class-plugin-1.0.1.1
- [ ] hls-call-hierarchy-plugin-1.0.1.1
- [ ] hls-ormolu-plugin-1.0.1.1
- [ ] hls-brittany-plugin-1.0.1.1
- [ ] haskell-language-server-1.5.0.0

**Comment by jneira** [comment]
All packages has been released to hackage

**Comment by ocharles** [comment]
Amazing work as always @jneira :heart_eyes: !!!

**Comment by jneira** [comment]
Possible improvements: 
* check the gitlab build which generates artifacts for ghcup is working *before* making the definitive release, like we are doing for hackage
  * they are failing and maybe will be need source changes 
* maybe a liitle bit paranoic but check the build script which generates artifacts for the github release *before* making the definitive release

**Comment by jneira** [comment]
I am gonna reopen the issue until ghcup are updated to include the release

**Comment by pepeiborra** [comment]
Maybe we could also add a step to the release process to do manual testing using the ghcup codebase, or some other non-trivial project (ghc itself?) to avoid last minute bugs like #2365

**Comment by jneira** [comment]
Yeah, maybe hls itself could be a good candidate, ghc is too big and hard to setup if you are not already working on it and ghcup too small (although coincidentally has hs-boot files).
Ideally it should automatized in some way, maybe calling hls in trace mode and examining the logs to see al files are correctly loaded?

**Comment by jneira** [comment]
The release has been included in ghcup: https://github.com/haskell/ghcup-metadata/blob/master/ghcup-0.0.6.yaml
thanks to @hasufell

**Comment by pepeiborra** [comment]
Looks like you missed the `hls-rename-plugin` here - maybe there's a list that needs to be updated somewhere?

**Comment by jneira** [comment]
The plugin is disabled by default at build time cause it does not have support for multicomponent projects afair: https://github.com/haskell/haskell-language-server/issues/2193

We were waiting for a way of disabling by default at runtime to include it at build time: https://github.com/haskell/haskell-language-server/issues/2193#issuecomment-946269703

But we could upload it anyways for sure, hls will not include it if you dont set the appropiate flag:

https://github.com/haskell/haskell-language-server/blob/2e61b7c0ba64cded22cf0fb80b089eaf328528e6/haskell-language-server.cabal#L124-L127
