### ISSUE TITLE
Cannot apply hlint hints when a trailing comment is on the same line.

### ISSUE THREAD

**Issue by shapr** [haskell/haskell-language-server#2290]
### Your environment
haskell-language-server 1.4
Which OS do you use: NixOS
Which lsp-client do you use: haskell-lsp in emacs
Describe your project (alternative: link to the project): https://github.com/shapr/hlsexamples/blob/main/src/Examples.hs#L14

### Steps to reproduce
Insert the line `biggest items = foldr1 max items -- the line above will show two hlint hints, "eta reduce" and "use maximum"
` into a file, and attempt to apply any of the hlint hints.
If you move the comment to a different line, the hlint hints apply with no problems.
### Expected behaviour
The hints should be applied.
### Actual behaviour
The hints are not applied.

**Comment by jneira** [comment]
Hi, thanks for reporting the issue i've just tried to reproduce and i was not able to do it with several ghc versions (9.0.1, 8.10.7, 8.8.4). I am gonna add a test anyways to check it in ci

**Comment by jneira** [comment]
@shapr I ve added a repro test here: https://github.com/haskell/haskell-language-server/blob/9818ab2d5271c6b534d36b0a5968b2f85c4d611c/plugins/hls-hlint-plugin/test/testdata/TwoHintsAndComment.hs

and it was succesfull for all CI configurations, let me know how could be changed to reproduce it
