### ISSUE TITLE
feature request: provide sortText with completionItems

### ISSUE THREAD

**Issue by mjlbach** [haskell/haskell-language-server#2291]
We received this issue on the neovim client: https://github.com/neovim/neovim/issues/15414

One thing that was reported by @tomsmeding (regarding HLS) is that the results are pre-sorted by the server to include 

* case-insensitive matching
* typo-fixing
* intelligent result ordering so that most likely matches come first

According to the specification, if sortText is not supplied, the client should sort on the label. See [here](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#completionItem)

>
	 * A string that should be used when comparing this item
	 * with other items. When `falsy` the label is used
	 * as the sort text for this item.
	sortText?: string;

If the results should not be sorted, sortText should be supplied to indicate the results should not be sorted as such, otherwise according to the spec we should sort on the label as we currently do which perturbs the HLS returned ordering.

I can look into providing a PR if welcome :) I don't any experience with the HLS codebase though

**Comment by jneira** [comment]
Thanks for report it here and the pr offer, sounds good to me. Wonder what is the behaviour of other editors like vscode o emacs, do not they follow the spec?

>I don't any experience with the HLS codebase though

Dont know much about that part of the codebase but the main entry point would be https://github.com/haskell/haskell-language-server/blob/master/ghcide/src/Development/IDE/Plugin/Completions.hs

//cc @michaelpj
