### ISSUE TITLE
HLS failing with `Assertion freesize < size failed` on a fairly minimal example

### ISSUE THREAD

**Issue by googleson78** [haskell/haskell-language-server#2328]
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
> haskell-language-server-9.0.1 --probe-tools
haskell-language-server version: 1.4.0.0 (GHC: 9.0.1) (PATH: /home/googleson78/.ghcup/bin/haskell-language-server-9.0.1~1.4.0) (GIT hash: 253547816ee216c53ee7dacc0ad3cac43e863d30)
Tool versions found on the $PATH
cabal:          3.6.0.0
stack:          2.7.3
ghc:            8.8.4
```

Which OS do you use:
Debian

Which lsp-client do you use:
LanguageClient-neovim

Describe your project (alternative: link to the project):
Here's a link to the reproducer - https://github.com/googleson78/hls-repro-0

Contents of `hie.yaml`:
Not using a custom `hie.yaml`

### Steps to reproduce
Run `haskell-language-server-wrapper` (or `-9.0.1`) in the given reproducer

Note that removing the `directory` dependency stops this from happening.

### Expected behaviour
No crash

### Actual behaviour
```
Completed (1 file worked, 0 files failed)
haskell-language-server-9.0.1: allocatestack.c:384: advise_stack_range: Assertion `freesize < size' failed.
[1]    144526 abort      haskell-language-server-9.0.1
```

### Include debug information
It's included in the repro example repo.

**Comment by jneira** [comment]
there are other issues reporting this error, all related with th or ghc compiler plugins and small reproducer would help for sure, thanks!

**Comment by nrnrnr** [comment]
Also reporting this error.

```
nr@homedog ~/a/g/compiler> haskell-language-server-wrapper --probe-tools
haskell-language-server version: 1.6.1.0 (GHC: 8.10.7) (PATH: /home/nr/.ghcup/bin/haskell-language-server-wrapper-1.6.1.0) (GIT hash: f4022c5bb8530cd306c53b941878244bf27a5d41)
Tool versions found on the $PATH
cabal:          3.6.2.0
stack:          2.5.1
ghc:            9.2.1
```

The crash occurs when working in the GHC source tree.  Since you're looking for a small reproducer, this is not it.  But I wanted to comment so I can watch this issue.

**Comment by michaelpj** [comment]
Has anyone seen this recently?

**Comment by michaelpj** [comment]
Tentatively closing since we haven't heard anything recently.
