### ISSUE TITLE
No pre-built binaries for GHC 8.8.3 for Windows

### ISSUE THREAD

**Issue by scottbass47** [haskell/haskell-language-server#234]
Currently Stack uses resolver `lts-16.6` which uses GHC version `8.8.3`. However, the pre-built binaries for windows only has a language server binary for GHC `8.8.4`. Mac and linux both have binaries for `8.8.3`, is the windows binary just missing from the listing or has it not been built yet?

**Comment by Ailrun** [comment]
Currently, the binary build process of 8.8.3 fails on Windows because of Segfault.
See: https://github.com/haskell/haskell-language-server/blob/12c0e4423263140e3d16e76681927ec69fe4929f/.github/workflows/build.yml#L18

**Comment by jneira** [comment]
I am afraid that he error is reproduced with ghc.8.8.4 as well. The error is not deterministic and we were able to build with ghc-8.8.4.
I'll give a try to ghc-8.8.3 to see if we have luck. 🤞

**Comment by scottbass47** [comment]
Oh that explains a lot. I was trying to build 8.8.3 myself and it kept failing on floskell which is why I wanted to download a pre-built binary. Welp, I guess it's 8.8.4 for me!

**Comment by bubba** [comment]
Yeah, it took 4 tries to get the windows 8.8.4 binary to build successfully on GitHub Actions, there was no secret unfortunately. We could try to produce 8.8.3 binaries as well maybe, retrying every time it fails? It will be a pain for us but could save others a lot of suffering

**Comment by jneira** [comment]
There is a workaround to install hls with ghc-8.8.3, described [here](https://github.com/haskell/haskell-language-server/issues/86#issuecomment-663905148).
However i am not sure if it worths to make the binary that way. stack will use ghc-8.8.4 sooner or later.

**Comment by bubba** [comment]
I think we might need to give up on the 8.8.3/8.8.4 Windows builds. It's been failing 4 out of 5 times anecdotally on the GitHub Actions jobs now. Hopefully we will eventually get a 8.8.x release working, but until now the workaround is to (attempt to) install it form source
