### ISSUE TITLE
Bumping retrie version

### ISSUE THREAD

**Issue by Tarmean** [haskell/haskell-language-server#2347]
Retrie currently doesn't work on windows, which also breaks the renaming support of haskell-language-server https://github.com/haskell/haskell-language-server/issues/2051

A pull request to fix this was merged a while ago https://github.com/facebookincubator/retrie/pull/31 , and this fixed the issue for me when pinning the commit in extra-deps/source-repository-package. However as far as I can see the commit isn't part of any retrie release. 

I'd quite like to get windows support for retrie into haskell-language-server. The easy answer would be to pin the commit, but doing so in every build variant seems a bit roundabout. Is there a more proper way to go about this?

**Comment by jneira** [comment]
Finally good news! thanks for noting it. I guess the more straightforward solution would be get the fix released, maybe @pepeiborra could help us in doing so.

In the meanwhile add the source-repository-package could help as the plugin is broken anways we would get a github release with it fixed

**Comment by jneira** [comment]
However i am bit perplexed with the relation between hls-rename-plugin and retrie. I would swear renaming has been working for me in windows with the actual retrie version, and i see the h[ls-rename-plugin tests are being executed in windows and the test suite pass](https://github.com/haskell/haskell-language-server/runs/4187506214?check_suite_focus=true) :thinking:

**Comment by pepeiborra** [comment]
I can push out a retrie minor release this weekend or next week if that helps.

**Comment by jneira** [comment]
> 
> 
> I can push out a retrie minor release this weekend or next week if that helps.

please, that way we will not have to do temporary config changes

**Comment by pepeiborra** [comment]
Since this will be a minor version bump in retrie, it shouldn't bump the HLS 1.5 release

**Comment by Tarmean** [comment]
> ~However i am bit perplexed with the relation between hls-rename-plugin and retrie.

Apparently the prototype used Retrie but the current version does it directly with SYB and exactprint, sorry for the confusion
https://gist.github.com/OliverMadine/96927f88b6e5e7890e5179559089166c

A minor retrie release seems ideal, thank you for working in this so quickly!

**Comment by pepeiborra** [comment]
retrie-1.1.0.0 is up in Hackage (it was a major release according to @kowainik policeman)

**Comment by jneira** [comment]
thsnks @pepeiborra, @Tarmean would you have any chance to bump the version used here? will do myself if you have not

**Comment by Tarmean** [comment]
Does the CI run the tests for all build versions? I'm mildly worried because in most builds still use  retrie-0.1.1.1. Since there aren't any transitive dependencies on retrie I don't see how the change could break anything, though.

**Comment by jneira** [comment]
we have the hackage index fixed at some point of time in cabal.project, and the retrie version fixed in all stack.yamls so some changes are needed to make the builds pick up the new version

**Comment by Tarmean** [comment]
Stack and cabal seem to build fine, but the nix expression in the CI build fails https://github.com/Tarmean/haskell-language-server/runs/4289543574?check_suite_focus=true

 I definitely do not know enough nix to figure out how all that fits together. After staring at the nix code for half an hour my guess is that the pinned hackage version is too old? https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/data/misc/hackage/pin.json

**Comment by jneira** [comment]
Maybe our hls nix hacker could help with that: @berberman

**Comment by jneira** [comment]
@Tarmean hi! could you open a pr here?, i think we could fix the nix issue with some help from maintainers using nix

**Comment by jneira** [comment]
ok retrie-1.2.0.0 only is available for ghc>=9.2 and there is no upper bound in any .cabal file so hls for ghc-9.2.0 will pick it automatically
To have the fix for ghc >= 8.8 and <= 9.0.1 we would need a retrie-1.1.0.1 with the patch included and I am not sure if retrie maintainers do backports.

/cc @pepeiborra @Tarmean

**Comment by pepeiborra** [comment]
What patch are you referring to @jneira? I thought that retrie 1.1.0.0 is good for Windows

**Comment by jneira** [comment]
ouch sorry, 1.1.0.0 already has the patch, yeah
so it should being used for cabal builds with the > 8.6.5 and it will be used for stack with my recent pr #2513
unfortunately we cant enforce the patched version while we support 8.6.5

thanks and sorry for the confusion, will make that #2513 close this
