### ISSUE TITLE
Extension pragma inserted below ghc options pragma (or shebang) no matter where it is in file

### ISSUE THREAD

**Issue by eddiemundo** [haskell/haskell-language-server#2364]
### Steps to reproduce
![extension-pragma-in-wrong-place](https://user-images.githubusercontent.com/929157/142272585-79a65424-dccf-4a90-9bf3-b5e103e4e73f.gif)
1. Have a ghc options pragma (or shebang) in the middle of the file somewhere. Both cases seem to compile fine...
2. Disable an extension that the file needs.
3. Use a code action to insert the extension back in.

### Expected behaviour
The extension should be put after the last pragma at the top of the file somewhere before the module declaration.

### Actual behaviour
The extension is inserted after the ghc options pragma (or shebang) in the middle of the file.

Working on a fix for this so that my fix for something else can work.

**Comment by jneira** [comment]
Many thanks for the report and to work in fixing it.
Position of pragmas has been, somewhat surprisingly, a tricky thing, there were several prs correcting different bugs (sometimes introduced by previous prs). 

So i think add a regression test will be a must: there are already lot of them 😄 

https://github.com/haskell/haskell-language-server/blob/07042d404340017b473833c1fb470e3c25fdf6d2/plugins/hls-pragmas-plugin/test/Main.hs#L29-L55

prs: #2043, #2078 amongs other

**Comment by eddiemundo** [comment]
Finished writing a fix for this but there is a test that fails that I'm not sure is correct.
```
Test output was different from 'test/testdata/AddPragmaAfterShebangPrecededByLangAndOptsGhc.expected.hs'. Output of ["git","-c","core.fileMode=false","diff","--no-index","--text","--exit-code","test/testdata/AddPragmaAfterShebangPrecededByLangAndOptsGhc.expected.hs","/tmp/AddPragmaAfterShebangPrecededByLangAndOptsGhc.expected932384-1.actual"]:
      diff --git a/test/testdata/AddPragmaAfterShebangPrecededByLangAndOptsGhc.expected.hs b/tmp/AddPragmaAfterShebangPrecededByLangAndOptsGhc.expected932384-1.actual
      index b29fc22f..ba4ecd18 100644
      --- a/test/testdata/AddPragmaAfterShebangPrecededByLangAndOptsGhc.expected.hs
      +++ b/tmp/AddPragmaAfterShebangPrecededByLangAndOptsGhc.expected932384-1.actual
      @@ -1,8 +1,8 @@
       {-# LANGUAGE OverloadedStrings #-}
       {-# OPTIONS_GHC -Wall #-}
      +{-# LANGUAGE TupleSections #-}
       #! /usr/bin/env nix-shell
       #! nix-shell --pure -i runghc -p "haskellPackages.ghcWithPackages (hp: with hp; [ turtle ])"
      -{-# LANGUAGE TupleSections #-}
       
       data Something = Something {
           foo :: !String,
```
In this one it expects the pragma after the shebang lines but the shebang lines are after existing pragmas which makes them screwy to begin with since shebangs should be at the top of the file. So is this behaviour necessary? It's easy to change my implementation to match, but if the behaviour is not necessary it's better to delete the test.

**Comment by nini-faroux** [comment]
hi @eddiemundo 

Thanks for the fix, I didn't think of the case of pragmas in the middle of the file. 

With the tests I was just trying different combinations to be sure it was added under the last file header pragma, but if your output makes sense and passes your new tests as well I'm sure it's ok to ignore this one.
