### ISSUE TITLE
hls-call-hierarchy-plugin-1.0.1.1: Build failure with `ghc-8.10.6`

### ISSUE THREAD

**Issue by hololeap** [haskell/haskell-language-server#2369]
The latest version of `hls-call-hierarchy-plugin` calls [`occNameSpace`](https://hackage.haskell.org/package/ghc-9.2.1/docs/GHC-Types-Name-Occurrence.html#v:occNameSpace) which does not exist in earlier versions of `ghc`.

```
Building library for hls-call-hierarchy-plugin-1.0.1.1..
[1 of 4] Compiling Ide.Plugin.CallHierarchy.Types ( src/Ide/Plugin/CallHierarchy/Types.hs, dist/build/Ide/Plugin/CallHierarchy/Types.o, dist/build/Ide/Plugin/CallHierarchy/Types.dyn_o )
[2 of 4] Compiling Ide.Plugin.CallHierarchy.Query ( src/Ide/Plugin/CallHierarchy/Query.hs, dist/build/Ide/Plugin/CallHierarchy/Query.o, dist/build/Ide/Plugin/CallHierarchy/Query.dyn_o )

src/Ide/Plugin/CallHierarchy/Query.hs:78:23: error:
    Variable not in scope:
      occNameSpace :: OccName.OccName -> OccName.NameSpace
   |
78 |     let o = toNsChar (occNameSpace symName) : occNameString symName
   |                       ^^^^^^^^^^^^

src/Ide/Plugin/CallHierarchy/Query.hs:78:47: error:
    Variable not in scope: occNameString :: OccName.OccName -> [Char]
   |
78 |     let o = toNsChar (occNameSpace symName) : occNameString symName
   |                                               ^^^^^^^^^^^^^

src/Ide/Plugin/CallHierarchy/Query.hs:80:26: error:
    • Variable not in scope: moduleUnit :: Module -> Unit
    • Perhaps you meant one of these:
        ‘moduleUnitId’ (imported from Development.IDE.GHC.Compat),
        ‘moduleInfo’ (imported from Development.IDE.GHC.Compat)
   |
80 |         u = unitString $ moduleUnit symModule
   |                          ^^^^^^^^^^
```

(Building with `ghc-8.10-6`)

This affects `hls-call-hierarchy-plugin >=1.0.1.1`, but not earlier versions.

**Comment by jneira** [comment]
Thanks for opening the issue. It is a little bit weird, ghcide is using the same definition (at least the name is the same) and it can be compiled with any supported ghc version:

https://github.com/haskell/haskell-language-server/blob/ec53fcb7b54434d62901a73bbf3e3085a579c487/ghcide/src/Development/IDE/Spans/AtPoint.hs#L128

**Comment by jneira** [comment]
Anf the hackage build was succesful with ghc-8.10.2: https://hackage.haskell.org/package/hls-call-hierarchy-plugin-1.0.1.1/reports/1 :thinking:

**Comment by hololeap** [comment]
Sorry about the "reference" spam. I removed the references to this bug from my commits, so it shouldn't happen again.

**Comment by hololeap** [comment]
It looks like it's all been cleared up with the latest versions of all the packages. I'm not sure if my system was to blame in part, but thanks for all the hard work, everyone!

**Comment by jneira** [comment]
Dont worry at all for the commits, and many thanks for packaging hls for gentoo

**Comment by jneira** [comment]
@hololeap if you think it could be useful, feel free to add gentoo in the installation guide, like Fedora dis: https://github.com/haskell/haskell-language-server/blob/master/docs/installation.md#fedora
