### ISSUE TITLE
hls-pragmas-plugin: Tests time out

### ISSUE THREAD

**Issue by maralorn** [haskell/haskell-language-server#2375]
Building hls-pragmas-plugin 1.0.1.11 for hls 1.5.0.0 has a lot of timeouts in the tests when trying to build in nixpkgs. This can very well be an environment problem (e.g., a missing tool or something), but I am not sure what it could be.

See the log at: https://hydra.nixos.org/build/158849688/nixlog/6

**Comment by eddiemundo** [comment]
I looked at this a little and if all of the completion and test logic is commented out except for the `waitForDiagnostics` line which is an `lsp-test` function, then the completion test(s) will timeout waiting for diagnostics.

I'm using nixos and used the flake.

**Comment by eddiemundo** [comment]
This no longer happens for some reason... probably can close.

**Comment by maralorn** [comment]
That’s okay with me. I might try again at some point and will just open a new issue if I encounter this problem again.

**Comment by jneira** [comment]
@eddiemundo i think you should be able to close ityourself, ping me it it is not the case
