### ISSUE TITLE
Display a warning when using Template Haskell and static binaries

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#2391]
We know that HLS is likely to crash in this situation, specially in Mac OS, so perhaps HLS should use a `WindowShowMessage` LSP notification to warn the user and link to the documentation of the recommended solution, which is to build locally with dynamic linking.

**Comment by jneira** [comment]
The warning is shown if you build hls with `--enable-executable-dynamic`, but i thought that way th would also works.
With that flag the executable uses dybnamic linking for system libs but no for haskell dependencies (like `--ghc-options="dynamic"`)
