### ISSUE TITLE
Please add upper bound `ghcide <1.5.0.1` to hls-eval-plugin 1.2.0.1 on hackage

### ISSUE THREAD

**Issue by hamishmack** [haskell/haskell-language-server#2396]
The latest ghcide in hackage (1.5.0.1) includes this change (when compared to ghcide 1.5.0):
```
 data GhcSessionDepsConfig = GhcSessionDepsConfig
     { checkForImportCycles :: Bool
-    , forceLinkables       :: Bool
     , fullModSummary       :: Bool
     }
 instance Default GhcSessionDepsConfig where
   def = GhcSessionDepsConfig
     { checkForImportCycles = True
-    , forceLinkables = False
     , fullModSummary = False
     }
```

It leads to this error when building hls-eval-plugin 1.2.0.1:
```
[8 of 9] Compiling Ide.Plugin.Eval.CodeLens ( src/Ide/Plugin/Eval/CodeLens.hs, dist/build/Ide/Plugin/Eval/CodeLens.o, dist/build/Ide/Plugin/Eval/CodeLens.dyn_o )

src/Ide/Plugin/Eval/CodeLens.hs:543:15: error:
    ‘forceLinkables’ is not a (visible) constructor field name
    |
543 |             { forceLinkables = True
    |               ^^^^^^^^^^^^^^
```

**Comment by jneira** [comment]
So the version bump should have been a breaking one (1.6.0) following pvp.
Will revise the plugin bounds in hackage and change it in the repo

**Comment by jneira** [comment]
Revised in hackage: https://hackage.haskell.org/package/hls-eval-plugin-1.2.0.1/revisions/

**Comment by jneira** [comment]
Change in the repo done with 484d101f (#2393), thanks for reporting the issue!

**Comment by pepeiborra** [comment]
My bad

**Comment by jneira** [comment]
Dont worry, we should add policeman to the hackage workflow (and remember to use the workflow in check mode even for manual uploads)
