### ISSUE TITLE
Import list whitespace is inconsistent

### ISSUE THREAD

**Issue by JakobBruenker** [haskell/haskell-language-server#2399]
### Your environment
Output of `haskell-language-server --probe-tools``:

```sh
haskell-language-server version: 1.5.0.0 (GHC: 9.0.1) (PATH: C:\Users\user\AppData\Roaming\C
ode\User\globalStorage\haskell.haskell\haskell-language-server-1.5.0-win32-9.0.1.exe) (GIT h
ash: 311107eabbf0537e0c192b2c377d282505b4eff1)
Tool versions found on the $PATH
cabal:          3.4.0.0
stack:          Not found
ghc:            9.0.1
```
Which OS do you use: Windows
Which lsp-client do you use: VS Code

### Steps to reproduce
Open a new Haskell file. Write

```haskell
import Control.Monad

f = guard catMaybes
```

where auto-completion should be used to complete `catMaybes`.

HLS will insert a import statement at the top saying `import Data.Maybe (catMaybes)`.

In VS Code, you can click above `import Control.Monad` to add an import list. This will result in `import Control.Monad ( guard )`.

### Expected behaviour
The spaces inside the parentheses in the import lists should be consistent.

### Actual behaviour
The two methods to automatically obtain an import list differ in whether or not there are spaces inside the parentheses.

**Comment by jneira** [comment]
Thanks for reporting the issue. I hope fix that will not be too much difficult. I would change the explicit import plugin to not add the extra spaces. The code to create the code edit is here:

https://github.com/haskell/haskell-language-server/blob/4b7d13977361c515dad8b2e83f50503ea779150d/plugins/hls-explicit-imports-plugin/src/Ide/Plugin/ExplicitImports.hs#L243-L256

What is the behaviour if the import list has more than one definition? does it also add extra parenthesis?

**Comment by JakobBruenker** [comment]
The extra space is added for multiple definitions as well, e.g.
```haskell
import Control.Monad ( guard, forM_, forM )
```
This is also the case if there are too many definitions for one line:
```haskell
import Control.Monad
    ( guard,
      Monad(return),
      Functor(fmap),
      sequence,
      sequence_,
      forM_,
      void,
      forM )
```

**Comment by pepeiborra** [comment]
This is one of many whitespace inconsistencies amongst the many plugins that we use. Trying to address them all is an enormous task. 

I suspect it would be more productive for you to enable "Format on save" and rely on the automated formatter to sort out whitespace for you.

**Comment by jneira** [comment]
> This is one of many whitespace inconsistencies amongst the many plugins that we use. Trying to address them all is an enormous task.

still i think fixing inconsistences one by one could be a way to get started in the codebase

**Comment by cardenaso11** [comment]
Hi! Newcomer to the hls codebase, and I thought this'd be a good place to get started, mind if I take on this ticket?

**Comment by jneira** [comment]
sure and welcome, feel free to open a draft pr at any time or to ask here or in any of the chat rooms

**Comment by pepeiborra** [comment]
As a heads up, the import lists generated by the Imports plugin (which I maintain) are pretty-printed by GHC, and I'm afraid it will be very hard for me to accept any changes that replace the GHC pretty-printer with a custom printer.

**Comment by JakobBruenker** [comment]
Making both ways to add an import list use the GHC pretty-printer seems like it could be a good way to resolve the issue

**Comment by fendor** [comment]
Closing, @bendo said it is not reproducible any more with ghc 9.2.4.

Feel free to reopen if we missed something
