### ISSUE TITLE
Use `undefined` as placeholder instead of `_`

### ISSUE THREAD

**Issue by afnanenayet** [haskell/haskell-language-server#2416]
**Is your feature request related to a problem? Please describe.**

When I get a function stub from HLS it's usually of the form

```haskell
someFunc = _
```

which is usually incompatible with the given type arguments, and shows up as an error. I think it would be a bit more ergonomic
to have

```haskell
someFunc = undefined
```

which in my opinion is clearer in the codebase (I'd rather just grep for `undefined` to see if I forgot to implement anything), and also passes the type checker, which means there's less noise.

**Describe the solution you'd like**

Use `undefined` as a placeholder instead of `_` when filling in methods.

**Describe alternatives you've considered**

I don't think there are any good alternatives aside from the proposed solution and the current behavior.

**Additional context**

N/A.

**Comment by afnanenayet** [comment]
Also would be happy to implement this myself if people think it's worth changing the existing behavior.

**Comment by Ailrun** [comment]
Could you elaborate on what you meant by "usually incompatible with the given type arguments"? Holes (`_`) are meant to raise errors with expected types for those, and it is the intended behaviour for holes.

**Comment by pepeiborra** [comment]
Using a hole is a deliberate design decision, and I would not support a change to use `undefined` unless you can convince us in this thread.

**Comment by afnanenayet** [comment]
Actually in retrospect I think there's a stronger argument for holes, closing.
