### ISSUE TITLE
hlint fixity issues

### ISSUE THREAD

**Issue by ivan-m** [haskell/haskell-language-server#2418]
### Your environment

Which OS do you use: Red Hat 7 VM
Which lsp-client do you use: Emacs
Describe your project (alternative: link to the project): Shake + Stack; internal project so can't be shared

### Steps to reproduce

```yaml
# .hlint.yaml
- fixity: "infixl 3 <!>"
```

Haskell source file:
```haskell
-- https://hackage.haskell.org/package/semigroupoids-5.3.6/docs/Data-Functor-Alt.html
import Data.Functor.Alt ((<!>))

-- Simplified function matching behaviour of actual functions
foo :: Char -> Maybe Int -> Maybe String
foo c mInt =
      show <$> mInt
  <!> pure <$> Just c

-- Note the relative fixities here: this is equivalent to: (...) <!> (...)
```

Load this in $EDITOR, list all suggestions from hls.

### Expected behaviour
No warnings related to `foo`.

### Actual behaviour

```
Functor law
 Found:
   show <$> mInt <!> pure <$> Just c
 Why not:
   show . (mInt <!> pure) <$> Just c
```

### Include debug information

Running hlint explicitly does not have any problems.

The `.hlint.yaml` file is indeed being picked up by the hls hlint plugin as other suggestions are appearing based upon the configuration (custom linting rules, etc.).  As such, this might be due to ndmitchell/hlint#1232

`haskell-language-server-wrapper --debug .` output only partially shown as it's quite large:
```
haskell-language-server version: 1.5.1.0 (GHC: 8.10.7) (PATH: /home/<elided>/haskell-language-server) (GIT hash: 1d82c8ec31628fc84f0ffe55ff572602212e07a2)
 ghcide setup tester in /home/<elided>
Report bugs at https://github.com/haskell/haskell-language-server/issues

Step 1/4: Finding files to test in /home/<elided>
Found 16145 files
```

Logs from LSP client:

```
Command "~/<elided>/haskell-language-server --lsp" is present on the path.
Command "~/<elided>/haskell-language-server --lsp" is present on the path.
Found the following clients for /path/to/Module.hs: (server-id lsp-haskell, priority 0)
The following clients were selected based on priority: (server-id lsp-haskell, priority 0)
```

**Comment by jneira** [comment]
Thanks for the bug report, i wonder what happens if you set the rule via file pragma f.e.

**Comment by ivan-m** [comment]
AFAICT, the fixity information [can only be specified](https://github.com/ndmitchell/hlint/blob/master/README.md#why-doesnt-hlint-know-the-fixity-for-my-custom--operator) in `.hlint.yaml`.

I did try adding `{-# ANN module ("HLint: fixity: infixl 3 <!>" :: String) #-}` but it had no effect.

**Comment by eddiemundo** [comment]
I looked into this and it seems to be that the hlint plugin in the end gets the `HLINT_ON_GHC_LIB` flag set, and cause of some cpp, flags (specifically fixities) from the `.hlint.yaml` are ignored:
https://github.com/haskell/haskell-language-server/blob/4cd1082743f4cb70fe9ce66962d31a2bd1d51da2/plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs#L238-L246

I think applying fixities in the flags to `modu` before passing it to `createModuleEx` would do the trick.
