### ISSUE TITLE
Stack setup might be polluting output of haskell-language-server-wrapper --project-ghc-version

### ISSUE THREAD

**Issue by bubba** [haskell/haskell-language-server#242]
Looks like with Stack on Windows the unpacking of GHC might be polluting stdout:
![image](https://user-images.githubusercontent.com/2488460/88488292-23b63d80-cf84-11ea-9742-0154c3017eac.png)

**Comment by jneira** [comment]
Maybe it could be fixed by https://github.com/mpickering/hie-bios/pull/254

**Comment by jneira** [comment]
The pr mentioned is merged so this woulf be fixed using a new version of hie-bios (maybe we are already using it?)

**Comment by jneira** [comment]
I am gonna close this optimistically as we should be using the hie-bios with the patch
