### ISSUE TITLE
Nix build in ci fails due to primitive-extras-0.10.1 build error with ghc-9.0.1

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#2430]
* From https://github.com/haskell/haskell-language-server/pull/2419#issuecomment-983526246
* [nix build in master](https://github.com/haskell/haskell-language-server/runs/4378729936?check_suite_focus=true)
```
primitive-extras> Preprocessing library for primitive-extras-0.10.1..
primitive-extras> Building library for primitive-extras-0.10.1..
primitive-extras> [ 1 of 10] Compiling PrimitiveExtras.Prelude ( library/PrimitiveExtras/Prelude.hs, dist/build/PrimitiveExtras/Prelude.o, dist/build/PrimitiveExtras/Prelude.dyn_o )
primitive-extras> [ 2 of 10] Compiling PrimitiveExtras.Types ( library/PrimitiveExtras/Types.hs, dist/build/PrimitiveExtras/Types.o, dist/build/PrimitiveExtras/Types.dyn_o )
primitive-extras> [ 3 of 10] Compiling PrimitiveExtras.SmallArray ( library/PrimitiveExtras/SmallArray.hs, dist/build/PrimitiveExtras/SmallArray.o, dist/build/PrimitiveExtras/SmallArray.dyn_o )
primitive-extras> [ 4 of 10] Compiling PrimitiveExtras.Bitmap ( library/PrimitiveExtras/Bitmap.hs, dist/build/PrimitiveExtras/Bitmap.o, dist/build/PrimitiveExtras/Bitmap.dyn_o )
primitive-extras> library/PrimitiveExtras/Bitmap.hs:5:3: error:
primitive-extras>     Ambiguous occurrence ‘singleton’
primitive-extras>     It could refer to
primitive-extras>        either ‘PrimitiveExtras.Prelude.singleton’,
primitive-extras>               imported from ‘PrimitiveExtras.Prelude’ at library/PrimitiveExtras/Bitmap.hs:25:1-70
primitive-extras>               (and originally defined in ‘base-4.15.0.0:Data.OldList’)
primitive-extras>            or ‘PrimitiveExtras.Bitmap.singleton’,
primitive-extras>               defined at library/PrimitiveExtras/Bitmap.hs:53:1
primitive-extras>   |
primitive-extras> 5 |   singleton,
primitive-extras>   |   ^^^^^^^^^
primitive-extras> [ 6 of 10] Compiling PrimitiveExtras.UnliftedArray ( library/PrimitiveExtras/UnliftedArray.hs, dist/build/PrimitiveExtras/UnliftedArray.o, dist/build/PrimitiveExtras/UnliftedArray.dyn_o )
```

It seems we are building an older release 0.10.1 which seems to be not compatible with ghc-9.0.1
Locally cabal picks 0.10.2

Asking for help from my dear nix+hls power users
//cc @maralorn @berberman @fendor @michaelpj

**Comment by michaelpj** [comment]
Dumb question: how did this make it into master? do the nix jobs not block merging?

I'll try and take a look at this.

**Comment by maralorn** [comment]
I am very confused. As far as I can tell this error didn't happen in nixpkgs master. We would never merge an update with this issue and our ci would definitely catch this.

**Comment by jneira** [comment]
> Dumb question: how did this make it into master? do the nix jobs not block merging?
> 
> I'll try and take a look at this.

the build on pr only is triggered on master if the pr does not change the nix workflow config file

https://github.com/haskell/haskell-language-server/blob/711e19cb479e7de3ff114e3b02f0362fe94c4716/.github/workflows/nix.yml#L65-L74

That pr touched the cache and maybe it could cause the issue

I think we should run it for every pr

**Comment by jneira** [comment]
> That pr touched the cache and maybe it could cause the issue

Rectifiction the nix build dont use the cabal cache touched in the pr so i dont see how could it cause the nix build fail

**Comment by michaelpj** [comment]
My plan is just to try bumping nixpkgs and see if that fixes it.
