### ISSUE TITLE
Wingman: Using the completion system for case analysis

### ISSUE THREAD

**Issue by kalhauge** [haskell/haskell-language-server#2437]
**Is your feature request related to a problem? Please describe.**

When I write code I often write it like this:

```haskell
foldMaybe :: Monoid m => Maybe m -> m
foldMaybe m = case m of 
   -- hmm.. what was the cases for Maybe again...
```

Right now I have to,
1. stop what I'm doing, 
2. click on the code lens hint, 
3. and apply the change, 
4. navigate to the first _ and start writing.

**Describe the solution you'd like**

It would be really nice if we could somehow "TAB" (pun intended) into the lsp completion/snippet system, 
and when I have written the `of` I can tap complete and be presented with a `case` expansion,
(and possibly a 'hylo'-morphic case expansion and a monadic case expansion):

```haskell
foldMaybe :: Monoid m => Maybe m -> m
foldMaybe m = case m of<TAB>(choose case)
   Just a -> _
   Nothing -> _

mapMaybe :: (a -> b) -> Maybe a -> Maybe b
mapMaybe  fn m  = case m of<TAB>(choose hylo)
   Just a -> Just _
   Nothing -> Nothing

mapMaybeM :: Monad m => (a -> m b) -> Maybe a -> m (Maybe b)
mapMaybeM m = case m of<TAB>(choose "do" hylo)
   Just a -> do 
    pure $ Just _
   Nothing -> do 
    pure $ Nothing
```

This suggestion is only for the case analysis part, it might however also work for refinements. If you 
are on a "_" and press tab, it could suggest a refined solution if it finds one in less than 0.x seconds, suggest it, otherwise it might suggest one of the other transformations.

**Describe alternatives you've considered**

Wingman works great as is, but this would really be a "killer" feature.

**Additional context**

There seem to be some kind of support for snippets in the LSP protocol, but I don't know how well it is integrated in the different editors (and in the haskell-language-server).

**Comment by pepeiborra** [comment]
You could create key bindings to trigger code lenses, depending on your editor, if that's what bothers you. 

But I agree that having a Wingman powered completion provider would be awesome.

**Comment by pepeiborra** [comment]
Would you be interested in contributing a PR? I'm sure @isovector could provide some starting tips

**Comment by kalhauge** [comment]
@pepeiborra I do have some time over the Christmas break, but I have no Idea about where to start. I'm pretty familiar to Haskell, but new to both the HLS code-base and to LSP.

**Comment by isovector** [comment]
This sounds like a great idea. Though doing this quickly I think is the challenge. Running the completion code is rather involved (slow), and you probably don't want to do it on every keypress!

**Comment by kalhauge** [comment]
It seems like there is an example setup (sadly, not using the _comand option) use in [plugins/hls-pragmas-plugin/src/Ide/Plugin/Pragmas.hs:L212](https://github.com/haskell/haskell-language-server/blob/master/plugins/hls-pragmas-plugin/src/Ide/Plugin/Pragmas.hs#L212) which might be usefull?

**Comment by michaelpj** [comment]
The ideal way would be to actually return the text to be inserted as part of the completion item edit, since then you could indeed send it as a snippet, which would potentially give a nicer UX. I guess computing the edit is expensive, but since we'd presumably only do this completion after an `of` token, it shouldn't be too hard to mostly avoid doing the work?

**Comment by kalhauge** [comment]
> The ideal way would be to actually return the text to be inserted as part of the completion item edit, since then you could indeed send it as a snippet, which would potentially give a nicer UX. I guess computing the edit is expensive, but since we'd presumably only do this completion after an `of` token, it shouldn't be too hard to mostly avoid doing the work?

This is exactly something like this I think would be really useful. Also I think we could expand it to also work for `_`. Seeing the snippet before applying it, could make the user more willing to experiment with different tactics?
