### ISSUE TITLE
Adding (\\) operator to import list adds it without surrounding it in parenthesis

### ISSUE THREAD

**Issue by jhrcek** [haskell/haskell-language-server#2451]
### Your environment

Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper) Version 1.5.1.0, Git revision dcd2163d81f4bb3228203598a761b005c54b1796 (2504 commits) x86_64 ghc-8.10.7
Current directory: /home/jhrcek/Devel/github.com/Holmusk/PI/backend
Operating system: linux
Arguments: ["--lsp"]
Cradle directory: /home/jhrcek/Devel/github.com/Holmusk/PI/backend
Cradle type: Stack

Tool versions found on the $PATH
cabal:		3.6.2.0
stack:		2.7.3
ghc:		8.10.7

### Steps to reproduce
See this gif

![ImportBug](https://user-images.githubusercontent.com/2716069/145226677-e6c65a46-9f50-4e49-956d-d5fab12dbbc1.gif)

### Expected behaviour
The `\\` operator should be surrounded in `()` after it's added to import list

### Actual behaviour
The `\\` operator is added without `()`

**Comment by jneira** [comment]
Thanks for reporting the issue, i've tried to reproduce it in windows using ghc-9.0.1 and i was not able:

![imagen](https://user-images.githubusercontent.com/54035/145249525-40aeb58b-c5ae-4917-8160-5a9d47348fc9.png)

My test module looks like yours 🤔

**Comment by jhrcek** [comment]
Interesting.
Seeing that the thing to add to import list is extracted from GHC error via regex,
I tried to compile the demo module with various versions of GHC and each time I got the same output, each time without `()`s
```bash
~/Tmp> ghcup set ghc 8.8.4
[ Info  ] GHC 8.8.4 successfully set as default version
~/Tmp> ghc Demo.hs 
[1 of 1] Compiling Demo             ( Demo.hs, Demo.o )

Demo.hs:3:12: error:
    • Variable not in scope: (\\) :: [Bool] -> [a0] -> t
    • Perhaps you want to add ‘\\’ to the import list in the import of
      ‘Data.List’ (Demo.hs:2:1-19).
  |
3 | x = [True] \\ []
  |            ^^
~/Tmp> ghcup set ghc 8.10.7
[ Info  ] GHC 8.10.7 successfully set as default version
~/Tmp> ghc Demo.hs 
[1 of 1] Compiling Demo             ( Demo.hs, Demo.o )

Demo.hs:3:12: error:
    • Variable not in scope: (\\) :: [Bool] -> [a0] -> t
    • Perhaps you want to add ‘\\’ to the import list in the import of
      ‘Data.List’ (Demo.hs:2:1-19).
  |
3 | x = [True] \\ []
  |            ^^
~/Tmp> ghcup set ghc 9.0.1
[ Info  ] GHC 9.0.1 successfully set as default version
~/Tmp> ghc Demo.hs 
[1 of 1] Compiling Demo             ( Demo.hs, Demo.o )

Demo.hs:3:12: error:
    • Variable not in scope: (\\) :: [Bool] -> [a0] -> t
    • Perhaps you want to add ‘\\’ to the import list in the import of
      ‘Data.List’ (Demo.hs:2:1-19).
  |
3 | x = [True] \\ []
  |            ^^
~/Tmp> ghcup set ghc 9.2.1
[ Info  ] GHC 9.2.1 successfully set as default version
~/Tmp> ghc Demo.hs 
[1 of 1] Compiling Demo             ( Demo.hs, Demo.o )

Demo.hs:3:12: error:
    • Variable not in scope: (\\) :: [Bool] -> [a0] -> t
    • Perhaps you want to add ‘\\’ to the import list in the import of
      ‘Data.List’ (Demo.hs:2:1-19).
  |
3 | x = [True] \\ []
  |            ^^
```

Can you please compile this module on command line and share the output that ghc gives you?

```Haskell
module Demo where
import Data.List ()
x = [True] \\ []
```

**Comment by jneira** [comment]
I am just aware i am on 1.5.0 so maybe it is a regression

**Comment by jneira** [comment]
> Can you please compile this module on command line and share the output that ghc gives you?

with ghc-9.0.1

```
src\Demo.hs:3:12: error:
    • Variable not in scope: (\\) :: [Bool] -> [a0] -> t
    • Perhaps you want to add ‘\\’ to the import list in the import of
      ‘Data.List’ (src\Demo.hs:2:1-19).
  |
3 | x = [True] \\ []
  |         
```

**Comment by jhrcek** [comment]
I found where the issue is coming from.
In our codebase we're using relude and hiding base's Prelude.
Since relude doesn't reexport Data.List's `(\\)` operator, it's not present in the imports map, so the code ends up in this fallback [branch](https://github.com/haskell/haskell-language-server/blob/ddacbced0f983a0b41dbb8a3b5340a54052095a1/ghcide/src/Development/IDE/Plugin/CodeAction.hs#L840) which contains the operator not surrounded in parens.

I'll see if I can come up with reasonably simple reproducer :sweat_smile:

**Comment by jhrcek** [comment]
Alright, I'm closer to the root cause, but not sure if there's good way to write a reproducer for tests.
To recap, the incorrect import happens because the code ends up in this [fallback branch](https://github.com/haskell/haskell-language-server/blob/ddacbced0f983a0b41dbb8a3b5340a54052095a1/ghcide/src/Development/IDE/Plugin/CodeAction.hs#L836-L843), because the module `Data.List` is not present in the `ExportsMap`.

Why is `Data.List` missing from the `ExportsMap`?
During construction of the ExportsMap the following error is returned on [this line](https://github.com/haskell/haskell-language-server/blob/ddacbced0f983a0b41dbb8a3b5340a54052095a1/ghcide/src/Development/IDE/Types/HscEnvEq.hs#L92):
```
Failed to load interface for ‘Data.List’
There are files missing in the ‘base-noprelude-4.14.3.0’ package,
```
This most likely happens because [base-noprelude](https://github.com/haskell-hvr/base-noprelude) doesn't actually contain any modules, it only re-exports modules from the `base` (all except Prelude).

In light of this I'm not sure what's the best way to apply the fix:
- add a workaround to the fallback branch to wrap operator in parentesis?
- fix the code constructing the ExportsMap so it can load the re-exported modules? (not sure if/how this could be done)
- fix the GHC error message so it wraps the operator in parens (probably not worth it because structured ghc messages are coming soon?)

**Comment by pepeiborra** [comment]
I think you have tracked down the bug. Amazing work!
 
We probably shouldn't be ignoring the second component returned by `unitExposedModules`:
> Modules exposed by the unit. A module can be re-exported from another package. In this case, we indicate the module origin in the second parameter.

https://hackage.haskell.org/package/ghc-9.2.1/docs/GHC-Unit-Info.html#v:unitExposedModules

**Comment by michaelpj** [comment]
I think this got fixed.
