### ISSUE TITLE
Error "file is a directory" on attempt to go to documentation/source (Windows)

### ISSUE THREAD

**Issue by DunetsNM** [haskell/haskell-language-server#247]
Windows 10, VS Code, GHC 8.6.5
HLS reinstalled from scratch with precompiled 0.2.1 binaries

Trying to browse source from the tooltip:

![image](https://user-images.githubusercontent.com/5116838/88658438-8f84db80-d127-11ea-9aa3-2a6dec7326b6.png)

Getting following error:

![image](https://user-images.githubusercontent.com/5116838/88658486-a3304200-d127-11ea-985e-3bc747d790ae.png)

The file does exist and it's not a directory.

It is probably because file url has two slashes (file://...) but should have three (file:///), as described here https://github.com/microsoft/vscode/issues/62251

**Comment by DunetsNM** [comment]
is fix as simple as adding extra slash in module Development.IDE.Spans.Documentation ?

**Comment by bubba** [comment]
It might be, did that fix the case on windows? I can test out adding an extra slash on macOS and see if that works

**Comment by DunetsNM** [comment]
@bubba tried just now, it worked to some extent: opened new tab with raw html source, which is not very helpful but probably depends related to my local vs or machine configuration
![image](https://user-images.githubusercontent.com/5116838/88753875-7aed2580-d1b1-11ea-9516-6778b5b9d571.png)

**Comment by DunetsNM** [comment]
OK seems like bug needs to be fixed in two places

1. add third slash in file: urls (trivial)

1. Update VS Code extension that overrides file urls with custom command (see https://github.com/haskell/vscode-haskell/pull/21) It doesn't understand backslashes from Windows file paths.

As alternative, slashes in paths can be normalized to forward slashes within HLS code?

Looking into this...

**Comment by DunetsNM** [comment]
Fixed as of 0.4.0
