### ISSUE TITLE
Document what is required to get HLint working

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haskell-language-server#249]
A search of the repo suggests that HLint is supported. But on my sample project, it doesn't make any suggestions, even when I define the classic:

```
foo f g x = map f (map g x)
```

(That was the first hint HLint ever matched.) The docs don't mention HLint at all. It would be useful if the docs included a note that HLint exists, some way of testing it, and ideally some way of validating that it works.

Or maybe HLint isn't yet supported?

**Comment by fendor** [comment]
HLint is not supported yet, see the PR #166 to add it.

**Comment by Ailrun** [comment]
#32 is the issue tracking the HLint plugin.

**Comment by bubba** [comment]
Where is hlint being advertised? We should probably take that down until it's actually merged. I can imagine it might be a leftover of code being copied over from HIE

**Comment by ndmitchell** [comment]
It wasn't being advertised - I just searched for HLint and found some configuration settings. I don't think there's any advertising removal that needs doing, but lets hope #166 is ready soon :)

**Comment by jneira** [comment]
@ndmitchell i think we can close this one as we have the main issue and the ongoing pr will come soon (hopefully :smile:)
