### ISSUE TITLE
Bug: test tries to discover in `dist-newstyle`

### ISSUE THREAD

**Issue by GuillaumeDesforges** [haskell/haskell-language-server#251]
From https://github.com/NixOS/nixpkgs/pull/93768

```
Test suite wrapper-test: RUNNING...
haskell-language-server-wrapper
  --project-ghc-version
    stack with ghc 8.10.1: FAIL
      Exception: dist-newstyle: getDirectoryContents:openDirStream: does not exist (No such file or directory)
    stack with ghc 8.8.3:  FAIL
      Exception: dist-newstyle: getDirectoryContents:openDirStream: does not exist (No such file or directory)
    cabal with global ghc: FAIL
      Exception: dist-newstyle: getDirectoryContents:openDirStream: does not exist (No such file or directory)

3 out of 3 tests failed (0.07s)
Test suite wrapper-test: FAIL
Test suite logged to:
dist/test/haskell-language-server-0.2.2.0-wrapper-test.log
```

https://github.com/NixOS/nixpkgs/pull/93768#issuecomment-665271699 

> I had a chat with lukelau in the hls freenode room. The issue seems to be simple and generic. The test needs the binary in the PATH and they wrote a hack accessing dist-newstyle to discover the binaries.

cc @maralorn

**Comment by bubba** [comment]
Can you check that this was fixed in https://github.com/haskell/haskell-language-server/commit/9d3d0e6f13fabfd089cfc7ef17186e49c274efa8

**Comment by maralorn** [comment]
@bubba I will check when I am back at the keyboard. Will probably take a week.

**Comment by jneira** [comment]
@GuillaumeDesforges @maralorn could you confirm if this was fixed by the commit referenced above?

**Comment by maralorn** [comment]
Sorry for letting this slide. This seems to be fixed.

Of course we have tons of other tests failing and I have trouble fixing all of them.

**Comment by jneira** [comment]
Ok, i am gonna close this one then. Feel free to open new ones for failing tests
