### ISSUE TITLE
CI test fails

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-language-server#252]
Seemingly in the latest commits, we have flaky CI results, e.g. some tests fail occasionally. This is really annoying, as it is hard to tell whether this is your PR's fault, or someone else's.

**Comment by bubba** [comment]
I broke these trying to get #243 in. All the tests were passing locally for me on macOS, so I'll need to spend some time debugging CircleCI

**Comment by bubba** [comment]
I'm not sure if I did break these in the end. Looks like these were already kind of flakey [here](https://app.circleci.com/pipelines/github/haskell/haskell-language-server/262/workflows/c4cdee65-d9ef-420d-8bf3-d07e8c01e0c9/jobs/1391) and [here](https://app.circleci.com/pipelines/github/haskell/haskell-language-server/245/workflows/dd50280a-d36f-4089-848c-9d75aacd7419/jobs/1308), but something recently is causing them to fail
