### ISSUE TITLE
Please, update `master` to `index-state: >=2021-12-18T00:00:08Z`

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell/haskell-language-server#2524]
The next best step in CI I can think of, to properly help GHC 9.2 work in #2503 - is to (what `jneira` was asking) update the Hackage snapshot we use.

When we would make the `master` `index-state` a bit higher then what is used in #2503 & then match #2503 to `master` `index-state` - `master` would start to build actually buildable cache (that is impossible to build inside #2503) & properly provide cache from `master` into there, which would ensure builds fast CI checks there.

Would note it is Ops part of #2179.

Would note that recent merge of `master` into #2503 caused the `index-state` roll back there. & `2021-12-18T00:00:08Z` was used there for GHC 9.2 work.

So I should stop the use of `index-state` changing to refresh caches & to just use `hash` changing - it would not create such sideeffect under that direction of rebases.

**Comment by jneira** [comment]
sorry, but I am not sure if I am understanding the issue, afaics we have now all cabal.project in master and ghc with index 10Z
what would we get setting them(in both branches or only in master?) to 8Z?

**Comment by jneira** [comment]
could we close this? the index will be updated anyways in the ongoing PRS about support for aeson 2 and/or ghc-9.0.2

**Comment by Anton-Latukha** [comment]
Yep.
