### ISSUE TITLE
Quasiquotation is not working on MacOS: Symbol not found: _pcre_compile2

### ISSUE THREAD

**Issue by ingun37** [haskell/haskell-language-server#2546]
### Your environment

Which OS do you use:
MacOS
Which LSP client (editor/plugin) do you use:
VSCode+Haskell
Describe your project (alternative: link to the project):
stack.yaml, package.yaml

### Steps to reproduce
Install `pcre-heavy`, enable `{-# LANGUAGE QuasiQuotes, FlexibleContexts #-}`, and then define anything using QuasiQuotation
```haskell
{-# LANGUAGE QuasiQuotes, FlexibleContexts #-}
import Text.Regex.PCRE.Heavy
aaa = [re|\d+|]
```

### Expected behaviour
HLS not to crash.

### Actual behaviour
HLS Crashes.

### Include debug information
```
dyld: lazy symbol binding failed: Symbol not found: _pcre_compile2
  Referenced from: /usr/local/lib/libpcre.dylib
  Expected in: flat namespace

dyld: Symbol not found: _pcre_compile2
  Referenced from: /usr/local/lib/libpcre.dylib
  Expected in: flat namespace
```

**Comment by jneira** [comment]
hi, thanks for the bug report, I am afraid hls support  for template Haskell using precompiled binaries is sometimes not reliable, specially in macos
See the troubleshooting guide to see a possible workaround for the issue:
https://haskell-language-server.readthedocs.io/en/latest/troubleshooting.html#static-binaries

**Comment by jneira** [comment]
As there are lot of similar but reports about thecsame root problem and a meta issue about (https://github.com/haskell/haskell-language-server/issues/1431) I am gonna close this one if you don't mind, feel free to reopen if you think this one differs in any way
