### ISSUE TITLE
Module import code action ignores reexported-modules

### ISSUE THREAD

**Issue by guibou** [haskell/haskell-language-server#2554]
### Your environment

Which OS do you use: Linux
Which LSP client (editor/plugin) do you use: NeoVim + lspconfig
Describe your project (alternative: link to the project): https://github.com/guibou/repro_hls_base_no_prelude

### Steps to reproduce

You can checkout https://github.com/guibou/repro_hls_base_no_prelude, it contains two cabal project with one `Main.hs` file with the following content:

```haskell
{-# LANGUAGE NoImplicitPrelude #-}
module Main where

main :: IO ()
main = putStrLn "Hello, Haskell!"
```

### Expected behaviour

The code above should not typecheck (i.e. `IO` is not in scope). Code action on the offending line should suggestion to import a few module, such as `System.IO` or `Prelude`.

### Actual behaviour

There is two variations in the sample codebase.

- One is a project with `base` as a dependency. Code action works as expected and suggest to import `System.IO` (as well as other modules from `base` which exports `IO`).

![image](https://user-images.githubusercontent.com/9705357/147773844-7712c068-5584-4197-9904-364b528eea47.png)

- The second project uses `base-noprelude` as a dependency. `base-noprelude` is a package which reexport all modules from base but `Prelude`. `System.IO` is exported, see: https://github.com/haskell-hvr/base-noprelude/blob/master/base-noprelude.cabal#L232, However, code action does not suggest to import `System.IO`:

![image](https://user-images.githubusercontent.com/9705357/147773855-d9d25111-8638-44f7-8265-12e5c7467749.png)

Note that in both cases, importing `System.IO` fixs the type error.

**Comment by jhrcek** [comment]
Could you please share the precise version of haskell-language-server you're using?
I was experiencing similar issue (we're also using base-noprelude) and I think I fixed the problem in https://github.com/haskell/haskell-language-server/pull/2468
If it's not fix the fix might need to be revisited.

Here's what the code action offers to me in your reproducer project (haskell-language-server built from current master):

![Screenshot from 2021-12-30 18-37-14](https://user-images.githubusercontent.com/2716069/147775413-f9c8b66e-7c89-481b-8c10-b3195224d6b9.png)

**Comment by guibou** [comment]
That's a super question that I should have answered when opening the issue.

- In my repro example, I use 1.5.1.0 as available in nixpkgs, so I suppose that's 1.5.1.0
- In my main repo, I use 87a69c2e6d1fa28b7b5a9d9cb3fb6a4c334f7566

Both are actually older than your #2468 so hey, the fix may already be there.

I'll try when next version will be released, the nix flake for current dev version does not work anymore (see #2030).

Thank you for your time.

**Comment by guibou** [comment]
@jhrcek I was able to test with latest HLS (master) and indeed the bug is fixed.

Thank you for your work, sorry for the noise, have a nice year!

**Comment by jhrcek** [comment]
@guibou thank you for confirming, my pleasure that the fix is useful for others.
Happy new year to you too :smile:
