### ISSUE TITLE
Please, organize GHC 9.2 API changes

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell/haskell-language-server#2568]
GHC 9.2 still had API organization & changes.

During hard work in #2503 - some of CPP were placed around, https://github.com/haskell/haskell-language-server/pull/2503#issuecomment-1006902521, the organization would be appreciated.

`CPP` is justified in `.ExactPrint` modules, since `ghc-exactprint` has been redesigned in `ghc 9.2`: the types and programming model are completely different, so much that it doesn't make sense to abstract those differences behind `Compat` modules.

The rest need to be organized into `Compat` infrastructure. `ghcide`'s `GHC.Compat` infrastructure is planned for #2454, so it is a community-useful work.

**Comment by pepeiborra** [comment]
> During hard work in #2503 - the 9.2 CPP organization was sacrificed for the main agenda & CPPs were scattered across the codebase. #2503 (comment)

This is not completely accurate - ghc-exactprint has been redesigned in ghc 9.2 and the types and programming model are completely different, so much that it doesn't make sense to abstract the differences behind Compat modules. So CPP is justified in `.ExactPrint` modules.

**Comment by Anton-Latukha** [comment]
In cases like these I love to use the rewriting paradigm, I just allow editing my headposts to clarify/add details. I do it myself to add details to reports headposts. And I often open reports to properly kanban "`Next: `" tasks regardless of my understanding & the source they came from, so frequently I await for context to be modified a bit & details to be added.

*(updated the headpost with information)*

**Comment by michaelpj** [comment]
Refactoring our CPP would be nice, but this particular thing is not going to get done
