### ISSUE TITLE
Allow defining new functions with typed holes

### ISSUE THREAD

**Issue by bradrn** [haskell/haskell-language-server#2572]
**Is your feature request related to a problem? Please describe.**

At the moment, the ‘Define &lt;function>’ code action is hardcoded to produce `name <> " = error \"not implemented\""` as the body of the function:

https://github.com/haskell/haskell-language-server/blob/65a8512761369778c7a1820cc99ea3365958bdec/ghcide/src/Development/IDE/Plugin/CodeAction.hs#L683-L685

This is mostly satisfactory — but has the disadvantage of not producing a compiler error. If defining several new functions at once, it is easy to forget to go back and fill it in.

**Describe the solution you'd like**

It would be nice to have the option to define the function as a typed hole — so something like:

```diff
 = [ ("Define " <> sig 
     , [TextEdit (Range nextLineP nextLineP) (T.unlines ["", sig, name <> " = error \"not implemented\""])] 
+    )
+  , ("Define " <> sig <> " as typed hole"
+    , [TextEdit (Range nextLineP nextLineP) (T.unlines ["", sig, name <> " = _"])]
     )]
```

This would provide an easy way to reduce the number of code errors. It also provides a better UX: in my editor (Emacs), for instance, it would let me jump to and from the new function using `flycheck-next-error` etc.

**Comment by jneira** [comment]
thanks for the suggestion, coincidentally there is a pr which aims to implement it: https://github.com/haskell/haskell-language-server/pull/2465#issuecomment-991553882

**Comment by bradrn** [comment]
Thanks @jneira! It’s a pretty minimal PR; any idea when it might be merged?

**Comment by jneira** [comment]
Afaics it "only" needs make the CI green 🙂

**Comment by michaelpj** [comment]
Fixed.
