### ISSUE TITLE
Random red squiggles when working with `.lhs` files

### ISSUE THREAD

**Issue by MangoIV** [haskell/haskell-language-server#2573]
### Your environment

Which OS do you use:
NixOS 
Which LSP client (editor/plugin) do you use:
Neovim+LanguageClient-neovim
Describe your project (alternative: link to the project):
*.cabal 

### Steps to reproduce
probably just create a cabal project with an lhs files

### Expected behaviour
same highlighting as with normal .hs files

### Actual behaviour
I get random red squiggles underneath some identifiers.
![image](https://user-images.githubusercontent.com/40720523/148683485-aaedb594-a2ce-46b0-9adb-199825e57636.png)
This code compiled with no warnings and no errors, however, I get red squiggles 
Running the hls-wrapper directly on the file also finishes without errors

```
Step 1/4: Finding files to test in /home/mangoiv/Devel/project-name/src
Found 1 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle
  ()

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
2022-01-09 14:15:14.270403563 [ThreadId 25] INFO hls:	Consulting the cradle for "FileName.lhs"
2022-01-09 14:15:14.270672946 [ThreadId 25] WARNING hls:	No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for FileName.lhs.
 Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie).
You should ignore this message, unless you see a 'Multi Cradle: No prefixes matched' error.
2022-01-09 14:15:14.450411487 [ThreadId 25] INFO hls:	Using interface files cache dir: /home/mangoiv/.cache/ghcide/main-da39a3ee5e6b4b0d3255bfef95601890afd80709
2022-01-09 14:15:14.450649441 [ThreadId 25] INFO hls:	Making new HscEnv[main]
2022-01-09 14:15:14.883188562 [ThreadId 44] INFO hls:	finish: User TypeCheck (took 0.41s)
2022-01-09 14:15:14.891917784 [ThreadId 95] INFO hls:	finish: GetHie (took 0.01s)
2022-01-09 14:15:14.892848368 [ThreadId 101] INFO hls:	finish: GenerateCore (took 0.00s)

Completed (1 file worked, 0 files failed)
```

There are also weird issues when not leaving free lines between haskell code and text.

**Comment by jneira** [comment]
hi, thanks for the bug report, does it reproduce consistently in any lhs file even a simpler one (and no in the more equivalent file possible but hs)?

**Comment by MangoIV** [comment]
The problem is that I do not know why the squiggles appear, it looks completely random. I can try to reproduce it in a different file if I find the time.

**Comment by jneira** [comment]
The lsp log would be helpful too, as those diagnostics will be reflected in it

**Comment by MangoIV** [comment]
Ok, I've played around some more and I now think that this might not even be an issue of the haskell-language server but a different error. 
I cannot supply enough information for this issue to be resolved successfully at the moment, I guess, so I will close the issue for now and reopen it if I get more information.
