### ISSUE TITLE
Please, CI: review the test matrix

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell/haskell-language-server#2575]
A while ago noticed that test matrix, lets say "needs to be reviewed".

MPJ noticed that also https://github.com/haskell/haskell-language-server/pull/2503#issuecomment-1002573725

(macOS never runs the test suite)

---

The matrix overall can be reviewed to do fewer builds & tests but do that strategically.

**Comment by Anton-Latukha** [comment]
Current matrix:
![image](https://user-images.githubusercontent.com/20933385/148698085-41b93f21-ddc4-468e-b1f0-09bf660c106c.png)

**Comment by Anton-Latukha** [comment]
I also have a bias towards Linux, but not to that degree 8).

**Comment by Anton-Latukha** [comment]
Since changes generally relate/address the newest changes in GHCs - it is important to check the testsuite for the newest GHCs on all platforms.

The oldest one can be skipped on Linux, in favor of macOS, since Linux is generally more Linux enthusiasts & the platform is fastest at updating the packages & other things. This argumentation is minor, because a lot of test suite runs that are unlikely to fail from a set (for example Ubuntu Linux GHC 8.6.5, with that GHC 8.6.5 passed on other platform) - that check can be deferred to run on main branch after the merge. So minor checks would stop run constantly on PR push & run once after the merge to check minor possibilities "just in case". In case some of those minor checks is failing in the main branch - that workflow state does not block other PRs to be merged, that minor check only notifies maintainers/community on the test failure in particular GHC version. And in a majority of cases the maintainers can right away request from PR author that contributed the patch - to fix the build for that version of GHC, so the author sends the minor patch. The described process happens rarely, especially for example - for things that do not use low-level OS FFIs (for example plugins, if they are built on 1 platform - for them unlikely to fail on the other platforms).

**Comment by Anton-Latukha** [comment]
The very conservative way then would look like:
![Screenshot-2022-01-09-22:07:49](https://user-images.githubusercontent.com/20933385/148698857-05206d0f-d68d-41c7-9568-82621e556d6a.png)

**Comment by Anton-Latukha** [comment]
The more, for brevity, effective matrix would look something like:
![image](https://user-images.githubusercontent.com/20933385/148699161-8a5c4f87-3667-433a-b209-aec9289ce2b8.png)

The newest & recommended & the oldest GHCs run the testsuite on PR but run it in different platforms & then additionally cross-check results after the merge.

The after merge cross-checks are much cheaper, they are running once per merge (so much more checks can run) & nobody waits for them. They are essential to check less probable things through an ad-hoc system of notification.

**Comment by Anton-Latukha** [comment]
But this optimization has a value when the time can be saved, or project contribution flow exhausts the CI job runners.

**Comment by Anton-Latukha** [comment]
That would be:

![image](https://user-images.githubusercontent.com/20933385/148699831-095828ef-7ae3-4fbd-8e76-f7ec16831a3e.png)

**Comment by michaelpj** [comment]
I did quite a bit on this, it's in a better state now
