### ISSUE TITLE
[Feature] Provide Stan integration

### ISSUE THREAD

**Issue by sir4ur0n** [haskell/haskell-language-server#258]
I propose HLS supports [Stan](https://hackage.haskell.org/package/stan-0.0.1.0) integration, what do you think?

**Comment by Ailrun** [comment]
I think it would be great if possible, but as they use .hie file, we cannot use them for GHC < 8.8...

**Comment by Sir4ur0n** [comment]
> P.S. You are at the Haskell Love Conference, aren't you? :)

Yes, and I wanted to link the existing HLS-Stan integration issue to others. That's how I noticed there is no issue yet :stuck_out_tongue:

**Comment by fendor** [comment]
Hi, I started with this, but have no particular branch yet.
I once had a somewhat working impl, but we need https://github.com/digital-asset/ghcide/pull/701, too.

**Comment by googleson78** [comment]
https://github.com/haskell/ghcide/pull/701 is now in `hls` master, what additional work needs to be done to get this working? @fendor

**Comment by jneira** [comment]
A required step for sure would be create a plugin to provide stan diagnostics and refactorings (?). I think `hls-hlint-plugin` could be a good starting point.

**Comment by googleson78** [comment]
I was wondering if @fendor s work is something that's "almost done", and just needs a bit of cleanup.

**Comment by fendor** [comment]
@googleson78 The work got stalled, and it was not that much, so we should rather re-write it. I don't have anything workable at the moment :(

**Comment by uhbif19** [comment]
I will try to work on this.

As far as I understand, it required to add new Rule, which will call Stan `runAnalysis` for each project file.

**Comment by fendor** [comment]
Right, but ideally we re-use the .HIE files HLS is already generating, so we save some work.

**Comment by uhbif19** [comment]
Stan requires `HieTypes.HieFile` while HLS `GetHieAst` returns `HieAstResult`, which contains only `Module`, not the whole file.
Is there any way to get `HieTypes.HieFile` out of HLS?

**Comment by pepeiborra** [comment]
HLS writes `.hie` files to disk, so you can definitely get a `HieFile` out of HLS although it's far from trivial. Something like this should do it:

```haskell
getHieFile :: NormalizedFilePath -> Action (Maybe HieFile)
getHieFile nfp = runMaybeT $ do
    HAR{hieAst} <- MaybeT $ use GetHieAst nfp
    tmr <- MaybeT $ use TypeCheck nfp
    ghc <- MaybeT $ use GhcSession nfp
    msr <- MaybeT $ use GetModSummaryWithoutTimestamps nfp
    source <- lift $ getSourceFileSource nfp
    let exports = tcg_exports $ tmrTypechecked tmr
    typedAst <- MaybeT $ pure $ cast hieAst
    liftIO $ runHsc (hscEnv ghc) $ mkHieFile' (msrModSummary msr) exports typedAst source
```

**Comment by uhbif19** [comment]
@pepeiborra 

Got error:

```
src/Ide/Plugin/Stan.hs:68:33: error:
    • No instance for (Typeable a) arising from a use of ‘cast’
    • In the second argument of ‘($)’, namely ‘cast hieAst’
      In the second argument of ‘($)’, namely ‘pure $ cast hieAst’
      In a stmt of a 'do' block: typedAst <- MaybeT $ pure $ cast hieAst
   |
68 |     typedAst <- MaybeT $ pure $ cast hieAst
   |                                 ^^^^^^^^^^^
```

**Comment by pepeiborra** [comment]
Add a Typeable constraint in the HAR constructor of the HieAstResult data type

**Comment by uhbif19** [comment]
@pepeiborra Thank you very much, your code worked.

Done WIP PR.
