### ISSUE TITLE
Ideas on CI improvements/refactoring

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell/haskell-language-server#2586]
- [ ] Reduce the test shotgun surgery: https://github.com/haskell/haskell-language-server/pull/2567#discussion_r778986427
  - [ ] Document `hackage.yml` inside code : https://github.com/haskell/haskell-language-server/pull/2567#discussion_r778978414
  - [x] After stabilization of code/action - refactor `build` & add results there: https://github.com/haskell/haskell-language-server/pull/2567#discussion_r783857102

**Comment by fendor** [comment]
Everything seems to be adressed here
