### ISSUE TITLE
Data.Text.Internal.Fusion.Common.index: Index too large

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-language-server#2602]
### Your environment

Which OS do you use: Ubuntu
Which LSP client (editor/plugin) do you use: VSCode
Describe your project (alternative: link to the project):
bios project with custom `hie.yaml`. I do not believe the project itself is important, but it does use TH.

Noticeably, this HLS version is installed via nix, is based on the hackage release 1.5.1, and applies the patch https://github.com/haskell/haskell-language-server/pull/2359.

### Steps to reproduce

Open HLS and perform some arbitrary editing of files.

### Expected behaviour

HLS should be happy and report diagnostics.

### Actual behaviour

Stops responding and shows no diagnostics any more. Logs contain:
```
haskell-language-server: Data.Text.Internal.Fusion.Common.index: Index too large
CallStack (from HasCallStack):
  error, called at libraries/text/src/Data/Text/Internal/Fusion/Common.hs:943:24 in text-1.2.4.1:Data.Text.Internal.Fusion.Common
```

### Include debug information

Since HLS has been installed via nix, I am not sure at the moment, whether an outdated dependency might cause the issue.
The error was thrown while all non-essential plugins were disabled via the VSCode settings.

**Comment by jneira** [comment]
I've just seen this issue: https://github.com/haskell/haskell-language-server/issues/2149 which is reporting the same error 😟

**Comment by fendor** [comment]
Ah, I knew I've seen this before! Unfortunately, no solution yet.
Going to run with profiling mode to get a proper stack-trace.

**Comment by fendor** [comment]
According to #2149, the first commit with this issue is: https://github.com/haskell/haskell-language-server/commit/9c40dcff1b989b14e05b5aebe96f3da78c6ea25c

**Comment by drsooch** [comment]
Just ran into this. Can't tell when the error fired (wasn't paying attention). I've been working on `TypeLenses.hs` from `ghcide/src/development/ide/plugin/`. On Emacs with all plugins enabled (plus a WIP plugin).

**Comment by fendor** [comment]
Were you using a remote plugin?

**Comment by Bodigrim** [comment]
https://github.com/haskell/haskell-language-server/blob/ffd0f346d88131f0238d266cb59ef2cf21329edb/ghcide/src/Development/IDE/Plugin/Completions/Logic.hs#L733-L736
This is wrong, should be `backtickIndex >= T.length line`.

**Comment by Bodigrim** [comment]
(I'll appreciate if someone else raises a PR)

**Comment by pepeiborra** [comment]
Raised https://github.com/haskell/haskell-language-server/pull/2629

**Comment by fendor** [comment]
At the same time, I raised #2630  :D
