### ISSUE TITLE
Restore consistency in ci using alpine in all workflows

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#2617]
* As commented here: https://github.com/haskell/haskell-language-server/issues/2461#issuecomment-991686414
* Sadly my pessimistic concern has come true and we hit two errors in the alpine build for the release that could have been caught before if the regular test workflow uses the same env to make the build (now uses raw ubuntu):
  * First the inclusion of a new dependency using integer-gmp without flag to switch break the build. Fortunately @maerwald added missing alpine ghc bindists against integer-gmp (see https://github.com/haskell/haskell-language-server/pull/2606#issuecomment-1017227934)
  * And then we have hit a weird bug only present in alpine + ghc-9.2.1 (and no in ubuntu + ghc-9.2.1) (see https://github.com/haskell/haskell-language-server/pull/2615#issuecomment-1017919238)
* So it has become clear that we need restore the consistency between the workflows (including tests and benchmarks) and run all of them on alpine for the linux variant

**Comment by michaelpj** [comment]
I'm *more* worried about the first one. If we're going to force some build configuration (e.g. using `integer-simple`) in some workflow, we should do it in all of them, otherwise things will be inconsistent.

I'm less worried about GHC bugs. They happen from time to time, but it's less likely than solver issues IMO.

**Comment by jneira** [comment]
Well the first one is resolved, as .ghcup downloads ghc versions linked against integer-gmp for all our supported ghc versions. So i removed the particular build configuration for `integer-simple` and afaics the build configuration is the same now between workflows (#2615)

**Comment by jneira** [comment]
> I'm less worried about GHC bugs. They happen from time to time, but it's less likely than solver issues IMO.

More frequent than desirable i am afraid. And more frequent in not so widely used systems like alpine i guess

**Comment by jneira** [comment]
From https://github.com/haskell/haskell-language-server/pull/2615#issuecomment-1018402230

> It worths to note that ghc-9.2.1 in alpine seems to be fragile:
>  * "Alpine segfaults many tests in 9.2.1" https://gitlab.haskell.org/ghc/ghc/-/issues/20266
>  * "Alpine ci job is broken" https://gitlab.haskell.org/ghc/ghc/-/issues/20574

btw, someone has done some dogfooding with the alpine based hls executables? do we know they work for sure? They have not passed the test suite

**Comment by jneira** [comment]
> btw, someone has done some dogfooding with the alpine based hls executables? do we know they work for sure? They have not passed the test suite

you can dowload the executables from the build artifacts: https://github.com/jneira/haskell-language-server/suites/5014931778/artifacts/147473084
i've triggered a build in this repo to make available them here too: https://github.com/haskell/haskell-language-server/actions/runs/1728847536#artifacts (the build still have not finished)

**Comment by jneira** [comment]
Hi,i've tried the linux executable in wsl and when opening a module with template haskell, i get an error in the top of the file:

```
Unexpected usage error
Dynamic loading not supported
```

![imagen](https://user-images.githubusercontent.com/54035/150644276-55c20153-0b9e-40d8-9f1d-48b7bd99110c.png)


And no ide feature is working in the module.
Is this the expected behaviour? hls will directly not work in modules with th?

**Comment by jneira** [comment]
> Is this the expected behaviour? hls will directly not work in modules with th?

cc @wz1000 @pepeiborra 

I am not sure if start the new release as this behaviour would break all Linux uses where th is working now

**Comment by kokobd** [comment]
> i've triggered a build in this repo to make available them here too: https://github.com/haskell/haskell-language-server/actions/runs/1728847536#artifacts (the build still have not finished)

@jneira I tried an executable from here and encountered the exact same error as yours.

My environment:
+ ubuntu 20.04
+ ghc 8.10.7 (installed by ghcup)

**Comment by jneira** [comment]
Will open a pr disabling the fully statically build for linux using alpine if i dont have any confirmation that is the expected behaviour or if it could work with some change here or in the user side

**Comment by Anton-Latukha** [comment]
1. Looked into #2640.

2. Good idea to test on Alpine.
Indeed, if it works in a minimal environment - it should work on the majority of other Linux'es.

3. Would note that Alpine has a caveat, it is not POSIX compliant by default, it relies on `BusyBox` & I encountered problems with that enough times in my former work to be quite aware of it. It seems to work perfectly, until suddenly something changed & it can not find something from GNU Coreutils POSIX support.

Changing from `BusyBox` to GNU Coreutils in `Alpine` - is simple as `apk --no-cache add coreutils`.

**Comment by Anton-Latukha** [comment]
If you want, I can tomorrow switch my scope. Would love to look more into how containers work in GitHub CI. & I used to do a lot of containerization & loved to optimize the use of containers caching, COW deduplication, etc.
