### ISSUE TITLE
positionInRange function in PluginUtils doesn't work as its name suggests

### ISSUE THREAD

**Issue by kokobd** [haskell/haskell-language-server#2618]
Look closely at this function:

https://github.com/haskell/haskell-language-server/blob/b937baa03cf310109aafc0d4835cdff1240ffd3e/hls-plugin-api/src/Ide/PluginUtils.hs#L222-L227

If this range has only 1 line, and the position lies in the same line as the range, but **after** the end of the range, then,
the second branch will fail, but the third branch will succeed, which is not expected, I think.
### Your environment

Which OS do you use:
> Ubuntu 20.04

### Steps to reproduce

I wrote a testcase for that
```
tests :: TestTree
tests = testGroup "PluginUtils"
    [ testCase "positionInRange" $
        positionInRange (Position 1 10) (Range (Position 1 1) (Position 1 3)) @?= False
    ]
```

### Expected behaviour

`Position 1 10` is not in the range of `Position 1 1` and `Position 1 3`. The above testcase should pass.

### Actual behaviour
The testcase fails
![image](https://user-images.githubusercontent.com/16440269/150493479-e8d6db4c-00da-4bbb-a51e-b45fce678c00.png)

**Comment by michaelpj** [comment]
Yikes. A fix would be great. (separately, I should raid `PluginUtils` for stuff to upstream into `lsp` :thinking: )

**Comment by kokobd** [comment]
I will submit a PR later.
