### ISSUE TITLE
Wingman produces ill-typed program with fundeps

### ISSUE THREAD

**Issue by isovector** [haskell/haskell-language-server#2626]
```
class (Functor p, Bifunctor p') => Diss p p' | p -> p' where
  plug :: x -> p' x x -> p x

data Sum2 f g a b = L2 (f a b) | R2 (g a b)
  deriving (Functor, Bifunctor)

instance (Diss f f', Diss g g') => Diss (Sum f g) (Sum2 f' g') where
  plug = _
```

running auto on the hole produces the ill typed:

```
  plug x (L2 f'xx) = plug x f'xx
  plug x (R2 g'xx) = plug x g'xx
```

when instead it should be

```
  plug x (L2 f'xx) = InL (plug x f'xx)
  plug x (R2 g'xx) = InR (plug x g'xx)
```

yikes!

**Comment by zloilya** [comment]
1) note that `BiFunctor` does not used
2) write a more explicit strategy to focus on the bug

```
instance (Diss f f', Diss g g') => Diss (Sum f g) (Sum2 f' g') where
  plug = [wingman|
    intros x y,
    destruct y,
    split, -- lucky boy
    use plug,
    assume x,
    assume f'xx, 
    split, -- generate wrong code :(
    use plug,
    assume x,
    assume g'xx|]
```

the problem I found is that `scoreSolution` generates the same sorting objects from previously generated solutions, so the following 4 solutions are equivalent (InL, InL) (InR, InL) (InL, InR) (InR, InR), the first `split` wins the lottery, the second `split` is unlucky

if you look closely, `scoreSolution` doesn't have much context, maybe we should generate solutions smartly before then? i think no magic can solve it in `scoreSolution`

this code is very similar to ours, but now we also have performance issues (timeout)

```
foo :: (Diss f f', Diss g g') => x -> g' x x -> Sum f g x
foo = _
```
and now your code generates to 

```
plug x (L2 f'xx) = InL (plug x f'xx)
plug x (R2 g'xx) = InL (plug x g'xx)
```

not 

```
plug x (L2 f'xx) = plug x f'xx
plug x (R2 g'xx) = plug x g'xx
```

**Comment by isovector** [comment]
Thanks for the nice repro @zloilya!
