### ISSUE TITLE
Export action on type family exports with constructors (Tyfam(..))

### ISSUE THREAD

**Issue by googleson78** [haskell/haskell-language-server#2635]
### Your environment
HLS version:
1.5.1
Which OS do you use:
Debian
Which LSP client (editor/plugin) do you use:
LanguageClient-neovim
```yaml
resolver: nightly-2021-09-12
```
### Steps to reproduce
Add a file with a type family, with an empty export list. Use the "export definition" action on the type family. HLS generates an export with exported constructors, even though type families don't have constructors.

### Expected behaviour
An export without constructors.

### Actual behaviour
An export with constructors, which don't exist, causing an additional warning.

**Comment by drsooch** [comment]
https://github.com/haskell/haskell-language-server/blob/f62ec3ec76bd972395a40689bb60c8e6c11957c3/ghcide/src/Development/IDE/Plugin/CodeAction.hs#L602-L617

Looks like type families default to having `(..)`. Even the test in `ghcide/test/exe/Main.hs` expects there to be `(..)`.

**Comment by drsooch** [comment]
That being said I tested quickly myself and I was able to export a TypeFamily with `(..)` with no errors. This was on `8.10.7` not sure if it's something new.

**Comment by googleson78** [comment]
It triggers a warning, I believe this one - https://downloads.haskell.org/ghc/latest/docs/html/users_guide/using-warnings.html#ghc-flag--Wdodgy-exports
