### ISSUE TITLE
Revise handling of files with local encoding

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#2641]
* #2637 assumes file encoding must be utf8, but almost surely that assumption was present in the codebase before that
* Most users will be using utf8 and there is no issues about this afaik but maybe it worths to give a try using a local encoding (pre and post #2637), verify hls does not work with local encoding and try to detect and warn users about with a lsp alert and noting it explicitly  in docs

**Comment by Bodigrim** [comment]
> #2637 assumes file encoding must be utf8, but almost surely that assumption was present in the codebase before that

As I said in #2637, we do not assume anything which is not yet implied by GHC, which [requires file encoding to be UTF-8](https://downloads.haskell.org/ghc/9.2.1/docs/html/users_guide/separate_compilation.html?highlight=utf#haskell-source-files).

**Comment by jneira** [comment]
Oh, thanks for the info, closing this then
