### ISSUE TITLE
Fix gitlab alpine build tar generation

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#2648]
* From https://github.com/haskell/ghcup-metadata/pull/19#issuecomment-1024623281 and posterior comments
* Options:
  * Enable decomprenssing old formats in the lib (needs new ghcup release)
  * Try to generate a "good" tar in alpine
  * Generate the tar in other linux distro

//cc @hasufell

**Comment by hasufell** [comment]
> Generate the tar in other linux distro

Yes
