### ISSUE TITLE
Automate manual steps of the gitlab release

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#2663]
The actual manual steps are:
1. download the six extra tarballs
2. download GitHub SHA256SUMS
3. compute the `sha256sum --tag haskell-language-server* >> SHA256SUMS`
4. upload the new six tarballs and replace SHA256SUMS in the GitHub release

so we have to find a way to

  * - [ ] download SHA256SUMS from GitHub to gitlab machine using GH API
  * - [ ] update it with all new checksums (maybe in one unique env which should access tarballs from all jobs)
  * - [ ] upload all artifacts to GitHub release using GH api (will need a GH Auth token in secrets)

cc @hasufell

**Comment by hasufell** [comment]
https://stackoverflow.com/questions/37786539/how-to-upload-github-asset-file-using-curl

**Comment by hasufell** [comment]
Storing secrets in gitlab seems to be a bit more annoying: https://gitlab.haskell.org/help/ci/secrets/index.md
