### ISSUE TITLE
This HLS binary does not support Template Haskell

### ISSUE THREAD

**Issue by why-not-try-calmer** [haskell/haskell-language-server#2666]
### Your environment
Which OS do you use:
Pop!_OS + Nix.

### Steps to reproduce
Launch VSCode with the current (latest) workspace (my project does make use of Template Haskell). All was fine with I think the one before the last version of the extension. It's still mostly fine -- everything works, this annoying popup notwithstanding.

### Expected behaviour
No error.

### Actual behaviour
`This HLS binary does not support Template Haskell`.

### Include debug information
```
No 'hie.yaml' found. Try to discover the project type!
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper-1.6.1.0-linux) Version 1.6.1.0, Git revision f4022c5bb8530cd306c53b941878244bf27a5d41 (dirty) x86_64 ghc-8.10.7
Current directory: /home/hades/haskell/feedfarer
Operating system: linux
Arguments: ["--debug"]
Cradle directory: /home/hades/haskell/feedfarer
Cradle type: Stack

Tool versions found on the $PATH
cabal:          Not found
stack:          2.7.3
ghc:            Not found

Consulting the cradle to get project GHC version...
Project GHC version: 8.10.7
haskell-language-server exe candidates: ["haskell-language-server-8.10.7","haskell-language-server"]
Cannot find any haskell-language-server exe, looked for: haskell-language-server-8.10.7, haskell-language-server
```

**Comment by jneira** [comment]
@why-not-try-calmer hi, thanks for the report. 
That alert was added on purpose cause prebuilt hls binaries dont work with template haskell in a reliable way *in general*
So maybe in your environment th worked and continue doing so.
You can see the rationale here (and the long list of linked issues around th): https://github.com/haskell/haskell-language-server/issues/1431
The issue about adding such alert was: https://github.com/haskell/haskell-language-server/issues/2391
And we have opened a general issue about the warning here: https://github.com/haskell/haskell-language-server/issues/2659

**Comment by why-not-try-calmer** [comment]
@jneira @fendor Thank you very much for your quick and helpful replies. I have two more questions about VSCode, I hope it's not too late to post them here.

As a Linux guy I don't mind compiling stuff but I am a bit concerned about the UX here. I mean, I am using HLS via a VSCode precisely because I want to make the list of things I need to micromanage _shorter_, not longer. Is there an option to allow VSCode users to not have to worry about this at all, or at least, make the process much streamlined, as in "Hello, you'll need to run <stack build ... | cabal install ...> if you want to fix HLS and make this alert disappear."

Also a related but more general question: does that mean that the user is expected to rebuild from source with every update to their HLS VSCode extension?

**Comment by jneira** [comment]
> Is there an option to allow VSCode users to not have to worry about this at all, or at least, make the alert more actionable, as in "Hello, you'll need to run <stack build ... | cabal install ...> if you want to fix HLS and make this alert disappear." ?

Agree with you but the build instructions are complex enough (specially if you want to use more than one ghc version) to not fit an alert i am afraid. You could use cabal, stack or nix or other build system. Now it has a link where you can consult the rationale and instructions:

https://user-images.githubusercontent.com/26626/145691163-11d0c2b5-2dd6-4aef-9299-1d86a16caf23.mov

> Also a related but more general question: does that mean that the user is expected to rebuild from source with every update to their HLS VSCode extension?

vscode uses a client/server design so update the extension and the server (hls) are separated things.
But you will need to build hls each time a new version of hls (not the extension) is released, if you want the new features and bug fixes, yeah. And we have almost all ide logic in the server.

**Comment by jneira** [comment]
@why-not-try-calmer if you dont mind i am gonna close this one as we have a general issue about (the mentioned #2659)
This issue has the concrete message in the title and that makes it more discoverable so i am gonna update the title of #2659 to include it, thanks!

**Comment by why-not-try-calmer** [comment]
I don't mind and your reply makes sense. Thanks!

**Comment by why-not-try-calmer** [comment]
Oh if I may @jneira perhaps one very last think: if I am user interacting from HLS from the HSL VSCode extension, I am not supposed to find any HLS binary on my system _except for_ e.g. `~/.config/Code/User/globalStorage/haskell.haskell`, correct? In which case running `stack install haskell-language-server --stack-yaml=stack-${ghcVersion}.yaml --ghc-options="-dynamic"` as per the instructions you mentioned (for a `stack` user) will get me a "duplicated" config, where I'll still have old stuff under `..Code/User..` and have new stuff under `~/.stack..`, correct?

**Comment by jneira** [comment]
> Does this entail that manually building + removing leftovers is what I should expect to be doing with every new release from HLS, under the assumptions above?

well, the vscode extension uses the hls on `$PATH` as first option and dont even tries to download it. So after deleting old versions in  `..Code/User..` you should not have to do it again, while you keep a hls on `$PATH`

**Comment by why-not-try-calmer** [comment]
Sorry to ping @jneira but on a different machine affected by the same issue I am getting:
```
Error: While constructing the build plan, the following exceptions were
encountered:

In the dependencies for haskell-language-server-1.6.1.1:
    ghcide must match ==1.6.*, but the stack configuration has no specified
           version  (latest matching version is 1.6.0.1)
    hiedb needed, but the stack configuration has no specified version  (latest
          matching version is 0.4.1.0)
    hls-alternate-number-format-plugin must match ^>=1.0.0.0, but the stack
                                       configuration has no specified version 
                                       (latest matching version is 1.0.1.0)
    hls-brittany-plugin must match ^>=1.0.0.1, but the stack configuration has
                        no specified version  (latest matching version
                        is 1.0.2.0)
    hls-call-hierarchy-plugin must match ^>=1.0.0.0, but the stack configuration
                              has no specified version  (latest matching version
                              is 1.0.2.0)
    hls-class-plugin must match ^>=1.0.0.1, but the stack configuration has no
                     specified version  (latest matching version is 1.0.2.0)
    hls-eval-plugin must match ^>=1.2.0.0, but the stack configuration has no
                    specified version  (latest matching version is 1.2.1.0)
    hls-explicit-imports-plugin must match ^>=1.0.0.1, but the stack
                                configuration has no specified version  (latest
                                matching version is 1.0.2.0)
    hls-floskell-plugin must match ^>=1.0.0.0, but the stack configuration has
                        no specified version  (latest matching version
                        is 1.0.1.0)
    hls-fourmolu-plugin must match ^>=1.0.0.0, but the stack configuration has
                        no specified version  (latest matching version
                        is 1.0.2.0)
    hls-graph needed, but the stack configuration has no specified version 
              (latest matching version is 1.6.0.0)
    hls-haddock-comments-plugin must match ^>=1.0.0.1, but the stack
                                configuration has no specified version  (latest
                                matching version is 1.0.1.0)
    hls-hlint-plugin must match ^>=1.0.0.2, but the stack configuration has no
                     specified version  (latest matching version is 1.0.3.0)
    hls-module-name-plugin must match ^>=1.0.0.0, but the stack configuration
                           has no specified version  (latest matching version
                           is 1.0.1.0)
    hls-ormolu-plugin must match ^>=1.0.0.0, but the stack configuration has no
                      specified version  (latest matching version is 1.0.2.0)
    hls-plugin-api must match ==1.3.*, but the stack configuration has no
                   specified version  (latest matching version is 1.3.0.0)
    hls-pragmas-plugin must match ^>=1.0.0.0, but the stack configuration has no
                       specified version  (latest matching version is 1.0.2.0)
    hls-qualify-imported-names-plugin must match ^>=1.0.0.0, but the stack
                                      configuration has no specified version 
                                      (latest matching version is 1.0.1.0)
    hls-refine-imports-plugin must match ^>=1.0.0.0, but the stack configuration
                              has no specified version  (latest matching version
                              is 1.0.1.0)
    hls-retrie-plugin must match ^>=1.0.0.1, but the stack configuration has no
                      specified version  (latest matching version is 1.0.2.0)
    hls-selection-range-plugin must match ^>=1.0.0.0, but the stack
                               configuration has no specified version  (latest
                               matching version is 1.0.0.0)
    hls-splice-plugin must match ^>=1.0.0.1, but the stack configuration has no
                      specified version  (latest matching version is 1.0.1.0)
    hls-stylish-haskell-plugin must match ^>=1.0.0.0, but the stack
                               configuration has no specified version  (latest
                               matching version is 1.0.1.0)
    hls-tactics-plugin must match >=1.2.0.0 && <1.7, but the stack configuration
                       has no specified version  (latest matching version
                       is 1.6.1.0)
needed since haskell-language-server is a build target.

Some different approaches to resolving this:

  * Recommended action: try adding the following to your extra-deps
    in /home/hades/.stack/global-project/stack.yaml:

- ghcide-1.6.0.1@sha256:302154f6d70ea82fa2c66c87a2221cfec841dd05f8bc7d1ea836f418ea48d434,13549
etc., etc.
```
Any clue?
