### ISSUE TITLE
1.6.1.0 cli execution doesn't work

### ISSUE THREAD

**Issue by googleson78** [haskell/haskell-language-server#2672]
### Your environment

Which OS do you use:
Debian testing
Which LSP client (editor/plugin) do you use:
Raw invocation
Describe your project (alternative: link to the project):
https://github.com/polysemy-research/polysemy

HLS 1.6.1.0 from ghcup
```sh
> haskell-language-server-wrapper --version
haskell-language-server version: 1.6.1.0 (GHC: 8.10.7) (PATH: /home/googleson78/.ghcup/bin/haskell-language-server-wrapper-1.6.1.0) (GIT hash: f4022c5bb8530cd306c53b941878244bf27a5d41)
```

### Steps to reproduce
Clone the project and run `haskell-language-server-wrapper`

### Expected behaviour
Loads the project.

### Actual behaviour
Fails with multiple instances of something like
```
  Maybe.fromJust: Nothing
  CallStack (from HasCallStack):
  error, called at libraries/base/Data/Maybe.hs:148:21 in base:Data.Maybe
  fromJust, called at src/Development/IDE/Core/Rules.hs:842:51 in
  ghcide-1.6.0.0-inplace:Development.IDE.Core.Rules
```

### Include debug information
[hls.log](https://github.com/haskell/haskell-language-server/files/7977592/hls.log)
[hls-stderr.log](https://github.com/haskell/haskell-language-server/files/7977599/hls-stderr.log)

**Comment by fendor** [comment]
I can reproduce it on the cli as described, but in VSCode everything seems to be fine 0.o.

**Comment by googleson78** [comment]
Has calling the cli perhaps gotten more complicated in some way? (some env needs to be provided etc)

**Comment by jneira** [comment]
@googleson78 does it work for you in the editor?

**Comment by googleson78** [comment]
Yup, thanks. I didn't even try it in an editor when I saw the cli invocation doesn't work tbh. 

I rely on the cli invocation to provide debug info and to also to troubleshoot issues if something isn't working from inside my editor. What do I need to do to be able to use it?

**Comment by fendor** [comment]
It should work, so there is at least one bug somewhere. 

I can trigger the same error on the hie-bios code-base, but everything *seems* to load fine, so this is likely to be a bug in the cli loader.

**Comment by solomon-b** [comment]
FYI I also am hitting this bug and am not using polysemy:

```
Hidden:   no
Range:    1:1-2:1
Source:   compiler
Severity: DsError
Message: 
  Maybe.fromJust: Nothing
  CallStack (from HasCallStack):
  error, called at libraries/base/Data/Maybe.hs:148:21 in base:Data.Maybe
  fromJust, called at src/Development/IDE/Core/Rules.hs:842:51 in
  ghcide-1.6.0.0-7wqffKHWPjBDdiU2g7XF1:Development.IDE.Core.Rules
2022-02-10 13:05:16.955923575 [ThreadId 57] INFO hls:	finish: User TypeCheck (took 0.12s)
2022-02-10 13:05:16.956033454 [ThreadId 114] DEBUG hls:	LOOKUP UP PERSISTENT FOR: GetModSummaryWithoutTimestamps
2022-02-10 13:05:16.956072025 [ThreadId 114] DEBUG hls:	LOOKUP UP PERSISTENT FOR: False
2022-02-10 13:05:16.956123559 [ThreadId 111] INFO hls:	finish: GetHie (took 0.00s)
2022-02-10 13:05:16.956229608 [ThreadId 116] INFO hls:	finish: GenerateCore (took 0.00s)
Files that failed:
 * /home/solomon/Development/hasura/graphql-engine-mono/pro/server/src/HasuraPro/App.hs

Completed (0 files worked, 1 file failed)
haskell-language-server-wrapper: callProcess: /nix/store/sznd4vbnba0iyl08p3wqp9k4jj3db9li-haskell-language-server-1.6.1.0/bin/haskell-language-server-8.10.7 "pro/server/src/HasuraPro/App.hs" "--debug" (exit 1): failed
```

**Comment by dschrempf** [comment]
I am also getting this error message independent of `polysemy`.

```
2022-02-15 10:58:09.561056426 [ThreadId 463] INFO hls:	File:     /home/dominik/Shared/haskell/circular/src/Data/Stack/Circular.hs
Hidden:   no
Range:    1:1-2:1
Source:   compiler
Severity: DsError
Message:
  Maybe.fromJust: Nothing
  CallStack (from HasCallStack):
  error, called at libraries/base/Data/Maybe.hs:148:21 in base:Data.Maybe
  fromJust, called at src/Development/IDE/Core/Rules.hs:842:51 in
  ghcide-1.6.0.0-7wqffKHWPjBDdiU2g7XF1:Development.IDE.Core.Rules
```

**Comment by googleson78** [comment]
I amended the title to represent the fact that this seems independent of polysemy.

**Comment by kamek-pf** [comment]
Same here, no Polysemy either, although in my case I can no longer get it to work with any editor.

**Comment by hasufell** [comment]
This bug happens only if you don't run in lsp mode.

The reason is here: https://github.com/haskell/haskell-language-server/blob/f4022c5bb8530cd306c53b941878244bf27a5d41/ghcide/src/Development/IDE/Core/Rules.hs#L842

`lspEnv` is `Nothing` for non-lsp initializations:
* https://github.com/haskell/haskell-language-server/blob/96ea854debd92f9a54e2270b9b9a080c0ce6f3d1/ghcide/src/Development/IDE/Main.hs#L355
* https://github.com/haskell/haskell-language-server/blob/96ea854debd92f9a54e2270b9b9a080c0ce6f3d1/ghcide/src/Development/IDE/Main.hs#L409
