### ISSUE TITLE
Support for COMPLETE pragma pattern matching.

### ISSUE THREAD

**Issue by lsmor** [haskell/haskell-language-server#2690]
**Wingman does not case split in pattern synonyms with COMPLETE pragma***

`COMPLETE` pragma allows to define exhaustive cases for a pattern synonym, which is quite handy sometimes. The problem is that wingman uses the internal representation of the type instead of cases defined by the pragma. Below an example:

```haskell
-- Imagine a Tic-tac-toe game in which we define Cell using a pattern synonym as a String.
type Cell  = String
pattern Empty:: Cell
pattern Empty = ""
pattern O :: Cell
pattern O = "O"
pattern X :: Cell
pattern X = "X"
{-# COMPLETE Empty, O, X #-}

-- HLS does warn an incomplete pattern match. So this is ok. 
shout :: A -> String
shout O = O ++ "!"

-- If we try Wingman to split cases using case split on a action
shout :: A -> String
shout a = _

-- returns this
shout :: A -> String
shout [] = _wf
shout (c : s) = _wg
```

**Describe the solution you'd like**

In the case above wingman should return 

```haskell
shout :: A -> String
shout Empty = _wf
shout O = _wg
shout X = _wh
```

Thanks! I am glad to contibute if this is a good-for-newcomers issue.

**Comment by isovector** [comment]
Interesting idea! I think we'd need some further specification to move forward on this:

1. what if there are multiple `COMPLETE` pragmas for the same type?
2. should we always use a `COMPLETE` if it's available?

**Comment by lsmor** [comment]
> 1. what if there are multiple `COMPLETE` pragmas for the same type?


So you mean the following situation isn't it?

```haskell
type Cell  = String
pattern Empty:: Cell
pattern Empty = ""
pattern O :: Cell
pattern O = "O"
pattern X :: Cell
pattern X = "X"
{-# COMPLETE Empty, O #-}
{-# COMPLETE Empty, X #-}
```
Ideally we could prompt the user about which COMPLETE wants to use. something like "case split on <var> with Empty, O" and "case split on <var> with Empty, X" instead of current "case split on <var>". Of course in case of very large set of cases, It'd be very auwful. But It could be an option.

> 2. should we always use a `COMPLETE` if it's available?

I think so, since the intention of `COMPLETE` is to behave like a sum type. I can't think any case in which the internal representation if prefered over the "abstracted" one. Do you have something in mind?

**Comment by isovector** [comment]
Sometimes complete patterns give an alternate way of looking at a data structure, not necessarily a more abstract one! But if the idea is to give a code action for every possible set of complete destructors, we could just add the internal version to that list.

**Comment by isovector** [comment]
I have half of a MVP implementation here https://github.com/haskell/haskell-language-server/compare/completes?expand=1

There are a few challenges:

1. GHC <9.2 uses a representation of `CompleteMatch`es which contain `Name`s, not `ConLike`s
2. Thus we need to get the `ConLike`s ourselves
3. but `Development.IDE.Core.Compile.lookupName` isn't finding them, at least ones defined in the current module
4. the tactics LSP data payload has no place to put the COMPLETE set you'd like

1 and or 3 are the hard bits; everything else should mostly fall into place
