### ISSUE TITLE
Issues with hls in vscode on Mac

### ISSUE THREAD

**Issue by KristianBalaj** [haskell/haskell-language-server#2695]
Hey!
Just watching the last video from @rae and he is having hard times with the HLS in VSCode so you could maybe give it a check and maybe try to find the issue and optionally fix it for the future :)

Here is the last video https://www.youtube.com/watch?v=C7-5y3sv_m4
It is approximally from 6:00-10:30

**Comment by drsooch** [comment]
He actually opened https://github.com/haskell/haskell-language-server/issues/2691 to track this issue.
