### ISSUE TITLE
Add uninstallation instructions

### ISSUE THREAD

**Issue by bubba** [haskell/haskell-language-server#271]
Just noticed in the traffic tab of the insights page on GitHub, one of the top links on the repository was a search for uninstall lol
<img width="460" alt="image" src="https://user-images.githubusercontent.com/2488460/89121185-a6735700-d4b4-11ea-9042-9f7ade41967d.png">

We should probably include in the README some basic instructions on how to uninstall, i.e. just deleting `~/.local/bin/haskell-language-server*` or `~/.cabal/bin/haskell-language-server*`

**Comment by jneira** [comment]
We should add instructions on how to clean the executables downloaded by the vscode extension

**Comment by lichever** [comment]
Hi, do you know how to uninstall Haskell-language-server?

**Comment by jneira** [comment]
It depends on how you install it: with `cabal install` from hackage or source, `stack install` from source, ghcup, automatic downloaded binaries by the vscode extension...
If you have used one method to install the paths would be those ones, yeah

**Comment by lichever** [comment]
Hi @jneira, Thanks! I am new to Haskell. When installing Haskell by using [ghcup](curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh),  there was a prompt for installing the Haskell-language-server and then I installed it. I am not sure if I can use the way posted here to uninstall it?

**Comment by jneira** [comment]
It seems there is a `ghcup rm xxx` that should do what do you want, with `ghcup rm haskell-language-server` i guess. I cant check locally cause i am on windows 🙂

**Comment by lichever** [comment]
@jneira Thanks a lot! It seems it works.

**Comment by fendor** [comment]
Since GHCup now takes care of the installation and is transparent in how to do it, and the install script has been deleted, so there should be no ambiguity left
