### ISSUE TITLE
monthly release?

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-language-server#272]
We did a release 5 days ago.

According to our "normal" schedule we should be pushing out 0.3 around now.

Should we? 

Pros - gets us back on the cadence
Cons - we just did a release

cc @bubba @fendor @jneira @pepeiborra @wz1000

**Comment by Ailrun** [comment]
I prefer not to release now, as there were only few updates that really matter after the 0.2.2... Most of commits are about repository management or so.

**Comment by pepeiborra** [comment]
What is the normal schedule? A major release every 2 weeks?

What are the steps to make a release? How much automation is there?

If we can merge and release the retrie plugin, that would be pretty cool.

**Comment by alanz** [comment]
@pepeiborra The normal schedule with hie was once a month, around this time of the month.  The logic is that a regular cadence makes more sense than some kind of big-bang release, as there is continuous improvement over the month.

**Comment by Anrock** [comment]
How about just skipping this one and calling the previous one as "a lil bit too early montly-release"?

**Comment by fendor** [comment]
We should probably think about more automation in the release process.

Do we want to keep these minor version releases? Maybe once in the middle of the month?


Personally, I dont feel strongly, keeping the cadence is fine by me, we have some bug fixes for ormolu right?

**Comment by alanz** [comment]
> Do we want to keep these minor version releases? Maybe once in the middle of the month?

I would say we should not have them as a regular feature. This month we needed them to trigger and debug the static binary download porcess.

Every release we do pushes a burden to the downstream people, in terms of packaging and the like.  This is why I like to keep a simple cadence, people can align their processes to ours.

**Comment by bubba** [comment]
Now that the retrie plugin is in, I think we have enough features now to warrant a release

**Comment by alanz** [comment]
Retrie is in, and the new hls-3 branch. So I reckon a new release

@pepeiborra are there any retrie follow-ups that need to go in, within a day or so?

**Comment by pepeiborra** [comment]
I'm not working on any further retrie changes at the moment.

**Comment by bubba** [comment]
@alanz if possible I'd like to get #289 and the fix for #221 in for this release, hopefully I should have the latter done today

**Comment by alanz** [comment]
@bubba that is fine.

And if you have the time/are able, would you like to do the release too?  It is not clear how it ties in to the vscode extension, better for you to shepherd it until we have a solid howto/automation.

**Comment by bubba** [comment]
0.3.0 is released now
