### ISSUE TITLE
A logging backend that sends some logs to client

### ISSUE THREAD

**Issue by eddiemundo** [haskell/haskell-language-server#2729]
https://github.com/haskell/haskell-language-server/pull/2558#issuecomment-1046327872

> For future work, we should have a logging backend that forwards some LSP messages (encoded as JSON values) to the LSP stream for testing invariants.

Which I think is related to https://github.com/haskell/haskell-language-server/pull/2558#issuecomment-1003634182
```
let eitherFormatOrInit =
          asum
            [ Left
                <$> satisfyLog
                  ( \case
                      KnownTargets.LogGetSigmaTargetsResult {} -> pure ()
                      _ -> empty
                  )
            , Right <$> responseForId STextDocumentFormatting rid
            ]
    res <- skipManyTill anyMessage eitherFormatOrInit
   ...
```

How I understand this is we want a `Recorder` that sends some subset of logs to the client by converting them to JSON, sending them using a custom LSP message, then converting them back to the `Log` type so we can inspect them in client tests.

I'm not certain how exactly the mechanics of choosing log messages to send will work.

**Comment by pepeiborra** [comment]
The test chooses which messages get sent, by crafting a priority function

**Comment by michaelpj** [comment]
We did this
