### ISSUE TITLE
Feature: Quick fix to add all constructors to the import list

### ISSUE THREAD

**Issue by ejconlon** [haskell/haskell-language-server#2734]
Wingman case splits (which are amazing) often introduce many constructors that are not imported yet. Often one wants to do a wildcard import of all constructors, but the quick fix for imports only adds one constructor at a time to the import list. (Example: `Add MyDataType(MyFirstConstructor) to the import list...`) Quite often I just quick fix once, scroll up to the imports, and replace with `..`, which disrupts the flow of development. It would be nice to have a second quick fix option to add all constructors to the import list. (Example: `Add MyDataType(..) to the import list...`)

As always, apologies if I missed an existing issue for this, and thanks for the wonderful project.

**Comment by July541** [comment]
We can close it if no more work on it.
