### ISSUE TITLE
Attach windows binaries for ghc 8.8.4

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#276]
As it is difficult to make ci generate those windows binaries but it is doable locally, i think we could try to attach my local windows versions.
I am gonna follow the naming conventions of the existing ones and attach them manually asap, if no one disagree.

/cc @bubba

**Comment by bubba** [comment]
That would be perfect!

**Comment by jneira** [comment]
I've attached binaries in the 0.2.2 release:
* https://github.com/haskell/haskell-language-server/releases/download/0.2.2/haskell-language-server-Windows-8.8.3.exe.zip
* https://github.com/haskell/haskell-language-server/releases/download/0.2.2/haskell-language-server-Windows-8.8.4.exe.zip

I would keep this open to track the manual upload of those versions, while they are not available via ci

**Comment by bubba** [comment]
Is 8.8.2 completely unbuildable on windows?

**Comment by jneira** [comment]
it was last time i tried it but not sure it it worths the time to try it again: two minor versions released and 5 months since the last 8.8.2 stackage lts

**Comment by bubba** [comment]
@jneira I’ve kicked off the [0.3.0 pre-release](https://github.com/haskell/haskell-language-server/releases/tag/0.3.0), whenever you're able can you upload some windows binaries for ghc-8.8.3 and 8.8.4 at some point?

**Comment by jneira** [comment]
Sure, i'll upload them asap

**Comment by jneira** [comment]
@bubba done!

**Comment by bubba** [comment]
Hi @jneira , @alanz has made the 0.4.0 release could you upload some binaries for those on 8.8.4 and 8.8.3 as well?

**Comment by jneira** [comment]
Sure i uploaded 8.8.3, 8.8.4 and 8.10.2 last night

**Comment by alanz** [comment]
Can we close this?

**Comment by jneira** [comment]
Well, we will need to upload manually windows versions hard to install in a ci env. 
Stackage is using 8.8.4 for lts and 8.10.2 for nightly (with a windows workaround) so there is chances that users will need them.
I would continue uploading until newer versions are released and stackage is updated to use them.

**Comment by alanz** [comment]
Oops, sorry, I thought this related to the 0.4.0 tag specifically.

**Comment by bubba** [comment]
@jneira 0.5.0 has been tagged, can you upload some binaries again whenever you're free? https://github.com/haskell/haskell-language-server/releases/tag/0.5.0

Btw, should we be also bumping hls-plugin-api to 0.5.0?

**Comment by jneira** [comment]
I did a diff between master and 0.4.0 and there is no differences, I will double check it just in case

**Comment by jneira** [comment]
* binaries for hls-0.5.0 already uploaded

**Comment by bubba** [comment]
@jneira can you do binaries for 0.5.1 at some point?

**Comment by jneira** [comment]
yeah, but I will not able to do it until tomorrow at night (UTC)

**Comment by bubba** [comment]
@jneira No rush, once you upload them can you uncheck the pre-release button? Thanks again as always!

**Comment by jneira** [comment]
@bubba uploaded and pre button unchecked!

**Comment by jneira** [comment]
Added missing windows binaries for 0.6.0

**Comment by jneira** [comment]
As we added 8.10.2 to cu, that version not need to be generated locally

**Comment by jneira** [comment]
To alliviate the manual generation of binaries i popose drop support for the ghc-8.8.3 binary and only relase ghc-8.8.4.
If nobody disagree i will do it in the next release.

**Comment by alanz** [comment]
Sounds good to me

**Comment by Ailrun** [comment]
Also agreed.

**Comment by Ailrun** [comment]
@jneira Could you upload HLS-8.8.4 for Windows?

**Comment by jneira** [comment]
my laptop is on heat, i ll try to upload it this evening gmt

**Comment by jneira** [comment]
This time i am not able to install hls for ghc-8.8.4, it fails continously with segfaults building floskell.
@Ailrun Maybe we should make definitive the release and hope not many windows users continue being using ghc-8.8.4
I'll will continue trying

**Comment by Ailrun** [comment]
Hm... does it work without floskell?

**Comment by jneira** [comment]
> Hm... does it work without floskell?

I want to try some tricks including it to get the full build but that is a good alternative if everything else fails.
However i did not want make rest of users continue waiting and ghc-8.10.4 is a good version for windows so we always can suggest upgrade it.
The release has been made public via ghcup and vscode users still cant upgrade so...

**Comment by Ailrun** [comment]
> However i did not want make rest of users continue waiting and ghc-8.10.4 is a good version for windows so we always can suggest upgrade it.

Agreed. I will make the pre-release be a real release.

**Comment by jneira** [comment]
@Ailrun many thanks, i *know* make the release can be a little bit stressing and you have done a perfect work :smile:

**Comment by Ailrun** [comment]
@jneira it's all my words, thank you for all your help for the release :)

**Comment by Ailrun** [comment]
If we can create a binary reliably with that setting, how about put things back to Github Actions?

**Comment by jneira** [comment]
mmm iirc in the CI windows environment the bug is more persistent, but maybe could work (the script would be more complex though)

**Comment by jneira** [comment]
I am installing locally 1.2.0 for ghc-8.8.4

**Comment by jneira** [comment]
This time i am not able to avoid the segfault easily, i am trying with 

```
package floskell
    ghc-options: -O0
```

😟

**Comment by jneira** [comment]
No need for more manual builds thanks to #2199
