### ISSUE TITLE
Abbreviate explicit import code lenses

### ISSUE THREAD

**Issue by michaelpj** [haskell/haskell-language-server#2765]
It's cool that the code lens shows the code that will be present after the change, but for imports that import a lot of things, the resulting code lens is *massive*. In some cases I've had it occupy most of or all of my editor's viewport, which is pretty annoying. This also causes problems in some clients that don't deal so well with massive code lenses (e.g. https://github.com/emacs-lsp/lsp-haskell/issues/137).

I hypothesise that nobody really needs to see exactly what's going to be inserted by this code lens. I think it could be abbreviated:
- Radically, just show "Make this import fully explicit"
- Less radically, show "import Foo (<49 items>)" or something

**Comment by michaelpj** [comment]
Here's the offending site: https://github.com/haskell/haskell-language-server/blob/master/plugins/hls-explicit-imports-plugin/src/Ide/Plugin/ExplicitImports.hs#L277

**Comment by michaelpj** [comment]
I'm happy to do this one, I just wanted to check that nobody really loves the existing behaviour!

**Comment by jhrcek** [comment]
I agree with your proposed behavior, I'd prefer the 2nd option "import Foo (<49 items>)" IF the list of items is too long.
But would still like to see the actual import items if there are say less than 10 items.

**Comment by pepeiborra** [comment]
That is indeed the motivation for the lenses: showing the explicit imports at a glance, without necessarily recording them in the file. Instead of showing the number of items, I would suggest cropping the list after 80 cols (or some other arbitrary number)

**Comment by michaelpj** [comment]
So you're suggesting something like this, @pepeiborra ?
```
-- pretend C occurs at 80 chars
import Foo (A, B, C
```
or this?
```
import Foo (A, B, C,...
```

I do think it's nice to have the count when it's truncated, since you might e.g. not want to make the import explicit if it has 100 items, but then once it's cropped you don't know how many there are.

So how about this?
```
import Foo (A, B, C... 32 more items
``

**Comment by pepeiborra** [comment]
Best of both worlds. Perfect.

**Comment by jhrcek** [comment]
`import Foo (A, B, C... (32 more items))` is my favorite too.
