### ISSUE TITLE
Add support for GHC 9.2.2 

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#2771]
We need to add support for GHC 9.2.2 before the 1.7.0 release.

_Originally posted by @pepeiborra in https://github.com/haskell/haskell-language-server/issues/2739#issuecomment-1063399678_

**Comment by hasufell** [comment]
9.2.2 is [broken on windows](https://gitlab.haskell.org/ghc/ghc/-/issues/21196) ... not sure it's worth the support.

**Comment by pepeiborra** [comment]
Oh dear. Thanks for the heads up, I guess we can go ahead with the release.

**Comment by Eason0210** [comment]
I just install GHC 9.2.2 on Windows 10 with ghcup, and it works.

```
➜ ~  which ghc
C:\ghcup\bin\ghc.exe
➜ ~  ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.2.2
```

**Comment by hasufell** [comment]
> I just install GHC 9.2.2 on Windows 10 with ghcup, and it works, not broken.
> 
> ```
> ➜ ~  which ghc
> C:\ghcup\bin\ghc.exe
> ➜ ~  ghc --version
> The Glorious Glasgow Haskell Compilation System, version 9.2.2
> ```

The only way this works is that you have `msys2` in PATH, which can create numerous other problems on your system.

**Comment by Eason0210** [comment]
> The only way this works is that you have `msys2` in PATH

@hasufell You are right, I do have `msys2` in my path.

**Comment by nrolland** [comment]
Stackage is on 9.2.2 now. It would be nice to have HLS targeting the same version.

**Comment by hasufell** [comment]
> Stackage is on 9.2.2 now. It would be nice to have HLS targeting the same version.

Nightly stackage, not LTS. That mean it's experimental.

**Comment by nrolland** [comment]
Not sure it is experimental, it's a set of package that compile.
It is valuable to have popular tools working together.

They say they'll upgrade to 9.2.3 soon enough it's out though.
https://www.stackage.org/blog/2022/03/announce-lts-19-nightly-ghc9.2

**Comment by georgefst** [comment]
Presumably this is closed by https://github.com/haskell/haskell-language-server/pull/2787?
