### ISSUE TITLE
Provide All Alternate Number Formats regardless of Enabled Language Extensions

### ISSUE THREAD

**Issue by drsooch** [haskell/haskell-language-server#2772]
Currently, the alternate number format plugin only suggests formats when the Language Extension is enabled. 

So for example, with Haskell2010 set as the default language, the literal `15` will provide `0xF` and `0o17` as alternatives. 

With `BinaryLiterals` enabled the literal `15` will provide `0xF`, `0o17`, and `0b1111`. 

Instead the provided alternatives should span all possible formats and add the language extension if not already enabled.

**Comment by michaelpj** [comment]
Maybe we can include a note in the code action title when we need an extension, "Convert to 0xF (needs BinaryLiterals)" or something.
