### ISSUE TITLE
How to prevent inserting a space after the type?

### ISSUE THREAD

**Issue by Eason0210** [haskell/haskell-language-server#2786]
### Discussed in https://github.com/haskell/haskell-language-server/discussions/2785

<div type='discussions-op-text'>

<sup>Originally posted by **Eason0210** March 16, 2022</sup>
I use Emacs + eglot + company + yasnippet, when I insert the name of a type( Int Double or Float), HLS will insert a space after it.
Any one known how to disable this feature?

For example: I input `length' :: [Int]` , and I will get ` length' :: [Int ]`

<img width="485" alt="image" src="https://user-images.githubusercontent.com/47546452/158523169-8cd92b1c-10c0-4a57-8398-96a14ed9d147.png">

<img width="213" alt="image" src="https://user-images.githubusercontent.com/47546452/158523495-eee1948a-a1e2-4b36-8f0a-5c912525680f.png">

The same issue also happened on vscode

From the *EGLOT event* log, you can see HLS return is` "Int "`

```
 [stderr] 2022-03-16 17:40:00.516289 [ThreadId 171] INFO hls:	finish: Completion (took 0.00s)
[server-reply] (id:2) Wed Mar 16 17:40:01 2022:
(:id 2 :jsonrpc "2.0" :result
     (:isIncomplete t :items
                    [(:detail ":: Type" :documentation
                              (:kind "markdown" :value "*Imported from 'Prelude'*\n* * *\n\n")
                              :insertText "Int " :insertTextFormat 2 :kind 22 :label "Int" :sortText "00")
                     (:detail ":: Type" :documentation
                              (:kind "markdown" :value "*Imported from 'Prelude'*\n* * *\n\n")
                              :insertText "Integer " :insertTextFormat 2 :kind 22 :label "Integer" :sortText "01")
                     (:detail ":: Type -> Constraint" :documentation
                              (:kind "markdown" :value "*Imported from 'Prelude'*\n* * *\n\n")
                              :insertText "Integral ${1:Type}" :insertTextFormat 2 :kind 8 :label "Integral" :sortText "02")

# .... more ....
```

Emacs 29.0.50
Mac OS 12.3
HLS: 1.6.1.0 

</div>

**Comment by July541** [comment]
I think you've enabled `"haskell.plugin.ghcide-completions.config.snippetsOn": true` by default, it will insert some snippets to be convenient for your next step, consider setting this field to false to disable it. Here docs may useful: https://haskell-language-server.readthedocs.io/en/latest/configuration.html#generic-server-options

**Comment by Eason0210** [comment]
Hi @July541 , Thanks for your information.

If I understand correctly, with `"haskell.plugin.ghcide-completions.config.snippetsOn": false`, I won't be able to use the snippet feature.

I was wondering, is it possible for the server to return a string without spaces (Just "Int" for example) while enabling the snippet feature.

I'm curious, why HLS need to return an extra space?

**Comment by ksqsf** [comment]
+1 for not inserting spaces by default.

**Comment by July541** [comment]
> I'm curious, why HLS need to return an extra space?

An extra space left because there is no argument for `Int`.

The only thing I can think of is entering multiple parameters in succession, but it also annoying for the last param, I'll delete the space before going to the next line.

Agree to remove the space while no arguments.

**Comment by Eason0210** [comment]
@July541  Thanks for your explanation.

> The only thing I can think of is entering multiple parameters in succession, but it also annoying for the last param, I'll delete the space before going to the next line.

Recently, I will use formatting tools to handle the unused spaces.
> Agree to remove the space while no arguments.

Indeed, this would be a small enhancement when input these  type keywords without arguments.

**Comment by michaelpj** [comment]
This just seems like a bug, tbh? Maybe something around here https://github.com/haskell/haskell-language-server/blob/master/ghcide/src/Development/IDE/Plugin/Completions/Logic.hs#L262
