### ISSUE TITLE
File scrolls to a different point when code formatter runs

### ISSUE THREAD

**Issue by sloorush** [haskell/haskell-language-server#2792]
### Your environment

Which OS do you use: Manjaro

Which LSP client (editor/plugin) do you use: VS Code+[haskell](https://marketplace.visualstudio.com/items?itemName=haskell.haskell) with format on save turned on

Describe your project (alternative: link to the project): one haskell file that deals with lists.

### Steps to reproduce
Not very sure because it happens sometimes, and sometimes it does not.

### Expected behaviour
Code should not scroll to a different point when code-formatter runs

### Actual behaviour
Code scrolls to a random point when code-formatter runs, leaving the user confused about where they were typing

### Include debug information
N/A

### Note
I am unsure if this is the correct place to file the issue. Please guide me if it is incorrect.

**Comment by michaelpj** [comment]
I'm pretty sure this isn't us doing anything weird. All the server does in response to a formatting request is to send back a series of text edits - nothing about moving the view. So it must be the client doing something, like moving you to the location of the first edit or something?

**Comment by sloorush** [comment]
I'll try to find when it happens it would give a better idea(it is still happening randomly to me)

It might also be because of the vscode-vim extension, will report anything else I find

Thanks

**Comment by michaelpj** [comment]
You could also have a look at the messages the server is sending to see if there's anything funny in there. But I'm not sure what it could be...

**Comment by sloorush** [comment]
Is there any way to look at the HLS logs when I'm working on some other Haskell project? 

@michaelpj

**Comment by michaelpj** [comment]
Have a read of https://haskell-language-server.readthedocs.io/en/latest/troubleshooting.html

**Comment by sloorush** [comment]
I guess it was a VSCode issue, haven't faced it in a long time. Closing the issue
