### ISSUE TITLE
`Set module name to <name>` is suggested even if the module is already called `<name>`

### ISSUE THREAD

**Issue by konsumlamm** [haskell/haskell-language-server#2797]
### Example

![set_module_name](https://user-images.githubusercontent.com/44230978/159781572-8dbaa22d-3198-462f-a894-aed1168895f9.png)

### Version

GHC version: 9.2.1
HLS version: 1.6.1.0

**Comment by July541** [comment]
It seems hard to reproduce, even I'm sure I've met this

**Comment by konsumlamm** [comment]
To be clear: this happens for any module I load.

It seems to only occur when using GHC 9.2.1 though, with GHC 9.0.2 and 8.10.7 everything is fine.

**Comment by Jashweii** [comment]
I also get this, on both 9.2.1 and 9.2.2 (haven't tried another version). I get it on both wsl ubuntu (hls master) and windows (1.6.1.0) on vscode.
