### ISSUE TITLE
Unexpected `import (implicit) Prelude` code lens

### ISSUE THREAD

**Issue by konsumlamm** [haskell/haskell-language-server#2798]
### Example
![import_implicit_prelude1](https://user-images.githubusercontent.com/44230978/159779118-3f72f4d1-d0ad-4918-a0ca-dd1b8a32ab5e.png)

I'm not sure if the `import (implicit) Prelude` code lens itself supposed to be a feature or not, but the import code lens for the module isn't shown. When a newline is added before, this doesn't occur:

![import_implicit_prelude2](https://user-images.githubusercontent.com/44230978/159779342-3c479369-d2f4-4c52-ba8d-62ed8c51e7d5.png)

GHC version: 9.2.2
HLS version: 1.7.0.0

**Comment by drsooch** [comment]
Any extra information on this? GHC version? Project details (are you using some non-standard setup)? 

I tried to repro with a simple file but didn't see anything.

**Comment by konsumlamm** [comment]
Sorry, I edited the issue to include the GHC and HLS versions. There is no non-stadard setup, just a simple default setup (generated by `cabal init`).

**Comment by drsooch** [comment]
Looks like this just affects GHC 9.2.*

**Comment by sloorush** [comment]
I tried to reproduce the error, and it is reproducible.

The `import (implicit) Prelude ()` text comes up when the import statement is in the first list of the file. Here is a screenshot comparing the two situations:

![image](https://user-images.githubusercontent.com/54478821/172397448-78be1237-1997-4c9b-addf-9cb13fabc04c.png)

Testing on `ghc-9.2.2`, this was not reproducible on `ghc-9.0.2`

**Comment by ChristophHochrainer** [comment]
Hey, I could also reproduce it and I believe to have found the culprit.

I believe it is the function `minimalImportsRule` inside `plugins/hls-explicit-imports-plugin/src/Ide/Plugin/ExplicitImports.hs`, or more specifically the `importsMap`. 

```
let importsMap =
        Map.fromList
          [ (realSrcSpanStart l, printOutputable i)
            | L (locA -> RealSrcSpan l _) i <- fromMaybe [] mbMinImports
          ]
      res =
        [ (i, Map.lookup (realSrcSpanStart l) importsMap)
          | i <- imports
          , RealSrcSpan l _ <- [getLoc i]
        ]
```
This map uses the source location as key and only allows a single value and not a value list. The `GHC` API always gives the `import (implicit) Prelude` suggestion in the first line. So every other import in the first line collides with this and gets overridden. A solution to this could be
  * exclude the `Prelude` code action or
  * create multiple code actions for implicit imports for the first line.
