### ISSUE TITLE
Open singleton .hs file inside and scan with lint [not a bug, but need help] 

### ISSUE THREAD

**Issue by lectricas** [haskell/haskell-language-server#2808]
Hi. I'm trying to run singleton files using vscode, so I would have all the types and suggestions highlighted for me.

But I have no luck with that. Can you explain how I can do that? 

Again ,what I want: Open vscode, open single .hs file inside some folder and have all the errors highlighted (and suggestions) without running ghci on this file. 

I've achieved that in the past but I didn't know how.

**Comment by July541** [comment]
Hello, can you show some correlated error messages by following https://github.com/haskell/vscode-haskell#investigating-and-reporting-problems?

**Comment by lectricas** [comment]
Hi. I've just completely killed vs code on my Mac, then opened a single file and it worked! Thanks. Sorry for bothering!
