### ISSUE TITLE
HLS Wrapper fails with Xmonad

### ISSUE THREAD

**Issue by jordan-josephs** [haskell/haskell-language-server#2811]
Hi all,

I recently setup HLS with Emacs lsp on my arch linux install. I wanted to set this up to get more information when messing around with my xmonad config. But with following the instructions for setting up HLS w/ emacs, emacs seems to load everything fine but nothing ever shows up (ie. LSP information like lens). I ran haskell-language-server-wrapper in my xmonad config directory and it failed with error in the picture attached. I don't know if this is a HLS issue or an XMonad issue or a me issue. If someone has any insight that would be amazing.

Error Message :
https://imgur.com/CKwQU2k

**Comment by fendor** [comment]
That looks like a Haskell/Arch Linux issue to me, how did you install HLS?

**Comment by jordan-josephs** [comment]
The AUR. haskell-language-server-static. 

I installed xmonad using stack, installed stack via their install script just to get away from arch linuxs problem with haskell programs. Any idea where this issue would be better suited?

**Comment by jordan-josephs** [comment]
I tried removing stack and reinstalling it thru the AUR stack-static package and its still the same issue. I have also spun up a VM of arch and recreated my exact environment and produces the same error.

Steps I took in VM - 
Installed stack-static from AUR
Install XMonad and XMonad-Contrib via stack
Installed haskell-language-server-static from AUR


HLS doesn't run on boot and then running the wrapper in the config folder it shows same error as host machine.

**Comment by fendor** [comment]
My general recommendation is to use [GHCup](https://www.haskell.org/ghcup/) for basically anything Haskell related (E.g. stack installation, GHC installation if you have any, HLS installation). At least, I fare very well with ghcup on Arch Linux. I don't use *anything* Haskell related from pacman to avoid issues.

For your problem in particular, I am not familiar enough with linking to tell why the statically linked binary failed to load glibc. Maybe ask the authors of the AUR package? Some other contributors are more familiar with linking, they might have additional insights.

**Comment by georgefst** [comment]
> At least, I fare very well with ghcup on Arch Linux. I don't use _anything_ Haskell related from pacman to avoid issues.

The trick is to add GHCup at the start of your `PATH`. Then Pacman will happily use its own GHC for when you want to install HLint or Pandoc or Fourmolu or whatever\*, and you can use the GHCup-managed GHC for your own development.

\* XMonad is a bit different to these since it's not just a user-facing tool that happens to be written in Haskell - it's also a Haskell library - so you should use your GHCup dev toolchain

**Comment by jordan-josephs** [comment]
I would also like to add that I am using kernel 5.17 that was recently released. I do not know if this could be playing any part in the issue?

**Comment by jordan-josephs** [comment]
Another update -

I also tried a VM with following your advice, installing ghcup, but difference was using the LTS kernel. And it still had the same error.

**Comment by jordan-josephs** [comment]
I managed to get it working by changing the resolver to lts18.28. For some reason using the auto-gened stack.yml when running stack init with xmonad the resolver set throws that error with HLS.
