### ISSUE TITLE
Test suite code compiles before HLS works

### ISSUE THREAD

**Issue by Vlix** [haskell/haskell-language-server#2812]
I've been looking through the issues to see if anything looks like this, but I have not found it.
If there is one out there, this issue can be closed and I'll pop in over there to share experiences, but I just want to get this out of my system.

Side note: if the `test-suite` does compile completely and THEN you start changing code that doesn't type-check etc. that works fine, no problem. But if you need to change something in the `test-suite`'s dependencies (like a library this package depends on) it might have to recompile everything.

... now that I say that, I also have the opposite problem, where changing the dependency of a `test-suite` doesn't actually retrigger a recompile, or even a rescan, and even having HLS recompile the dependency won't actually show those changes in the live loaded-in `test-suite` 🤔 Those situations require a complete stop, a `stack clean` of more than just the direct package (so plus any of its dependencies) and then starting HLS again.

### Your environment

Which OS do you use: **Ubuntu 20.04**
Which LSP client (editor/plugin) do you use: **VSCode**
Describe your project (alternative: link to the project): **stack.yaml**
* It's a big production code base with several packages, all with libraries/test-suites/executables, but I'm pretty sure it happens with any cabal file

### Steps to reproduce
Open a `*.hs` file from a `test-suite` instead of a `library` in VSCode with dependencies that have not already been compiled. It will compile all the dependencies (potentially other local libraries) and then ALSO the `test-suite` to which the `*.hs` file belongs too, even though it might not compile (because I'm might still be working on it)

### Expected behaviour
Just like when opening a file from a library, only the dependencies should be actually compiled, and the package the file belongs to just gets scanned and indexed so HLS can start working on the file which might be full of type errors.

### Actual behaviour
HLS can't compile the `test-suite`, so it retries 5 times and then dies. Leaving me a sad developer with no information on-hover and no squigly lines to show where things don't type-check.

**Comment by michaelpj** [comment]
Known problem, sorry: https://haskell-language-server.readthedocs.io/en/latest/troubleshooting.html#problems-with-multi-component-support-using-stack
