### ISSUE TITLE
Formatters should pick up default extensions from `NAME.cabal` or `package.yaml`

### ISSUE THREAD

**Issue by ikervagyok** [haskell/haskell-language-server#2817]
**Is your feature request related to a problem? Please describe.**

I like the `default-extensions` field in `<NAME>.cabal`/`package.yaml` but it breaks (auto-)formating in VS Code.

**Describe the solution you'd like**

It seems that `ormolu` and `fourmolu` have gotten the ability to use the default extensions from the project's cabal file. It would be great, if this could be enabled through the VS Code plugin or there would be a option to pass CLI options to the current formater.

See: https://github.com/fourmolu/fourmolu#account-for-cabal-files

**Describe alternatives you've considered**

The alternative is to add all the Extensions in every file, which has the downsides of visual overload when reviewing for safe/unsafe extensions.

**Additional context**

Thanks for making (mid- to large-scale) Haskell programming go from unbearable to bearable and now to enjoyable. This is more like the cherry on top of the cake, but it's the only reoccurring wish I have regarding the Haskell experience!

**Comment by fendor** [comment]
Thank you for the bug report, moved to HLS repo

**Comment by ikervagyok** [comment]
> I'm looking to work on this as a first contribution, but I'm unable to get this to reproduce with a fresh build off `master`. I did `cabal init` on a new repo and have the following `Main.hs`.
> 
> ```
> --Main.hs
> {-# RULES
> "x# `eqChar#` x#" forall x#. x# `eqChar#` x# = True
> "x# `neChar#` x#" forall x#. x# `neChar#` x# = False
> "x# `gtChar#` x#" forall x#. x# `gtChar#` x# = False
> "x# `geChar#` x#" forall x#. x# `geChar#` x# = True
> "x# `leChar#` x#" forall x#. x# `leChar#` x# = True
> "x# `ltChar#` x#" forall x#. x# `ltChar#` x# = False
>   #-}
> ```
> 
> Ormolu succeeds when `default-extensions: MagicHash` is included in the `proj.cabal` file, and fails when its missing (which is the expected behavior). It appears enabled lang extensions are passed to ormolu from `extensionFlags` generated by GHC.
> 
> Would you mind elaborating on how ormolu/fourmolu fail due to ignored `default-extensions`?

@coltenwebb I see now that I did something wrong in my setup and the wrong (ancient) HLS version was used sometimes. Thank you for testing this - after reworking my setup this seems resolved.
