### ISSUE TITLE
Document why users might want to build from source

### ISSUE THREAD

**Issue by sullyj3** [haskell/haskell-language-server#2825]
**Is your feature request related to a problem? Please describe.**

I had installed hls using the ghcup tui, and I was getting the following when trying to run hls in my project:
```
  Unexpected usage error
  /usr/lib/libldap.so.2: symbol close version GLIBC_2.2.5 not defined in file libpthread.so.0 with
  link time reference
```
After going without hls for a while, I eventually got sick of it and decided to try to figure out the issue.

I followed the troubleshooting guide (great job on that, by the way!), and eventually came across [this section](https://haskell-language-server.readthedocs.io/en/latest/troubleshooting.html#static-binaries) containing the arcane incantation:
```
$ ghcup compile hls -v 1.6.1.0 --ghc 9.0.2 --cabal-project cabal-ghc90.project
```
This potent spell seems to have done the trick. 

In my opinion, my OS installation is not a particularly unusual setup, and I wouldn't be surprised if many people have similar issues to me and never resolve them. 

**Describe the solution you'd like**

It would have saved me a lot of time if the [documentation installation page](https://haskell-language-server.readthedocs.io/en/latest/installation.html) mentioned this potential eventuality to me, as a reason for why I might want to use `ghcup compile`. 

While the installation page does mention installing from source as a possibility, it doesn't explain that if you don't, you can potentially get weird linker errors that are totally inscrutable to non C programmers such as myself. I assumed it was there for people who like to build things from source for the fun of it.

It seems likely to me that adding this documentation would reduce pressure on this issue tracker.

**Describe alternatives you've considered**

none

**Additional context**

n/a

**Comment by pepeiborra** [comment]
Did you check the Common issues? https://haskell-language-server.readthedocs.io/en/latest/troubleshooting.html

**Comment by pepeiborra** [comment]
The upcoming 1.7.0 HLS release will fix this problem by deploying dynamically linked binaries instead of static ones.

**Comment by sullyj3** [comment]
> I followed the troubleshooting guide (great job on that, by the way!), and eventually came across [this section](https://haskell-language-server.readthedocs.io/en/latest/troubleshooting.html#static-binaries)

I did check the common issues, yes

> The upcoming 1.7.0 HLS release will fix this problem by deploying dynamically linked binaries instead of static ones.

Nice, that's exciting!
