### ISSUE TITLE
Editor support for Fourmolu CLI option

### ISSUE THREAD

**Issue by georgefst** [haskell/haskell-language-server#2827]
As for:

> Add config option to editor plugins e.g. VSCode 

Is there anything I need to do? I see from https://github.com/haskell/haskell-language-server/pull/1576 that we have some auto-generation script. Is this part of the release process? Is any of this (i.e. the process of adding an option) documented anywhere?

_Originally posted by @georgefst in https://github.com/haskell/haskell-language-server/issues/2763#issuecomment-1066140768_

**Comment by georgefst** [comment]
The functionality added in #244 is in a weird state, of being implemented but not supported by editor integrations. It would be great to get some help from someone who knows more about how plugin-specific options work. I suspect it's simple for anyone who knows the system, but I don't know how to proceed by myself.

More generally, we could really do with a documented process for this. I'm sure other contributors will want to add plugin options in future.

**Comment by pepeiborra** [comment]
I think @berberman contributed the support for plugin-specific options. What do you need help with?

**Comment by berberman** [comment]
#1576 provided `--vscode-extension-schema` for generating available client options, which can be used in `package.json` of `vscode-haskell`. Yes, this should be a part of the release process of `vscode-haskell`, and iirc @jneira used to do that. It would be better to have a documentation for this. However, for other editors, there is no automated generating support, because they usually have their own formats of configurations, and I think they always can translate the vscode one to their formats if needed.

**Comment by michaelpj** [comment]
@fendor seems to be doing the vscode plugin release.

It would be great if someone could write some documentation in the `vscode-haskell` readme about how to add new HLS options there, since this question comes up a lot.

**Comment by fendor** [comment]
I tried to look into and I am honestly a little confused myself, can someone help me out  writing some nice docs for this task?

**Comment by georgefst** [comment]
> #1576 provided --vscode-extension-schema

FYI, there's no `--`, it's just `haskell-language-server vscode-extension-schema`.

Anyway, I finally looked in to this. https://github.com/haskell/haskell-language-server/pull/3284 combined with https://github.com/haskell/vscode-haskell/pull/736 should solve the problem at hand. But I'm reluctant to close this thread since it's now being used to track something more general: documenting what plugin writers need to do to add full support for any plugin options.

PS. The Fourmolu CLI option can be used in the latest release of HLS with VSCode by adding `"haskell.plugin.fourmolu.config.external": true` to the VSCode settings JSON file manually. It doesn't matter that neither of the aformentioned PRs have been merged.

**Comment by jhrcek** [comment]
Could you please document the haskell.plugin.fourmolu.config.external option in hls docs?
I managed to make it work, but had to do a lot of searching before I found this thread :smile:

**Comment by michaelpj** [comment]
Or better, do https://github.com/haskell/haskell-language-server/issues/3183

**Comment by georgefst** [comment]
Closing this. It is now usable, as outlined in https://github.com/haskell/haskell-language-server/issues/2827#issuecomment-1275392086. Though I agree that #3183 is important.
