### ISSUE TITLE
"Remove redundant import" action not showing up anymore

### ISSUE THREAD

**Issue by andys8** [haskell/haskell-language-server#2845]
### Your environment

Which OS do you use: Arch
Which LSP client (editor/plugin) do you use: Vim + CoC
Describe your project (alternative: link to the project): Stack

### Steps to reproduce

* Import a function that isn't used
* Trigger `coc-fix-current`

![image](https://user-images.githubusercontent.com/13085980/164354108-dbdb9c60-0ed6-4bd5-ab9f-6c9f88af7e7e.png)

### Expected behaviour

Hint to remove this or all redundant imports shows up

### Actual behaviour

Hint doesn't show up. Only option is to disable the warning.

![image](https://user-images.githubusercontent.com/13085980/164354051-3ef3b188-c97c-4a60-a902-777bfec4602a.png)

https://github.com/haskell/haskell-language-server/blob/2221371a87d3a423d3273e928e8a93ac182d854e/ghcide/src/Development/IDE/Plugin/CodeAction.hs#L312

**Comment by tim2CF** [comment]
I have the same issue. Linux, Vim, Coc, Hls-1.6.1.1

**Comment by michaelpj** [comment]
What GHC version are you using?

**Comment by andys8** [comment]
Forgot to include more information about my system. 
GHC is 8.10.7. More in [other issue](https://github.com/haskell/haskell-language-server/issues/2858)

**Comment by wz1000** [comment]
Could you share LSP communication logs for the HLS session? This may be a client issue.

**Comment by andys8** [comment]
Hey there, I retested again. For the example I posted, it seems to work again with the current setup I have. There is an action to remove the import

![image](https://user-images.githubusercontent.com/13085980/189109070-9fd56a03-2fe0-435e-9a44-a982626531e6.png)
![image](https://user-images.githubusercontent.com/13085980/189109202-bfeadaab-2ee9-49e3-8b30-7ba432520a5e.png)

## Setup

* HLS: a89ba412293327ec838c00d899ea9c6013c46aa3
* Stack 2.7.5
* Cabal 3.8.1
* GHC tested with 8.10.7 and 9.2.4 projects (both stack)
