### ISSUE TITLE
Internal error, getIdeGlobalExtras, no entry for DisplayTHWarning

### ISSUE THREAD

**Issue by andys8** [haskell/haskell-language-server#2858]
### Your environment

Which OS do you use: Manjaro 21.2.6 Qonos (Arch based)
Which LSP client (editor/plugin) do you use: Vim/CoC
Describe your project (alternative: link to the project): stack

### Steps to reproduce

Run `haskell-language-server-wrapper .`

### Expected behaviour

No errors

### Actual behaviour

Many of these logs showing an internal error missing an entry for `DisplayTHWarning`

```
2022-04-27T00:14:29.070716Z | Info | updateFileDiagnostics published different from new diagnostics - file diagnostics: File:     /home/<path>.hs
Hidden:   no
Range:    1:1-2:1
Source:   compiler
Severity: DsError
Message:
  Internal error, getIdeGlobalExtras, no entry for DisplayTHWarning
  CallStack (from HasCallStack):
  errorIO, called at src/Development/IDE/Core/Shake.hs:351:20 in
  ghcide-1.7.0.0-5d0280f91cc32129977b489cf9b14cb95b9062238f5e7b9a5bc31c595dd97f64:Development.IDE.Core.Shake
```

### Include debug information

```
haskell-language-server version: 1.7.0.0 (GHC: 9.2.2) (PATH: /home/andreas/.ghcup/hls/1.7.0.0/lib/haskell-language-server-1.7.0.0/bin/haskell-language-server-wrapper)
Tool versions found on the $PATH
cabal:          3.6.2.0
stack:          2.7.5
ghc:            8.10.7
```

**Comment by andys8** [comment]
Should have mentioned I installed with `ghcup tui` and clicked install.

**Comment by pepeiborra** [comment]
Does HLS work when used as an LSP server?

**Comment by andys8** [comment]
Yes, it does. Not sure if this will lead to issues, but didn't notice them. (HLS often stopped working before this release/issue and doesn't work well with stack projects anyway)

**Comment by michaelpj** [comment]
I think this should have been fixed by https://github.com/haskell/haskell-language-server/pull/2895.
