### ISSUE TITLE
Can't build from source with 8.10.7: ‘coreExprToBCOs’ is applied to too few arguments

### ISSUE THREAD

**Issue by maksbotan** [haskell/haskell-language-server#2860]
### Your environment

Which OS do you use:
macOS 11.6.2
Which LSP client (editor/plugin) do you use:
neovim + coc-nvim
Describe your project (alternative: link to the project):
Not relevant

### Steps to reproduce
Basically, I did

1. Git clone the repo
2. `git checkout 1.7.0.0`
3. `cabal new-build exe:haskell-language-server`

I have `cabal` and `ghc` 8.10.7 in my `$PATH`, installed from [`haskell.nix`](https://github.com/input-output-hk/haskell.nix).

```
$ cabal --version
cabal-install version 3.6.2.0
compiled using version 3.6.2.0 of the Cabal library 
$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.10.7
```

### Expected behaviour

I expect `cabal` to build me a `haskell-language-server` exe.

### Actual behaviour

Building of `ghcide` package breaks with this error:

```
src/Development/IDE/Core/Compile.hs:260:22: error:
    • Couldn't match expected type ‘IO ByteCodeTypes.UnlinkedBCO’
                  with actual type ‘StgSyn.StgRhs -> IO ByteCodeTypes.UnlinkedBCO’
    • Probable cause: ‘coreExprToBCOs’ is applied to too few arguments
      In a stmt of a 'do' block:
        bcos <- coreExprToBCOs
                  hsc_env (icInteractiveModule (hsc_IC hsc_env)) prepd_expr
      In the expression:
        do let dflags = hsc_dflags hsc_env
           simpl_expr <- simplifyExpr dflags hsc_env ds_expr
           let tidy_expr = tidyExpr emptyTidyEnv simpl_expr
           prepd_expr <- corePrepExpr dflags hsc_env tidy_expr
           ....
      In an equation for ‘compile_bco_hook’:
          compile_bco_hook var hsc_env srcspan ds_expr
            = do let dflags = ...
                 simpl_expr <- simplifyExpr dflags hsc_env ds_expr
                 let tidy_expr = ...
                 ....
    |
260 |            ; bcos <- coreExprToBCOs hsc_env
    |                      ^^^^^^^^^^^^^^^^^^^^^^...

src/Development/IDE/Core/Compile.hs:261:63: error:
    • Couldn't match type ‘CoreSyn.Expr CoreSyn.CoreBndr’
                     with ‘GHC.Var’
      Expected type: Id
        Actual type: CoreExpr
    • In the third argument of ‘coreExprToBCOs’, namely ‘prepd_expr’
      In a stmt of a 'do' block:
        bcos <- coreExprToBCOs
                  hsc_env (icInteractiveModule (hsc_IC hsc_env)) prepd_expr
      In the expression:
        do let dflags = hsc_dflags hsc_env
           simpl_expr <- simplifyExpr dflags hsc_env ds_expr
           let tidy_expr = tidyExpr emptyTidyEnv simpl_expr
           prepd_expr <- corePrepExpr dflags hsc_env tidy_expr
           ....
    |
261 |                        (icInteractiveModule (hsc_IC hsc_env)) prepd_expr
    |                                                               ^^^^^^^^^^
```

### Include debug information

I attach `cabal.project.freeze` generated by `cabal new-freeze` just in case.

[cabal.project.freeze.txt](https://github.com/haskell/haskell-language-server/files/8570200/cabal.project.freeze.txt)

**Comment by wz1000** [comment]
How did you install GHC? In GHC 8.10.7, [coreExprToBCOs](https://hackage.haskell.org/package/ghc-8.10.7/docs/ByteCodeGen.html#v:coreExprToBCOs) has type `HscEnv -> Module -> CoreExpr -> IO UnlinkedBCO`

Can you start a GHCi session with `-package ghc`, import `ByteCodeGen` and then ask for `:type coreExprToBCOs`?

**Comment by amesgen** [comment]
Also hitting this issue with haskell.nix, and indeed, the type is different:
```
 Λ :t coreExprToBCOs
coreExprToBCOs
  :: HscTypes.HscEnv
     -> Module.Module -> Var.Id -> StgSyn.StgRhs -> IO UnlinkedBCO
```
So this seems like a haskell.nix issue as it uses slightly patched GHCs. I opened https://github.com/input-output-hk/haskell.nix/issues/1455 to track this.

**Comment by wz1000** [comment]
It seems like the culprit is haskell.nix: https://github.com/input-output-hk/haskell.nix/blob/a5b74bf002bee3ee41012c8f5e48105150892eee/overlays/patches/ghc/ghc-8.10.5-ubxt.patch

This is an upstream issue since we can't conceivably support all custom distributions of GHC.

**Comment by maksbotan** [comment]
@wz1000 

Turns out `haskell.nix` applies a patch to 8.10 series:
https://github.com/input-output-hk/haskell.nix/blob/master/overlays/patches/ghc/ghc-8.10.5-ubxt.patch

Among other things it has this:

```patch
@@ -155,23 +167,25 @@ literals:
 -- Returns: the root BCO for this expression
 coreExprToBCOs :: HscEnv
                -> Module
-               -> CoreExpr
+               -> Id
+               -> StgRhs
                -> IO UnlinkedBCO
-coreExprToBCOs hsc_env this_mod expr
+coreExprToBCOs hsc_env this_mod bndr expr
```

Do you maybe know corresponding upstream MR? I could not find any reference in haskell.nix repository :/

```
$ ghci -package ghc
GHCi, version 8.10.7: https://www.haskell.org/ghc/  :? for help
Loaded package environment from /Users/maksbotan/.ghc/x86_64-darwin-8.10.7/environments/default
Loaded GHCi configuration from /Users/maksbotan/.ghci
λ> import ByteCodeGen
λ> :type coreExprToBCOs
coreExprToBCOs
  :: HscTypes.HscEnv
     -> Module.Module -> Var.Id -> StgSyn.StgRhs -> IO UnlinkedBCO
```

**Comment by maksbotan** [comment]
@amesgen thanks for reporting this to haskell.nix!

**Comment by wz1000** [comment]
Closing as this is a downstream packaging issue.
