### ISSUE TITLE
Wingman not available when using HLS from nix

### ISSUE THREAD

**Issue by aVikingTrex** [haskell/haskell-language-server#2869]
### Steps to reproduce
Using Nix for package management using "nix-shell -p ghc haskell-language-server" sets up an environment with:
HLS version: 1.6.1.1 
GHC version: 9.0.2 

### Expected behaviour
running "haskell-language-server --list-plugins" should include hls-tactics-plugin

### Actual behaviour
hls-tactics-plugin is missing and within any of vim/vscode/emacs, wingman suggestions are not available

### Include debug information
--list-plugins returns:
``` alternateNumberFormat
callHierarchy
class
eval
floskell
fourmolu
ghcide-code-actions-bindings
ghcide-code-actions-fill-holes
ghcide-code-actions-imports-exports
ghcide-code-actions-type-signatures
ghcide-completions
ghcide-core
ghcide-hover-and-symbols
ghcide-type-lenses
haddockComments
hlint
importLens
moduleName
ormolu
pragmas
qualifyImportedNames
refineImports
retrie
selectionRange
splice
```

**Comment by matthewess** [comment]
also seem to be hitting this, same hls and ghc versions. i tried using the hls flake directly but i ran into a lot of trouble getting that to work, for some reason.

**Comment by michaelpj** [comment]
I think the tactics plugin was working for GHC 9.0 in that version, so it sounds like this is a problem with the nix packaging, and you probably want to take it up with them?

**Comment by barendventer** [comment]
This issue shows up ahead in search results, but it looks like actual discussion about it is taking place in an issue on NixOS, so I'll putting a link here for the benefit of others who wind up here if that's alright: https://github.com/NixOS/nixpkgs/issues/177759

**Comment by michaelpj** [comment]
Wingman is gone
