### ISSUE TITLE
Paren style for auto-import and import code lens

### ISSUE THREAD

**Issue by schuelermine** [haskell/haskell-language-server#2883]
### Your environment

<details>

<summary> Click to expand </summary>

#### Hardware:
```
81FV Lenovo Legion Y530-15ICH

x86_64
Intel i5-8300H (8) @ 4.000GHz
NVIDIA GeForce GTX 1050 Ti Mobile
Intel CoffeeLake-H GT2 [UHD Graphics 630]
Memory: 7830MiB

Display: 1920x1080@60.03Hz 100%
```
#### Operating system:
```
NixOS 22.05.20220426.e10da1c (Quokka)

e10da1c7f542515b609f8dfbcf788f3d85b14936
```
#### Kernel:
```
Linux buggeryyacht 5.17.3 haskell/vscode-haskell#1-NixOS SMP PREEMPT Wed Apr 13 17:27:43 UTC 2022 x86_64 GNU/Linux
```
#### Graphical environment:
```
GNOME 42.0
Mutter
X
```
#### Visual Studio Code:
```
Version: 1.66.2
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:49:24.808Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Linux x64 5.17.3

b3fk6zip2lnk8m4n68icm75mrsywil5c-vscode-1.66.2.drv
```
#### Haskell:
```
The Glorious Glasgow Haskell Compilation System, version 9.0.2
cabal-install version 3.6.2.0
compiled using version 3.6.3.0 of the Cabal library

c4gsm4i98amdwh54hs956bbkh1np27hw-ghc-9.0.2.drv
4rfyqwnb76qpaym686ij0gb7dfgpz5gh-cabal-install-3.6.2.0.drv
```
#### Extension:
```
v2.2.0
```

</details>

### Steps to reproduce

1. Type the name of an out-of-scope identifier and press <kbd>⭾</kbd>
2. Use an identifier from a module that is imported without an import list, and click on the code lens text above the import

### Expected behaviour

Both actions generate a consistent style of import list

### Actual behaviour

One generates `import Module (identifier)`, the other `import Module ( identifier )`

**Comment by michaelpj** [comment]
Dupe, I think: https://github.com/haskell/haskell-language-server/issues/2399
