### ISSUE TITLE
Evaluate lens only comments the first line of multiline output

### ISSUE THREAD

**Issue by konsumlamm** [haskell/haskell-language-server#2907]
### Steps to reproduce

Code:
```hs
module Lib where

data MultiLine = MultiLine

instance Show MultiLine where
    show MultiLine = "Multi\nLine"

-- >>> MultiLine
```
Click `Evaluate...`:

![multiline1](https://user-images.githubusercontent.com/44230978/168441069-5cf64c64-71f1-4024-a8eb-1979b2a3a4ec.png)

### Expected behaviour

![multiline3](https://user-images.githubusercontent.com/44230978/168441120-3056c3c2-ff8b-4a2b-92ef-7c69a339d339.png)

### Actual behaviour

![multiline2](https://user-images.githubusercontent.com/44230978/168441126-78de8f59-ffab-40b6-915e-2f14f87bcb73.png)

### Versions

GHC: 9.2.2, 9.0.2, 8.10.7
HLS: 1.7.0.0

**Comment by xsebek** [comment]
Hi @konsumlamm and thanks for the bug report. Indeed we were not prefixing the multi-line show results. :sweat_smile: 

Luckily the fix is a one-liner `concatMap lines` and I even added a test case for this, though slightly different from yours:
```Haskell
data Multiline = M {l1 :: String, l2 :: String} deriving Read

instance Show Multiline where
  show m = "M {\n  l1=" <> show (l1 m) <> ",\n  l2=" <> show (l2 m) <> "\n}"

-- >>> M "first line" "second line"
-- M {
--   l1="first line",
--   l2="second line"
-- }
```
