### ISSUE TITLE
hls-eval-plugin: -- Not in scope: ‘P.writeFile’

### ISSUE THREAD

**Issue by codygman** [haskell/haskell-language-server#2926]
Trying out the example:

-- >>> 3 + 5

results in:

-- Not in scope: ‘P.writeFile’

### Your environment

Which OS do you use:
Ubuntu
Which LSP client (editor/plugin) do you use:
vscode-haskell
Describe your project (alternative: link to the project):
Stack project, ghc 9.0.2, hls installed via `ghcup compile hls -g 9b3f3bf20e3016d20adf1f7259dc9622f8046569 --ghc 9.0.2 --set -- --ghc-options='-dynamic'`

#### I'm also using a non-standard docker based hls/ghcup setup

Attempted repro failed in custom docker based setup (eval worked) as of: https://github.com/codygman/EvalTest/commit/478ab27578dd3361e4790cd00d24fcf8cca035f8

### Steps to reproduce

Type `-- >>> 3 + 5`
Click "evaluate"
get `-- Not in scope: ‘P.writeFile’`

### Expected behaviour
Type `-- >>> 3 + 5`
Click "evaluate"
get `-- 8`

### Actual behaviour
See above.

##### --probe-tools output
```
❯ ./tools/haskell-language-server-wrapper --probe-tools
haskell-language-server version: 1.7.0.0 (GHC: 9.0.2) (PATH: /home/haskell/.ghcup/bin/haskell-language-server-wrapper-1.7.0.0)
Tool versions found on the $PATH
cabal:          3.6.2.0
stack:          2.7.5
ghc:            9.0.2
```

### Things for me to test (some things others could help with) in [the minimal repro repo](https://github.com/codygman/EvalTest/tree/minimal-repro):

- [x] add a minimal repro using our custom docker/ghcup stack environment (see [the minimal repro repo](https://github.com/codygman/EvalTest/tree/minimal-repro))
- [x] Try reproducing code eval not working (failed, meaning code eval works fine)
- [ ] add some template Haskell with aeson-qq and re-test code eval
- [ ] add a persistent model and re-test code eval
- [ ] add testing with hspec-discover and re-test code eval
- [ ] disable the same set of plugins as we do in our prod codebase and re-test code eval

**Comment by xsebek** [comment]
Hi @codygman, I compiled the HLS with your command, but I can't reproduce the problem on a default Stack project. ([my repo](https://github.com/xsebek/EvalTest/blob/49d2ce18935f547699ea7b7b5f2ca04b2ec29810/src/Lib.hs#L6)).

Could you please provide a link to your repo or [the debug information](https://haskell-language-server.readthedocs.io/en/latest/troubleshooting.html#basic-diagnosis-steps)?

**Comment by codygman** [comment]
Hey @xsebek, I'm using hls from within a docker container using a wrapper script. I've tried adding it to your example and waiting for the build to finish to make sure it repros:

https://github.com/codygman/EvalTest/commit/7e7e3015048a29fa6c18935dce07014bfde3d485

**Comment by codygman** [comment]
My repro failed, so I'll have to try adding things that could have caused the error in the title in the order I think they matter and how easy they are to test to [the minimal repro repo](https://github.com/codygman/EvalTest/tree/minimal-repro):

- add some template Haskell with aeson-qq and re-test code eval
- add a persistent model and re-test code eval
- add testing with hspec-discover and re-test code eval
- disable the same set of plugins as we do in our prod codebase and re-test code eval

**Comment by codygman** [comment]
I wonder if this could be related to #2872, guess I'll see when I can test adding some template Haskell to the example using code eval.

**Comment by xsebek** [comment]
@codygman well, good luck with the debugging :slightly_smiling_face: You could also try finding a snippet of the debug output from HLS and the client, maybe that could narrow down the search.

**Comment by michaelpj** [comment]
Did you manage to get anywhere with this?

**Comment by codygman** [comment]
I didn't. I've been trying to get core HLS features stable with $WORK codebase. I wish I could upgrade back to this problem 😄

**Comment by tek** [comment]
this happens to me because my `Prelude` does not export `System.IO.writeFile`. Adding
```
import qualified System.IO as P
```

fixes the issue

**Comment by codygman** [comment]
I believe this was my issue as well since we were using a custom prelude. Closing this. Feel free to reopen if we want to do something else like have the plugin import that itself.
