### ISSUE TITLE
Dot Record Syntax Plugin

### ISSUE THREAD

**Issue by jaredramirez** [haskell/haskell-language-server#295]
The [proposal](https://github.com/ghc-proposals/ghc-proposals/pull/282) for `RecordDotSyntax` has been accepted, but until it's implemented in GHC, is it possible to use the the equivalent [plugin](https://github.com/ndmitchell/record-dot-preprocessor#readme) with HLS?

I have the plugin setup in my project and everything is compiling, but HLS give an error whenever I access anything like `record.prop`.

Thanks for the great tool!

**Comment by fendor** [comment]
@jaredramirez I think it should work with the ghc plugin. See https://github.com/digital-asset/ghcide/issues/294 and https://github.com/digital-asset/ghcide/issues/262

**Comment by jaredramirez** [comment]
I was able to get HLS/ghcide working with the preprocessor, but not with the ghc plugin. Someone is the issue you linked [said](https://github.com/digital-asset/ghcide/issues/262#issuecomment-567247837):
> I think the plugin still does not work for some reason. I was trying to debug this earlier today and printed out the list of loaded plugins in DynFlags after the initializePlugins call. RecordDotPreprocessor was in the list, but type checking still returned errors like if it was not loaded.

The preprocessor works just fine, but it would be nice to be able to use the plugin. According the dot record repo, the plugin "has much better error messages", so I'm interested in being able to use that, but this is not preventing me from using HLS.

Thanks for your help!

**Comment by ndmitchell** [comment]
The plugin is better, especially if you've got an IDE, since the IDE makes it possible to use precise error messages at speed much more than you would otherwise. I've tagged the Ghcide with great first issue - if you can get the plugin working (which I only barely can on Windows), it should be debuggable with a few print statements.

**Comment by neongreen** [comment]
Does HLS use ghcide? Or should the fix be done both in HLS and in ghcide?

**Comment by ndmitchell** [comment]
HLS uses Ghcide. The fix should be done in Ghcide alone, and tested there.

**Comment by jaredramirez** [comment]
This is fixed in Ghcide here: https://github.com/haskell/ghcide/issues/262
