### ISSUE TITLE
Adding imports adds an extra comma

### ISSUE THREAD

**Issue by cdsmith** [haskell/haskell-language-server#2958]
It is legal in Haskell to write an import list like this:

``` haskell
import Foo
  ( a,
    b,
    c,
  )
```

Note the trailing comma.  In particular, Ormolu formats files this way.  However, if I have an import list formatted this way, and ask HLS to add an import (for example, from the quick-actions list, or otherwise auto-importing something), I get this

``` haskell
import Foo
  ( a,
    b,
    c,, newImport
  )
```

Note the double comma at the end.  Of course, this is a syntax error.

**Comment by michaelpj** [comment]
I bet this is related to https://github.com/haskell/haskell-language-server/issues/2399, in that something is not using exactprint. If we're using exactprint I wouldn't expect this kind of bug.

**Comment by kokobd** [comment]
I'm going to take a look at this.
