### ISSUE TITLE
refineImports plugin causes excessive memory use

### ISSUE THREAD

**Issue by mpickering** [haskell/haskell-language-server#2962]
The refineImports plugin calls `TypeCheck` on all transitively imported modules which violates the important memory invariant that we only store TypeCheck results for files of interest. I recommend disabling this plugin by default until it is fixed.

My experience on GHC is that disabling this plugin causes start-up memory usage to decrease from 3GB to 1GB.

**Comment by michaelpj** [comment]
Wow, yes, that's quite bad!

**Comment by pepeiborra** [comment]
I noticed this a while ago but failed to raise an issue, my bad. Ping @rayshih would you mind contributing a fix?
