### ISSUE TITLE
Add first class support for GHC Notes Syntax

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-language-server#2964]
This feature has been proposed by SPJ during ZuriHac 2022.

Essentially, GHC has many Notes to explain the code-base, ghcide has these too, and they look like this: 
```haskell
{- Note [Avoiding bad interface files]
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
-}
```

And these notes are often references in documentation for functions like this:
![image](https://user-images.githubusercontent.com/8463814/174067417-0706fabf-3cba-4379-8a92-0e88393ab7bf.png)

The issue is, that there is no way to actually find the note from the documentation without resorting to a basic grep search.
This UX is acceptable, but maybe we can do better!
The idea presenting here is the following:
* Inline the comment in the haddock documentation when displayed to the user
* Alternatively: Make the syntax `Note [Avoiding bad interface files]` clickable, allowing users to jump to the original note, allowing them to more easily discover the information.

As an alternative design space, maybe we can teach haddock in general about references to other comment sections?

**Note**: If standardised, this feature is useful for more than just the GHC codebase, but beneficial to the whole community.

Possible roadmap:
1. Standardise the GHC Note system
2. Figure out how to automatically create an index of available Notes in a local project.
    * .hie files might provide this information, also haddock (which I think depends on .hie, right?).
3. Find notes from dependencies
    * again, .hie files or haddock.
4. Display notes to users

**Comment by michaelpj** [comment]
I think this is not a HLS problem. Adding support for such things to Haddock might be nice, and would benefit lots of people, but I think ad-hoc support baked into HLS would maybe even be bad (since it suppressed the desire to actually fix upstream tooling, and it's another random thing for us to maintain).
