### ISSUE TITLE
haskell-language-server should fail loudly if hie-bios fails to load the cradle

### ISSUE THREAD

**Issue by catern** [haskell/haskell-language-server#2965]
### Your environment

Which OS do you use:
NixOS
Which LSP client (editor/plugin) do you use:
n/a (was running HLS at the command line to test)
Describe your project (alternative: link to the project):
https://github.com/sweirich/pi-forall/blob/2022/version1/pi-forall.cabal

### Steps to reproduce
I ran haskell-language-server to test my setup and noticed a bunch of failures to build. It looked like haskell-language-server wasn't able to load my cabal file, but it didn't print any warnings or errors about that.

Eventually I ran hie-bios to check and got:
```
[nix-shell:~/.local/src/pi-forall/version1]$ hie-bios debug .
Cradle failed to load
Deps: ["pi-forall.cabal","cabal.project","cabal.project.local"]
Exit Code: ExitSuccess
Stderr: Couldn't execute cabal exec -v0 -- ghc --print-libdir
[nix-shell:~/.local/src/pi-forall/version1]$ echo $?
0
```

So hie-bios was failing because I had a messed-up environment without cabal, but haskell-language-server wasn't surfacing that failure in a useful.

### Expected behaviour
haskell-language-server should print a loud warning if hie-bios fails, and ideally incorporate hie-bios's own failure message into that warning. This would have helped a lot in debugging why it wasn't working.

### Actual behaviour
See above

**Comment by michaelpj** [comment]
I think once we bump `hie-bios` to include the more integrated logging, these kinds of errors should get shown to the user with `window/showMessage`, but we should check.

**Comment by michaelpj** [comment]
Error logs get sent to the user, so this should be surfaced loudly now
