### ISSUE TITLE
pre-commit hook is broken in nix

### ISSUE THREAD

**Issue by kokobd** [haskell/haskell-language-server#2967]
Currently, `nix develop` complains:
```
nix-pre-commit-hooks: updating /home/kokobd/work/github.com/kokobd/haskell-language-server repo
nix-pre-commit-hooks: WARNING: Refusing to install because of pre-existing .pre-commit-config.yaml
    1. Translate .pre-commit-config.yaml contents to the new syntax in your Nix file
        see https://github.com/hercules-ci/nix-pre-commit-hooks#getting-started
    2. remove .pre-commit-config.yaml
    3. add .pre-commit-config.yaml to .gitignore
```
This problem was introduced by #2679, where `.pre-commit-config.yaml` was checked in git.
But according to our documentation, `.pre-commit-config.yaml` should be managed by Nix. People do not use Nix can just manually install `pre-commit` hook and paste the file content into `.pre-commit-config.yaml`
https://github.com/haskell/haskell-language-server/blob/09968a156738d8bc196ad280e474c13bd36555c6/docs/contributing/contributing.md?plain=1#L171-L216

Now we have two options to compare:
1. Remove `pre-commit` config from Nix, and update the docs accordingly.
    - pros: Non-Nix users' life is made easier a little bit.
    - cons: Nix users will have to install pre-commit hooks manually.
2. Remove `.pre-commit-config.yaml` from Git, and let Nix manage it again.
    - pros: Nix users can benefit from the pre-commit hooks without any extra setup.
    - cons: Non-Nix users have to do one more manual step: paste the `.pre-commit-config.yaml`

I recommend the second option, as Non-Nix users will have some manual setups anyway, and we were on option 2 before #2679 was merged.

**Comment by drsooch** [comment]
To be fair this has been merged for 5 months. No one has raised any objections or issues since. It would seem like nix users are in the minority. 

The original intention was to make it so users didn't have to copy the json from documentation. 

Is there a third option that can satisfy both parties?

**Comment by drsooch** [comment]
I'm assuming the `nix` file of interest is `flake.nix` it looks like the pre-commit hook is out of date anyways. Not that it matters for nix users but we've added a `\r\n` to `\n` converter in the pre-commit hook as well. Seems odd nix can't handle a predefined pre commit hook configuration.

**Comment by kokobd** [comment]
I noticed the last change to `flake.nix` was made by @michaelpj last month, so I assume you are using Nix. Would you mind providing some advice on this?

**Comment by michaelpj** [comment]
I haven't really been using the flake-based shell so I'm not sure. Perhaps we could try using something like https://github.com/cachix/pre-commit-hooks.nix ? I think that generates `pre-commit.yaml` on the fly also?

**Comment by kokobd** [comment]
> Perhaps we could try using something like https://github.com/cachix/pre-commit-hooks.nix ?

`flake.nix` is using it already, but it relies on the non-existence of `.pre-commit-config.yaml`.

**Comment by michaelpj** [comment]
Why did we commit `.pre-commit-config.yaml` then? I am confused.

**Comment by drsooch** [comment]
> Why did we commit `.pre-commit-config.yaml` then? I am confused.

I had made an unrelated change to the config, and someone had suggested to commit it directly rather than have users copy the config directly.

**Comment by kokobd** [comment]
More context: `.pre-commit-config.yaml` was added back into `.gitignore` in #2892 last month. But it isn't removed from git. (an already checked-in file needs to be removed by `git rm --cached`, adding it to `.gitignore` alone is not sufficient)

**Comment by kokobd** [comment]
Considering not everyone is using Nix to develop HLS, ignoring `.pre-commit-config.yaml` will lead to an outdated config if it is changed. (who will remember to check docs for the latest `.pre-commit-config.yaml` regularly?).

So I'm planning to:
- Remove pre-commit config from `flake.nix`. Add `pre-commit` to `shellHook` directly (so that people using Nix still benefit from `.pre-commit-config.yaml`)
- Add `pre-commit` to Gitpod configuration
- Update docs about this. It's no longer required to copy `.pre-commit-config.yaml` from the docs.

**Comment by teto** [comment]
this breaks `nix flake show`. In the line `checks = { pre-commit-check = pre-commit-check ghcDefault; };` pre-commit-check is unknown. I find the config of pre-commit hooks via nix a bit annoying, should I just ditch that check ?

**Comment by kokobd** [comment]
@teto Oh, nice catch! I only tested `nix develop`. I believe you can remove both `checks = { pre-commit-check = pre-commit-check ghcDefault; };` and `inherit (self.checks.${system}.pre-commit-check) shellHook;`
