### ISSUE TITLE
CircleCI CI tasks are stuck for my PR

### ISSUE THREAD

**Issue by uhbif19** [haskell/haskell-language-server#2968]
### Your environment

GitHub

### Steps to reproduce

https://github.com/haskell/haskell-language-server/pull/2896

### Expected behaviour

CI finishes in reasonable time.

### Actual behaviour

3 CI tasks are pending for 20 hours.

![image](https://user-images.githubusercontent.com/300919/174451151-5d94cb45-032c-4388-9a34-180ec1f3539c.png)

**Comment by uhbif19** [comment]
These PR seems stuck too:

https://github.com/haskell/haskell-language-server/pull/2949
https://github.com/haskell/haskell-language-server/pull/2956
https://github.com/haskell/haskell-language-server/pull/2908

**Comment by michaelpj** [comment]
I really have no idea what's going on here. I might just temporarily make the circleci jobs not required.

**Comment by uhbif19** [comment]
@michaelpj Does not Circle CI has logs or something to see for somebody with correct access rights?

**Comment by michaelpj** [comment]
https://app.circleci.com/pipelines/github/haskell/haskell-language-server?filter=all

The problem is that this is all very well for figuring out what's going on with a particular run, but I'm not sure it helps working out why runs aren't being triggered.

**Comment by michaelpj** [comment]
I haven't seen this in a while, so I'm going to close this for now, please reopen if it recurs.
