### ISSUE TITLE
Rename plugin doesn't work with NamedFieldPuns

### ISSUE THREAD

**Issue by santiweight** [haskell/haskell-language-server#2970]
The environment doesn't matter here: just a plugin bug...

### Steps to reproduce
Rename the following `field` to something else using the rename plugin

```
{-# LANGUAGE NamedFieldPuns #-}
newtype Foo = Foo { field :: Int }

unFoo :: Foo -> Int
unFoo Foo{field} = field
```

### Expected behaviour
I think the best UX should be that renames compose with bindings incurred by NamedFieldPuns

### Actual behaviour
The output is instead:

```
{-# LANGUAGE NamedFieldPuns #-}
newtype Foo = Foo { bleh :: Int }

unFoo :: Foo -> Int
unFoo Foo{bleh} = field
```
i.e. the field reference in the binding site is renamed, but not the subsequent reference on the RHS of unFoo

**Comment by santiweight** [comment]
I'm happy to take this on, but it's not immediately clear to me what the solution is. The result returned from hie-db is a [RefRow](https://hackage.haskell.org/package/hiedb-0.4.1.0/docs/HieDb-Types.html#t:RefRow), which appears only to be a location and the OccName.

I see two options:
 1. Have NamedFieldPuns return the RHS reference to `field` as a reference to `field`. I don't think this is a good solution, because I don't think the RHS reference _is_ a reference to the field; it's more a reference to the punned field binding.
 2. Do a subsequent pass for each punned field binding. In other words, if RefRow returned information about whether this reference is a punned field, then we could do a second pass on these punned fields.

I'm happy to take this on: someone more hie-savvy please tell me the preferable option (or some other option I didn't think/know of)

**Comment by July541** [comment]
Same as #2915?

**Comment by michaelpj** [comment]
cc @OliverMadine

**Comment by OliverMadine** [comment]
Sorry for the delay in following up on this.
This is a different issue to  #2915. I will open a PR shortly.
