### ISSUE TITLE
Missing "Remove all redundant imports" in code action suggestions with neovim and coc.nvim

### ISSUE THREAD

**Issue by Disco-Dave** [haskell/haskell-language-server#2972]
### Your environment

Which OS do you use: Arch Linux
Which LSP client (editor/plugin) do you use: Neovim with CoC
Describe your project (alternative: link to the project): [example-cabal-package](https://gitlab.com/Disco-Dave/nvim-coc-hls/-/tree/main/example-cabal-package)

#### Using dockerized example scenario

[repo](https://gitlab.com/Disco-Dave/nvim-coc-hls)

```
git clone git@gitlab.com:Disco-Dave/nvim-coc-hls.git
cd nvim-coc-hls
./start.sh
```
This should start neovim inside of a docker container with neovim opened to [Example.hs](https://gitlab.com/Disco-Dave/nvim-coc-hls/-/blob/main/example-cabal-package/Example.hs). Navigate to line 19 which is a redundant import of `for_` and `traverse_`. Try any of the code actions described in the comment above.

#### Hand crafted
Install neovim and coc.nvim. Create a cabal project with `-Wunused-imports` enabled. Write a redundant import and run code actions on the line.

### Expected behaviour
In VS Codium it will suggest "Remove all redundant imports".
![expected.png](https://gitlab.com/Disco-Dave/nvim-coc-hls/-/raw/main/expected.png)

### Actual behaviour
However with neovim and coc.nvim it only suggests the following:
![actual.png](https://gitlab.com/Disco-Dave/nvim-coc-hls/-/raw/main/actual.png)

### Include debug information
- ghc 8.10.7
- cabal 3.6.2.0
- haskell-language-server 1.7.0.0
- neovim 0.7.0
- coc.nvim, sha `2522eee57d18aea040f4def29f2b8e9c69b5690c`

**Comment by michaelpj** [comment]
Can you look at the log of the communication between the client and the server and see if the code actions are being advertised to the server?

It may also be the case that coc.vim is not advertising the client capabilities that are necessary for us to provide code actions, although that seems strange.

**Comment by Disco-Dave** [comment]
I went to reproduce the issue so I could grab the logs and found that it works now. With that being said, I think we can close this issue. If you disagree, feel free to open it back up.

![Screenshot_2022-08-11_18-00-24](https://user-images.githubusercontent.com/13578196/184250239-08255ec4-d9de-4678-b8cd-7fde21c51ed2.png)
