### ISSUE TITLE
Expose other ghc versions in the flake

### ISSUE THREAD

**Issue by MangoIV** [haskell/haskell-language-server#2976]
**Is your feature request related to a problem? Please describe.**

At the moment there's just ghc922 and ghc902 exposed. ~~Is there a specific reason for that? I use a version of `nixpkgs` that doesn't have ghc922 but I would still like to use the flake outputs of `haskell-language-server`.~~
Edit: I see that the ghc version 921 was explicitly removed, because of nixpkgs removing it as well but I think it's agreeable that there are a couple of projects who don't or cannot follow the newest nixpkgs.  

**Describe alternatives you've considered**

Obviously you could just compile it from the src directory and use it as a normal haskell packages but that kinda makes the flake useless for my usecase, I guess...

~~**Additional context**~~

**Comment by michaelpj** [comment]
How would we expose other versions? We'd have to pin an older nixpkgs too.

**Comment by michaelpj** [comment]
TBH I agree that the flake is not really useful for distribution. You're better off installing it from nixpkgs.

**Comment by MangoIV** [comment]
maybe we could just expose `mkExe` and the respecting helpers for `ghc92` and `ghc90`in the outputs? But yeah, I think for now I might just go with the hls from `nixpkgs`, as the one in `haskell.nix` doesn't build...
Thanks for your help and answers!

**Comment by MangoIV** [comment]
maybe you could also just pin an older `nixpkgs` version until it gets updated to the *then new* version, so you basically have one version in the buffer...

**Comment by michaelpj** [comment]
I'm going to close this because I can't see any way for us to do this easily, please reopen if you can think of things.
