### ISSUE TITLE
Docs: Video does not render for hls-selection-range-plugin in features

### ISSUE THREAD

**Issue by sloorush** [haskell/haskell-language-server#3001]
### Your environment

Which OS do you use: NA

Which LSP client (editor/plugin) do you use: NA

Describe your project (alternative: link to the project):  NA

### Steps to reproduce

Visit https://haskell-language-server.readthedocs.io/en/latest/features.html#selection-range

### Expected behaviour

The video should be rendered, all other videos on the page are .gif files.

### Actual behaviour

It is a .mov file and does not render in the documentation
![image](https://user-images.githubusercontent.com/54478821/176459171-cb7b0a82-cb8d-46e5-a29a-71552c8992cf.png)

### Include debug information

The file should be replaced by a gif instead [here](https://github.com/sloorush/haskell-language-server/blob/0b8c793dfdf0d6adb1d4704343fa512c7646a15a/docs/features.md?plain=1#L326)

**Comment by sloorush** [comment]
Also the URL for the `shrink/expand selection` has been changed to https://code.visualstudio.com/docs/editor/codebasics#_shrinkexpand-selection over [here](https://github.com/sloorush/haskell-language-server/blob/0b8c793dfdf0d6adb1d4704343fa512c7646a15a/docs/features.md?plain=1#L323)

**Comment by kokobd** [comment]
Fixed in master, closing.
