### ISSUE TITLE
Add placeholders for all class instance methods

### ISSUE THREAD

**Issue by July541** [haskell/haskell-language-server#3017]
In #2920, we've got all class instance methods and dropped them immediately. So it's not hard to pick them up and supply `add placeholder for xxx` even if they are not the minimal requirements.

The main point is how to display these code actions properly because there may be so many items. Reference: https://github.com/haskell/haskell-language-server/pull/2920#discussion_r890959437

I'm willing to offer help if someone plans to pick this:)

**Comment by July541** [comment]
@batkot Thank advance for your interest!

If I do this, I'll first display all methods in code action and then give them a tidy look for users.

Please feel free to let me know if you meet any troubles!

**Comment by batkot** [comment]
Finally I managed to find some time to work on this (sorry for delay).

> If I do this, I'll first display all methods in code action and then give them a tidy look for users.

Not sure if I'm getting you right, but what I was able to quickly hack is single (well make it 2, counting `with signature(s)` :wink:) code action for adding placeholders for all not implemented type class methods. 

![image](https://user-images.githubusercontent.com/2933458/184224593-e37124c3-1062-4a00-ae4d-cd8e671a4d10.png)

I'm wondering if some kind of action (or lens?) for adding placeholders for not implemented methods even when minimal requirements are meet would be useful? E.g. creating placeholder for `(/=)` when `(==)` is implemented :thinking:

**Comment by July541** [comment]
It may be quite a lot of methods for one class, import them at one time looks crazy, I prefer something like this, a secondary list to select methods one by one.
![image](https://user-images.githubusercontent.com/16057632/184354106-ddc238d9-4a62-446c-aa48-533c51496dd4.png)

> I'm wondering if some kind of action (or lens?) for adding placeholders for not implemented methods even when minimal requirements are meet would be useful? E.g. creating placeholder for (/=) when (==) is implemented

In most cases, it's useless, but implementing this to supply for corner cases is worth I think.

**Comment by batkot** [comment]
Hi again. Time for monthly update, I guess :sweat_smile: 

> I prefer something like this, a secondary list to select methods one by one.

What kind of secondary list are we talking about? Some kind of "expandable/searchable submenu" or just appending additional items (one per not implemented method)? I'm not sure how to achieve the former (if it's possible, I'd love some directions) and the latter can result in pretty big code action lists (e.g. list of 34 items for `Foldable` feels overwhelming :confused:) Maybe breaking it into "2 stages" is a good idea? First we could suggest placeholders to fulfil minimal requirements and when they're met we could suggest placeholders for other missing methods :thinking: Or maybe as it was suggested in linked PR, we should drop `with signature(s)` variant of code action, since it would cut in half number of items on list.

**Comment by July541** [comment]
> Some kind of "expandable/searchable submenu" or just appending additional items (one per not implemented method)?

The first one I think. I don't know what is in vscode(I tried to go through the lsp doc but found nothing), but some other language servers have this.

At least we can have **only one** code action to add unnecessary methods once, though people won't use it very often.

**Comment by batkot** [comment]
I did some digging and as you said it looks like LSP doesn't [support any kind of CodeAction groupings/filtering](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.18/specification/#textDocument_codeAction). I found [this issue for LSP extension](https://github.com/microsoft/language-server-protocol/issues/994), that HLS might support. However it seems a bit forgotten and it's not supported by vscode (and probably other IDEs) by default, so it's probably not worth it.

Other LSPs implement their own ux in vscode extensions  (e.g. [Java](https://github.com/redhat-developer/vscode-java/blob/ccb75b154c03928d60a2ef423ddfd960fb3b43d9/src/sourceAction.ts#L269), [Rust](https://github.com/rust-lang/rust-analyzer/blob/791cb87cdf47ddfd2a2b1a726dab3aa66ec2bff3/editors/code/src/client.ts#L51). [Roslyn*](https://github.com/allisonchou/roslyn/blob/a972be7d74b5d8a4217dfbc66d417eac130c5439/src/Features/LanguageServer/Protocol/Handler/CodeActions/CodeActionHelpers.cs#L106)). *This one is probably for VS. 

One low hanging fruit, that kind of works, would be to use different `CodeActionKind` for implementing minimal requirements and other methods, e.g. vscode separates QuickFixes, Refactor and Source CodeActionKinds into different context menus. We could use that to our advantage, it could look more or less like this:

Implement minimal requirements in QuickFixes `Ctrl + .`:
![image](https://user-images.githubusercontent.com/2933458/203866300-74ca35db-2fca-49e3-a8d4-d0ec99512c8f.png)

Implement any missing method in Source Action Context Menu:
![image](https://user-images.githubusercontent.com/2933458/203866380-858547d2-a74e-482a-9927-d4d472d83aad.png)

However it still gets messy for Foldable. I'd just drop the `with signature(s)` action here:
![image](https://user-images.githubusercontent.com/2933458/203866548-accca000-ba4f-4d73-8c97-9043e2bb7e78.png)


Downside is that other clients might not group CodeActions by their Kind (e.g. CoC):
![image](https://user-images.githubusercontent.com/2933458/203866784-de1e17e3-b07f-4313-ac60-115794c9e1be.png)

Sorry for lengthy post. TL;DR:

We have few options:
1. Use `source.*` CodeActionKind for "implement missing method" CodeAction to separate it from QuickFixes in VSCode
2. Implement custom UI/action handling in [VSCode extension](https://github.com/haskell/vscode-haskell) - similiar to what `vscode-java` and `rust-analyzer` do.
3. Create just single action for adding placeholder for all missing class methods.
4. Other ideas? :thinking: 

Both 1. and 2. are VSCode centric and could lead to CodeAction spam in other IDEs, but that could probably be mitigated by configuration/clientCapabilities :thinking:

**Comment by July541** [comment]
Option 2 looks better to me.

Any suggestion? @michaelpj
