### ISSUE TITLE
Code action for "Avoid lambda" hint doesn't replace with the recommended code

### ISSUE THREAD

**Issue by feature-not-a-bug** [haskell/haskell-language-server#3020]
### Your environment

Which OS do you use:

Debian testing in a Windows wsl2 instance

Which LSP client (editor/plugin) do you use:

Neovim+nvim-lspconfig

```
$ haskell-language-server-wrapper --probe-tools
haskell-language-server version: 1.7.0.0 (GHC: 9.2.2) (PATH: /home/deepak/.ghcup/hls/1.7.0.0/lib/haskell-language-server-1.7.0.0/bin/haskell-language-server-wrapper)
Tool versions found on the $PATH
cabal:          3.6.2.0
stack:          2.7.5
ghc:            9.2.3
```

### Steps to reproduce

```
foo :: [a] -> [a]
foo = foldl (\xs x -> x : xs) []
```

This produces a hint
```Diagnostics:
1. Avoid lambda
Found:
    \ xs x -> x : xs
Why not:
    flip (:)
```
Running a code action seems to insert the recommended code without the brackets on the cons

### Expected behaviour

Should replace with `flip (:)`

### Actual behaviour

Replaces with `flip :` which results in a type mismatch

**Comment by michaelpj** [comment]
The edit we send back is definitely wrong, and that's generated by `apply-refact`. Can you try again with debug logging enabled, I'm looking for the line corresponding to this (https://github.com/haskell/haskell-language-server/blob/master/plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs#L551) which should show us the `apply-refact` stuff that gets generated.

**Comment by michaelpj** [comment]
Here's the relevant bit:

> 'Generated hlint ideas for for NormalizedFilePath "/home/deepak/code/haskell/foo/foo.hs": [[Replace {rtype = Expr, pos = SrcSpan {startLine = 2, startCol = 14, endLine = 2, endCol = 29}, subts = [("x",SrcSpan {startLine = 2, startCol = 25, endLine = 2, endCol = 26})], orig = "flip x"}]]'

I'm actually not entirely sure how to interpret this, need to figure out what it means to know if it's making the wrong suggestion or what.

**Comment by michaelpj** [comment]
Ah, an easy way to tell whether it's us or `hlint` is to run `hlint --refactor` on the file and see if it also does the wrong thing. If so then it's definitely an `apply-refact` bug.
