### ISSUE TITLE
Smart eta reduce suggestions with or without deep subsumption

### ISSUE THREAD

**Issue by theGhostJW** [haskell/haskell-language-server#3026]
Following the introduction for [simplified / deep subsumption](https://www.youtube.com/watch?v=XMnXbBRg-B0) the old hlint eta reduce suggestion wont work correctly with simplified subsumption, at times suggestion eta reduction where ghc would disallow the same.  As **hlint does not use types there is no way for hlint to make the distinction between valid and invalid eta reduction when simplified subsumption is active**. Discussed in the [following hlint issue](https://github.com/ndmitchell/hlint/issues/1107). 

The following example is copied directly from  this issue:
```Haskell
{-# LANGUAGE RankNTypes #-}

g :: forall a. () -> a
g x = undefined

f :: () -> forall a. a
f x = g x
```

hlint will recommend eta-reducing the latter definition to f = g. But while this is fine under GHC 8.10, it fails under GHC 9:
```bash
    • Couldn't match type ‘a0’ with ‘forall a. a’
      Expected: () -> forall a. a
        Actual: () -> a0
      Cannot instantiate unification variable ‘a0’
      with a type involving polytypes: forall a. a
    • In the expression: g
      In an equation for ‘f’: f = g
```
The user needs to either turn off the hint altogether or leave the hint on and fully understand the issue and know how to disable hlint for those cases where hlint gets it wrong.

**Describe the solution you'd like**

It would be great if hls could make eta reduce suggestions correctly. In order to do this hls would need to know:

1. is the eta reduction hint enabled via an hls config option?
2. is eta reduction structurally applicable? i.e same rules as hlint currently uses
2. does simplified subsumption apply? (i.e. is the ghc version > 9 and simplified subsumption has not been deactivated by the deep subsumption extension)
3. if simplified subsumption does apply then does the type of the expression allow eta reduction under simplified subsumption?

**Describe alternatives you've considered**

Living with the incorrect suggestions from hlint (as described above) or disabling the the option in hlint. Options discussed in linked hlint issue.

**Additional context**

This feature request is really just a means to automate [this workflow](https://www.reddit.com/r/haskell/comments/ujpzx3/comment/i7kquyl/?utm_source=share&utm_medium=web2x&context=3)

**Comment by michaelpj** [comment]
I'm personally a :-1: on trying to fix up the behaviour of tools that we provide support for. This is fundamentally an issue with hlint, we just pass on what hlint says. Don't like hlint? Turn it off or turn off that hint.

If there was a way we could provide hlint with additional information so it could do better, that would be fine, but I don't think we want to get into trying to post-process it's output.

**Comment by theGhostJW** [comment]
> I'm personally a 👎 on trying to fix up the behaviour of tools that we provide support for. This is fundamentally an issue with hlint, we just pass on what hlint says. Don't like hlint? Turn it off or turn off that hint.

Just to be clear this feature request is a request for reliable eta reduce suggestions. The fact that hlint was able to provide this (< ghc 9.0) is kind of irrelevant. The feature request strays into a not so well thought out solution which I will remove.  Such functionality would need to be in, or part of, a separate plug in and the hlint suggestion turned off (it's soon to be default state). 

This is for the benefit of users who 1) love hlint, 2) use to love the eta reduce hint and 3) want to follow best practice and leave simplified subsumption on post ghc 9.

> If there was a way we could provide hlint with additional information so it could do better, that would be fine, but I don't think we want to get into trying to post-process it's output.

hlint is a text interpreter and does not use types so I don't think this is a case of hlint "needing to do better". Its a case of ghc becoming more rigorous and moving the problem beyond the constraints of can be achieved with such a tool.

**Comment by michaelpj** [comment]
I think the decision here was the right one, and there haven't been more requests, so I'm going to close this.

**Comment by theGhostJW** [comment]
Sounds good, might be something that could be implemented in Stan anyway
