### ISSUE TITLE
Project requires GHCup but isn't installed

### ISSUE THREAD

**Issue by bolanzach** [haskell/haskell-language-server#3032]
### Your environment

Which OS do you use:
MacOS
Which LSP client (editor/plugin) do you use:
VS Code haskell plugin

### Steps to reproduce
I know this is a pretty basic question but im stuck. Im starting off trying to learn haskell and up to this point have just been using `ghci` to get familiar with the syntax, so excuse my lack of understanding what all the build tools are.

- I had already installed ghcup - I see it and cabal on my PATH. I have no issues compiling and running single .hs file with ghc
- Installed the Haskell VSCode extension and selected to find the language server from GHCup

### Expected behaviour
All the sweet goodness from the language server

### Actual behaviour
I get `Project requires GHCup but it isn't installed`

### Include debug information
ghcup is pretty clearly installed but the extension cant find it? Or possibly the extension cant find HLS?

In [troubleshooting](https://haskell-language-server.readthedocs.io/en/latest/troubleshooting.html) i see references to `haskell-language-server`. Im not sure if this is the same as hls, which is installed with ghcup:

```
ghcup install hls                                                                                                                                                     127 ↵ ──(Sun,Jul10)─┘
[ Info  ] downloading: https://raw.githubusercontent.com/haskell/ghcup-metadata/master/ghcup-0.0.7.yaml as file /Users/zach/.ghcup/cache/ghcup-0.0.7.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
[ Warn  ] New ghc version available. To upgrade, run 'ghcup install ghc 9.2.3'
[ Warn  ] HLS ver 1.7.0.0 already installed; if you really want to reinstall it, you may want to run 'ghcup install hls --force 1.7.0.0'
```

Im not sure what else i can add - again im just learning so I dont know what i dont know. feel free to let me know and I can add whatever else is needed to debug.

**Comment by drsooch** [comment]
> In troubleshooting i see references to haskell-language-server. Im not sure if this is the same as hls, which is installed with ghcup:

They are the same thing, yes. 

As for not finding ghcup on your path, VSCode has some weird PATH rules in my experience. As a workaround (for now) you can change the setting in the plug-in to use a direct path to the hls binary (which is located under your ghcup install folder).

You can check out the [vscode-haskell](https://github.com/haskell/vscode-haskell) plug-in docs for more information.

**Comment by bolanzach** [comment]
Thanks for getting back!

_I uninstalled the extensions again and restarted and its seems to work now ha._

Not sure what happened, I tried various settings like:
```json
{
  "haskell.manageHLS": "PATH",
  "haskell.serverExecutablePath": "~/.ghcup/bin/haskell-language-server-8.10.7",
  "haskell.ghcupExecutablePath": "~/.ghcup/bin"
}
```
And still wasnt able to get it working 😕 

I dont have any settings overrides anymore so Im not entirely sure what went wrong. i ran HLS a few times manually, i dont think that would have anything to do with it but thats the only thing I remember doing differently before restarting. In any case its working and im excited to explore more haskell!

**Comment by D3usXMachina** [comment]
I ran into the same problem (Manjaro, OSS Code).
For me the solution was to specify the **full** paths to the respective executables:

```
"haskell.manageHLS": "GHCup",
"haskell.ghcupExecutablePath": "~/.ghcup/bin/ghcup",
"haskell.serverExecutablePath": "~/.ghcup/bin/haskell-language-server-9.4.4"
```

**Comment by fendor** [comment]
Iirc, the last line will force the plugin to always use that HLS version, so you probably shouldn't use that.
