### ISSUE TITLE
Parse error when adding def to trailing-comma import list

### ISSUE THREAD

**Issue by georgefst** [haskell/haskell-language-server#3039]
```hs
import Prelude (
  Bool,
 )

x = not
```

Running the code action to add `not` results in:

```hs
import Prelude (
  Bool,, not
 )

x = not
```

`HEAD` (445192e21daa4f4973e60a13e748ffa910819e79) with GHC 9.2.3. I'm pretty sure this is a regression since the last release.

**Comment by kokobd** [comment]
Duplicate of #2958? I'm trying to fix it in #3035.
