### ISSUE TITLE
Wingman should be able to autocomplete missing function patterns 

### ISSUE THREAD

**Issue by NiekPas** [haskell/haskell-language-server#3041]
**Is your feature request related to a problem? Please describe.**

Given the following code:

```
data CardinalDirection = N | E | S | W

instance Show CardinalDirection where
    show N = "N"
```

GHC complains (as it should) that:

```
app/CardinalDirection.hs:6:5: warning: [-Wincomplete-patterns]
    Pattern match(es) are non-exhaustive
    In an equation for ‘show’:
        Patterns not matched:
            E
            S
            W
  |
6 |     show N = "North"
  |     ^^^^^^^^^^^^
```

However, Wingman is not able to autocomplete the rest of the patterns.

**Describe the solution you'd like**

I'd like Wingman to be able to complete the function patterns.

**Describe alternatives you've considered**

I don't see any alternatives but am open to them.

**Additional context**

So Wingman _can_ actually do this (`case split on x`), but it only suggests this completion for the following code example:

```
data CardinalDirection = N | E | S | W

instance Show CardinalDirection where
    show x = _
```

Seems to be this functionality should be transferable to the given problem.

**Comment by Ailrun** [comment]
Could you suggest more explicit steps for the suggested feature? Namely, which hole should wingman work on?

**Comment by NiekPas** [comment]
I'd say that Wingman should suggest autocompleting the function patterns. E.g., in an editor like VS Code, I'd like to be able to `cmd+.` over `N` in `show N = "N"` and see "Wingman: complete function patterns", which, when activated, completes the code to:

```
instance Show CardinalDirection where
    show N = "N"
    show E = _
    show S = _
    show W = _
```

(This is the functionality `case split on x` already provides.)

Let me know if I'm not making myself clear.
