### ISSUE TITLE
Unreadable unicode in type-level literals

### ISSUE THREAD

**Issue by dpwiz** [haskell/haskell-language-server#3115]
### Your environment

* ghcup-compiled LSP from a recent-ish master
* VS Code extension v2.2.1
* GHC 9.2.4
* Ubuntu

### Steps to reproduce

```haskell
type family (label :: Symbol) ::: a where
  label ::: a = a

type Example = "привет" ::: Int

x :: Example
x = 4
```

Hover over `4` to see its type.

### Expected behaviour

The label should be preserved since it's a valid Haskell symbol: `_ :: "привет" ::: Int`.

### Actual behaviour

The label escaped into `_ :: "\1087\1088\1080\1074\1077\1090" ::: Int`.

![Capture d’écran du 2022-08-19 15-19-08](https://user-images.githubusercontent.com/486682/185621732-c2f6ac5a-cccb-4a1f-a3ca-bf49b93c482f.png)

**Comment by michaelpj** [comment]
Our handling of unicode is pretty broken in general, but we should at least render it properly in hovers. I have a suspicion that this may ultimately be https://gitlab.haskell.org/ghc/ghc/-/issues/20027, however. So the solution may mean replacing some deep usage of `Show` with something better behaved... probably from `text`.

**Comment by dpwiz** [comment]
20027 was [superceded](https://github.com/haskell/core-libraries-committee/issues/25) then withdrawn. I'd expect no improvement from the `Show` side.

**Comment by kokobd** [comment]
I located the line producing the message:
https://github.com/haskell/haskell-language-server/blob/5b229b631fbc3b53fdacd1092aacb55f8f2de4a3/ghcide/src/Development/IDE/Spans/AtPoint.hs#L254
`printOutputable` indirectly calls this function in `ghc`: https://hackage.haskell.org/package/ghc-9.2.4/docs/src/GHC.Iface.Type.html#pprIfaceTyLit

```haskell
pprIfaceTyLit :: IfaceTyLit -> SDoc
pprIfaceTyLit (IfaceNumTyLit n) = integer n
pprIfaceTyLit (IfaceStrTyLit n) = text (show n)
pprIfaceTyLit (IfaceCharTyLit c) = text (show c)
```

You see, it calls `show` on a `FastString`. `Show` for `FastString` is defined by converting to `String` then call `show` on `String`.
