### ISSUE TITLE
Evaluate/Refresh links missing following multiple-equation definitions

### ISSUE THREAD

**Issue by jgbm** [haskell/haskell-language-server#3129]
### Your environment

Which OS do you use: Windows, MacOS

### Steps to reproduce

Doctest comments following definitions with multiple equations don't get "Evaluate" or "Refresh" popups.

Example interaction: ![VS Code Equations](https://user-images.githubusercontent.com/1005589/187291826-b8182b96-f4ca-490a-ae57-f3a8fc9a8464.gif)

### Expected behaviour

The "Evaluate" and "Refresh" links should be present

### Actual behaviour

The "Evaluate" and "Refresh" links are not present.

**Comment by jfong2702** [comment]
I am having the same issue how do I fix it?

**Comment by fendor** [comment]
Closing this in favour of #3312 as a duplicate
