### ISSUE TITLE
Documentation: Configuration in README

### ISSUE THREAD

**Issue by andys8** [haskell/haskell-language-server#313]
The configuration of `haskell-language-server` is currently not documented in the `README.md`.

https://github.com/haskell/haskell-language-server/blob/bda4058011ea422379a1555b3c1725c870fba92b/src/Ide/Plugin/Config.hs#L44-L54

See [documentation of configuration in `haskell-ide-engine`](https://github.com/haskell/haskell-ide-engine#configuration) for comparison.

**Comment by bubba** [comment]
As far as I'm aware, the only one of these config settings that has any affect is `formattingProvider`

**Comment by andys8** [comment]
Oh, didn't know. So, adding only `formattingProvider` to the docs could help avoid confusion.

**Comment by jneira** [comment]
A configuration section was added after this issue: https://github.com/haskell/haskell-language-server#language-specific-server-options
It mentions the actual working options, @andys8 please reopen this (or open a new issue) if you miss something in the actual version
