### ISSUE TITLE
[Feature Request] Auto complete in imports

### ISSUE THREAD

**Issue by GuillaumeDesforges** [haskell/haskell-language-server#314]
Feature request

Say I start writing:

```haskell
import Data.Map (
```

I'd like to have autocomplete that proposes what I can import from this module, with its doc/type signature.

This is a common feature in other module-based programming languages IDE/LSP.

**Comment by jneira** [comment]
I would say this should be added in ghcide

**Comment by jneira** [comment]
Afaiu this was fixed by #2152 (although it stil is  not released)
