### ISSUE TITLE
How to use a project file other than `cabal.project`

### ISSUE THREAD

**Issue by clintonmead** [haskell/haskell-language-server#3142]
## Your environment 

Which OS do you use?

MacOS

Which version of GHC do you use and how did you install it?

9.2.2 from Nix

How is your project built (alternative: link to the project)?

Cabal inside `nix develop`

Which LSP client (editor/plugin) do you use?

VSCode

Which version of HLS do you use and how did you install it?

1.7.0.0 from Nixpkgs

Have you configured HLS in any way (especially: a `hie.yaml` file)?

## What's wrong?

I have a project, which I generally build in the following way:

```
nix develop
cabal build all --project-file=cabal-dev.project
```

We can alternatively do a `nix build`, and the CI process uses that, but for local development either a `cabal build` or `nix build` works fine.

In my main project directory, I have two `.project` files, namely:

```
cabal.project
cabal-dev.project
```

`cabal.project` is our ordinary cabal file. It has fairly strict set of warnings, and `-Werror` is on. This is what our build happens under.

But for day to day development, this strict set of warnings is annoying. You'll often have unused imports, variables etc, and I also like using "Typed Holes" library to stub things during development, but obviously I don't want them to pass CI.

So there's a second project file, named `cabal-dev.project`, that looks like the following:

```
import: cabal.project

optimization: 0

program-options
  ghc-options:
    -Wno-unused-top-binds -Wno-unused-matches -Wno-unused-imports -Wno-unused-packages 
    -Wno-missing-signatures 
    -fdefer-typed-holes -Wwarn=typed-holes
    -XPartialTypeSignatures -Wwarn=partial-type-signatures
```

Basically, turning off a bunch of warnings. This works quite nicely in Cabal 3.8 and turns off the warnings for all local packages. I can then do "dev" builds with `cabal build all --project-file=cabal-dev.project` whilst "release" builds use the usual `cabal build all`. So whilst our CI system doesn't know about `cabal-dev.project` as developers we can use a loosened set of warnings/errors so we can use typed holes/top level bindings without types whilst hacking together a PR and clean them up before pushing.

So I have set HLS in VSCode to search for things via path. But I'm getting errors like the following:

```
Failed to parse result of calling cabal
Failed command: cabal ...

...

error: [-Wunused-imports, -Werror=unused-imports]    
The import of ‘Control.Monad’ is redundant
```

I _think_ what is happening is that HLS is recognising this is a `cabal` project, and then building it using the `cabal.project` file for it's settings, which means there's a whole lot of stuff I'm getting errors for in HLS when I really would prefer the `cabal-dev.project` settings were used and I didn't get errors for things I didn't care about at this stage of development. 

Is there any way that I can hint to HLS in VSCode to use a different project file other than the "default"?

(note if this is an issue particular to the VSCode plugin please say and I'll raise this issue there)

**Comment by michaelpj** [comment]
I believe you will be able to do what you specifically ask for with a `hie.yaml` once https://github.com/haskell/hie-bios/pull/357 is done.

**Comment by clintonmead** [comment]
@michaelpj we use `cabal build all --project-file=cabal-dev.project` for "dev" builds. Sorry I've now edited the OP to make clearer regarding this.

Why aren't I using `cabal.project.local`? Because I've never heard of it. Note I don't want `cabal build all` to be affected, nor any nix derivations, as the whole point of this exercise is to allow as to keep our CI processes quite strict.

**Comment by michaelpj** [comment]
https://cabal.readthedocs.io/en/stable/cabal-project.html?highlight=cabal.project.local#cabal-project-reference

It's commonly not checked in to git and used for developer-local settings, which sounds like it might match your usecases. Or conversely you could have a special project file you only use in CI.
