### ISSUE TITLE
run HLS as a TCP server

### ISSUE THREAD

**Issue by teto** [haskell/haskell-language-server#3151]
## Is your enhancement request related to a problem? Please describe.

HLS takes a few seconds to startup when I start my editor

## Describe the solution you'd like

I would like to run HLS as a TCP server so that I can open/close my editor as I wish and just connect to an always running LSP server.

## Describe alternatives you've considered

with the help of netcat/socat I think this is achievable and I may try soon but I wanted to put the request out there.

## Additional context
neovim added support for this kind of scenario 1 maybe 2 weeks ago and I was eager to try.

**Comment by michaelpj** [comment]
Are there any other language servers that support this?

**Comment by pepeiborra** [comment]
Are you using the VSCode extension? If so, you can speed up startup by pointing it to the exact HLS binary and skipping the version discovery stuff

**Comment by michaelpj** [comment]
I don't think we're going to do this.
