### ISSUE TITLE
hie-bios revision in cabal.project is outdated, breaking fresh builds

### ISSUE THREAD

**Issue by TerrorJack** [haskell/haskell-language-server#3152]
As of now, `hie-bios` revision in `cabal.project` is `aa73d3d2eb89df0003d2468a105e326d71b62cc7`, shown at [here](aa73d3d2eb89df0003d2468a105e326d71b62cc7), however a force push seems to have invalidated that revision, which results in a `fatal: Could not parse object 'aa73d3d2eb89df0003d2468a105e326d71b62cc7'.` error when trying to build from scratch using ghc 9.4.2.

**Comment by fendor** [comment]
My apologies!

**Comment by wz1000** [comment]
I pushed a branch with this commit to my fork of hie-bios, so that should resolve this. In the meantime, #3150 contains the changes necessary to upgrade to the upcoming release of hie-bios, which we will start using from hackage as soon as it is ready.
