### ISSUE TITLE
Config: How to disable stan plugin

### ISSUE THREAD

**Issue by andys8** [haskell/haskell-language-server#3157]
Hey there, it's either currently not possible or I don't know how to exactly disable the stan plugin.

* Config is `"stan": { "globalOn": false }`
* [Docs](https://haskell-language-server.readthedocs.io/en/latest/configuration.html#generic-plugin-configuration) don't list `stan` plugin
* The default configuration (`haskell-language-server-wrapper generate-default-config`) doesn't have an entry for `stan`.

Is `globalOn` respected for this plugin?

![image](https://user-images.githubusercontent.com/13085980/190134161-025ae27a-eaba-4867-8fb6-9971a40b3fb0.png)

###  Vim

Still enabled, but expected to be off

![image](https://user-images.githubusercontent.com/13085980/190133625-629d1e75-d93e-4983-8ae2-218bd94a8be4.png)

### CLI

Still enabled, but expected to be off

![image](https://user-images.githubusercontent.com/13085980/190134550-4d9e4e45-f7a1-415b-854a-29e49aa087ab.png)

## Additional context

```
haskell-language-server-wrapper --probe-tools
haskell-language-server version: 1.8.0.0 (GHC: 9.2.4) (PATH: /home/andreas/.ghcup/bin/haskell-language-server-wrapper-1.8.0.0)
Tool versions found on the $PATH
cabal:          3.8.1.0
stack:          2.7.5
ghc:            9.2.4

Tool versions in your project
ghc:            8.10.7
```

**Comment by kokobd** [comment]
I'm not familiar with the dynamic config, but you can add `--constraint "haskell-language-server -stan"` to your cabal command if you were building HLS from source. In this way, stan plugin will be disabled at compile time.

**Comment by andys8** [comment]
I'm indeed compiling hls from scratch with `ghcup compile hls` and thanks for the hint. But I'm less interested in "fixing" this for me but to make sure configuration is working as expected for the project. Therefore I'm wondering if it can currently be disabled (like other plugins) and why it's missing in the documentation.

**Comment by pepeiborra** [comment]
Have you tried `"haskell.plugin.span.globalOn": false` ?

**Comment by andys8** [comment]
I'm starting to have doubts regarding the whole editor configuration. This way would not be the format `generate-default-config` suggests, but I'm having trouble to find any configuration that has an effect.

Could you point me to documentation showing how to configure Vim with Coc with plugin options?

* [CoC's example has no options](https://github.com/neoclide/coc.nvim/wiki/Language-servers#haskell)
* [Haskell language server documentation has no options](https://haskell-language-server.readthedocs.io/en/latest/configuration.html#coc)

**Comment by AnthonySuper** [comment]
I am also experiencing this issue.


COC config:

```json
{
  "languageserver": {
    "haskell": {
      "command": "haskell-language-server-wrapper",
      "args": ["--lsp"],
      "rootPatterns": ["*.cabal", "stack.yaml", "cabal.project", "package.yaml", "hie.yaml"],
      "filetypes": ["haskell", "lhaskell"],
      "settings": {
        "languageServerHaskell": {
          "plugin": {
            "stan": {
              "globalOn": false
            }
          }
        }
      }
    }
  }
}
```

If I change it to:

```json
{
  "languageserver": {
    "haskell": {
      "command": "haskell-language-server-wrapper",
      "args": ["--lsp"],
      "rootPatterns": ["*.cabal", "stack.yaml", "cabal.project", "package.yaml", "hie.yaml"],
      "filetypes": ["haskell", "lhaskell"],
      "settings": {
        "languageServerHaskell": {
          "plugin": {
            "stan": {
              "globalOn": false
            },
            "tactics": { "globalOn": false }
          }
        }
      }
    }
  }
}
```

Wingman is disabled. This suggests to me that the configuration is working, there's just no way to turn off `stan`.

The stan plugin also seems to be ignoring my `.stan.toml` file, for what it's worth.

**Comment by pepeiborra** [comment]
Found the bug - Stan diagnostics should be gated in the same way that hlint are:

https://github.com/haskell/haskell-language-server/blob/master/plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs#L199-L205

**Comment by andys8** [comment]
Funny that you bring up `hlint` because I tested with `hlint` to compare, and I wasn't able to disable `hlint` either. That's when I started doubting the configuration as a whole.

I assume disabling `hlint` is working for you, while stan isn't?

---

```json
            "hlint": {
              "globalOn": false,
              "codeActionsOn": false,
              "diagnosticsOn": false,
              "config": { "flags": [] }
            },
```

![image](https://user-images.githubusercontent.com/13085980/190360625-0cc093c4-3bb2-406c-b8dc-c9877fd01c3d.png)

**Comment by uhbif19** [comment]
@michaelpj Will try to fix on weekend.

**Comment by andys8** [comment]
@uhbif19 @michaelpj Here is a suggestion for a fix that works for me

https://github.com/haskell/haskell-language-server/pull/3179

**Comment by andys8** [comment]
https://github.com/haskell/haskell-language-server/pull/3179 merged, configuration should now work.

**Comment by m4lvin** [comment]
How can I disable the stan plugin when using **emacs with eglot**?

Above it says "Config is `"stan": { "globalOn": false }`" but where does this configuration go? Is it a config for HLS or editor-specific?

Alternatively, how can I tell HLS to ignore specific stan hints? As @AnthonySuper says above, the `.stan.toml` seems to be ignored.

Sorry to resurrect this issue, but I could not find the relevant documentation and still have these problems with HLS 1.9.0.0.

**Comment by jhrcek** [comment]
I'm not that familiar with config. options, but what helped me was to build hls from source with stan plugin disabled.
The `-f-stan` below is cabal flag which prevents stan plugin from being included in the final hls binary.

`ghcup compile hls -g master --ghc 8.10.7 --cabal-update -- -f-stan`

This assumes you're building hls to be used with ghc 8.10.7 (because AFAIK stan plugin only works with that version and is automatically disabled when building against more recent ghc versions)

**Comment by fendor** [comment]
> but where does this configuration go?

I think this is HLS specific, so in some HLS config you should specify that

**Comment by andys8** [comment]
Because I had trouble figuring out how the options should look like for Vim, I added an example with options to the [docs](https://haskell-language-server.readthedocs.io/en/latest/configuration.html). For emacs there is none. So in case you're able to tinker and find  out how plugins can be configured (it be quite similar to other emacs LS settings), it would be awesome to add a more detailed example to the docs afterwards.

**Comment by m4lvin** [comment]
Thank you all for the replies!

I now managed to disable stan in emacs with eglot, by putting the following in my `~/.emacs` :tada: 

```elisp
(use-package eglot
  :ensure t
  :config
  (add-hook 'haskell-mode-hook 'eglot-ensure)
  :config
  (setq-default eglot-workspace-configuration
                '((haskell
                   (plugin
                    (stan
                     (globalOn . :json-false))))))
  )
```
In particular, then with `M-x eglot-show-workspace-configuration` one can see the JSON config that eglot will send to the language server. See https://joaotavora.github.io/eglot/#Customizing-Eglot

As for editing the docs: Currently the whole emacs section assumes that `lsp-mode` is used and not `eglot`. So before I make a suggestion how to add this, would it be good to have separate (sub)sections for `Emacs with lsp` and `Emacs with eglot`?

(As far as I know newer versions of emacs ship with `eglot` by default, and not with `lsp-mode`.)

**Comment by michaelpj** [comment]
I'd be happy to have a section on `eglot`.  We just need an `eglot` user to write it, maybe that's you? :)
