### ISSUE TITLE
Release package permissions and file name

### ISSUE THREAD

**Issue by hyiltiz** [haskell/haskell-language-server#316]
I had to download the pre-built binaries from Github Release, unpack them, **`chmod +x` them and also remove `-Linux-` in their file name** before putting them into `$PATH`. The steps in bold weren't mentioned in the project Readme.md file. Better yet, would be easier if the file modes and names were set appropriately before archiving them for release.

**Comment by rgleichman** [comment]
I also encountered this recently when installing Haskell Language Server for the first time. The specific error I got in my Emacs `*hie::stderr*` buffer was

>Project GHC version: 8.8.3
haskell-language-server exe candidates: ["haskell-language-server-8.8.3","haskell-language-server-8.8","haskell-language-server"]
Cannot find any haskell-language-server exe, looked for: haskell-language-server-8.8.3, haskell-language-server-8.8, haskell-language-server
>Process hie stderr<1> finished
>Process hie stderr finished

**Comment by jneira** [comment]
It should not be difficult to change [the build script](https://github.com/haskell/haskell-language-server/blob/master/.github/workflows/build.yml) to change the name and set executable permisson (it it is not already done)
//cc @bubba

**Comment by bubba** [comment]
@jneira I think the ghcup .tar.gz bundles might fix this issue. Let me check to see if they have the correct permissions

**Comment by hyiltiz** [comment]
9689b83 seems to only address the exec permissions. The other part of the problem is the file name of the executable in the bundle. I think it is reasonable to mention `-Linux-` in the bundle name, but the exec should be ready to deploy once uncompressed, by a simple `cp` or `ln -s`, without also requiring a rename first.

**Comment by hyiltiz** [comment]
Hmm? Accidentally closed by the hook? From the patch that got merged, it doesn't seem to address the renaming yet.

**Comment by jneira** [comment]
@hyiltiz yeah, the pr was linked to this issue and closed it

**Comment by sloorush** [comment]
I was looking into the issue, but I believe this issue has been fixed in https://github.com/haskell/haskell-language-server/commit/34e9914f4edaa83c2e4a80dcba0c6375d4911da9. 

Is that correct?

**Comment by michaelpj** [comment]
The way that we distribute releases has changed hugely, so I suspect this is done!
