### ISSUE TITLE
Update supported ghc versions page

### ISSUE THREAD

**Issue by maralorn** [haskell/haskell-language-server#3172]
As a downstream maintainer, the https://haskell-language-server.readthedocs.io/en/latest/supported-versions.html page is immensely valuable to me. Currently, it doesn‘t inform about the state of ghc 9.4, although the changelog claims it is supported by quite a few plugins.

**Comment by michaelpj** [comment]
cc @wz1000 we need to remember to update this when adding support for new GHC versions.

**Comment by michaelpj** [comment]
https://github.com/haskell/haskell-language-server/pull/3186
