### ISSUE TITLE
Fails to provide HLS functionality

### ISSUE THREAD

**Issue by mouse07410** [haskell/haskell-language-server#3177]
## Your environment 

- **Which OS do you use?** MacOS Monterey 12.6
- **Which version of GHC do you use and how did you install it?** GHC-9.2.4 and 9.4.2, installed via ghcup
- **How is your project built?** via Cabal-3.8.1.0, but it’s irrelevant here, I think. 
- **Which LSP client (editor/plugin) do you use?**
 VS Code 1.72.1 + vscode-haskell 2.2.1
- **Which version of HLS do you use and how did you install it?** 1.8.0.0 from ghcup

## What's wrong?

Does not give documentation popup, code completion, suggestions, etc. Looks like HLS does not talk to VS Code plug-in. 

I can’t figure out why, especially since it used to work just fine with Monterey 12.5.1, HLS built from GitHub master via ghcup, and VS Code 1.72.

**Comment by pepeiborra** [comment]
Logs please?

**Comment by mouse07410** [comment]
> Logs please?

How do I get them? I'd love to send them over.

**Comment by michaelpj** [comment]
Have you read the troubleshooting page in the documentation?

**Comment by mouse07410** [comment]
> Have you read the troubleshooting page in the documentation?

Shame on me - I did not. Going through it now. Will report.
