### ISSUE TITLE
Reload HLS on dependency changes (change to package.yaml and .cabal file)

### ISSUE THREAD

**Issue by ArturGajowy** [haskell/haskell-language-server#3178]
## Is your enhancement request related to a problem? Please describe.

When adding a new dependency, one has to manually reload HLS (I'm using vscode).

## Describe the solution you'd like

HLS watches package.yaml or - when it's not present - .cabal files.
Upon change, server is restarted.

## Describe alternatives you've considered

Better yet: HLS understands which part of package.yaml / .cabal file corresponds to dependencies, reloads only on changes to those sections.

Even better, and easier: A modal / prompt is displayed before reload, similarly to what happens when HLS download is needed.

Thank you for considering this, and for all your great work for the Haskell ecosystem! :)

**Comment by pepeiborra** [comment]
HLS already does this, so please use the bug issue template and share logs and repros

**Comment by fendor** [comment]
For stack, the logic is a bit imprecise. Also, the reloading logic might take a noticeable amount of time, you have to patient, but in theory it should work.

**Comment by ArturGajowy** [comment]
now THAT's a quick fix :D I've tested again and it must've been a mindfart of mine + assuming this hasn't changed since I upgraded from 1.4.0.0 :) Sorry for the commotion. Closing, thank you!
