### ISSUE TITLE
hls-1.8.0.0 broken on Pop OS 20.04 due to missing GLIBC_2.34

### ISSUE THREAD

**Issue by decapo01** [haskell/haskell-language-server#3202]
This is the same issue as #3160 but with Pop!_OS 20.04 LTS.  I was asked on that thread to open up a new issue here.  Please let me know if I need to do anything else.

Which OS do you use?
Pop!_OS 20.04 LTS

Which version of GHC do you use and how did you install it?
8.10.7 ghcup

How is your project built (alternative: link to the project)?
stack

Which LSP client (editor/plugin) do you use?
VS Code+vscode-haskell

Which version of HLS do you use and how did you install it?
I reverted back 1.7.0.0, I believe it was installed with ghcup

Have you configured HLS in any way (especially: a `hie.yaml` file)?
No
### Steps to reproduce
On Pop! os install vscode, the haskell extension and ghcup.  I believe vscode will use ghcup to install the newest version of HLS but if it doesn't one can install it manually with ghcup.

### Expected behaviour
The language server and client start normally.

### Actual behaviour
The server fails to start with the error `version GLIBC_2.32 not found`

### Debug information
Install the previous version of the HLS and see if it works maybe.

**Comment by michaelpj** [comment]
Closing as this is old and distribution has changed a bunch
