### ISSUE TITLE
Bogus "Duplicate instance declarations:" error

### ISSUE THREAD

**Issue by mouse07410** [haskell/haskell-language-server#3237]
### Your environment

- MacOS Monterey 12.6 with Xcode-14
- GHC-9.4.2
- Cabal-3.8.1.0
- HLS 1.8.0.0 installed via `ghcup`
- hlint v3.4.1
- VS Code 1.71.2 with `vscode-haskell` (Haskell for VIsual Studio Code) v2.2.1

### Steps to reproduce and Actual behavior

At some point in time, HLS complains about "Duplicate instance declarations" which don't make sense because both refer to the **same** definition - same file and line number (aka, the same place).

Here's an example:
```
Duplicate instance declarations:
  instance Functor Point3D
     -- Defined at /Users/ur20980/src/stepic-tests/src/Lib.hs:523:10
  instance Functor Point3D
     -- Defined at /Users/ur20980/src/stepic-tests/src/Lib.hs:523:10  typecheck
```

### Expected behaviour

Understand that one entry in one file is not a duplicate of itself?

### Debug information

This is an intermittent problem. Usually it clears up when I restart HLS within VS Code (don't even need to restart VS Code itself).

**Comment by lf-** [comment]
I've also hit this recently on ghc-9.4.2. My wild speculation is that it might be something like is described in this section, related to mishandling of multiple home units: https://well-typed.com/blog/2022/01/multiple-home-units/#closure-property-for-home-units

**Comment by mouse07410** [comment]
> . . . mishandling of multiple home units . . .

I don't know - but I doubt that "multiple home units" is the cause, because in my case there are no such dependencies.

**Comment by michaelpj** [comment]
It sounds an issue with our hacked up support for multiple home units indeed, we should revisit this after the proper support is merged.

**Comment by mouse07410** [comment]
> It sounds an issue with our hacked up support for multiple home units indeed

But I do **not** have multiple homes...? Or are you saying that "multiple home units" mistakenly triggers here?

**Comment by mouse07410** [comment]
@michaelpj thank you, now I understand. 

In your opinion, how near are we to having this solved?

**Comment by fendor** [comment]
Depends. 
Fully correctly? Still pretty far.
Best effort, sort-of-kind-of correct? Actually very close, maybe by the end of the year?

**Comment by soulomoon** [comment]
I have another one which is off by a line?
```
  instance Hashable KeyValue
    -- Defined at /Users/ares/src/haskell-language-server/hls-graph/src/Development/IDE/Graph/Internal/Types.hs:145:10
  instance Hashable KeyValue
    -- Defined at /Users/ares/src/haskell-language-server/hls-graph/src/Development/IDE/Graph/Internal/Types.hs:146:10typecheck
```

**Comment by soulomoon** [comment]
The problem does goes away, swtiching to cabal head, with cabal's multiple home unites feature enables

**Comment by PaulJohnson** [comment]
Just getting rid of most of these would be a benefit. Depending on which files I'm editing I can get hundreds of them, and real error messages are just buried.

**Comment by soulomoon** [comment]
> Just getting rid of most of these would be a benefit. Depending on which files I'm editing I can get hundreds of them, and real error messages are just buried.

Is switching to cabal head help in your case? @PaulJohnson

**Comment by fendor** [comment]
It did in my tests
