### ISSUE TITLE
 "disable warning" gets ordered high in the fix list

### ISSUE THREAD

**Issue by lf-** [haskell/haskell-language-server#3238]
## Is your enhancement request related to a problem? Please describe.

When I hit the code action button on unused imports, the "Disable [x] warnings" option is very high up, despite rarely being the right code action to fix the problem at hand. More generally it seems that the disable warning action is always high up on every warning.

![image](https://user-images.githubusercontent.com/6652840/193483107-84092157-366f-4919-9902-1f9d4ed5d9d9.png)

## Describe the solution you'd like

I would like the most appropriate fix to be first, so I can hit the "fix-first-suggestion" button in my editor to fix my imports. For instance, in this case, the first action should be deleting the unused imports on the current line.

## Additional context

Reproduced on 1.7.0.0 but I'm 90% sure it's also a problem on 1.8.0.0.

**Comment by michaelpj** [comment]
I think in this situation removing the specific redundant import is probably the canonical fix here, and we could just mark it as `isPreferred`. @andys8 you've shown this kind of problem some love before, want to take a look?

**Comment by lf-** [comment]
Oh damn, I'll file a pr to update the work version of hls then. Thanks!

**Comment by michaelpj** [comment]
Oh yes, for some reason I thought it was a different code action you fixed! Great!
