### ISSUE TITLE
undefined symbol __clock_nanosleep in librt.so

### ISSUE THREAD

**Issue by GuillaumeDesforges** [haskell/haskell-language-server#324]
Also here: https://github.com/NixOS/nixpkgs/issues/95425

I'm using HLS from nixpkgs, and hit an error: `undefined symbol __clock_nanosleep in librt.so`
Basically, it seems that HLS calls either a lib or an executable that triggers this error.

I am investigating and need to know what triggers this error.

How/where can I find detailled logs of HLS execution ?

**Comment by jneira** [comment]
It seems it was resolved in the nixpkgs linked issue: https://github.com/NixOS/nixpkgs/issues/95425#issuecomment-674569275
