### ISSUE TITLE
Add hacktoberfest topic

### ISSUE THREAD

**Issue by andys8** [haskell/haskell-language-server#3248]
Hey there,

This year https://hacktoberfest.com seems to be opt-in. I'm suggesting to add the topic #hacktoberfest to this project.

I personally like the idea and think it might encourage people to contribute improvements.

https://dev.to/github/how-to-get-ready-for-hacktoberfest-2022-2ck2

https://www.digitalocean.com/blog/hacktoberfest-2022-your-mission-for-open-source

**Comment by lf-** [comment]
hacktoberfest often results in useless spam contributions sadly. Might be worth trying anyway and seeing what happens, just remember that it can be removed later.

**Comment by andys8** [comment]
@lf- Have you read this year's rules?

**Comment by andys8** [comment]
Who has the rights to add the label and would be so kind to add it?

**Comment by pepeiborra** [comment]
Added
