### ISSUE TITLE
Display fourmolu version information

### ISSUE THREAD

**Issue by pgrange** [haskell/haskell-language-server#3255]
**Is your feature request related to a problem? Please describe.**

I can't find which version of fourmolu is used by vscode-haskell to ensure it matches others tools/CI/peers version.

I've observed breaking changes in [fourmolu version 0.5.0](https://github.com/fourmolu/fourmolu/pull/124) in some haddock indentation.

When indenting with fourmolu 0.4.0 I get one formatting.

When indenting with fourmolu 0.6.0 I get another formatting.

When indent with fourmolu inside vscode using vscode-haskell extension version 2.2.1 I get another formatting.

I can't find out the version of fourmolu that is being used by vscode-haskell so that I may use it as a "standard" version for instance.

**Describe the solution you'd like**

Display version of fourmolu used.

In the short term, I would be interested by just having the answer here for vscode-haskell 2.2.1.

In a longer term, display this information, for instance in _Haskell: Formatting Provider_ preference drop-down list.

**Describe alternatives you've considered**

Add the Formatting provider versions in CHANGELOG

**Additional context**

No additional context.

**Comment by michaelpj** [comment]
Another casualty of https://github.com/haskell/haskell-language-server/issues/411 IMO

**Comment by georgefst** [comment]
> You might be interested to instruct HLS to use the fourmolu binary HLS finds on the PATH instead of the one directly linked into HLS.

Unfortunately, I'm still now sure if this is possible (and I wrote the patch!): https://github.com/haskell/haskell-language-server/issues/2827. I'm looking in to finally solving that now.

**Comment by jhrcek** [comment]
For people who want to have specific version of fourmolu built into hls.
You can build hls from source using ghcup, specifying version constraint on fourmolu like this:
```bash
ghcup compile hls -g master --ghc 9.2.4 --cabal-update -- --constraint="fourmolu==0.6.0.0"
```
this compiles haskell-language-server from master branch of it's repo using ghc 9.2.4 (= hls has to be compiled with the same version of ghc that your project is using). --cabal-update tells ghcup to tell caball to fetch latest version of packages from hackage. --constraint flag is forwarded by ghcup to cabal, which then uses specific version of fourmolu in cabal plan. Might not work with all versions of ghc, didn't check. But it works with 9.2.4

**Comment by michaelpj** [comment]
You can now see the version by running `haskell-language-server --list-plugins`, which I think is as good as we can do.
