### ISSUE TITLE
Suggestion to remove language extension if usage is enabled dependent on the MIN_VERSION_ghc macro

### ISSUE THREAD

**Issue by nilsalex** [haskell/haskell-language-server#3275]
### Your environment

```bash
$ ghcup list -c set
   Tool  Version  Tags                      Notes      
✔✔ ghc   9.2.4    recommended,base-4.16.3.0 hls-powered
✔✔ cabal 3.6.2.0  recommended                          
✔✔ hls   1.8.0.0  latest,recommended                   
✔✔ stack 2.9.1    latest,recommended                   
✔✔ ghcup 0.1.18.0 latest,recommended 
```

Which OS do you use? **Arch Linux**
Which version of GHC do you use and how did you install it? **9.2.4 from ghcup**
How is your project built (alternative: link to the project)? **cabal**

Which LSP client (editor/plugin) do you use? **vim + coc.nvim and VS Code + vscode-haskell**

Which version of HLS do you use and how did you install it? **problem occurs both with 1.8.0.0 from ghcup and own build from master**
Have you configured HLS in any way (especially: a `hie.yaml` file)? **no**

### Steps to reproduce

```haskell
-- Main.hs

{-# LANGUAGE CPP #-}
{-# LANGUAGE TypeApplications #-}

module Main where

#if MIN_VERSION_ghc(9,2,1)
myInt = head @Int [1,2,3]
#endif

main :: IO ()
main = putStrLn "Hello, Haskell!"
```

```cabal
-- hls-bug-repro.cabal

cabal-version:      2.4
name:               hls-bug-repro
version:            0.1.0.0

executable hls-bug-repro
    main-is:          Main.hs

    build-depends:    base ^>=4.16.3.0,
                      ghc ^>=9.2.4
    hs-source-dirs:   app
    default-language: Haskell2010
```

Open `Main.hs` in VS Code (with the vscode-haskell plugin) or vim (with coc.nvim).

### Expected behaviour

hls should not suggest to remove the `TypeApplications` language extension.

### Actual behaviour

hls suggests to remove the `TypeApplications` language extension. If it is removed, the code does not compile and hls suggests to add the language extension again.

**Comment by michaelpj** [comment]
I think this is likely a hlint bug. Does hlint suggest this change if you run it directly?

**Comment by nilsalex** [comment]
You're right:

```
$ hlint .
app/Main.hs:2:1-33: Warning: Unused LANGUAGE pragma
Found:
  {-# LANGUAGE TypeApplications #-}
Perhaps you should remove it.

1 hint
```

**Comment by michaelpj** [comment]
Okay, then this is a hint issue which you may want to report upstream.
