### ISSUE TITLE
hls-hlint-plugin not included in 1.8.0.0 (GHC 8.10.7)

### ISSUE THREAD

**Issue by k-narron** [haskell/haskell-language-server#3308]
First off, hls is awesome. I'm learning haskell right now and it's such a qol/productivity improvement. Thanks!!

Second, I don't know if this has already been flagged or is actively worked on. I did a few quick searches but couldn't find any relevant issues.
Apologies if redundant.

hls and hls-hlint-plugin work as expected in 1.7.0.0.
I just noticed while trying to set this up for the first time that 1.8.0.0 doesn't include hlint, and nothing gets picked up. Code action in neovim doesn't show `Apply hint`/`Ignore hint` either.

### Your environment

Which OS do you use?

MacOS

Which version of GHC do you use and how did you install it?

8.10.7 from Nix

Which LSP client (editor/plugin) do you use?

Neovim-lspconfig

### Steps to reproduce

I use [haskell.nix](https://input-output-hk.github.io/haskell.nix/tutorials/getting-started-flakes.html) so
1. setup nix flake with `haskell-language-server = "1.8.0.0";`
2. run `nix develop .` in project directory
3. list hls plugins
4. exit nix environment
5. repeat 1~3 with `haskell-language-server = "1.7.0.0";`

### Expected behaviour

hls-hlint-plugin should be in hls v1.8.0.0 based on documentation.
[Only GHC 9.4 is listed as unsupported](https://haskell-language-server.readthedocs.io/en/latest/support/plugin-support.html#current-plugin-support-tiers:~:text=hls%2Dhlint%2Dplugin,9.4)

### Actual behaviour

hls-hlint-plugin is not found in hls v1.8.0.0
hls-hlint-plugin is in hls v1.7.0.0

v1.8.0.0:
<img width="1575" alt="hls-1 8 0 0" src="https://user-images.githubusercontent.com/89028527/198844962-9f6f7cec-97a2-4088-9ea9-2f5508058c29.png">

v1.7.0.0
<img width="1578" alt="hls-1 7 0 0" src="https://user-images.githubusercontent.com/89028527/198844951-64f88342-fe18-4b0c-8014-37be004717d6.png">

**Comment by andys8** [comment]
Hey there, I wanted to compare if this is also the case with my setup (not nix, installed with ghcup).

`haskell-language-server-wrapper --list-plugins`, `haskell-language-server-8.10.7 --list-plugins` and `haskell-language-server-8.10.7\~1.8.0.0` all seem to include `hlint` for me.


I'm not an expert when it comes to nix, but it looks like `hlint` is acticely removed by the maintainers of `haskell.nix` with `-hlint` here:

https://github.com/input-output-hk/haskell.nix/blob/7029d1fd0d0d21c6f54e0218b2b60779a963e243/modules/hackage-quirks.nix#L54-L57


```nix
      # TODO remove once these two plugins have been updated in hackage
      + lib.optionalString (config.version == "1.8.0.0") ''
        package haskell-language-server
          flags: -qualifyimportednames -stylishhaskell${lib.optionalString (config.compiler-nix-name != "ghc902") " -hlint"}
```

**Comment by k-narron** [comment]
> I'm not an expert when it comes to nix, but it looks like `hlint` is actively removed by the maintainers of `haskell.nix` with `-hlint` here:
> 
> * https://github.com/input-output-hk/haskell.nix/blob/7029d1fd0d0d21c6f54e0218b2b60779a963e243/modules/hackage-quirks.nix#L54-L57
> * [input-output-hk/haskell.nix@7029d1f](https://github.com/input-output-hk/haskell.nix/commit/7029d1fd0d0d21c6f54e0218b2b60779a963e243)
> 
> 
> The questions is if this is actually necessary or outdated. Since the information provided by the list of supported plugins and this commit don't add up, you could dig into it more or [open an issue in the repository](https://github.com/input-output-hk/haskell.nix/issues/new/choose) and ask for clarification.
> 
> Hope I could help a bit.

makes sense. I'll followup with haskell.nix. Thanks for pointing that out!
