### ISSUE TITLE
Scope of functions considered by hls-call-hierarchy-plugin?

### ISSUE THREAD

**Issue by jchia** [haskell/haskell-language-server#3320]
## Your environment 

Ubuntu 20.04, vscode, GHC 9.2.4 under stack 2.9.1.

Have you configured HLS in any way (especially: a `hie.yaml` file)?
Yes

## What's wrong?
I have no problem with basic functionality, but is it expected that functions in a different build target are excluded from the call hierarchy results? E.g. within a stack project, if a function `main` in foo-project:exe calls a function `callee` in foo-project:lib, is it normal that `main` will not show up in `callee`'s call hierarchy as one of its callers? This is what I am experiencing with my project. If this is normal, it would be helpful to clarify in the README.md the scope of the call hierarchy result.

**Comment by July541** [comment]
Yes, it is expected.

It will have the hierarchy relation if you open the two files in `exe` and `lib`(it writes `hiedb` actually, hls-call-hierarchy-plugin` relies on its clues).

**Comment by fendor** [comment]
Closing since the question seems to be answered
