### ISSUE TITLE
HLS doesn't indicate when it's ready

### ISSUE THREAD

**Issue by 9999years** [haskell/haskell-language-server#3328]
Before HLS starts up, it has to build the project. While this is happening, code actions aren't available, diagnostics aren't shown, and so on. However, HLS doesn't indicate when it's working on the first build or when it's ready. This is misleading; we've had complaints that HLS doesn't work when it's just doing that first invisible build.

HLS does log `Started LSP server in 0.02s`, but this is misleading; even if the language server is started, it's not ready in any meaningful way.

HLS should log at info-level when it's starting that first build, and when it completes.

**Comment by drsooch** [comment]
HLS sends progress notifications to the client which dictate its status. For example, in my doom emacs setup, I can see when HLS is processing and how close it is to finishing its build. I doubt shifting log messages to info will provide any real-time visibility into when HLS is building. 

It should be up to the Client editor should be the one to display this information.

**Comment by 9999years** [comment]
Huh, really? Neovim doesn't expose this information at all, as far as I can tell. Do you know how/where those messages are sent?

**Comment by 9999years** [comment]
Got it working in Neovim with [lsp-status.nvim](https://github.com/nvim-lua/lsp-status.nvim) and [lualine.nvim](https://github.com/nvim-lualine/lualine.nvim). Thanks for the pointer!
