### ISSUE TITLE
[Feature Request] Add missing fields in record

### ISSUE THREAD

**Issue by GuillaumeDesforges** [haskell/haskell-language-server#333]
It would be great if HLS could hint a code action to add (and import) missing fields of a record.

Say I write (using the [process](https://hackage.haskell.org/package/process) library)

```
import System.Process (CreateProcess(CreateProcess), CmdSpec(RawCommand))

proc = CreateProcess { cmdspec = RawCommand "echo" [ "hello world" ] }
```

many other fields are missing [(see doc)](https://hackage.haskell.org/package/process-1.6.10.0/docs/System-Process.html#t:CreateProcess), and need to be imported.

**Comment by pepeiborra** [comment]
I think this should be a completion provider

**Comment by ndmitchell** [comment]
A completion provider would be great. But in Rust, it's also a diagnostic fix, which has been a very nice way to use it.

**Comment by gdevanla** [comment]
I plan to take a stab at this, thanks to @pepeiborra's awesome tutorial on how to write a plugin.

So, should I start exploring this as a completion provider?  I was able to explore the `Example.hs`, so far to build a sample code snippet so that each field in the record could correspond to a placeholder.  

Can one of you provide me pointers, on where I can explore the AST information in ghcide for this?

**Comment by pepeiborra** [comment]
Look at how completions are done in ghcide, in particular check https://github.com/haskell/ghcide/blob/9ae5134d79972405415ce5062dbae67aeb938f21/src/Development/IDE/Plugin/Completions/Logic.hs#L232

You will need to generate new completions for records that include not only the constructor, but also the fields. For that you will need to find all the `TyThing`s that correspond to constructors fo record types and figure out the names of all the fields.

**Comment by gdevanla** [comment]
I am testing this now, and we do get completions for records.  I have added some tests to show what I found so far: 
https://github.com/haskell/ghcide/pull/804

Looks, like what we need is inspection of currently used fields in the context and provide a code action for missing fields. Which kind of suggests, we should use diagnostics as the original issue comment suggested.

Now, I need to look at, how to determine if I am inside a context of `record` creation, inspect the currently declared fields and identify the missing fields. Some scenarios, where this will not be correct is when `def` is used. At that point a code-action provided in that context may not be accurate.

**Comment by gdevanla** [comment]
I observed and added tests to show that missing record fields are already being report under diagnostics by hls. https://github.com/haskell/ghcide/pull/824.

Please suggest if we would like to extend this any further as part of this issue.

**Comment by gdevanla** [comment]
I have started iterating over the changes required for this feature.  For now, I have support for Local completions. Please could I have some feedback on the initial approach and if I can proceed in this path to support completions that are available from other modules.  #512

**Comment by gdevanla** [comment]
Can we close this issue now?

**Comment by jneira** [comment]
Yeah, thanks @gdevanla
