### ISSUE TITLE
Failed to find a HLS version for GHC 9.2.5

### ISSUE THREAD

**Issue by RHL120** [haskell/haskell-language-server#3332]
## Your environment 

Which OS do you use?

archlinux x86_64
Which version of GHC do you use and how did you install it?

I installed the default ghc version (9.2.5) from ghcup
How is your project built (alternative: link to the project)?
cabal init
Which LSP client (editor/plugin) do you use?

neovim + coc + hls
Which version of HLS do you use and how did you install it?
The default hls version (1.8.0.0) from ghcup
Have you configured HLS in any way (especially: a `hie.yaml` file)?
No
## What's wrong?
On an fresh cabal project I tried to edit Main.hs it loads for a while and then outputs: 
Failed to find a HLS version for GHC 9.2.5

### Debug information

No 'hie.yaml' found. Try to discover the project type!
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper-1.8.0.0) Version 1.8.0.0 x86_64 ghc-9.4.2
Current directory: /home/rhl120/jets/dchase
Operating system: linux
Arguments: ["--lsp"]
Cradle directory: /home/rhl120/jets/dchase
Cradle type: Cabal

Tool versions found on the $PATH
cabal:          3.6.2.0
stack:          2.9.1
ghc:            9.2.5

Consulting the cradle to get project GHC version...
Project GHC version: 9.2.5
haskell-language-server exe candidates: ["haskell-language-server-9.2.5","haskell-language-server"]
Failed to find a HLS version for GHC 9.2.5
Executable names we failed to find: haskell-language-server-9.2.5,haskell-language-server
 2022-11-12T12:29:29.485762Z | Info | Starting server

**Comment by fendor** [comment]
> On an fresh cargo project  

*cargo*?

In any way, we don't officially support GHC 9.2.5, yet, but you may build it from source via `ghcup compile hls --ghc 9.2.5 --git-ref 1.8.0.0`

**Comment by RHL120** [comment]
> > On an fresh cargo project
> 
> _cargo_?
> 
> In any way, we don't officially support GHC 9.2.5, yet, but you may build it from source via `ghcup compile hls --ghc 9.2.5 --git-ref 1.8.0.0`

Oops, I am trying to torture my self by learning rust, I can't get cargo of my mind. It is cabal

**Comment by fendor** [comment]
Of course, but usually only with the next release

**Comment by jhrcek** [comment]
You can build ghc 9.2.5 - supporting hls from source using ghcup.
I do it like this
`ghcup compile hls --cabal-update -g master --ghc 9.2.5`

More info in ghcup user guide: https://www.haskell.org/ghcup/guide/#hls
