### ISSUE TITLE
HLS master pulls wrong exactprint for GHC-9.4.3

### ISSUE THREAD

**Issue by mouse07410** [haskell/haskell-language-server#3336]
### Your environment

Which OS do you use?
- MacOS Monterey 12.6.1
 
Which version of GHC do you use and how did you install it?
- GHC-9.4.3 installed via `ghcup`
 
Which LSP client (editor/plugin) do you use?
- vscode-haskell

Which version of HLS do you use and how did you install it?
- Current master, via `ghcup compile hls -g master --ghc 9.4.3
 
Have you configured HLS in any way (especially: a `hie.yaml` file)?
- I would if it could build

### Steps to reproduce

Run
```
$ ghcup compile hls -g master --ghc 9.4.3
```
and observe the results.

### Expected behaviour

Successful build of HLS for GHC-9.4.3

### Actual behaviour

```
.  .  .
[ ...   ]   HLS version (from cabal file): 1.8.0.0
[ ...   ]   commit hash: 385dd1b57af75ccd286e104b7e00f2b0cb626588
[ Info  ] Building HLS 1.8.0.0 for GHC version 9.4.3
[ cabal ]      |            ^^^^^^^^^^^^^
[ cabal ] Error: cabal: Failed to build ghc-exactprint-1.6.0 (which is required by
[ cabal ] exe:haskell-language-server from haskell-language-server-1.8.0.0 and
[ cabal ] exe:haskell-language-server-wrapper from haskell-language-server-1.8.0.0). See
[ cabal ] the build log above for details.
[ cabal ] 
[ Error ] BuildFailed failed in dir /Users/ur20980/.ghcup/tmp/ghcup-43143085c88e9adb: Process "cabal" with arguments ["v2-install",
```

### Proposed fix

If GHC is 9.4.x - relax the upper bound on `ghc-exactprint` dependency package to at least 1.6.1.

**Comment by michaelpj** [comment]
HLS builds with 9.4.3 now.
