### ISSUE TITLE
Plugin for record-selector to record dot syntax

### ISSUE THREAD

**Issue by santiweight** [haskell/haskell-language-server#3350]
If the user's editor looks like this:

```
   bar = unFoo foo
             ^
```

We could provide a code action that produces:

```
   bar = foo.unFoo
```

We could also provide this functionality file-wide, either as a an action on the module or in the file explorer.

**Comment by michaelpj** [comment]
I think this wouldn't be too hard: look for simple applications of functions which are record selectors, offer to rewrite them.
