### ISSUE TITLE
Failure when installing HLS in VSCODE.

### ISSUE THREAD

**Issue by FullValueRider** [haskell/haskell-language-server#3372]
I spent the day yesterday trying to get the Haskell working in VSCode. 

I've installed removed and reinstalled upmpty times the 2.2.1 Haskell Language support powerd by the Haskell Lanhuage server and the 3.6.0 Haskell SYntax Highlighting.

 I had no success.

I am new to VSCode.  I am new to Haskell. Most of my previous programming (strictly amateur) has been done in VBA/twinBasic.  I wanted to try Haskell for this year's Advent of Code challenges. The reason for this is that my VBA code is increasingly using a functional approach (although my use of the term functional may be nowhere near what Haskell uses).

I continually ran into two challenges

1. 9.2.5 is not supported
2. The HLS has crashed x times in the last x minutes and will not be restarted

I've installed Haskell on Windows using GHcup.  I used GHcup to change to various versions of ghc, HLS and cabal.  I've edited the stack.yaml ( e.g. resolver: gch-9.2.4 ) created when you use stack to create a new project.   

All to no avail.

I'd be grateful if someone can give me a pointer as to where I'm going wrong and how to get the Haskell Language server working in VSCode.

## Your environment 
Which OS do you use?
Windows 11

Which version of GHC do you use and how did you install it?
 Tried GHC from 9.2.4 onwards using GHcup to install and then set as default.  Likewise I've also tried HLS 1.7.00, 1.8.0.0 (installed and set as default)
How is your project built (alternative: link to the project)?
??
Which LSP client (editor/plugin) do you use?
vscode-haskell language server -Haskell syntax highlighting -->

Which version of HLS do you use and how did you install it?
all installations were from ghcup. I tried 1.7.0.0 and 1.8.0.0

Have you configured HLS in any way (especially: a `hie.yaml` file)?

I've no idea what/where hie.yaml is or how to configure it
## What's wrong?

1. 9.2.5 is not supported
2. The HLS has crashed x times in the last x minutes and will not be restarted

**Comment by ivcosla** [comment]
Same issue. If I use `stack` it doesn't work neither with 9.2.5 (not yet supported by HLS) neither by 9.2.4.

**Comment by FullValueRider** [comment]
@fendor Thanks for taking the time to respond to my plea for help.

The output from the instructions above is attached (install.logs).  

[InstallLogs.txt](https://github.com/haskell/haskell-language-server/files/10138831/InstallLogs.txt)

I created a new Project using

stack new TestProj

The stack.yaml for this project is below (as Stack.txt)

[stack.txt](https://github.com/haskell/haskell-language-server/files/10138850/stack.txt)

If I go into this project and launch VSCode using 'Code .', I get the HLS does not suppoert 9.2.5 message.

The debug log is below (output.txt)

[Output.txt](https://github.com/haskell/haskell-language-server/files/10138929/Output.txt)

The output from Stack build is below (StackBuild.txt)
[StackBuild.txt](https://github.com/haskell/haskell-language-server/files/10138938/StackBuild.txt)

**Comment by fendor** [comment]
Alright great, that looks pretty good already! Please change your `stack.yaml` to:
Now we need to make sure, you have an HLS version compatible with the used GHC version.

We have two ways forward: Compile HLS from source, or make stack use a different GHC version for compiling your project. I will elaborate both ways, but I *think* switching to the GHC version will be easier.

### Compiling from source

Compiling from source can be achieved with ghcup the following way:
```bash
ghcup compile hls --version 1.8.0.0 --ghc 9.2.5 --cabal-update
```

Note, this will take a *considerable* amount of time, depending on your hardware, up to an hour.

### Switching GHC version

In stack.yaml, change the line:
```yaml
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/20/2.yaml
```

to:

```yaml
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/33.yaml
```

You can see from https://www.stackage.org/, this stackage snapshot should install GHC 9.0.2. But don't worry about that, the necessary GHC versions should be installed automatically and the installed HLS version is compatible with GHC 9.0.2.

---

If this still doesn't work, please provide the VSCode output again.

**Comment by FullValueRider** [comment]
Editing the yaml got me a squiggly red line but there are error messages.
[Output.txt](https://github.com/haskell/haskell-language-server/files/10140320/Output.txt)

and 
![Haskel_gcideError](https://user-images.githubusercontent.com/81257042/205277252-ef66904a-ff64-4cc4-96d9-b6c16c5b8bca.jpg)


Attempting to build 9.2.5 just flat out failed



[StackBuild.txt](https://github.com/haskell/haskell-language-server/files/10140324/StackBuild.txt)

**Comment by FullValueRider** [comment]
Aha, I now see that the ghcide error is actually a message from the HSL.

**Comment by fendor** [comment]
Yes, we are getting closer.

> Attempting to build 9.2.5 just flat out failed 

I don't quite get that, since you changed the resolver in `stack.yaml`, you are not building your project with GHC 9.2.5 any more, no?

Or did you undo that change?

On a second thought, it might be easier indeed to install HLS with GHC 9.2.5 support, can you try the instructions from above for compiling HLS from source? Might take a while, but it should be "fairly" reliable.

**Comment by FullValueRider** [comment]
Hmmm.  for some reason the installs I did yesterday have reverted.  I repeated the ghcup installs and reattempted the compilation of HLS but I get the same issue.

ghcup list output

```
[ Info  ] verifying digest of: gs.exe
   Tool  Version  Tags                      Notes
X  ghc   7.10.3   base-4.8.2.0
X  ghc   8.0.2    base-4.9.1.0
X  ghc   8.2.2    base-4.10.1.0
X  ghc   8.4.1    base-4.11.0.0
X  ghc   8.4.2    base-4.11.1.0
X  ghc   8.4.3    base-4.11.1.0
X  ghc   8.4.4    base-4.11.1.0
X  ghc   8.6.1    base-4.12.0.0
X  ghc   8.6.2    base-4.12.0.0
X  ghc   8.6.3    base-4.12.0.0
X  ghc   8.6.4    base-4.12.0.0
X  ghc   8.6.5    base-4.12.0.0
X  ghc   8.8.1    base-4.13.0.0
X  ghc   8.8.2    base-4.13.0.0
X  ghc   8.8.3    base-4.13.0.0
X  ghc   8.8.4    base-4.13.0.0
X  ghc   8.10.1   base-4.14.0.0
X  ghc   8.10.2   base-4.14.1.0
X  ghc   8.10.3   base-4.14.1.0
X  ghc   8.10.4   base-4.14.1.0
X  ghc   8.10.5   base-4.14.2.0
X  ghc   8.10.6   base-4.14.3.0
X  ghc   8.10.7   base-4.14.3.0             hls-powered
X  ghc   9.0.1    base-4.15.0.0
X  ghc   9.0.2    base-4.15.1.0             hls-powered
X  ghc   9.2.1    base-4.16.0.0
I  ghc   9.2.2    base-4.16.1.0
X  ghc   9.2.3    base-4.16.2.0             hls-powered
IS ghc   9.2.4    base-4.16.3.0             hls-powered
I  ghc   9.2.5    recommended,base-4.16.4.0
X  ghc   9.4.1    base-4.17.0.0             hls-powered
X  ghc   9.4.2    base-4.17.0.0             hls-powered
I  ghc   9.4.3    latest,base-4.17.0.0
X  cabal 2.4.1.0
X  cabal 3.0.0.0
X  cabal 3.2.0.0
X  cabal 3.4.0.0
X  cabal 3.4.1.0
X  cabal 3.6.0.0
IS cabal 3.6.2.0  recommended
I  cabal 3.8.1.0  latest
X  hls   1.1.0
X  hls   1.2.0
X  hls   1.3.0
X  hls   1.4.0
X  hls   1.5.0
X  hls   1.5.1
X  hls   1.6.0.0
X  hls   1.6.1.0
X  hls   1.7.0.0
IS hls   1.8.0.0  latest,recommended
X  stack 2.5.1
X  stack 2.7.1
X  stack 2.7.3
X  stack 2.7.5
IS stack 2.9.1    latest,recommended
IS ghcup 0.1.18.0 latest,recommended
```

compile output

```
>ghcup compile hls --version 1.8.0.0 --ghc 9.2.5 --cabal-update
[ Info  ] verifying digest of: gs.exe
[ Info  ] Updating cabal DB
Downloading the latest package list from hackage.haskell.org
Package list of hackage.haskell.org is up to date at index-state 2022-12-02T10:58:19Z
Unpacking to haskell-language-server-1.8.0.0\
[ Info  ] Building HLS 1.8.0.0 for GHC version 9.2.5
cabal-3.6.2.0.exe: Could not resolve dependencies:
[__0] trying: haskell-language-server-1.8.0.0 (user goal)
[__1] trying: haskell-language-server:+stylishhaskell
[__2] trying: hls-stylish-haskell-plugin-1.0.1.1 (dependency of
haskell-language-server +stylishhaskell)
[__3] next goal: hls-plugin-api (dependency of haskell-language-server)
[__3] rejecting: hls-plugin-api-1.5.0.0 (conflict: hls-stylish-haskell-plugin
=> hls-plugin-api^>=1.4)
[__3] rejecting: hls-plugin-api-1.4.0.0 (conflict: haskell-language-server =>
hls-plugin-api^>=1.5)
[__3] skipping: hls-plugin-api-1.3.0.0, hls-plugin-api-1.2.0.2,
hls-plugin-api-1.2.0.1, hls-plugin-api-1.2.0.0, hls-plugin-api-1.1.0.2,
hls-plugin-api-1.1.0.1, hls-plugin-api-1.1.0.0, hls-plugin-api-1.0.0.0,
hls-plugin-api-0.7.1.0, hls-plugin-api-0.7.0.0, hls-plugin-api-0.6.0.0,
hls-plugin-api-0.5.0.1, hls-plugin-api-0.5.0.0, hls-plugin-api-0.4.1.0,
hls-plugin-api-0.4.0.0 (has the same characteristics that caused the previous
version to fail: excluded by constraint '^>=1.5' from
'haskell-language-server')
[__3] fail (backjumping, conflict set: haskell-language-server,
hls-plugin-api, hls-stylish-haskell-plugin)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: haskell-language-server,
hls-plugin-api, hls-stylish-haskell-plugin,
haskell-language-server:stylishhaskell
Try running with --minimize-conflict-set to improve the error message.


[ Error ] BuildFailed failed in dir c:\Haskell\ghcup\tmp\ghcup-9436e0368b104572\haskell-language-server-1.8.0.0: Process "cabal" with arguments ["v2-install",
[ ...   ]
                         "-w",
[ ...   ]
                         "ghc-9.2.5",
[ ...   ]
                         "--install-method=copy",
[ ...   ]
                         "--overwrite-policy=always",
[ ...   ]
                         "--disable-profiling",
[ ...   ]
                         "--disable-tests",
[ ...   ]
                         "--installdir=c:\\Haskell\\ghcup\\tmp\\ghcup-9436e0368b104572\\haskell-language-server-1.8.0.0\\out\\9.2.5",
[ ...   ]
                         "--project-file=cabal.project",
[ ...   ]
                         "exe:haskell-language-server",
[ ...   ]
                         "exe:haskell-language-server-wrapper"] failed with exit code 1.
```

**Comment by fendor** [comment]
Uhu, ok, well, apparently HLS truly doesn't work with GHC 9.2.5. Then back to making your stack project compliant with GHC 9.0.2.

Did you change your stack.yaml to have the resolver 19.33 and if yes, does `stack build` work?

**Comment by FullValueRider** [comment]
This is the relevant part from the current project stack yaml 

```
# resolver: ./custom-snapshot.yaml
# resolver: https://example.com/snapshots/2018-01-01.yaml
resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/19/33.yaml

# User packages to be built.
# Various formats can be used as shown in the example below.
```
stack build completes successfully

```
>stack build
Building all executables for `Test3' once. After a successful build of all of them, only specified executables will be rebuilt.
Test3> configure (lib + exe)
Configuring Test3-0.1.0.0...
Test3> build (lib + exe)
Preprocessing library for Test3-0.1.0.0..
Building library for Test3-0.1.0.0..
[1 of 2] Compiling Lib
[2 of 2] Compiling Paths_Test3
Preprocessing executable 'Test3-exe' for Test3-0.1.0.0..
Building executable 'Test3-exe' for Test3-0.1.0.0..
[1 of 2] Compiling Main
[2 of 2] Compiling Paths_Test3
Linking .stack-work\dist\d53b6a14\build\Test3-exe\Test3-exe.exe ...
Test3> copy/register
Installing library in C:\Users\slayc\source\repos\AdventOfCode\Haskell\Test3\.stack-work\install\e59e8013\lib\x86_64-windows-ghc-9.0.2\Test3-0.1.0.0-G7bVOFpEy6cKeKLeAPOsok
Installing executable Test3-exe in C:\Users\slayc\source\repos\AdventOfCode\Haskell\Test3\.stack-work\install\e59e8013\bin
Registering library for Test3-0.1.0.0..

```

**Comment by fendor** [comment]
Ok, great, now try running `haskell-language-server-wrapper --debug .` and provide the output here.

 ---
 
 Btw, I found the ghcup command I pasted was incorrect, what you need is
 ```
 ghcup compile hls --git-ref master --ghc 9.2.5 --git-describe-version
 ```
 
 that should install HLS for ghc version 9.2.5.

**Comment by FullValueRider** [comment]
The updated compile  is now working, is been doing its thing for the past 5 minutes with no apparent issues.

The out put of haskell-language-server-wrapper --debug

[HaskellLSWDebug.txt](https://github.com/haskell/haskell-language-server/files/10141352/HaskellLSWDebug.txt)

**Comment by fendor** [comment]
that looks great, so HLS is now working for you?

**Comment by FullValueRider** [comment]
HLS has successfully compiled and installed ( or so it claims).  I created a new project via 'stack new Test4' and then opened the project using 'code .'  This is what I'm current looking at
![HaskelWith925](https://user-images.githubusercontent.com/81257042/205304539-6ec534d9-83bd-4486-ab65-ecfcd9f9844e.jpg)

If I comment out the whole of that block the error goes away.
When I uncomment the bock I get the text back without the red squiggle.

saving the fil and reopening and there is no red squiggle
changing 'someFunc' to 'someFun'  does not give rise to any entries in the Problems area.
If I close vscode and then reopen I get back to the image I posted above.

**Comment by fendor** [comment]
Ok, this looks like a stack bug... 

You can give it a try to compile your project via cabal, try adding this `hie.yaml` to the root of your project (right next to stack.yaml`)
```yaml
cradle:
  cabal:
```

this will instruct HLS to use cabal for building your project. In general, cabal works slightly better with HLS than stack.
