### ISSUE TITLE
Migrate CI from GitLab to GitHub

### ISSUE THREAD

**Issue by hasufell** [haskell/haskell-language-server#3398]
## Motivation

1. one CI system to deal with instead of two
2. better stability (IME)
3. more access to shared code and actions of GitHub (larger ecosystem)

## Execution

A prototype was done at GHCup: https://github.com/haskell/ghcup-hs/compare/2abcb46199f06f09cb746322af7e88314be1f182%5E..823458910b41cf79739257dbc3d08084400bb594

This includes intelligent caching via `cabal-cache` with S3 BlackBlaze.

Self-hosted runners for Linux AARCH64 and Darwin AARCH64 will be provided by @angerman  ...can you briefly comment here what you need to hook them up with HLS repo?

**Comment by hasufell** [comment]
@Bodigrim can you give @angerman admin rights to be able to set up the self hosted runners as needed?

**Comment by Bodigrim** [comment]
@hasufell I'm reluctant to provide full admin access to the org. What kind of access is required?

**Comment by angerman** [comment]
> @hasufell I'm reluctant to provide full admin access to the org. What kind of access is required? 

Access to setup shared runners (under settings). Or you generate a bunch of runner tokens and share them with me.

**Comment by hasufell** [comment]
I'm repo admin now and have shared a token with @angerman 

@Bodigrim can you enable cirrus CI for this repo?

**Comment by hasufell** [comment]
> I'm repo admin now and have shared a token with @angerman

But I'm not sure those are shared runners... probably not. So someone with org admin access needs to share that.

**Comment by hasufell** [comment]
Issues with FreeBSD: https://github.com/cirruslabs/cirrus-ci-docs/issues/1123

**Comment by Bodigrim** [comment]
> @Bodigrim can you enable cirrus CI for this repo?

Done.

> But I'm not sure those are shared runners... probably not. So someone with org admin access needs to share that.

I don't think it is possible to share across the organization an existing runner, it needs to be created anew?.. Tokens are time-limited, so if you drop me an email once you are up to it, I'll generate one. I'm in +0 UTC.
