### ISSUE TITLE
HLS does not tolerate deleting modules.

### ISSUE THREAD

**Issue by ProofOfKeags** [haskell/haskell-language-server#341]
Environment: VSCode

Release: 0.3.0

If you delete a module (and remove all references to it), VSCode Problems tab still shows it as not being found. Restarting the editor fixes this, but for obvious reasons that's pretty annoying.

This seems like an easy thing to fix and I would like to learn how to contribute to HLS. I'll for sure need some help orienting myself though.

**Comment by jneira** [comment]
The ghcide issue has been moved [here](https://github.com/haskell/haskell-language-server/issues/792) so i am gonna close this one.
