### ISSUE TITLE
Module autocompletion occasionally duplicates one of the segments

### ISSUE THREAD

**Issue by ProofOfKeags** [haskell/haskell-language-server#342]
Environment: VSCode

Release 0.3.0

tested module imports from fused-effects

Importing `Control.Car<tab>` results in `Control.Carrier.Empty.Church` <- this is correct
Importing `Control.Carrier.E<tab>` results in `Control.Carrier.Carrier.Empty.Church`
Importing `Control.Carrier.Empty.C<tab>` results in `Control.Carrier.Empty.Empty.Church`

This is stable across packages.

Hitting '.' the after the first segment kills the autocomplete window. Beginning the second segment starts a new autocomplete window with the submodule (without the first segment). Autocompleting during the second segment will work. But if you finish out to the third segment or later, it will always duplicate the first segment you started with.

If you go back and delete the Duplicate and try again, if dot is the last remaining character, the behavior will be correct. If you delete the dot as well, it will do the module segment duplication outlined above.

The behavior seems *almost* right. So I'm wondering if this is an easy thing for me to work on with zero experience with the LSP or HLS

**Comment by georgefst** [comment]
> I'm wondering if this is an easy thing for me to work on with zero experience with the LSP or HLS

https://github.com/digital-asset/ghcide/issues/613

It's tagged "good first issue"!
