### ISSUE TITLE
would it increase takeup if there were a docker image with everything preinstalled?

### ISSUE THREAD

**Issue by chumbleycode** [haskell/haskell-language-server#344]
as with rocker for R?

**Comment by jneira** [comment]
Hi, i think this was somewhat a proposal about setup a docker image with hls and all tools needed to start hacking with haskell code. That could be a nice way to distribute indeed.

**Comment by jneira** [comment]
And we could use it for setup a vscode dev container.
In fact from a quick search i found a image: https://github.com/vzarytovskii/haskell-dev-env
Maybe we should mention it in docs?

**Comment by ndmitchell** [comment]
Should this be the IDE team, or perhaps this could be a Haskell foundation project, where they bundle HLS, plus whatever else. For example, I think such a package should almost certainly contain Alex/Happy, but us bundling them, and figuring out which version etc, seems like an orthogonal problem.

**Comment by jneira** [comment]
Agree, ideally it should be integrated in https://hub.docker.com/_/haskell via https://github.com/haskell/docker-haskell/issues

**Comment by jneira** [comment]
Opened issue upstream: https://github.com/haskell/docker-haskell/issues/41

**Comment by jneira** [comment]
Although the upstream issue is still open we get a container matching the requirement of the issue directly hosted in microsoft vscode dev containers: https://github.com/microsoft/vscode-dev-containers/tree/main/containers/haskell
So i am gonna close this, @chumbleycode feel free to reopen if you think the mentioned image does not fullfill your requirements
