### ISSUE TITLE
Is the ormolu plugin compatible with haskell-language-server-1.9.0.0?

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell/haskell-language-server#3445]
Hi! I just installed `haskell-language-server-1.9.0.0` with `ghcup` (on `Pop_OS!`) and I see it doesn't come with the `ormolu` plugin enabled:

```
$ haskell-language-server-wrapper --list-plugins
```

<details>

```
LSPRecorderCallback
alternateNumberFormat
cabal
cabalfmt
callHierarchy
changeTypeSignature
class
codeRange
explicit-fields
explicit-fixity
fourmolu
gadt
ghcide-code-actions-bindings
ghcide-code-actions-fill-holes
ghcide-code-actions-imports-exports
ghcide-code-actions-type-signatures
ghcide-completions
ghcide-core
ghcide-extend-import-action
ghcide-hover-and-symbols
ghcide-type-lenses
hlint
importLens
moduleName
pragmas
qualifyImportedNames
refineImports
retrie
splice
```

</details>

Is that because of how the `ghcup` maintainers elected to compile `haskell-language-server`, and I could enable the `ormolu` plugin by building it from source myself? Or is there some other reason why the `ormolu` plugin is disabled?

Thanks!

**Comment by michaelpj** [comment]
What GHC version? Does this page answer your question? https://haskell-language-server.readthedocs.io/en/latest/support/plugin-support.html

**Comment by mitchellwrosen** [comment]
Oh, yes, of course - `haskell-language-server-wrapper` selects some other `haskell-language-server-*`, so the list of plugins I see with `--list-plugins` depends on which GHC version is selected.

So yes, I see now `ormolu` doesn't support GHC 9.4 :) Thank you!
