### ISSUE TITLE
dyn_o files are not genereated

### ISSUE THREAD

**Issue by yaitskov** [haskell/haskell-language-server#3447]
VScode shows error:

> 	"severity": 8,
>	"message": "Program error: /home/dan/Foo.hs:286:85: fatal:\n    cannot find object file ‘/home/dan/.cache/ghcide/napkin-0.5.14-inplace-798c540bdfae53019945733e435479cbb0a39026/Bar.dyn_o’\n    while linking an interpreted expression",
>	"source": "typecheck",

```
haskell-language-server --version
2023-01-09T15:58:42.640530Z | Info | No log file specified; using stderr.
haskell-language-server version: 1.7.0.0 (GHC: 8.10.7) (PATH: /nix/store/yb79pi8j9i3rlqfq0ppaija8ihqjwc21-haskell-language-server-1.7.0.0/bin/haskell-language-server)
```

cabal build generates dyn_o files and after copying them manually issue resolves:

```
find -name "*.dyn_o" | while read dyno ; do 
 dynoSuffix=${dyno##./dist-newstyle/build/x86_64-linux/ghc-8.10.7/foo-0.5.14/build/} 
 dst=/home/dan/.cache/ghcide/foo-0.5.14-inplace-798c540bdfae53019945733e435479cbb0a39026/$dynoSuffix
 mkdir -p $(dirname $dst)
 cp ./dist-newstyle/build/x86_64-linux/ghc-8.10.7/foo-0.5.14/build/$dynoSuffix $dst
done
```

**Comment by michaelpj** [comment]
Also you might want to try clearing out the ghcide cache in `~/.cache/ghcide`
