### ISSUE TITLE
False error in polykinded type family

### ISSUE THREAD

**Issue by sjshuck** [haskell/haskell-language-server#3457]
### Environment

* Windows 11 + WSL2 (Ubuntu 20.04)
* GHCUp 0.1.19.0
  * Stack 2.9.3
  * Cabal 3.6.2.0
  * GHC 9.2.5
  * HLS 1.9.0.0
* Neovim 0.7.2
  * built-in LSP client
  * nvim-lspconfig, default configuration, this commit: https://github.com/neovim/nvim-lspconfig/blob/8ebe6894dddaeb1459e1397c865f54fa5ecaac80/lua/lspconfig/server_configurations/hls.lua

Editing `pcre2` package at this commit: https://github.com/sjshuck/hs-pcre2/tree/2d01498056569905abc643fdffa697efbbd6c08c

### Steps to reproduce

Run `stack build`, open `src/hs/Text/Regex/Pcre2/Internal.hs`, and then open `src/hs/Text/Regex/Pcre2/TH.hs` alongside.

### Expected behaviour

There should be no errors, just as when `stack build` was run.

### Actual behaviour

This error on line 64 of `src/hs/Text/Regex/Pcre2/TH.hs`:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/15720421/213014351-e41c9be0-3a45-473c-b5fb-c1a4b0edbf99.png">

**Comment by geekosaur** [comment]
Could this be related to https://mail.haskell.org/pipermail/ghc-steering-committee/2022-July/002812.html ff?

**Comment by sjshuck** [comment]
@geekosaur I doubt it.  I can't pretend to understand the ins and outs of that thread but it seems to be surprising behavior when PolyKinds _isn't_ turned on, but in my code sample, it is turned on (along with AllowAmbiguousTypes and UndecidableInstances).

Also note that GHC 9.2.5 itself compiles the code just fine, it's just HLS that's having an issue.  They should work the same.

**Comment by fendor** [comment]
Seems related #3302

**Comment by michaelpj** [comment]
Is this still a problem?

**Comment by sjshuck** [comment]
> Is this still a problem?

It is not.  Tested with HLS 2.5.0.0 and GHC both 9.4.8 and 9.6.3.  Thanks!
