### ISSUE TITLE
Errors are highlighted in wrong parts of lines indented with tab.

### ISSUE THREAD

**Issue by torgeirsh** [haskell/haskell-language-server#3459]
### Your environment

Which OS do you use: Windows

### Steps to reproduce

Cause an error in a line indented with tab:

![vscode-error-highlighting](https://user-images.githubusercontent.com/5411177/213921319-4ca405c1-9232-4ced-93bf-66aa6b31c6b4.png)

### Expected behaviour

The problematic part of the line is highlighted.

### Actual behaviour

The highlight starts 7 characters too far to the right, so I guess the tab character is counted as one character when the highlight position is calculated, whereas HLS seems to expand it to 8 characters. This also affects type info popups, etc.

### Include debug information

Range:    259:21-259:32
Source:   typecheck
Severity: DsError
Message:  Variable not in scope: nonExisting

**Comment by michaelpj** [comment]
Closing as dupe
