### ISSUE TITLE
Stay updated with changes to related compilation targets of same package (e.g. src & test)

### ISSUE THREAD

**Issue by DanBurton** [haskell/haskell-language-server#346]
Thank you for your hard work! I have a request.

When I have multiple buffers open with different compilation targets of the same package in each buffer, I would like it if, for example, updating a `src` module will propagate the changes to another buffer open on the `test` module that imports that `src` module. What currently happens is that I need to restart the HLS, or restart my editor (emacs), in order for HLS to pick up the changes to the upstream component in the `test` module buffer.

**Comment by theGhostJW** [comment]
To reproduce:
1. open the following in HLS: https://github.com/theGhostJW/pyrethrum/releases/tag/346_Repro_1
2. evaluate (using Eval lens) ````-- >>> "Hello " <> salutation```` in ````DemoTest.hs````
3. will evaluate to "Hello World"
4. change ````salutation```` in ````Demo.hs````
5. refresh ````-- >>> "Hello " <> salutation```` in ````DemoTest.hs````
6. the eval does not reflect the change in the Demo module

**Comment by michaelpj** [comment]
I think this should be fixed by the proper multi-home-unit support.
