### ISSUE TITLE
Including xmonad ./lib folder sources

### ISSUE THREAD

**Issue by trev-dev** [haskell/haskell-language-server#3460]
I'm using xmonad on nixos.  XMonad has this nice feature where you may stick any local module that you would like into the configuration's `lib` folder.  You may then import those modules in your XMonad configuration as though they existed in the same folder as your xmonad.hs

I'm hoping there's a simple way to configure the language server for this project to recognize the modules in the `~/.config/xmonad/lib` folder.  Most suggestions suggest a sort of all-or-nothing stack/cabal thing.  I don't want to make my reproducible nix more complex than I need it to be.  May I get a hand?

**Comment by wz1000** [comment]
You need to set up a [hie-bios](https://github.com/haskell/hie-bios) cradle (which means adding a hie.yaml file to your .xmonad directory) which can tell HLS the correct GHC flags to load your project into HLS.

**Comment by fendor** [comment]
Closed for inaction. Please don't hesitate to ask for more clarification if needed.

**Comment by trev-dev** [comment]
Thanks @fendor - for the most part I am happy with my xmonad config at this point but when I get a chance to explore Haskell some more I will circle back.
