### ISSUE TITLE
HLS 1.9.0.0 wrapper installed via ghcup on WSL fails to find HLS executables

### ISSUE THREAD

**Issue by jship** [haskell/haskell-language-server#3461]
Possibly related to #3332 and #3353. Running the installed `haskell-language-server-wrapper-1.9.0.0` errors due to not finding a matching HLS executable:

```
❯ haskell-language-server-wrapper-1.9.0.0
No 'hie.yaml' found. Try to discover the project type!
Run entered for haskell-language-server-wrapper(haskell-language-server-wrapper-1.9.0.0) Version 1.9.0.0 x86_64 ghc-9.4.4
Current directory: /path/to/repo
Operating system: linux
Arguments: []
Cradle directory: /path/to/repo
Cradle type: Stack

Tool versions found on the $PATH
cabal:          3.6.2.0
stack:          2.9.1
ghc:            9.2.5


Consulting the cradle to get project GHC version...
Project GHC version: 9.2.5
haskell-language-server exe candidates: ["haskell-language-server-9.2.5","haskell-language-server"]
Failed to find a HLS version for GHC 9.2.5
Executable names we failed to find: haskell-language-server-9.2.5,haskell-language-server
```

Contents of `~/.ghcup/bin`:

```
❯ ls -l ~/.ghcup/bin | grep language
lrwxrwxrwx 1 jship jship       49 Jan 22 14:34 haskell-language-server-8.10.7~1.9.0.0 -> ../hls/1.9.0.0/bin/haskell-language-server-8.10.7
lrwxrwxrwx 1 jship jship       48 Jan 22 14:34 haskell-language-server-9.0.2~1.9.0.0 -> ../hls/1.9.0.0/bin/haskell-language-server-9.0.2
lrwxrwxrwx 1 jship jship       48 Jan 22 14:34 haskell-language-server-9.2.5~1.9.0.0 -> ../hls/1.9.0.0/bin/haskell-language-server-9.2.5
lrwxrwxrwx 1 jship jship       48 Jan 22 14:34 haskell-language-server-9.4.3~1.9.0.0 -> ../hls/1.9.0.0/bin/haskell-language-server-9.4.3
lrwxrwxrwx 1 jship jship       48 Jan 22 14:34 haskell-language-server-9.4.4~1.9.0.0 -> ../hls/1.9.0.0/bin/haskell-language-server-9.4.4
lrwxrwxrwx 1 jship jship       86 Jan 22 14:34 haskell-language-server-wrapper-1.9.0.0 -> ../hls/1.9.0.0/lib/haskell-language-server-1.9.0.0/bin/haskell-language-server-wrapper
```

So it looks like a `haskell-language-server-9.2.5` does indeed exist, but the symlink to it in `~/.ghcup/bin` has the `~1.9.0.0` suffix. Presumably the wrapper is looking for the exact name rather than that suffixed name?

### Your environment

Which OS do you use?
WSL

Which version of GHC do you use and how did you install it?
9.2.5 from ghcup

How is your project built (alternative: link to the project)?
Via stack

Which LSP client (editor/plugin) do you use?
nvim + CoC

Which version of HLS do you use and how did you install it?
1.9.0.0 from ghcup

Have you configured HLS in any way (especially: a `hie.yaml` file)?
No, using default config

**Comment by jship** [comment]
As a temporary fix, copying the `~/.ghcup/hls/1.9.0.0/haskell-language-server-9.2.5` binary directly into `~/.ghcup/bin` works fine

**Comment by hasufell** [comment]
You're supposed to **set** a HLS version and then execute that. We don't support running qualified hls like that.

If you want to run a custom hls, do this:

```sh
ghcup run --hls 1.9.0.0 -- haskell-language-server-wrapper
```

**Comment by jship** [comment]
Ah, my mistake. I had installed via `ghcup tui` and didn't realize a fresh install when no other HLS was present also required setting that version. Works great after explicitly setting - thanks!
