### ISSUE TITLE
Code completion imports the current module when completing a TH lens

### ISSUE THREAD

**Issue by Ptival** [haskell/haskell-language-server#3474]
I'm on 1.9.0.0, compiled with GHC 9.4.4, working on a 9.4.4 project.

Consider:
```haskell
{-# LANGUAGE TemplateHaskell #-}

module LensCompletion where

import Control.Lens ( makeLenses )

newtype Testing = Testing
  { _someField :: Int
  }

makeLenses ''Testing
```

Now start typing:
```haskell
whatever = someF<Trigger-code-completion>
```

This will add a cyclic import:
```haskell
import LensCompletion (someField)
```
at the top of the current file.

It's quite annoying, likely never the correct thing to do.

This might already have been reported (I'd be surprised if not), but I did a search and could not find it. Sorry if this is a duplicate.

**Comment by michaelpj** [comment]
Is the TH important here? Or does this happen whenever you try and import something which is defined in the current module?
