### ISSUE TITLE
Multiline expressions

### ISSUE THREAD

**Issue by deemp** [haskell/haskell-language-server#3487]
### Your environment

HLS 1.9.0.0 from `nixpkgs`. `inputs.nixpkgs.rev` = `3954218cf613eba8e0dcefa9abe337d26bc48fd0`, VS Codium from `nixpkgs`

Which OS do you use?

Ubuntu

Which version of GHC do you use and how did you install it?

9.2.5

How is your project built (alternative: link to the project)?

cabal build

Which LSP client (editor/plugin) do you use?

Which version of HLS do you use and how did you install it?

Have you configured HLS in any way (especially: a `hie.yaml` file)?

### Steps to reproduce

1. See [multiline expressions](https://github.com/haskell/haskell-language-server/blob/master/plugins/hls-eval-plugin/README.md#multiline-expressions)

1. Paste a doctest [example](https://hackage.haskell.org/package/doctest#multi-line-input) like

```hs
-- >>> :{
--  let
--    x = 1
--    y = 2
--  in x + y + multiline
-- :}
-- 6
multiline = 3
```

### Expected behaviour

the code outputs `6`

### Actual behaviour

the code outputs:

```hs
-- >>> :{
-- unknown command '{'
```

**Comment by deemp** [comment]
Related: https://github.com/haskell/haskell-language-server/issues/1817

**Comment by michaelpj** [comment]
I think in fact it's a dupe.
