### ISSUE TITLE
[RELEASE] 1.9.1.0

### ISSUE THREAD

**Issue by hasufell** [haskell/haskell-language-server#3488]
## Release checklist

- [x] check ghcup supports new GHC releases if any
     - https://github.com/haskell/ghcup-metadata/compare/98ca9d2%5E...develop#diff-9d111791ed64e71b59591ea50be7526f5e6690df7ca161cfd70b4247b7d719ea
- [x] set the supported GHCs in workflow file
- [x] check all plugins still work
- [x] bump package versions
- [x] generate and update changelog
- [x] create release branch
    - https://github.com/haskell/haskell-language-server/tree/wip/1.9.1.0
- [x] create release tag
- [x] trigger release pipeline (creates a draft)
- [x] run `scripts/release/download-gh-artifacts` to add FreeBSD bindist and signatures
- [x] upload bindists to downloads.haskell.org
- [x] create PR to ghcup-metadata
- [x] get sign-off on release
- [x] publish release on github
- [x] upload hackage packages
- [x] update https://github.com/haskell/ghcup-metadata/blob/develop/hls-metadata-0.0.1.json
- [ ] update https://haskell-language-server.readthedocs.io/en/latest/support/ghc-version-support.html#current-ghc-version-support-status
- [x] post release on discourse and reddit

----

@wz1000 @michaelpj @pepeiborra @fendor

**Comment by hasufell** [comment]
GHC versions to be supported will be: `["9.4.4", "9.2.6", "9.2.5", "9.0.2", "8.10.7"]`

**Comment by hasufell** [comment]
Pipeline triggered: https://github.com/haskell/haskell-language-server/actions/runs/4151253439

**Comment by hasufell** [comment]
New run removing 9.2.6 windows build due to https://gitlab.haskell.org/ghc/ghc/-/issues/22961

* https://github.com/haskell/haskell-language-server/actions/runs/4152410104
* https://cirrus-ci.com/build/6362202936967168

**Comment by hasufell** [comment]
New run removing 9.0.2 on Darwin M1 [due to build failures](https://github.com/haskell/haskell-language-server/actions/runs/4152410104/jobs/7183346369):

* https://github.com/haskell/haskell-language-server/actions/runs/4152495742
* https://cirrus-ci.com/build/4752999420002304

**Comment by hasufell** [comment]
* draft release: https://github.com/haskell/haskell-language-server/releases/tag/untagged-00055a881b97eb1dfb33
* release artifacts: https://downloads.haskell.org/~hls/haskell-language-server-1.9.1.0/
* ghcup-metadata PR: https://github.com/haskell/ghcup-metadata/pull/71

Testing:

```sh
ghcup -s https://raw.githubusercontent.com/haskell/ghcup-metadata/5b0adcc859269be290673132323c45838802423c/ghcup-0.0.7.yaml install hls 1.9.1.0
```

----

Can I get at least two sign-offs @wz1000 @michaelpj @fendor @pepeiborra

**Comment by fendor** [comment]
LGTM, tried the release with ghc 9.2.5 on linux :+1:

**Comment by michaelpj** [comment]
I haven't had a chance to test the binaries, but the release branch and changelog look good, CI runs look plausible. So LGTM!

I gather we're missing bindists for a couple of platforms for various reasons. @hasufell how do you think we should advertise this? We can put it in the release notes, will ghcup give users a comprehensible error if they try and install for one of the platform/GHC combinations with missing bindists?

**Comment by wz1000** [comment]
Unsetting the the `ghc-check-use-package-abis` cabal flag for `ghc-check` allows the build to suceed on Windows with 9.2.6:

```diff
diff --git a/cabal.project b/cabal.project
index 73e93be97..d2768097d 100644
--- a/cabal.project
+++ b/cabal.project
@@ -66,6 +66,7 @@ constraints:
   hlint +ghc-lib,
   ghc-lib-parser-ex -auto,
   stylish-haskell +ghc-lib,
+  ghc-check -ghc-check-use-package-abis,
   fourmolu -fixity-th
```

I think it is safe to unset on other platforms as well because the wrapper script already performs the package abi check.

**Comment by hasufell** [comment]
> because the wrapper script already performs the package abi check

Not if you use `ghcup compile hls` and end up changing compiler (can easily happen when stack is involved).

**Comment by wz1000** [comment]
I'm not convinced that check ever worked reliably because we still ran into issues with mismatching ABI after it was implemented.

**Comment by wz1000** [comment]
I mean the check in `ghc-check` specifically.

If you use `ghcup compile hls` that will build from master?

**Comment by wz1000** [comment]
It's also the wrong place for the check because any Haskell code can segfault before it reaches the check if the ABI is incompatible.

**Comment by wz1000** [comment]
Right, `ghcide` doesn't use the package abi information check returned by `ghc-check`:

https://github.com/haskell/haskell-language-server/blob/d3a5ee1a6db38fd4604bb42cd3e332a35414969f/ghcide/session-loader/Development/IDE/Session.hs#L658-659

In order to actually check the ABIs, we would need to run `_ghcLibCheck`. Without this, ABIs are not checked at all, only `ghc --version`. 

So using `ghc-check -ghc-check-use-package-abis` is completely harmless and has no effect on ghcide behaviour.

**Comment by wz1000** [comment]
Here is the code generating that result in `ghc-check`:

```haskell
        if runTime /= compileTime
          then InstallationMismatch {libdir = runTimeLibdir, ..}
          else InstallationChecked compileTime
            $ flip gcatchSafe (pure . PackageCheckError)
            $ do
              runTimeVersions <- collectPackageVersions (map fst compileTimeVersions)
              let compares =
                    if isUnstableGhcVersion (lookup "ghc" runTimeVersions)
                      then Map.empty
                      else Map.intersectionWith
                            comparePackageVersions
                            compileTimeVersionsMap
                            (Map.fromList runTimeVersions)
                  failure = PackageCheckFailure <$> nonEmpty (Map.toList $ Map.filter isPackageCheckFailure compares)
                  success = PackageCheckSuccess <$> nonEmpty (Map.toList compares)
                  inconclusive = PackageCheckInconclusive (map fst compileTimeVersions)

              return $ fromMaybe inconclusive (failure <|> success)


```

Notice that the second argument of `InstallationChecked` is a monadic action that needs to be run to actually perform the check, we do not do in current `ghcide`.

**Comment by hasufell** [comment]
Understood. Will trigger another run shortly.

**Comment by hasufell** [comment]
New pipeline running with the `cabal.project` patch:

* https://github.com/haskell/haskell-language-server/actions/runs/4164245614
* https://cirrus-ci.com/build/5556688531488768

**Comment by hasufell** [comment]
All done.

Except https://haskell-language-server.readthedocs.io/en/latest/support/ghc-version-support.html#current-ghc-version-support-status

**Comment by hasufell** [comment]
Discourse thread: https://discourse.haskell.org/t/ann-hls-1-9-1-0-released/5808

Forward port: https://github.com/haskell/haskell-language-server/pull/3493
