### ISSUE TITLE
GHC 9.6 support

### ISSUE THREAD

**Issue by 9999years** [haskell/haskell-language-server#3502]
This is a tracking issue for GHC 9.6 support.

We'll need to update `hie-compat` for GHC 9.6: https://github.com/haskell/haskell-language-server/blob/a73c07c51b9dabf9b8551a30744e7e1ffdea6c3a/hie-compat/hie-compat.cabal#L49-L56

Please collect other issues needed to land support for GHC 9.6 here.

**Comment by wz1000** [comment]
Have you seen https://github.com/haskell/haskell-language-server/pull/3480

**Comment by 9999years** [comment]
@wz1000 I hadn't! I'd only searched the open issues for PRs. That's great, glad to see work is underway.
