### ISSUE TITLE
hls-cabal-git interaction leaving git repo in detached head state

### ISSUE THREAD

**Issue by harendra-kumar** [haskell/haskell-language-server#3521]
### Your environment

Which OS do you use?

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

Which version of GHC do you use and how did you install it?

GHC 9.2.x, via nix and via ghcup

How is your project built (alternative: link to the project)?

Using cabal and cabal.project file - https://github.com/composewell/streamly-examples/blob/master/cabal.project.user

Which LSP client (editor/plugin) do you use?

CoC neovim

Which version of HLS do you use and how did you install it?

```
$ haskell-language-server --version
2023-03-14T09:09:31.225705Z | Info | No log file specified; using stderr.
haskell-language-server version: 1.7.0.0 (GHC: 9.2.2) (PATH: /nix/store/5jpmvbjad6i71mmz4059l19746yj2bnj-haskell-language-server-1.7.0.0/bin/haskell-language-server)
```

Have you configured HLS in any way (especially: a `hie.yaml` file)?

https://github.com/composewell/streamly-examples/blob/master/hie.yaml

### Steps to reproduce

Use a `cabal.project` file with a source-repository package stanza like the following:

```
source-repository-package
  type: git
  location: https://github.com/composewell/streamly
  tag: 24926eb041da4bc25c55460e0ecbf18fcb33e990
```

The usual workflow that triggers this bug is as follows:

* We are working in a git repo
* have a `cabal.project` file in the repo like above
* Use a `git difftool` command to see the diff of modified files in the repo
* this command opens neovim with a side-by-side diff, neovim CoC triggers hls
* Make some edits to a file in the diff and save it
* quit the editor

Our repo is now in a detached head state. 

It does not happen always, but when it starts happening it happens all the time in a reproducible manner. Because of this we had to change all our repos to not have a cabal.project file because we accidentally trigger this bug. Instead we use a `cabal.project.user` file, so that hls does not work on it by default.

I once tested this and it happened even without using git difftool as well. I just needed to open a file and modify it. Perhaps the modification makes it do some interaction with hls, which triggers the issue.

### Expected behaviour

It sounds very dangerous that hls makes the repository go in a detached head state. hls/cabal should not change the project git repository at all in any way.

I am not sure if this is a hls bug or a cabal bug. But it is always triggered by hls. cabal builds always work fine.

### Actual behaviour

Repository is left in a detached head state.

### Debug information

No debug info.

**Comment by fendor** [comment]
Hi, thank you for your bug report!

I don't think this is a HLS bug per se. HLS is not invoking git whatsoever. Cabal might be messing up in some capacity, what version of cabal are you using?

Also, have you made sure neovim doesn't do something funky? In HLS, we always use a cabal.project file, with lots of source-repository-package stanzas. So far, I am not aware of any similar reports.

**Comment by fendor** [comment]
> If you can explain a bit how hls interacts with cabal, I might have some pointers to follow.

There are three commands we invoke `cabal` with:
```bash
$ cabal exec -- ghc --print-libdir
$ cabal exec -v0 -- ghc -package-env=- -ignore-dot-ghci -e "Control.Monad.join (Control.Monad.fmap System.IO.putStr System.Environment.getExecutablePath)"
$ cabal --builddir=<custom-build-dir> v2-repl --with-compiler <ghc-shim> --with-hc-pkg <ghc-pkg-shim> Haskell/Source.hs
```

Respectively to find the libdir of ghc, then what the location of the ghc executable is cabal would use to build the project, and then build the project with some shims using `cabal repl` and obtain the compilation options.
That's all, if I am not mistaken.

**Comment by fendor** [comment]
That should be uninterruptible, and I don't recall any bug reports about that.

**Comment by harendra-kumar** [comment]
I am closing it then.
