### ISSUE TITLE
Suggest new open imports

### ISSUE THREAD

**Issue by expipiplus1** [haskell/haskell-language-server#353]
It would be nice if in addition to closed (or qualified) imports HLS would suggest adding an open import for a missing symbol. 

As far as I can tell this is the only bit which would need to change: https://github.com/jneira/ghcide/blob/f4f575dbdd0cf37fc60d2a11215cb35368d3a334/src/Development/IDE/Plugin/CodeAction.hs#L749-L767

Indiscriminate open imports are certainly not a good thing, but here and there they can be useful.

I'm pretty sure HIE used to suggest these.

**Comment by expipiplus1** [comment]
Ah, I realize that this should probably have been opened against ghcide

**Comment by konn** [comment]
+1 for it, since one can now make import list closed afterwards with the newly added import lense feature.

It is more desirable if it could automatically generate the `hiding` clause if there are some symbol collisions with already imported ones.

**Comment by expipiplus1** [comment]
@pepeiborra got there first: https://github.com/digital-asset/ghcide/pull/740

**Comment by jneira** [comment]
So this was closed by https://github.com/haskell/ghcide/pull/740?, closing optimistically
