### ISSUE TITLE
Hls reports a prelude error when replacement prelude is an internal library mixin

### ISSUE THREAD

**Issue by jhgarner** [haskell/haskell-language-server#3532]
### Your environment

Which OS do you use?
Nixos

Which version of GHC do you use and how did you install it?
9.2.6 installed from nixpkgs

How is your project built (alternative: link to the project)? https://github.com/jhgarner/hls-minimal-reproducible-example

Which LSP client (editor/plugin) do you use? VSCode + haskell extension

Which version of HLS do you use and how did you install it? 1.9.0.0 (GHC: 9.2.6) (PATH: /nix/store/7vx128y0yrmijfj5k6kzf3r6snf3w084-haskell-language-server-1.9.0.0/bin/.haskell-language-server-9.2.6-unwrapped)

Have you configured HLS in any way (especially: a `hie.yaml` file)? No, see example repo.

### Steps to reproduce

See example repository. It contains a cabal (not stack) project which uses mixins to include a custom prelude. The custom prelude comes from an internal library defined in the same cabal file.

### Expected behaviour

Since Cabal builds the project fine, I expect HLS to report no errors on the Lib.hs file from the repo. 

### Actual behaviour

Instead it reports an error in the Lib.hs file:

```
Could not load module ‘Prelude’
  It is a member of the hidden package ‘base-4.16.4.0’.
  Perhaps you need to add ‘base’ to the build-depends in your .cabal file.
```

See hls.log in the example repo for the full output from the haskell-language-server command.
The cabal log is in cabal.log.

### Debug information

Log snippets are included in the example repo https://github.com/jhgarner/hls-minimal-reproducible-example

Using a custom prelude mixin works if I use a package from Hackage such as Relude.

**Comment by fendor** [comment]
Hi, thank you for your bug report!

I cannot reproduce the issue locally, with version 1.9.1.0 (but there should be no difference in project initilisation to 1.9.0.0)

Taking a look at your logs, I see the paths: `/home/user/sources/hls-minimal-reproducible-example/dist-newstyle/` in `cabal.log`, while `hls.log` reports:
`Directory: /home/user/sources/hls-minimal-reproducible-example/broken`.

These should match up, so either your logs are out-of-date, or make sure you invoke HLS from the directory where the `*.cabal` file exists. Is there a `cabal.project` file involved that you are not showing?

**Comment by NickSeagull** [comment]
I'm getting the same error. Just created a new Stack project with `stack new` and used `relude` as a mixin for Prelude. HLS doesn't seem to figure that out.

**Comment by fendor** [comment]
Can you provide the output of `haskell-language-server-wrapper --debug <some-hs-file-in-your-project>`?
