### ISSUE TITLE
Implement `completionItem/resolve` for more completion types

### ISSUE THREAD

**Issue by michaelpj** [haskell/haskell-language-server#3535]
LSP allows you to implement `completionItem/resolve` to delay the computation of some parts of completion items. The advantages are similar to https://github.com/haskell/haskell-language-server/issues/3534, but mostly it's about avoiding expensive computation.

We got support for `completionItem/resolve` for Haskell completions in https://github.com/haskell/haskell-language-server/pull/3204, but we have other completion providers e.g. the pragmas plugin. It would be good to implement `completionItem/resolve` in more places.

As with https://github.com/haskell/haskell-language-server/issues/3534, doing this properly would mean figuring out a way to make it easy for plugin authors to opt into it.

**Comment by joyfulmantis** [comment]
Upon investigation, this may be a non-issue. From my investigation, plugin authors can already use completionItem/resolve by making a plugin handler for the SCompletionItemResolve type. Furthermore, the pragmas plugin is the only other plugin offering completion, and that plugin does not provide anything for the detail or documentation fields of completionItem, which are the fields that completionItem/resolve is built to provide.

From the spec:
> A typical use case is for example: the ‘textDocument/completion’ request doesn’t fill in the documentation property for returned completion items since it is expensive to compute. When the item is selected in the user interface then a ‘completionItem/resolve’ request is sent with the selected completion item as a parameter. The returned completion item should have the documentation property filled in. By default the request can only delay the computation of the detail and documentation properties.

For these reasons, I believe this issue can be closed.

**Comment by michaelpj** [comment]
> Furthermore, the pragmas plugin is the only other plugin offering completion, and that plugin does not provide anything for the detail or documentation fields of completionItem, which are the fields that completionItem/resolve is built to provide.

Right, it's indeed unclear whether any of the actual completions implementations that we have will benefit from this, since most of them are cheap. Pragmas are cheap, probably whatever we end up with for the cabal plugin will be cheap, it's really only the primary Haskell completions that are expensive, and there it's already implemented.

> From my investigation, plugin authors can already use completionItem/resolve by making a plugin handler for the SCompletionItemResolve type.

Right, the issue is that (IMO) it's not terribly easy to do. All the `/resolve` methods give you as a parameter the item you returned in the original request. So you have to 
- Put some identifier in the item so that you can later work out what entity it refers to
- In the resolve handler, reconstruct any state that you might need in order to work out further information about that entity

Maybe there's nothing really to do here, and we just need some examples for people to follow, but  I wonder if we could make it easier, even by just giving people a little interface to implement that gives them both, e.g. 
```
mkCompletionHandlerWithResolve :: (FromJSON key, ToJSON key) => (CompletionItemRequest -> [(CompletionItem, key)]) -> (key -> CompletionItem) -> Handlers
```
which would compute a serializable key for every completion item, stick it in the `data` field, and then pull it back out and use it to create a fuller completion item in the resolve handler. Not really doing all that much, but it nudges people in the right direction.

**Comment by lf-** [comment]
I am not sure if this is a bug in coc.nvim or in HLS, since I would class it as a "protocol misunderstanding/disagreement". But: completions are not getting documentation from HLS because HLS promises to have resolveable completions, but then *errors* the request instead of returning the same documentation that was sent in the `textDocument/completion` request. The end result is you can't see the module that things come from when invoking completion with coc.nvim, which is pretty bad!

Again, don't know whose bug this is, but HLS is on the scene with odd behaviour.
```
[Trace - 17:03:42.938] Received response 'textDocument/completion - (13)' in 34ms.
Result: {
    "isIncomplete": true,
    "items": [
        {
            "command": {
                "arguments": [
                    {
                        "doc": "file:///home/jade/.dotfiles/bin/intercept2chrome.hs",
                        "importName": "System.Directory.Internal.Prelude",
                        "importQual": null,
                        "newThing": "getArgs",
                        "thingParent": null
                    }
                ],
                "command": "2827480:ghcide-extend-import-action:extendImport",
                "title": "extend import"
            },
            "detail": "from System.Directory.Internal.Prelude",
            "documentation": {
                "kind": "markdown",
                "value": "*Defined in 'System.Directory.Internal.Prelude'*\n"
            },
            "insertText": "getArgs",
            "insertTextFormat": 2,
            "kind": 3,
            "label": "getArgs",
            "sortText": "00"
        },
        {
            "command": {
                "arguments": [
                    {
                        "doc": "file:///home/jade/.dotfiles/bin/intercept2chrome.hs",
                        "importName": "System.Environment",
                        "importQual": null,
                        "newThing": "getArgs",
                        "thingParent": null
                    }
                ],
                "command": "2827480:ghcide-extend-import-action:extendImport",
                "title": "extend import"
            },
            "detail": "from System.Environment",
            "documentation": {
                "kind": "markdown",
                "value": "*Defined in 'System.Environment'*\n"
            },
            "insertText": "getArgs",
            "insertTextFormat": 2,
            "kind": 3,
            "label": "getArgs",
            "sortText": "01"
        },
(.....)
```

```
[Trace - 17:03:43.464] Sending request 'completionItem/resolve - (15)'.
Params: {
    "command": {
        "arguments": [
            {
                "doc": "file:///home/jade/.dotfiles/bin/intercept2chrome.hs",
                "importName": "System.Directory.Internal.Prelude",
                "importQual": null,
                "newThing": "getArgs",
                "thingParent": null
            }
        ],
        "command": "2827480:ghcide-extend-import-action:extendImport",
        "title": "extend import"
    },
    "detail": "from System.Directory.Internal.Prelude",
    "documentation": {
        "kind": "markdown",
        "value": "*Defined in 'System.Directory.Internal.Prelude'*\n"
    },
    "insertText": "getArgs",
    "insertTextFormat": 2,
    "kind": 3,
    "label": "getArgs",
    "sortText": "00"
}


2023-10-23T00:03:43.464592Z | Warning | No plugin enabled for SMethod_CompletionItemResolve
[Trace - 17:03:43.464] Received response 'completionItem/resolve - (15)' in 0ms. Request failed: No plugin enabled for SMethod_CompletionItemResolve, potentially available: ghcide-completions (-32601).
[Error - 17:03:43.465] Sending request completionItem/resolve failed.
  Message: No plugin enabled for SMethod_CompletionItemResolve, potentially available: ghcide-completions
  Code: -32601 
[Error - 17:03:43.465] Request completionItem/resolve failed.
  Message: No plugin enabled for SMethod_CompletionItemResolve, potentially available: ghcide-completions
  Code: -32601 
```

Probable cause inside of coc.nvim:

https://github.com/lf-/coc.nvim/blob/7aab006ccea9ca3a0f8f240684e37c55a6fe1052/src/completion/floating.ts#L20-L36

**Comment by lf-** [comment]
Confirmed this is the problem by crudely ripping out the code from coc.nvim that performs the `completionItem/resolve` request if supported. Should I file another bug? idk

**Comment by joyfulmantis** [comment]
@lf- Please see issue #3842

**Comment by michaelpj** [comment]
I think we mostly did this

**Comment by lf-** [comment]
> @lf- Please see issue #3842

fyi this bug is against a completely unrelated LSP client stack and I suspect it's unrelated. I can test against master I guess and see if completions are still broken.

**Comment by michaelpj** [comment]
For at least one bit of the improvement we need a new `lsp` release.

**Comment by createyourpersonalaccount** [comment]
How to stop this "SMethod_CompletionItemResolve" warning? It's really really annoying.
