### ISSUE TITLE
Missing releases for various plugins.

### ISSUE THREAD

**Issue by maralorn** [haskell/haskell-language-server#3550]
The latest released version of hls-rename-plugin has a cabal flag to not build on ghc >= 9.4. A release with commit 472947cdb9e711f6ef889bba3b83b0dd44a1b6bc would be desirable.

**Comment by maralorn** [comment]
Similar for hls-floskell-plugin. Here we are missing commit ddc67b2d4d719623b657aa54db20bf58c58a5d4a

**Comment by maralorn** [comment]
hie-compat is also affected

**Comment by michaelpj** [comment]
@wz1000 did this get resolved?

**Comment by cumber** [comment]
@michaelpj No, as of today hls-floskell-plugin, hls-rename-plugin, and hls-stylish-haskell-plugin all have `base` bounds that say they work up to `base < 5`, but then all have `if impl(ghc >= 9.3) buildable: False` buried inside the cabal file, so they can't work on GHC 9.4 and 9.6.

**Comment by simonmichael** [comment]
I spent an hour troubleshooting this today. Here's how to disable those plugins and get HLS 0.10.0.0 installed for your GHC version with ghcup:
```
$ ghcup -v compile hls -v 1.10.0.0 --ghc 9.4.5 -- -f 'haskell-language-server -floskell -stylishhaskell -rename' 
```

**Comment by michaelpj** [comment]
Old, so hopefully this stuff is better now
