### ISSUE TITLE
hls-tactics-plugin prevents building 1.10.0 for ghc 9.0 and 8.10

### ISSUE THREAD

**Issue by juhp** [haskell/haskell-language-server#3554]
### Your environment
Which OS do you use?  Linux
Which version of GHC do you use and how did you install it?
ghc8.10 and ghc9.0 from Fedora Linux
How is your project built (alternative: link to the project)?
https://github.com/fedora-haskell/haskell-language-server

### Steps to reproduce

$ cabal install haskell-language-server-1.10.0.0 -w ghc-8.10.7
(or ghc-9.0.2)

(Well actually `rpmbuild -bb haskell-language-server.spec`)

### Actual behaviour
```
[__0] trying: haskell-language-server-1.10.0.0 (user goal)
[__1] trying: haskell-language-server:+tactic
[__2] trying: hls-tactics-plugin-1.8.0.0 (dependency of
haskell-language-server +tactic)
[__3] next goal: ghcide (dependency of haskell-language-server)
[__3] rejecting: ghcide-1.10.0.0 (conflict: hls-tactics-plugin =>
ghcide^>=1.9)
[__3] rejecting: ghcide-1.9.1.0 (conflict: haskell-language-server =>
ghcide==1.10.0.0)
```

originally mentioned in #3546

**Comment by juhp** [comment]
For now I went ahead disable the tactics plugin for these ghc versions.

(btw it is also confusing that the flag is called tactic but the plugin is tactics)

**Comment by michaelpj** [comment]
@wz1000 is this resolved?

**Comment by juhp** [comment]
I think this can be closed, right?

**Comment by fendor** [comment]
If you say this is fixed, yes :)
