### ISSUE TITLE
cabal install haskell-language-server-1.10.0.0 --with ghc-9.6.1 fails

### ISSUE THREAD

**Issue by juhp** [haskell/haskell-language-server#3557]
### Your environment
Which OS do you use?  Linux
Which version of GHC do you use and how did you install it?
ghc9.6 from Fedora Linux
How is your project built (alternative: link to the project)?
https://github.com/fedora-haskell/haskell-language-server

### Steps to reproduce

$ cabal install haskell-language-server-1.10.0.0 -w ghc-9.6.1

### Actual behaviour
```
Error: cabal: Could not resolve dependencies:
[__0] trying: haskell-language-server-1.10.0.0 (user goal)
[__1] trying: binary-0.8.9.1/installed-0.8.9.1 (dependency of
haskell-language-server)
[__2] trying: lsp-1.6.0.0 (dependency of haskell-language-server)
[__3] trying: uuid-1.3.15 (dependency of lsp)
[__4] next goal: cryptohash-md5 (dependency of uuid)
[__4] rejecting: cryptohash-md5-0.11.101.0 (conflict: binary =>
base==4.18.0.0/installed-4.18.0.0, cryptohash-md5 => base>=4.5 && <4.18)
[__4] rejecting: cryptohash-md5-0.11.100.1 (conflict: binary =>
base==4.18.0.0/installed-4.18.0.0, cryptohash-md5 => base>=4.5 && <4.16)
[__4] rejecting: cryptohash-md5-0.11.100.0 (conflict: binary =>
base==4.18.0.0/installed-4.18.0.0, cryptohash-md5 => base>=4.5 && <4.10)
[__4] rejecting: cryptohash-md5-0.11.7.2 (conflict: uuid =>
cryptohash-md5>=0.11.100 && <0.12)
[__4] skipping: cryptohash-md5-0.11.7.1 (has the same characteristics that
caused the previous version to fail: excluded by constraint '>=0.11.100 &&
<0.12' from 'uuid')
[__4] fail (backjumping, conflict set: binary, cryptohash-md5, uuid)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, uuid, binary, lsp,
cryptohash-md5, memory, haskell-language-server
Try running with --minimize-conflict-set to improve the error message.
```
Logs at https://download.copr.fedorainfracloud.org/results/petersen/haskell-language-server/fedora-rawhide-x86_64/05745213-haskell-language-server-ghc9.6/

**Comment by juhp** [comment]
Next is:
```
[__5] rejecting: base-4.18.0.0/installed-4.18.0.0 (conflict: co-log-core =>
base>=4.10.1.0 && <4.18)
[__5] skipping: base-4.18.0.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=4.10.1.0 && <4.18' from
'co-log-core')
```

**Comment by MaciekFlis** [comment]
@juhp did you manage to build it?

**Comment by juhp** [comment]
No - I am assuming the only way currently might be with `allow-newer`?

**Comment by ocharles** [comment]
I get:

```
[__0] trying: haskell-language-server-1.10.0.0 (user goal)
[__1] trying: hiedb-0.4.3.0 (dependency of haskell-language-server)
[__2] trying: hie-compat-0.3.1.0 (dependency of hiedb)
[__3] next goal: base (dependency of haskell-language-server)
[__3] rejecting: base-4.18.0.0/installed-4.18.0.0 (conflict: hie-compat =>
base<4.18)
```

**Comment by fendor** [comment]
In our [`cabal.project`](https://github.com/haskell/haskell-language-server/blob/master/cabal.project) we do have all the `allow-newer` stanzas necessary to compile HLS with GHC > 9.4. I don't think there is anything we can do about that. However, hie-compat is missing a revision for `base < 4.18`

**Comment by fendor** [comment]
I uploaded the `hie-compat` version `0.3.1.1`. That should fix the error shown in https://github.com/haskell/haskell-language-server/issues/3557#issuecomment-1546614383, but again, the other `allow-newer`'s are still required.

**Comment by MaciekFlis** [comment]
I was able to build hls with new hie-compat, but had to disable rename plugin

**Comment by ocharles** [comment]
> the other allow-newer's are still required

Is this because of packages that are not maintained by anyone who maintains HLS?

**Comment by fendor** [comment]
> Is this because of packages that are not maintained by anyone who maintains HLS?

Yeah, I think so.

> I was able to build hls with new hie-compat, but had to disable rename plugin

True that, Iet's try removing all these `allow-newer` then!

**Comment by juhp** [comment]
Also [builds](https://copr.fedorainfracloud.org/coprs/build/5918071) now for me, thanks!

I agree the allow-newer are no longer needed: and should be avoided afap. :-)
