### ISSUE TITLE
Duplicate log in client

### ISSUE THREAD

**Issue by July541** [haskell/haskell-language-server#3564]
As the image shows below, we have two kinds of logs for each piece. Not sure how it happened, but I'm sure it is caused by `handleMaybeM` or `pluginResponse` since the following plugins are using the same pattern.

And it is worth noticing, these warnings printed while I was typing, it is just temporary status and shouldn't be treated as a warning in my mind.

<img width="992" alt="image" src="https://user-images.githubusercontent.com/16057632/232808790-3bc9876c-d057-46b5-8491-b9e2d23a76a0.png">

**Comment by fendor** [comment]
I agree, these shouldn't be warnings. The logging needs some attentive eyes, making sure everything is consistent.

**Comment by michaelpj** [comment]
I think this is because we send our logs to the client with `window/logMessage`, and _also_ log it to stderr. Some clients show both and then you get this. It's unclear what we should do.

**Comment by July541** [comment]
`vscode` capture all output as default, we can disable `window/logmessage` or `stderr`, but not sure if it will miss out something🤔

**Comment by michaelpj** [comment]
We don't send logs to the client by default now.
