### ISSUE TITLE
Symbol renaming work in simple modules without any exports does not work

### ISSUE THREAD

**Issue by halloleo** [haskell/haskell-language-server#3571]
### Your environment

Using VS Code as LSP client with Haskell 9.2.5 via ghcup on macOS. HLS is on 1.9.1

### Steps to reproduce

Write a simple module `Cnt.hs`:

```
-- File Cnt.hs
module Cnt where

mostFrequentChar' :: String -> Char -> Int -> (Char, Int)
mostFrequentChar' [] maxChar maxFreq = (maxChar, maxFreq)
mostFrequentChar' (c:cs) maxChar maxFreq =
    let freq = count c (c:cs)
    in if freq > maxFreq
        then mostFrequentChar' cs c freq
        else mostFrequentChar' cs maxChar maxFreq
    where count x xs = length $ filter (== x) xs
```

No exports needed. (I will load the file into ghci to play with it.)

Then try to rename `mostFrequentChar'` to `mostFrequentChar`. 
### Expected behaviour

I expected that `mostFrequentChar'` is changed to `mostFrequentChar`. 

### Actual behaviour

No renaming is performed, but you get (in VS Code):

![f66fff2629027c4a07f98d65705df3f9284b34bf](https://user-images.githubusercontent.com/1521852/233813646-4e803940-48cf-4049-aefb-c325e987311f.png)

### See also

I discussed this problem first [on the Haskell discourse](https://discourse.haskell.org/t/in-vs-code-how-to-make-symbol-renaming-work-in-simple-modules/6054).

**Comment by July541** [comment]
Thanks for your report! It's a known limitation for hls-rename-plugin, see https://github.com/haskell/haskell-language-server/issues/3130 for details.

**Comment by halloleo** [comment]
Thanks for picking this up, @July541.

I had a look at #3130 and I saw the tip about `"haskell.plugin.rename.config.crossModule": true`. Interesting, but how can a crossModule setting help in a local rename situation?

I think I don't understand...

**Comment by July541** [comment]
> but how can a crossModule setting help in a local rename situation?

Rename only work for local symbols, without the explicit export list, hls with consider all function as exported symbols, that doesn't work.

So you have two choices:

1. Supply an explicit export list, and rename local symbols.
2. Enable `crossModule` even if it's an experimental item.

**Comment by halloleo** [comment]
Ah, makes sense: The initial error means I can normally rename *local* symbols only _with_ export list, but with the crossModule setting I can rename local symbols _even without_ export list, right?

Then excuse my newbie question, but *in which file* do I need to set this HLS setting `haskell.plugin.rename.config.crossModule: true` when I use HLS in VS Code?

**Comment by July541** [comment]
Precisely, you are renaming *exported symbols* with `crossModule` enabled since all symbols will be exported implicitly.

On the `Settings` page, and search `haskell rename`, you'll find it.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/16057632/234032374-bb3dcb06-463f-4b2e-98c0-95764ad80135.png">

**Comment by halloleo** [comment]
Thank you, @July541! This works brilliantly!

PS: Not sure whether I should close this issue...

**Comment by OlegAlexander** [comment]
Hello, and thank you for creating HLS! I'm on Windows in VSCode, and I just ran into the "Explicit export list required for renaming." Luckily, setting `haskell.plugin.rename.config.crossModule: true` seems to have fixed the problem. I'm new to Haskell, and I want to say that this error was very unexpected coming from other languages. I hope the `crossModule` renaming settings will be on by default in the future. Again, thank you for making HLS!

**Comment by sohang3112** [comment]
@July541 Thanks for your suggestion - in VS Code Settings, Haskell > Plugin > Rename > Config: Cross-Module , enabling checkbox "Enable Experimental Cross-Module Renaming" makes rename symbol work for modules without explicit export (eg. `module Main where`).

IMO this setting should be enabled by default.

**Comment by fendor** [comment]
It is enabled since the HLS 2.14 release #4817
