### ISSUE TITLE
hls removes the wrong redundant definition

### ISSUE THREAD

**Issue by expipiplus1** [haskell/haskell-language-server#358]
```haskell
module Foo where

a = ()

b = () where a = ()
```

- Apply the code action on `a` in the where clause of `b` to remove the redundant definition
- Observe that the top level `a` definition is the one removed!

**Comment by jneira** [comment]
I cant reproduce with last hls, it removes the definition inside the where for me. Feel free to reopen if it does not work for you.

![imagen](https://user-images.githubusercontent.com/54035/111922022-faf53200-8a97-11eb-9bcf-e46051e74d31.png)

![imagen](https://user-images.githubusercontent.com/54035/111922036-08aab780-8a98-11eb-8b50-d8210c0b791b.png)

**Comment by expipiplus1** [comment]
Great!
