### ISSUE TITLE
Type class constraint inserted as last line in source file

### ISSUE THREAD

**Issue by runeksvendsen** [haskell/haskell-language-server#360]
I'm using the `haskell.haskell` VSCode plugin (v1.1.0) with VSCode 1.48.1.

When I use the Quick Fix `Add <constraint> to the context of the type signature for <function>` the constraint(s) are inserted in the bottom of the source file. Please see attached screen recording for an illustration of the issue.

![hls-insert-constraint-bug](https://user-images.githubusercontent.com/1069247/91631688-c0348b00-e9db-11ea-917b-dfbddaa7b7f0.gif)

**Comment by jhrcek** [comment]
Hello, I'm also hitting this issue and couple of other odd behaviors with this context action.
I created a simple reproducer repository https://github.com/jhrcek/hls-add-to-context-broken

Here's a gif illustrating both two of the issues with this feature:

![hls-context-issue](https://user-images.githubusercontent.com/2716069/93889666-c4f21380-fce9-11ea-8ff6-0644fd6a7107.gif)

Info about my environment:
```bash
$ haskell-language-server --probe-tools
haskell-language-server version: 0.4.0.0 (GHC: 8.8.3) (PATH: /home/jhrcek/.local/bin/haskell-language-server) (GIT hash: b43a8cd78d10d77184a895293d766a0fbceb5573)
Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		2.3.3
ghc:		8.10.2
```

Could someone please take a look at this
