### ISSUE TITLE
Following -Werror from cabal file

### ISSUE THREAD

**Issue by fkrunic** [haskell/haskell-language-server#3602]
## Your environment 

Which OS do you use?
- macOS Monterey (12.6.6)

Which version of GHC do you use and how did you install it?
- 9.2.7 from ghcup 

How is your project built (alternative: link to the project)?
- Cabal 3.2.6.0

Which LSP client (editor/plugin) do you use?

- Neovim + HLS via `lsp-zero`. 

Which version of HLS do you use and how did you install it?
- 1.10.0.0 from ghcup

Have you configured HLS in any way (especially: a `hie.yaml` file)?
- No

## What's wrong?
The following options are specified under the `ghc-options` section of my cabal file: 
- `-Wall`
- `-Werror=missing-fields`
- `-Werror=incomplete-patterns`

How do I pass these options into HLS so that instead of highlighting missing fields or incomplete patterns as warnings in Neovim, it highlights them as build errors to match the behavior of `cabal build`? 

### Debug Information

LSP configuration in `after/plugin/lsp_config.lua`:

```
local lsp = require('lsp-zero')

lsp.preset('recommended')
lsp.ensure_installed({
  'lua_ls',
  'hls'
})

-- Fix for undefined 'vim'
lsp.nvim_workspace()
lsp.setup()

vim.diagnostic.config({
  virtual_text = false
})
```

**Comment by michaelpj** [comment]
We do get the flags from the cabal file. I believe the issue here is that we explicitly disable `-Werror` after all that, so that we don't block compilation for warnings.

There is some discussion in https://github.com/haskell/haskell-language-server/issues/853, probably continue there?

**Comment by fkrunic** [comment]
> We do get the flags from the cabal file. I believe the issue here is that we explicitly disable `-Werror` after all that, so that we don't block compilation for warnings.
> 
> There is some discussion in #853, probably continue there?

Sounds good, thank you!
