### ISSUE TITLE
Import bug, suggestion PRAGMA's not submodules

### ISSUE THREAD

**Issue by gweithio** [haskell/haskell-language-server#3617]
### Your environment

Which OS do you use?
MacOS M1 Pro Ventura 13.2

Which version of GHC do you use and how did you install it?
Via GHCUP

GHC 9.6.1 (base-4.18.0.0) happens with 9.2.7 also
Cabal 3.6.20
Stack 2.9.3

How is your project built (alternative: link to the project)?
Cabal

Which LSP client (editor/plugin) do you use?
Neovim with Coc
[gist example of the language server setup](https://gist.github.com/gweithio/0deabf4944b8e687a86a66aebb68d046)

Which version of HLS do you use and how did you install it?
HLS 2.0.0.0 from GHCUP, also happens with 1.10.0.0

Have you configured HLS in any way (especially: a `hie.yaml` file)?
Only Coc setup

### Steps to reproduce
Create a project via cabal init, go to app/Main.hs, proceed to import a module, such as `Data.List` or `Control.Concurrent`

### Expected behaviour

Provide only suggestions for submodules

### Actual behaviour

Whilst pressing . to access the submodule, PRAGMA's are suggested, such as, LANGUAGE, OPTIONS_GHC, then the submodules are at the bottom of the suggestion list 

![image](https://github.com/haskell/haskell-language-server/assets/32551776/f7d48618-1bd6-4f85-a745-1e13b37dd975)

**Comment by michaelpj** [comment]
This should definitely not happen, and I don't think it used to :thinking:

**Comment by akshaymankar** [comment]
I will work on this during ZuriHac.

**Comment by gweithio** [comment]
@akshaymankar I believe @fendor is working on it? he can correct me if not :)

**Comment by fendor** [comment]
I am not working on it, I was just adding the zurihac label, so this is free for the taking :)

**Comment by fendor** [comment]
Closed  by #3647
