### ISSUE TITLE
Supported code actions in coc.vim implementation?

### ISSUE THREAD

**Issue by peterstorm** [haskell/haskell-language-server#363]
Hello!

First of all, thank you for making this awesome project!

I just have a question, so I'm not even sure an issue is appropriate, but I hope it can be tagged as a question.

I was just wondering how much code action support there is with coc.vim?

**Comment by Ailrun** [comment]
Hello, @peterstorm. I think this question is more appropriate for the coc.vim repo as the implementation code action is not HLS specific, and is more about LSP clients.

**Comment by peterstorm** [comment]
Ok, thank you for your answer!
