### ISSUE TITLE
Code evaluation not working

### ISSUE THREAD

**Issue by jinl0ng** [haskell/haskell-language-server#364]
![image](https://user-images.githubusercontent.com/18110696/91679298-7f26ad00-eb7a-11ea-9778-fdf531bc4172.png)

And I found some error in haskell-language-server starting
![image](https://user-images.githubusercontent.com/18110696/91679511-12f87900-eb7b-11ea-961e-c4c6130d3534.png)

 
vscode haskell extension version: 1.1.0
haskell-language-serve version: 0.3.0.0 (GHC: 8.8.4)

**Comment by pepeiborra** [comment]
The markup is wrong.

# WRONG
```
-- | >>> foo
```

# RIGHT
```
-- >>> foo
```

**Comment by jinl0ng** [comment]
> The markup is wrong.
> 
> # WRONG
> ```
> -- | >>> foo
> ```
> 
> # RIGHT
> ```
> -- >>> foo
> ```

It works. Thanks
