### ISSUE TITLE
Code Action to import a qualified binding doesn't respect `ImportQualifiedPost`.

### ISSUE THREAD

**Issue by jumper149** [haskell/haskell-language-server#3645]
## Is your enhancement request related to a problem? Please describe.

Let's say I edit my program like this:

```haskell
f :: M.Map String String
f  = M.fromList []
```

When `Data.Map` is not yet imported qualified as `M`, then I can use a code action to add the import.
This will add:

```haskell
import qualified Data.Map as M
```

I am using `ImportQualifiedPost` and `-Wprepositive-qualified-module`.
The code action still puts "qualified" before the module.

## Describe the solution you'd like
I'd like the code action to respect `ImportQualifiedPost` when adding the import.

```haskell
import Data.Map qualified as M
```

There are 2 options that I find reasonable.

Either the code action uses the qualified syntax whenever `ImportQualifiedPost` is turned on.
Or the code action only uses the qualified syntax when both `ImportQualifiedPost` AND `-Wprepositive-qualified-module` are on.

I personally would argue for the first option (just `ImportQualifiedPost`), because of simplicity.

## Additional context

```
haskell-language-server version: 1.9.0.0 (GHC: 9.4.4) (PATH: /nix/store/hahlz8nx1b625k9dawh3js65ng8fba7c-haskell-language-server-1.9.0.0/bin/haskell-language-server-wrapper)
```

**Comment by michaelpj** [comment]
duplicate I think? https://github.com/haskell/haskell-language-server/issues/3362
