### ISSUE TITLE
Try using the nonmoving GC

### ISSUE THREAD

**Issue by michaelpj** [haskell/haskell-language-server#3656]
This uses 50% of the max memory of the copying GC. That would be pretty welcome for our users, but it's unclear whether the loss of defragmentation would bite us over time. I'm not sure how we could test this.

cc @wz1000

**Comment by michaelpj** [comment]
Yeah, I think the issue is that issues are likely to arise over time, so it's hard to test.

**Comment by fendor** [comment]
Make it available via a cabal flag and tell people to use it and report back?

**Comment by michaelpj** [comment]
I think people can probably already get it by passing RTS options to their HLS? I assume that overrides the ones we set in our .cabal file?

**Comment by fendor** [comment]
Oh, so it is not a compile time setting? Yeah, then let's just tell people about it.

**Comment by michaelpj** [comment]
Well, we can set the RTS flags in the cabal file too, so we can change the default.

**Comment by michaelpj** [comment]
I might see if I can persuade any GHC devs who use HLS on GHC and understand the GC to try this out, they might be more likely to notice issues.

**Comment by TeofilC** [comment]
We use the non-moving gc extensively at work and I think you're unlikely to get much lower memory usage with it than with the copying gc. At work we actually see slightly higher memory usage with the non-moving GC once fragmentation and overheads from its allocator are taken into account. But if HLS's allocation pattern is different to ours then you might see very different behaviour. The place where the non-moving GC really shines is in reducing GC pauses.

Despite that I think this is definitely worth trying.
I'll give the non-moving GC a try with HLS on our work codebase tomorrow and report back.

**Comment by michaelpj** [comment]
Thanks, that's very useful! That looks like it's at best a small improvement and sometimes worse, and may get even worse over time.

**Comment by TeofilC** [comment]
No worries. Hopefully this will get a bit better in GHC 9.8. I'm currently working on a patch that should shave something like 15-20% off the memory usage of the non-moving collector (https://gitlab.haskell.org/ghc/ghc/-/issues/23340).

**Comment by michaelpj** [comment]
Okay, this sounds like fairly convincing data that the nonmoving GC is certainly not a clear win, and so we should probably ignore it.

**Comment by TeofilC** [comment]
I've implemented some improvements to the non-moving GC's memory usage recently.

See mainly:
- https://gitlab.haskell.org/ghc/ghc/-/merge_requests/12152
- https://gitlab.haskell.org/ghc/ghc/-/merge_requests/10659

These will be in 9.10 and 9.12. So it might make sense to revisit this soon.

I'm hoping with these changes and some fine-tuning we can maybe beat or get close to the memory usage from the copying GC

**Comment by TeofilC** [comment]
Could we re-open this? @michaelpj @fendor 

I think it's time to revisit this now that GHC-9.12 is getting more users. 

Once I have a branch for building the $work codebase with 9.12 I'll do another round of tests

**Comment by TeofilC** [comment]
The very high memory usage you are seeing @guibou is likely caused by: https://gitlab.haskell.org/ghc/ghc/-/issues/27211

I can work around it by setting `-F1.2` then I get much more reasonable memory usage with the non-moving GC. Otherwise, I see the same thing as you where it just climbs
