### ISSUE TITLE
Multi Cradle: No prefixes matched

### ISSUE THREAD

**Issue by joshcbrown** [haskell/haskell-language-server#3690]
## Your environment 

Which OS do you use?
EndeavourOS, behaviour also present on macOS

Which version of GHC do you use and how did you install it?
9.4.2, tested with 9.0.2 and the same behaviour is present. Both installed with ghcup

How is your project built (alternative: link to the project)?
Using cabal as the build tool.

Which LSP client (editor/plugin) do you use?
nvim+haskell-tools

Which version of HLS do you use and how did you install it?
2.0.0.1 from ghcup

Have you configured HLS in any way (especially: a `hie.yaml` file)?
I found [this](https://github.com/haskell/haskell-language-server/issues/2932) issue from a while ago that had the same error and tried configuring hie.yaml in the suggested way, but ran into another error.

## What's wrong?
When I create a new cabal project (i.e., `mkdir test; cd test; cabal init`), and edit in any file other than app/Main.hs, I get the following error:
```
cradle: Multi Cradle: No prefixes matched
pwd: /home/josh/coding/haskell/test
filepath: /home/josh/coding/haskell/test/app/Test.hs
prefixes:
("app/Main.hs",Cabal {component = Just "test:exe:test"})
```
As I said, I tried configuring hie.yaml to include
```yaml
cradle:
  cabal:
```
After which, I get
```
cradle: Failed to run ["cabal","v2-repl","/home/josh/coding/haskell/test/app/Test.hs"] in directory "/home/josh/coding/haskell/test". Consult the logs for full command and error.
Failed command: cabal --builddir=/home/josh/.cache/hie-bios/dist-test-3c68864534c42b201fc3a1238f7ec82a v2-repl --with-compiler /home/josh/.cache/hie-bios/wrapper-b54f81dea4c0e6d1626911c526bc4e36 --with-hc-pkg /home/josh/.cache/hie-bios/ghc-pkg-62f4c27b4e25dca48155dbaa1378731d /home/josh/coding/haskell/test/app/Test.hs

cabal: Unknown target '/home/josh/coding/haskell/test/app/Test.hs'.
The package test has no file target 'app/Test.hs'.




Process Environment:
HIE_BIOS_GHC: /home/josh/.ghcup/ghc/9.0.2/lib/ghc-9.0.2/bin/ghc
HIE_BIOS_GHC_ARGS: -B/home/josh/.ghcup/ghc/9.0.2/lib/ghc-9.0.2
```
I did also try `cabal build`, because a similar error using stack as the build tool went away when I built the project, but no luck.

### Debug information
The only relevant log I can find is:
```
2023-06-22T01:10:16.511114Z | Warning | No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for app/Divide.hs.
Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie).
You should ignore this message, unless you see a 'Multi Cradle: No prefixes matched' error.
```
Not sure what to do with it, though. Any help would be greatly appreciated!

**Comment by fendor** [comment]
Hi, thank you for your bug report!

What's your cabal version?

**Comment by joshcbrown** [comment]
Hey there, 3.6.2.0. Also installed from ghcup.

**Comment by joshcbrown** [comment]
Both Test.hs and Main.hs are on disk. I've put my code [here](https://github.com/joshcbrown/cabal-test). `cabal build` also succeeds.

**Comment by fendor** [comment]
`Test.hs` is not part of the cabal project, so the error message is legit, it is not part of the executable or anything.

`Test.hs` basically doesn't exist from cabal's perspective; thus, HLS can't load that file.

See https://cabal.readthedocs.io/en/stable/getting-started.html for how to get started with cabal! 
If this is about how you are supposed to add new files, ignore the error message until you have modified the .cabal file. HLS should automatically reload after some time once you have edited your .cabal file.

**Comment by joshcbrown** [comment]
Hmm, yeah sorry noob question. I took `hs-source-dirs: app` to mean that cabal would scan any files in the  `app` folder and add them to the project. How exactly should I add the file, then? I did read that documentation again; maybe I'm missing something entirely obvious, but don't see that anywhere.

**Comment by fendor** [comment]
Yeah, the docs are lacking in general T_T

`hs-source-dirs` only means that the modules you list are searched for in these source directories.

So, what you have to do depends on what you actually want to do. What is Test.hs supposed to be?

Let's assume you want to import Test.hs from Main.hs. That means, `Main.hs` is the main entry point of your project and it contains `main :: IO ()`. To do that, you have to add `Test.hs` as an `other-module` to the executable component. This way, it is a private module of the executable you named `test`. 

Your cabal file, would look like this:

```
cabal-version:      2.4
name:               test
version:            0.1.0.0
extra-source-files: CHANGELOG.md

executable test
    main-is:          Main.hs

    -- Modules included in this executable, other than Main.
    other-modules:    Test
    build-depends:    base ^>=4.15.1.0
    hs-source-dirs:   app
    default-language: Haskell2010
```

If you want to have another executable, e.g. something you can actually run, you need to create a new executable *stanza*. It is almost identical to your `executable test` component. The result, would look like this:
```
cabal-version:      2.4
name:               test
version:            0.1.0.0
extra-source-files: CHANGELOG.md

executable test
    main-is:          Main.hs

    -- Modules included in this executable, other than Main.
    -- other-modules: 
    build-depends:    base ^>=4.15.1.0
    hs-source-dirs:   app
    default-language: Haskell2010
    
 executable test2
    main-is:          Test.hs

    -- Modules included in this executable, other than Main.
    -- other-modules: 
    build-depends:    base ^>=4.15.1.0
    hs-source-dirs:   app
    default-language: Haskell2010
```

Note, the `app/` folder can be overlapping, e.g. `test` and `test2` use the directory for their modules.

**Comment by joshcbrown** [comment]
Ah, thanks so much for the help, and sorry for putting this in the wrong place! Will close it now.
