### ISSUE TITLE
Remove `hls-stan-plugin`

### ISSUE THREAD

**Issue by michaelpj** [haskell/haskell-language-server#3701]
It doesn't work on any recent GHC, and is blocked by `stan` itself being updated, but `stan` is pretty dead. I think we should remove it.

cc @uhbif19

**Comment by uhbif19** [comment]
@michaelpj 

Yes, I can see your reasoning.

Seems like there is a branch working with new GHC. https://github.com/kowainik/stan/issues/423#issuecomment-1264384538

I can ask if it gonna be merged and if not create fork. Will it work for you (if Stan gonna work with new GHCs?)?

**Comment by michaelpj** [comment]
Sure: if we can get the plugin working again then there's no reason to drop it. It's only if it looks like it's dead that we might as well drop it. And `stan` does look fairly dead.

**Comment by michaelpj** [comment]
Done
