### ISSUE TITLE
Remove `hls-tactics-plugin`

### ISSUE THREAD

**Issue by michaelpj** [haskell/haskell-language-server#3703]
While it remains very popular and desired, we don't have a viable maintenance path now @isovector isn't maintaining it and it doesn't work on the last three major GHC versions. @santiweight has made some attempts, but I'm not sure whether they're going to succeed.

At this point I think we should maybe just declare it dead.

**Comment by bolt12** [comment]
Personally I don't use all its features, I find the most useful ones to be just pattern matching and friends. Perhaps a good middle ground would be to strip it down to only the most used features? Hopefully that's easier to maintain

**Comment by michaelpj** [comment]
Maybe! And I believe there is some prior work in that direction. But someone has to take it on.

**Comment by isovector** [comment]
It's the pattern matching that is the maintenance burden, unfortunately. Everything else is more-or-less self-contained pure code. But spitting out the actual characters to change the document is excruciatingly hard.

**Comment by santiweight** [comment]
I am no longer able to push forward on this effort :(

I think that developer tooling is one of the biggest potential wins for Haskell, but unfortunately as Sandy says, the pretty printing infrastructure is fairly poor (very powerful, but extremely hard to use).

I think this is a good place for the Haskell Foundation to get involved.

**Comment by michaelpj** [comment]
Done :crying_cat_face:

**Comment by alanz** [comment]
@santiweight can we have a discussion about the pretty printing infrastructure some time?

**Comment by santiweight** [comment]
> @santiweight can we have a discussion about the pretty printing infrastructure some time?

Would love to! Can you send me an email (we’ve exchanged before)?

**Comment by isovector** [comment]
@alanz @santiweight I'd love to be involved in that!

**Comment by alanz** [comment]
@isovector As I understand it the plan moving forward is to wait for my "simplify exact print in GHC" [branch](https://gitlab.haskell.org/ghc/ghc/-/commits/wip%2Faz%2Flocateda-epa-improve-2023-07-15) to land, and then see how we can clean up and improve the user-facing API.

I anticipate this taking around a month
