### ISSUE TITLE
Multi Cradle: No prefixes matched when editing Setup.hs

### ISSUE THREAD

**Issue by k355l3r-5yndr0m3** [haskell/haskell-language-server#3710]
### Your environment
Arch Linux
Cabal
Neovim (lsp-config)

### Steps to reproduce

1. Create new project 
2. Change build-type to Custom
```
build-type:         Custom
custom-setup
  setup-depends:
    base,
    Cabal
```
3. Create a Setup.hs file and build
4. Open Setup.hs 
### Expected behaviour

hls works seamlessly on Setup.hs

### Actual behaviour
hls output this error
```
Multi Cradle: No prefixes matched
pwd: /home/cha0s/testing
filepath: /home/cha0s/testing/Setup.hs
prefixes:
("app/Main.hs",Cabal {component = Just "testing:exe:testing"})
```
### Debug information
I found this [reddit](https://www.reddit.com/r/haskell/comments/wcny2p/hls_issues_in_stack_project/) post describing something similar but Stack is used instead. 
The custom build script Setup.hs is the only file affected, the other seems to work fine.

**Comment by fendor** [comment]
Hi!

Unfortunately, this is simply not supported at this time. Here is an issue for the underlying hie-bios issue: https://github.com/haskell/hie-bios/issues/208

**Comment by k355l3r-5yndr0m3** [comment]
That's a bit disappointing, but I've managed to figure out a temporary solution. Adding an hie.yaml file with the following content.
```
cradle:
  cabal:
```
will change the error into something like this.
```
   Error: cabal: Failed extracting script block: `{- cabal:` start marker not
   found
```
Inserting the following lines at the top of the Setup.hs file will fix it and allow hls to function.
```
{- cabal: 
build-depends: base,
               Cabal
-}
```
If Setup.hs depends on other packages, you would need to add it both to the .cabal file and Setup.hs/

**Comment by fendor** [comment]
I did not know this was possible. Thank you very much for this workaround :)

**Comment by fendor** [comment]
Closing in favour of #3735 which also documents this workaround
