### ISSUE TITLE
Unexpected usage error - user specified .o/.so/.DLL could not be loaded 

### ISSUE THREAD

**Issue by alaendle** [haskell/haskell-language-server#3722]
### Environment

Debian bullseye with latest patches; GHC 9.4.5; stack 2.11.1; hls 2.0.0.1 - all via ghcup 0.1.19.4; vscode  1.80.1

### Steps to reproduce

Clone the reproduction repo: https://github.com/alaendle/hls-th-static-lib
Open src/Lib.hs

### Expected behaviour

HLS is able to process the source file.

### Actual behaviour

HLS shows the following error:
```
Unexpected usage error
user specified .o/.so/.DLL could not be loaded (libparson.so: cannot open shared object file: No such file or directory)
Whilst trying to load:  (dynamic) parson
Additional directories searched: (none)
```

![grafik](https://github.com/haskell/haskell-language-server/assets/969523/f596b924-22a0-4026-bde6-0617b4369feb)

### Debug information

For now I keep short; since I guess the reproducer in the mentioned repository is able to give answer to any details. But don't hesitate to contact me if I could provide further information.

Maybe the following issues are related:
https://github.com/haskell/haskell-language-server/issues/3063
https://github.com/haskell/haskell-language-server/issues/3104

(fyi @F-Joachim)

**Comment by michaelpj** [comment]
Unclear what's going on here, some kind of library path or pkgconfig issue? Maybe @wz1000 has an idea?

Does `cabal build` work?

**Comment by alaendle** [comment]
@michaelpj - Sorry for the late response; and many thanks for your hint - `cabal repl` reports a similar error - so I will try to fix this and post an update...

**Comment by michaelpj** [comment]
Okay, I'm going to close this for now. If `cabal repl` works and you still can't get HLS to work, then open another issue.
