### ISSUE TITLE
new release: for `hls` 

### ISSUE THREAD

**Issue by swarnimarun** [haskell/haskell-language-server#3726]
#### Which OS do you use?
Windows, Mac, Linux

#### Which version of GHC do you use and how did you install it?
9.2.7

#### How is your project built (alternative: link to the project)?
cabal/stack

#### Which LSP client (editor/plugin) do you use?
helix, and a few others

#### Which version of HLS do you use and how did you install it?
2.0.0.1 ghcup -- `haskell-language-server version: 2.0.0.1`

#### Have you configured HLS in any way (especially: a `hie.yaml` file)?
nope

## What's wrong?

There was a fix for correct document versions for lsp code actions, that specific PR(#3643) was merged back on June 11th. And I have tried building it from source which works on my mac laptop but building the project from source on Windows is tedious and since there are now over 50 commits since last release(also it's been over a month) I think a new release would be nice for everyone in community. 
Also lsps that respect versioning are all broken on hls atm, not just helix.

Would also "not" require me to build the project on every platform and every machine I work on, also I can start using ghcup again. Also, though if there is an issue with making a new release atm feel free to take the time.

Thanks for the awesome work on hls, cheers. :)

**Comment by hasufell** [comment]
> but building the project from source on Windows is tedious

Why exactly?

**Comment by hasufell** [comment]
> Would also "not" require me to build the project on every platform and every machine I work on, also I can start using ghcup again.

Sounds like you're not aware of `ghcup compile hls`?

**Comment by swarnimarun** [comment]
I do know about it but I have never gotten it to work for me,

![image](https://github.com/haskell/haskell-language-server/assets/19930870/8ce658ae-c2e0-4403-bbd5-b84895cace08)

That job had to be cancelled(Ctrl+C) not sure what I am doing wrong either, also building directly in msys2 env can end up halting as well, I figured out how to fix it after a bunch of work.

#### machine specs:
Intel i7 12700K
32GB RAM
Windows 11 64-bit

For perspective hls builds in an amount of time it takes for me to read a couple articles... Not very scientific but I haven't had to ever measure that.

Also for libs with C dependencies then I have to ensure that built binary runs correctly and all dynamic dependencies are correctly found outside of msys2 if it had any as well, thankfully that's not an issue here.

Tbh building any haskell project on windows without wsl2 has been quite confusing and tedious for me. I maybe just doing things wrong, also I don't like using wsl2 because it can be buggy when writing code against any platform libraries like win32 api, which I used for writing my tiny render engine also using glfw c api in ffi.

**Comment by michaelpj** [comment]
We're going to do a release this week.

**Comment by swarnimarun** [comment]
Thanks. :)
