### ISSUE TITLE
Popup explaning when hls is degraded

### ISSUE THREAD

**Issue by joyfulmantis** [haskell/haskell-language-server#3728]
Currently, most functionality in HLS depends on parsing, and if there is a parse failure then a lot of functionality gets degraded. It would be good, especially for new users, to have a popup upon parse failure, that explains that there is a parse error, and some functionality will be unavailable till that is corrected.

**Comment by michaelpj** [comment]
I'm not sure about this:
- Popups are very aggressive
- We work with the file that the user is typing in. The _normal state_ of that file is being somewhat broken, often including not parsing
- All the stuff we have about stale results is so we _can_ give reasonable responses even if the file is broken!

So I'm not sure it's true that HLS is very degraded when the file doesn't parse, even!

**Comment by joyfulmantis** [comment]
Good points. I guess we could detect if the useWithStale parser rule failed, and then show a message then. That would avoid most of the problems you mentioned, but of course also not have as much of an impact. If the useWithStale parser rule fails I don't think we can do anything.

Another option is to implement something like rust-analyser's health feature on vscode, so something a bit more out of the way, and when clicked upon can show the status of the rules.

**Comment by michaelpj** [comment]
> I guess we could detect if the useWithStale parser rule failed, and then show a message then.

The thing is, I _think_ this will only happen if the file has _never_ parsed. And that's not such a common case. It's also worth noting that if the file doesn't parse/typecheck the user does get some information about that... in the form of the error diagnostics!

Do you have situations in mind where you would have liked to see this?

> Another option is to implement something like rust-analyser's health feature on vscode, so something a bit more out of the way, and when clicked upon can show the status of the rules.

That would be cool, but thus far we've stayed away from adding LSP extensions because that means we need to write the client support ourselves...

**Comment by joyfulmantis** [comment]
> Do you have situations in mind where you would have liked to see this?

Yes, here for example is a recent issuer where the user was confused with the current situation: https://github.com/haskell/haskell-language-server/issues/3697

**Comment by michaelpj** [comment]
Shouldn't that person have got a bunch of error diagnostics too? I think their confusion was maybe more about the fact that "InternalError" sounds very scary, which is I guess related to our recent discussion about plugin errors. Now I think a session like that should have a much less scary-looking log.
