### ISSUE TITLE
`textDocument/references` on a record field in a definition returns way too many things 

### ISSUE THREAD

**Issue by googleson78** [haskell/haskell-language-server#3731]
## Is your enhancement request related to a problem? Please describe.

Currently, calling `textDocument/references` on the field of a record in a definition returns way too many things, including all of the other record fields, as well as the data type definition line, as well as some seemingly duplicate entries. Example:

For this file
```haskell
{-# LANGUAGE RecordWildCards #-}
data Foo = MkFoo
  {
    bar :: Int,
    baz :: String
  }

fooUse0 :: Foo -> Int
fooUse0 MkFoo{bar} = 5

fooUse1 :: Foo -> Int
fooUse1 MkFoo{..} = 6

fooUse2 :: Int -> String -> Foo
fooUse2 bar baz =
  MkFoo{..}
```

Calling `textDocument/references` while my cursor is on `bar` on line 4 returns the following results:
![2023-07-26-165942_636x284_scrot](https://github.com/haskell/haskell-language-server/assets/8667384/6c428a3f-9c31-45e4-8d48-52336bbee576)
A lot of these seem redundant:
1. The constructor definition (the last result)
2. Some of the lines are seemingly duplicated - `fooUse1` and `fooUse2` are both seemingly mentioned twice, which seems like a bug?
3. (my biggest issue) `baz :: String` also comes up as a result, which also seems like a bug, and is a huge pain when dealing with Real World :tm: data types with loads of fields, as this happens for each field.

## Describe the solution you'd like

I would like for only lines that mention the field in question to show up.

## Describe alternatives you've considered

Maybe I'm just confused regarding what "references" means?

**Comment by michaelpj** [comment]
Seems like a definite bug. @wz1000 could this be a hiedb issue? is there a query @googleson78 can run to check if the db is wrong?

**Comment by wz1000** [comment]
I think this is https://gitlab.haskell.org/ghc/ghc/-/issues/23492 which will be fixed in future releases of GHC starting with 9.4.6

**Comment by michaelpj** [comment]
Closing as it's fixed upstream

**Comment by googleson78** [comment]
Note that this is still note fixed, I've "reopened" this issue in https://github.com/haskell/haskell-language-server/issues/4412
