### ISSUE TITLE
No prefixes matched

### ISSUE THREAD

**Issue by noughtmare** [haskell/haskell-language-server#3734]
### Your environment

> Which OS do you use?

NixOS

> Which version of GHC do you use and how did you install it?

9.4.5 from nixpkgs

> How is your project built (alternative: link to the project)?

with cabal, see https://github.com/noughtmare/gigaparsec

> Which LSP client (editor/plugin) do you use?

VS Codium+vscode-haskell

> Which version of HLS do you use and how did you install it?

haskell-language-server version: 1.10.0.0 (GHC: 9.4.5) (PATH: /nix/store/g3mjflh04dizbfgzq0rp6k61sjq6ggp4-haskell-language-server-1.10.0.0/bin/haskell-language-server-wrapper)
From nixpkgs

> Have you configured HLS in any way (especially: a `hie.yaml` file)?

No

### Steps to reproduce

optionally: `nix-shell -p haskell.compiler.ghc945 haskell.packages.ghc945.haskell-language-server`

```
git clone https://github.com/noughtmare/gigaparsec.git
cd gigaparsec
git checkout 9b41b8b1c1e945599b72bad9166eca401f9c71d0
codium . -n -g experiments/Experiment2.hs
```

Unfortunately, I wasn't able to reproduce this on an even smaller project.

### Expected behaviour

No prefix matching errors.

### Actual behaviour

```
Multi Cradle: No prefixes matched
pwd: /home/user/haskell/gigaparsec
filepath: /home/user/haskell/gigaparsec/experiments/Experiment2.hs
prefixes:
("src",Cabal {component = Just "lib:gigaparsec"})
("examples/Main.hs",Cabal {component = Just "gigaparsec:exe:gpc-examples"})
("tests",Cabal {component = Just "gigaparsec:test:gpc-test"})
("experiments/Experiment1.hs",Cabal {component = Just "gigaparsec:exe:gpc-experiment1"})
("./Experiment2.hs",Cabal {component = Just "gigaparsec:exe:gpc-experiment2"})
```

Especially that last line seems wrong.

### Notes

I found out that it works fine if I swap the order of the `main-is` and `hs-source-dirs` fields of the `gpc-experiment2` component.

**Comment by fendor** [comment]
Have you tried an explicit `hie.yaml` with the contents:
```yaml
cradle:
  cabal:
```

that should work in all cabal cases.

**Comment by noughtmare** [comment]
Yes, that seems to fix the problem as well.

**Comment by noughtmare** [comment]
I do get 2 duplicate errors/warnings/actions for everything now.

**Comment by fendor** [comment]
Closing in favour of #3695

**Comment by noughtmare** [comment]
@fendor I don't think that issue subsumes this. The module should be known, because it is listed in the cabal file. The problem seems to be that implicit-hie picks up the wrong location for `Experiment2.hs`. It should be `experiments/Experiment2.hs`, not `./Experiment2.hs`.

**Comment by fendor** [comment]
Upstream issue: https://github.com/Avi-D-coder/implicit-hie/issues/1

We aim to migrate away from implicit-hie, or at least generate smarter cradles in the future.
