### ISSUE TITLE
`stackYaml` support in `hie.yaml`

### ISSUE THREAD

**Issue by konn** [haskell/haskell-language-server#375]
### Subject of the issue
It seems that precompiled binary (at least for GHC 8.6.5) doesn't accept `stackYaml` configuration item supported by hie-bios >= 0.7, as described in the [hie-bios repo](https://github.com/mpickering/hie-bios/blob/master/README.md#stack).

### Your environment
* Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`
  ```
  haskell-language-server version: 0.4.0.0 (GHC: 8.6.5) (PATH: ~/Library/Application Support/Code/User/globalStorage/haskell.haskell/haskell-language-server-0.4.0-darwin-8.6.5) (GIT hash: 0a18edde24923251a148cbbc0ae993a6aac83b9c)
   Tool versions found on the $PATH
   cabal:          3.2.0.0
   stack:          2.3.3
   ghc:            8.6.5
   ```
* Which lsp-client do you use: VSCode
* Describe your project (alternative: link to the project)
  * Include `stack.yaml` and `stack-prof.yaml`
* Contents of `hie.yaml`:

  ```
  cradle:
    stack:
      stackYaml: stack-prof.yaml
      components:
        - path: "src"
          component: "hie-fail-test:lib"
        - path: "app/Main.hs"
          component: "hie-fail-test:exe:hie-fail-test-exe"
        - path: "test"
          component: "hie-fail-test:test:hie-fail-test-test"
  ```

### Steps to reproduce
1. `stack new hie-fail-test`
2. Create a copy `stacl-prof.yaml` which has an identical contents as `stack.yaml`
3. Create a `hie.yaml` with the above contents
4. Open, e.g. `src/Lib.hs` in VSCode
5. VSCode complains that:

   ```
   Couldn't figure out what GHC version the project is using:
   ~/Library/Application Support/Code/User/globalStorage/haskell.haskell/haskell-language-server-wrapper-0.4.0-darwin --project-ghc-version exited with exit code 1:

   Found "/path/to/hie-fail-test/hie.yaml" for "/path/to/hie-fail-test/a"
   haskell-language-server-wrapper-0.4.0-darwin: AesonException "Error in $.cradle: Not a valid Configuration type, following keys are allowed: component"
   ```

6. or just invoking `haskell-language-server-wrapper-0.4.0-darwin`, downloaded automatically from GitHub by VSCode, on `src/Lib.hs` halts with the following error:

   ```
   Found "/Users/hiromi/Documents/Programming/Haskell/git/hie-fail-test/hie.yaml" for "/path/to/hie-fail-test/a"
   haskell-language-server-wrapper-0.4.0-darwin: AesonException "Error in $.cradle: Not a valid Configuration type, following keys are allowed: component"
   ```

### Expected behaviour
`hls` should work properly using the flags/settings in `stack-prof.yaml`.

### Actual behaviour
Doesn't accept `stackYaml` option at a..

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

<details>
<summary>
Debug output:
</summary>

```
Found "/path/to/hie-fail-test/hie.yaml" for "/path/to/hie-fail-test/a"
haskell-language-server-wrapper-0.4.0-darwin: AesonException "Error in $.cradle: Not a valid Configuration type, following keys are allowed: component"
```
</details>

Paste the logs from the lsp-client, e.g. for [VS Code](https://github.com/haskell/vscode-haskell#troubleshooting)

<details>
<summary>
LSP logs:
</summary>

```
NO LOGS
```
</details>

**Comment by Ailrun** [comment]
We are using hie-bios 0.6.1 so the option is not supported yet. Thank you for the report!

**Comment by jneira** [comment]
First step is to change ghcide to use the appropiate hie-version: https://github.com/haskell/ghcide/pull/763

**Comment by jneira** [comment]
ghcide master already uses the required hie-bios version, now we need to reabase those changes to the branch used by hls (and bump submodule): i guess there will be a hls-3.5, like https://github.com/haskell/ghcide/tree/hls-3.3

**Comment by konn** [comment]
It seems that `stackYaml` configuration is already supported in HLS 0.5.0.0, right?

**Comment by jneira** [comment]
Yeah, thanks to point it out, have you got the chance to test it?

**Comment by konn** [comment]
I've just tested with our project, and it seems working properly for now. Thanks!
