### ISSUE TITLE
is the ghc-lib dependency really a ghc-lib-parser dependency?

### ISSUE THREAD

**Issue by shayne-fletcher** [haskell/haskell-language-server#3752]
i see dependencies (of ghcide, hie-compat at least) on ghc-lib. i wonder if in fact they are completely satisfied by ghc-lib-parser? (i ask because i am considering there may not be sufficient users of ghc-lib to justify more releases).

**Comment by michaelpj** [comment]
I don't see any direct dependencies on `ghc-lib` from us? I'm not sure there are any indirect ones either.

**Comment by shayne-fletcher** [comment]
was reading from https://hackage.haskell.org/package/ghc-lib-9.6.2.20230523/. could be wrong?

**Comment by michaelpj** [comment]
I'm guessing that looks at all versions. Seems like HLS stopped depending on `ghc-lib` in [2021](https://github.com/haskell/haskell-language-server/pull/1366).
