### ISSUE TITLE
HLS doesn't detect git dependencies in cabal.project

### ISSUE THREAD

**Issue by nlander** [haskell/haskell-language-server#3755]
### Your environment

Which OS do you use?
Pop!_OS
Which version of GHC do you use and how did you install it?
9.6.2 from ghcup
How is your project built (alternative: link to the project)?
the project is hls, specifically my branch: https://github.com/haskell/haskell-language-server/pull/3749

Which LSP client (editor/plugin) do you use?
I have seen this in both VSCode and Neovim
Which version of HLS do you use and how did you install it?
In Neovim, 2.0.0.1. In VSCode, it's ghcide built from my branch.
Have you configured HLS in any way (especially: a `hie.yaml` file)?

### Steps to reproduce

Open `ghcide/src/Development/IDE/Core/Dependency.hs` (a new file in my branch)

### Expected behaviour

This should typecheck, because it compiles with cabal just fine.

### Actual behaviour

Typecheck fails because of the function `lookupPackage`, which is found in my fork of hiedb, referenced in the cabal.project, but is not found in the latest version of hiedb found on hackage.

### Debug information

Finished: codeLens.TypeCheck Took: 0.00s
ghcide-type-lenses: Rule Failed: TypeCheck
[Error - 6:57:06 AM] Request textDocument/codeLens failed.
  Message: ghcide-type-lenses: Rule Failed: TypeCheck
  Code: -32803

**Comment by fendor** [comment]
We discussed this in matrix, looks like a cabal bug to me, where clearing the appropriate caches solves the issue.

@nlander correct me if I am wrong.

**Comment by michaelpj** [comment]
Tenatively closing as solved
