### ISSUE TITLE
Completion does not show up on number or dash

### ISSUE THREAD

**Issue by VeryMilkyJoe** [haskell/haskell-language-server#3760]
While writing a value, completion suggestions are continuously displayed until the dash/number occurs as can be seen below. 
This should not be the case.

![ezgif com-video-to-gif(1)](https://github.com/haskell/haskell-language-server/assets/22590431/fc6f0164-86b5-4172-abc4-77228959f5e3)

**Comment by VeryMilkyJoe** [comment]
This seems to be linked to a global lsp config, where [completion trigger characters are defined](https://hackage.haskell.org/package/lsp-types-2.0.1.1/docs/Language-LSP-Protocol-Types.html#t:CompletionOptions) (updated documentation can be read in the [lsp-specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionOptions)). 

Additional, trigger characters may be defined [here](https://hackage.haskell.org/package/lsp-2.1.0.0/docs/Language-LSP-Server.html#t:Options) but all of these options would affect how hls behaves when working with haskell files, so changing this is probably not wise.

**Comment by July541** [comment]
Can we close this as not planned?

**Comment by VeryMilkyJoe** [comment]
Yupp, I think that makes sense!
