### ISSUE TITLE
Kate editor: HLS / implicit cradle doesn't pick up .cabal file? 

### ISSUE THREAD

**Issue by prez** [haskell/haskell-language-server#3777]
## Your environment 

**Editor**: KDE Kate (with LSP plugin)
**HLS**: 2.1.0.0
**Cabal**: 3.10.1.0

## What's wrong?

I tried Kate and VS Code - in both of them, the LSP does not pick up the language extensions / build-depends if you open the file the normal way.

Is this expected? Somehow depressing and hard to believe if so... Other language server implementations do not have this issue. Is there a tracking issue to fix this?

When opening the entire folder with VS Code, things work as expected (HLS is picking up the dependencies and language extensions).

However, I can't seem to find a way to set the "current working directory" for Kate's LSP client.
I hope other HLS + Kate users can chime in. Thank you.

**Comment by fendor** [comment]
Hi, thank you for your bug report!

Regarding your VSCode issue, please follow https://github.com/haskell/vscode-haskell#investigating-and-reporting-problems and provide some logs.

I have no experience regarding Kate, though. However, if it follows LSP, it seems likely to me your problems have a common cause.

> Is this expected? 

No it is not, we use HLS on huge multi package projects, like HLS itself and we do get accurate diagnostics, code actions, code lenses, etc...

**Comment by fendor** [comment]
> To be clear, I have no interest in using VS Code

Well, in that case, provide the logs of Kate, please.

> Here are the lines which I think are relevant from HLS's debug log in both editors:

That's helpful already but incomplete. 
However, it tells you immediately that Kate opened the wrong folder as the root of the project.
Please, provide some project information, what's your project structure? Did you make sure you opened the root of your project in your editor?

The provided link has a solution, have you tried it? If yes and it didn't work, then it likely is not related.

**Comment by fendor** [comment]
I installed the Kate LSP client and tried it myself, and it worked out of the box after I made sure I opened the correct folder [CTRL + T, O]. However, opening many folders, aka multiple workspaces caused some issues. I am not sure though, whether that's a Kate issue or HLS issue.

**Comment by fendor** [comment]
We cannot fix anything until we know what is going wrong and why. 

Can you perhaps record a screen session of what you are doing? Together with showing the Logs from the output panel, perhaps that can give us an idea.

**Comment by georgefst** [comment]
While I'm not very familiar with Kate, note that one might not necessarily want to consider `*.cabal` to indicate a project root. Many projects (such as HLS itself!) have only a `cabal.project` file at the root, which points to multiple directories with `*.cabal` files. On the other hand, `cabal.project` isn't mandatory, so sometimes `*.cabal` might be the only indication of the project root.

Anyway, it would be useful to [upstream](https://invent.kde.org/utilities/kate/-/blob/master/addons/lspclient/settings.json?ref_type=heads) this fix to benefit other users.
