### ISSUE TITLE
HLS fails on complex project

### ISSUE THREAD

**Issue by k355l3r-5yndr0m3** [haskell/haskell-language-server#3780]
I have a project that I am working on that is quite complex. The build-type is custom, and Setup.hs uses the autoconfUserhooks so it also generate a .buildinfo file. 
The configure build-type could not be used because I uses Setup.hs to generate the project's autogen modules. 
There are two issues. The auto generated modules are not created and must be manually copied from dist-newstyle to the corresponding directory in hie-bios, and the buildinfo file appears to be ignored. 
The project builds fine, but hls cannot be used.

**Comment by fendor** [comment]
Hi, thank you for your bug report!

Does `cabal repl` succeed in your project?

Can you reduce your project to a minimal reproducer and post it so we can take a look at it?

**Comment by k355l3r-5yndr0m3** [comment]
[minimal.zip](https://github.com/haskell/haskell-language-server/files/12458624/minimal.zip)
The configure script generate a buildinfo file with the buildable flag set to false, yet hls is not aware of this. Adding `buildable: False` to the .cabal file produces the correct behavior. This apply to other flags too. 
The Setup script create a module called Autogen, which hls cannot locate.

**Comment by fendor** [comment]
I am not sure if we can help with the `configure` script, I don't know enough about Cabal to know what's going on here.

What behaviour would you expect?

Re the `Setup.hs`, iirc, `preBuildHook` is only run if you execute `cabal build`. However, HLS calls `cabal repl` to find the compilation options. If you manage to generate the module also on `cabal repl`, perhaps via the `preReplHook`, that could work.

**Comment by k355l3r-5yndr0m3** [comment]
Generating the modules at preRepl does solve the autogenerated module issue. 
As for the configure script issue, I use it to resolve the include paths and library paths. My project deals with a lot of C code. I've been adding the paths specific to my system to the cabal file as a workaround. 
`cabal build` run without error, but `cabal repl` fails because it could not find the header files.

**Comment by michaelpj** [comment]
As Fendor says, we rely on `cabal repl` to find the build flags. If `cabal repl` doesn't work, HLS won't work. I'm not sure how to make `cabal repl` work for your project, but that's more of a cabal issue than a HLS issue.

**Comment by AleXoundOS** [comment]
> `cabal build` run without error, but `cabal repl` fails

I face the same issue with cabal 3.10.1.0:
1. `build-type: Configure`
2. `configure` script generates `PROJ.buildinfo` file with `cpp-options: -DMYDEF=1` contents
3. haskell code uses `CPP` extension to access `MYDEF`
4. `cabal build` successfully builds the project
5. `cabal repl` fails with `Data constructor not in scope` for `MYDEF`

**Comment by michaelpj** [comment]
Closing as mostly-expected
