### ISSUE TITLE
hls consumes extreme amounts of memory on comparatively small application

### ISSUE THREAD

**Issue by MangoIV** [haskell/haskell-language-server#3786]
### Your environment

Which OS do you use?
NixOS 23.11 

Which version of GHC do you use and how did you install it?
9.4.6 nix package manager

How is your project built (alternative: link to the project)?
cabal 

Which LSP client (editor/plugin) do you use?

neovim
Which version of HLS do you use and how did you install it?

2.0.0.1 nix package manger
Have you configured HLS in any way (especially: a `hie.yaml` file)?
no

### Steps to reproduce

- hard to reproduce, occurs after working a while on a file, the repo is also not open source yet, it might be related to the dependency on package `stripeapi` which has a very large amount of symbols.  

### Expected behaviour

consume reasonable amounts of memory (16, hell 20 gb would be fine)

### Actual behaviour

memory runs full then at some point my computer just hangs until I get a GC (I guess that's what happens) and I get normal amounts of memory (the yellow line is SWAP)

![image](https://github.com/haskell/haskell-language-server/assets/40720523/484bea2e-bc77-4df9-8e8b-e26d7df0f05f)

### Debug information

I'm reporting this because I think this is a novel issue, I have never experienced this. It could also be related to the `stripeapi` package having a really high amount of symbols.

**Comment by MangoIV** [comment]
It now happens as soon as I open a file which I have recently added this function to: 
```haskell
verifyStripeSignature'
  :: (ToJSON payload)
  => POSIXTime
  -- ^ the time to diff the payload time with
  -> NominalDiffTime
  -- ^ the maximum tolerated difference between the time to diff the payload time with
  -> StripeSignature
  -- ^ the signature to verify
  -> StripeSigningSecret
  -- ^ the Stripe signing secret
  -> payload
  -- ^ the payloaddto verify the signature against
  -> Either StripeSignatureVerificationError ()
verifyStripeSignature' now diff sig key payload = do
  let signedPayload = encodeUtf8 (sig.originalTimeStamp) <> "." <> toStrict (encode payload)
      hmacDigest :: HMAC SHA256 = hmac key signedPayload
  stripeSignatureDigest :: Digest SHA256 <- maybe (throwError StripeSignatureInvalidDigest) pure $ digestFromByteString _


  pure ()
``` 
(I know it ain't much :/)

**Comment by MangoIV** [comment]
![image](https://github.com/haskell/haskell-language-server/assets/40720523/d93090a6-4d03-4df5-a60a-de209d448b9c)
this is what happens when opening the editor (and closing it afterwards)

**Comment by wz1000** [comment]
Does it also happen without the hole?

**Comment by MangoIV** [comment]
no.

**Comment by wz1000** [comment]
OK could you prepare a small reproducer please? Sounds like a `stripapi` dependency and a function with a hole could be sufficient.

**Comment by MangoIV** [comment]
but this could also just be luck, because now it doesn't happen *with* the hole.

**Comment by MangoIV** [comment]
> OK could you prepare a small reproducer please? Sounds like a stripapi dependency and a function with a hole could be sufficient.

I will try to, but as I said, it's hard to reproduce reliably.

**Comment by michaelpj** [comment]
Tentatively closing pending lack of reproduction
