### ISSUE TITLE
Fourmolu plugin formats code differently compared to separate installation of fourmolu

### ISSUE THREAD

**Issue by ollimandoliini** [haskell/haskell-language-server#3788]
### Your environment

Which OS do you use?
MacOS

Which version of GHC do you use and how did you install it?
9.6.2 from GHCUp

How is your project built (alternative: link to the project)?

Which LSP client (editor/plugin) do you use?
VSCode and vscode-haskell

Which version of HLS do you use and how did you install it?
 2.2.0.0 from GHCUp

Have you configured HLS in any way (especially: a `hie.yaml` file)?
Whether you have `fourmolu.yaml` or not doesn't change the behaviour.

### Steps to reproduce

Have the HLS configured to use the built-in installation of fourmolu and run the formatting command.

```hs
foo :: Maybe Int -> Int
foo = undefined

thing :: Int
thing =
    foo $ Just $
            case undefined of
                True -> 1
                False -> 2
```

### Expected behaviour

The could should be formatted with the following output like a separate installation of `fourmolu-0.13.1.0` does.

```hs
foo :: Maybe Int -> Int
foo = undefined

thing :: Int
thing =
    foo $
        Just $
            case undefined of
                True -> 1
                False -> 2
```

### Actual behaviour

Running VSCode's formatting command while having HLS use the built-in fourmolu will format the code to the following form:
```hs
foo :: Maybe Int -> Int
foo = undefined

thing :: Int
thing =
    foo
        $ Just
        $ case undefined of
            True -> 1
            False -> 2
```

### Debug information

vscode-haskell outputs the following log entry:
```
2023-09-03T12:47:51.063236Z | Debug | fourmolu: Using compiled in fourmolu-0.13.1.0
```

**Comment by michaelpj** [comment]
Sounds like we're somehow using different configuration to what the CLI fourmolu is getting?

**Comment by fendor** [comment]
Yes, I theorised the fixity of `($)` might be known in HLS but not on the cli.

**Comment by michaelpj** [comment]
That sounds likely. It's unfortunate that using the extra information we have in HLS can let us do better formatting, but make https://github.com/haskell/haskell-language-server/issues/411 worse.

**Comment by ollimandoliini** [comment]
That makes sense.

I'm also curious why HLS formats it the way that it does? To me the one formatting that separate fourmolu produces looks nicer and more similar to how what's commonly used in Haskell ecosystem in general.

**Comment by michaelpj** [comment]
I guess that's a question for the fourmolu devs. If our guess is correct, that's just what fourmolu does if it knows the fixity of `$`.

**Comment by brandonchinn178** [comment]
Yes, that's simply the behavior when Fourmolu doesn't know the fixity of an operator. Some follow up questions:
1. What if you tell HLS to use an external fourmolu (i.e. the CLI version)?
2. What's the structure of your project? Do you have a cabal file? Is your module mentioned in it?
3. Are you using `NoImplicitPrelude` or a custom prelude or otherwise hiding Prelude? Have you configured the `reexports` configuration correctly?
4. How are you invoking the fourmolu CLI? How are you specifying the files?

**Comment by ollimandoliini** [comment]
1. The formatting is the same as when using the CLI directly.
2. I created the project using `cabal init` with cabal version `3.10.1.0`. It only has `app/Main.hs` module and it's mentioned in the cabal file.
3. No and no.
4. By calling `fourmolu --mode inplace .` from the project root.

**Comment by brandonchinn178** [comment]
hm I don't use HLS, so I'm not sure how much help I'd be here.

@ollimandoliini it seems like you have a pretty basic set up. Does it work if you're in a completely separate directory (e.g. `/tmp/my-project/`) with just a single Haskell file without a Cabal file in any parent directories? If it does work, can you provide a full minimal repro?

@georgefst do you have any idea?

**Comment by Vlix** [comment]
I can confirm that I had the same.
I've worked around it by adding most fixities in the `fourmolu.yaml`, which seems to have made it behave again (and work the same as running the executable separately.

**Comment by georgefst** [comment]
> Yes, I theorised the fixity of `($)` might be known in HLS but not on the cli.

Fortunately it's the opposite, which is easier to fix!

I do also intend, in a separate PR, to modify the external Fourmolu mode to (at least have the option to) avoid passing `--no-cabal` in order to more straightforwardly replicate using the formatter outside HLS.
