### ISSUE TITLE
Converge on implicit cradle discovery mechanism

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-language-server#38]
Related to #1 

What is the current consensus to use?
Competing approaches:
* ghcide uses `loadImplicitCradle` from hie-bios
* hie uses a custom implicit cradle discovery mechanism powered by cabal-helper

In hls, we didnt take sides, yet, and just use both (which is not a solution), but we need to decide on one of them or some hybrid approach.

Was there some consensus what to use in bristol?

cc @ndmitchell, @cocreature, @alanz, @bubba

**Comment by cocreature** [comment]
I think the consensus in Bristol was to first figure out where exactly `loadImplicitCradle` is insufficient (@bubba started to look into this). The main issue there is probably multi-cradles.

Personally, I think `loadImplicitCradle` should do the right thing in the long-term which probably means moving some of the logic for that into build tools (Chris Done implemented a patch for that in Stack at the hackathon).
Until we can rely on that, `cabal-helper` might be a sensible choice. I don’t have strong feelings on whether that should be achievedby `hie-bios` depending on it or in `ghcide` itself.

**Comment by alanz** [comment]
I agree with @cocreature that where precisely this functionality lives is not important, but I do think that cabal-helper is probably the best shot we have at it, and we should use it, for the forseeable future.

**Comment by jneira** [comment]
Imo we could wait to cabal and stack to improve the implicit discovery in hie-bios itself (so not use cabal-helper in it).
If we want to dont link ghcide to cabal-helper (it eventually will get the implicit cradle with the previous change) the unique way i can think of is make ghcide accept external cradles (if it doesnt do it yet) and get the c-h implicit cradle in hls. In fact `hls` already has the code doing that so that part is already done.
It would suppose that we will not need a new library neither.

**Comment by jneira** [comment]
I've implement the change here naively, it does not work, of course, and i am afraid that not only for lack of multicradle support: https://github.com/haskell/haskell-language-server/compare/master...jneira:cabal-helper

**Comment by jneira** [comment]
* Update: the actual plan is make the lib `implicit-hie` work for most cases, using [cabal-helper](https://github.com/Avi-D-coder/implicit-hie/pull/11)  or [cabal-install-parsers](https://github.com/Avi-D-coder/implicit-hie/pull/13) and use that lib in hls: https://github.com/haskell/haskell-language-server/pull/138

**Comment by jneira** [comment]
For reference: there are some comments related with this #386 
We are pushing the implicit-hie use for the implicit cradle: https://github.com/haskell/ghcide/pull/782 without waiting to make it work for common stanzas and conditionals

**Comment by jneira** [comment]
We already are using `implicit-hie-cradle` to handle implicit hie-bios config, indirectly with the ghcide bump from #391
