### ISSUE TITLE
Duplicate add extension suggestion

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#380]
HLS gives me two quick fixes to add the same LANGUAGE extension:

<img width="564" alt="image" src="https://user-images.githubusercontent.com/26626/92334796-0dbe9100-f089-11ea-9c9a-f60e21a71315.png">

One of them is coming from the ghcide plugin, the other one's coming from the Pragmas plugin. 
Can we turn one off?

### Your environment
* HLS 0.4.0 head
* VS Code
* HLS codebase using the default cradle (Cabal I think)

### Steps to reproduce
Screenshot attached

### Expected behaviour
I would expect only one suggestion instead of two

### Actual behaviour
Seen in the screenshot

**Comment by ndmitchell** [comment]
Question is whether such a plugin should live in Ghcide or HLS.

* DAML probably wants it, suggesting Ghcide.
* Makes Ghcide a standalone usable IDE, although I'm not sure that's something we want to aim for.
* Generally decoupling whatever we can is as best as possible, suggesting HLS.

Maybe @cocreature could weigh in?

**Comment by cocreature** [comment]
Seems very similar to the other suggestions we already have in ghcide and it only relies on GHC so I would go for ghcide but I don’t feel all that strongly about this.

**Comment by ndmitchell** [comment]
@cocreature - note that this is an existing suggestion, so the question is whether to _delete_ it from Ghcide, or delete it from HLS.

**Comment by berberman** [comment]
To fix #555, similar code changes would be applied twice to ghcide and HLS if we maintain the status quo.

**Comment by jneira** [comment]
I would say that all ghcide plugins should be separated from the lib, make them follow the haskell plugin definition (introducing hls-plugin-api as dependency) and make ghcide executable depends on those plugins (like we did in hls)
I would keep them in the ghcide repo to make them available to daml, that maybe would need be refactored to acommodate that change (not sure about that)

That said, that change should be applied as a whole so i would remove the hls plugin in a first step.

**Comment by pepeiborra** [comment]
@jneira you should open an issue in the ghcide issue tracker to discuss the extraction of ghcide "plugins".

**Comment by pepeiborra** [comment]
> @jneira you should open an issue in the ghcide issue tracker to discuss the extraction of ghcide "plugins".

I have done this:

https://github.com/haskell/ghcide/issues/935
https://github.com/haskell/ghcide/issues/936

**Comment by Ailrun** [comment]
Maybe #630 also has the same root?

**Comment by gdevanla** [comment]
So, is this issue still open due to lack of decision to keep/remove Pragma code action from ghcide?

**Comment by jneira** [comment]
@gdevanla the plan was remove it from his, any reason to prefer it over ghcide one?
And yeah there is no technical reason to wait for do it so a pr would be very welcomed

**Comment by jneira** [comment]
@gdevanla sorry, i had not seen your pr (#662) that seems to be related. So if the hls plugin is more complete thanks to it, it would be a good reason to keep it and delete ghcide one

**Comment by jneira** [comment]
Afaik this one was closed by #948, thanks @gdevanla!
