### ISSUE TITLE
`hls-fourmolu-plugin` support for `fourmolu` `0.14`

### ISSUE THREAD

**Issue by peterbecich** [haskell/haskell-language-server#3809]
## Is your enhancement request related to a problem? Please describe.

Current upper bound is `<0.14`.
https://hackage.haskell.org/package/hls-fourmolu-plugin

Latest release is `0.14.0.0`: https://hackage.haskell.org/package/fourmolu

## Describe the solution you'd like

Support for `fourmolu` `0.14.0.0`

Thank you

**Comment by michaelpj** [comment]
Done a while ago: https://github.com/haskell/haskell-language-server/pull/3796

**Comment by peterbecich** [comment]
Thanks, I should have checked https://github.com/haskell/haskell-language-server/blob/master/plugins/hls-fourmolu-plugin/hls-fourmolu-plugin.cabal#L48
