### ISSUE TITLE
Comment Underlined as Error

### ISSUE THREAD

**Issue by TheCongaGuy** [haskell/haskell-language-server#3810]
### Your environment

Which OS do you use? - <b> Windows</b>
 

Which version of GHC do you use and how did you install it? - <b>v.9.2.8 via the following PowerShell command;</b>

```
Set-ExecutionPolicy Bypass -Scope Process -Force;[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; try { Invoke-Command -ScriptBlock ([ScriptBlock]::Create((Invoke-WebRequest https://www.haskell.org/ghcup/sh/bootstrap-haskell.ps1 -UseBasicParsing))) -ArgumentList $true } catch { Write-Error $_ }
```

How is your project built (alternative: link to the project)?
```
In the vscode terminal, using:
 ghci > :l
 ghci > run {{fileName.hs}}
```

Which LSP client (editor/plugin) do you use?

<b>
I use the Haskell v.2.4.1 extension on VSCode published by Haskell </b>

Which version of HLS do you use and how did you install it?

Have you configured HLS in any way (especially: a `hie.yaml` file)?

### Steps to reproduce

1) Create a new .hs file

2) On line 1 add a comment, such as '-- CptS 355 - Fall 2023 -- Homework1 - Haskell' (in my case)

3) On line 10 write any function, such as `test [] = []`

4) Save the file once

### Expected behaviour

File should be saved as normal, ready to be loaded.

### Actual behaviour

The comment on line 1 will be underlined as an error. I have copy pasted the error in the Debug Information. Upon saving a second time, I've noticed it is up to random chance if this error stays or resolves itself. Regardless of the error being underlined, the application will still load and you can still run the file.

### Debug information

Error Information:

{{ghcide location}}\Local\ghcide\main-da39a3ee5e6b4b0d3255bfef95601890afd80709\{{File Location and Name}}\ext9514: renameFile:renamePath:MoveFileEx "\\\\?\\{{ghcide location}}\\Local\\ghcide\\main-da39a3ee5e6b4b0d3255bfef95601890afd80709\\{{File Location and Name}}\\ext9514" Just "\\\\?\\{{ghcide location}}\\Local\\ghcide\\main-da39a3ee5e6b4b0d3255bfef95601890afd80709\\{{File Location and Name}}\\hs.hie": permission denied (Access is denied.)compiler

**Comment by fendor** [comment]
Hi, thank you for your bug report!

So essentially, HLS can not access the `.hie` file for some haskell module.
This may be caused by another process that has opened this file as well, or some process didn't clean up properly.

Try closing all GHC / HLS processes, and then delete the cache directory, e.g. `\\?\{{ghcide location}}\Local\ghcide\main-da39a3ee5e6b4b0d3255bfef95601890afd80709\`.
Then open *only* HLS and see if the error arises again.

Also, could you please share the exact module and .cabal file you have? If you don't have a cabal file in your project, that's fine, too.

**Comment by TheCongaGuy** [comment]
Following your advice, it does seem to work! The mystery error doesn't seem to appear after attempting to recreate it. Thanks for working with me! Not sure why a file couldn't be loaded though? I really only work on one project at a time, unless it is to copy some code I'm too lazy to rewrite. Hopefully this was just my machine being dumb and not some minute edge case!

**Comment by fendor** [comment]
Windows and GHC don't always work flawlessly together. I fully expect this to be some edge case in either GHC or HLS, but not your fault :)
