### ISSUE TITLE
Error: [S-5159]

### ISSUE THREAD

**Issue by LaiKangWei** [haskell/haskell-language-server#3837]
### Your environment
vscode

Which OS do you use?
 Windows 11
Which version of GHC do you use and how did you install it?
 
   Tool  Version  Tags                      Notes      
X  ghc   7.10.3   base-4.8.2.0
X  ghc   8.0.2    base-4.9.1.0
X  ghc   8.2.2    base-4.10.1.0
X  ghc   8.4.1    base-4.11.0.0
X  ghc   8.4.2    base-4.11.1.0
X  ghc   8.4.3    base-4.11.1.0
X  ghc   8.4.4    base-4.11.1.0
X  ghc   8.6.1    base-4.12.0.0
X  ghc   8.6.2    base-4.12.0.0
X  ghc   8.6.3    base-4.12.0.0
X  ghc   8.6.4    base-4.12.0.0
X  ghc   8.6.5    base-4.12.0.0
X  ghc   8.8.1    base-4.13.0.0
X  ghc   8.8.2    base-4.13.0.0
X  ghc   8.8.3    base-4.13.0.0
X  ghc   8.8.4    base-4.13.0.0
X  ghc   8.10.1   base-4.14.0.0
X  ghc   8.10.2   base-4.14.1.0
X  ghc   8.10.3   base-4.14.1.0
X  ghc   8.10.4   base-4.14.1.0
X  ghc   8.10.5   base-4.14.2.0
X  ghc   8.10.6   base-4.14.3.0
X  ghc   8.10.7   base-4.14.3.0             hls-powered
X  ghc   9.0.1    base-4.15.0.0
X  ghc   9.0.2    base-4.15.1.0             hls-powered
X  ghc   9.2.1    base-4.16.0.0
X  ghc   9.2.2    base-4.16.1.0
X  ghc   9.2.3    base-4.16.2.0
X  ghc   9.2.4    base-4.16.3.0
X  ghc   9.2.5    base-4.16.4.0
X  ghc   9.2.6    base-4.16.4.0
X  ghc   9.2.7    base-4.16.4.0
I  ghc   9.2.8    base-4.16.4.0             hls-powered
X  ghc   9.4.1    base-4.17.0.0
X  ghc   9.4.2    base-4.17.0.0
X  ghc   9.4.3    base-4.17.0.0
X  ghc   9.4.4    base-4.17.0.0
X  ghc   9.4.5    base-4.17.1.0             hls-powered
X  ghc   9.4.6    base-4.17.2.0             hls-powered
IS ghc   9.4.7    recommended,base-4.17.2.0 hls-powered
X  ghc   9.6.1    base-4.18.0.0
X  ghc   9.6.2    base-4.18.0.0             hls-powered
X  ghc   9.6.3    base-4.18.1.0
X  ghc   9.8.1    latest,base-4.19.0.0      2023-10-09
X  cabal 2.4.1.0
X  cabal 3.0.0.0
X  cabal 3.2.0.0
X  cabal 3.4.0.0
X  cabal 3.4.1.0
X  cabal 3.6.0.0
IS cabal 3.6.2.0  recommended
X  cabal 3.8.1.0
X  cabal 3.10.1.0 latest
X  hls   1.1.0
X  hls   1.2.0
X  hls   1.3.0
X  hls   1.4.0
X  hls   1.5.0
X  hls   1.5.1
X  hls   1.6.0.0
X  hls   1.6.1.0
X  hls   1.7.0.0
X  hls   1.8.0.0
X  hls   1.9.0.0
X  hls   1.9.1.0
X  hls   1.10.0.0
X  hls   2.0.0.0
X  hls   2.0.0.1
X  hls   2.1.0.0
IS hls   2.2.0.0  recommended
X  hls   2.3.0.0  latest
X  stack 2.5.1
X  stack 2.7.1
X  stack 2.7.3                              2022-02-02
X  stack 2.7.5
X  stack 2.9.1
IS stack 2.9.3
I  stack 2.11.1   recommended
X  stack 2.13.1   latest
IS ghcup 0.1.19.4 latest,recommended
Download through ghcup
How is your project built (alternative: link to the project)?

Which LSP client (editor/plugin) do you use?

Which version of HLS do you use and how did you install it?

Have you configured HLS in any way (especially: a `hie.yaml` file)?

### Steps to reproduce

running stack setup / everytime reopen vscode

### Expected behaviour

Should not yield error
### Actual behaviour
Got error below
Error: [S-5159]
```
The GHC located at C:\Users\User1\AppData\Local\Programs\stack\x86_64-windows\ghc-9.2.8\bin\ghc.exe failed to compile a sanity check. Please see:

    http://docs.haskellstack.org/en/stable/install_and_upgrade/

for more information. Exception was:
Received ExitFailure 1 when running
Raw command: "C:\\Users\\User1\\AppData\\Local\\Programs\\stack\\x86_64-windows\\ghc-9.2.8\\bin\\ghc.exe" "C:\\Users\\User1\\AppData\\Local\\Temp\\stack-sanity-check-2788d7c1e0eed89e\\Main.hs" -no-user-package-db
Run from: C:\Users\User1\AppData\Local\Temp\stack-sanity-check-2788d7c1e0eed89e\
Standard error:

Unable to start C:\Users\User1\AppData\Local\Programs\stack\x86_64-windows\ghc-9.2.8\bin/ghc-9.2.8.exe (error code: 2)
```

### Debug information

![image](https://github.com/haskell/haskell-language-server/assets/126481432/0efb29ed-fc19-45c4-9fb6-069a03d3f741)

**Comment by fendor** [comment]
Hi, thank you for your bug report!

The issue you are seeing looks like a stack bug https://github.com/commercialhaskell/stack. Tagging @mpilgrem

What's the output of the command `stack setup`? Perhaps it includes better debug information.

**Comment by LaiKangWei** [comment]
Hi this is what happen when run stack setup, sorry im a very new beginner in haskell and i learnt this because of university
![image (4)](https://github.com/haskell/haskell-language-server/assets/126481432/545a46ed-30f2-45bf-9b26-4881a17745a4)

**Comment by fendor** [comment]
Thanks!

So, you briefly showed the output of `stack test` which complained about the ghc executable.
Perhaps it has been mangled for some reason during the download.

Try deleting `C:\Users\User1\AppData\Local\Programs\stack\x86_64-windows\` and rerun `stack test`/`stack setup`. Does it make a difference?

If not, it looks like you installed GHC via ghcup. Does `ghci` work in the terminal?
Also, have you followed https://www.haskell.org/ghcup/guide/#strategy-2-stack-hooks-new-recommended ?

**Comment by LaiKangWei** [comment]
Meaning the Users folder? but I got other stuff in there. Is it removing the x86_64-windows folder?

**Comment by fendor** [comment]
Sorry, only delete exactly that folder, not your `AppData`, not your `User1` folder.

**Comment by LaiKangWei** [comment]
omg it worked!!!!!!!!!!!!!!!!!! Thankyou, life savior!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by LaiKangWei** [comment]
https://github.com/haskell/haskell-language-server/issues/2495

btw i followed this link

**Comment by fendor** [comment]
Happy to hear that!
Feel free to open another issue if you run into more issues.

> btw i followed this link before i post this thread, and i did remove the default file, does it matter?

No it does not.
