### ISSUE TITLE
Plugin infrastructure for performing WorkspaceApplyEdit with correct indentation

### ISSUE THREAD

**Issue by isovector** [haskell/haskell-language-server#385]
### Subject of the issue
I'm working on a plugin to fill typed holes. Unfortunately, when I fill it with a case expression, the indentation gets thrown off. This is too tricky of an issue for individual plugin authors to implement on their own, and is an excellent candidate for infrastructure in HLS proper.

**Comment by jneira** [comment]
To make it explicit, do not the edit utilities in https://github.com/haskell/haskell-language-server/blob/master/hls-plugin-api/src/Ide/PluginUtils.hs fit in your use case or you tried them and they drop the identantion?

**Comment by isovector** [comment]
I tackled this in #391
