### ISSUE TITLE
Drop support for GHC 9.0 early

### ISSUE THREAD

**Issue by michaelpj** [haskell/haskell-language-server#3872]
GHC 9.0 is still in our support window, but:
1. Anecdotally, it's an unpopular release, with most people having gone straight from 8.10 to 9.2
2. It is relatively expensive for us to support, since the exactprint in-tree migration happened in 9.2. So if we drop it we can get rid of a bunch of CPP.

For these reasons I propose dropping GHC 9.0 after the next release.

**Comment by hasufell** [comment]
+1
