### ISSUE TITLE
HLS 2.5.0.0 generates Stan? related error

### ISSUE THREAD

**Issue by Release-Candidate** [haskell/haskell-language-server#3885]
### Your environment

Which CPU do you use?

- Apple ARM64 M1

Which OS do you use?

- MacOS Sonoma 14.1.2

Which version of GHC do you use and how did you install it?

- 9.6.3 ghcup (ARM64)

How is your project built (alternative: link to the project)?

- Using stack.

Which LSP client (editor/plugin) do you use?

- VS Code + Haskell 

Which version of HLS do you use and how did you install it?

- 2.5.0.0 ghcup (ARM64)

Have you configured HLS in any way (especially: a `hie.yaml` file)?

- Does not work with or without an explicit `hie.yaml` - HLS 2.4.0.0 is working with the same `hie.yaml`.

### Steps to reproduce

- I don't know. Works with a "simple" project with 5 source files in total - 1x app, 2x lib 2x test - but not in two other, but still small, projects.

### Expected behaviour

- No errors are generated. Works when building manually and with HLS 2.4.0.0

### Actual behaviour

Some Haskell source files - not all in the same subdirectory and not all files of a subdirectory - generate a HLS error.

### Debug information

- Error message:

```text
nodeInfo
CallStack (from HasCallStack):
  error, called at src/Relude/Debug.hs:296:11 in rld-1.2.1.0-ae82aff6:Relude.Debug
  error, called at src/Stan/Hie/Compat904.hs:56:24 in stn-0.1.0.2-d29f6af7:Stan.Hie.Compat904
```

I do not see any indication of errors in the "Output" pane of "Haskell" in VS Code.

**Comment by fendor** [comment]
Hi, thank you for your bug report!

Pinging @0rphee as the maintainer of the stan plugin.

**Comment by fendor** [comment]
I can reproduce on the HLS codebase itself.

**Comment by Release-Candidate** [comment]
Thank you very much, that spares me from the work of generating a minimal project to reproduce the error

**Comment by fendor** [comment]
The latest VSCode 2.4.2 should disable the stan plugin by default. Can you give it a try?

**Comment by Release-Candidate** [comment]
Yes, thanks, it is working now.

And as soon as I enable Stan in the extension's config, the error appears.

**Comment by fendor** [comment]
Keeping this open since this is a real issue we have to fix, but we have a work around :)

**Comment by 0rphee** [comment]
This is an issue with the stan compatibility layer for =<9.4. 
I'm very busy right now, but next week I will take a look.

**Comment by 0rphee** [comment]
> I can reproduce on the HLS codebase itself.
> 
> I will make a release for VSCode so that you can disable the stan plugin and silence this error.

@fendor do you happen to remember on which file, or component/package you used it? I cannot reproduce.

**Comment by fendor** [comment]
@0rphee Make sure to enable the plugin in vscode, and then ghcide/.../Session.hs triggered the error at the very top after some time.
