### ISSUE TITLE
Generate a simple cabal cradle if available

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-language-server#3886]
## Is your enhancement request related to a problem? Please describe.

For a long time, we have been telling users to use 
```yaml
cradle:
  cabal:
```
if anything fishy is going on with implicit-hie.
Implicit-hie has served its purpose, and will continue to do so for stack cradles, but for cabal, the trivial cradle should work more reliable.

## Describe the solution you'd like

If the user uses a cabal version greater than 3.2, then the internally generated cabal cradle should be the trivial one.

## Additional context

https://discourse.haskell.org/t/whats-the-current-status-of-hls-cradle-discovery/8254/5

**Comment by fendor** [comment]
It seems that #3462 may have implemented this behaviour already, so perhaps we can close this issue immediately.

**Comment by Avi-D-coder** [comment]
Any chance stack will be able to generate it's own cradle in the near future?
I have just been notified of a build error, and I don't do much Haskell these days.
It'd be good to replace my hacky solution for stack too.

**Comment by fendor** [comment]
Unfortunately, we are currently not closer to any solution for stack

**Comment by michaelpj** [comment]
This is done
