### ISSUE TITLE
Mark `hls-fourmolu-plugin`, `hls-ormolu-plugin` buildable with GHC 9.8

### ISSUE THREAD

**Issue by moonshxne** [haskell/haskell-language-server#3897]
I noticed that many plugins are marked as `buildable: false` for GHC 9.8 because of a dependency on `ghc-exactprint`. However, having tried to build HLS with nix for GHC 9.8.1, I'm fairly certain that `hls-fourmolu-plugin` and `hls-ormolu-plugin` actually don't depend on exactprint (and the latest `fourmolu` and `ormolu` already support GHC 9.8).

**Comment by michaelpj** [comment]
Great, should be easy to verify, CI will tell us.
