### ISSUE TITLE
Unexpected usage error - undefined symbol

### ISSUE THREAD

**Issue by RichardWarfield** [haskell/haskell-language-server#3898]
### Your environment

Which OS do you use? Arch Linux
Which version of GHC do you use and how did you install it? 9.6.3 with haskell.nix
How is your project built (alternative: link to the project)? cabal

Which LSP client (editor/plugin) do you use? emacs+lsp-mode
Which version of HLS do you use and how did you install it? 2.5.0.0, built from source using nix
Have you configured HLS in any way (especially: a `hie.yaml` file)? Yes I have a hie.yaml containing my various packages and components

### Actual behaviour

Diagnostics, hover etc don't work at all in emacs for the project.  Running `haskell-language-server` from the command line shows many errors similar to the below.

The project can be built with cabal without problem.  `cabal repl` also works fine.  I've tried deleting ~/.cache/hie-bios to no avail.

```
  /home/richard/project/src/Metrics/TextfileExporter.hs
Hidden:   no
Range:    1:1-2:1
Source:   typecheck
Severity: DiagnosticSeverity_Error
Message: 
  Unexpected usage error
  /nix/store/94pp1d89yl4x5f1x6jmb216fs0w93md9-aeson-lib-aeson-2.1.2.1/lib/x86_64-linux-ghc-9.6.3/libHSaeson-2.1.2.1-GnMqW0o872s8RIjt0Svfm4-ghc9.6.3.so:
  undefined symbol:
  bytestringzm0zi11zi5zi2zm1FkOkb2DprnGh7KU9Uwoy2_DataziByteStringziLazzyziInternal_toStrict2_closure
```

**Comment by fendor** [comment]
Hi, thank you for your bug report!

There is another cache in `~/.cache/ghcide` you can try to delete and retry.
However, this looks like there is an error in a dependency installed by haskell.nix.
Maybe @michaelpj knows more.

**Comment by RichardWarfield** [comment]
Thanks for the quick response.  I tried deleting both `~/.cache/ghcide` and `~/.cache/hie-bios` but still same result.

**Comment by michaelpj** [comment]
This is weird. I agree it looks like the nix-built library file is broken, but then I'm surprised that `cabal repl` doesn't also break in the same way. I would say "maybe cabal is rebuilding the libraries so they're fine", but we get the flags from cabal so if that was happening we should see it too.

I guess maybe try with an empty cabal cradle and see if that makes any difference on that file?

like this:
```
cradle:
  cabal:
```

**Comment by RichardWarfield** [comment]
I tried using the empty cradle, but that didn't seem to change the result.  I also tried downgrading aeson by a minor version (to 2.1.2.0), just to perturb things and see if anything changed since the original errors seemed to all relate to aeson somehow.  I'm now seeing a lot of errors that look like the following.  This is after again nuking the two cache directories and confirming `cabal repl` still works.  

```
  <no location info>: error:
  /home/richard/.cache/hie-bios/dist-myproject-c99a57d181b0c5f31770ad32ba847f6f/build/x86_64-linux/ghc-9.6.3/dhall-1.41.2/build/libHSdhall-1.41.2-inplace-ghc9.6.3.so:
  undefined symbol:
  
profunctorszm5zi6zi2zm3ec2ab57d5a1114ecf95ef66ba66f7aa71191fe2ba1e636a8b67f2e31e9296b1_DataziProfunctorziUnsafe_dimap_info
  Error: cabal: Failed to build rest-resource-0.1.0.0 (which is required by
  myproject-0.1.0.0).

...

  <no location info>: error:
  Dynamic hash doesn't match for ‘Dhall.Syntax.Instances.Data’
  Normal interface file from
  /home/richard/.cache/hie-bios/dist-myproject-c99a57d181b0c5f31770ad32ba847f6f/build/x86_64-linux/ghc-9.6.3/dhall-1.41.2/build/Dhall/Syntax/Instances/Data.hi
  Dynamic interface file from
  /home/richard/.cache/hie-bios/dist-myproject-c99a57d181b0c5f31770ad32ba847f6f/build/x86_64-linux/ghc-9.6.3/dhall-1.41.2/build/Dhall/Syntax/Instances/Data.dyn_hi
  You probably need to recompile ‘Dhall.Syntax.Instances.Data’
  Error: cabal: Failed to build mydep-0.1.0.0 (which is required by
  myproject-0.1.0.0).

```

**Comment by michaelpj** [comment]
Are you using the exact same GHC to build your project and HLS? You must do this - you can't e.g. use the HLS from nixpkgs with a haskell.nix GHC. You have to build HLS with haskell.nix and the same GHC.

**Comment by RichardWarfield** [comment]
I'm using haskell.nix to build/install HLS so the GHC version should be consistent throughout.

**Comment by RichardWarfield** [comment]
I did some more investigation into where those symbols are being imported and exported, in case it helps...

The error seems to indicate that `/nix/store/94pp1d89yl4x5f1x6jmb216fs0w93md9-aeson-lib-aeson-2.1.2.1/lib/x86_64-linux-ghc-9.6.3/libHSaeson-2.1.2.1-GnMqW0o872s8RIjt0Svfm4-ghc9.6.3.so` is looking for `bytestringzm0zi11zi5zi2zm1FkOkb2DprnGh7KU9Uwoy2_DataziByteStringziLazzyziInternal_toStrict2_closure` but can't find it.  

`ldd` shows that that .so is linking to a bytestring library in the nix store as expected...

```
% ldd /nix/store/94pp1d89yl4x5f1x6jmb216fs0w93md9-aeson-lib-aeson-2.1.2.1/lib/x86_64-linux-ghc-9.6.3/libHSaeson-2.1.2.1-GnMqW0o872s8RIjt0Svfm4-ghc9.6.3.so | grep bytestring

>	libHSbytestring-0.11.5.2-1FkOkb2DprnGh7KU9Uwoy2-ghc9.6.3.so => /nix/store/r8anhmxhqld2czm9g5v8xq2n1952sshs-bytestring-lib-bytestring-0.11.5.2/lib/x86_64-linux-ghc-9.6.3/libHSbytestring-0.11.5.2-1FkOkb2DprnGh7KU9Uwoy2-ghc9.6.3.so (0x00007f4d18200000)
```

And `nm` seems to indicate that the offending symbol is indeed in the `bytestring` library:

```
% nm -D /nix/store/r8anhmxhqld2czm9g5v8xq2n1952sshs-bytestring-lib-bytestring-0.11.5.2/lib/x86_64-linux-ghc-9.6.3/libHSbytestring-0.11.5.2-1FkOkb2DprnGh7KU9Uwoy2-ghc9.6.3.so | grep bytestringzm0zi11zi5zi2zm1FkOkb2DprnGh7KU9Uwoy2_DataziByteStringziLazzyziInternal_toStrict2_closure

> 0000000000359b80 D bytestringzm0zi11zi5zi2zm1FkOkb2DprnGh7KU9Uwoy2_DataziByteStringziLazzyziInternal_toStrict2_closure
```
So I'm not sure why it's not getting found.

**Comment by RichardWarfield** [comment]
OK I figured it out.  

In my call to cabalProject' I had:

```
                modules = [ {
                  ghcOptions = ["-finfo-table-map" "-fdistinct-constructor-tables"];
                } ];
```

Whereas HLS was being compiled without those flags - which caused HLS be linked to a different instantiation of the `bytestring` library in the Nix store.  Adding those flags to the HLS build resolved the problem.  So I guess it's necessary to not only use the same version of GHC but also build common dependencies of the program and HLS with the same GHC flags.  

I'll close this then. Thank you for the help.

**Comment by michaelpj** [comment]
Huh, that's surprising to me. I wouldn't expect that to happen :thinking: but it's a bit obscure indeed.

**Comment by spacekitteh** [comment]
> OK I figured it out.
> 
> In my call to cabalProject' I had:
> 
> ```
>                 modules = [ {
>                   ghcOptions = ["-finfo-table-map" "-fdistinct-constructor-tables"];
>                 } ];
> ```
> 
> Whereas HLS was being compiled without those flags - which caused HLS be linked to a different instantiation of the `bytestring` library in the Nix store. Adding those flags to the HLS build resolved the problem. So I guess it's necessary to not only use the same version of GHC but also build common dependencies of the program and HLS with the same GHC flags.
> 
> I'll close this then. Thank you for the help.

How did you add them to the HLS build?

**Comment by RichardWarfield** [comment]
> How did you add them to the HLS build?

I have this in my `flake.nix`:

```nix
      let
        commonModules = [{
          # NOTE some module options like ghcOptions need to be the same for
          # HLS as for the program, so put them here.
          ghcOptions = ["-finfo-table-map" "-fdistinct-constructor-tables"];
          doCheck = false; doCoverage = false; doHaddock = false; dontStrip = true;
        }];
        tools =
          {
            haskell-language-server = {
              version =  "latest";
              cabalProject = ''
                  packages: .
                  package haskell-language-server
                     flags: -floskell -eval
                '';
              modules = [({pkgs, config, ...}: {
                packages.haskell-language-server.name = "haskell-language-server-2.5.0.0";
                packages.haskell-language-server.src = pkgs.fetchurl {
                  url = "mirror://hackage/haskell-language-server-2.5.0.0.tar.gz";
                  sha256 = "sha256-liAms8dTVFZVJED3lFdjmsbpL5G1AXTbHur9eIjwLS0=";
                };
              })] ++ commonModules;
            };
          };
```

Then in my cabalProject' call I have `{ shell.tools = tools; modules = commonModules; }`

**Comment by spacekitteh** [comment]
thanks!
