### ISSUE TITLE
harmonise logging

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-language-server#39]
We seem to have a number of approaches to logging, spread over `haskell-lsp`, `hie` and `ghcide`.

I think there are two decisions we need to take

a) how and what are we going to log?  Tapping into the LSP expectations makes sense, which seems to be to use `stderr`, which can then be managed per process and per client.

b) Which logging framework will we use? In my mind this should be common across `haskell-lsp`, `ghcide`, and `hls`.  And that will drag `hie` in to match, but it should not necessarily be the driver for the decision.

**Comment by alanz** [comment]
I spoke to @ndmitchell today, I gather the logger in `ghcide` is an abstraction, it should be easy to instantiate it with the one already used in `haskell-lsp` etc.

This still leaves open what the logging policy should be.

**Comment by teto** [comment]
every message on stderr appears as an error in neovim logs (which kinda makes sense, it's stderr after all)  but it makes finding actual errors harder.
