### ISSUE TITLE
Completion of GHC options in`OPTIONS_GHC` doesn't properly handle `-`s

### ISSUE THREAD

**Issue by konsumlamm** [haskell/haskell-language-server#3908]
#### Which version of GHC do you use and how did you install it?

9.8.1 from GHCup

#### Which version of HLS do you use and how did you install it?

2.5.0.0

### Steps to reproduce

```hs
{-# OPTIONS_GHC -ddump-simpl -dno-suppr #-}
```
When typing `-dno-suppr`, select the `-dno-suppress-type-signatures` suggestion.

### Expected behaviour

```hs
{-# OPTIONS_GHC -ddump-simpl -dno-suppress-type-signatures #-}
```

### Actual behaviour

```hs
{-# OPTIONS_GHC -ddump-simpl -dno-dno-suppress-type-signatures #-}
```

**Comment by michaelpj** [comment]
I suspect it's not so much the dashes as that it's not correctly handling the presence of a partial prefix at all. We should be able to support that!

**Comment by konsumlamm** [comment]
I think it is the dashes, if I type `-ddum` and select the `-ddump-asm` suggestion, it works as expected.
