### ISSUE TITLE
Failed to format code with error "OrmoluParsingFailed"

### ISSUE THREAD

**Issue by Alecton4** [haskell/haskell-language-server#3912]
### Your environment

<details>

#### Which OS do you use?

Operating System: openSUSE Tumbleweed 20231206
KDE Plasma Version: 5.27.9
KDE Frameworks Version: 5.112.0
Qt Version: 5.15.11
Kernel Version: 6.6.3-1-default (64-bit)
Graphics Platform: X11
#### Which version of GHC do you use and how did you install it?

Output of `haskell-language-server-wrapper --probe-tools`:
```text
haskell-language-server version: 2.4.0.0 (GHC: 9.0.2) (PATH: /home/az/.ghcup/hls/2.4.0.0/lib/haskell-language-server-2.4.0.0/bin/haskell-language-server-wrapper)
Tool versions found on the $PATH
cabal:          3.6.2.1
stack:          2.11.1
ghc:            9.4.7

Tool versions in your project
2023-12-18T06:37:13.171524Z | Debug | executing command: ghc --numeric-version
ghc:            9.4.7
```
Installed via `curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh`
#### How is your project built (alternative: link to the project)?
https://github.com/Alecton4/playground-Haskell/blob/master/Stdm.lhs
#### Which LSP client (editor/plugin) do you use?

VSCode 1.85.0 + `haskell.haskell` 2.4.2
#### Which version of HLS do you use and how did you install it?

See above.
#### Have you configured HLS in any way (especially: a `hie.yaml` file)?
No.

</details>

### Steps to reproduce

1. Open the [file](https://github.com/Alecton4/playground-Haskell/blob/master/Stdm.lhs) and try to format it.

### Expected behaviour

The file should be formatted, I guess.
### Actual behaviour

An error occur:

![image](https://github.com/haskell/haskell-language-server/assets/43232804/3da1d953-3a92-493c-8a73-3bba0fa97e90)

### Debug information

The log in the output panel:

```text
2023-12-18T06:39:31.407264Z | Error | ormolu: Internal Error: ormoluCmd: OrmoluParsingFailed (RealSrcSpan SrcSpanOneLine "/home/az/workspace/playground-Haskell/playground/Stdm.lhs" 6 1 5 Nothing) "[GHC-58481] parse error on input `Last'"
[Error - 2:39:31 PM] Request textDocument/formatting failed.
  Message: ormolu: Internal Error: ormoluCmd: OrmoluParsingFailed (RealSrcSpan SrcSpanOneLine "/home/az/workspace/playground-Haskell/playground/Stdm.lhs" 6 1 5 Nothing) "[GHC-58481] parse error on input `Last'"
  Code: -32603 
```

**Comment by fendor** [comment]
Can reproduce with ormolu only: 
![image](https://github.com/haskell/haskell-language-server/assets/8463814/4543c255-f0ee-49f8-a679-07eb79b4e294)

Looks like ormolu tries to parse the literate haskell file as a haskell file. Maybe ormolu cannot parse `.lhs` files?

Would you mind reporting this issue upstream?

**Comment by Alecton4** [comment]
@fendor Thanks! I will report this upstream. BTW, do you suggest any other formatter that deals with literal Haskell and could be integrated with the VSCode extension?

**Comment by fendor** [comment]
HLS comes with a number of formatters such as `stylish-haskell`, `fourmolu`, `ormolu` and `floskell`. You switch them with `Settings > Extensions > Haskell: Formatting Provider`. 
`fourmolu` is based off `ormolu`, thus has the same issue. `stylish-haskell` barely formats, mainly unifies the imports and I haven't used floskell before, I think. (Brittany is also in the list, but has been removed in recent HLS releases).
So, give `floskell` a try, maybe you are lucky :)

**Comment by fendor** [comment]
Yeah, that looks like it does not understand literate haskell files, I am sorry, it seems you are out of luck :(
