### ISSUE TITLE
stan plugin (enabled by default) gives obnoxious suggestions

### ISSUE THREAD

**Issue by vmchale** [haskell/haskell-language-server#3916]
## Is your enhancement request related to a problem? Please describe.

stan gives a warning on every single lazy field (!) of a data structure that one defines, with the dubious suggestion to add `StrictData` pragmas.

Haskell is a lazy language and the idea that lazy fields cause space leaks is confused. It is embarrassing that the official language server would behave like this out of the box!

## Describe the solution you'd like

Stan suggestions should not pop up or the default options should disable the warning about defining non-strict data structures.

## Additional context

<img width="633" alt="image" src="https://github.com/haskell/haskell-language-server/assets/13259982/577fab89-89d3-450c-9225-ff8a79692c95">

**Comment by fendor** [comment]
Thanks for the bug report!

This was an accident when `hls-stan-plugin` was reintroduced. The `vscode-haskell` plugin disabled the `hls-stan-plugin` already by default.
However, thank you for the reminder, the next release definitely needs to disable the plugin by default again.

**Comment by Bodigrim** [comment]
I came to raise the same issue, motivated by https://github.com/kowainik/stan/issues/550.

**Comment by 0rphee** [comment]
Until the stan plugin takes into account .stan.toml config files, the best way to ignore this suggestions would be to disable the plugin. After that, if you are still interested in other diagnostics, you can create a global `~/.stan.toml` to silence particular observations.
