### ISSUE TITLE
request for `floskell` 11 support in `hls-floskell-plugin`

### ISSUE THREAD

**Issue by peterbecich** [haskell/haskell-language-server#3927]
## Is your enhancement request related to a problem? Please describe.

`floskell` < 11 does not support `aeson` 2.2
`floskell` 11 supports `aeson` 2.2.
https://hackage.haskell.org/package/floskell-0.11.1

The latest version of `hls-floskell-plugin` supports `floskell` < 11.
https://hackage.haskell.org/package/hls-floskell-plugin-2.5.0.0

This makes `hls-floskell-plugin` difficult to build with Nix when using `aeson` 2.2.

## Describe the solution you'd like
Support for `floskell` 11 would make it easier to build `hls-floskell-plugin` with Nix and `aeson` 2.2.

## Additional context

The latest version of `floskell` in NixPkgs is `floskell` 0.11.0: https://github.com/NixOS/nixpkgs/blob/42ad9df28c071f8865f3167b1c875b6abead7c2b/pkgs/development/haskell-modules/hackage-packages.nix#L107834

Thanks

**Comment by michaelpj** [comment]
Note that nobody active is currently maintaining the floskell plugin. If you use it, maybe you would like to maintain it?

**Comment by peterbecich** [comment]
I'd be happy to keep an eye on the plugin. Here is a fix for this issue https://github.com/haskell/haskell-language-server/pull/3933 with some questionable changes to package version numbers, feedback appreciated
