### ISSUE TITLE
Release for 9.6.4

### ISSUE THREAD

**Issue by michaelpj** [haskell/haskell-language-server#3939]
This is a release-tracking ticket.

**Comment by fendor** [comment]
hls-cabal-plugin needs to honour `globalOn` configuration. Currently, diagnostics are produced, even if the plugin is turned off.

**Comment by wz1000** [comment]
I have a fix for https://github.com/haskell/haskell-language-server/issues/3542 failures with 9.8 in hiedb.

**Comment by soulomoon** [comment]
> It would be nice to get #3937 done but not a blocker, depends on when @soulomoon gets to it.

Sure, I've open a pull request for this in https://github.com/haskell/haskell-language-server/pull/3940.

**Comment by benz0li** [comment]
Building of HLS 2.5.0.0 currently fails using GHC 9.6.4:

* Aarch64: https://gitlab.b-data.ch/ghc/ghc-musl/-/jobs/92056
* x86_64: https://gitlab.b-data.ch/ghc/ghc-musl/-/jobs/92057

---

### My environment

Which OS do you use? Alpine Linux 3.19.0

Which version of GHC do you use and how did you install it? 9.6.4  
👉 Docker image `glcr.b-data.ch/ghc/ghc-musl:9.6.4` ([https://github.com/benz0li/ghc-musl](https://github.com/benz0li/ghc-musl/blob/ba4b87499b3dd5cea81cdfbbb755a068f41a8777/prior/9.6.4.Dockerfile))

### Steps to reproduce

**On a host with docker installed**

```bash
docker run --rm -ti glcr.b-data.ch/ghc/ghc-musl:9.6.4 bash
```

**Inside the container**

```
export HLS_VERSION=2.5.0.0 \
  && apk add --no-cache patchelf findutils \
  && cd /tmp \
  && curl -sSL "https://github.com/haskell/haskell-language-server/archive/refs/tags/$HLS_VERSION.tar.gz" \
    -o "haskell-language-server-$HLS_VERSION.tar.gz" \
  && tar -xzf "haskell-language-server-$HLS_VERSION.tar.gz" \
  && cd "haskell-language-server-$HLS_VERSION" \
  && . .github/scripts/env.sh \
  && . .github/scripts/common.sh \
  && sed -i.bak -e '/DELETE MARKER FOR CI/,/END DELETE/d' cabal.project \
  && GHCS="$GHC_VERSION" \
  && export GHCS \
  && ARTIFACT="$(uname -m)-linux-alpine" \
  && export ARTIFACT \
  && cabal update \
  && emake hls-ghc \
  && emake bindist \
  && strip "out/bindist/$ARTIFACT/haskell-language-server-$HLS_VERSION/lib/$GHC_VERSION"/*.so \
  && emake bindist-tar
```

### Logfile

[logfile.txt](https://github.com/haskell/haskell-language-server/files/13898117/logfile.txt)

**Comment by wz1000** [comment]
@benz0li see https://github.com/haskell/haskell-language-server/pull/3929
