### ISSUE TITLE
Extend the Properties api to better support nested configuration

### ISSUE THREAD

**Issue by soulomoon** [haskell/haskell-language-server#3944]
> I don't know whether we might want more configuration options later, but perhaps it would be wise to nest all these in config.tokenMapping or something?

I think this one would be better. I am going to extend the properties api to better support nested configuration.

_Originally posted by @soulomoon in https://github.com/haskell/haskell-language-server/pull/3940#discussion_r1451019549_
            
Since the plugin api's support for nested configuration is poor. It would be better to extend it to enable a type safe configuration for nested configuration. 

### Steps
Towards this goal there are two steps of implementation.
1. The current implementation use (unsafecoerce), and the safty is provided by hand obeying the rules in property map.
Which is not really safe. We replace it with safer implementation. doing in #3947 
2. Extend the configuration api under the above safer implementation to provide nicer nested configuration. doing in #3952

It should support #3937 better

**Comment by michaelpj** [comment]
FWIW I think this is probably not the most important thing to do. We have generally coped with one layer of custom plugin config, and if you need more you can fake it by adding prefixes/suffixes to option names. Not lovely, but not worth a huge amount of effort to fix, IMO.

**Comment by soulomoon** [comment]
no worry. It is very close to be done now.
