### ISSUE TITLE
support module name and split out module name in qualified name

### ISSUE THREAD

**Issue by soulomoon** [haskell/haskell-language-server#3957]
Mainly for `quolified names`.
Semantic highlighting looks worse than syntax highlighting for quolified name.

1. A Syntax highlighting easily support splitting the module part and the name part of a quolified name. 
2. Semantic token is not identifing them, since the `range` of `Name` for quolified name include the module part and the name part as a whole. 

Two steps to solve the problems.
1. First add suppport for module names in the import section, it is easy since there is module name as identifier in hieAst #3958
2. split out the module part and name part, handles ```(Prelude.+), `Data.List.elem` ``` #3958

**Comment by soulomoon** [comment]
Step 2 might requires peek into the source code, which breaks the abstraction of `LSP` and reach into the `LSP`'s package dependency `Text.Rope`, I am not quite sure if it is a good idea to implement Rope related function here. Excepcially when https://github.com/haskell/lsp/pull/542(unrelease) get into release and HLS picks it up, Rope related function implemented in HLS would surely break.

**Comment by michaelpj** [comment]
> Step 2 requires peeking into the source code

Hmm. Why do we need to go into the source code? Don't we have the `OccName` which I think includes the full name text? Then we could just look at that, count how many characters until the last `.`, and split the `Range` at that point? Will need a bit of care about what "character" means, but I don't think we necessarily need the whole file source.

> for (Prelude.+), it is original highlight (Prelude.+) as a whole, now we need to split them. 

Wait, we currently highlight the parens? That's surprising! Is that because GHC gives that as part of the span?

**Comment by soulomoon** [comment]
> Wait, we currently highlight the parens? That's surprising! Is that because GHC gives that as part of the span?
Yes, Ast gives span of `(Prelude.+) `, and OccName give only `+`.

This is the same reason we need to peek into the source code.

**Comment by michaelpj** [comment]
That seems... surprising to me. The _span_ includes all the other text, but the `OccName` doesn't? how odd. Is that expected @wz1000 ?

**Comment by soulomoon** [comment]
You can see that from the renamed source as well.
