### ISSUE TITLE
Semantic Tokens treats a standalone deriving strategy as type parameter

### ISSUE THREAD

**Issue by konn** [haskell/haskell-language-server#3983]
### Your environment

Which OS do you use? macOS Sonoma14.2.1(23C71)

Which version of GHC do you use and how did you install it? GHC 9.2.8 via GHCup

How is your project built (alternative: link to the project)? By `cabal-install`. This can happen in any project, but see [`linear-extra`](https://github.com/konn/linear-extra/blob/a94642b0171639d290b80ffa934b1b00defcd2bd/linear-witness/src/Linear/Token/Borrowing/Unsafe.hs).

Which LSP client (editor/plugin) do you use? VSCode

Which version of HLS do you use and how did you install it? 2.6.0.0, via ghcup-vanilla-0.0.8.

Have you configured HLS in any way (especially: a `hie.yaml` file)? No. Auto Detection.

### Steps to reproduce

Adds a standalone deriving clause with explicit deriving strategy with Semantic Tokens enabled.

```settings.json
{
  "haskell.plugin.semanticTokens.globalOn": true,
  "editor.semanticHighlighting.enabled": true
}
```

Example. Consider the following:

```hs
type LocAddr :: Location -> Type
newtype LocAddr s = LocAddr {getLocAddr_ :: LocAddr_}
  deriving (P.Eq, P.Ord)
  deriving newtype (Hashable)
```

In above, `newtype` is treated as keyword correctly:

![newtype-deriving](https://github.com/haskell/haskell-language-server/assets/21860/c847ebda-e315-4e59-b49b-e1c3b3d1237c)

Next, make `Hashable` instance deriving standalone:

```hs
deriving newtype instance Hashable (LocAddr s)
```

Then `newtype` is rendered differently!

![deriving-newtype-standalone](https://github.com/haskell/haskell-language-server/assets/21860/213e1475-4150-4202-a146-d7b043b3b752)

Changing `newtype` to `anyclass` gives the same effect. If we change it to `via LocAddr_`, `via` is rendered correctly.

### Expected behaviour

Both `newtype` and `anyclass` must be treated as keyword.

### Actual behaviour

Treated as parameter, as above. Here is the token inspection result from VSCode:

![スクリーンショット 2024-01-19 14 11 04](https://github.com/haskell/haskell-language-server/assets/21860/e3724f6c-e25d-4392-81ce-43f7d8695c35)

### Debug information

Here is the trace log of VSCode:

[vscode.log](https://github.com/haskell/haskell-language-server/files/13984634/vscode.log)

**Comment by soulomoon** [comment]
Interesting case, I’ll take a look later

**Comment by soulomoon** [comment]
I can not repro use your setting 
@konn 
<img width="646" alt="image" src="https://github.com/haskell/haskell-language-server/assets/14073857/e6163832-03bf-46ad-889c-4bc8775539c2">

**Comment by soulomoon** [comment]
I can now. Just specific to `instance KnownRepresentable Int8`

**Comment by soulomoon** [comment]
shoud be fixed by https://github.com/haskell/haskell-language-server/pull/3958.
![Uploading Screenshot 2024-01-22 at 21.56.35.png…]()
