### ISSUE TITLE
NixPkgs: `ghcide-test-utils` fails to build

### ISSUE THREAD

**Issue by peterbecich** [haskell/haskell-language-server#3994]
### Your environment

https://github.com/NixOS/nixpkgs/issues/282273

### Steps to reproduce

Package marked broken on both master and haskell-updates.

```
nix build nixpkgs#haskellPackages.ghcide-test-utils
```

or

```
nix build nixpkgs/haskell-updates#haskellPackages.ghcide-test-utils
```

### Actual behaviour

Here is the error if `markBroken` is removed:
```

session-loader/Development/IDE/Session/Implicit.hs:45:43: error: [GHC-76037]
    Not in scope: type constructor or class ‘CradleTree’
    Suggested fix:
      Perhaps use one of these:
        ‘CradleType’ (imported from HIE.Bios.Config),
        data constructor ‘CradleNone’ (imported from HIE.Bios.Types)
   |
45 | inferCradleTree :: FilePath -> MaybeT IO (CradleTree a, FilePath)
   |                                           ^^^^^^^^^^

session-loader/Development/IDE/Session/Implicit.hs:74:39: error: [GHC-76037]
    Not in scope: type constructor or class ‘CradleTree’
    Suggested fix:
      Perhaps use one of these:
        ‘CradleType’ (imported from HIE.Bios.Config),
        data constructor ‘CradleNone’ (imported from HIE.Bios.Types)
   |
74 | stackCradle :: FilePath -> MaybeT IO (CradleTree a, FilePath)
   |                                       ^^^^^^^^^^

session-loader/Development/IDE/Session/Implicit.hs:96:35: error: [GHC-76037]
    Not in scope: type constructor or class ‘CradleTree’
    Suggested fix:
      Perhaps use one of these:
        ‘CradleType’ (imported from HIE.Bios.Config),
        data constructor ‘CradleNone’ (imported from HIE.Bios.Types)
   |
96 | simpleCabalCradle :: FilePath -> (CradleTree a, FilePath)
   |                                   ^^^^^^^^^^

```

Can this be fixed in this repository and a new release published?

-------------

There is no issue with building `ghcide-test-utils` with plain Cabal in this repository:
```
cd ghcide-test/test
cabal build  --enable-tests
```
succeeds

Thanks

**Comment by michaelpj** [comment]
Looks like it needs a lower-bound on `hie-bios`

**Comment by michaelpj** [comment]
Ah no, it needs a bound on `ghcide`. It shouldn't really be a separate package at all tbh

**Comment by michaelpj** [comment]
It has no bound on ghcide at all.

**Comment by peterbecich** [comment]
I misread the `nix log`.

`ghcide-test-utils` is correctly marked broken on both `master` and `haskell-updates`.

Additionally, `ghcide` is broken on `haskell-updates`, but not marked broken.
```
nix build nixpkgs/haskell-updates#haskellPackages.ghcide  
```
The build failure above is `ghcide` on `haskell-updates`.

**Comment by michaelpj** [comment]
Does nixpkgs jailbreak the bounds or something? Recent `ghcide` needs a newer `hie-bios`, but it does seem to correctly declare the bounds as far as I can see :thinking:

**Comment by peterbecich** [comment]
I don't believe there is any jailbreaking in `hackage-packages.nix`, where `ghcide` is defined. `jailbreak` doesn't appear in that file:
https://github.com/NixOS/nixpkgs/blob/fc9b80e7a36a991dd25490a5a8ea795439a190c6/pkgs/development/haskell-modules/hackage-packages.nix

In smaller collections of packages for specific purposes, like text formatting, `jailbreak` and other manual fixes are used. i.e. https://github.com/NixOS/nixpkgs/commit/83c6ef3b9c75a50456309d5e1361c86311e43d69


My understanding is that `hackage-packages.nix` is entirely generated, and no manual edits are allowed: https://github.com/NixOS/nixpkgs/blob/fc9b80e7a36a991dd25490a5a8ea795439a190c6/pkgs/development/haskell-modules/HACKING.md

**Comment by michaelpj** [comment]
Which version of `ghcide` is it building?

**Comment by peterbecich** [comment]
Currently `2.6.0.0`

```
$ nix search nixpkgs/haskell-updates#haskellPackages.ghcide
* legacyPackages.x86_64-linux.haskellPackages.ghcide (2.6.0.0)
  The core of an IDE
```


The previous version `2.5.0.0` had a different issue, resolved: https://github.com/haskell/haskell-language-server/issues/3945
```
nix build nixpkgs/49c1247b0e54#haskellPackages.ghcide  
...
       > hiedb >=0.4.4 && <0.4.5

```

`2.4.0.0` builds fine:
```
 nix search nixpkgs/0b3450476c35#haskellPackages.ghcide                           
* legacyPackages.x86_64-linux.haskellPackages.ghcide (2.4.0.0)
  The core of an IDE

 nix build nixpkgs/0b3450476c35#haskellPackages.ghcide 
```

**Comment by michaelpj** [comment]
2.6 bounds hie-bios to 0.13.1, which is correct: https://hackage.haskell.org/package/ghcide

It really looks like you're forcing it to build with an older hie-bios

**Comment by peterbecich** [comment]
You're absolutely right, great catch, thanks

```
nix search nixpkgs/haskell-updates#haskellPackages.hie-bios
* legacyPackages.x86_64-linux.haskellPackages.hie-bios (0.12.1)
  Set up a GHC API session
```

So `hie-bios` needs to be updated.

**Comment by peterbecich** [comment]
`ghcide` is fixed.
`ghcide-test-utils` remains broken


After `broken` removed:
```
Using Parsec parser
Configuring ghcide-test-utils-1.9.0.0...
CallStack (from HasCallStack):
  withMetadata, called at libraries/Cabal/Cabal/src/Distribution/Simple/Utils.hs:368:14 in Cabal-3.10.1.0:Distribution.Simple.Utils
Error: Setup: Encountered missing or private dependencies:
lsp-test >=0.14 && <0.15
```

odd because
https://github.com/haskell/haskell-language-server/blob/26079b56dd13341183832e95d63efc202e37cd31/ghcide/test/ghcide-test-utils.cabal#L38

and NixPkgs has `lsp-test` 0.16

**Comment by peterbecich** [comment]
@haskell/haskell-ide , can someone publish a new release `2.6.0.0` for https://hackage.haskell.org/package/ghcide-test-utils? Just to fix the Nix package https://search.nixos.org/packages?channel=unstable&show=haskellPackages.ghcide-test-utils&from=0&size=50&sort=relevance&type=packages&query=ghcide-test-utils on `haskell-updates` branch

**Comment by fendor** [comment]
Do you need revisions for the 2.6.0.0 release? The latest release should have the updated version constraints.

Closing for now, but feel free to reopen if we should add the revisions.

**Comment by peterbecich** [comment]
No need for 2.6, the version on Hackage now fixed the issue like you said, thanks @fendor
