### ISSUE TITLE
Base lower bounds are wrong

### ISSUE THREAD

**Issue by hasufell** [haskell/haskell-language-server#3999]
Compiling HLS with GHC-9.0.2 results in compilation errors:

```
[ 6 of 76] Compiling Development.IDE.GHC.Compat.Core ( src/Development/IDE/GHC/Compat/Core.hs, dist/build/Development/IDE/GHC/Compat/Core.o, dist/build/Development/IDE/GHC/Compat/Core.dyn_o )

src/Development/IDE/GHC/Compat/Core.hs:509:1: error:
    Could not load module `GHC.Driver.Env'
    It is a member of the hidden package `ghc-lib-parser-9.4.8.20231111'.
    Perhaps you need to add `ghc-lib-parser' to the build-depends in your .cabal file.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
```

Unbuildable configurations must be disallowed by the cabal file, so we don't revive cabal hell.

https://github.com/haskell/haskell-language-server/blob/0a02832ed3d2ef8b5128b1f8de2cbdc98eb4bc2f/haskell-language-server.cabal#L17

https://github.com/haskell/haskell-language-server/blob/0a02832ed3d2ef8b5128b1f8de2cbdc98eb4bc2f/haskell-language-server.cabal#L38

**Comment by fendor** [comment]
Updated the lower bounds and the tested-with field. Do you require a hackage revision?

**Comment by hasufell** [comment]
> Updated the lower bounds and the tested-with field. Do you require a hackage revision?

I don't, but I think it is better to do one.
