### ISSUE TITLE
Generalise the formatter plugin infrastructure

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-language-server#40]
We now have one formatter implemented, Ormolu via #33 

This has been done in a "make it work" way, and I merged it to get concrete progress into the project.

We need to extract some sort of formatter plugin support from this, so it is easy to plug in other formatters.

**Comment by alanz** [comment]
I am going to add floskell, and see what ends up common

**Comment by Ailrun** [comment]
If there's no one working on stylish-haskell plugin, I will make that.

**Comment by Ailrun** [comment]
PR has been made: #146

**Comment by jneira** [comment]
Afaik there is a common formatter module with reusable functions for all formatters: https://github.com/haskell/haskell-language-server/blob/master/hls-plugin-api/src/Ide/Plugin/Formatter.hs
It can be extended if we discover more shared functionality
