### ISSUE TITLE
Stack install hls (upload package to hackage/stackage)

### ISSUE THREAD

**Issue by jeapostrophe** [haskell/haskell-language-server#400]
I'd like to be able to type `stack install haskell-language-server` in a stack package and have a version of all the tools I need for the version of GHC that package is using and put in a place where it will get found, if I change my LSP setup (in neovim) from `cmd = { "haskell-language-server-wrapper", "--lsp" }` to `cmd = { "stack", "exec", "haskell-language-server-wrapper", "--lsp" }`

**Comment by jneira** [comment]
That would be a nice feature, it needs the package in hackage and, optionally in stackage

**Comment by ndmitchell** [comment]
We could continue to use ghcide as a submodule, just make sure we release syncronised? The flexibility of upgrading ghcide quickly seems like its currently pretty useful, so I'd be a bit sad to give that up.

**Comment by jneira** [comment]
Yeah, i overlooked it; just sync them will be enough

**Comment by jneira** [comment]
It turns out the next release will use the hackage ghcide version, so we could relase hls to hackage (by coincidence this time so maybe it will be discontinued)

**Comment by jneira** [comment]
There is some discussion about the issue of the possible mismatch between the project ghc and the used on to compile hls: https://github.com/haskell/haskell-language-server/issues/567#issuecomment-724538262

**Comment by jneira** [comment]
hls is already in hackage and we have too much extra-deps to upload to stackage in short/medium term so closing this
if anybody still thinks that upload to stackage would be good please open a new specific issue
