### ISSUE TITLE
Update hls-plugin-api on Hackage

### ISSUE THREAD

**Issue by galagora** [haskell/haskell-language-server#404]
The current version fails to build with error:
```
src/Ide/Plugin/GhcIde.hs:42:7: error:
    Variable not in scope:
      executeAddSignatureCommand
        :: Language.Haskell.LSP.Core.LspFuncs Ide.Plugin.Config.Config
           -> IdeState
           -> ExecuteCommandParams
           -> IO
                (Either ResponseError Value,
                 Maybe (ServerMethod, ApplyWorkspaceEditParams))
   |
42 |     = executeAddSignatureCommand lf ide (ExecuteCommandParams "typesignature.add" (Just (List [toJSON params])) Nothing)
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Updating this is the only straightforward way to build `haskell-language-server` in Nixpkgs.

**Comment by jneira** [comment]
thanks for the bug report, we should test the package install in isolation

**Comment by galagora** [comment]
The build [works in master](https://github.com/haskell/haskell-language-server/blob/master/hls-plugin-api/src/Ide/Plugin/GhcIde.hs#L42), it's just a matter of updating the version that's on Hackage.

**Comment by jneira** [comment]
From #405 

> Well, i am afraid that the hackage version of hls-plugin-api cant be built standalone cause it relies in the ghcide fork that was used when it was uploaded. It fails to compile with the hackage version of ghcide 😟
> That should not be like that, and i still think the next release should be done correctly, against a suitable released ghcide version.

**Comment by jneira** [comment]
hls-plugin-api-0.4.1.0, compatible with ghcide-0.4.0, has been released:
* https://github.com/haskell/haskell-language-server/tree/hls-plugin-api-0.4.1.0
* https://hackage.haskell.org/package/hls-plugin-api
* https://matrix.hackage.haskell.org/#/package/hls-plugin-api
