### ISSUE TITLE
patchelf issues on nix on darwin

### ISSUE THREAD

**Issue by locallycompact** [haskell/haskell-language-server#4064]
Issue getting this to build on darwin. 

Reproduction by `nix build 'git+https://gitlab.horizon-haskell.net/package-sets/horizon-devtools?ref=hls-darwin#haskell-language-server` on darwin.

Results in:

`patchelf: command not found`

https://gist.github.com/srid/8f99a1fbb6659f3e673ed0cd7fe1044b

Using `addBuildTool prev.haskell-language-server pkgs.patchelf` results in

```
patchelf: not an ELF executable
```

Any ideas here?

**Comment by maralorn** [comment]
patchelf is nixpkgs specific. I don’t think this bug has to do with hls upstream.

**Comment by angerman** [comment]
patchELF can only work on ELF containers. For Darwin we'd need Mach-O. I don't think there exist a patchmacho. The stock install_name_tool and otool however are usually good enough for the usual patchelf needs.

**Comment by michaelpj** [comment]
I don't see that this has anything to do with HLS, sounds like a nixpkgs issue.
