### ISSUE TITLE
HLS 2.6.0.0 does not suggest import code actions with GHC 9.8.1

### ISSUE THREAD

**Issue by gabrielsimoes** [haskell/haskell-language-server#4067]
### Your environment

Which OS do you use?
ArchLinux

Which version of GHC do you use and how did you install it?
9.8.1 from ghcup

How is your project built (alternative: link to the project)?
cabal build

Which LSP client (editor/plugin) do you use?
neovim + haskell-tools

Which version of HLS do you use and how did you install it?
2.6.0.0

Have you configured HLS in any way (especially: a `hie.yaml` file)?
No

### Steps to reproduce

Given a file with:

    main :: IO ()
    main = do
      unless False

Hover over `unless` and running `lua vim.lsp.buf.code_action()`.

### Expected behaviour

HLS should suggest importing `Control.Monad`.

### Actual behaviour

HLS does not suggest importing anything, only `Disable "deferred-out-of-scope-variables" warnings`.

This still works with GHC 9.6.4 from ghcup, but seems broken with 9.8.1.

### Debug information

Both versions of GHC produce the same logs with HLS 2.6.0.0, no errors.

**Comment by fendor** [comment]
Hi, thank you for the bug report! 

The HLS version 2.6.0.0 only has limited support for GHC 9.8.1 https://haskell-language-server.readthedocs.io/en/2.6.0.0/support/ghc-version-support.html, so this is expected behaviour.

It should work better if you build HLS from source via `ghcup compile hls`.

**Comment by gabrielsimoes** [comment]
Nice, sorry for the oversight. I wonder if there is an easy way to log a warning when HLS is launched with a partially supported GHC. Not sure if the HLS runtime has awareness of that at launch.

**Comment by fendor** [comment]
> Not sure if the HLS runtime has awareness of that at launch.

Yeah, unfortunately not :(
