### ISSUE TITLE
Cannot format only "modified" lines

### ISSUE THREAD

**Issue by emlautarom1** [haskell/haskell-language-server#4074]
Today I've upgrade to GHC 9.x from 8.10.4, together with HLS and Cabal. Before the upgrade, I was able to format my code using `fourmolu` alongside VSCode's `"editor.formatOnSaveMode": "modificationsIfAvailable"` option, which only formats part of the code that has been changed (sometimes I want to decide how to format certain code instead of my formatter).

After upgrading, this option no longer works forcing me to format the entire modified Haskell file.

### Your environment

Which OS do you use?
- Fedora 39 Workstation

Which version of GHC do you use and how did you install it?
- 9.4.8 from GHCUp

How is your project built (alternative: link to the project)?
- Plain cabal project (see https://github.com/emlautarom1/shamir-secret-sharing/blob/master/app/Main.hs)

Which LSP client (editor/plugin) do you use?
- VSCode 1.86.1

Which version of HLS do you use and how did you install it?
- HLS 2.5.0.0 from GHCUp

Have you configured HLS in any way (especially: a `hie.yaml` file)?
- Default

### Steps to reproduce

This requires VSCode's with the `"editor.formatOnSaveMode": "modificationsIfAvailable"` option set in the `settings.json` file.

1. Create a Haskell project (ex. through cabal) with Git support
2. Write some valid Haskell code
3. Commit the changes
4. Modify the code
5. Save the file to trigger the formatter

### Expected behaviour

Modified lines should be formatted.

### Actual behaviour

HLS throws and error and does not format the code as intended.

### Debug information

```
2024-02-13T15:51:12.327971Z | Info | fourmolu: Loaded Fourmolu config from: "/home/emlautarom1/.config/fourmolu.yaml"
2024-02-13T15:51:12.331138Z | Error | fourmolu: Internal Error: OrmoluParsingFailed (RealSrcSpan SrcSpanOneLine "/home/emlautarom1/Development/Haskell/shamir-secret-sharing/app/Main.hs" 245 15 17 Nothing) "[GHC-58481] parse error on input `->'"
[Error - 12:51:12 PM] Request textDocument/rangeFormatting failed.
  Message: fourmolu: Internal Error: OrmoluParsingFailed (RealSrcSpan SrcSpanOneLine "/home/emlautarom1/Development/Haskell/shamir-secret-sharing/app/Main.hs" 245 15 17 Nothing) "[GHC-58481] parse error on input `->'"
  Code: -32603 
2024-02-13T15:51:12.380405Z | Info | Typechecking reverse dependencies for NormalizedFilePath "/home/emlautarom1/Development/Haskell/shamir-secret-sharing/app/Main.hs": [  ]
```

**Comment by emlautarom1** [comment]
For now, my workaround is to format the entire file on save. In VSCode's `settings.json`, add the following:

```json
"[haskell]": {
    "editor.formatOnSaveMode": "file",
}
```

**Comment by emlautarom1** [comment]
Note that I'm able to format selections by selecting a range of text and using the `Format Selection` command. My guess is that VSCode is sending different information between the command and it's automatic "format on save" feature, the later causing issues for `fourmolu`/`ormolu`.

**Comment by michaelpj** [comment]
Could you take a look at the message logs and see what different messages VSCode is sending in the two cases? I would indeed expect them to be the same.

**Comment by emlautarom1** [comment]
Ok, after further investigation it seems like the problem also exist when using the `Format Selection` command. A minimal reproducible example is as follows:

1. Create a Haskell file
2. Write the following code:

```haskell
x = case () of
  () ->   ()
```

3. Select the complete `() ->  ()` line
4. Run `Format Selection`.

HLS fails to invoke the formatter with the following error:

```
2024-02-20T13:29:55.151918Z | Error | fourmolu: Internal Error: OrmoluParsingFailed (RealSrcSpan SrcSpanOneLine "/home/emlautarom1/Development/Haskell/myapp/app/Main.hs" 249 4 6 Nothing) "[GHC-58481] parse error on input `->'"
[Error - 10:29:55 AM] Request textDocument/rangeFormatting failed.
  Message: fourmolu: Internal Error: OrmoluParsingFailed (RealSrcSpan SrcSpanOneLine "/home/emlautarom1/Development/Haskell/myapp/app/Main.hs" 249 4 6 Nothing) "[GHC-58481] parse error on input `->'"
  Code: -32603 
```

This seems to be an issue with Ormolu/Fourmolu and not HLS related.

**Comment by michaelpj** [comment]
Yes, that seems right. It looks like we're using native support in `ormolu`/`fourmolu` for formatting ranges, so I think it is indeed a bug.

**Comment by michaelpj** [comment]
Closing as it's tracked upstream.
