### ISSUE TITLE
Add cabal-gild as an alternative cabal file formatter

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-language-server#4082]
https://github.com/tfausak/cabal-gild

**Comment by tfausak** [comment]
I'm the author of Gild. It supports the three latest versions of GHC and only depends on boot libraries, so hopefully it's easy to integrate. Please let me know if there's anything I can do to help here!

**Comment by fendor** [comment]
Indeed, essentially cloning `hls-cabal-fmt-plugin` should suffice.

**Comment by tfausak** [comment]
Awesome, thanks @fendor!
