### ISSUE TITLE
hlint diagnostics not working

### ISSUE THREAD

**Issue by eko234** [haskell/haskell-language-server#410]
### Subject of the issue
hlint diagnostics not working

### Your environment
Tool versions found on the $PATH
cabal:		Not found
stack:		2.3.3
ghc:		Not found

-- i'm using ghc-8.8.4

* Which lsp-client do you use
kak-lsp
* Describe your project (alternative: link to the project)
the base result of runngin "stack new <project>"

* Contents of `hie.yaml`
cradle:
  stack:
    - path: "./src"
      component: "testerino:lib"

    - path: "./app/Main.hs"
      component: "testerino:exe:testerino-exe"

    - path: "./app/Paths_testerino.hs"
      component: "testerino:exe:testerino-exe"

    - path: "./test"
      component: "testerino:test:testerino-test"

### Steps to reproduce
i write some flawed lines like f  = (\_ -> True), which when
using hie in the same editor yields a diagnostic saying i should use (const True) instead, or at least output something
in the diagnostics buffer 

### Expected behaviour
to actually lint such mistakes listed above

### Actual behaviour
nothing

### Include debug information
when i see my debug buffer in kakoune :+1: Config-change detected:
LSP: haskell-lsp:configuration parse error. NotificationMessage {_jsonrpc = "2.0", _method = WorkspaceDidChangeConfiguration, _params = DidChangeConfigurationParams {_settings = Object (fromList [])}} "ket \" languageServerHaskell\" not found"

**Comment by fendor** [comment]
Hi!
Hlint is not yet supported in HLS, see #166 which is the implementation, but not merged yet.
