### ISSUE TITLE
Merged plugins pull in disabled deps when building with `Setup.hs`

### ISSUE THREAD

**Issue by hololeap** [haskell/haskell-language-server#4100]
I'm taking a look at packaging `haskell-language-server-2.7.0.0` for Gentoo Linux. Currently, I have `2.6.0.0` and most plugins installed to my system, although I do not have the `hls-fourmolu-plugin` or `fourmolu` packages installed. Just experimenting with the `Setup.hs` interface, I notice that the `fourmolu` dependency is being pulled in even when the `fourmolu` flag is disabled:

```bash
cd haskell-language-server-2.7.0.0/
runhaskell Setup.hs configure --flag=-fourmolu
```

As you can see, it is still looking for `fourmolu`:

```
Configuring haskell-language-server-2.7.0.0...
Setup.hs: Encountered missing or private dependencies:
fourmolu >=0.14 && <0.16,
ghcide ==2.7.0.0,
hiedb >=0.6.0.0 && <0.7,
hls-graph ==2.7.0.0,
hls-plugin-api ==2.7.0.0,
lsp >=2.4 && <2.5
```

The changes made in https://github.com/haskell/haskell-language-server/pull/3976 seem to be selectively choosing which sub-libraries to build using `build-depends`:

https://github.com/haskell/haskell-language-server/blob/41de40ea637231be3ceb1355513f6a99c0c6026f/haskell-language-server.cabal#L1298-L1301

It seems to me that `Setup.hs` does not seem to have the functionality to handle this, and instead tries to build _all_ sub-libraries mentioned in the `.cabal` file, regardless of what flags are toggled.

This experiment was done using `ghc-9.2.8` and `Cabal-3.6.3.0`.

**Comment by michaelpj** [comment]
I am pretty sure the `Setup.hs` should have the ability to build individual components correctly. `haskell.nix` uses it fine. I note that I get all sorts of weird errors from running just `runhaskell Setup.hs configure`, so I wonder if that simply isn't the right way to use it?

**Comment by hololeap** [comment]
Thank you!
