### ISSUE TITLE
"Typechecked a file which is not currently open in the editor" but that's not the case

### ISSUE THREAD

**Issue by Aster89** [haskell/haskell-language-server#4114]
### Your environment

Which OS do you use?
up-to-date ArchLinux

Which version of GHC do you use and how did you install it?
9.4.8 from ghcup

How is your project built (alternative: link to the project)?
https://github.com/Aster89/reprosForHLS

But you might have to tweak it a bit. E.g.,  `xmobar >= 0.47.4` requires you to have a local repo of `xmobar` so that you can use 0.47.4 (see `cabal.project` too) which doesn't have a tag yet at the time of writing, but I think you should change as little as possible, because I think the complexity of the project (which is not high, but it's definitely not HelloWorld-level) seems to be necessary to reproduce the issue.

Which LSP client (editor/plugin) do you use?
Vim+YCM

Which version of HLS do you use and how did you install it?

Both
- 2.7.0.0 from ghcup
- 2.5.0.0 from ghcup

they give slighly different behaviors, but both erronous.

Have you configured HLS in any way (especially: a `hie.yaml` file)?
Not that I'm aware of :/

### Steps to reproduce

Since the observed behavior is erratic, any attemps I've made to shrink the example substatially while preserving the buggy behavior has been a failure. But with the linked repo, the issue is fairly reproducible.

All is shown in the following screencast, where I also switch HLS version midway.
[![asciicast](https://asciinema.org/a/mcZtf60yqQZ97BVtcgvodydvZ.svg)](https://asciinema.org/a/mcZtf60yqQZ97BVtcgvodydvZ)

but here are some basic steps: 

1. `cd` in the linked repo,
2. open the `xmobar.hs` file on line 77
3. move cursor on `ArchUpdates` and jump to it (should move  you to `ArchUpdates.hs`)
4. move to line 10, on the word `withFont` and jump to it (should move you to `Utils.hs`)

### Expected behaviour
Gotos should work.

### Actual behaviour
Erratic:
- at times jumping works,
- other times it errors,
- sometimes it works but things (like `withFont` at line 10) are incorrectly marked as erroneous
The constant is that the server emits this
```
2024-03-03T17:50:46.093114Z | Warning | Typechecked a file which is not currently open in the editor: /home/enrico/myconfigfiles/HOME/#config/xmobar/Utils.hs
This can indicate a bug which results in excessive memory usage.
This may be a spurious warning if you have recently closed the file.
If you haven't opened this file recently, please file a report on the issue tracker mentioning the HLS version being used, the plugins enabled, and if possible the codebase and file which triggered this warning.
2024-03-03T17:50:58.521012Z | Info | Live bytes: 93.77MB Heap size: 730.86MB
```

### Debug information
I suspect the above should be sufficient.

**Comment by fendor** [comment]
Hi, thank you for your bug report!

This looks like an issue with the multiple home unit support!
You shouldn't expose 'Utils' from both the library and the executable. Rather, in your executable, you should depend on the internal library, to avoid confusing HLS.

**Comment by Aster89** [comment]
@fendor , do you mean that I might have solved the issue by following [this](https://stackoverflow.com/questions/78097507/how-to-avoid-listing-a-as-build-dependency-for-internal-library-executable-e-jus)?

I'll double check and report :smile:

**Comment by fendor** [comment]
Essentially, yes :)

You might into other problems, but exposing the same module twice is bound to cause issues and this weird behaviour where the order of opening modules matters.

**Comment by michaelpj** [comment]
Are we going to consider this a wontfix, then?
