### ISSUE TITLE
Release CI is broken

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-language-server#4120]
https://github.com/haskell/haskell-language-server/actions/runs/8165885130/job/22327004810

Likely, I broke it in #4110 

*But* it proves that the test now works

**Comment by fendor** [comment]
We need to bump the `recommended` version in the vanilla ghcup metadata.

**Comment by hasufell** [comment]
Generally, `recommended` and `latest` are supposed to point to the same version. At least that's how it had been maintained before. If GHC devs want to deviate, I don't really mind, though.

**Comment by fendor** [comment]
This issue has been fixed, but we have a new one: https://github.com/haskell/haskell-language-server/actions/runs/8516412965/job/23326024633

closing this, but I will open a new issue.
