### ISSUE TITLE
HLS often cannot find a `.hi.core` file in `~/.cache/ghcide/`

### ISSUE THREAD

**Issue by siddharth-krishna** [haskell/haskell-language-server#4145]
### Your environment

**Which OS do you use?**
MacOS 11.7.10 and 14
**Which version of GHC do you use and how did you install it?**
9.2.8 via ghcup (0.1.22.0)
**How is your project built (alternative: link to the project)?**
cabal (or nix + cabal)
https://github.com/plow-technologies/inferno

**Which LSP client (editor/plugin) do you use?**
vscode (v1.87.2) + Haskell plugin (v2.4.3)
**Which version of HLS do you use and how did you install it?**
2.7.0.0 via ghcup
**Have you configured HLS in any way (especially: a `hie.yaml` file)?**
No

### Steps to reproduce

I cannot reproduce it myself deterministically, but it happens so often that I'm opening a bug report. Today I tried on a fresh laptop, fresh ghcup + ghc + hls install, fresh install of vscode's Haskell plugin, and within an hour I saw this error again. Here's the steps:
- Install ghcup using official instructions
- Install ghc 9.2.8 and hls 2.7.0.0 using ghcup
- Install vscode and Haskell plugin 
- Wait for HLS to startup, find ghc and hls using ghcup, and build the project. It all works perfectly for a while.
- But at some point, some files start to show an error on the first line that it cannot find a `.hi.core` file in `~/.cache/ghcide/`...

### Expected behaviour

No such error.

### Actual behaviour

I see a red squiggle on the first line of the file, with the error:

> /Users/sid/.cache/ghcide/inferno-core-0.11.1.0-inplace-bdea44f530a52e915c4b2a4fb12efa71e6fd5f24/Inferno/Infer.hi.core: getFileStatus: does not exist (No such file or directory)

### Debug information

The vscode output window for Haskell shows some errors, but I don't know if they are related:
```
2024-03-21T13:20:36.759358Z | Warning | No plugin handles this "textDocument/semanticTokens/full" request.
[Error - 15:20:36] Request textDocument/semanticTokens/full failed.
  Message: No plugins are available to handle this SMethod_TextDocumentSemanticTokensFull request.
 Plugins installed for this method, but not available to handle this request are:
semanticTokens is disabled globally in your config.
  Code: -32601 
[Error - 15:23:06] Request textDocument/foldingRange failed.
  Message: codeRange: Rule Failed: GetCodeRange
  Code: -32803 
...

```

Thank you for all your awesome work 🙌 

---

EDIT:  Clearing the `~/.cache/ghcide/` and `~/.cache/hie-bios/` directories helps for a while, but the error is back soon.

**Comment by jhrcek** [comment]
This behavior should have been made less likely after https://github.com/haskell/haskell-language-server/pull/4076

Though the bug is still present and we're tracking it in https://github.com/haskell/haskell-language-server/issues/4093

I was trying to find the exact place in the code where the `.hi.core` file is actually written but so far failed to find it. It seems there's a race between the code that writes that file and the code that checks the timestamp on it.
@wz1000 is it possible that the code writing .hi.core files runs in separate thread from the code that [checks the timestamp](https://github.com/haskell/haskell-language-server/blob/334b4d4c7d56be3d75aa5f8626f5d68b2f0c03ec/ghcide/src/Development/IDE/Core/Rules.hs#L1076) on it?

**Comment by fendor** [comment]
Thank you for the bug report! @wz1000 will have a closer look at this issue.

**Comment by soulomoon** [comment]
```
[{
	"resource": "/Volumes/src/soulomoonHLS/ghcide/src/Control/Concurrent/Strict.hs",
	"owner": "Haskell (soulomoonHLS)",
	"severity": 8,
	"message": "/Users/ares/.cache/ghcide/ghcide-2.9.0.0-inplace-acd8748a3527adb2c9c8b8ab003c11596c14c67f/Control/Concurrent/Strict.hi.core: getFileStatus: does not exist (No such file or directory)",
	"source": "compiler",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 1
}]
```

**Comment by soulomoon** [comment]
Some how it does not write to core. I wonder if only FOI branch would write out the *.hi.core

**Comment by soulomoon** [comment]
The fail case would be the following, 
* open file A and A' core file would be saved to the first computed `setCacheDirs` using the hashed of the `cacheDirOpts` by the time.
* open file B, the hashed of `cacheDirOpts` changed and `GetModSummary`  would pick up another cache dir location
* reading core file failed.
