### ISSUE TITLE
Implicit cradle failure: /home/user/.cabal: openFile: inappropriate type (is a directory)

### ISSUE THREAD

**Issue by georgefst** [haskell/haskell-language-server#417]
The implicit cradle support is unfortunately completely broken for me, with an impenetrable error ($HOME/.cabal is indeed a directory...):

```
haskell-language-server version: 0.4.0.0 (GHC: 8.10.2) (PATH: /home/gthomas/.cabal/bin/haskell-language-server)
(haskell-language-server)Ghcide setup tester in /home/gthomas/Desktop/tmp.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Tool versions found on the $PATH
cabal:          3.2.0.0
stack:          Not found
ghc:            8.10.2


Step 1/4: Finding files to test in /home/gthomas/Desktop/tmp
Found 1 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files
[INFO] Consulting the cradle for "Tmp.hs"
NotShowMessage (NotificationMessage {_jsonrpc = "2.0", _method = WindowShowMessage, _params = ShowMessageParams {_xtype = MtWarning, _message = "No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for Tmp.hs.\n Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie)"}})
File:     /home/gthomas/Desktop/tmp/Tmp.hs
Hidden:   no
Range:    1:0-2:0
Source:   compiler
Severity: DsError
Message:  /home/gthomas/.cabal: openFile: inappropriate type (is a directory)
Files that failed:
 * /home/gthomas/Desktop/tmp/Tmp.hs

Completed (0 files worked, 1 file failed)
[INFO] finish: User TypeCheck (took 0.00s)
```

This occurs with all cabal projects or standalone files that I've tried.

**Comment by jneira** [comment]
@georgefst weird error, does the file `$HOME/.cabal` exists? It seems that file breaks the hie-implicit l[ogic of discovering the `.cabal` file](https://github.com/Avi-D-coder/implicit-hie-cradle/blob/master/src/Hie/Implicit/Cradle.hs#L157), that needs to be fixed

**Comment by georgefst** [comment]
@jneira Ha right, thanks, I can see what's happening there...

Unfortunately `$HOME/.cabal` is the default directory for cabal on Linux (containing `config`, `store` etc.). Changing that logic to ignore directories is probably enough.

**Comment by jneira** [comment]
A direct workaround could be move the project out of $HOME directory, sorry for the incovniences! we will try to fix it asap

**Comment by arjunkathuria** [comment]
hi. the working solution i got from IRC was.

make a `hie.yaml` file in your project root folder with the following contents
```
cradle: {direct: {arguments: []}}
```

note:- 
OS: linux Debian
ghc:- 8.10.2

**Comment by georgefst** [comment]
@arjunkathuria Yes, that's what I settled on as well.

Though, to be clear, that's just a workaround for the regression that direct cradles have stopped working implicitly. For actually utilising more complex implicit cradles, the only options seems to be to move our projects out of `$HOME`, as @jneira said.

Anyway, the fix is already on the way, and I imagine it'll make it for next HLS release.

**Comment by arjunkathuria** [comment]
@georgefst sweet!
Another win for good bug reports 💯. 

prompt maintainer responses are always appreciated, no matter the bug. thanks @jneira : )

**Comment by jneira** [comment]
Reopen until the fix is included in ghcide/hls

**Comment by jneira** [comment]
@georgefst @arjunkathuria the fix is already in master, could you confirm that it resolves the issue for you?

**Comment by georgefst** [comment]
All working here. Thanks @jneira!

**Comment by jneira** [comment]
@georgefst thanks you for reporting and help to fix the issue itself
