### ISSUE TITLE
Applying a code action to a _ hole produces too many suggestions

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell/haskell-language-server#4198]
I'm often using code actions to import out-of-scope identifiers. But sometimes I accidentally run a code action on a line that contains both an out-of-scope identifier _and_ an underscore, such as:

```haskell
TwoWay.twoWay (zipDefnsWith (alignWith _) undefined) conflicts
                             ^^^^^^^^^
                                this is out of scope, and I want HLS to suggest
                                `import Data.Semialign (alignWith)` with a code action.
```

In this case, the `_` on the same line will cause 1800 (!) suggestions that look like

```
1: replace _ with foo
2: replace _ with bar
...
```

for (I guess?) every single identifier in scope.

**Comment by michaelpj** [comment]
Many things weird here:
- GHC shouldn't compute all this stuff
- We should limit the number of things also

Also somewhat unclear why this is happening at all?

**Comment by akshaymankar** [comment]
I'm looking into this during Zurihac 2024.
