### ISSUE TITLE
HLS hangs in file with typed hole

### ISSUE THREAD

**Issue by andriusstank** [haskell/haskell-language-server#4242]
HLS seems to loop forever typechecking certain code.

I have GHC 9.8.2 and HLS 2.8.0.0, both installed by GHCup on Fedora 33 system.

Heres' complete code to reproduce the issue:

```
{-# LANGUAGE RankNTypes #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE QuantifiedConstraints #-}
{-# LANGUAGE TypeOperators #-}
module MyLib where

type family F a

class F a ~ F b => C a b

f :: (forall x. C x x) => ()
f y = _
```

I run `haskell-language-server-9.8.2~2.8.0.0 MyLib.hs` on command line and it hangs, consuming 100% cpu. If I change this code just about any way, HLS correctly reports errors and exits. GHC also correctly handles this code, reporting type errors.

**Comment by michaelpj** [comment]
Possible duplicate? https://github.com/haskell/haskell-language-server/issues/2731

**Comment by michaelpj** [comment]
If it's to do with the hole

**Comment by andriusstank** [comment]
It's about the hole, I didn't succeed hanging HLS without it. I just tried the code from #2731, HLS quickly inferred the hole, so this must be a different issue.

**Comment by michaelpj** [comment]
We now limit the hole fits, which I hope should fix this.

**Comment by fendor** [comment]
Closed by https://github.com/haskell/haskell-language-server/pull/4288, could you check your issue is indeed solved in the latest release?
