### ISSUE TITLE
Unify critical session running in hls

### ISSUE THREAD

**Issue by soulomoon** [haskell/haskell-language-server#4251]
There are some places we serialize critical session.
* Reactor thread, running the notification handler, by running it in the reactor thread.
* sessionLoader, we load session one by one, spawn a thread each time, and wait for the preivous thread to end.
* sessionRestart, we runs it in seperate threads but using an `MVar` to do the serlization.

The latter two create a challenge for our shutdown handler to halt the hls. Since they are not cancelable.
A possible solution, would be to switch the latter two to the first approach. Create a thread specifically to run the target critical session.

**Comment by soulomoon** [comment]
This might fix the hanging problem happend in windows
https://github.com/haskell/haskell-language-server/pull/2497

**Comment by michaelpj** [comment]
We did this
