### ISSUE TITLE
HLS building forever with no notion of progress

### ISSUE THREAD

**Issue by TotallyNotChase** [haskell/haskell-language-server#4283]
## Your environment 

Which OS do you use?
ArchLinux

Which version of GHC do you use and how did you install it?
GHC 9.6.4 and GHC 9.2.8

How is your project built (alternative: link to the project)?
cabal
https://github.com/mlabs-haskell/clb

Which LSP client (editor/plugin) do you use?

vscode-oss+vscode-haskell/
Which version of HLS do you use and how did you install it?

2.7.0.0 from ghcup
Have you configured HLS in any way (especially: a `hie.yaml` file)?
No

## What's wrong?
HLS is building forever with no update on progress. Equivalent to "Progress: X/Y" with X not changing at all in VSCode. Tries with command line too (`haskell-language-server src/Clb.hs`) with no end in sight.

Is there any way to at least find the progress? `cabal build` doesn't take nearly as long.

**Comment by michaelpj** [comment]
I think this is ultimately https://github.com/haskell/hie-bios/issues/405. If you run with a higher logging level you should get the process output from cabal in your logs, but ideally we would just track this progress in `hie-bios` and report it up.

**Comment by TotallyNotChase** [comment]
I have run HLS with `--debug` and I still get nothing.

The last line simply notes down where the interface directory will be and that's the end of the logs while HLS keeps running forever

**Comment by wz1000** [comment]
This could be #4046, can you try HLS 2.8.0.0?

**Comment by TotallyNotChase** [comment]
I noticed that if I let it run for 4+ hours (`haskell-language-server src/Clb.hs`), it finally succeeds. But when I run it again, nothing is cached and it runs forever once again.

**Comment by TotallyNotChase** [comment]
Looks like HLS 2.8.0.0 works!

Does that imply it was fixed in #4046 ?

**Comment by michaelpj** [comment]
Seems plausible! Sounds like it's fixed anyway.
