### ISSUE TITLE
Field and value completion does not work inside conditionals

### ISSUE THREAD

**Issue by VeryMilkyJoe** [haskell/haskell-language-server#4289]
Cabal completion seems to not be able to complete anything inside if statements.

Here, the default completion for vscode is suggested inside an if conditional, when it should be the library section fields:
![image](https://github.com/haskell/haskell-language-server/assets/22590431/8103a64c-4004-4a53-a11d-aa733d0dc7cc)
Here, the exposed modules values should be completed instead of the default vscode completions:
![image](https://github.com/haskell/haskell-language-server/assets/22590431/3c6102ca-42dd-454b-bb31-a7b2129e6e86)

The fields we are checking for completion are defined [here](https://hackage.haskell.org/package/Cabal-syntax-3.12.0.0/docs/Distribution-Fields.html). 
I think to fix this we can check the parent sections recursively instead of simply the most direct parent to figure out the stanza the cursor is located in.

**Comment by fendor** [comment]
Do we need to change the `Context` then?

**Comment by VeryMilkyJoe** [comment]
> Do we need to change the `Context` then?

I don't think it is necessary to change the type of `Context` for this issue, since we do not care whether we are inside a conditional for the completion.
We can simple set the `StanzaContext` to the nearest parent which is a Stanza.

**Comment by fendor** [comment]
@dyniec is taking a stab at this :confetti_ball:

**Comment by VeryMilkyJoe** [comment]
@dyniec are you still working on this issue?

**Comment by dyniec** [comment]
I couldn't make it work. Please mark it as up for grabs

**Comment by SamuelLess** [comment]
Hi, I'll give it a try :)

**Comment by fendor** [comment]
Implemented by #4427
