### ISSUE TITLE
HLS does not start up if stack's docker integration is enabled.

### ISSUE THREAD

**Issue by ProofOfKeags** [haskell/haskell-language-server#430]
Title says it all, I cannot seem to get hls to come up if `docker: enable: true` is in my stack.yaml file.

### Your environment
- vs code
- stack project
- docker: enable: true
- ghc-8.6.3 (hls installation derived from 8.6.4 with package overrides), I suspect this is unrelated though and could just as easily be reproduced in another version.

**Comment by jneira** [comment]
Thanks for reporting this, what is the log output of the startup (calling hls in the shell)? is there some error logged?

**Comment by jneira** [comment]
I guess the culprit is hie-bios, that maybe can't handle stack projects with docker enabled, see https://github.com/mpickering/hie-bios/issues/45
Maybe @fendor could confirm it.

**Comment by fendor** [comment]
Indeed, hie-bios does not support running stack in docker mode. IIRC, we concluded, that the easiest solution is to run HLS in the docker container as well.

**Comment by jneira** [comment]
Another workaround could be disable docker in a specific `stack.yaml` for hls: see https://github.com/mpickering/hie-bios#stack

**Comment by michaelpj** [comment]
Tentatively closing as no recent reports
