### ISSUE TITLE
Drop support for GHC 9.2

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-language-server#4321]
According to our deprecation policy, GHC `9.2 ` is no longer in our support window. See https://haskell-language-server.readthedocs.io/en/latest/support/ghc-version-support.html#ghc-version-deprecation-policy

This ticket tracks dropping support for GHC `9.2` in the next release (i.e., the one **after** `2.9.0.0`).

If there is any reason we should keep support for `9.2`, please voice your opinions here :)

**Comment by michaelpj** [comment]
Yes, you're right, I had mis-counted and thought it was still in!
