### ISSUE TITLE
ghc-iserv terminated

### ISSUE THREAD

**Issue by LeventErkok** [haskell/haskell-language-server#433]
Upon loading an existing project, I'm getting an error of the form:

```
Installation error: ghc-iserv terminated (-6) typecheck [1,1]
```

I understand this is not much to go on with. If you tell me how to turn on debugging and provide you more info, I'll certainly do so.

If it helps, this is a project that uses both `-dynamic` and `-fexternal-interpreter` as ghc-options.

**Comment by jneira** [comment]
Hi! thanks for the report, could you add a link to your project to try to reproduce the error?
Also the complete output of haskell-language-server could help. 

(`ghc-iserv` is the executable called by ghc if you set `-fexternal-interpreter`)

The original issue was: https://github.com/haskell/vscode-haskell/issues/296.

**Comment by LeventErkok** [comment]
How do I get the complete output of haskell-language-server? In the "OUTPUT" tab, I see nothing.

**Comment by pepeiborra** [comment]
Using `-fexternal-interpreter` with HLS is not supported at the moment. 
ghcide needs to override the user setting and disable this option at startup

As a workaround, you can edit your cabal descriptor and remove this option

**Comment by jneira** [comment]
Thanks for pointed it out. I will keep this open to track the eventual addition of support.
But I am afraid that ghc suggested use it as a way to make -dynamic work, as we can see in  haskell/vscode-haskell#296.
So I will reopen that one.

**Comment by mpickering** [comment]
@pepeiborra Do you know why it is not supported yet? I seem to recall that I used the external interpreter with `haskell-ide-engine` back in the day but that may be mistaken.

**Comment by pepeiborra** [comment]
This is what goes wrong when using `-fexternal-interpreter` for me:
```
ghc-iserv-dyn: internal error: RELEASE_LOCK: I do not own this lock: rts/Linker.c 621
    (GHC version 8.8.4 for x86_64_apple_darwin)
    Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
```

I have not investigated any further.

**Comment by pepeiborra** [comment]
It's very likely that the external interpreter cannot cope with the multithreaded usage of the ghc-api and the abrupt cancellation features in ghcide

**Comment by michaelpj** [comment]
Tentatively closing as no recent reports
