### ISSUE TITLE
Unwanted Completions in Comments

### ISSUE THREAD

**Issue by wgledbetter** [haskell/haskell-language-server#4330]
## Summary

If I'm typing comments, code completion suggestions are irrelevant and frustrating.

## Environment

- VSCode 1.90.2
- vscode-haskell v2.4.4
  - HLS managed via GHCup

## Problem Description

The `Haskell > Plugin > Ghcide-completions` plugin is too enthusiastic about providing completion suggestions. Any time I'm typing a comment and follow a non-space character with a period, a list of suggestions pops up. Usually, in a comment, I'm ending sentences with periods and hit Enter to go to a new line, but instead, the first suggestion will be inserted and I have to backtrack and remove it.

This is obviously a minor issue, but it is consistently frustrating. I am aware of VSCode's `Debug > Console: Accept Suggestion on Enter` option, and yes, this problem could be avoided by disabling it, but I feel like I shouldn't be getting suggestions in a comment in the first place.

## Example

Repo: https://github.com/wgledbetter/hls-issue

![image](https://github.com/haskell/haskell-language-server/assets/3212255/3e71a251-c95a-4eff-b9bd-68e6a55fab3e)

**Comment by michaelpj** [comment]
Duplicate: https://github.com/haskell/haskell-language-server/issues/2292
