### ISSUE TITLE
Document how hls can be configured 

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#437]
* Fow now the configuration section talks exclusively about the build info that hls needs to open a haskell project in a reliable way
* However, there is nothing about the settings that final users can change from their editors/lsp clients:
  * What formatter want to use for example
  * Several options were translated from hie and they still does not make sense, so they should not be documented yet

https://github.com/haskell/haskell-language-server/blob/84a227489ef9d62bf32153d7b4877c7d6169cbad/hls-plugin-api/src/Ide/Plugin/Config.hs#L44-L54

**Comment by googleson78** [comment]
Thanks! This would be great! relating #432, as it is somewhat a start on this.
