### ISSUE TITLE
GLIBC: __tunable_is_initialized, version GLIBC_PRIVATE

### ISSUE THREAD

**Issue by why-not-try-calmer** [haskell/haskell-language-server#4377]
I am on NixOS unstable setting up my project with:
```nix
{
  inputs = {
    nixpkgs.url = "https://github.com/NixOS/nixpkgs/archive/54aac082a4d9.tar.gz";
    flake-utils.url = "github:numtide/flake-utils";
  };
  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        tools = [
          pkgs.haskellPackages.fourmolu
          pkgs.haskellPackages.hoogle
          pkgs.haskellPackages.stack
        ];
      in
      {
        devShell = pkgs.mkShell {
          buildInputs = [
            pkgs.haskellPackages.haskell-language-server
            tools
          ];
          NIX_LD_LIBRARY_PATH = pkgs.lib.makeLibraryPath [
            pkgs.stdenv.cc.cc
            pkgs.openssl
            pkgs.zlib
          ];
          NIX_LD = pkgs.lib.fileContents "${pkgs.stdenv.cc}/nix-support/dynamic-linker";
        };
      }
    );
}
```
Before reproducing I did:
```
rm -rf ~/.cache/stack/
rm -rf ~/.cache/hie-bios
rm -rf ~/.cache/ghcide/
```
I've made sure that `stack` used `system-ghc: yes` and `no-install-ghc: yes` and I've tried to respect HLS's ABI requirements (both ghc --version and haskell-language-server-wrapper tell me that I am using ghc 9.4.8.):

![image](https://github.com/user-attachments/assets/b6dc7a28-edb9-4513-9725-afb3abb5476c)

Now the issue: in VSCode using the latest standard version of the haskell language server extension, I am running into:

![image](https://github.com/user-attachments/assets/cf69d8fd-0392-4e9b-b5e5-78ae7408796e)

VSCode HLS extension is thus not working for me at all for this project.

Any hint?

**Comment by fendor** [comment]
Thanks for the bug report!

Can you post the output of `haskell-language-server-wrapper --debug <some-path-in-your-project>`?

**Comment by why-not-try-calmer** [comment]
> Thanks for the bug report!
> 
> Can you post the output of `haskell-language-server-wrapper --debug <some-path-in-your-project>`?

Yes, that will output building my entire project though.

**Comment by why-not-try-calmer** [comment]
[logs.txt](https://github.com/user-attachments/files/16522033/logs.txt)

**Comment by fendor** [comment]
These logs don't seem to include the error message from the issue :(

**Comment by why-not-try-calmer** [comment]
Sorry @fendor, here's the correct file
[logs.txt](https://github.com/user-attachments/files/16522799/logs.txt)

**Comment by fendor** [comment]
Looks like the module that fails is using TemplateHaskell: https://github.com/why-not-try-calmer/feedo/blob/master/src/TgramInJson.hs

Likely related, potentially a distribution issue.
I remember some issues about TemplateHaskell with static vs dynamic linking.

**Comment by fendor** [comment]
I can't run the nix flake from my arch linux: 

```
 nix develop                                                                                                                                                                       15:54:56
error:
       … while calling the 'derivationStrict' builtin

         at /builtin/derivation.nix:9:12: (source not available)

       … while evaluating derivation 'nix-shell'
         whose name attribute is located at /nix/store/50bgi74d890mpkp90w1jwc5g0dw4dccr-source/pkgs/stdenv/generic/make-derivation.nix:348:7

       … while evaluating attribute 'NIX_LD' of derivation 'nix-shell'

         at /nix/store/86n4xb2xaa7sr85m4vc1n0s2892s2dpl-source/flake.nix:27:11:

           26|           ];
           27|           NIX_LD = pkgs.lib.fileContents "${pkgs.stdenv.cc}/nix-support/dynamic-linker";
             |           ^
           28|         };

       error: access to canonical path '/nix/store/lwqnazddv8037sin49482dnzc9iwgg8l-binutils-wrapper-2.40/nix-support/dynamic-linker' is forbidden in restricted mode
```

So not much I can do right now.

**Comment by why-not-try-calmer** [comment]
`nix-ld` needs `nix develop --impure` as far as I know

**Comment by why-not-try-calmer** [comment]
> Looks like the module that fails is using TemplateHaskell: https://github.com/why-not-try-calmer/feedo/blob/master/src/TgramInJson.hs
> 
> Likely related, potentially a distribution issue. I remember some issues about TemplateHaskell with static vs dynamic linking.

It builds fine with the flake shared above though.

**Comment by fendor** [comment]
Even with `nix develop --impure`, I get dozens of 
```
zlib                         > Error: Cabal-simple_9p6GVs8J_3.8.1.0_ghc-9.4.8: Missing dependency on a  
zlib                         > foreign library:                                                         
zlib                         > * Missing (or bad) header file: zlib.h                                   
zlib                         > * Missing (or bad) C library: z      
``

**Comment by why-not-try-calmer** [comment]
And they say nix is reproducible...
How about removing the `nix-ld` setup, does it build?
```nix
{
  inputs = {
    nixpkgs.url = "https://github.com/NixOS/nixpkgs/archive/54aac082a4d9.tar.gz";
    flake-utils.url = "github:numtide/flake-utils";
  };
  outputs = { self, nixpkgs, flake-utils }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        pkgs = nixpkgs.legacyPackages.${system};
        build_tools = [
          pkgs.stack
          pkgs.ghc
        ];
        dev_tools = [
          pkgs.haskell-language-server
          pkgs.haskellPackages.fourmolu
          pkgs.haskellPackages.hoogle
        ];
      in
      {
        devShell = pkgs.mkShell {
          buildInputs = [
            build_tools
            dev_tools
          ];
        };
      }
    );
}
```
