### ISSUE TITLE
Period in comment has autocomplete options.

### ISSUE THREAD

**Issue by ilostthegame** [haskell/haskell-language-server#4378]
On MacOS. Only a minor but annoying bug.

Within a comment, the haskell extension provides autocomplete options for a period.

To reproduce, just create a comment, and type a word and a period after that, for example:
`-- a.`
Then the autocomplete options for . shows up in intellisense

I'm not sure if this is a problem with the extension or with HLS.

Here's an image of the issue.
<img width="492" alt="Screen Shot 2024-08-09 at 7 22 45 pm" src="https://github.com/user-attachments/assets/b01ce33c-1854-4064-bab4-d78bd980daff">

**Comment by fendor** [comment]
Hi, thank you for the bug report!

I am moving this to the main repo which is responsible for the completions.

I can reproduce the behaviour and was annoyed at times as well...  But sometimes it was useful being able to get function name autocompletion in the comments.

**Comment by Anrock** [comment]
Dup? https://github.com/haskell/haskell-language-server/issues/3370

**Comment by fendor** [comment]
Thanks! Closing this as a duplicate, feel free to continue the discussion #3370
