### ISSUE TITLE
Code action: switch to record syntax

### ISSUE THREAD

**Issue by guibou** [haskell/haskell-language-server#4391]
## Is your enhancement request related to a problem? Please describe.

My codebase is full of pieces of record that are constructed using "function" syntax. Something such as:

```haskell
data Foo = Foo {
   count :: Int,
   name :: String
}

boz = Foo 10 "hello"
```

## Describe the solution you'd like

I would like a code action available on `Foo` in `boz` which expand the syntax to record field syntax. Said otherwise, after usage, I would like:

```haskell
boz = Foo 10 "hello"
```

to become:

```haskell
boz = Foo { count = 10, name = "hello" }
```

## Additional context

This can also be extended to other cases where record are used in "function" form, example for pattern matching:

```haskell
biz (Foo a b) = ...
```

Could be turned to:

```haskell
biz (Foo {count = a, name = b}
```

If you are interested and if the initial design is ok, I can give a try to the implementation.

**Comment by michaelpj** [comment]
Definitely desirable!

I think this would be nice if it was done in combination with https://github.com/haskell/haskell-language-server/issues/4212, since it should be mostly the same code?
