### ISSUE TITLE
Syntax hightlight break when typing some type signature

### ISSUE THREAD

**Issue by foxmean** [haskell/haskell-language-server#4396]
### My environment

Which OS do you use?: MacOS Sonoma 14.6.1, MacBook Air M1 2020

Which version of GHC do you use and how did you install it?: GHC 9.10.1 from GHCup

Which LSP client (editor/plugin) do you use?: Helix 24.7 (079f5442) & Zed 0.151.1. All of them was installed with Homebrew 4.3.19-40-g9659b57.

Which version of HLS do you use and how did you install it?: HLS 2.9.0.1 from GHCup.

Have you configured HLS in any way (especially: a `hie.yaml` file)?: I only use default setting without config anything

### Steps to reproduce
1. Type some type signature such as in the video below and the syntax highlight would break. It is semi-inconsistent. I mostly encounter with ad-hoc polymorphism or parametric polymorphism but it is not always happen. (Mostly with '=>' or '->') [![asciicast](https://asciinema.org/a/1DoAM5Xz6NrvQ0BPLblBmWWry.svg)](https://asciinema.org/a/1DoAM5Xz6NrvQ0BPLblBmWWry) 

https://github.com/user-attachments/assets/bb4a4baf-56a9-4048-a02f-cff86300edde

2. The syntax highlighting is always solvable by just close & reopen the file with any of editors I use.

ref: https://github.com/helix-editor/helix/issues/11517

**Comment by fendor** [comment]
If you did not configure HLS in any way, then I presume you don't have semantic highlighting enabled in HLS?

If that's not the case, then the syntax highlighting is not provided by HLS but Helix, as such there is nothing we can do to fix this.

**Comment by foxmean** [comment]
Thank you for your reply. So, should I try [Semantic highlighting](https://discourse.haskell.org/t/semantic-highlighting-in-haskell-language-server/8760) or better waiting for stable release?

**Comment by fendor** [comment]
Sure, give it a try! However, it is experimental, so expect bugs :) Also, I don't know whether helix has support for semantic highlighting.

Closing as "not our fault (this time)". Feel free to ask more questions or open more issues :)

**Comment by foxmean** [comment]
Just for reference, in case someone search for this issue: Helix [won't support semantic highlighting](https://github.com/helix-editor/helix/pull/6102#issuecomment-1737676445) for foreseeable future.
