### ISSUE TITLE
Show "Add dependency" Code Action only if there is no `package.yaml` file

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-language-server#4400]
If the project is a stack project, there might be a `package.yaml` file. Adding a dependency to the generated .cabal file is a bad idea, as it will lead to annoying behaviour: Stack will no longer re-generate the .cabal file, so changes to `package.yaml` are not propagated to the `.cabal` file any more.

solution:

When looking for the `.cabal` file in the filesystem, check there is no `package.yaml` file next to it.

**Comment by AureliaSnd** [comment]
We are trying to work on this issue.

**Comment by fendor** [comment]
Closed by #4422
