### ISSUE TITLE
Identify the version built with cabal

### ISSUE THREAD

**Issue by teto** [haskell/haskell-language-server#444]
When building from master (with bazel), I get the following output
```
bazel run @hls-exe//haskell-language-server -- --version
INFO: Invocation ID: fb19e081-f4d8-4423-ad90-e3d2a3f92ac8
INFO: Analyzed target @hls-exe//haskell-language-server:haskell-language-server (2 packages loaded, 8669 targets configured).
INFO: Found 1 target...
Target @hls//:_haskell-language-server_exe_haskell-language-server up-to-date:
  bazel-bin/external/hls/haskell-language-server-0.4.0.0/_install/bin/haskell-language-server
INFO: Elapsed time: 10.631s, Critical Path: 0.09s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
haskell-language-server version: 0.4.0.0 (GHC: 8.8.3) (PATH: /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/execroot/toplevel_workspace/bazel-out/k8-fastbuild/bin/external/hls/haskell-language-server-0.4.0.0/_install/bin/haskell-language-server)
```
it still prints 0.4.0.0 as a version (as the current .cabal on master). It would be nice to bump the version after a release so that one knows from `--version` if he runs a development version or not.

**Comment by alanz** [comment]
I would like to see the commit in the version, but I think that is complicated when installing via cabal.

**Comment by jneira** [comment]
Yeah, gitrev does not work with `cabal v2-install`: https://github.com/acfoltzer/gitrev/issues/23
I think there is a workaround involvinf enn vars, maybe we can try to include it in the install script

**Comment by teto** [comment]
having a commit would be the best but even having it echo RELEASE + 1 (aka 0.5.0.0) would be enough to let me know I am on the next release.

**Comment by alanz** [comment]
@teto That makes sense.  Perhaps we should move onto one of those odd-even schemes, so immediately after we tag a release we bump the version number. So so be clear

Release 0.5.0.0
Make 0.6.0.0 (dev) (for a month roughly)
Release Release 0.7.0.0
Make 0.8.0.0 

and so on

**Comment by jneira** [comment]
Mmm, i am not wrong i will swear hls binaries from releases has the commit in the version, not sure why 😄 

```
PS D:\dev\ws\haskell\ghcup-hs> D:\ghcup\bin\haskell-language-server-8.10.2.exe --version
haskell-language-server version: 1.2.0.0 (GHC: 8.10.2) (PATH: D:\ghcup\bin\haskell-language-server-8.10.2~1.2.0.exe) (GIT hash: be2071e985cb417f984ab00a1aad76dee02d6d0b)
```
