### ISSUE TITLE
stylish-haskell plugin fails to data declaration that is correctly parsed by GHC

### ISSUE THREAD

**Issue by andremarianiello** [haskell/haskell-language-server#4466]
### Your environment

Which OS do you use?
Linux (WSL2)

Which version of GHC do you use and how did you install it?
9.8.2 (ghcup) (also happened in 9.6.6)

How is your project built (alternative: link to the project)?
ghc (no stack or cabal needed to reproduce)

Which LSP client (editor/plugin) do you use?
neovim native client + lsp-config

Which version of HLS do you use and how did you install it?
2.9.0.0 (ghcup)

Have you configured HLS in any way (especially: a `hie.yaml` file)?
no hie.yaml, but I did make stylish-haskell the default formatting plugin

### Steps to reproduce
Format 
`Main.hs`:
```haskell
main = pure ()

data MyRecord = MyRecord
  { ab :: Int
  , c:: Int
  }
```
with the stylish-haskell plugin.

Important pieces here:
* `c:: Int`  <- no space between field name and `::`. This makes the formatting fail.
* `ab` field name is longer than `c` field name. This makes the error show up in the LSP log. If the fields are the same length no error appears, but the formatting still fails to apply. Weird!

### Expected behaviour

Since this code compiles with `ghc Main.hs` and is correctly formatted with `stylish-haskell Main.hs`, I would expect the stylish-haskell plugin to format this code the same way

### Actual behaviour
The stylish-haskell plugin prints in the LSP logs
```
stylish-haskell: Internal Error: stylishHaskellCmd: /root/tmp/Main.hs: <string>:5:6: error: [GHC-58481] parse error on input `:'
```

### Debug information
I don't think there is anything else

**Comment by fendor** [comment]
Hi, thank you for the bug report!

Rather puzzling!

Maybe it is related to the version of stylish-haskell the plugin is using?
Your example crashes for me on the cli as well:
```
> stylish-haskell --version
stylish-haskell 0.14.5.0
> stylish-haskell A.hs
A.hs: <string>:3:6: error: [GHC-58481] parse error on input `:'
```

**Comment by andremarianiello** [comment]
Good catch! Same with `0.14.6.0` for me. I will report this upstream. Should this ticket me closed?
