### ISSUE TITLE
On workspace/didChangeConfiguration HLS refetches configuration _again_ with workspace/configuration

### ISSUE THREAD

**Issue by andremarianiello** [haskell/haskell-language-server#4469]
### Your environment

Which OS do you use?
Linux (WSL2)

Which version of GHC do you use and how did you install it?
9.10.1

How is your project built (alternative: link to the project)?
<no repro project, but let me know if that is a problem>

Which LSP client (editor/plugin) do you use?
neovim built-in client + nvim-lspconfig

Which version of HLS do you use and how did you install it?
Compiled and installed from master branch with ghcup. Not sure how to get the exact commit, but it was the tip of master within the last couple days.

Have you configured HLS in any way (especially: a `hie.yaml` file)?
No hie.yaml. Just client configuration from nvim-lspconfig

### Steps to reproduce
* Open a haskell file
* Start hls with neovim. I use the config from nvim-lspconfig to do this automatically but that isn't necessary
* Send a workspace/didChangeConfiguration notification with neovim, containing a change. In my case I want to change the default formatter
* Do something that relies on the updated configuration. In my case I tried formatting the file. The file will be formatted according to the original configuration, not the updated one.

### Expected behaviour

I expect workspace/didChangeConfiguration notifications to result in a changed configuration

### Actual behaviour

workspace/didChangeConfiguration notifications appear up update the servers knowledge of the client configuration

```
'2024-12-22T17:39:14.695968Z | Debug | LSP: set new config: { "formattingProvider": "stylish-haskell" }\n'
"2024-12-22T17:39:14.696527Z | Debug | Finished build session\nAsyncCancelled\n" 
'2024-12-22T17:39:14.696556Z | Debug | Configuration changed: Config {checkParents = CheckOnSave, checkProject = True, formattingProvider = "stylish-haskell", cabalFormattingProvider = "cabalfmt", maxCompletions = 40, sessionLoading = PreferSingleComponentLoading, plugins = fromList [(PluginId "semanticTokens",PluginConfig {plcGlobalOn = True, plcCallHierarchyOn = True, plcCodeActionsOn = True, plcCodeLensOn = True, plcInlayHintsOn = True, plcDiagnosticsOn = True, plcHoverOn = True, plcSymbolsOn = True, plcCompletionOn = True, plcRenameOn = True, plcSelectionRangeOn = True, plcFoldingRangeOn = True, plcSemanticTokensOn = True, plcConfig = fromList []})]}\n'
```
This causes the entire build session to restart
```
"2024-12-22T17:39:14.696806Z | Debug | Restarting build session due to config change\nAction Queue: []\nKeys: [GetClientSettings; ]\nAborting previous build session took 0.00s \n"
```
Which apparently causes hls to refetch the client configuration again
```
'2024-12-22T18:01:12.912034Z | Debug | LSP: set new config: {\n  "cabalFormattingProvider": "cabalfmt",\n  "formattingProvider": "ormolu",\n  "plugin": { "semanticTokens": { "globalOn": true } }\n'          [ERROR][2024-12-22 13:01:12] .../vim/lsp/rpc.lua:734    "rpc"   "/root/.ghcup/bin/haskell-language-server-wrapper"   "stderr"        "}\n"
"2024-12-22T18:01:12.912839Z | Debug | Finished build session\nAsyncCancelled\n"
'2024-12-22T18:01:12.912927Z | Debug | Configuration changed: Config {checkParents = CheckOnSave, checkProject = True, formattingProvider = "ormolu", cabalFormattingProvider = "cabalfmt", maxCompletions = 40, sessionLoading = PreferSingleComponentLoading, plugins = fromList [(PluginId "semanticTokens",PluginConfig {plcGlobalOn = True, plcCallHierarchyOn = True, plcCodeActionsOn = True, plcCodeLensOn = True, plcInlayHintsOn = True, plcDiagnosticsOn = True, plcHoverOn = True, plcSymbolsOn = True, plcCompletionOn = True, plcRenameOn = True, plcSelectionRangeOn = True, plcFoldingRangeOn = True, plcSemanticTokensOn = True, plcConfig = fromList []})]}\n'
```

which essentially undoes the change made with `workspace/didChangeConfiguration`

I believe this is happening because the nvim lsp client is statically configured with an initial configuration that is always returned when the server requests it with `workspace/configuration`. The client supports sending updates to the server via `workspace/didChangeConfiguration` notifications, but this only updates the configuration on the server side. This notification has no effect on the statically defined initial configuration on the client side, so when the client receives another `workspace/configuration` request, the response overwrites the configuration sent by the `workspace/didChanceConfiguration` notification, and we are back to where we started.

There is a good argument to be made that neovim's behavior of not remembering the last configuration sent with didChangeConfuration is wrong, and I think I agree with that. However, I do think that HLS's behavior in this situation, if not "wrong", is at least inefficient. AFAIK, LSP does not dictate that you refetch configuration on receiving a didChangeConfiguration notification, but I am definitely not an LSP expert, so I an uninformed when it comes to best practice here. I'm happy to let someone else weigh in on this.

I noticed this problem because my configuration updates weren't working, but ultimately I think the only thing HLS might be doing wrong is inefficiently rerequesting configuration from the client more times than necessary. I mainly think neovim's behavior should also be adjusted to better handle the more modern pull-base configuration paradigm, so I will make an issue over there as well and link them together.

**Comment by fendor** [comment]
Hi, thank you for bug report!

I am not too familiar with the details, but I *think* we implemented the behaviour you are describing intentionally for compatibility with VSCode, but I am not sure.

cc @michaelpj who is our LSP whisprer

**Comment by michaelpj** [comment]
Yes, I think nvim is wrong here. The situation is a mess, but AFAIK we are doing the right thing here: `workspace/configuration` should be canonical if supported, and then `workspace/didChangeComfiguration` is just there to notify that things changed. 

_Certainly_ if the client says it supports `workspace/configuration` then the server should be able to assume that calling that gets the right configuration.

**Comment by michaelpj** [comment]
(If you don't want that, then don't say you support `workspace/configuration`! Then we will rely on the contents of `workspace/didChangeConfiguration`).

**Comment by andremarianiello** [comment]
I did realize that disabling the `workspace.configuration` capability makes everything work as intended, but it seems hacky. Hopefully we can get change on the neovim side of things. I'll close this! Hopefully it at least serves to help other people with the same issue
