### ISSUE TITLE
HSL exits with exit code 0

### ISSUE THREAD

**Issue by orest58008** [haskell/haskell-language-server#4474]
### Which OS do you use?
NixOS 24.11.710905.a0f3e10d9435 (Vicuna)
### Which version of GHC do you use and how did you install it?
The Glorious Glasgow Haskell Compilation System, version 9.6.6
### How is your project built (alternative: link to the project)?
cabal-install version 3.12.1.0
compiled using version 3.12.1.0 of the Cabal library

### Which LSP client (editor/plugin) do you use?
emacs+lsp-mode
### Which version of HLS do you use and how did you install it?
haskell-language-server version: 2.9.0.0 (GHC: 9.6.6) (PATH: /nix/store/6bwnb2ds0sz7wd2nlccgkkwjip2fv1lh-haskell-language-server-2.9.0.0/bin/haskell-language-server-wrapper)

## Steps to reproduce
1. launch `haskell-language-server-wrapper`

## Expected behaviour
HSL working

## Actual behaviour
HSL exits with $? 0

## Debug information
https://pastebin.com/eZsxJ0Vp

**Comment by orest58008** [comment]
Stranglely, doesn't exit like this with emacs-lsp/lsp-haskell, but does with

```elisp
(require 'lsp-mode)
(lsp-register-client (make-lsp-client ; enable haskell-language-server without lsp-haskell
                     :new-connection (lsp-stdio-connection "haskell-language-server-wrapper")
                     :activation-fn  (lsp-activate-on "haskell")
                     :server-id 'haskell-language-server))

```

**Comment by fendor** [comment]
Hi, thank you for the bug report!
To launch HLS in lsp mode, you need to pass `--lsp`, e.g. `haskell-language-server-wrapper --lsp`. 

Without it, HLS runs in test mode and tries to compile all files it can find in the current directory, reports the results, and then exits, just like you observed!

Hope that answes the question, feel free to ask more or reopen if you feel like this doesn't solve your issue!
