### ISSUE TITLE
2020-09 monthly release

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-language-server#449]
By our monthly cadence we should be aiming to get a release out by the weekend sometime.

What must we wait for before doing it?

I am happy to do it as a non-hackage one, it is more about getting something tagged that we are all comfortable with, given the number of downstreams that package it now

**Comment by fendor** [comment]
I have nothing we need to wait for.

We definitely should have a tagged release for ghcup/vscode, regardless of hackage.

BTW, what generates the artifacts on the release page? Is it automatic or manual? We must not forget to add tar archives for all supported HLS versions per platform for ghcup, see https://github.com/haskell/haskell-language-server/issues/239#issuecomment-695810253.

**Comment by jneira** [comment]
> what generates the artifacts on the release page? Is it automatic or manual? 

automatic with github actions triggered by the release

**Comment by fendor** [comment]
Then we need to add this artifact as well

**Comment by bubba** [comment]
We can/should probably automate this. I think we can create another GitHub job to run after all the build jobs are done, download the linux/macOS binaries and tar them?

**Comment by alanz** [comment]
@bubba I was thinking about it, we need to get the whole process automated, there are now so many pieces to be coordinated.

**Comment by bubba** [comment]
I think we should be able to use https://github.com/actions/download-artifact for this. Giving it a shot now

**Comment by alanz** [comment]
See https://github.com/haskell/haskell-language-server/issues/444#issuecomment-702888693

**Comment by jneira** [comment]
@bubba i would mention the new implicit cradle in the release, cause it theoretically could break some setups.

**Comment by bubba** [comment]
@jneira updated the release notes to mention it here https://github.com/haskell/haskell-language-server/releases/tag/0.5.0, does this seem good?

**Comment by jneira** [comment]
@bubba 👍 , btw great work with the release

**Comment by bubba** [comment]
0.5.0 has been released
