### ISSUE TITLE
Module not found with custom hie.yaml and bazel

### ISSUE THREAD

**Issue by teto** [haskell/haskell-language-server#453]
### Subject of the issue
When opening files with atom/vscode, I have `Module not found` errors. I use a multicradle with a per-subfolder cradle similar to this one: https://github.com/mpickering/hie-bios/issues/250#issuecomment-696223578 , i.e., I have a list of flags in a file on a per-cradle basis. aka (.tmp/subfolder2.flags for the cradle matching path "./subproject2")
If I open file/module A and vscode+hls says file/module B missing. If I run `hie-bios check A`, it returns 0 with no output (which I assume mean my flags are good and thus contradicts vscode output). the path to B appears in `hie-bios flags A`.
Now if I open B, the error about the missing B disappears :s

### Your environment
* Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`
  * This command is available since version `>= 0.4.0.0`
```
My version of hls is 5729c2ea119e9d48c136cc75c377d41fec811dde (recent).
haskell-language-server version: 0.4.0.0 (GHC: 8.8.3) (PATH: /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/execroot/toplevel_workspace/bazel-out/k8-fastbuild/bin/external/hls/haskell-language-server-0.4.0.0/_install/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:		Not found
stack:		2.3.1
ghc:		8.8.3
```
* Which lsp-client do you use: atom/vscode (possibly neovim)
* Describe your project (alternative: link to the project): Closed source and we  use bazel so no cabal/stack
* Contents of `hie.yaml`: akin to https://github.com/mpickering/hie-bios/issues/250#issuecomment-696223578 

### Steps to reproduce
can't share the code sry :'(

### Expected behaviour
No error about missing module

### Actual behaviour
Error about missing module

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:
So I can't paste all the logs but here is an excerpt. Because I use bazel to build we don't have .cabal files and also my hie.yaml ignores all the files in bazel-out/ (where haskell packages can be stored) which points at my /home/teto/.cache/bazel/_bazel_teto/
<details>
<summary>
Debug output:
</summary>

```
Hidden:   no
Range:    13:17-13:36
Source:   not found
Severity: DsError
Message: 
  Could not find module ‘Options.Applicative’
  It is not a module in the current program, or in any known package.
[INFO] Consulting the cradle for "/home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/execroot/toplevel_workspace/bazel-out/k8-fastbuild/bin/simwork/examples/DummDiff@scenarized_Main.hs"
NotShowMessage (NotificationMessage {_jsonrpc = "2.0", _method = WindowShowMessage, _params = ShowMessageParams {_xtype = MtWarning, _message = "No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/execroot/toplevel_workspace/bazel-out/k8-fastbuild/bin/simwork/examples/DummDiff@scenarized_Main.hs.\n Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie)"}})
Output from setting up the cradle Cradle {cradleRootDir = "/home/teto/nova/jinko", cradleOptsProg = CradleAction: Default}
```
</details>

Paste the logs from the lsp-client, e.g. for [VS Code](https://github.com/haskell/vscode-haskell#troubleshooting)

<details>
<summary>
LSP logs:
</summary>

```
2020-10-02 17:17:38.469240769 [ThreadId 7] - <--2--{"jsonrpc":"2.0","params":{"uri":"file:///home/teto/nova/jinko/simwork/jinquantities/library/Data/Quantities/Convert.hs","diagnostics":[{"sev
erity":1,"range":{"start":{"line":12,"character":22},"end":{"line":12,"character":50}},"source":"not found","message":"Could not find module ‘Data.Quantities.Constructors’\nIt is not a module 
in the current program, or in any known package."}]},"method":"textDocument/publishDiagnostics
```
</details>

**Comment by fendor** [comment]
```
Output from setting up the cradle Cradle {cradleRootDir = "/home/teto/nova/jinko", cradleOptsProg = CradleAction: Default}
```
This seems unlikely to be correct. It should almost definitely not be a `Default` cradle. Is the cradle root correct?

**Comment by teto** [comment]
thanks for always taking the time to answer my issues.
The cradle root is correct. Inside this root /home/teto/nova/jinko, there is a symlink /home/teto/nova/jinko/bazel-bin that points at home/teto/.cache/bazel/_bazel_teto/. As in my hie.yaml I have an entry `path: ./. => cradle: none` I think /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/execroot/toplevel_workspace/bazel-out/k8-fastbuild/bin/simwork/examples/DummDiff@scenarized_Main.hs should be covered by a none cradle ? Also  /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/execroot/toplevel_workspace/bazel-out/k8-fastbuild/bin/simwork/examples/DummDiff@scenarized_Main.hs may be loaded because I reference this very file as a bios flag in another cradle .

 Not sure what "default" means there (implicit ?)

**Comment by fendor** [comment]
Late answer (but better late than never I assume):

Easiest way to check is to use `hie-bios debug <filepath>` and look at the output.

> Not sure what "default" means there (implicit ?)

Default means basically: use straight "ghc" with no further options. With current changes to ghcide, this basically means, don't do anything, as we don't discover targets implicitly.

**Comment by jneira** [comment]
@teto do you continue having this issue or did you find any workaround? From the comments i guess it should work with the correct explicit `hie.yaml`file

**Comment by teto** [comment]
I've managed to squash some of the issues: explnation at https://github.com/mpickering/hie-bios/issues/275.

Some other errors elude me but I think I can create more specific issues
