### ISSUE TITLE
Add missing definition code action

### ISSUE THREAD

**Issue by 1Computer1** [haskell/haskell-language-server#458]
It would be really neat to have a code action to add missing definitions. One would hover over the diagnostic, and it would give an option to add definitions for type signatures (top-level, where clauses, let-bindings, etc.). For instance declarations, it would give an option to add all required methods or a specific method from the class. This would make development super comfy alongside the tactics plugin (introducing lambdas, case splitting, and filling in holes).

```hs
-- Before
foo :: Int
bar :: Int -> Int
instance Semigroup Baz where
instance Monoid Baz where

-- After
foo :: Int
foo = _
bar :: Int -> Int
bar x = _
instance Semigroup Baz where
  x <> y = _
instance Monoid Baz where
  mempty = _
```

**Comment by jneira** [comment]
The instance class implementation seems to be specially useful. I wonder if the tactic plugin could fill even more (without user input) so i would tag this with it just in case.

**Comment by isovector** [comment]
Producing the definitions is outside of the forseeable scope for tactics (we're really only set up to produce `HsExpr`s, and this is a hard constraint to change.)

**Comment by jneira** [comment]
Mmmm we still dont have this feature?

**Comment by peterwicksstringfield** [comment]
FYI: I have implemented this. Right now I put it in its own plugin, with a lot of code borrowed from ghcide/CodeActions and hls-class-plugin. Needs some clean up, but I hope to open a PR this week.

**Comment by pepeiborra** [comment]
Doesn't the class plugin already provide some parts of this? IIUC it generates all the missing definitions for an instance

**Comment by jneira** [comment]
@pepeiborra is right, i get class instances "placeholders" thanks to class pluginm the quick fix is named "Add placeholders for ${typeclassMethod}` and it makes in my end

```haskell
newtype ExampleText2 = ExampleText Text

instance Semigroup ExampleText2 where
instance Monoid ExampleText2 where
```

go to

```haskell
instance Semigroup ExampleText2 where
  (<>) = _
instance Monoid ExampleText2 where
  mempty = _
```

@1Computer1 feel free to reopen if it does not work for you
