### ISSUE TITLE
Change pull request to require an approval to be merged

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#465]
* As it is already done in ghcide

@alanz do you have the needed permissions to change that?

**Comment by alanz** [comment]
I have ticked just the first box:

![image](https://user-images.githubusercontent.com/409607/95052190-6a43b900-06e6-11eb-8f7a-5fab7f231582.png)

**Comment by jneira** [comment]
many thanks @alanz i already had to ask you a review to merge :smile:
