### ISSUE TITLE
Looking for .stack in /build fails

### ISSUE THREAD

**Issue by andreas-ebot7** [haskell/haskell-language-server#47]
Hi, great work. Wanted to give it a try and ran the `haskell-language-server` in a project (with and without `hie.yaml`). It failed because its expecting the `.stack` folder in `/build`. It's located in the directory itself. Am I doing something wrong? Wanted to provide this as feedback. Feel free to close if expected.

```
haskell-language-server
ghcide version: 0.1.0.0 (GHC: 8.6.5) (PATH: /home/andreas/bin/haskell-language-server) (GIT hash: 80bc2e8fac470330479c9e2e2222ebf5a687b95f)
(haskell-language-server)Ghcide setup tester in /home/andreas/dev/ebot7/conversational-engine.
Report bugs at https://github.com/haskell/haskell-language-server/issues

Step 1/6: Finding files to test in /home/andreas/dev/ebot7/conversational-engine
Found 35 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Implicit cradle for /home/andreas/dev/ebot7/conversational-engine
Cradle {cradleRootDir = "/home/andreas/dev/ebot7/conversational-engine", cradleOptsProg = CradleAction: Stack}

Step 4/6, Cradle 1/1: Loading GHC Session
haskell-language-server: /build/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/lib/ghc-8.6.5/settings: openFile: does not exist (No such file or directory)
```

**Comment by alanz** [comment]
Great to hear you are trying this. Quite frankly, it is not really in a usable state at the moment.

**Comment by jneira** [comment]
@andreas-ebot7 That is a really weird error message: can you build the project with stack? what is the output of run `stack path --compiler-bin` in the `haskell-language-server` dir?

**Comment by andreas-ebot7** [comment]
@alanz Glad to hear. I'll keep an eye open until it's ready to be tested.
@jneira I installed it as binary for arch. See https://github.com/haskell/haskell-ide-engine/issues/1068#issuecomment-583738370 Maybe that's related to the issue.

**Comment by jneira** [comment]
@andreas-ebot7 
> I installed it as binary for arch
The comment is about haskell-ide-engine binaries (no haskell-language-server), did you want to mean you installed ghc using arc package manager?
Afaiu the error is caused haskell-language-server is looking for your ghc installation in the wrong place. As you are using stack, that should download ghc in a sandbox location i think run `stack build` to check if `stack` works standalone and `stack path --compiler-bin` to show where stack is looking for ghc could help to diagnose the error.

**Comment by andreas-ebot7** [comment]
> The comment is about haskell-ide-engine binaries (no haskell-language-server), did you want to mean you installed ghc using arch package manager?

https://repo.archlinuxcn.org/x86_64/
https://repo.archlinuxcn.org/x86_64/haskell-language-server-git-r77.80bc2e8-1-x86_64.pkg.tar.zst
It is, but the repository contains also binaries for `haskell-language-server`.
![image](https://user-images.githubusercontent.com/59447501/75054340-2db6aa80-54d3-11ea-9ff0-82b240d2967f.png)

You intially asked for `stack` output in the **`haskell-language-server` dir**, which confused me because I didn't clone the repo and compile it myself.

`stack path --compiler-bin` in a haskell project prints a path located in my user home. The binary was looking for `/build/..`. Maybe a directory existing when at the compile time of the binary.

```
stack path --compiler-bin
/home/andreas/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/bin
```

So I tend to not spending much time digging into the issue, because it could be caused by the way the binary was compiled on another system. Thanks for your answers.

**Comment by andreas-ebot7** [comment]
I don't see this error when compiling the language server myself :) Therefore I'm happy to close the issue.

```
Step 1/6: Finding files to test in /home/andreas/dev/ebot7/conversational-engine
Found 34 files

Step 2/6: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/6, Cradle 1/1: Loading /home/andreas/dev/ebot7/conversational-engine/hie.yaml

Step 4/6, Cradle 1/1: Loading GHC Session

Step 5/6: Initializing the IDE

Step 6/6: Type checking the files

Completed (34 files worked, 0 files failed)
```

**Comment by jneira** [comment]
Great! thanks for trying it and report the issue, it could help a lot in this early stage of development.
