### ISSUE TITLE
Is it time to archive haskell-ide-engine?

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-language-server#473]
It seems there are still people using hie, which is fine. But they are occasionally filing bug reports or even PRs, which we are no longer interested in dealing with.

It will send a clearer message if we mark it as archived in github.

**Comment by ndmitchell** [comment]
Everyone seems to be in agreement with thumbs up, so go for it!

**Comment by alanz** [comment]
![image](https://user-images.githubusercontent.com/409607/95362444-ffe96f00-08c5-11eb-9760-706a0411dd28.png)

Here we go

**Comment by alanz** [comment]
For posterity

![image](https://user-images.githubusercontent.com/409607/95362637-45a63780-08c6-11eb-8864-dc896f17b678.png)

Makes me feel  bit funny, to be honest.

**Comment by alanz** [comment]
And I think we can probably take the first line of the README out now too

> Integration point for ghcide and haskell-ide-engine. One IDE to rule them all. Read the project's background.
