### ISSUE TITLE
Releases source code should include ghcide

### ISSUE THREAD

**Issue by motorto** [haskell/haskell-language-server#484]
Releases source code should include ghcide as well instead of an empty directory. 
The ghcide is simply an empty directory which makes it impossible to build. 
Which makes releases unnecessary (useless)

**Comment by jneira** [comment]
Yeah, build config files point to the dir (so they dont use ghcide from hackage) but there is no content.

**Comment by bubba** [comment]
@jneira they are automatically uploaded by GitHub for all releases, i.e it's not something that we do ourselves. That is weird that they don't clone the submodules first before generating them. Someone else must have run into this issue before

**Comment by motorto** [comment]
Turns out that GitHub api for releases doesn't add the sub-modules to the tarball ( the question is 4y old , don't know if it changed , turns out that not).  

https://stackoverflow.com/questions/34719785/how-to-add-submodule-files-to-a-github-release#34721233

One possible solution would be to maybe create a branch that doesn't use the sub module and that be used to create releases ...

**Comment by jneira** [comment]
There is a issue that has recent comments continuing asking for that feature.
Sync release with ghcide will be inevitable if we want to uploas hls so hackage/stackage but now it let us make releases faster in simple way.
Another alternative will be replace the actual zip/tarball with a custom ones (ideally in the github workflow script)

**Comment by motorto** [comment]
Sync releases would be the easiest solution to this problem , don't know how easy to implement would be.

**Comment by jneira** [comment]
@motorto well, it will be relatively easy but the dev process will be disturbed and will be less agile. 
Now we bump ghcide version at will and we have not wait for ghcide hackage releases.

Maybe they should be in the same repo, as suggested in other issue(s)

**Comment by jneira** [comment]
@motorto it turns out that last hls-0.6.0 works with last ghcide release version, so you should be able to build it without the subrepo.
Not sure if all future releases will be done this way though.

**Comment by jneira** [comment]
@motorto ghcide has been moved to this repo, so source releases will include it
