### ISSUE TITLE
Add documentation on LSP

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haskell-language-server#491]
We seem to have had a few beginners (both on the tracker and to me privately) confused by the LSP. In particular, its a protocol, and each editor implements it separately. That means what completions pop up is "the domain" of HLS, but the key to make them pop up is the editor. I think some more documentation focused on that aspect would be valuable.

Having read the prefix of the readme, I'm not sure it's that beginner friendly. The main questions I want to ask are what is this (it's a Haskell IDE), why might I want to use it (quite featureful), and how do I use it (quite far down the page). I'm not totally sure what it should look like, but I imagine we could do better...

**Comment by ndmitchell** [comment]
See https://github.com/haskell/ghcide/issues/658 for some more information.

**Comment by michaelpj** [comment]
There is a small amount about LSP in the doc that just got merged, but it covers the key concepts at least.
