### ISSUE TITLE
Please, provide wrapper with ability to respect the reproducible Nix envs that projects provide

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell/haskell-language-server#493]
### Subject of the issue

Currently, I am thinking is it right solution that all IDEs are currently required to provide their own custom Nix env loading mechanism and wrapper for the `haskell-language-server-wrapper`, because there is no support of Nix env in the HLS wrapper.

IDK. There is already support and docs of that in most IDEs. But to make a truly clean code refactoring of the ecosystem for the Nix env and NixOS case - they probably need to be accounted into the wrapper, at least as an option key for the wrapper, which maybe/probably needs to use by default on NixOS, as I said - because on NixOS Haskell projects needs to be built in project's Nix env, and if no Nix env provided - NixOS people need to create it by `caba2nix`, because there is no two-way support between NixOS system env & Cabal, shortly: Cabal works only in `nix-shell` on the NixOS, which means always load provided Nix env.

### Your environment
* NixOS

### Steps to reproduce
Download any Haskell project that provides Nix env. How to make HLS use provided reprocucible Nix env without a custom sidecars project?

### Expected behaviour
HSL wrapper to provide an option to load the projects Nix env.

### Actual behaviour
IDEs invent and maintain their own Nix env wrappers to wrap the HLS wrapper into them to load the projects Nix env and start HLS inside it.

**Comment by Anton-Latukha** [comment]
I started spitballing the PR: #490 

Seems simple.

HLS and `ghcid` currently have problems loading HLS project in Nix env, at least HLS `shell.nix` and `ghcid` situation needs to be looked into. Currently, code is in pure draft mode, until something (me on Ubuntu, or utils loading HLS in Nix env) works.

You are free to start your own PR, or add your hacking into the current PR.

**Comment by Anton-Latukha** [comment]
I started spitballing the PR: #490 

Seems simple.

HLS and `ghcid` currently have problems loading HLS project in Nix env, at least HLS `shell.nix` and `ghcid` situation needs to be looked into. Currently, code is in pure draft mode, until something (me on Ubuntu, or utils loading HLS in Nix env) works.

You are free to start your own PR, or add your hacking into the current PR.

**Comment by michaelpj** [comment]
I think this is solved fairly well with `direnv`:
- Use `lorri` or similar to get information from the `nix-shell` to `direnv`
- Use a `direnv` support plugin in your editor (emacs has one, vscode has one) to get the right environment for the server launch.

Best of all, it's completely independent of us.

**Comment by michaelpj** [comment]
I also really don't think this is HLS's problem. We can't expect every executable under the sun to implement Nix support, rather you usually expect the user to set up the environment. And there are tools to help them with that (like `direnv`).

**Comment by fendor** [comment]
I agree, usage with `lorri` works well in my experience.

**Comment by ocharles** [comment]
One more happy `lorri` user. I haven't had to do anything special to get `haskell-language-server` working in any of my projects. I just let Emacs launch it, and use `envrc-mode` to make sure that Emacs respects my Lorri environment.

**Comment by Anton-Latukha** [comment]
I am actually one that forgot about existence of `direnv` configs.

Ok, I'm convinced at this point 8)

Thank you.
