### ISSUE TITLE
Problems with process handling?

### ISSUE THREAD

**Issue by hasufell** [haskell/haskell-language-server#499]
### Subject of the issue

HLS doesn't seem to shut down all processes. After a while of using it in gvim I seem to have multiple HLS processes. This happens very frequently (although only one editor is opened and the by default no server is started). When I tell my client to shut down the server, only one of those processes will exit and `haskell-language-server-wrapper` will always remain active.

This happens with multiple clients:
- coc.nvim
- vim-lsp
- LanguageClient-neovim

To me, it's not clear what the issue is:
1. if HLS is not supposed to spawn multiple processes
  - why does this happen across many clients? Does the server confuse them into thinking it's exited and needs to be respawned?
2. if HLS is supposed to spawn multiple processes
  - then it seems the server doesn't correctly process the `exit` message
3. it could still be all 3 clients are buggy?

### Your environment

```
haskell-language-server version: 0.5.1.0 (GHC: 8.10.1) (PATH: /mnt/sdd2/.ghcup/bin/haskell-language-server-wrapper-0.5.1) (GIT hash: e3fe0e7546aa91e44cc56cfe8ec078a026cf533a)
Tool versions found on the $PATH
cabal:		3.4.0.0
stack:		2.3.3
ghc:		8.8.4
```

* LangugeClient-neovim, vim-lsp, coc.nvim
* happens on any project, e.g. https://github.com/input-output-hk/cardano-wallet or https://gitlab.haskell.org/haskell/ghcup-hs
* hie.yaml generated by `gen-hie`

### Steps to reproduce

Use hls for a while and observe processes, then try to issue an exit message via the client.

### Expected behaviour

All processes exit.

### Actual behaviour

Only one process exits.

### Include debug information

I currently don't have more isolated debug info. I'll try next time it happens.

**Comment by expipiplus1** [comment]
Are you able to reproduce this in coc.nvim using my port of the vscode plugin?

https://github.com/expipiplus1/vscode-hie-server/

It does have some session management functionality (pretty much the only thing it does actually).

I've been using this for a while and have not noticed this (although I haven't looked for it)

**Comment by hasufell** [comment]
> Are you able to reproduce this in coc.nvim using my port of the vscode plugin?

I haven't tried. I try to stay away from coc.

----

Just now I tried to enable hls on ghcup codebase and this is what I got:

![hls-processes-many](https://user-images.githubusercontent.com/1241845/97086886-61c80980-1626-11eb-8874-5467c508d60e.png)

I had to kill everything, because my editor was becoming unresponsive.

**Comment by hasufell** [comment]
![Screenshot_2021-03-01_23-26-46](https://user-images.githubusercontent.com/1241845/109567646-fb785980-7ae5-11eb-9ecd-e4cf892e9dab.png)

With hls-1.0.0 ghc-8.10.4 on ghcup codebase (which is fairly small). This was maybe after an hour of editing.

**Comment by Anton-Latukha** [comment]
How is the status of it now?

**Comment by michaelpj** [comment]
Closing as it's old and hasn't had new reproductions.
