### ISSUE TITLE
Language.Haskell.LSP.Types.Message.RequestMessage the key params was not present

### ISSUE THREAD

**Issue by teto** [haskell/haskell-language-server#501]
If you encounter a bug or you have a support question, please try to fill out some of the information below.
However, if you think your issue does not need any of it, you may omit it.
Generally speaking, the information below is meant for helping debugging issues
but they are no prerequisite for opening issues.

### Subject of the issue
Describe your issue here.

`[ DEBUG ] 2020-10-13T21:20:40+0200 ] ...0zz-neovim-master/share/nvim/runtime/lua/vim/lsp/rpc.lua:462 ]	"decoded"	{  error = {    code = -32603,    message = 'haskell-lsp:parse error. Object (fromList [("jsonrpc",String "2.0"),("method",String "shutdown"),("id",Number 3.0)]) "When parsing the record RequestMessage of type Language.Haskell.LSP.Types.Message.RequestMessage the key params was not present." `stack update` and install new haskell-lsp. Or check information on https://marketplace.visualstudio.com/items?itemName=xxxxxxxxxxxxxxx'  },  id = 3,  jsonrpc = "2.0"}`

### Your environment
* Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`haskell-language-server --probe-tools
```
INFO: Invocation ID: c61d1ded-e638-401a-943d-3afdd6fa3f60
INFO: Build option --compilation_mode has changed, discarding analysis cache.
INFO: Analyzed target @hls-exe//haskell-language-server:haskell-language-server (1 packages loaded, 9568 targets configured).
INFO: Found 1 target...
Target @hls//:_haskell-language-server_exe_haskell-language-server up-to-date:
  bazel-bin/external/hls/haskell-language-server-0.4.0.0/_install/bin/haskell-language-server
INFO: Elapsed time: 0.589s, Critical Path: 0.03s
INFO: 0 processes.
INFO: Build completed successfully, 8 total actions
haskell-language-server version: 0.4.0.0 (GHC: 8.8.3) (PATH: /home/teto/.cache/bazel/_bazel_teto/32070fb26dd3cfe8bd075800f8bb83d1/execroot/toplevel_workspace/bazel-out/k8-opt/bin/external/hls/haskell-language-server-0.4.0.0/_install/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:		Not found
stack:		2.3.1
ghc:		8.8.3
```

* Which lsp-client do you use: Neovim master
* Describe your project (alternative: link to the project): closed source bazel buildsystem
* Contents of `hie.yaml`: generated, multicradle based

### Steps to reproduce
Just open my editor (neovim), nothing happens.

### Include debug information
I can't provide any debug log, it's a complex project and there are many errors but anyway the same issue seems to have existed in hie:
https://github.com/haskell/haskell-ide-engine/issues/983

**Comment by jneira** [comment]
Thanks for the bug report. It would be really useful reproduce it in a alternate open source project.
Otoh could you try another editor to confirm it is neovim specic?

**Comment by bubba** [comment]
This is an issue in alanz/lsp, that request message should be valid since the shutdown request has no params associated with it

**Comment by teto** [comment]
I haen't seen this in a long time. Will close and reopen if I see it again
