### ISSUE TITLE
(steps towards an) Eval plugin

### ISSUE THREAD

**Issue by googleson78** [haskell/haskell-language-server#51]
I would love to be able to highlight some text and say "evaluate this please". I imagine this to be a "plugin".

My hopes are that since (it seems to me that) `ghci` is used, this shouldn't be impossible.

Is this currently feasible, and if yes, where should I look for pointers/documentation on how I would go about trying to implement it?

**Comment by alanz** [comment]
@googleson78 we are not using ghci in hls, only the GHC API.

Having evaluation available is definitely something we want, but is not likely to be available soon.

See also https://github.com/haskell/haskell-ide-engine/issues/1257
