### ISSUE TITLE
How to disable fold/unfold suggestions?

### ISSUE THREAD

**Issue by mrkkrp** [haskell/haskell-language-server#510]
I have noticed that now there are code actions that propose to fold/unfold functions. They do not work and are very annoying. How can I disable this plugin?

Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`

```
haskell-language-server version: 0.4.0.0 (GHC: 8.8.4) (PATH: /nix/store/gif7ck91xlm2kxchbwa87v6gf440b9zf-haskell-language-server-0.4.0.0/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:          3.2.0.0
stack:          2.3.3
ghc:            Not found
```

Editor: emacs with stack.

**Comment by jneira** [comment]
fold/unfold functions comes from the splice plugin?
In any case we can disable plugins per feature and type so adding in the proper lsp config configuration for emacs:

```json
{
    "haskell": {
        "plugin" : {
            "splice" : {
                "codeActionsOn" : false
            }
        }
    }
}
```

You can replace splice with the actual plugin if it is not generating the fold/unfold, all plugins are listed [here](https://github.com/haskell/haskell-language-server/issues/1342#issuecomment-776518880)
A working configuration disabling features in emacss [here](https://github.com/haskell/haskell-language-server/pull/691#issuecomment-749046342)

**Comment by pepeiborra** [comment]
This is actually the retrie plugin, not the splice plugin

**Comment by jneira** [comment]
thanks, correcting my previous comment to set retrie
