### ISSUE TITLE
The type of selected expression

### ISSUE THREAD

**Issue by nartamonov** [haskell/haskell-language-server#514]
Since Haskell is rather expression-heavy language and sometimes expressions in our programs can be complicated, it would be invalueable if this extension allows to select arbitrary expression and show its type. The feature is one of the most demanded and useful in other IDEs for "functional" languages. For example, IntelliJ IDEA (with Scala plugin) can show the type of Scala expression under selection:

![image](https://user-images.githubusercontent.com/1040557/96280756-0f149f00-0fe1-11eb-9ec1-1b1c9cfb080d.png)

Importantly that the showed type above is already inferred and concrete, in contrast to the generic type of `foldLeft` function which we can find out by hovering over function name:

![image](https://user-images.githubusercontent.com/1040557/96281131-93672200-0fe1-11eb-9426-ccf538bece42.png)

That's why "Type information and documentation on hover" (already implemented in extension) does not replace "Type of selected expression" functionality.

I'm novice Haskell programmer and like the language a lot. So I really miss that feature when learning Haskell. I had many years of experience in Scala and use the feature constantly. It helps a lot when you work on real-world projects.

**Comment by alanz** [comment]
I guess someone needs to actually make a PR for https://github.com/microsoft/language-server-protocol/issues/377

**Comment by jneira** [comment]
The linked issue in ghcide was moved [here](https://github.com/haskell/haskell-language-server/issues/709) so i am gonna close this one.
