### ISSUE TITLE
How to auto-format code?

### ISSUE THREAD

**Issue by aryairani** [haskell/haskell-language-server#515]
I have ormolu selected in settings:
![image](https://user-images.githubusercontent.com/538571/90402990-4c56c200-e06e-11ea-99cb-00971b5ed3f8.png)

but when I run the Format Document action:

![image](https://user-images.githubusercontent.com/538571/90403059-5ed0fb80-e06e-11ea-931d-8af3d674f6f8.png)

it doesn't work:

![image](https://user-images.githubusercontent.com/538571/90403025-54166680-e06e-11ea-9d6f-29e7c9b43443.png)

and it suggests I install another extension.  Am I using the wrong action?

**Comment by jneira** [comment]
@aryairani hi, have you the chance to try it out again and provide some info if it does not work?

**Comment by andys8** [comment]
Issue could be renamed. Author confirmed formatting is working with his. Now the topic is about "random errors".

**Comment by jneira** [comment]
@andys8 thanks for the suggestion. As it is a totally different issue i will close this one, @aryairani please open a new one if you continue experiencing those errors
