### ISSUE TITLE
Use ghcide version with last TemplateHaskell improvements 

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#526]
* Using ghcide minimum at https://github.com/haskell/ghcide/commit/71c88dc521b639d20913c98a7e68443c9c8795c1
* It would fix a bunch of issues th related here too.
* It seems it will need some code adjustements (see #463)

**Comment by wz1000** [comment]
Changes in hls should mostly be a matter of playing type-tetris. Maybe the `auto` tactic can do them?

**Comment by jneira** [comment]
I'll give a try if nobody else take it, after merging hlint and include the last implicit-hie fix here

**Comment by jneira** [comment]
pr done
