### ISSUE TITLE
Enable ignored tests: renaming and liquid haskell

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#527]
* Follow up of #5
* Some of them do not have implemented the functionality
* We could change the cause of being ignored to help enable them progresively

**Comment by jneira** [comment]
Thanks to @peterwicksstringfield we have most tests enabled but some of them:
* renaming
* liquid haskell

We should add a checklist here to track them (and not include the ignored ones for concrete unresolved issues)

**Comment by peterwicksstringfield** [comment]
I don't know quite what the tests in functional/Deferred.hs and functional/FunctionalBadProject.hs are supposed to be testing, but those files are in poor condition.

functional/Definition.hs and functional/Reference.hs will need a second look after the hiedb PR #704 gets merged, I'm expecting that many of those tests can be enabled and pass. (I don't think it would be a good idea to try to get these tests into #704. That PR is complex enough as is, and it has its own tests on the ghcide side.)

**Comment by jneira** [comment]
@peterwicksstringfield #704 is already merged, could you have the chance to take a look to mentioned modules? thanks!

**Comment by jneira** [comment]
>     * renaming
> 
>     * liquid haskell
>  

renaming tests are moved to its own plugin and we dont have the liquid plugin yet

**Comment by peterwicksstringfield** [comment]
Merge #2235 and close this ticket? At this point all the ignored or expect failed tests have reasonable reasons, so maybe there is no need for this ticket to track them anymore?
