### ISSUE TITLE
Unable to set language extensions for eval plugin

### ISSUE THREAD

**Issue by expipiplus1** [haskell/haskell-language-server#535]
I would like to set a language extension for use with the eval plugin:

```haskell
-- >>> :set -XQuasiQuotes
-- >>> [e||]
```

However I am told that there is no such command as `set`, similar things happen with the multiline input command too (`:{`)

Adding the extension as a pragma works well, however this extension is otherwise unused and hlint thus complains about it.

Happy to provide all the other stuff in the issue template lazily.

**Comment by pepeiborra** [comment]
PRs welcome! You just need to add the `:set` command to the set of supported commands, shouldn't be too hard, and tests

**Comment by expipiplus1** [comment]
I can put it on my todo queue. After a quick look it would probably involve just copying over https://github.com/ghc/ghc/blob/b352d63cbbfbee69358c198edd876fe7ef9d63ef/ghc/GHCi/UI.hs#L2891-L2951 and the interesting case of https://github.com/ghc/ghc/blob/b352d63cbbfbee69358c198edd876fe7ef9d63ef/ghc/GHCi/UI.hs#L2711-L2742

`setDynFlags` looks sufficiently intimidating to put me off doing this today, as does the idea of just copying code wholesale from GHC. Perhaps someone wiser in GHC knows an alternative.

**Comment by tittoassini** [comment]
this is not fixed @expipiplus1

**Comment by expipiplus1** [comment]
> I meant: this is now fixed @expipiplus1 :-)) !!

hahah, I was worried for a second!
