### ISSUE TITLE
hlint hints tweak suggestion

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-language-server#553]
This is an example of an hlint hint from the emacs log

```json
    {
      "severity": 3,
      "range": {
        "start": {
          "line": 500,
          "character": 0
        },
        "end": {
          "line": 500,
          "character": 50
        }
      },
      "code": "Use camelCase",
      "source": "hlint",
      "message": "/home/alanz/mysrc/git.haskell.org/ghc/compiler/GHC/Parser/PostProcess.hs:501:1-50: Suggestion: Use camelCase\nFound:\n  has_args :: [LMatch GhcPs (LHsExpr GhcPs)] -> Bool\nPerhaps:\n  hasArgs :: [LMatch GhcPs (LHsExpr GhcPs)] -> Bool\n"
    },
```

I think it would be better to remove the full location from the `message` part, as it is already captured in the Range and Uri for the diagnostic.

**Comment by ndmitchell** [comment]
Agreed - I think the right approach is to grab the HLint Idea data type and write our own formatter based on the one in HLint. That ties us quite closely to HLint internals, but I think we are already, so that's not a big deal.

**Comment by alanz** [comment]
I know we were doing something like that in hie, can perhaps just bring the code over.
