### ISSUE TITLE
Is it possible (and sensible) to disable the monomorphism restriction when suggesting type sigs?

### ISSUE THREAD

**Issue by expipiplus1** [haskell/haskell-language-server#558]
Perhaps this is too simply solved by adding the extension pragma to the file, nevertheless I've bumped into a couple of times when writing something where I'd like to add a general sig to it, and HLS suggests the monomorphized version. I've not yet bumped into the converse problem.

An example:

```haskell
(<||>) = liftA2 (||)
```

I'd like HLS to suggest `(<||>) :: Applicative f => f Bool -> f Bool -> f Bool`, however it currently suggests `(<||>) :: (Char -> Bool) -> (Char -> Bool) -> Char -> Bool` or something.

I assume that it would be computationally expensive (and potentially confusing) to juggle language extensions like this, but thought I'd mention anyway, feel free to close with prejudice :)

**Comment by jneira** [comment]
I think in hie we had the two versions, the polymorphic and the monomorphic one, so all info, including being able to compare between them, was there

**Comment by isovector** [comment]
I wonder what would happen here if we just turned on `-XNoMonomorphismRestriction` globally in ghcide.

**Comment by pepeiborra** [comment]
> I wonder what would happen here if we just turned on `-XNoMonomorphismRestriction` globally in ghcide.

Wouldn't that lead to programs that typecheck in the IDE but do not when compiled in the command line?

**Comment by michaelpj** [comment]
We think this is no longer an issue, but not 100% sure.
