### ISSUE TITLE
Tactics plugin cannot derive I from combinators S and K in tagless-final style

### ISSUE THREAD

**Issue by siraben** [haskell/haskell-language-server#562]
Consider
```haskell
class SKIC repr where
  capp :: repr (a -> b) -> repr a -> repr b
  cK :: repr (a -> b -> a)
  cS :: repr ((a -> b -> c) -> (a -> b) -> a -> c)

cI :: SKIC repr => repr (a -> a)
cI = _
```

The tactics plugin fails to fill the hole. One potential solution would be

```haskell
cI = cS `capp` cK `capp` cK
```

This has been tested as of commit 6c14163167e43b064d03fabe14cdbc91ad07c166. I tested to see if this would be the case in the tagless-final HOAS encoding of lambda calculus as well, but it succeeded, i.e.

```haskell
class Lam repr where
  app :: repr (a -> b) -> repr a -> repr b
  lam :: (repr a -> repr b) -> repr (a -> b)

id_ :: Lam repr => repr (a -> a)
id_ = _
```

The plugin generates `(lam (\ x -> x))` as a solution.

**Comment by isovector** [comment]
I think the reason the original one fails to solve is that the `auto` tactic is running out of gas. We limit solutions at depth <= 4 to ensure a speedy search. It's an easy thing to change, but will exponentially slow down the search times:

https://github.com/haskell/haskell-language-server/blob/6c14163167e43b064d03fabe14cdbc91ad07c166/plugins/tactics/src/Ide/Plugin/Tactic/Auto.hs#L25

**Comment by jneira** [comment]
Time to add some plugin specific configuration? Or the slowness is so bad that it is not an option?

**Comment by isovector** [comment]
This turns out to not be an issue of gas at all. What's happening is that Wingman tries each method, and ends up with holes of the form `repr a` for some to-be-unified variable `a`. But this could be anything, and Wingman tries really hard not to make big search spaces, so it opts out. I'm not sure if there's a satisfactory solution to be had here; any approach I can think of that would make this work would make the search space exponentially big for all other problems.

**Comment by Ailrun** [comment]
I also think, as your SKI can represent any 0-th order logic proof, and in general SKI can represent any system that untyped lambda calculus can represent, the search space is too big without any case-specific tactic or exposes tactic language.

**Comment by isovector** [comment]
That sounds like a convincing argument to me. I'd be interested in exposing the tactic language if there were some way to use source-haskell machinery, instead of me needing to write a little language.
