### ISSUE TITLE
Haskell Language Server seems to enter infinite loop with concrete hie.yaml

### ISSUE THREAD

**Issue by jaunruh** [haskell/haskell-language-server#566]
I am trying to make a setup where I use an existing [repo](https://github.com/jgm/pandoc) and add one of its [dependencies](https://github.com/jgm/pandoc-types) to the folder. My goal is changing the source code for both repos together. I also need the _hover documentation_. 

My root folder looks like this:
```
pandoc/
- src/
- pandoc.cabal
- cabal.project
- hie.yaml
- stack.yaml
- [... other stuff from the repo ...] 
- pandoc-types/
-- src/
-- pandoc-types.cabal
-- cabal.project
-- stack.yaml
-- [... other stuff from the repo ...]
```

I have tried to set up the `hie.yaml` file according to the [documentation](https://github.com/mpickering/hie-bios) and using [this](https://github.com/Avi-D-coder/implicit-hie) tool. In both cases the language server keeps restarting 5 times and stops running after that with the following error message: `The Haskell (pandoc_haskell) server crashed 5 times in the last 3 minutes. The server will not be restarted.`

Attach you will find the Log file and the `<>.cabal` file as well as other relevant files.
[haskell-loop.zip](https://github.com/haskell/haskell-language-server/files/5477734/haskell-loop.zip)

Am I doing something wrong or is this a bug?

**02.11.2020 21:14GMT :: EDIT:** (after labels where applied to issue)
When using the `hie.yaml` file from the `.zip` file above. The infinite loop arises. It seems like the `pandoc-types-1.22` repo is downloaded in that case (appears in `./dist-newstyle`). This might either be a bug or an error in my `<>.cabal` file.

But when using the following `hie.yaml` file:
```
cradle:
  stack:
    - path: "./pandoc-types/src"
      component: "pandoc-types:lib"

    - path: "./src"
      component: "pandoc:lib"

    - path: "."
      component: "pandoc:exe:pandoc"
```
The language server seems to start normally (and `pandoc-types-1.22` is not downloaded to `./stack-work`). But _documentation on hover_ still seems to be broken.

**Comment by jneira** [comment]
@jaunruh afaik documentation on hover for all dependencies requires the project to be built with haddock enabled, like we did in this repo itself. Did you miss docs for all definitions or only "external" ones? Could you try to add a similar configuration to your repo to check f it works?

https://github.com/haskell/haskell-language-server/blob/c884ad92dae0962425d7f89b37b59bca31fa1a63/stack-8.10.3.yaml#L18-L19

https://github.com/haskell/haskell-language-server/blob/c884ad92dae0962425d7f89b37b59bca31fa1a63/cabal.project#L23-L24

**Comment by jaunruh** [comment]
> @jaunruh afaik documentation on hover for all dependencies requires the project to be built with haddock enabled, like we did in this repo itself. Did you miss docs for all definitions or only "external" ones? Could you try to add a similar configuration to your repo to check f it works?
> 
> https://github.com/haskell/haskell-language-server/blob/c884ad92dae0962425d7f89b37b59bca31fa1a63/stack-8.10.3.yaml#L18-L19
> 
> https://github.com/haskell/haskell-language-server/blob/c884ad92dae0962425d7f89b37b59bca31fa1a63/cabal.project#L23-L24

I am not entirely sure where to do that when using VS Code running the HLS as a plugin. Could you please let me know where I would edit this?

**Comment by jneira** [comment]
@jaunruh 

> I am not entirely sure where to do that when using VS Code running the HLS as a plugin. Could you please let me know where I would edit this?

Sorry i pasted an example from the haskell-language-server but the idea was you should change your project config files in a similar way (hence `Could you try to add a similar configuration to your repo to check if it works?`).

So you should add 

```
ghc-options:
   "$everything": -haddock
```
in `pandoc/stack.yaml`

and/or 

```
package * 
   ghc-options: -haddock 
```

in `pandoc/cabal.project`

depending on if you are using stack and/or cabal as a build tool

**Comment by jneira** [comment]
@jaunruh did you get the chance to try the last suggestion to get documentation on hover? That was the unique feature not working or you did not get any compiler error or code action?

**Comment by jaunruh** [comment]
I have actually removed the repo locally recently. But since the topic came up again, I will retry this setup soon and I will get back to this thread. It will take a few days tho.

**Comment by jneira** [comment]
i am gonna close this optimistically, @jaunruh feel free to reopen if you continue hitting the issue with a newer hls version
