### ISSUE TITLE
Inserting a constraint context erases the rest of type signature

### ISSUE THREAD

**Issue by googleson78** [haskell/haskell-language-server#569]
HLS version - 
`haskell-language-server version: 0.5.1.0 (GHC: 8.8.4) (PATH: /home/googleson78/.local/bin/haskell-language-server) (GIT hash: d0f02b5e9a100f8a62591170c339cb22888f9897`
LSP client - `LanguageClient-neovim`
GHC version - 8.8.4

Using the `Use type signature` action on this program:
```haskell
what :: _ => Int
what = 5
```
results in
```haskell
what :: (())
what = 5
```
This also happens with non-empty constraints.

**Comment by ChristophHochrainer** [comment]
Cannot reproduce with  `ghc 9.2.4`.
I only get a `add "PartialTypeSignatures"` action which worked for me correctly.

**Comment by fendor** [comment]
Feel free to reopen if we missed something

**Comment by googleson78** [comment]
I get the action as previously described, but it now correctly adds the type signature, so this appears to be fixed. Thanks!
