### ISSUE TITLE
Unused import warnings

### ISSUE THREAD

**Issue by georgefst** [haskell/haskell-language-server#572]
```
$ ./haskell-language-server-0.5.1-linux-8.10.2 --probe-tools
haskell-language-server version: 0.5.1.0 (GHC: 8.10.2) (PATH: /home/gthomas/.config/Code/User/globalStorage/haskell.haskell/haskell-language-server-0.5.1-linux-8.10.2) (GIT hash: e3fe0e7546aa91e44cc56cfe8ec078a026cf533a)
Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		Not found
ghc:		8.10.2
```

```hs
import Data.Functor -- doesn't matter what module this is

main = putStrLn "hi"
```

Standalone file, no warnings enabled. I still get a blue, info-level, message about the unused import. There's seemingly no way to turn this off, and some would regard it as unwanted noise (particularly [this person](https://www.reddit.com/r/haskell/comments/jp60nz/can_anyone_help_me_remove_import_warning_messages/)).

**Comment by ndmitchell** [comment]
I think we generate the info message so we can colour it in gray. Would be best to hide it though...

**Comment by serras** [comment]
As I mentioned in https://github.com/haskell/ghcide/pull/902, the current LSP spec requires each "unused element" to be tied to a diagnostic. That was the original reason for enabling extra warnings, but demoting them if they were not in the set of original ones.

@ndmitchell @jneira I am happy to send a PR to remove the behavior of enabling the "unused X" warnings when the user hadn't requested them. But I only want to do that if you think that should be the correct behavior.

Another choice is to have a middle ground. Maybe we want to always enable "unused variables", but not "unused imports", right now we just do all of them. I think most people would be happy with [`WarnUnusedLocalBinds`](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html#ghc-flag--Wunused-local-binds), [`WarnUnusedMatches`](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html#ghc-flag--Wunused-matches), [`WarnUnusedForalls`](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html#ghc-flag--Wunused-foralls), [`WarnInaccessibleCode`](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html#ghc-flag--Winaccessible-code) and [`WarnWarningsDeprecations`](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/using-warnings.html#ghc-flag--Wwarnings-deprecations) by default. Here's the entire list for reference:

```haskell
unnecessaryDeprecationWarningFlags
  = [ Opt_WarnUnusedTopBinds
    , Opt_WarnUnusedLocalBinds
    , Opt_WarnUnusedPatternBinds
    , Opt_WarnUnusedImports
    , Opt_WarnUnusedMatches
    , Opt_WarnUnusedTypePatterns
    , Opt_WarnUnusedForalls
#if MIN_GHC_API_VERSION(8,10,0)
    , Opt_WarnUnusedRecordWildcards
#endif
    , Opt_WarnInaccessibleCode
    , Opt_WarnWarningsDeprecations
    ]
```

**Comment by jneira** [comment]
@serras thanks for take vare, i like your last proposal as default

> Another choice is to have a middle ground. Maybe we want to always enable "unused variables", but not "unused imports", 

but sure there will be users that might want to remove all of them so

> to remove the behavior of enabling the "unused X" warnings when the user hadn't requested them

seems to be the more generic one

**Comment by serras** [comment]
@jneira unfortunately, since we don't have a way to configure the plug-in, we need to make one choice.

**Comment by jneira** [comment]
mmm in fact I think we could configure it, like we are doing in the hlint plugin but if I had to choose one I would pick the based in user request (we will reuse the ghc config)

**Comment by jneira** [comment]
It seems this was closed by https://github.com/haskell/ghcide/pull/907
Feel free to reopen if that is not the case
