### ISSUE TITLE
HLS 0.5.1 gets stuck in Fedora

### ISSUE THREAD

**Issue by mdimjasevic** [haskell/haskell-language-server#573]
There are issues with running the binary 0.5.1 release of HLS in Fedora 32 and 33, and consequently with integrating it with tools like VSCodium. In particular, it gets stuck when type-checking a project obtained by running:

```
stack new helloworld new-template
```

and making sure it uses Stack's `lts-16.20` as a resolver in `stack.yaml`. No `hie.yaml` was generated explicitly. When HLS 0.5.1 for GHC 8.8.4 is executed within the project's root, it hangs for over an hour, and after that I interrupted the execution. I was expecting HLS to terminate.

Stack 2.5.1 was used. Here is the output of running `~/.local/bin/haskell-language-server-Linux-8.8.4`:

```
Tool versions found on the $PATH
cabal: 2.4.1.0
stack: 2.5.1
ghc: 8.8.4


Step 1/4: Finding files to test in /home/marko/helloworld
Found 4 files

Step 2/4: Looking for hie.yaml files that control setup
Found 1 cradle

Step 3/4: Initializing the IDE

Step 4/4: Type checking the files:
```

Are there any additional dependencies that should be installed?

**Comment by wz1000** [comment]
Can you report the output of `hie-bios flags <somefile.hs>`?

**Comment by mdimjasevic** [comment]
@wz1000, I don't have `hie-bios` installed.

**Comment by fendor** [comment]
@mdimjasevic Does `stack repl` succeed? Does it work if you try only explicitly load a file, e.g. `haskell-language-server --debug ./src/Lib.hs`?

**Comment by jneira** [comment]
@mdimjasevic the error is reproduced with haskell-language-server-0.6.0?

**Comment by expipiplus1** [comment]
I have bumped into the same symptoms on NixOS with 0.6.0 8.8.4

`--debug` and `--logfile` don't seem to do anything.

Here is a reproducer in the form of a nixos test:

```nix
import <nixpkgs/nixos/tests/make-test-python.nix> ({ pkgs, ... }: {
  name = "test";
  machine = { ... }: {
    imports = [ <nixpkgs/nixos/tests/common/user-account.nix> ];
    environment.systemPackages =
      [ pkgs.vim pkgs.ghc pkgs.haskell-language-server ];
  };
  testScript = ''
    # Login
    machine.wait_for_unit("multi-user.target")

    # Create a hie.yaml file and Foo.hs
    machine.succeed('echo "cradle:\n  direct:\n    arguments: []" > hie.yaml')
    machine.succeed('echo "module Foo where\nfoo = ()" > Foo.hs')

    # Run haskell-language-server
    machine.succeed("haskell-language-server")

    # Record for posterity
    machine.screenshot("hls-output")
  '';
})
```

Either run with `nix-build repro.nix` or start the VM to experiment with `$(nb tests/vim.nix -A driverInteractive)/bin/nixos-run-vms` logging in with `alice`/`foobar`

**Comment by zech564** [comment]
Prominence

**Comment by mdimjasevic** [comment]
@jneira, yes, it still occurs with HLS 0.6.0.

@fendor, yes, `stack repl` works and the project builds just fine. When executed against a single source code file, the outcome is the same.

**Comment by jneira** [comment]
As the [correlated issue in ghcide](https://github.com/haskell/haskell-language-server/issues/727) is now here, i am gonna close this one
