### ISSUE TITLE
Disable hlint hints when there are GHC errors

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-language-server#579]
Working on GHC, there are a *lot* of hlint diagnostics.

When a file has an error in it, the "go to next error" command (`] l` in evil-mode) steps through all the hlint warnings, making it hard to quickly fix a file.

Perhaps remove the hlint warnings if GHC reports an error.

haskell-language-server at 8682517e9ff92caa35e727e28445896f97c61e8d

**Comment by jneira** [comment]
Not sure if that would suit all workflows, so it should be configurable. 
I suppose if the editor could discriminate the error level when navigating errors/warnings/infos the experience would be improved too (but i guess it is not possible?)

**Comment by ndmitchell** [comment]
Doesn't upstream GHC have a .hlint.yaml file to supress most of them? Is HLS finding that file and applying it? It seems that having a lot of HLint warnings is a bad thing regardless.

Maybe if there is no .hlint.yaml, then the plugin should offer to supress all existing warnings either for this session (inside the plugin), or by generating a .hlint.yaml file for you.

**Comment by michaelpj** [comment]
This seems like a client issue. We should report all the diagnostics we know about. They already have a `source` field, so clients perfectly well could implement filtering by source :shrug: Or fix your hlint config to report less...
