### ISSUE TITLE
Tactics: case split as several declarations

### ISSUE THREAD

**Issue by serras** [haskell/haskell-language-server#582]
Right now, if I start with the following code:

```haskell
go :: Maybe Int -> Int
go x = _
```

and use "case split on x", the result is:

```haskell
go x = (case x of
   Nothing -> _
   (Just i) -> _)
```

which is not very idiomatic. I was wondering whether there's room for a new "case split" which would produce:

```haskell
go Nothing = _
go (Just i) = _
```

@isovector do you have any opinions on this? I am happy to invest some time on implementing this, but I don't want to step over anybody's plans.

**Comment by isovector** [comment]
Hlint already has support for this; I think the play here is to just automate running hlint's suggestions over the generated span. I don't have any plans to work on this.

**Comment by expipiplus1** [comment]
FWIW, I prefer

```haskell
go x = (case x of
   Nothing -> _
   (Just i) -> _)
```

to 

```haskell
go Nothing = _
go (Just i) = _
``` 

as there isn't any repetition of `go`. (obviously LambdaCase is best of all!)

**Comment by georgefst** [comment]
HLint will suggest removing the bracket and using LambdaCase (which is what I'd personally use), but not the refactoring @serras suggested.

**Comment by isovector** [comment]
To clarify, I'm extremely pro on this idea; I just don't have time to work on it.
