### ISSUE TITLE
Add option to proceed with implicit cradle without error message

### ISSUE THREAD

**Issue by xerus2000** [haskell/haskell-language-server#585]
### Your environment
```
[nix-shell:~/data/1-projects/done/done/pkgs/core-test]$ haskell-language-server-wrapper --probe-tools
haskell-language-server version: 0.5.0.0 (GHC: 8.8.4) (PATH: /nix/store/lh1kn4x6jsdm5v3vv0vgx4kcd35sv8mc-haskell-language-server-0.5.0.0/bin/haskell-language-server-wrapper)
Tool versions found on the $PATH
cabal:          3.2.0.0
stack:          Not found
ghc:            8.8.4
```
* Which lsp-client do you use: https://github.com/gtache/intellij-lsp

### Steps to reproduce
Start language server

### Expected behaviour
I can give it a CLI flag to not warn about using implicit cradle.

### Actual behaviour
I get annoying popups:
> No [cradle](https://github.com/mpickering/hie-bios#hie-bios) found for test/Test/Done.hs.\n Proceeding with [implicit cradle](https://hackage.haskell.org/package/implicit-hie)

So I run `gen-hie` just to get rid of this error-message, even though I don't want to mess with the `hie.yaml` at all.

**Comment by jneira** [comment]
The popup is not longer shown
