### ISSUE TITLE
Flaky test "code actions -> hlint suggestions -> falls back to pre 3.8 code actions"

### ISSUE THREAD

**Issue by maralorn** [haskell/haskell-language-server#611]
I am trying to enable hls tests in nixpkgs. This test seems to fail only sometimes on my local system (a thinkpad notebook with nixos). This is with hls 0.6.0 and ghcide 0.5.0.

```
      falls back to pre 3.8 code actions:                                                               FAIL
        Exception: Timed out waiting to receive a message from the server.
        Last message received:
        {
            "tag": "RspExecuteCommand",
            "contents": {
                "result": null,
                "jsonrpc": "2.0",
                "id": 4
            }
        }
```

**Comment by jneira** [comment]
I've seen this error in other systems, including windows.
In ci we had to add three retries to make it pass almost all times:
```
cabal test func-test --test-options="-j1 --rerun-update" || cabal test func-test --test-options="-j1 --rerun" || LSP_TEST_LOG_COLOR=0 LSP_TEST_LOG_MESSAGES=true LSP_TEST_LOG_STDERR=true cabal test func-test --test-options="-j1 --rerun"
```

Maybe it can alliviate the problems caused by flaky tests for you too

**Comment by maralorn** [comment]
Huh, thanks for the heads-up. Let's just say: That is not how we run our tests normally.^^
I have them disabled anyways for now.
