### ISSUE TITLE
Path error

### ISSUE THREAD

**Issue by georgefst** [haskell/haskell-language-server#613]
HLS 0.6, VScode, Manjaro Linux, Cabal 3.2, GHC 8.10.2.

HLS sometimes gets confused when the Haskell project is not at the root of the folder added to VScode. This is a regression - it worked with 0.5.

[This file](https://github.com/georgefst/monpad/blob/master/haskell/app/Main.hs) demonstrates the problem: I get the error `[..]/monpad/app/Main.hs: openBinaryFile: does not exist (No such file or directory)`. That path indeed doesn't exist - it's missing `haskell` - the second path component.

I've seen this in a simpler project at work, so it's nothing to do with the conditionals in the cabal file or anything like that. I can try to create a minimal repository if that could be helpful.

**Comment by fendor** [comment]
@georgefst Fixed in ghcide master: https://github.com/haskell/ghcide/pull/914

**Comment by jneira** [comment]
This seems to be fixed, @georgefst feel free to reopen if that is not the case
