### ISSUE TITLE
^@ in import lens text

### ISSUE THREAD

**Issue by FongHou** [haskell/haskell-language-server#618]
### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 0.6.0.0 (GHC: 8.10.2) (PATH: /home/haskeller/.local/bin/haskell-language-server-wrapper) (GIT hash: 61c69fd387281c2222f75f13542eaa2e91cbc1b1)
Tool versions found on the $PATH
cabal:          3.2.0.0
stack:          2.5.1
ghc:            8.8.4
```
Which lsp-client do you use:
### neovim + coc.nvim

Describe your project (alternative: link to the project):

Contents of `hie.yaml`:
```yaml

```

### Expected behaviour

neovim/coc.nvim display import lens in virtual text on the same line of import statement (which is not bad in terms of cursor movement), however there are lots of ^@ (how nvim renders null character) and extra whitespaces. I'm not sure where these characters come from.  Do they come from ghcide backend or import plugin does some special formatting for vscode rendering. 

In VSCode, the same file doesn't show any special character or extra whitespaces. 

![image](https://user-images.githubusercontent.com/13973254/100051195-47ca4400-2de9-11eb-9db2-9ad9341f79c8.png)

### Actual behaviour

![image](https://user-images.githubusercontent.com/13973254/100051421-db9c1000-2de9-11eb-9c49-fe7f1ecb3892.png)

Openned an issue https://github.com/neoclide/coc.nvim/issues/2643#issue-748962009. But its maintainer closed it with a very terse comment "The extension your're using should fix this by use first line only for virtual text."

I'd like to see if we can make any improvement here. 

### Include debug information
Execute in the root of your project the command `haskell-language-server --debug .` and paste the logs here:

<details>
<summary>
Debug output:
</summary>

```
<paste your logs here>
```
</details>

Paste the logs from the lsp-client, e.g. for [VS Code](https://github.com/haskell/vscode-haskell#troubleshooting)

<details>
<summary>
LSP logs:
</summary>

```
<paste your logs here>
```
</details>

**Comment by expipiplus1** [comment]
> Openned an issue [neoclide/coc.nvim#2643 (comment)](https://github.com/neoclide/coc.nvim/issues/2643#issue-748962009). But its maintainer closed it with a very terse comment "The extension your're using should fix this by use first line only for virtual text."
> 
> I'd like to see if we can make any improvement here.

Those characters are the rendering of newlines. 

He is very terse :)

This could either be fixed in coc.nvim by joining the lines (and removing large chunks of whitespace) or in HLS before sending.

**Comment by expipiplus1** [comment]
@FongHou I made a patch which resolves this, please check it out: https://github.com/neoclide/coc.nvim/pull/2660

Works quite well for me:

![image](https://user-images.githubusercontent.com/857308/100492423-c6670e80-3166-11eb-833d-13005338f691.png)

**Comment by FongHou** [comment]
@expipiplus1, works great! gave a 👍 there. hope it gets merged!

**Comment by Sir4ur0n** [comment]
Hi, AFAIU this was merged (thus fixed) in Nvim, can we close this issue?

**Comment by expipiplus1** [comment]
Yes, this was merged (in coc.nvim)

**Comment by Sir4ur0n** [comment]
Thanks!
