### ISSUE TITLE
Tone down the implicit cradle import warnings

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haskell-language-server#620]
### Your environment

I am using HLS 0.6. Since I installed directly from VS Code I have no HLS or HLS wrapper on my path to probe tools. Windows, VS Code.

### Steps to reproduce

Open Shake with no hie.yaml. Observe that each and every file I open produces a warning about an implicit prelude. I just dismissed 25 such warnings.

### Expected behaviour

One warning. Once per session seems plenty.

### Actual behaviour

Many warnings.

**Comment by expipiplus1** [comment]
Or no warnings by setting a config option! I don't think I've ever changed my behavior after getting one of those warnings.

**Comment by ndmitchell** [comment]
Or maybe the warnings are no longer necessary? It used to be that an implicit cradle was a guarantee something would go wrong. Nowadays I have way more success with implicit cradles than explicit ones.

**Comment by jneira** [comment]
@ndmitchell i was a little bit confused for the 

>implicit prelude

in the description, i suppose you wanted to mean impicit cradle.

I think it works well enough to demote it again (was done from warning to info) to a log message

**Comment by ndmitchell** [comment]
Oops! Too much time dealing with implicit prelude stuff - thanks for the fix :). Agreed, a lot message might be the way to go.
