### ISSUE TITLE
Issue template doesn't work (make easier generate bug report info with no executable in path)

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haskell-language-server#621]
> Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

I don't have either of these on my PATH. I have no idea where they lie because VS Code installed HLS for me. Perhaps VS Code should have a "generate HLS bug report info" command we could point people at?

**Comment by jneira** [comment]
The executables are inside `context.globalStoragePath` setting of vscode, i think it should be `%USERPROFILE%\.vscode\extensions` but i cant check it just now.
That said, that is something users might not know and i agree add a command `generate HLS bug report info`, maybe in the vscode extension would be a nice ux improvement.
