### ISSUE TITLE
CodeLens to add type signature failed to deal with functions with `*` in their names

### ISSUE THREAD

**Issue by berberman** [haskell/haskell-language-server#622]
![image](https://user-images.githubusercontent.com/26041945/100096181-a3064000-2e96-11eb-892b-e1fd16c57357.png)

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 0.6.0.0 (GHC: 8.10.2) (PATH: /home/berberman/.cabal/store/ghc-8.10.2/haskell-language-server-0.6.0.0-12a6a1bf45aba2e44066b7b11fef0d76d92497c62667866a713a7034b763f060/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:          3.2.0.0
stack:          2.5.1
ghc:            8.10.2
```
Which lsp-client do you use:
vscode

### Steps to reproduce
Create a function whose name contains `*` .
### Expected behaviour
Code lens helps me to add the missing type signature properly.

### Actual behaviour
Type signature is cut off at `*`.

### Note

https://github.com/haskell/ghcide/blob/c4418abdc10c93eda0b27f24b1076995fff9de45/src/Development/IDE/Plugin/CodeAction.hs#L686-L692

Why we take until the `*` or `•`?

**Comment by jhrcek** [comment]
I guess this `takeWhile` logic is there because of this [bullet](https://github.com/ghc/ghc/blob/2ed3e6c0f179c06828712832d1176519cdfa82a6/compiler/GHC/Utils/Outputable.hs#L689) which is used in GHC error messages to provide additional details in error messages.
