### ISSUE TITLE
Import suggestion code action doesn't suggest importing operators

### ISSUE THREAD

**Issue by expipiplus1** [haskell/haskell-language-server#629]
With the following file:

```haskell
module Foo where

foo = (.|.)

bar = complement
```

Observe that the code actions suggest importing `Data.Bits` for `complement` but not for `.|.`

**Comment by jneira** [comment]
Wow, thanks for the rush of reported issues. Defintely, it seems import suggestions, included in ghcide, should be improved.

**Comment by georgefst** [comment]
I think the problem is just operators containing a ".". Probably an issue parsing the error message - isn't GHC getting typed errors and warnings at some point or is that a very long-term goal?

**Comment by georgefst** [comment]
To confirm this isn't a separate issue to what I've seen, try `f = (<&>)`, assuming you don't already have `Data.Functor` in scope.

**Comment by expipiplus1** [comment]
ah, I tested it also on `<$` and it didn't seem to work.

**Comment by expipiplus1** [comment]
Thanks!
