### ISSUE TITLE
Format on import 

### ISSUE THREAD

**Issue by expipiplus1** [haskell/haskell-language-server#634]
I'm sure there was an issue for this already, but I couldn't find it.

It would be great if the import list was formatted after using the auto import function, I think HIE used to have this functionality as there's a vestigial option for it in the config.

**Comment by pepeiborra** [comment]
VSCode already provides format on save and there's an option to restrict the formatting to the diff with the on-disk file, so this is a client-side feature.
 
But I guess having HLS doing it might still be relevant for other clients.

**Comment by michaelpj** [comment]
I think it's better if HLS does just the thing it was asked to do. Format on save on the client side seems like a good solution.
