### ISSUE TITLE
Please release

### ISSUE THREAD

**Issue by gwils** [haskell/haskell-language-server#636]
Some of the recent changes (especially the fourmolu bump) would really help my team. Can you please cut a release soon?

**Comment by jneira** [comment]
The monthly release would have to happen soon. We were waiting for some hlint plugin fixes but i think we can plan to cut the release for the weekend and include them in a next one, if they are not finished
//cc @alanz @bubba

**Comment by alanz** [comment]
Agree

**Comment by bubba** [comment]
We can do a minor version release for things like dependency bumps. Would `0.6.1` make sense?

**Comment by jneira** [comment]
We should take a quick look to check we wanna not break clients of the libs (pvp etcetc) but yeah, it is fine for me

**Comment by jneira** [comment]
Hi, we just have released 0.7.0 that includes the fourmolu bump, sorry for the delay

**Comment by pepeiborra** [comment]
@jneira can we have a Hackage release of `his-plugin-api` too?
