### ISSUE TITLE
"Remove redundant import" doesn't always work with ImportQualifiedPost

### ISSUE THREAD

**Issue by georgefst** [haskell/haskell-language-server#642]
```hs
{-# LANGUAGE ImportQualifiedPost #-}
{-# OPTIONS_GHC -Wall #-}

import Data.Functor qualified
```

leads to:

```hs
{-# LANGUAGE ImportQualifiedPost #-}
{-# OPTIONS_GHC -Wall #-}

 qualified
```

**Comment by georgefst** [comment]
Actually, this looks like a GHC `SrcLoc` bug. See `ghc -ddump-parsed-ast`. Will report upstream.

**Comment by ndmitchell** [comment]
@georgefst can you include the link here when you do. CC @shayne-fletcher (the Ghcide guts of HLS and the ImportQualifiedPost were written by the same people at the same time)

**Comment by shayne-fletcher** [comment]
@georgefst , @ndmitchell thanks for alerting me. Yes, I see the problem. @georgefst please assign me the bug

**Comment by georgefst** [comment]
https://gitlab.haskell.org/ghc/ghc/-/issues/19014

**Comment by shayne-fletcher** [comment]
Submitted an MR fixing this https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4552.

**Comment by shayne-fletcher** [comment]
The fix has landed on GHC master and marked as needing back porting to 8.10.3 and 9.0.1 🤞

**Comment by shayne-fletcher** [comment]
> The fix has landed on GHC master and marked as needing back porting to 8.10.3 and 9.0.1 🤞

I see that the fix was back-ported to these branches today so we are all set.
