### ISSUE TITLE
Problem with extension in vscode when build application with --docker flag

### ISSUE THREAD

**Issue by xgrommx** [haskell/haskell-language-server#644]
I have some dependencies and I need it build on my mac via docker. 
I use command `stack build --docker` and after that extension in vscode doesn't work.

How can I fix this problem? Maybe someone have some advices how can I solve it.

**Comment by jneira** [comment]
Thanks for report this. It might be related with #430, the workaround suggested there was:

> IIRC, we concluded, that the easiest solution is to run HLS in the docker container as well.

I am gonna close it as duplicated, feel free to commment there any concern.
