### ISSUE TITLE
Rename executables to `hls` and `hls-wrapper`

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-language-server#65]
Mainly because I think that `cabal install exe:haskell-language-server` hurts my wrist 😄
Opinions?

**Comment by jneira** [comment]
Well, i liked it when we discussed the project name: https://github.com/haskell/haskell-language-server/issues/29 so :+1

**Comment by alanz** [comment]
> Mainly because I think that cabal install exe:haskell-language-server hurts my wrist

I have a small helper script to do that.  And there is a great big one, 

```bash
./cabal-hls-install hls-8.6.5
```

**Comment by jneira** [comment]
@fendor do you think we could close this one?

**Comment by fendor** [comment]
I suppose it is too late to rename the executables without some serious overhead. Closing as wontfix
