### ISSUE TITLE
Add code-action to fill in functions required for implementing a type-class

### ISSUE THREAD

**Issue by fendor** [haskell/haskell-language-server#652]
E.g. on a code-snippet:

```haskell
data Bar = Bar

instance Show Bar where
```

The code-action should offer (semantically):
```haskell

data Bar = Bar

instance Show Bar where
  showsPrec = undefined
```

and 

```haskell

data Bar = Bar

instance Show Bar where
  show = undefined
```

This could explode exponentially if there are complex Minimal pragmas, but I guess that is fine.
The stub-definition could be implemented with snippets.

**Comment by fendor** [comment]
I don't know how easy it would be to implement something like that.

**Comment by ocharles** [comment]
I'd suggest holes instead of `undefined`

**Comment by Ailrun** [comment]
I will try this using a similar idea with the AddPragma plugin.
