### ISSUE TITLE
Desugarer warnings

### ISSUE THREAD

**Issue by georgefst** [haskell/haskell-language-server#676]
Has haskell/ghcide#107 crept back in?

Just updated to HLS 0.7 via the VScode plugin and I'm back to not seeing any "incomplete pattern match" warning on e.g.:

```
{-# OPTIONS_GHC -Wall #-}

f = \case
    Nothing -> ()
```

:cry:

**Comment by jneira** [comment]
No worries, i hope this one will be less problematic 🤞
