### ISSUE TITLE
How to disable completion snippets

### ISSUE THREAD

**Issue by berberman** [haskell/haskell-language-server#680]
Thanks to all contributors, this is an awesome feature. But it can be annoying sometimes. For functions, supposed that I'm playing with point-free code, or using view patterns, obviously it should not help me complete the arguments. For types, I don't think inserting `*` makes a lot of sense. Personally speaking, in more than half of cases I have to delete these generated snippets, and they are not informative, since I can grab the details of a function or a type in the populated completion window,

Is there a way to disable this in lsp clients?

### Your environment
Output of `haskell-language-server --probe-tools` or `haskell-language-server-wrapper --probe-tools`:

```sh
haskell-language-server version: 0.7.0.0 (GHC: 8.10.2) (PATH: /home/berberman/.cabal/store/ghc-8.10.2/haskell-language-server-0.7.0.0-366830c6e84454f47d73ac01246969cb5c550194b34bde3428fbd57c6144f4d0/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:		3.2.0.0
stack:		2.5.1
ghc:		8.10.2
```
Which lsp-client do you use:

vscode

**Comment by jneira** [comment]
A config option would be the way i guess. It could be added in the pr that are moved completions to hls: #670 and ideally it would be included in the plan to configure plugins in a general way: #513 (although it doesnt have to wait for it, hlint already has a option to disable it)
//cc @gdevanla

**Comment by konn** [comment]
IIRC, Haskell extension for VSCode provides a flag for exactly this issue: you can turn off `Haskell: Completion Snippets On
`, which corresponds to `haskell.completionSnippetsOn`.

**Comment by expipiplus1** [comment]
@konn  the readme says that this flag is unused: https://github.com/haskell/haskell-language-server/blob/f78f40c87a937eadd4dd1f10eb3411ab2da9d157/README.md#L291

**Comment by jneira** [comment]
@konn thanks for note it, so the config option already exists and it still is included in the plugin configuration data type:

https://github.com/haskell/haskell-language-server/blob/bf8ce830710bd49f6dcdbd30e944553e85ccdb97/hls-plugin-api/src/Ide/Plugin/Config.hs#L51

So it is matter to use it effectively in the new hls completion plugin.

**Comment by konn** [comment]
@expipiplus1 @jneira Ah, I misunderstood the situation. Sorry.

**Comment by poscat0x04** [comment]
I too find completion snippets utterly unhelpful.

**Comment by gdevanla** [comment]
@poscat0x04 Thanks for the feedback. Is your concern similar to what the berberman had brought up? Do you have any suggestions on how we could make the experience better and useful? Thanks for trying it out and letting us know how you feel.

**Comment by alanz** [comment]
Now that #691 has landed you can add a config item to send JSON like

```json
haskell.plugin.ghcide.completionOn = false
haskell.plugin.pragmas.completionOn = false
```
Depending on which ones you want turned off

**Comment by peterwicksstringfield** [comment]
A user asking about this bug:
https://stackoverflow.com/questions/65530569/vscode-autocompletion-adds-extra-information-that-i-dont-need-want-with-haskell

**Comment by jneira** [comment]
Afaics hls already honours `completionSnippetsOn` flag thanks to @takoeight0821 , and it is included in vscode
