### ISSUE TITLE
A language pragma snippet would be very useful

### ISSUE THREAD

**Issue by expipiplus1** [haskell/haskell-language-server#681]
A snippet which matches on `language` and expands to `{-# LANGUAGE <> #-}` would be very handy

**Comment by jneira** [comment]
Maybe it could be added to the completion plugin that @gdevanla is moving to hls from ghcide (it does not have to be in the initital pr but afterwards)

**Comment by July541** [comment]
To make it more clearly, for the code
```haskell
{-# LANGUAGE OverloadedStrings #-}

import Data.Text as T

foo :: T.Text
foo = "abc"
```

does this look like the image?
![image](https://user-images.githubusercontent.com/16057632/116085738-b16cb800-a6d1-11eb-8954-1c98e42ac32f.png)
