### ISSUE TITLE
Completion provenance for local definition is Just ModuleName instead of just ModuleName

### ISSUE THREAD

**Issue by expipiplus1** [haskell/haskell-language-server#683]
To reproduce:

Create the following module:

```haskell
module Foo
  where

bar = ()

foo = ba
```

- Trigger completion for `ba`
- Observe that the provenance of `bar` is `Just Foo` instead of just `Foo`

![image](https://user-images.githubusercontent.com/857308/102451958-78ae3980-4074-11eb-9111-6430c4a5e7c4.png)

**Comment by jneira** [comment]
Thanks to test the new version and report the issues you have found (it seems all of them are related with completions). The fix could be added to the new completion plugin as the rest: #670

**Comment by July541** [comment]
Completion doc does not display correctly with the local module.

<img width="752" alt="image" src="https://user-images.githubusercontent.com/16057632/164479222-2c61e44a-3ba8-416d-bb27-f69335996b9f.png">

<img width="803" alt="image" src="https://user-images.githubusercontent.com/16057632/164479343-a4f4e757-e165-4fe4-94cb-e440f3773673.png">
