### ISSUE TITLE
Upload new logo

### ISSUE THREAD

**Issue by GuillaumeDesforges** [haskell/haskell-language-server#694]
https://github.com/haskell/haskell-ide-engine/issues/267

Any logo for HLS?

-----------------------------------
EDIT (@jneira)

### We are choosing our new logo through an open survey. ~~You can vote in the comment [below](https://github.com/haskell/haskell-language-server/issues/694#issuecomment-762701777).~~

--------------------
EDIT (@Ailrun)

### We decided our new logo. You can check the result in the comment [below](https://github.com/haskell/haskell-language-server/issues/694#issuecomment-767741115) and related [PR](https://github.com/haskell/haskell-language-server/pull/1267).

**Comment by jneira** [comment]
Absolutely! Afair we tried to adapt the hie one (simply changing ie for ls) when it was started but we did not finish anything

**Comment by alanz** [comment]
I propose we open it up for contributions again, and vote, as we did for HIE.

**Comment by alanz** [comment]
[Called for contributions](https://mail.haskell.org/pipermail/haskell-cafe/2020-December/133253.html)

> Hi all,
>
> The haskell language server is coming up for its first birthday in
January.  To celebrate we would like to collectively choose a logo.
>
> So if you have a creative streak and would like to donate a lasting
contribution to the project, please submit for consideration at [1].
>
> We will aim to close the judging on 25 Jan 2021, being the anniversary of
the Bristol Hackathon[2] where HLS was born.
>
> Alan
> 
> [1] https://github.com/haskell/haskell-language-server/issues/694
> [2] https://mpickering.github.io/bristol2020.html

**Comment by gizmo-mk0** [comment]
![hls-logo](https://user-images.githubusercontent.com/8467908/103012469-94618600-4533-11eb-9e18-b521e7d43021.png)

**Comment by sjcjoosten** [comment]
![Logo_animated](https://user-images.githubusercontent.com/7753626/103015547-a1b84980-450e-11eb-8578-bb17cda714e9.png)
[Still files as svg, png, etc](https://github.com/haskell/haskell-language-server/files/5736072/Stills.zip)

**Comment by sjcjoosten** [comment]
![ProposalSJC](https://user-images.githubusercontent.com/7753626/103015736-f360d400-450e-11eb-85a8-b93ed6aaca5e.png)
[Separate Files as pdf and png](https://github.com/haskell/haskell-language-server/files/5736079/SeparateFiles.zip)

**Comment by alanz** [comment]
Albert Krewinkel suggests on haskell-cafe

> You could also post this as a "job" on the Open Source Design board, a
community dedicated to help open source projects with their designs.
https://opensourcedesign.net/

**Comment by Ailrun** [comment]
![logo3](https://user-images.githubusercontent.com/12473268/103048788-c2f45680-455d-11eb-869d-c56abc933933.png)

**Comment by mel-brown** [comment]
![image](https://user-images.githubusercontent.com/18196871/103104083-4ca23380-45f3-11eb-8553-955d3fbc608e.png)

**Comment by georgefst** [comment]
![out](https://user-images.githubusercontent.com/12991097/103144151-e4e80780-471c-11eb-8f03-ef7b2d65f5cc.png)

Got off to a good start, couldn't really work out what to do with the S. Open to suggestions.

**Comment by georgefst** [comment]
> Open to suggestions.

Or, if anyone wants to play with some under-commented code:

```
git clone https://github.com/georgefst/haskell-logo -b hls
cd haskell-logo
cabal install --package-env . --allow-newer='*:base' --lib diagrams-lib diagrams-core diagrams-svg
ghcid -c 'ghci logo.hs' -W -T ':main -w 1000 -o out.svg'
```

And open in an SVG viewer with live reload (EOG, MacOS Finder, ...).

**Comment by Ailrun** [comment]
@mel-brown If I pick yours, I would probably choose the first one, because, IMHO, the second is less readable than the first, and the third is barely readable in a dark mode (for example, GitHub's).

**Comment by mel-brown** [comment]
@Ailrun thanks for the feedback! I’ll edit my post later today with a wider range of colours.

**Comment by georgefst** [comment]
Revised:


![out](https://user-images.githubusercontent.com/12991097/103152675-3b3b6180-4782-11eb-9929-c610d15ae2b7.png)

**Comment by alanz** [comment]
@georgefst Your revised one looks good, but the lambda in the middle would get lost when this is turned into a page icon.  Maybe leave it blank?

**Comment by georgefst** [comment]
@alanz Yeah it's a shame - I feel it kind of ties the whole thing together, but you're right that it doesn't really work at small scale.

I liked the idea of drawing attention to the lambda shape in the middle, but perhaps it's best left implicit.

![out](https://user-images.githubusercontent.com/12991097/103160924-ae6cc400-47d2-11eb-8878-1a5dc0a51771.png)
![out-1](https://user-images.githubusercontent.com/12991097/103160925-b0368780-47d2-11eb-8deb-416de0b9e8e7.png)

**Comment by alanz** [comment]
I think I prefer the top one, tbh. The grey lambda in the bottom one breaks the 3d effect.

**Comment by alanz** [comment]
Maybe draw a highlight line along the bottom of the H, over the lambda, to indicate it "bends" there, if you want to keep it.

**Comment by sureyeaah** [comment]
![image](https://user-images.githubusercontent.com/2617705/104018475-d64f2500-51df-11eb-9c39-3ac91f407bbe.png)

**Comment by alanz** [comment]
I guess it is time to set this up for a vote. Anyone want to organise it?

**Comment by Ailrun** [comment]
![logo](https://user-images.githubusercontent.com/12473268/104870335-41060c00-5916-11eb-983a-151826fa8bb4.png)
I may add yet another candidate.
<details>
<summary>
SVG Code
</summary>

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   width="290mm"
   height="215mm"
   viewBox="0 0 290 215"
   version="1.1">
  <g
     id="h">
    <path
       id="h_greater"
       fill="#453a62"
       d="M 65,119.99956 105.00031,59.99978 65,0 H 94.999891 L 135.0002,59.99978 94.999891,119.99956 Z m 0,0" />
    <path
       id="h_lambda"
       fill="#5e5086"
       d="M 105.00031,119.99956 145.00063,59.99978 105.00031,0 h 29.99989 l 79.99925,119.99956 H 184.99956 L 160.00057,82.500387 135.0002,119.99956 Z m 0,0" />
  </g>
  <path
     fill="#8f4e8b"
     d="m 60,125 h 30 l -40,60 h 75 l -20,30 H 0 Z"
     id="l" />
  <path
     fill="#8f4e8b"
     d="m 185,150 h 55 l -20,-25 h -45 l -35,55 h 95 l 2,5 H 135 l -20,30 h 175 l -45,-60 h -62 z"
     id="s" />
</svg>
```

</details>

**Comment by Anrock** [comment]
@Ailrun this! 
P.S. Also, add a squiggly red line somewhere :D

**Comment by Ailrun** [comment]
@Anrock as steam from the flask? LoL

**Comment by Anrock** [comment]
@Ailrun no, like source code error squiggly line. Like @sureyeaah did.
P.S. I'm joking
P.P.S. Tho why not.

**Comment by alanz** [comment]
Will a squiggly show up in a favicon?

**Comment by Ailrun** [comment]
@alanz where will the vote be held? Maybe I just missed, but I don't see a link or service name on the previous HIE issue.

**Comment by alanz** [comment]
We did it in the issue, with likes. Scroll down and you will see

**Comment by jneira** [comment]
I am testing https://app.gh-polls.com/, let me some time to setup it

**Comment by jneira** [comment]
![hls-logo](https://user-images.githubusercontent.com/8467908/103012469-94618600-4533-11eb-9e18-b521e7d43021.png)
[![](https://api.gh-polls.com/poll/01EWCXMPWX0YCWMK5XS6Y84TAX/%40gizmo-mk0)](https://api.gh-polls.com/poll/01EWCXMPWX0YCWMK5XS6Y84TAX/%40gizmo-mk0/vote)

--------------------------------------------
![Logo_animated](https://user-images.githubusercontent.com/7753626/103015547-a1b84980-450e-11eb-8578-bb17cda714e9.png)
[![](https://api.gh-polls.com/poll/01EWCXMPWX0YCWMK5XS6Y84TAX/%40sjcjoosten%201)](https://api.gh-polls.com/poll/01EWCXMPWX0YCWMK5XS6Y84TAX/%40sjcjoosten%201/vote)

--------------------------------------------
![ProposalSJC](https://user-images.githubusercontent.com/7753626/103015736-f360d400-450e-11eb-85a8-b93ed6aaca5e.png)
[![](https://api.gh-polls.com/poll/01EWCXMPWX0YCWMK5XS6Y84TAX/%40sjcjoosten%202)](https://api.gh-polls.com/poll/01EWCXMPWX0YCWMK5XS6Y84TAX/%40sjcjoosten%202/vote)

--------------------------------------------
![logo4](https://user-images.githubusercontent.com/12473268/103146538-1232b680-4719-11eb-9026-d0f4319a3470.png)
[![](https://api.gh-polls.com/poll/01EWCXMPWX0YCWMK5XS6Y84TAX/%40ailrun%201)](https://api.gh-polls.com/poll/01EWCXMPWX0YCWMK5XS6Y84TAX/%40ailrun%201/vote)

--------------------------------------------
![logo](https://user-images.githubusercontent.com/12473268/104871043-10bf6d00-5918-11eb-956a-ecb1b48f06cd.png)
[![](https://api.gh-polls.com/poll/01EWCXMPWX0YCWMK5XS6Y84TAX/%40ailrun%202)](https://api.gh-polls.com/poll/01EWCXMPWX0YCWMK5XS6Y84TAX/%40ailrun%202/vote)

--------------------------------------------
![hls-haskell-wordmark](https://user-images.githubusercontent.com/18196871/103153076-cbb27b80-475b-11eb-9009-ea10f3de86ca.png)
[![](https://api.gh-polls.com/poll/01EWCXMPWX0YCWMK5XS6Y84TAX/%40bi-functor)](https://api.gh-polls.com/poll/01EWCXMPWX0YCWMK5XS6Y84TAX/%40bi-functor/vote)

--------------------------------------------
![out](https://user-images.githubusercontent.com/12991097/103160924-ae6cc400-47d2-11eb-8878-1a5dc0a51771.png)
[![](https://api.gh-polls.com/poll/01EWCXMPWX0YCWMK5XS6Y84TAX/%40georgefst)](https://api.gh-polls.com/poll/01EWCXMPWX0YCWMK5XS6Y84TAX/%40georgefst/vote)

--------------------------------------------
![image](https://user-images.githubusercontent.com/2617705/104018475-d64f2500-51df-11eb-9c39-3ac91f407bbe.png)
[![](https://api.gh-polls.com/poll/01EWCXMPWX0YCWMK5XS6Y84TAX/%40sureyeaah)](https://api.gh-polls.com/poll/01EWCXMPWX0YCWMK5XS6Y84TAX/%40sureyeaah/vote)

--------------------------------------------

**Comment by Ailrun** [comment]
I think it's worthwhile to mention that you can vote for multiple options.

**Comment by georgefst** [comment]
@jneira Is this intended as the final poll? I'd have wanted to submit (a slightly modified version of) https://github.com/haskell/haskell-language-server/issues/694#issuecomment-751358012 if it weren't for the concern that the element in the middle is too small to be visible in e.g. favicons. And yet, the "red-squiggly-line" submission is currently winning...

**Comment by Ailrun** [comment]
@georgefst wait... does it look different per user? For me the winning is 4th lambda LS. Have you refreshed your browser?

**Comment by jneira** [comment]
> @jneira Is this intended as the final poll

yeah, sorry, i thought everybody finished their proposals :worried:

**Comment by Ailrun** [comment]
@jneira Thank you for the confirmation. Then it looks consistent across users... I guess.

**Comment by georgefst** [comment]
> yeah, sorry, i thought everybody finished their proposals 😟

No worries, I guess I didn't really make clear which of the ones I posted was my preferred choice. I'd been meaning to come back with a final version, but admittedly it has been three weeks...

**Comment by Anrock** [comment]
@jneira re: gh-polls - I don't see any pros in using it. It's exactly the same (sans vote bars and percents) as multiple posts with likes but with an ugly con of sending you to another page and then back losing scroll position.

**Comment by GuillaumeDesforges** [comment]
> @jneira re: gh-polls - I don't see any pros in using it. It's exactly the same (sans vote bars and percents) as multiple posts with likes but with an ugly con of sending you to another page and then back losing scroll position.

Might have been done to reset counts (as there was a bias in favor of propositions that got posted earlier)

**Comment by alanz** [comment]
It is not at all clear to me that there is a poll going on at the moment.  There are images with sliders underneath. How do I vote?

We also need to decide and explain when the vote ends. Probably in a week's time?

**Comment by Ailrun** [comment]
@alanz A click on one of (or clicks on many of) those sliders is voting.

**Comment by alanz** [comment]
> A click on one of (or clicks on many of) those sliders is voting.

Thanks. But I think we need to edit that into the top of the voting comment (https://github.com/haskell/haskell-language-server/issues/694#issuecomment-762701777)

**Comment by Ailrun** [comment]
Agree, that may confuse others too.

**Comment by jneira** [comment]
@Ailrun @alanz updated, thanks for suggesting it

**Comment by Ailrun** [comment]
Thanks!

**Comment by alanz** [comment]
I think it would help to edit the very top comment to say what is happening, and add a link to the voting point.

Is it possible to undo a vote if you change your mind?

**Comment by Ailrun** [comment]
I don't think it's possible, unfortunately.

**Comment by jneira** [comment]
> I think it would help to edit the very top comment to say what is happening, and add a link to the voting point.

done, sorry for opening the poll with no further info, i did not think in the usability

**Comment by alanz** [comment]
Call for votes sent to [haskell-cafe](https://mail.haskell.org/pipermail/haskell-cafe/2021-January/133335.html)

**Comment by alanz** [comment]
So this has closed, and

![image](https://user-images.githubusercontent.com/409607/105888181-902dfa00-6004-11eb-8c69-4a921ebd952c.png)

Appears to be the winner.

Congratulations @Ailrun 

What next?

**Comment by Ailrun** [comment]
Maybe it will be better for me to provide some minor adjustment of the winning version, and pick the best among them?

**Comment by alanz** [comment]
> Maybe it will be better for me to provide some minor adjustment of the winning version, and pick the best among them?

That sounds like a good idea.  And when we finalise it, will you be able to supply a set as in https://github.com/haskell/haskell-ide-engine/tree/master/logos?

**Comment by Ailrun** [comment]
Sure, will be easy since the image is in SVG.

**Comment by Ailrun** [comment]
I tried some adjustments, but most of them (definitely) look not better. I decided to stick with the original elected version.

<details>
  <summary>SVG</summary>

  ```svg
  <?xml version="1.0" encoding="UTF-8"?>
  <svg xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg"
       width="290mm" height="215mm" viewBox="0 0 290 215">
      <g id="h">
          <path id="h_greater" fill="#453a62"
                d="M 65,119.99956 105.00031,59.99978 65,0 H 94.999891 L 135.0002,59.99978 94.999891,119.99956 Z m 0,0" />
          <path id="h_lambda" fill="#5e5086"
                d="M 105.00031,119.99956 145.00063,59.99978 105.00031,0 h 29.99989 l 79.99925,119.99956 H 184.99956 L 160.00057,82.500387 135.0002,119.99956 Z m 0,0" />
      </g>
      <path id="l" fill="#8f4e8b"
            d="m 60,125 h 30 l -40,60 h 75 l -20,30 H 0 Z" />
      <path id="s" fill="#8f4e8b"
            d="m 185,150 h 55 l -20,-25 h -45 l -35,55 h 95 l 2,5 H 135 l -20,30 h 175 l -45,-60 h -62 z" />
  </svg>
  ```
</details>

<details>
  <summary>32px</summary>

  ![logo-32](https://user-images.githubusercontent.com/12473268/105920321-2a8e3d80-6005-11eb-9e76-af331203d0c0.png)
</details>

<details>
  <summary>64px</summary>

  ![logo-64](https://user-images.githubusercontent.com/12473268/105920583-a4262b80-6005-11eb-84f6-51771f0f3ea1.png)
</details>

<details>
  <summary>128px</summary>

  ![logo-128](https://user-images.githubusercontent.com/12473268/105920689-cfa91600-6005-11eb-854f-1181e2760e46.png)
</details>

<details>
  <summary>256px</summary>

  ![logo-256](https://user-images.githubusercontent.com/12473268/105920699-d59ef700-6005-11eb-8e99-6c8aae143e7d.png)
</details>

<details>
  <summary>512px</summary>

  ![logo-512](https://user-images.githubusercontent.com/12473268/105920734-e5b6d680-6005-11eb-8b11-4bef1d83d88f.png)
</details>

<details>
  <summary>1024px</summary>

  ![logo-1024](https://user-images.githubusercontent.com/12473268/105920755-ea7b8a80-6005-11eb-915e-08ac620cbdf8.png)
</details>

I will upload these as a PR too.

**Comment by alanz** [comment]
Well, that is what we all voted for, so no problem.

Thanks for generating the different sizes

**Comment by andys8** [comment]
Printed a handful of stickers. Awesome project, awesome logo.

https://twitter.com/_andys8/status/1368194495016271874?s=19

**Comment by Ailrun** [comment]
Awesome, I also want to have one :)
