### ISSUE TITLE
HEADS UP: git force push on master

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#706]
The history of the master branch was rewritten on Dec 29th at 13:40 GMT. 

If you checked out master between Dec 29th at 9:49 GMT and 13:40 GMT, you will probably need to throw that branch away or use `git reset --hard` to restore the history. 

And ghcide is no longer a submodule, you may have the residual content on your checkout, in which case doing `rm -fr ghcide` will allow the checkout of master to go ahead.

**Comment by jneira** [comment]
i think we can close this one
