### ISSUE TITLE
Create trouble shooting setup guide

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haskell-language-server#714]
We get a lot of people who come to us with very similar setup problems. We should have a single page that says "If you have Nix + Cabal v2, be aware of ...". If your tests fail with `ghcide` then ... If it works in `ghcide` but not VS Code then perhaps....

**Comment by jneira** [comment]
There is a `type: setup` label for issues than can be used to identify them, to skecth such a troubleshooting

**Comment by jneira** [comment]
We have newer issues about improving the existing troubleshooting guides, like #2387 so i think we can close this
