### ISSUE TITLE
sectionSeparator does not work with Emacs lsp-ui

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/haskell-language-server#716]
I'm using Emacs 26.3 and the lsp-ui install instructions on the ghcide README.

lsp-ui does not seem to like the [`sectionSeparator`](http://hackage.haskell.org/package/haskell-lsp-types-0.17.0.0/docs/src/Language.Haskell.LSP.Types.MarkupContent.html#sectionSeparator) defined by `haskell-lsp-types`.  It renders the info box shown below, seemingly thinking that the first `*` is a bullet and then generating a sort of underlined `*` using the other two.  I'm not sure whose bug this is.  If `*\t*\t*\n` as a Markdown section separator is a genuine part of the LSP standard then I suppose it's `lsp-ui`'s bug; if it's not part of the LSP standard then it's probably `haskell-lsp-types`'s bug.  In either case I think `ghcide` needs to make a decision to ignore, workaround, or poke upstream or downstream as appropriate.

![image](https://user-images.githubusercontent.com/1951567/68991403-68ff6880-0856-11ea-890a-23112061e2be.png)

**Comment by jneira** [comment]
@alanz doest this behaviour persist in hls?

**Comment by alanz** [comment]
I get

![image](https://user-images.githubusercontent.com/409607/103299761-303c3780-49f5-11eb-8455-aa41397e9249.png)

GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.23, cairo version 1.16.0) of 2020-11-07, modified by Debian

**Comment by jneira** [comment]
@tomjaguarpaw it seems the separator looks good now, feel free to reopen if it is not the case
