### ISSUE TITLE
Cannot build ghcide on Windows with cabal v1 commands

### ISSUE THREAD

**Issue by augustss** [haskell/haskell-language-server#725]
The heapsize package refers to an undefined symbol.  Here's the build log:

Build log ( C:\Users\lennart.augustsson\AppData\Roaming\cabal\logs\ghc-8.10.3\ghcide-0.6.0.1-5nHKroEr0uE5lwJdL7Kohe.log ):
Preprocessing executable 'ghcide-test-preprocessor' for ghcide-0.6.0.1..
Building executable 'ghcide-test-preprocessor' for ghcide-0.6.0.1..
[1 of 1] Compiling Main             ( test\preprocessor\Main.hs, dist\build\ghcide-test-preprocessor\ghcide-test-preprocessor-tmp\Main.o )
Linking dist\build\ghcide-test-preprocessor\ghcide-test-preprocessor.exe ...
Preprocessing library for ghcide-0.6.0.1..
Building library for ghcide-0.6.0.1..
[ 1 of 52] Compiling Development.IDE.Compat ( src\Development\IDE\Compat.hs, dist\build\Development\IDE\Compat.o )
[ 2 of 52] Compiling Development.IDE.Core.Debouncer ( src\Development\IDE\Core\Debouncer.hs, dist\build\Development\IDE\Core\Debouncer.o )
[ 3 of 52] Compiling Development.IDE.Core.PositionMapping ( src\Development\IDE\Core\PositionMapping.hs, dist\build\Development\IDE\Core\PositionMapping.o )
[ 4 of 52] Compiling Development.IDE.GHC.Compat ( src\Development\IDE\GHC\Compat.hs, dist\build\Development\IDE\GHC\Compat.o )
[ 5 of 52] Compiling Development.IDE.GHC.CPP ( src\Development\IDE\GHC\CPP.hs, dist\build\Development\IDE\GHC\CPP.o )
[ 6 of 52] Compiling Development.IDE.Plugin.CodeAction.PositionIndexed ( src\Development\IDE\Plugin\CodeAction\PositionIndexed.hs, dist\build\Development\IDE\Plugin\CodeAction\PositionIndexed.o )
[ 7 of 52] Compiling Development.IDE.Session.VersionCheck ( session-loader\Development\IDE\Session\VersionCheck.hs, dist\build\Development\IDE\Session\VersionCheck.o )
ghc.exe:  | C:\Users\lennart.augustsson\AppData\Roaming\cabal\x86_64-windows-ghc-8.10.3\heapsize-0.3.0.1-LAg81MfrxlyBstfNO1PK7g\HSheapsize-0.3.0.1-LAg81MfrxlyBstfNO1PK7g.o: unknown symbol `heap_view_closurePtrs'
ghc.exe: Could not load Object Code C:\Users\lennart.augustsson\AppData\Roaming\cabal\x86_64-windows-ghc-8.10.3\heapsize-0.3.0.1-LAg81MfrxlyBstfNO1PK7g\HSheapsize-0.3.0.1-LAg81MfrxlyBstfNO1PK7g.o.

**Comment by jneira** [comment]
This is about building the ghcide executable and it is not advisable to use it standalone. @augustss any chance to check if lastest hls is buildable with `cabal v1-install`?

**Comment by jneira** [comment]
closing as v1 commands are deprecated and ghcide executable is not the recommended way, feel free to reopen if you hhit this with hls
