### ISSUE TITLE
Hover/go to definition do not work with top-level splices

### ISSUE THREAD

**Issue by mpickering** [haskell/haskell-language-server#733]
If you have a top-level splice then when you hover over it you get information about the generated code rather than the source program. I made a start at fixing this on a branch but got stuck working out how to mix together the splice expressions and the normal HieASTs information. 

The plan for fixing this was:

* Add a hook to capture the spliced expression before it is run (implemented)
* Use this information in the GetHieFile rule in order to add information about the splice expression so it works with hover. (Where I am stuck)

https://github.com/mpickering/ghcide/tree/wip/top-level-splices-hover

**Comment by jneira** [comment]
This should had been fixed by #759 which included https://github.com/mpickering/ghcide/tree/wip/top-level-splices-hover
Thanks!
