### ISSUE TITLE
Intermittent "failed to load packages, cannot satisfy -package <main-lib>" from components other than <main-lib>

### ISSUE THREAD

**Issue by googleson78** [haskell/haskell-language-server#735]
I "randomly" get errors like `ghcide compiled by GHC 8.8 failed to load packages: <command line>: cannot satisfy -package main-lib-name-0.1.0.0` when trying to use ghcide/hls on a component that isn't the main library.

Yes, I am using a matching  version.

The component I'm currently trying to use has some compilation errors (redundant imports + `-Werror`), that did indeed pop up when I tried to run hls(/ghcide) from the command-line, however after them, the error from above pops up also, seemingly overwriting the previous errors from when trying to use hls/ghcide from within an IDE (nvim + LanguageClient-neovim). When I fix these errors I can load the component/file just fine.

I'm using `stack`.

Here's a version of the hls log, with concrete names edited out: https://gist.github.com/googleson78/bb431e4cdd791ddafed36200fdbc2a16

Is there anything I can do while in this "state" to provide more debug info/attempt some kind of fix?

**Comment by googleson78** [comment]
Another observation: if I get it to a working state by doing the "build lib manually" workaround, and then change something in the lib, I have to do the workaround again.

**Comment by drsooch** [comment]
> Another observation: if I get it to a working state by doing the "build lib manually" workaround, and then change something in the lib, I have to do the workaround again.

I can confirm this is how I've been working for the last couple of days. Anytime my project recompiles (the executable or test-suite) it seems to pop the error again. I can't say for certain but I am 95% sure it's when there is a compile error in the dependent component. 

If it helps any, I have my ghc-options set for `"$targets": -Werror` in `stack.yaml`. After changing this I can't seem to reproduce it (did only minor testing).

**Comment by googleson78** [comment]
This is extremely annoying, is there anything I can do to push this forward? Any clues for what's going on, i.e. where one should look if they choose to look into this?

**Comment by jneira** [comment]
summoning @fendor in case we can do something in the `hie-bios` component, at least link an issue that tracks stack needed changes (if that is the case, i am not sure tbh)

**Comment by hsek** [comment]
Ran into this issue as well in VSCode. I had to restart the editor every time the "could not find module" error pops up, which is pretty tiring to do. I also tried out what @googleson78 instructed in #1909, and I think I was able to reproduce the issue reliably outside VSCode with just HLS. So it seems to be an HLS issue since Stack detects the modules just fine, while HLS complains about it not finding the module.

After trying it out with just HLS, I hopped onto VSCode, and HLS reported a different issue, which was also mentioned in the original post, about not satisfying the package. To which I had to `stack clean` and `stack build` for it to go away. But the main issue still remains that HLS does not detect the new modules until I perform a full editor restart.

You can try it out in this repo: https://github.com/hsek/quad-ci/tree/fa44eb79b6b6085fc7326f88973e5047936d7efd

`Sample` module is the new module I introduced, which HLS failed to detect but Stack did just fine. You'd have to make a new one, then import it to the `test/Spec.hs`. Following [this](https://github.com/haskell/haskell-language-server/issues/1909#issuecomment-859578376) with just HLS provided in nix will give a different error compared to stack.

**Comment by Fubuchi** [comment]
You don't need to restart VSCode, just need to restart the LSP after run `stack clean && stack build`. Still very annoying.

The best thing I can do at the moment is combining all those steps to tasks.json like this:
```
{
    "group": "build",
    "type": "shell",
    "label": "haskell clean & build",
    "command": "stack clean && stack build"
},
{
    "label": "rebuild and reload LSP",
    "command": "${command:haskell.commands.restartServer}",
    "dependsOn": [
        "haskell clean & build"
    ]
}
```

**Comment by jneira** [comment]
@Fubuchi thanks for the tip to automate the workaround, sweet!

**Comment by fyusuf-a** [comment]
I get this problem with haskell-language-server v1.2.0.0 and it does not go away with `stack clean && stack build`. Of course, the versions are the same. It is utterly annoying.

**Comment by hsek** [comment]
I think it might be setup with nix cause afaik it's still at 1.2.0.

**Comment by jneira** [comment]
hmm dont know much about nix but i think other maintainers uses the last version 🤔

**Comment by jneira** [comment]
@hsek agree in this should be annoying but at least the workaround works for you?

**Comment by hsek** [comment]
I've moved to emacs + cabal so I'm not sure, sorry.

**Comment by fyusuf-a** [comment]
> @fyusuf-a do you use an older version of hls due to some reason?

@jneira  The building process of hls is quite long. I built it like 6 months ago I guess with ghc-8.8.4 if I remember correctly and I have not had the courage to build it again since. I will try and use the last version and keep you posted.

**Comment by jneira** [comment]
Ok i think this is essentially #366 and is triggered in test/exe/bench components if the package lib has a compile errors when loading the project.
@googleson78 and the rest of participants: thanks for the tests and the info provided. If any of you thinks this issue differs from #366 please reopen.
Will post the @Fubuchi workaround there

**Comment by meSmashsta** [comment]
Guys, I am still experiencing this issues, work around was doing what this comment instructed:
https://github.com/haskell/haskell-language-server/issues/735#issuecomment-730507961

**Comment by ProofOfKeags** [comment]
I am now encountering this. Seems that the workarounds no longer work. It just randomly stopped working on me. Don't know how to get it back to a state where it was working.

**Comment by sebastian-j-ibanez** [comment]
> This also happens to me, but it goes away after I compile `<project>:lib` target with `stack build` and restart the language server.

I was having this issue with a newly initialized stack project and HLS. I can confirm that the issue goes away after building and reconnecting to HLS.

(I work on Emacs 29 with eglot)
