### ISSUE TITLE
ghcide stuck on a failed hie.yaml with no feedback 

### ISSUE THREAD

**Issue by teto** [haskell/haskell-language-server#737]
I have this faulty hie.yaml  (as in .OUT/generated.flags didn't exist) 
```
cradle:
  bios:
    shell: cat ".OUT/generated.flags" > $HIE_BIOS_OUTPUT
```
and I had ghcide 0.4.0 stuck on
```
Step 1/4: Finding files to test in /home/teto/nova/project
```
Hopefully `hie-bios debug` showed the error. 

at some point I also had symlink cycles in my folders and IIRC I had ghcide endlessly looking for files without much to guess why (even with --verbose).

**Comment by jneira** [comment]
@teto are you still experienced the issue with newer versions of hls?

**Comment by teto** [comment]
I've improved my hie.yaml alot since then, I dont see the issue anymore.
