### ISSUE TITLE
Support for function call hierarchy

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#738]
(From https://github.com/mpickering/ghcide/issues/18)
* It is a feature common in other ides like eclipse or intellij
* It shows the graph of all transitive calls of a function, in a tree:
  * The nodes are selectable (shows info in the right pane) and navigable with ctrl+click
  * In the right pane other info like the possible multiple calls in the same funcion, with the line number (also navigables to the concrete line)

![imagen](https://user-images.githubusercontent.com/54035/81186841-96ca9c00-8fb3-11ea-8652-676a2f805fb9.png)

![imagen](https://user-images.githubusercontent.com/54035/81189571-03936580-8fb7-11ea-9eee-f68b2c93509b.png)

* It could use @wz1000 HieDB, like the recent find references implementation
* It is supported in lsp 3.16: 
  * https://microsoft.github.io/language-server-protocol/specifications/specification-3-16/
  * https://github.com/microsoft/language-server-protocol/issues/468

**Comment by alanz** [comment]
> LSP 3.16 is not out yet

It is now.

**Comment by July541** [comment]
To whom it may concern, I'm tackling this feature as my GSoC 2021 works. I make this comment to avoid duplication:)

**Comment by July541** [comment]
Hello all, currently I am focusing on extract `kind` and `span` info from `HieAST`, and some details baffled me.

1. the `record field` has two components, and the [`RecField`](https://hackage.haskell.org/package/ghc-8.10.2/docs/src/HieTypes.html#RecField) is about `Int`, and another out target `a` is relevant to [`ValBind`](https://hackage.haskell.org/package/ghc-8.10.2/docs/src/HieTypes.html#ValBind). see https://github.com/July541/haskell-language-server/blob/7a8979d7576e1e5d39e2f32f09511b1090925881/plugins/hls-call-hierarchy-plugin/test/Main.hs#L48
2. `type family` and `data family` are all under [`FamDec`](https://hackage.haskell.org/package/ghc-8.10.2/docs/src/HieTypes.html#FamDec),  the span for `type family` is the whole expression like `type family A`, but the span for `data family` for example `data family A` is just the keyword `data family` without `A`. see https://github.com/July541/haskell-language-server/blob/7a8979d7576e1e5d39e2f32f09511b1090925881/plugins/hls-call-hierarchy-plugin/test/Main.hs#L103
--- 
@wz1000, it'd be appreciated if you have time to take a look at it.

**Comment by July541** [comment]
The original reachable query in `HieDb` is for the whole graph, which not satisfy the call hierarchy that only requires one-hop vertexes. So I wrote some additional queries in my plugin, it has initial workability but still needs a deeper query to distinguish multi type with the same name like `typeclass`.

---

I still take much time to differentiate the behaviors between FOIs(file of interest) and non-FOIs, it seems FOIs can not extract `HieAst` from `Shake`, which cause it must require `HieDb` result.

**Comment by pepeiborra** [comment]
> The original reachable query in HieDb is for the whole graph, which not satisfy the call hierarchy that only requires one-hop vertexes. So I wrote some additional queries in my plugin, it has initial workability but still needs a deeper query to distinguish multi type with the same name like typeclass.

Would it be better to move this discussion to the #1955 PR? I think that @wz1000 suggested the use of hiedb there. 

> I still take much time to differentiate the behaviors between FOIs(file of interest) and non-FOIs, it seems FOIs can not extract `HieAst` from `Shake`, which cause it must require `HieDb` result.

Can you clarify this remark? Both FOIs and non-FOIs are able to request `HieAst` via `use GetHieAst`. It's only during startup that the hiedb is used to locate the hie file for non FOIs.

**Comment by July541** [comment]
> Both FOIs and non-FOIs are able to request `HieAst` via `use GetHieAst`. 

@pepeiborra Can I understand that `GetHieAst` has the same result for both FOIs and non-FOIs?

For `HieDb` discussion, I'll push some code later as support.

**Comment by pepeiborra** [comment]
> > Both FOIs and non-FOIs are able to request `HieAst` via `use GetHieAst`.
> 
> @pepeiborra Can I understand this as `GetHieAst` has the same result for both FOIs and non-FOIs?

Yes, as far as I can tell.

**Comment by July541** [comment]
To whom it may concern, the [call hierarchy](https://github.com/haskell/haskell-language-server/pull/1955#issuecomment-877804383) has basic functions.🚀🚀🚀

**Comment by jneira** [comment]
Many, mant thanks @July541 for implementing this long time awaited feature. It has been really welcomed by users.
So closing this with a big :tada:
