### ISSUE TITLE
Odd hover behaviour with comments

### ISSUE THREAD

**Issue by michaelpj** [haskell/haskell-language-server#743]
If I hover over a Haddock comment for a function *or* any comment preceding such a comment, I get a type hover for the *previously declared* function without the name.

e.g.
```
f :: a -> b
-- comment1

-- | comment2
g :: b -> c
```

Hovering over either `comment1` or `comment2` I see `_ :: a -> b`. If there is no preceding function I don't get a hover.

I think this is maybe something wrong with the spans in the HIE files or something? If they were incorrectly being set to "start of function definition -- start of next function definition" then the span for f could cover those comments.

### Your environment
* `hls` version 0.3.0.0 (I can try again with a newer version)
* ghc 8.8.3
* emacs
* cabal project

### Steps to reproduce

I think the example I gave should reproduce, but I extracted it from the middle of my project, so it might not.

### Expected behaviour

Probably no hover on comments!

**Comment by Anton-Latukha** [comment]
Maybe this is fixed by now?

**Comment by jneira** [comment]
The initial example could be used as a regression test which would be nice to add (if it does not exist)

**Comment by michaelpj** [comment]
The reason I got stuck on this was that I couldn't reproduce it without a quite chunky example, which was a bit disappointing. I'll try and reproduce with more recent versions.

**Comment by michaelpj** [comment]
Haven't noticed this recently
