### ISSUE TITLE
Position mapping is occasionally broken

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#744]
Noticeable when your code doesn't type check, after a few edits. Screenshots attached
This is a regression from 0.2.0.

Last good code:
![image](https://user-images.githubusercontent.com/26626/90231102-8a57aa00-de12-11ea-85c3-97bde8c510c5.png)

Edited code:
![image](https://user-images.githubusercontent.com/26626/90230971-4d8bb300-de12-11ea-858f-18788ccdffa2.png)

Bad hover:
![image](https://user-images.githubusercontent.com/26626/90230936-41075a80-de12-11ea-8cc8-1a2458b5eb92.png)

**Comment by jneira** [comment]
I wonder if it is reproduced with lastest versions of hls and lsp

**Comment by michaelpj** [comment]
No recent reproductions, tentatively closing

**Comment by soulomoon** [comment]
We have fixed that in https://github.com/haskell/haskell-language-server/pull/3920
