### ISSUE TITLE
Don't put type on newline

### ISSUE THREAD

**Issue by hexagonal-sun** [haskell/haskell-language-server#745]
Hi,

I'm using `ghcide` with doom Emacs and whenever I hover over a piece of code I expect to see the type, however all that is seen is the fully qualified name:

![foo](https://user-images.githubusercontent.com/222664/90286041-eb13d080-de6c-11ea-9596-34abfa913883.png)

I believe that the type is there, it's just hidden on a newline as when I ask for a full definition of `print` I get:

![foo_000](https://user-images.githubusercontent.com/222664/90286112-1696bb00-de6d-11ea-9b3c-b95ba37e1ae9.png)

Could we add a switch or something to make `ghcide` render the type on the same line?

Finally, apologies if this issue is in the wrong place. I'm not entirely sure how the LSP architecture works; whether `ghcide` is responsible for formatting the type information or something else.

Thanks!

**Comment by jneira** [comment]
@hexagonal-sun as commented by @rayshih, that problem seems to be related with the client. I would consider open an issue in the editor (or lsp plugin) project issue tracker
