### ISSUE TITLE
Completion triggering is flaky

### ISSUE THREAD

**Issue by georgefst** [haskell/haskell-language-server#747]
I sometimes have difficulties getting completions to show up (when using VScode's "Trigger Suggest", bound by default to `ctrl`+`space`). For example:

- If I use Ghcide's completion for the `import` keyword, import suggestions won't show. They will if I type `import` manually.
- Typing `{-# LANGUAGE ` doesn't trigger the extensions list. Deleting the actual extension name from an existing pragma does. Edit: This seems to be affected by the closing brace that VScode automatically inserts after typing the opening one - if I delete the closing brace before getting further than the first 'a' of 'language' (seriously, this is reproducible as the cut-off point), then the extension list will show up when I complete the word.

I've looked at what appears to be the relevant code e.g. [here](https://github.com/digital-asset/ghcide/blob/765967d19be4ca64abc999173029a6bfe6aec113/src/Development/IDE/Plugin/Completions/Logic.hs#L447-L459), but can't see anything obvious. So I guess the issue is further up the chain, and that code isn't always being triggered when I'd expect.

Ideally, I'd like to make use of the following VScode snippets, but for reasons related to the above, only the first is truly useful:
```json
{
    "OPTIONS_GHC pragma": {
        "prefix": "options",
        "body": [
            "{-# OPTIONS_GHC -$0 #-}"
        ],
        "description": "OPTIONS_GHC pragma"
    },
    "LANGUAGE pragma": {
        "prefix": "language",
        "body": [
            "{-# LANGUAGE $0 #-}"
        ],
        "description": "LANGUAGE pragma"
    },
    "import": {
        "prefix": "import",
        "body": [
            "import $0"
        ],
        "description": "import"
    }
}
```

Ghcide (or HLS) head. GHC 8.10.1.

**Comment by pepeiborra** [comment]
Please reopen if needed
