### ISSUE TITLE
Hole suggestions doesn't properly qualify the result

### ISSUE THREAD

**Issue by anka-213** [haskell/haskell-language-server#750]
If I import a module qualified
```
import qualified Data.List as L
```
and then ask vscode to fill a hole with something from there
```
myTails :: [a] -> [[a]]
myTails = _
```
it will pretend that it was available unqualified
```
myTails :: [a] -> [[a]]
myTails = tails
```
which Haskell will complain about again, but fortunately ghcide gives a suggestion to automatically fix it, so after another `⌘-. <Enter>` I will end up with what I wanted.
```
myTails :: [a] -> [[a]]
myTails = L.tails
```
The last step shouldn't be needed though.

**Comment by pepeiborra** [comment]
Fixed by haskell/ghcide#938
