### ISSUE TITLE
Special case the type of main

### ISSUE THREAD

**Issue by aherrmann** [haskell/haskell-language-server#751]
Consider the following code snippet:
```
module Main where
import Control.Monad (unless)
main = unless True $ pure ()
```
It compiles without error
```
$ ghc Main.hs
[1 of 1] Compiling Main             ( Main.hs, Main.o )
Linking Main ...
```
But, `ghcide` produces the following diagnostic on `unless True`.
```
[typecheck] [E] • Ambiguous type variable ‘f0’ arising from a use of ‘unless’
  prevents the constraint ‘(Applicative f0)’ from being solved.
  Relevant bindings include
    main :: f0 ()
      (bound at /home/aj/tweag.io/da/repro/ghcide-monomorphism-restriction/Main.hs:3:1)
  Probable fix: use a type annotation to specify what ‘f0’ should be.
  These potential instances exist:
    instance Applicative (Either e) -- Defined in ‘Data.Either’
    instance Applicative NonEmpty -- Defined in ‘GHC.Base’
    instance Applicative P -- Defined in ‘Text.ParserCombinators.ReadP’
    ...plus six others
    (use -fprint-potential-instances to see them all)
• In the expression: unless True
  In the expression: unless True $ pure ()
  In an equation for ‘main’: main = unless True $ pure ()
```
`ghcide` also suggests the following type signature in a code-lens
```
main = unless True $ pure () ‣ main :: Any () 
```
That is, it suggests `main :: Any ()`.

**Expected Behavior**
I would expect no diagnostic on `unless True`.

I would expect a different suggested type-signature, say `main :: Applicative f => f ()` or maybe `main :: IO ()`.

**To Reproduce**
```
$ cat Main.hs
module Main where
import Control.Monad (unless)
main = unless True $ pure ()
```

```
$ cat hie.yaml
cradle:
  direct:
    arguments: []
```

```
$ ghcide --version
ghcide version: 0.2.0 (GHC: 8.8.2) (PATH: /home/aj/.local/lib/ghcide/ghc88/bin/ghcide) (GIT hash: 1ca896980d65503aa7e668106fb822fc06104632)
```

**Additional Information**
Enabling `NoMonomorphismRestriction` avoids the issue. I.e. the following snippet
```
{-# LANGUAGE NoMonomorphismRestriction #-}
module Main where
import Control.Monad (unless)
main = unless True $ pure ()
```
produces no diagnostic, and the suggested type signature in the code lens reads `main :: Applicative f => f ()`.

**Comment by jneira** [comment]
@aherrmann hi! i tried to reproduce the issue using hls-1.5.1 and directly ghc and with a .cabal file and i am not being able:

![imagen](https://user-images.githubusercontent.com/54035/144566462-5a9f2e97-fe93-4f63-8f4b-d4faa7b2d59f.png)

So i guess this has been fixed at some point. Will close it optimistically, feel free to reopen if you continue experiencing it
