### ISSUE TITLE
Doesn't jump to literate Haskell file and doesn't reload it either

### ISSUE THREAD

**Issue by turion** [haskell/haskell-language-server#755]
For modules defined as literate Haskell, jumping to source doesn't work. Similarly, changes to these files don't get reloaded automatically.

_To reproduce:_

```
git clone https://github.com/turion/essence-of-live-coding
cd essence-of-live-coding
gen-hie > hie.yaml
codium
```

(This is assuming VSCodium with the ghcide extension as editor.)

1. Navigate to a test file like `essence-of-live-coding/test/Main.hs`
2. Navigate to line 21
3. Press F12 or select "Jump to source"
4. "No definition found for 'LiveCoding'"
5. Change anything in the module `essence-of-live-coding/LiveCoding.lhs`, e.g. add a definition
6. Try to use this definition in the test
7. It's not found

```
$ ghcide --version
ghcide version: 0.2.0 (GHC: 8.8.3) (PATH: /nix/store/hvdw1f7nwjns5j3jxd9wjkx4jnvb8vw7-ghcide-0.2.0/bin/ghcide)
```
(I'm running from a `nix-shell`)

**Comment by jneira** [comment]
@turion had you the opprtunity to check lhs files with haskell-language-server (ghcide is being deprecated as external executable)?

**Comment by turion** [comment]
Yes, it works. Thank you!
