### ISSUE TITLE
Variable not in scope:htf_xxx_thisModulesTests :: TestSuite from Test.Framework

### ISSUE THREAD

**Issue by andrewufrank** [haskell/haskell-language-server#770]
I use the [`Test.Framework`] (https://hackage.haskell.org/package/test-framework-0.8.2.0/docs/Test-Framework.html). Test.Framework uses a precompiler to produce code, called with `{-# OPTIONS_GHC -F -pgmF htfpp #-}`.
ghcide complains that the variable produced by the precompiler are not seen. How can I handle this in the `yaml` file?

**Comment by pepeiborra** [comment]
@andrewufrank is this ticket still relevant or can it be closed?

**Comment by jneira** [comment]
@andrewufrank i am gonna close this optimistically, feel free to reopen if you continue experiencing the error with hls (as ghcide is deprecated as external executable)
