### ISSUE TITLE
Multi-component could perform downsweep in order to discover targets

### ISSUE THREAD

**Issue by mpickering** [haskell/haskell-language-server#778]
At the moment, each cradle has to explicitly list all the targets for that component. This is how most build tools (ie cabal-install hadrian etc) interact already with ghci but sometimes build tools do not list all the targets for whatever reason. This works in GHCi because GHC will automatically perform dependency analysis using the given targets and discover the missing ones. ghcide does not do this dependency analysis because it wasn't exactly clear how to do the analysis without causing a circular dependency at some point. 

It would be nicer if ghcide was also a bit more robust to missing targets if someone could work out how to invoke the downsweep logic without needing to call a `GhcSession` rule.

**Comment by michaelpj** [comment]
I think this is obsoleted by proper multi-component support
