### ISSUE TITLE
Incorrect error about orphan instances due to ghc session module loading

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haskell-language-server#779]
Given Ghcide HEAD, Windows, GHC 8.6.5, 64bit, VS Code and HLint HEAD (https://github.com/ndmitchell/hlint 90dde61ab2039597709e20f444a369d3a1f791b5) I get an error. `ghcide` on the command line works fine. However,, if I:

* Open the file src\Hint\Bracket.hs - observe no errors or warnings.
* Introduce a parse error, correctly see a parse error.
* Remove the parse error. I would expect no errors or warnings but I get:

```
{
	"resource": "/C:/Neil/hlint/src/Hint/Bracket.hs",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "• Overlapping instances for Uniplate a\n    arising from a use of ‘holes’\n  Matching instances:\n    instance Data a => Uniplate a\n      -- Defined in ‘Data.Generics.Uniplate.Data’\n    instance Uniplate BriDoc\n      -- Defined in ‘Language.Haskell.Brittany.Internal.Types’\n  (The choice depends on the instantiation of ‘a’\n   To pick the first instance above, use IncoherentInstances\n   when compiling the other instance declarations)\n• In the second argument of ‘($)’, namely ‘holes o’\n  In the expression: zipFrom 0 $ holes o\n  In a stmt of a list comprehension:\n    (i, (x, gen)) <- zipFrom 0 $ holes o",
	"source": "typecheck",
	"startLineNumber": 197,
	"startColumn": 73,
	"endLineNumber": 197,
	"endColumn": 80
}
```

It points at `holes o`.  I suspect a related factor is that Data.Generics.Uniplate.Data defines a global Uniplate instance, which does indeed conflict with `Uniplate BriDoc`, but I'm at a loss as to how Brittany gets loaded at all. The fact we load Brittany in fact seems like a bug on its own, as its likely costing time/memory to do so.

No idea how to debug from here, but happy to give it a prod if someone tells me how.

**Comment by michaelpj** [comment]
I think this is obsoleted by proper multi-component support.
