### ISSUE TITLE
Go-to definition jumps to hs-boot files

### ISSUE THREAD

**Issue by mpickering** [haskell/haskell-language-server#790]
If an identifier is defined in a hs-boot file then jumping to the definition will jump into the hs-boot file.

Technically, this is where the definition is, but really it would be better to jump to the definition in 
the source file I think.

**Comment by alanz** [comment]
I just checked on HLS at 6b0740c476192178a4d9eea96b1a2a8b1c9e601d, go to definition for `LHsExpr` takes me to the boot file.

**Comment by alanz** [comment]
False alarm, I flushed `~/.cache/ghcide` and it now works as intended.

**Comment by jneira** [comment]
> 
> 
> [haskell/ghcide#898](https://github.com/haskell/ghcide/pull/898) will fix this

the pull request in this repo is: #704

**Comment by wz1000** [comment]
> False alarm, I flushed ~/.cache/ghcide and it now works as intended.

I suspect it will come back on a boot with a primed cache since we will load the locations from `.hi` files instead of the `NameCache`.

**Comment by alanz** [comment]
Ok, so I must just kill the cache on startup :)

**Comment by wz1000** [comment]
You can also use my branch :)
