### ISSUE TITLE
Hover performance is still far too slow (and worse with multiple threads)

### ISSUE THREAD

**Issue by mpickering** [haskell/haskell-language-server#791]
There have been previous issues about hover performance in big projects but so far no substantial progress has been made. 

I tried again today on `ghc/Main.hs` with the `wip/multi-rebased` branch which is based on haskell/ghcide#457 and things seemed very bad still.

* With `optThreads = 1` - Hover time was 2.2s
* With `optThreads = 0` - Hover time was 6.5s

I tried on the command line and in the editor and could reproduce similar numbers in both, so it's not entirely to do with the `FileExists` logic which previously closed haskell/ghcide#101. 

Here is the profile of performing a single hover request.

https://gist.github.com/mpickering/c12db7d1b9c0724024259f8411189ca6

Load the JSON into [`speedscope.app`](speedscope.app) in order to view it. 

I can't believe that I am the only person who observes this or wants this fixed! But it seems like I am so far the only person to complain about it. 

Also see haskell/ghcide#101 and haskell/ghcide#485

**Comment by jneira** [comment]
Not sure if this issue is actionable, is hover still too slow? what should be do if it is?

**Comment by mpickering** [comment]
I think this is mostly fixed, at least hover is now quite fast. I still suspect that there is some poor thread utilisation by shake but it's no longer on the critical path.
