### ISSUE TITLE
ghcide does not deal with relative source directories well

### ISSUE THREAD

**Issue by mpickering** [haskell/haskell-language-server#793]
For a long time ghcide has been broken when working on GHC because hadrian was providing relative source directories (`-i` flags to ghcide). This leads to a bunch of confusing errors about paths not existing and so on. Today I tried to fix it by providing absolute paths and it made things work much better.

`ghcide` should probably canonicalise all paths and make sure to only use absolute paths.

**Comment by pepeiborra** [comment]
Closing due to lack of confirmation.
