### ISSUE TITLE
Hover only shows the instantiated type signature

### ISSUE THREAD

**Issue by Avi-D-coder** [haskell/haskell-language-server#795]
For instance only the monomorphic show up when hovering over `map`.
```haskell
GHC.Base.map
:: (Int -> Int) -> [Int] -> [Int]
```
```
mapInt :: (Int -> Int) -> [Int] -> [Int]
mapInt = map
```

This makes it harder to figure out what went wrong when there are type errors.

`hie`'s out put here is better, although the `forall` seems noisy.
```
map :: (Int -> Int) -> [Int] -> [Int]
map :: forall a b. (a -> b) -> [a] -> [b]
```

**Comment by jneira** [comment]
Being ghcide deprecated as external executable and having the feature in hls, i think this can be closed
