### ISSUE TITLE
Consider using Reflex backend

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haskell-language-server#796]
@mpickering wrote a port to a Reflex backend: https://mpickering.github.io/posts/2020-03-16-ghcide-reflex.html. See https://github.com/mpickering/ghcide/tree/reflex

I'm sceptical that the 1s slowdown on hover is due to Shake overheads, so it would be good to get profile reports showing that. I suspect there's something else we're doing that is taking the 1s, and that should probably be fixed - but the profile will tell us all.

In the longer run, we all knew a well-tested FRP would be a better fit. @mpickering, is this a path towards Ghcide 1.1, or an experiment that we should use to guide future FRP/Ghcide evolution so they collide at a future date?

**Comment by pepeiborra** [comment]
Now that we have reactive builds via reverse dependencies in Shake, is there any reason to consider Reflex?

**Comment by jneira** [comment]
will close soon if nobody disagree

**Comment by jneira** [comment]
closing, @ndmitchell feel free to reopen if you think the suggestion is still sensible after last changes in ghcide
