### ISSUE TITLE
Record quick fixes based on fields should be deduped

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haskell-language-server#798]
![image](https://user-images.githubusercontent.com/1651197/75113626-6f686200-5647-11ea-9354-83a7b6b58f67.png)

Not sure what version of ghcide I'm on...

**Comment by ishmum123** [comment]
@jneira this might be a noob question. What's the consequence of changing the line to this
        `= [("Add " <> x <> " extension", [TextEdit (Range (Position 0 0) (Position 0 0)) $ "{-# LANGUAGE " <> x <> " #-}\n"]) | x <- (Set.toList $ Set.fromList exts) ]`
?

**Comment by jneira** [comment]
it could work, a test case would be the definitive evidence 🙂

**Comment by ishmum123** [comment]
@jneira can you help me a bit? I am a bit lost on where to provide the pull request for ghcide

**Comment by jneira** [comment]
@ishmum123 sorry for the delay, the pull request should be done in this repo, now that ghcide lives here.

But the code responsive of suggest language extensions has been removed from ghcide, cause hls had already a plugin to do the same.
However it suffer the same bug, i think the relevant code there could be:

https://github.com/haskell/haskell-language-server/blob/3145830b1b9266784f17b0000fed6c445b981832/plugins/default/src/Ide/Plugin/Pragmas.hs#L71

**Comment by ishmum123** [comment]
Thank you very much

**Comment by Ailrun** [comment]
I'm not super confident, but I think it wont't fix this issue as this issue is caused by multiple diagnostics, not by a single diagnostic.

**Comment by jneira** [comment]
Mmm, @Ailrun you are right and the fix becomes more complex, i am afraid. ghc is giving us a waning for each field so the alternatives i can think of is:

* fix ghc to only emit one warning per record constructor (that would be the right one, but we would be blocked upstream)
* filter diagnostics in hls (not sure if possible or feasible)
* only emit one code action although we get several diagnostics. I would be feasible i we can access to the set of actual diagnostics (and i think there is a field stored somewhere) or code actions and only emit the new code action if it is not redundant

**Comment by berberman** [comment]
You can use `getDiagnostics` to get global diagnostics, like this:
https://github.com/haskell/haskell-language-server/blob/79c5cc75d9c3b63a03194fc7540e61a63b8b3df6/ghcide/src/Development/IDE/Plugin/CodeAction.hs#L82

**Comment by ishmum123** [comment]
@berberman you probably did a much better job than I did. I was working on it for a while, so thought I should push the fix if it's of any use.

**Comment by berberman** [comment]
@ishmum123 Oops, really sorry, I should ask first if someone has already started working on this :(
