### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by adamConnerSax** [haskell/haskell-language-server#802]
I know versions of this have been reported before but I thought this might be a useful data point and maybe a way for me to get things to try...
I'm using ghcide-0.1.0.0, with ghc-8.6.5, from emacs (with recent versions of hie-bios and haskell-lsp) on Mac OSX 10.15.3. 
It works fine but memory usage (of ghcide) starts at about 5GB, grows fast and eventually (an hour of editing a few files in the project) makes things too slow.  So I kill it and then emacs asks me to restart and it all works fine for a while.  
One observation: I was using ghcide 0.0.6 and the same thing would happen but much more slowly.  I'd maybe restart once a day instead of once an hour.
Anything I can try to improve this or help debug it?

**Comment by jneira** [comment]
@mpardalos dont want to bother you too much but gsoc has finished some time ago afaik: do you have some additional insights about this issue? thanks :slightly_smiling_face:

**Comment by mpardalos** [comment]
@jneira my GSoC time ended before I had a chance to address this memory leak, however, I had done work on identifying what exactly was causing the memory leak that was merged into ghcide as https://github.com/haskell/ghcide/pull/922, and that should help in finding a fix

I have discussed some findings in https://github.com/haskell/ghcide/pull/826 (which ended up becoming https://github.com/haskell/ghcide/pull/922) that you might find useful.

**Comment by jneira** [comment]
not sure if last changes around performance in hls 1.5.0 would affect this

**Comment by jneira** [comment]
@adamConnerSax hi, there had been lot of changes since the issue and we have newer issues about memory usage, so i am gonna close this one. If you continue expriencing excessive memory usage with the last hls version feel free to comment in any of the newer memory issues or open a new one if no one match your observations
