### ISSUE TITLE
Replace GetModificationTime with a file version scheme via WatchedFile events

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#803]
The idea is to replace `GetModificationTime`, which is expensive and called on every change, by a  new rule `GetFileVersion` implemented entirely on top of watched file events. This would reduce I/O, eliminate timestamp serialization and comparison, and hopefully improve performance 

One possible approach is to generalize the `FileExistsMapVar` in order to keep track of file versions.

**Comment by jneira** [comment]
@pepeiborra does it worth keeping this opened? asking due to this comment:

> Implemented both 1 and 2, but doesn't seem to pay off massively.

**Comment by pepeiborra** [comment]
Yes, I think it's still worth keeping this open. Back when I implemented 1 and 2 we didn't have a good benchmarking suite, and on paper this optimisation should be very much worth it.

**Comment by michaelpj** [comment]
We could also use the file change events that we get from watching files to update modification times.
