### ISSUE TITLE
CPP errors on Windows aren't reported correctly

### ISSUE THREAD

**Issue by ndmitchell** [haskell/haskell-language-server#805]
When I break a CPP file on Windows, with an unterminated `#ifdef` or similar, I get the error:

```
`gcc.exe' failed in phase `C pre-processor'. (Exit code: 1)
```

The root cause is a GHC issue, namely https://gitlab.haskell.org/ghc/ghc/issues/17786.

But we should be able to do better. GHC manages to capture the stderr of the process and display that alongside the rest - we should do that if we don't have any better information (if GHC has exposed it). We might even be able to fix GHC's error capture stuff to get it right on older GHC versions until the fix trickles in.

**Comment by jneira** [comment]
> 
> 
> The test for cpp error is marked as ignored in windows due to this

The mentioned test is

https://github.com/haskell/haskell-language-server/blob/fde10fa5e4cb74ca4b64c43250297b36a9bbbd7e/ghcide/test/exe/Main.hs#L2717-L2732

**Comment by jneira** [comment]
The ghc issue is closed with the mr https://gitlab.haskell.org/ghc/ghc/-/merge_requests/2622 in 2020-10-04 so it should be in ghc-9.0.1
Not sure what is going on but with 9.0.1 i don get any error at all:

![imagen](https://user-images.githubusercontent.com/54035/143652822-8787946d-7c37-4764-8e23-3d8bfa5ae977.png)

**Comment by michaelpj** [comment]
I think given that the GHC issue is closed we can presumptively close this as fixed unless someone notices it recurring.
