### ISSUE TITLE
Add performance regression tests and benchmarks

### ISSUE THREAD

**Issue by cocreature** [haskell/haskell-language-server#807]
It would be good to have some performance regression tests. We have a small wrapper around `lsp-tests` in DAML https://github.com/digital-asset/daml/blob/master/compiler/damlc/ide-debug-driver/README.md that makes it easy to script sessions which I’ve used successfully in the past to track down performance issues which might come in handy here.

**Comment by jneira** [comment]
I supposethis still is not done

**Comment by soulomoon** [comment]
done in #4203
