### ISSUE TITLE
Add installation and usage instructions

### ISSUE THREAD

**Issue by jneira** [haskell/haskell-language-server#85]
Checklist:
* [ ] Installation
  * [ ] Nix (?)
  * [X] From source
* [ ] Editor integration
  * [ ] *vscode*
  * [ ] vim/neovim
  * [ ] sublime
  * [ ] atom
  * [X] emacs
  * [X] doom emacs
  * [ ] spacemacs (?)
  * [X] kakoune

**Comment by alanz** [comment]
We should be able to bring the info from hie directly, it honours the same arguments.

lsp-haskell has a customize option for it, setting the path to haskell-language-server-wrapper instead of hie-wrapper in any client should just work.

**Comment by jneira** [comment]
Yeah, i think one little caveat is hls does not accept the `--vomit` cli option set by the extension if you choose the verbose mode.

> setting the path to haskell-language-server-wrapper instead of hie-wrapper in any client should just work

basically it is the key change, you have to set `useCustomHieWrapper` to true too

```json
{
    "languageServerHaskell.useCustomHieWrapperPath": "D:\\bin\\haskell-language-server-wrapper.exe",
    "languageServerHaskell.useCustomHieWrapper": true,
    "languageServerHaskell.trace.server": "messages"
}
```

**Comment by jneira** [comment]
Now there is a vscode extension release that lets choose the server so it is easier.

**Comment by EncodePanda** [comment]
I'm about to go through the process this week and I will be documenting all my steps. Eventually, I will push them to this repo as docs.

**Comment by Sir4ur0n** [comment]
@EncodePanda I'll try to save you some time: pay attention to installing `haskell-language-server` with the same GHC version you use in your project!

I didn't pay attention at first while doing `stack install` and things blew up rather spectacularly in VSCode afterwards :smile:

**Comment by jneira** [comment]
@Sir4ur0n yeah it has to be clearly visible in docs. However, the program should have emit a warning in the output pane and in a popup alert. At least haskell-ide-engine used to do it.

**Comment by jneira** [comment]
I am porting the installation and configuration instruction from hie.

**Comment by theGhostJW** [comment]
Would someone coming from hie and using vs code need to uninstall anything first?

**Comment by fendor** [comment]
Good point.
An upgrading/switching section would be a great idea! 

To give an immediate answer: no, nothing needs to be uninstalled. You can just install hls and point the vscode plugin to use haskell-language-server in its recent settings addition to switch between hie/ghcide/hls.
However, it might make sense to delete unused binaries of hie since they are quite large (like 120MiB, iirc)

**Comment by jneira** [comment]
Well, to close this i think we would add how to use hls with the more used editors (like hie)
I am feel confident to port the vscode part but not sure about others

**Comment by jneira** [comment]
Checklist:
* [ ] Installation
  * [ ] Nix (?)
  * [X] From source
* [ ] Editor integration
  * [ ] *vscode*
  * [ ] vim/neovim
  * [ ] sublime
  * [ ] atom
  * [X] emacs
  * [X] doom emacs
  * [ ] spacemacs (?)
  * [X] kakoune

This issue is about how to install and use (editor integration) hls. Only available methods.

**Comment by Anrock** [comment]
Neovim + CoC could be just copypastted from hie, only changing executable name to hls-wrapper.

**Comment by suhdonghwi** [comment]
@Anrock Did you manage to use formatter plugins? For me, running `:call CocAction('format')` silently fails without any error messages.

**Comment by Anrock** [comment]
@suhdonghwi not much of a fan of autoformatting, but 
```
" Formatting selected code.
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)
```
is working on my setup.

**Comment by suhdonghwi** [comment]
@Anrock Thank you! It works well now.
