### ISSUE TITLE
Improved fill hole suggestions 

### ISSUE THREAD

**Issue by pepeiborra** [haskell/haskell-language-server#883]
[A lot of work](https://downloads.haskell.org/ghc/latest/docs/html/users_guide/glasgow_exts.html#typed-holes) has gone into making GHC able to produce suggestions and the current code action falls short of making the most of it. The possibilities include:

- Should it use `-fshow-hole-constraints` to make added constraints explicit?
- Should it use `-fshow-docs-of-hole-fits` to show the docs of the suggestion?
- Should it use `-frefinement-level-hole-fits=1` to show almost-valid fits?
- Should it use `-fsort-by-subsumption-hole-fits` ?

**Comment by Tritlo** [comment]
Note! Valid hole-fits are a lot faster now on HEAD, so this might not be required anymore.
