### ISSUE TITLE
ModBreaks.modBreaks_array not initialised

### ISSUE THREAD

**Issue by remexre** [haskell/haskell-language-server#923]
Tried to use ghcide on a cabal v2 project I hadn't tried it on before, in a bunch of files I now get:

```
  ModBreaks.modBreaks_array not initialised
  CallStack (from HasCallStack):
  error, called at compiler/ghci/ByteCodeTypes.hs:173:24 in ghc:ByteCodeTypes
```

when I run `ghcide src`.

My `hie.yaml` looks like:

```yaml
cradle:
  cabal:
    component: "lib:thingy"
```

so nothing too fancy there.

**Comment by bgamari** [comment]
Nathan Ringo <notifications@github.com> writes:

> Tried to use ghcide on a cabal v2 project I hadn't tried it on before, in a bunch of files I now get:
>
> ```
>   ModBreaks.modBreaks_array not initialised
>   CallStack (from HasCallStack):
>   error, called at compiler/ghci/ByteCodeTypes.hs:173:24 in ghc:ByteCodeTypes
> ```
>
> when I run `ghcide src`.
>
> My `hie.yaml` looks like:
>
> ```yaml
> cradle:
>   cabal:
>     component: "lib:thingy"
> ```
>
> so nothing too fancy there.
>
Which GHC version are you using? IIRC this is only fixed in 8.10.3 and
later
