### ISSUE TITLE
'data' build failure

### ISSUE THREAD

**Issue by georgefst** [haskell/haskell-language-server#93]
On a fresh install, `./cabal-hls-install data` fails with

```
# cabal (for data)
Resolving dependencies...
cabal: Cannot build the package hoogle, it is not in this project (either
directly or indirectly). If you want to add it to the project then edit the
cabal.project file.
```

It's unclear where hoogle is supposed to be coming from.

**Comment by fendor** [comment]
True, there is no hoogle plugin in the project. That is probably the reason why this fails.

You may ignore this failure for installation.
This target doesnt do anything for hls so far, but I would expect it to do something in the future. We should either document that it doesnt do anything at the moment, or comment it out in the script.

**Comment by jneira** [comment]
* The `data`target has been disabled with #112 so it should not fail but print a warning
