### ISSUE TITLE
Inline REPL like in Simple GHC (Haskell) Integration plugin

### ISSUE THREAD

**Issue by fuszenecker** [haskell/haskell-language-server#94]
Hi,

This is a suggestion: it would be great if HLS had an inline REPL feature like [Simple GHC (Haskell) Integration plugin](https://marketplace.visualstudio.com/items?itemName=dramforever.vscode-ghc-simple).

![image](https://user-images.githubusercontent.com/7091194/81264524-d770f680-9041-11ea-8c77-4b7ff3fb05af.png)

This feature makes testing, playing with code lot easier, and is a really unique feature.

**Comment by googleson78** [comment]
#51 is related

**Comment by Avi-D-coder** [comment]
For very simple stuff https://github.com/haskell-hint/hint maybe useful. However, this likely to be the wrong approach, since we really want the appropriate stack or cabal GHCi instance with PKG imports and symbols from the file.

**Comment by jneira** [comment]
@fuszenecker the feature described here is very similar to the actual eval plugin (almost identical?) so maybe we could close this one

**Comment by jneira** [comment]
closing cause it is very similar to an existing feature
