### ISSUE TITLE
Incomplete pattern warnings are not highlighted

### ISSUE THREAD

**Issue by liftM** [haskell/haskell-language-server#96]
When I compile code with an incomplete pattern using `-fwarn-incomplete-patterns`, I see the incomplete pattern warning in my GHC output. I do not see a corresponding highlight for the incomplete pattern in the source code. I discovered this in the VS Code extension, although this appears to also occur in the Emacs extension (so I think it's an LSP rather than extension bug).

**Comment by ndmitchell** [comment]
The root cause is https://github.com/digital-asset/ghcide/issues/107

I suggest this deserves an entry on the HLS FAQ, as it does keep coming up.

**Comment by alanz** [comment]
Until such time as we fix it, somehow.  I think via managing scheduling.

**Comment by jneira** [comment]
As commented in #96 the ghcide issue is https://github.com/haskell/ghcide/issues/107 and it was closed by https://github.com/haskell/ghcide/pull/836 son only left bump the ghcide submodule to include it: https://github.com/haskell/haskell-language-server/pull/463

**Comment by jneira** [comment]
It will be close when #526 is resolved

**Comment by jneira** [comment]
We are using the ghcide version with the fix, @liftM feel free to reopen if it is not the case (not that you should use master until 0.5 version is not resleased)
