### ISSUE TITLE
hover improvements

### ISSUE THREAD

**Issue by alanz** [haskell/haskell-language-server#97]
Some observations from testing with https://github.com/alanz/haskell-language-server/tree/hls-wz1000 at https://github.com/alanz/haskell-language-server/commit/ebad0a1bc28dd0b48eb0d2aa9be784752e0db42d.

I am using `lsp-mode` on emacs 26.3, comparing the hover output for `Integer` in the snippet

```haskell
{-# LANGUAGE MultiParamTypeClasses #-}
module B where
--
-- TODO2 added by Example2 Plugin directly
--
--
--
foo :: Integer
foo = 4

class Foo a b where
  baz :: a -> b

```

## haskell-ide-engine (1.3)

```json
[Trace - 09:19:58 ] Received response 'textDocument/hover - (47)' in 27ms.
Result: {
  "range": {
    "end": {
      "character": 14,
      "line": 7
    },
    "start": {
      "character": 7,
      "line": 7
    }
  },
  "contents": {
    "value": "Invariant: `Jn#` and `Jp#` are used iff value doesn't fit in `S#`\n\nUseful properties resulting from the invariants:\n\n- \n```haskell\nabs (`S#` _) <= abs (`Jp#` _)\n```\n\n- \n```haskell\nabs (`S#` _) <  abs (`Jn#` _)\n```\n\n\n\n[Documentation](file:///home/alanz/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/share/doc/ghc-8.6.5/html/libraries/integer-gmp-1.0.2.0/GHC-Integer.html#t:Integer)\n\n[Source](file:///home/alanz/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/share/doc/ghc-8.6.5/html/libraries/integer-gmp-1.0.2.0/src/GHC-Integer-Type.html#Integer)\n\ninteger-gmp GHC.Integer.Type",
    "kind": "markdown"
  }
}
```

The contents of the markdown is

<pre>
Invariant: `Jn#` and `Jp#` are used iff value doesn't fit in `S#`

Useful properties resulting from the invariants:

- 
```haskell
abs (`S#` _) <= abs (`Jp#` _)
```

- 
```haskell
abs (`S#` _) <  abs (`Jn#` _)
```

[Documentation](file:///home/alanz/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/share/doc/ghc-8.6.5/html/libraries/integer-gmp-1.0.2.0/GHC-Integer.html#t:Integer)

[Source](file:///home/alanz/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/share/doc/ghc-8.6.5/html/libraries/integer-gmp-1.0.2.0/src/GHC-Integer-Type.html#Integer)

integer-gmp GHC.Integer.Type

</pre>

### haskell-language-server as above

```json
[Trace - 09:17:38 ] Received response 'textDocument/hover - (31)' in 12ms.
Result: {
  "range": {
    "end": {
      "character": 14,
      "line": 7
    },
    "start": {
      "character": 7,
      "line": 7
    }
  },
  "contents": {
    "value": "\n```haskell\nInteger\n```\n\n*Defined in ‘GHC.Integer.Type’*\n\n\nInvariant:  `Jn#`  and  `Jp#`  are used iff value doesn't fit in  `S#` \n\nUseful properties resulting from the invariants: \n+ ```haskell\n  abs ( `S#`  _) <= abs ( `Jp#`  _)\n  ```\n\n+ ```haskell\n  abs ( `S#`  _) <  abs ( `Jn#`  _)\n  ```\n\n\n",
    "kind": "markdown"
  }
}
```

The markdown is

<pre>

```haskell
Integer
```

*Defined in ‘GHC.Integer.Type’*

Invariant:  `Jn#`  and  `Jp#`  are used iff value doesn't fit in  `S#` 

Useful properties resulting from the invariants: 
+ ```haskell
  abs ( `S#`  _) <= abs ( `Jp#`  _)
  ```

+ ```haskell
  abs ( `S#`  _) <  abs ( `Jn#`  _)
  ```

</pre>

Emacs renders these as

HIE
![hie-hover](https://user-images.githubusercontent.com/409607/81342423-20a96080-90ab-11ea-9acf-5e6cf4b728ea.png)

HLS
![hls-hover](https://user-images.githubusercontent.com/409607/81342440-2bfc8c00-90ab-11ea-950d-d63f094b88df.png)

The main problem seems to be that the <pre>```haskell</pre> markup needs to be against the left margin, which is not the case for hls.

**Comment by mpickering** [comment]
It is because lists are indented by ghcide. 

https://github.com/mpickering/ghcide/blob/hls/src/Development/IDE/Spans/Common.hs#L126

**Comment by jneira** [comment]
@alanz this one could be closed by #99?

**Comment by alanz** [comment]
@jneira I actually think #99 has got lost in the meantime. The Hover info is still not great on emacs, but I have not got round to taking a look again.

**Comment by alanz** [comment]
Current master (066ce8b94f3be66a011818f748ecb6c6ab7974b8) gives me

![image](https://user-images.githubusercontent.com/409607/94203700-c7a26380-feb7-11ea-9cb5-3d5c2b0f3837.png)

The red is my emacs highlighting trailing whitespace

**Comment by michaelpj** [comment]
I'm going to close this as it's very old and unclear if it still is a problem.
